### ISSUE TITLE
does gin have filters ?  like JavaWeb filters

### ISSUE THREAD

**Issue by qingbozhang** [gin-gonic/gin#1005]
does gin have filters ?  like Java Web

**Comment by javierprovecho** [comment]
@qingbozhang maybe something like `groups` helps you https://github.com/gin-gonic/gin#grouping-routes

**Comment by easonlin404** [comment]
@qingbozhang yes, just using [using-middleware](https://github.com/gin-gonic/gin#using-middleware), and you also can use [custom-middleware](https://github.com/gin-gonic/gin#custom-middleware) like java filer or interceptor.

**Comment by qingbozhang** [comment]
Thanks for everyone
