### ISSUE TITLE
why use github.com/json-iterator/go

### ISSUE THREAD

**Issue by robscc** [gin-gonic/gin#1008]
i have occurred an error in using json-iterator
https://github.com/json-iterator/go/issues/129

**Comment by tboerger** [comment]
We have integrated it because it's faster than the stdlib

**Comment by taowen** [comment]
sorry about the bug, I will it as soon as possible. Test coverage is our recent focus.

**Comment by taowen** [comment]
should be fixed now, you need to use the latest master branch. The map key is read from the buffer without copy, which caused this bug.

**Comment by appleboy** [comment]
fix from https://github.com/json-iterator/go/commit/bd4364ab7c76bfcd12959af1c1e2327408690d4a Thanks @taowen

**Comment by javierprovecho** [comment]
awesome, thanks @taowen 😄

**Comment by taowen** [comment]
@javierprovecho @appleboy thanks for choosing jsoniter. There are bugs for sure, I can only promise to fix  them as soon as I can.

**Comment by codedance** [comment]
jsoniter also does not seem to work on Google App Engine (use of unsafe).  One option may be to enable/disable this via build tags.

**Comment by taowen** [comment]
jsoniter is based on unsafe.Pointer which seems not allowed by GAE. build tags is an option.

**Comment by codedance** [comment]
Wow.  Nice work with jumping on this so quick.  I think refactoring to enable via a built-tag is the right idea.  It allows evolution and innovation, while reducing the risk by giving it time to bake.

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/gin/pull/1026
