### ISSUE TITLE
More details on bindJSON() documentation

### ISSUE THREAD

**Issue by nidhind** [gin-gonic/gin#1014]
_First of all thanks for this awesome project thats so much useful_
In your example 
```
 // Binding from JSON 
  type Login struct {
	User     string `form:"user" json:"user" binding:"required"`
	Password string `form:"password" json:"password" binding:"required"`
  }
```
 we can see a field `binding:"required"` but it seems like not documented. Could you please update the doc to include what are the _other_ supported options.

Also I 'am new to Go, so don't know if this is stupid, but why does the elements of the Login struct must start with a _capital_ letter?

**Comment by cch123** [comment]
Gin uses https://github.com/go-playground/validator as its validator, you can find detailed docs on that project page

**Comment by nidhind** [comment]
@cch123 Thanks.
