### ISSUE TITLE
I have some doubts about "gin/examples/graceful-shutdown/graceful-shutdown/server.go"

### ISSUE THREAD

**Issue by guobingithub** [gin-gonic/gin#1016]
@appleboy hi, I have some doubts about your code of "gin/examples/graceful-shutdown/graceful-shutdown/server.go". when i run this code, and send a signal as "kill -2 9604" (note that, 9604 is the pid, 2 is the interrupt signal), but there has no any log information shown on the pc screen. But in your code, when interrupt signal is emit, there would show logs, like log.Println("Shutdown Server ..."), log.Println("Server exist").  So can you help me with this doubt? thanks a lot.

**Comment by appleboy** [comment]
What is your os? The example is working for me on MacOS.

```
```

**Comment by guobingithub** [comment]
my os is win10, and my develop tools include vscode and git bash, does this matter?
my cmd is "kill -2 9604"

**Comment by appleboy** [comment]
@guobingithub I just execute the command `kill -2 $(PID)`

**Comment by appleboy** [comment]
@guobingithub Maybe you can try it out on Linux machine.

**Comment by guobingithub** [comment]
@appleboy ok, i got it. Thank you very match.
