### ISSUE TITLE
c.SaveUploadedFile undefined

### ISSUE THREAD

**Issue by k0fi** [gin-gonic/gin#1025]
When I try[ this snippet](https://github.com/gin-gonic/gin/blob/master/examples/upload-file/single/main.go):

```go
 		// Source
 		file, err := c.FormFile("file")
 		if err != nil {
 			c.String(http.StatusBadRequest, fmt.Sprintf("get form err: %s", err.Error()))
 			return
 		}
 
 		if err := c.SaveUploadedFile(file, file.Filename); err != nil {
 			c.String(http.StatusBadRequest, fmt.Sprintf("upload file err: %s", err.Error()))
 			return
 		}
```

I get this compile time error:

> c.SaveUploadedFile undefined (type *gin.Context has no field or method SaveUploadedFile)

so the doc needs revision, or I'm missing something?

**Comment by appleboy** [comment]
@k0fi Please update Gin to the latest version and try the following example:

https://github.com/gin-gonic/gin/blob/master/examples/upload-file/single/main.go

**Comment by k0fi** [comment]
I updated gin but I still get the same error. Here is my code:

```
func PostArticle(c *gin.Context) {
	var err error
	userId, userName := getUserId(c)
	title := c.PostForm("title")
	content := c.PostForm("content")

	file, err := c.FormFile("file")
	if err != nil {
		c.String(http.StatusBadRequest, fmt.Sprintf("get form err: %s", err.Error()))
		return
	}

	if err := c.SaveUploadedFile(file, file.Filename); err != nil {
		c.String(http.StatusBadRequest, fmt.Sprintf("upload file err: %s", err.Error()))
		return
	}
...

```

Error message:

>  c.SaveUploadedFile undefined (type *gin.Context has no field or method SaveUploadedFile)


Any ideas why this happen?

**Comment by javierprovecho** [comment]
@

**Comment by javierprovecho** [comment]
@k0fi can you post the commit hash of your gin copy? you should be on latest version with `go get -u github.com/gin-gonic/gin`. Also make sure you are using GitHub and not gopkg import tag.

**Comment by easonlin404** [comment]
@k0fi Please use the -u flag  to get the latest version (master branch) 
```
go get -u github.com/gin-gonic/gin
```

**Comment by k0fi** [comment]
@javierprovecho
I used `go get -u github.com/gin-gonic/gin` and I'm importing from github: `"github.com/gin-gonic/gin"`
How can i get the commit hash?

**Comment by javierprovecho** [comment]
@k0fi `git -C $GOPATH/src/github.com/gin-gonic/gin rev-parse HEAD`

**Comment by k0fi** [comment]
git -C $GOPATH/src/github.com/gin-gonic/gin rev-parse HEAD
8f861946b028a0b5ed4acf8df4b673e23e8c5634

**Comment by k0fi** [comment]
It worth mentioning, even if I comment out the file retrial part,the text form fields are empty.
That is I get no value for `title`, `content`.

**Comment by javierprovecho** [comment]
@k0fi do a 
`rm -rf $GOPATH/pkg/*`
to clean cached compilations

**Comment by k0fi** [comment]
@javierprovecho  
My problem is solved. Thanks!
Just wondering how to assign a path to save the file? Currently it saves it at the project's root, which is not good.

**Comment by k0fi** [comment]
I get this issue again, this time on my server. 
Here are the details:

My code works fine on my Computer but I get this compile time error on my server after I moved the code to the debian vps: 

    type *gin.Context has no field or method SaveUploadedFile

I have upgraded go to 1.8.3 on the server (to be of the same version as go on my desktop) and updated gin afterwards, hoping to solve the issue. But it did not.

git -C $GOPATH/src/github.com/gin-gonic/gin rev-parse HEAD
6613cdbf74a2597c335b6f34bc7722fbbd4588e5


Here is my `go env`:

    root@s1:~# go env
    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/srv/go"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="1"
    PKG_CONFIG="pkg-config"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"

I tried with no avails:

    rm -rf $GOPATH/pkg/*

 I also tried  `go build -a` but get the same error.

So I'm left clueless and appreciate your hints to solve this issue.


  [1]: https://github.com/gin-gonic/gin/blob/master/examples/upload-file/single/main.go

**Comment by javierprovecho** [comment]
@k0fi the commit you posted was from develop branch, please be sure you are `go-getting` from `github.com/gin-gonic/gin`

`*gin.Context.SaveUploadedFile()` is only available on master branch, not on 1.2 version

**Comment by mrichman** [comment]
`gin.Context.SaveUploadedFile()` was added on July 15. Maybe it's time for a new release tag?

**Comment by appleboy** [comment]
@mrichman Try to fetch the latest code using vendor tool like `govendor`

**Comment by ryanbmilbourne** [comment]
Any update on a new release tag?  `dep` is by default only pulling `^1.2.0`.  I had to modify my `toml` file with a `branch="master"` constraint to fetch the code committed since the 1.2 release was tagged on 2 July.

**Comment by motleycrew** [comment]
same issue here. using dep. It fetches 1.2.0

**Comment by appleboy** [comment]
@motleycrew Try the master branch.
