### ISSUE TITLE
Work with Static File,route '*filepath' conflicts

### ISSUE THREAD

**Issue by housirvip** [gin-gonic/gin#1044]
```go
engine.Static("/", "dist")
user := engine.Group("/user")
user.POST("/login", handler.Login)
user.POST("/reg", handler.Register)
user.GET("/sub", handler.Subscribe)
```

```
panic: path segment '/user/sub' conflicts with existing wildcard '/*filepath' in path '/user/sub'
```

Then ,if I delete all GET method route , it work good.
So ,how to use gin with angular2 gracefully? Thank you very much

**Comment by housirvip** [comment]
sorry,I copied with an error , corrected bellow
panic: path segment '/user/sub' conflicts with existing wildcard '/*filepath' in path '/user/sub' 
GET method may be work with static file

**Comment by javierprovecho** [comment]
`engine.Static` is designed for paths like `/static`, not a root path combined with other handlers.

you should use static middleware, see its example 😃 
https://github.com/gin-contrib/static#canonical-example

```
r.Use(static.Serve("/", static.LocalFile("/tmp", false)))
```
