### ISSUE TITLE
How do you solve vue.js HTML5 History Mode?

### ISSUE THREAD

**Issue by boneq** [gin-gonic/gin#1048]
https://router.vuejs.org/en/essentials/history-mode.html

How do you solve vue.js HTML5 History Mode?

**Comment by javierprovecho** [comment]
@boneq As the vuejs docs say, returning the `index.html` of your web app when no other route is matched, is the way to go. It can ve achieved like below:

```go
r.Use(static.Serve("/", static.LocalFile("/src", false)))
r.NoRoute(func(c *gin.Context){
    c.File("/src/index.html")
})
```

**Comment by javierprovecho** [comment]
PD: static is the middleware from https://github.com/gin-contrib/static

**Comment by boneq** [comment]
OK, I'll try it
