### ISSUE TITLE
AbortWithStatusJSON and JSON returns wrong response headers

### ISSUE THREAD

**Issue by mymtw** [gin-gonic/gin#1053]
## gin latest version. 1.2
1) Need to add docs how to use ctx method `AbortWithStatusJSON`
```
	var ucr messages.UsersCreateRequest
	if e := c.BindJSON(&ucr); e != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{
			"errors": "someError",
		})
	}
        fmt.Println(1)
```
response should be `application/json; charset=utf-8` BUT it gives `content-type == 'text/plain; charset=utf-8'`

1. 1 I thought I will not need to write `return` If I will use AbortWithStatusJSON.

2) I'm getting in response headers `content-type == 'text/plain; charset=utf-8'` even if I using c.JSON:
```
	var ucr messages.UsersCreateRequest
	if e := c.BindJSON(&ucr); e != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"errors": "bsalslasalksaslas"
		})
		return
	}
```

**Comment by appleboy** [comment]
This PR https://github.com/gin-gonic/gin/pull/1047 can resolve this issue.

**Comment by appleboy** [comment]
https://github.com/gin-gonic/gin/issues/1041#issuecomment-319125864 can resolve your problem.

**Comment by mymtw** [comment]
I need to use this?
`err := c.ShouldBindWith(&data, binding.JSON) //instead of  c.Bind(&data)`
how this differs from 
`e := c.BindJSON(&ucr)`
which looks as:
```
func (c *Context) BindJSON(obj interface{}) error {
	return c.MustBindWith(obj, binding.JSON)
}
```
which calls 
```
func (c *Context) MustBindWith(obj interface{}, b binding.Binding) (err error) {
	if err = c.ShouldBindWith(obj, b); err != nil {
		c.AbortWithError(400, err).SetType(ErrorTypeBind)
	}

	return
}
```
?

**Comment by mymtw** [comment]
@appleboy thank you, works.
I'm closing this issue and:
I didn't find in README.md (docs) anything about using this `ShouldBindWith`.
it will be better to update the doc, even the note like `if you wanna get content-type == 'application/json' in response, then you need to use c.ShouldBindWith(&something, binding.JSON); instead of c.BindJSON`.
Cuz, on my frontend I'm checking content-type in response, in my tests on backend not. Frontend didn't work correctly for me.
Thx
