### ISSUE TITLE
Automatic Time pars

### ISSUE THREAD

**Issue by almgwary** [gin-gonic/gin#1062]
i am sending time in `time.RFC3339` format it has the following problem with automatic binding.

my modle

```go
type MyModel struct {
	From   time.Time   `form:"from" json:"from"`
}
```
binding 

```go
var myModel MyModel 
context.Bind(&myModel)
```

error `"parsing time ""2017-08-16P15:00:00+00:00"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "P15:00:00+00:00"" as "T"" `

How to setup automatic binding to use format   `time.RFC3339` ?
i cannot find any middle-ware configuration

**Comment by easonlin404** [comment]
@almgwary Could you please post your example code?
Because json accepted RFC 3339 in Go if you binding with json content type.  Like following date-string:
```
2002-10-02T10:00:00-05:00

2002-10-02T15:00:00Z

2002-10-02T15:00:00.05Z
```

**Comment by ckybonist** [comment]
I also encountered a similar problem, please check out my [example code](https://play.golang.org/p/OjJeW1_5ao).

In the example code, I need to manually add `time.RFC3339` format to `time_format` field tag, otherwise Gin will throw an error: `Blank time format`.

But adding these field tag makes my struct definition cumbersome:
```
type struct Question {
    Title string `json:"title" form:"title"`
    CreatedAt time.Time `json:"createdAt" form:"createdAt" time_format:"2006-01-02T15:04:05Z07:00"`
}
```
NOTE: "2006-01-02T15:04:05Z07:00" is just the [time.RFC3339](https://golang.org/pkg/time/#pkg-constants)

Any workarounds to solve this problem?

**Comment by thinkerou** [comment]
Hi all, please #1487 thanks!

**Comment by liulwx** [comment]
> I also encountered a similar problem, please check out my [example code](https://play.golang.org/p/OjJeW1_5ao).
> 
> In the example code, I need to manually add `time.RFC3339` format to `time_format` field tag, otherwise Gin will throw an error: `Blank time format`.
> 
> But adding these field tag makes my struct definition cumbersome:
> 
> ```
> type struct Question {
>     Title string `json:"title" form:"title"`
>     CreatedAt time.Time `json:"createdAt" form:"createdAt" time_format:"2006-01-02T15:04:05Z07:00"`
> }
> ```
> NOTE: "2006-01-02T15:04:05Z07:00" is just the [time.RFC3339](https://golang.org/pkg/time/#pkg-constants)
> 
> Any workarounds to solve this problem?

In fact, I am confused by the same problem. How did you solved this problems?
