### ISSUE TITLE
Issue on BindJSON method

### ISSUE THREAD

**Issue by sabloger** [gin-gonic/gin#1066]
Hi,
When using BindJson on a http request data, if data types of defined struct fields be different from http body data field type, Gin will set that field and all of next fields empty!!!!
Please resolve this issue, set only that fields empty of on better way do Panic!  

Thanks

**Comment by thinkerou** [comment]
Maybe you should have some example codes, thanks!

**Comment by thinkerou** [comment]
@sabloger Now it's panic, like: `{"errors":{"modelA":"json: cannot unmarshal string into Go struct field modelA.bar of type int64","modelB":"EOF"}}`, closing. thanks!
