### ISSUE TITLE
how to set gin access log to file

### ISSUE THREAD

**Issue by Ywmet** [gin-gonic/gin#1069]
How to write gin access log to file without  shell redirect。

**Comment by KISSMonX** [comment]
https://github.com/gin-gonic/gin/issues/602

https://github.com/gin-gonic/gin/issues/255

**Comment by thinkerou** [comment]
@Ywmet Please read readme https://github.com/gin-gonic/gin#output-log-to-file

**Comment by robvdl** [comment]
I notice some bad spelling in the README there:

// Disable Console Color, because not need color when output log to file

"because not need color when output" is not proper English

**Comment by appleboy** [comment]
@robvdl PR welcome. Thanks.
