### ISSUE TITLE
upload image processing using gin

### ISSUE THREAD

**Issue by badoet** [gin-gonic/gin#107]
do gin have a feature to handle multipart form post upload?

**Comment by whidbey** [comment]
dont know what's the plan for the image upload .i am trying to do as above and use c.Request.Formfile("image") ,which may not so convinence.

**Comment by nazwa** [comment]
I use the following stuff, just like @badoet suggested and it works super fine. 
```
file, _, err := c.Request.FormFile("file")
x, _, err := image.Decode(file)
// Do something with the image + error handling for above 2 
jpeg.Encode(f, file, &settings)
```

**Comment by whidbey** [comment]
@nazwa and your settings detail?

**Comment by nazwa** [comment]
Anything you want really. In my case it's 
```
settings := jpeg.Options{Quality: 80}
```

**Comment by whidbey** [comment]
@nazwa thankyou
