### ISSUE TITLE
GetHeader is case-sensitive where Header.Get isn't

### ISSUE THREAD

**Issue by JorritSalverda** [gin-gonic/gin#1079]
Changing from my original implementation that retrieved a header directly from a request to the `GetHeader` function failed because it turned out that my casing for the header wasn't correct - the h should be lowercase; the `Header.Get` implementation tolerated that however.

Old working code

```
eventType := c.Request.Header.Get("X-GitHub-Event")
```
New failing code

```
eventType := c.GetHeader("X-GitHub-Event")
```

Wouldn't it make sense to make the retrieval case insensitive? I think different casing for headers is actually pretty common.

**Comment by thinkerou** [comment]
Hi, @JorritSalverda I use the following code that is OK:

    r.GET("/ping", func(c *gin.Context) {
		h := c.GetHeader("Upgrade-Insecure-Requests")
		//h := c.Request.Header.Get("User-Agent")
		c.String(200, h)
	})

I think you should check `X-GitHub-Event` in Request-Header, like this:

![image](https://user-images.githubusercontent.com/4488261/29696648-e0b2e132-897c-11e7-8c4c-98bcc7ad3936.png)

**Comment by dmarkham** [comment]
@thinkerou  It's all about `textproto.CanonicalMIMEHeaderKey()` that the Standard Library uses to normalize it's header keys.  `X-GitHub-Event` fails because it's going to get stored in `http.request.headers`  as `X-Github-Event`  #1081  will fix this.
