### ISSUE TITLE
r.group not working

### ISSUE THREAD

**Issue by RoelVanNyen** [gin-gonic/gin#108]
I made a quick test with custom middleware groups:

```go
func TestHandle() gin.HandlerFunc {
    return func(c *gin.Context) {
        fmt.Printf("TEST: \n" )

        c.Next()

        fmt.Printf("TEST2: \n" )
    }
}

 r.Group("/", TestHandle()) {
    	r.GET("/test", func(c *gin.Context) {
    		fmt.Printf("test")
    		c.String(200, "ok")
    	})
}
```

TEST and TEST2 never gets printed.

I do get a warning:
[GIN] WARNING. Headers were already written!

Any ideas ?

**Comment by javierprovecho** [comment]
@RoelVanNyen sorry for the delay

Pretty sure your warning about headers is related because you write to the response before trying to redirect.
