### ISSUE TITLE
How to use BindJson with custom headers?

### ISSUE THREAD

**Issue by aghasoroush** [gin-gonic/gin#1091]
I try to use ``c.BindJson`` for validation but it forces me to send `400` status code and `plain text` content type. Is there any way to send custom header/response with it?
  
If no, I can add it to the framework and send a merge request. Let me know.
Thanks in advance.

**Comment by easonlin404** [comment]
@aghasoroush Could you please post your example code?

**Comment by aghasoroush** [comment]
@easonlin404 
```go
package main

import (
    "fmt"
    "github.com/gin-gonic/gin"
    "http"
)

func main() {
    router := gin.Default()

    type testReq struct {
        name string `form:"name" json:"name" binding:"required"`
    }

    router.POST("/test", func (c *gin.Context) {
        var json testReq
        if validationErr := c.BindJson(&json); validationErr == nil {
            c.JSON(http.StatusOK, gin.H{
                "name": json.Name,
            })
        } else {
            //This is what I'm talking about :)
            c.JSON(422, gin.H {
                "validationError": validationErr.Error()
            })
        }
    })
}
```

First of all, sorry if there is any syntax error in my code, I wrote it on the fly...
As you know, `BindJson` terminates the chain with 400 error while the status code is 422 for validation errors and I can't send my desired status code...

**Comment by aghasoroush** [comment]
@easonlin404  Thank you. Fixed.
