### ISSUE TITLE
Unable to use Number validator

### ISSUE THREAD

**Issue by benmoss** [gin-gonic/gin#1093]
Hi,

It's possible I just don't understand how to use the validations correctly, but I am trying to bind this form object:

```
type Form struct {
   Age int `binding:"required,number"`
}
```

but when testing supplying a string value in the form submission, it errors with an `strconv.Atoi` error instead of providing a validation error. It looks like it's failing when converting the data into my Form type, instead of first validating it.

Is there a recommended pattern for handling this? Using a `interface{}` or `string` for what should be an `int` field doesn't seem ideal.

**Comment by aghasoroush** [comment]
@benmoss Could you please provide the code you're trying to run?

**Comment by benmoss** [comment]
Here's code that reproduces the problem, I believe:

```
type Login struct {
	User     string `form:"user" json:"user" binding:"required"`
	Password int    `form:"password" json:"password" binding:"required,number"`
}

func main() {
	router := gin.Default()

	// Example for binding JSON ({"user": "manu", "password": "123"})
	router.POST("/loginJSON", func(c *gin.Context) {
		var json Login
		if err := c.BindJSON(&json); err != nil {
			panic(err)
		}
		if json.User == "manu" && json.Password == 123 {
			c.JSON(http.StatusOK, gin.H{"status": "you are logged in"})
		} else {
			c.JSON(http.StatusUnauthorized, gin.H{"status": "unauthorized"})
		}
	})

	// Listen and serve on 0.0.0.0:8080
	router.Run(":8080")
}
```

And here are my results from running it:
https://gist.github.com/benmoss/d66516bb70116f8504161c308084ea6b

**Comment by aghasoroush** [comment]
@benmoss Have you tried what I told? `numeric` is the correct tag but you are using `number`.

**Comment by thinkerou** [comment]
@benmoss 
If you change the follow code:

    type Login struct {
	    User     string `form:"user" json:"user" binding:"required"`
	    Password int    `form:"password" json:"password" binding:"required,number"`
    }

to:

    type Login struct {
	    User     string `form:"user" json:"user" binding:"required"`
	    Password int    `form:"password" json:"password" binding:"required"`
    }

right?

**Comment by appleboy** [comment]
@aghasoroush I try your solution but got the same error. maybe you can help to try the following example:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

type Login struct {
	User     string `form:"user" json:"user" binding:"required"`
	Password int    `form:"password" json:"password" binding:"required,numeric"`
}

func main() {
	router := gin.Default()

	// Example for binding JSON ({"user": "manu", "password": "123"})
	router.POST("/loginJSON", func(c *gin.Context) {
		var json Login
		if err := c.BindJSON(&json); err != nil {
			fmt.Println(err)
		}
		if json.User == "manu" && json.Password == 19 {
			c.JSON(http.StatusOK, gin.H{"status": "you are logged in"})
		} else {
			c.JSON(http.StatusUnauthorized, gin.H{"status": "unauthorized"})
		}
	})

	// Listen and serve on 0.0.0.0:8080
	router.Run(":8080")
}
```

**Comment by appleboy** [comment]
@aghasoroush @benmoss Please try the following solution.

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

type Login struct {
	User     string `form:"user" json:"user" binding:"required"`
	Password int    `form:"password" json:"password" binding:"required,numeric"`
}

func main() {
	router := gin.Default()

	// Example for binding JSON ({"user": "manu", "password": "123"})
	router.POST("/loginJSON", func(c *gin.Context) {
		json := new(Login)
		if err := c.BindJSON(&json); err != nil {
			fmt.Println(err)
		}
		if json.User == "manu" && json.Password == 19 {
			c.JSON(http.StatusOK, gin.H{"status": "you are logged in"})
		} else {
			c.JSON(http.StatusUnauthorized, gin.H{"status": "unauthorized"})
		}
	})

	// Listen and serve on 0.0.0.0:8080
	router.Run(":8080")
}
```

changes:

```diff
- var json Login
+ json := new(Login)
```

**Comment by benmoss** [comment]
@appleboy this solution still gives you a `json.UnmarshalTypeError` rather than a validation error. What's failing is `json.Unmarshal`, and the `numeric` validation has no effect.

**Comment by aghasoroush** [comment]
@appleboy benmoss is right.

**Comment by cch123** [comment]
json value has types, if your value is quoted in "
then the std json lib cannot umarshal it to int value and report error
details can be refered from json rfc
form request value has no types, they are all passed by string, so it is why your json request failed to bind but form request success

If you want to successful bind Json to your struct, change Json to 
{"user": "abc", "password":44323}

From
{"user":"abc","password":"44323"}

**Comment by benmoss** [comment]
@cch123 yes, I think that for the JSON case the problem is that you need to unmarshal before validation can happen, but that Go's strict JSON parser will fail. The only options I see here would be to use an alternate parser like jsoniter or to wrap JSON errors in validation errors, trying to present a more uniform API of error types for the developer to handle.

I think the form data case is actually easier, since we can apply all the validations to the string types of the form data *before* unmarshaling them. Right now the unmarshaling happens first, resulting in a `strconv` errors in this case.

**Comment by cch123** [comment]
@benmoss , no matter which type(json/form/msgpack/pb) of binding you are using, bind behavior happens before validation, you can read the binding part of gin's code to confirm that. eg, form binding:
```go
func (formPostBinding) Bind(req *http.Request, obj interface{}) error {
	if err := req.ParseForm(); err != nil {
		return err
	}
	if err := mapForm(obj, req.PostForm); err != nil { // ===> bind here
		return err
	}
	return validate(obj) // ===> validate here
}
```

The form type binding didn't fail, is just because form request data have no type, the form decoder will do the conversion for you. But the json decoder will not.

**Comment by torkelrogstad** [comment]
Sorry for bumping this old and closed issue, but I'm running into the same problem here. I'm getting a `strconv.ParseInt` error, which doesn't tell me anything about which field failed validation (which is bad, because I want to show the users of my API which field was invalid). 

From @benmoss:
> The only options I see here would be to use an alternate parser like jsoniter or to wrap JSON errors in validation errors, trying to present a more uniform API of error types for the developer to handle.

I think exactly that is a very good idea, and would go a long way towards solving this problem .

**Comment by ericleb010** [comment]
Also running into this issue. This renders using the validator almost pointless because there is still a need to dissect what was invalid with the request when it was malformed in a specific way. We also want to use translations to provide user-friendly messages for _all_ input errors.

I too like the idea of standardising all of the errors coming out of the `Bind` functions as much as possible to `ValidationErrors`.

**Comment by jinjiangcc** [comment]
err := context.BindQuery(&p)   is work
err := context.ShouldBindQuery(&p) is not work

**Comment by appcypher** [comment]
@benmoss  Can this issue be opened again since this problem hasn't been resolved yet?
I will have to create a new one otherwise.

BTW, was anyone able to find a workaround for this?  I would really hate to send cryptic error messages to the users.

**Comment by qbiqing** [comment]
Same, will be helpful to have `ValidationErrors` for `strconv` types

**Comment by Mohanbarman** [comment]
@appcypher you can change the type of `int` field to `string` then `number` binding will work as expected. You can convert the string to int afterwards. Here's an example
```go
type RegisterDTO struct {
	Age  string `json:"limit" form:"limit" binding:"number"`
}
```

**Comment by shushenghong** [comment]
please reopen, if a field defined as int, and client send a string like "abc", it will comeout `strconv.ParseInt: parsing "abc": invalid syntax`, not validation error

**Comment by shushenghong** [comment]
i suggest if a field parse value fail, set to the zero value of the golang type, like int default to 0, then we can add other validate tags such as  `min` `max` `ne` to validate

**Comment by jackbaron** [comment]
@shushenghong you got a solution for this?

**Comment by shushenghong** [comment]
> 

no, i will try to send a PR for this latter

**Comment by Oranzh** [comment]
Please  reopen this issue!

**Comment by emarais-godaddy** [comment]
A slight workaround for this is to switch on error types. Pass int he universal translator and the errors from `ShouldBind`.

```go
type ListRequest struct {
	Limit int    `form:"limit,default=20" binding:"numeric,gt=0,lte=100"`
	Sort  string `form:"sort,default=created_at" binding:"db_field"`
	Order string `form:"order,default=desc" binding:"oneof=asc desc"`
	Page  int    `form:"page,default=1" binding:"numeric,gt=0"`
}

if err := c.ShouldBind(&req); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, response.ValidationErrorResponse{
			Status: response.StatusValidation,
			Errors: request.ParseBindErrors(err),
		})

		return
	}
```

```go

type ValidationError struct {
	Message   string `json:"message" example:"Field can only contain alphabetic characters"`
	FieldName string `json:"field_name,omitempty" example:"snake_case_field_name"`
}

func ParseBindErrors(err error, trans ut.Translator) []ValidationError {
	var errs []ValidationError

	switch v := err.(type) { //nolint:errorlint
	case validator.ValidationErrors:
		// For internal gin validation errors from the bound request context, we can hook into the translation
		// for better error messages
		validationErrs := err.(validator.ValidationErrors) //nolint:errorlint

	        for _, e := range validationErrs {
		        validationError := ValidationError{
			        Message:   e.Translate(trans),
			        FieldName: strcase.ToSnake(e.Field()),
		        }

		        errs = append(errs, validationError)
	        }
	case *strconv.NumError:
		errs = []ValidationError{
			{
				Message: fmt.Errorf("error validating request, failed to convert: %w", err).Error(),
			},
		}
	default:
		// Default to a generic error response
		errs = []ValidationError{
			{
				Message: fmt.Errorf("error validating request: %w", err).Error(),
			},
		}
	}

	return errs
}
```

Even just adding a default statement will help with the untranslated validation error.

**Comment by egege** [comment]
Is there a solution now? I am currently using version 1.10

**Comment by QingShan-Xu** [comment]
Same question

**Comment by wwaayyaa** [comment]
same question, need a friendly readable error info.
