### ISSUE TITLE
/user/:name/*action  error action

### ISSUE THREAD

**Issue by a57571735** [gin-gonic/gin#1095]
// However, this one will match /user/john/ and also /user/john/send
	// If no other routers match /user/john, it will redirect to /user/john/
	router.GET("/user/:name/*action", func(c *gin.Context) {
		name := c.Param("name")
		action := c.Param("action")
		message := name + " is " + action
		c.String(http.StatusOK, message)
	})
name is john but action is /send why with '/'?

**Comment by appleboy** [comment]
```diff
-router.GET("/user/:name/*action", func(c *gin.Context) {
+router.GET("/user/:name/:action", func(c *gin.Context) {
	name := c.Param("name")
	action := c.Param("action")
	message := name + " is " + action
	c.String(http.StatusOK, message)
})
```

right?

**Comment by appleboy** [comment]
closed this issue. Please feel free to reopen the issue if you have the same problem.
