### ISSUE TITLE
Run with custom TLSConfig

### ISSUE THREAD

**Issue by hryamzik** [gin-gonic/gin#1099]
Is it even possible? With bare http:

```go
server := http.Server{
    Addr:      cfg.ListenHttps,
    Handler:   http.HandlerFunc(handler),
    TLSConfig: tlsConf,
}
server.ListenAndServeTLS("", "")
```

**Comment by aghasoroush** [comment]
@hryamzik Yes it is possible. You can find it here : https://golang.org/pkg/net/http/#Server.ListenAndServeTLS

> Filenames containing a certificate and matching private key for the server must be provided if neither the Server's TLSConfig.Certificates nor TLSConfig.GetCertificate are populated

**Comment by hryamzik** [comment]
@aghasoroush I'm able to do this with `net.http`, the question is how to serve in the same way with gin?

**Comment by thinkerou** [comment]
Hi @hryamzik [the example](https://github.com/gin-gonic/gin/blob/master/examples/http2/main.go)?

**Comment by hryamzik** [comment]
@thinkerou actually the question is how to run with multiple certificates, like [here](https://github.com/Guidewire/sni-proxy/blob/master/sni-proxy.go#L153).

**Comment by szechyjs** [comment]
I'm looking to do the same thing. `RunTLS` uses `http.ListenAndServeTLS ` which does not allow for the setting of `TLSConfig`.

https://github.com/gin-gonic/gin/blob/master/gin.go#L290

It would be nice if `RunTLS` used the `Server.ListenAndServeTLS` variant so that `TLSConfig` can be set.

https://golang.org/pkg/net/http/#Server.ListenAndServeTLS

Without this it's impossible to set `ClientAuthType` for TLS Client Authentication.

**Comment by thinkerou** [comment]
@hryamzik because `ServeTLS` only set one cert/key pair, it not support multiple certificates, see:
https://github.com/golang/go/blob/master/src/net/http/server.go#L2786

**Comment by hryamzik** [comment]
@thinkerou it's actually possible with [net/http](https://stackoverflow.com/questions/32175300/http-listenandservetls-with-multiple-certificates)

**Comment by sheepbao** [comment]
I think you can do this code like in main function:
```go
    r := gin.Default()
    server := http.Server{
		Addr:      addr,
		Handler:   r,
		TLSConfig: tlsConfig,
    }
    err = server.ListenAndServeTLS("", "")
}
```

**Comment by hryamzik** [comment]
Can't check right now but if gin can be just set as a handler that should work, thanks!
