### ISSUE TITLE
c.Query can not get right value sometime

### ISSUE THREAD

**Issue by witwave** [gin-gonic/gin#1102]
my query string is 

i use the log.Println(c.Request.URL.RawQuery)
can output, the user agent  is encodeURI string
userAgent=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_12_6)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/60.0.3112.113%20Safari/537.36

but   
userAgent := c.Query("userAgent")
log.Println("userAgent",userAgent)

output is 
userAgent Mozilla/5.0 (Macintosh

i don't know why?

**Comment by thinkerou** [comment]
Are you sure it will output `Mozilla/5.0 (Macintosh`??
`Query` returns the keyed url query value, you should use `c.GetHeader("User-Agent")` about UA.
please read here: https://github.com/gin-gonic/gin/blob/master/context.go#L308

**Comment by witwave** [comment]
Yes, I am sure, in my computer.

I write some js code to report the  pv  uv and some info in web client



(function(){
    var params={};

    if (document){
        params.domain = document.domain || '';
        params.url = document.URL || '';
        params.title =document.title || '';
        params.referrer =document.referrer || '';
    }
    if (window && window.window){
        params.sh=window.screen.height || 0;
        params.sw=window.screen.width || 0;
        params.cd=window.screen.colorDepth || 0;
    }

    if (navigator) {
        params.userAgent = navigator.userAgent || '';
        params.platform = navigator.platform || '';
        params.language = navigator.language || '';
    }

    params.sid="{{.sid}}"
    params.uid="{{.uid}}"

    var args=[];

    for(var i in params){
        args.push(i+'='+ encodeURI(params[i]));
    }
    var img=new Image(1,1);
    img.src="http://localhost:8080/api/report?"+args.join('&');

})()


Here is golang code

log.Println(c.Request.URL.RawQuery)

sid := c.DefaultQuery("sid", "")
uid := c.DefaultQuery("uid", "")
ip := c.Request.RemoteAddr

domain := c.DefaultQuery("domain", "")
url := c.DefaultQuery("url", "")
title := c.DefaultQuery("title", "")
referrer := c.DefaultQuery("referrer", "")
sh := c.DefaultQuery("sh", "0")
sw := c.DefaultQuery("sw", "0")
cd := c.DefaultQuery("cd", "0")

userAgent := c.Query("userAgent")
platform := c.DefaultQuery("platform", "")
language := c.DefaultQuery("language", "")

log.Println("userAgent", userAgent)

Here is the output log

domain=daocms.io<http://daocms.io>&url=http://daocms.io/wordpress/?p=4&title=dao%20cms%20%E2%80%93%20blog&referrer=http://daocms.io/wordpress/&sh=1080&sw=2560&cd=24&userAgent=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_12_6)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/60.0.3112.113%20Safari/537.36&platform=MacIntel&language=zh-CN&sid=sid&uid=uid
userAgent Mozilla/5.0 (Macintosh



And then

在 2017年9月7日，下午7:47，田欧 <notifications@github.com<mailto:notifications@github.com>> 写道：

c.GetHeader("User-Agent")

**Comment by thinkerou** [comment]
OK, I have reproduced it, because your value of url query have `;`.

**Comment by witwave** [comment]
Tsk
在 2017年9月7日，下午8:23，田欧 <notifications@github.com<mailto:notifications@github.com>> 写道：

;.

**Comment by thinkerou** [comment]
Because `;` is the special character of URL [RFC](http://www.ietf.org/rfc/rfc1738.txt).
You should use `URL encode` for the query param, or not use `;`.
In a word, I think that this matter should do in client.

**Comment by witwave** [comment]
yes i do it in the javascript , i use the encodeURI to encode the value. now I use the c.GetHeader() to do it, thank you
