### ISSUE TITLE
Map as query parameter

### ISSUE THREAD

**Issue by guzmo** [gin-gonic/gin#1106]
Is Map as query parameter supported? And if it is how to use it? I tried with:

`localhost:8080?test[asd]=asd&test[dsa]=dsa`

and the code 

```
queries := c.Request.URL.Query()
// Doesn't work
log.Println(queries["test"])
// Gets the variable but not how I want it.
log.Println(queries["test[asd]"][0])
```

**Comment by picone** [comment]
You can try this
```go
context.GetQueryArray("test")
```

**Comment by tsirolnik** [comment]
Was just about to post an issue regarding this subject

@picone GetQueryArray returns an array where @guzmo request is for a map, e.g - 

```
a[]=1&a[]=2&a[]=3
```
Would fit for GetQueryArray

but

```
a[foo]=1&a[bar]=2
```
Would need a map as the result is the following map -

```go
map[string]int{
    "foo": 1,
     "bar":2,
}
```

The solution for guzmo is to use [c.GetStringMap](https://github.com/gin-gonic/gin/blob/b8b68314faa067acae5b17c828127b04af51ebe2/context.go#L271)

**Comment by syssam** [comment]
Any one know this solution?
I also have this problem on Post Form

**Comment by thinkerou** [comment]
@guzmo please see #1383 thanks!

**Comment by appleboy** [comment]
Please try the latest version and see the document https://github.com/gin-gonic/gin#map-as-querystring-or-postform-parameters
