### ISSUE TITLE
How to  recursive template files

### ISSUE THREAD

**Issue by puma007** [gin-gonic/gin#1109]
My template file path is as follows:
<img width="234" alt="2017-09-15 3 10 05" src="https://user-images.githubusercontent.com/1724962/30470774-aca75ed8-9a28-11e7-845b-e70c9e010f98.png">

The code for setting up templates is `router.LoadHTMLGlob("views/**/*")`
，but the error is `panic: read views/admin/enterprise: is a directory`
How to  recursive template files？Thanks

**Comment by zzwind** [comment]
Try router.LoadHTMLGlob("views/**/**/*")
