### ISSUE TITLE
type *gin.Engine has no field or method SetFuncMap

### ISSUE THREAD

**Issue by aragonetC** [gin-gonic/gin#1113]
I'm having this error when I'm trying to add a function to a template:
```
func main() {
        router := gin.Default()
	router.Use(gin.Logger())
	router.SetFuncMap(template.FuncMap{
	     "getData": getData,
	})
}
```
router.SetFuncMap undefined (type *gin.Engine has no field or method SetFuncMap)

I tried go get -u but nothing changes. What could be the problem?

**Comment by thinkerou** [comment]
I not reproduce the questiong, are you read the example code? https://github.com/gin-gonic/gin/blob/master/examples/template/main.go

**Comment by showmei5320** [comment]
I run this example code but result will be
`Date: {[{.now | formatAsDate}]}`

**Comment by FarahHourani** [comment]
Had the same problem and fixed it with: go get -u github.com/gin-gonic/gin 

What is your Go version?

**Comment by thinkerou** [comment]
@aragonetC please upgrade your gin version as @FarahHourani pointed, if still have problem please reopen the issue and discuss, thanks a lot~
