### ISSUE TITLE
 gin is blocked when using same browser

### ISSUE THREAD

**Issue by Larry850806** [gin-gonic/gin#1122]
### version
go: `latest(go1.9 darwin/amd64)`
gin: `latest(v1.2)`

### code

For each request, I would like to wait for five seconds and then respond `{ "message": "pong" }`

```golang
package main

import (
	"time"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	r.GET("/ping", func(c *gin.Context) {
		time.Sleep(time.Second * 5)
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})

	r.Run() // listen and serve on 0.0.0.0:8080
}
```

### what happen

In issue #968 (one request, one goroutine), It seems that each request will run in different goroutine. When I open two tabs `localhost:8080/ping` in chrome simultaneously. I expect two tabs both wait for 5 seconds and get `{ "message": "pong" }`. But the second tab wait for 10 seconds, which means the second request is not started processing until first request is finished. They aren't processed concurrently.
See the picture below, I open two tabs simultaneously. First request is finished at `11:13:21` but second request finished at `11:13:26`. They should both be finished at `11:13:21` if they run in different goroutine.
![](https://i.imgur.com/7sdqyNP.png)

### if using two different browsers

But when I use two different browsers(chrome and firefox). It works perfectly. Two requests is processed in the same time period, and they are both finished at `11:20:00`.
![](https://i.imgur.com/jzo9zjo.png)

It's very strange, Is there any clue?

**Comment by thinkerou** [comment]
Maybe the problem associate with chrome browser.
If we use two `curl` commands which can run correctly.

**Comment by NelsonKen** [comment]
keep-alive will use the same tcp connection, so : two request will be serial, so blocked is not gin's fault

**Comment by Larry850806** [comment]
@NelsonKen Chrome use the same tcp connection even if opening in two tabs?

**Comment by NelsonKen** [comment]
yes

发自我的iPhone


------------------ Original ------------------
