### ISSUE TITLE
There is no way to remove the route?

### ISSUE THREAD

**Issue by monikaYZ** [gin-gonic/gin#1124]
There is no way to remove the route?

**Comment by monikaYZ** [comment]
func (engine *Engine) RemoveRoute(path string) bool {
	for _, tree := range engine.trees {
		find("", path, tree.root, tree.root)
	}
	return true
}

func find(path, targetRoute string, root *node, org *node) {
	path += root.path
	if len(root.handlers) > 0 && strings.EqualFold(path, targetRoute) {
		//清理 handlers chain
		var hd HandlersChain
		root.handlers = hd
		return
	}
	for _, child := range root.children {
		find(path, targetRoute, child, root)
	}
}

**Comment by rfyiamcool** [comment]
@monikaYZ  I thank U delete uro route in net.http.Server handler struct.

**Comment by tsirolnik** [comment]
We can't understand your problem this way
* Format your code with the Go code tag 
* Present the issue in a better way
* Use English comments

**Comment by thinkerou** [comment]
please post more details and closing, if you still problem please reopen and discuss. thanks!

**Comment by pi314pi** [comment]
I also need a dynamic route. Please support deleting or canceling routing!
