### ISSUE TITLE
gin string validation

### ISSUE THREAD

**Issue by alkesh26** [gin-gonic/gin#1127]
I have a use case like this
```
type IDData struct {
	ID      string `json:"id" binding:"required"`
	Type    string `json:"type" binding:"required"` // this value should be buzz or fizz only
}

type request struct {
	IDS []IDData        `json:"ids" binding:"required,dive"`
	Timespan int64      `json:"timespan" binding:"required"`
}
```

I need to validate the `type` value of IDData struct to be only `buzz` or `fizz` else throw error.
Is there any validator for this case.

**Comment by joeybloggs** [comment]
Hello @alkesh26 please see here [https://github.com/go-playground/validator/issues/313] for 2 examples on how.

I highly recommend upgrading to v9 of validation if not already done, see [here](https://github.com/go-playground/validator/tree/v9/_examples/gin-upgrading-overriding) for instructions.
