### ISSUE TITLE
Gin support graceful code reload for debug ?

### ISSUE THREAD

**Issue by rfyiamcool** [gin-gonic/gin#1129]
Gin support graceful code reload for debug ?

**Comment by cosmtrek** [comment]
You may try my little live-reloading tool [Air](https://github.com/cosmtrek/air) :)

**Comment by nazwa** [comment]
If I remember correctly, endless worked fine with Gin in the past. Shouldn't be too hard to add live reload base don it if you feel adventurous.

@cosmtrek Air looks interesting!

**Comment by cosmtrek** [comment]
@nazwa Thanks:)
