### ISSUE TITLE
go get github.com/gin-gonic/gin

### ISSUE THREAD

**Issue by 4ebyrek** [gin-gonic/gin#1139]
I have some specific problem with go get github.com/gin-gonic/gin
Please tell me how to fix it?

package gopkg.in/go-playground/validator.v8: unrecognized import path "gopkg.in/
go-playground/validator.v8" (https fetch: Get https://gopkg.in/go-playground/val
idator.v8?go-get=1: dial tcp 45.33.37.13:443: connectex: No connection could be
made because the target machine actively refused it.)
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fet
ch: Get https://gopkg.in/yaml.v2?go-get=1: dial tcp 45.33.37.13:443: connectex:
No connection could be made because the target machine actively refused it.)

C:\gopath\src\ucs_api_21_08_2017\api_v4>go get -u gopkg.in/gin-gonic/gin.v1
package gopkg.in/gin-gonic/gin.v1: unrecognized import path "gopkg.in/gin-gonic/
gin.v1" (https fetch: Get https://gopkg.in/gin-gonic/gin.v1?go-get=1: dial tcp 4
5.33.37.13:443: connectex: No connection could be made because the target machin
e actively refused it.)

**Comment by appleboy** [comment]
Don't download gin source code from `gopkg.in`. Please read the following guide.

https://github.com/gin-gonic/gin#use-a-vendor-tool-like-govendor
