### ISSUE TITLE
Suggestion for code improvement: render.go writeContentType

### ISSUE THREAD

**Issue by dalu** [gin-gonic/gin#1142]
https://github.com/gin-gonic/gin/blob/1e88466d234a82ce4aeca904bce8a0b93fac3d42/render/render.go#L29

currently this function looks like this:
```go
func writeContentType(w http.ResponseWriter, value []string) {
	header := w.Header()
	if val := header["Content-Type"]; len(val) == 0 {
		header["Content-Type"] = value
	}
}
```
This doesn't take into account the various upper and lowercase versions of `Content-type`, aka normalization.

```go
	if ct := w.Header().Get("content-type"); len(ct) == 0 {
		w.Header().Set("content-type", "text/html; charset=utf8")
	}
```

what do you think of this instead?

**Comment by thinkerou** [comment]
I don't agree with you @dalu , because `writeContentType ` is the common function, we can't only set `"text/html; charset=utf8"` because the value is also `"application/json; charset=utf-8"`, etc.
But maybe we should use `Get` and `Set`, what do you think?

**Comment by thinkerou** [comment]
@dalu I will close the issue, if you still have any problem please reopen it and discuss, thanks!

**Comment by dalu** [comment]
Oh yeah sure, I forgot about this issue being open. Sorry.
