### ISSUE TITLE
Best way to use subdomains?

### ISSUE THREAD

**Issue by Swatiparbhakar** [gin-gonic/gin#1143]
Hello
I am working on a project where I need to setup the multiple sub-domains with the routes. I tried code with two sub-domains, but in my case it would be 100 sub-domains. I tried the following code for this:
<pre>
package main

import (
    "github.com/gin-gonic/gin"
    "net/http"
    "strings"
)

type Subdomains map[string]http.Handler

func (subdomains Subdomains) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    domainParts := strings.Split(r.Host, ".")

    if mux := subdomains[domainParts[0]]; mux != nil {
        mux.ServeHTTP(w, r)
    } else {
        http.Error(w, "Not found", 404)
    }
}

func main() {
    r := gin.Default()
    r2 := gin.Default()
    hs := make(Subdomains)
    hs["admin"] = r
    hs["analytics"] = r2
    r.GET("/ping", adminHandlerOne)
    r2.GET("/ping", adminHandlerOne)
    http.ListenAndServe(":9090", hs)
}
func adminHandlerOne(c *gin.Context) {
    c.JSON(200, gin.H{
        "message": "pong",
    })
}
</pre>

But I think that this is not good. Is anybody know the proper way to do this?
I tried to do this with loop also, but it did't work for me.

**Comment by thinkerou** [comment]
Maybe you should see it:https://github.com/gin-gonic/gin/blob/master/examples/multiple-service/main.go, but it is't `subdomain`.

**Comment by nazwa** [comment]
Are routes going to be identical across all the subdomains? Or are is everything going to be different / random?

**Comment by Swatiparbhakar** [comment]
@nazwa Yes routes are identical across all subdomains.

**Comment by Swatiparbhakar** [comment]
@nazwa  Do you have any solution for this?

**Comment by nazwa** [comment]
Hey @Swatiparbhakar , sorry about the delay - I missed a notification for this thread.

I think you're approaching this from a wrong angle. Assuming, as you say, that all subdomains use exactly the same routes - you only need one "server/router" and use a middleware + context to manage what's what.

A generic flow would be like this:

1. Single gin router instance
2. Top level middleware that executes before all routes. It detects the hostname and depending on your set up, loads or sets that site's identifier inside context for handlers to detect
3. Handlers read the site object / identifier from context and perform do their job based on it

I hope this makes sense!

**Comment by Swatiparbhakar** [comment]
Hello @nazwa  thank you for your reply.
I will try approach and check.
Thanks!

**Comment by Swatiparbhakar** [comment]
Hello @nazwa I got what you explained but I am not sure if I am able to implement it with code as I am not getting how should I approach, can you guide me on this as well with some sample code . Would be a great help to me.

**Comment by jochasinga** [comment]
You can use `*httputil.ReverseProxy` for this. Here is how I would reroute to a subdomain based on a hostname without any middleware:

```go
router.GET("/:username", func(c *gin.Context) {
        uri, ok := c.Get("location")
        if !ok {
                c.JSON(500, gin.H{
                     "reason": "Location unknown",
                })
        }
        domain := "awesome.io"
        if uri.(*url.URL).Host == domain {
                // Want to send client to "https://auth.awesome.io/:username"
                s := fmt.Sprintf("https://auth.%s/%s", domain, c.Param("username"))
                uri, err := url.Parse(s)
	       if err != nil {
	               c.JSON(500, gin.H{
	                       "reason": "Subdomain is wrong",
                        })
                }
                rp := new(httputil.ReverseProxy)
                rp.Director = func(req *http.Request) {
                        req.URL = uri
                }
                rp.ServeHTTP(c.Writer, c.Request)
        }
})
```
