### ISSUE TITLE
Binding validation doesn't seem to work

### ISSUE THREAD

**Issue by techjanitor** [gin-gonic/gin#115]
Placing 'required' on a struct doesn't prevent the request from going through. I'm getting some strange behavior with binding in general.

Here is a function:

```
func CreateTag(c *gin.Context) {
        var ntf NewForm
        c.Bind(&ntf)

        if ntf.Name == "" {
                c.JSON(400, gin.H{"error_message": "tag name required"})
                return
        } 
```

Presumably if the item is not present in the request, c.Fail should be returning 'Error #01: Required Type' in the response. Yet this does not happen, it passes straight to the conditional (which defeats the whole purpose of validate):

```
HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 10 Sep 2014 00:18:29 GMT
Content-Type: application/json
Content-Length: 38
Connection: keep-alive

{"error_message":"tag name required"}
```

The error does show up in the gin logs, however:

```
[GIN] 2014/09/09 - 20:18:29 | 400 |    174.682us | 172.4.231.9 POST /new
Error #01: Required Type 
     Meta: Operation aborted
```

It also doesn't return correctly for an unknown MIME type:

```
[GIN] 2014/09/09 - 20:18:53 | 400 |     46.372us | 172.4.231.9 POST /new
Error #01: unknown content-type: pplication/json 
     Meta: Operation aborted
```

I get the same response from the server, it passes straight through.

**Comment by davisford** [comment]
Why was this issue closed?  I'm having a similar problem where c.Bind() does not fail with invalid input.  The api has also changed so `Bind()` now returns an `error` instead of a `bool`.

It appears that gin uses [this validator](https://godoc.org/gopkg.in/bluesuncorp/validator.v5) as it's default, but it does not appear to run for me when I send in JSON with missing tags that are `required`.

**Comment by nazwa** [comment]
This is an old issue and like you said, the binding tags do work. Seems like the docs still need to be updated.

**Comment by luongs3** [comment]
still got trouble with Form Binding

**Comment by SharkFourSix** [comment]
Bump. Invalid input just crosses path the validator like it's not there when it should fail.

**Comment by nicholasss** [comment]
@SharkFourSix Would you be able to create a new issue and describe what is going wrong?
