### ISSUE TITLE
undefined: binding.Query

### ISSUE THREAD

**Issue by hongweishang** [gin-gonic/gin#1160]
I use go1.9.2  gin1.2, and i follows the README.md.

when i run "go run main.go"  after "curl https://raw.githubusercontent.com/gin-gonic/gin/master/examples/basic/main.go > main.go",  it shows:

github.com/gin-gonic/gin/context.go:471:29: undefined: binding.Query
github.com/gin-gonic/gin/context.go:505:31: undefined: binding.Query
github.com/gin-gonic/gin/context.go:673:17: undefined: render.SecureJSON
github.com/gin-gonic/gin/mode.go:68:2: undefined: binding.EnableDecoderUseNumbe

So  why?

**Comment by hongweishang** [comment]
I use govender as well.

**Comment by thinkerou** [comment]
What is the result that run `go env`?

**Comment by def1oyd** [comment]
me too, I'm using dep
It uses v1.2 and gets the commit hash from https://github.com/gin-gonic/gin/releases which is d459835d2b077e44f7c9b453505ee29881d5d12d
And https://github.com/gin-gonic/gin/blob/d459835d2b077e44f7c9b453505ee29881d5d12d/binding/binding.go doesn't have Query

**Comment by thinkerou** [comment]
@hongweishang @def1oyd gin v1.2 have not `binding.Query`, please use new gin version v1.3.0, thanks, if still have any problem please reopen the issue.
