### ISSUE TITLE
instance_id

### ISSUE THREAD

**Issue by FrankIT60** [gin-gonic/gin#1161]
I think is usefull define an instance identification (uuid ?) and print it in logger middleware.
With this option is easy write a debug file for every transaction identified by istance_id inside the name.
And from the log you can go back to the debug file.

**Comment by nazwa** [comment]
I believe this is something up to you to implement, as it is very dependant on your environment and scenario.

Not everyone uses the standard UUID formats for identification!

**Comment by FrankIT60** [comment]
ciao,
my was a hint.
I have already developed this.
I thought it might be useful also to others.
>Not everyone uses the standard UUID formats for identification!

I'm in good company

>>Propagate a context.Context throughout your APIs. Use this context to pass things like request >>UUIDs, which are useful when doing distributed tracing of requests.

https://blog.kolide.com/using-go-for-scalable-operating-system-analytics-cb170d85b1c5
