### ISSUE TITLE
Interpret a // in URL as a /

### ISSUE THREAD

**Issue by Zensey** [gin-gonic/gin#1164]
Though HTTP RFC 2396 defines path separator to be single slash, 
but many multiplexers allow use of // i.e.
```
GET /a/b
GET /a//b
```
produce the same result.

Can this be done in gin-gonic one day ?

**Comment by thinkerou** [comment]
You should use `r.RedirectFixedPath = true`, and it will redirect(`301`).

**Comment by Zensey** [comment]
Thanks
