### ISSUE TITLE
Binding validations does not work when request body is Array of objects

### ISSUE THREAD

**Issue by UltraNemesis** [gin-gonic/gin#1171]
Gin's request validation feature is not working when the request body (JSON) represents an array of objects

Ex:

```
type item struct {
    Field1 string `binding:"required"`
    Field2 string `binding:"required"`
}

var items []item

err := c.BindJSON(&items)

```
To be more clear, the validation logic in gin is expecting the root object to be a struct and hence bails out when an array type gets passed.

**Comment by ycavatars** [comment]
Could you post a sample request body?

**Comment by ycavatars** [comment]
Yes, this is an expected behavior. From the [`StructValidator` interface](https://github.com/gin-gonic/gin/blob/b7e8a6b9b062473c7f3f4f5c16d0a28b6244de48/binding/binding.go#L33), it says 'If the received type is not a struct, any validation should be skipped and nil must be returned.'.

**Comment by benediktreichert** [comment]
Even though this might be expected behaviour per interface definition, I was surprised to see ``binding:"required"`` lose its effect without any warnings or complaints at least at runtime.

**Comment by khier996** [comment]
@ycavatars  So, what is best way to validate each object in an array passed in the body?

**Comment by thinkerou** [comment]
@khier996 yes, closing.

**Comment by Ramzec** [comment]
the issue was closed without answer the last question:

> what is best way to validate each object in an array passed in the body?

Could someone answer it?

**Comment by miaojiuchen** [comment]
+1

**Comment by c1800054work** [comment]
use 
```
type AutoGenerated []struct {
	OrgID   string `json:"org_id"`
	GroupID string `json:"group_id"`
}
```

https://mholt.github.io/json-to-go/

**Comment by memochou1993** [comment]
use `dive`

```GO
Items    []Item `json:"mails" binding:"dive"`
```

**Comment by ns-kliu** [comment]
> use `dive`
> 
> ```go
> Items    []Item `json:"mails" binding:"dive"`
> ```

Thanks @memochou1993 , you really help me to validate all objects in an array.

**Comment by fzf404** [comment]
> 用`dive`
> 
> ```go
> Items    []Item `json:"mails" binding:"dive"`
> ```

thank you!
