### ISSUE TITLE
Can params be validated?

### ISSUE THREAD

**Issue by stuart-mclaren** [gin-gonic/gin#1172]
Is there a way to use the validator bindings to verify a path parameter's format?

eg, if the id for a delete should be a uuid:

DELETE /foo/\<id\>

is there a way to make

id := c.Param("id")

trigger the equivalent to this validate call?

validate.Var(id, "uuid")

Thanks.

**Comment by ycavatars** [comment]
Is this the same as https://github.com/gin-gonic/gin/issues/846?

**Comment by thinkerou** [comment]
@stuart-mclaren duplicated #846
