### ISSUE TITLE
Running common function/route before all defined routes.

### ISSUE THREAD

**Issue by qZanity** [gin-gonic/gin#1181]
Let's say we want to check if a user is logged in, It would be silly if we had to call isLoggedIn() on every single route. Is there a way we can have gin call isLoggedIn() before any defined routes are called?

**Comment by gplume** [comment]
Hi @qZanity, that's the purpose of `router.group("/some-path-prefix")` and `group.Use(someMiddleWare())`. 
No problem to do what you are saying very easily with that.

**Comment by qZanity** [comment]
Thanks very much, I had the term middleware confused.
