### ISSUE TITLE
404 errors not handled by NoRoute when using StaticFS

### ISSUE THREAD

**Issue by shimmy568** [gin-gonic/gin#1182]
This seems like a bit of an issue and gave me a headache for a bit. So if you are using StaticFS to serve a folder you are then unable to catch the 404 errors using NoRoute. This was mentioned in #440 and is a result of http/fs doing it's own error handling. This is a bit problematic when trying to host static files of any kind and also being able to make use of NoRoute to have custom 404 error handling.

```go
r.StaticFS("/", http.Dir("./public/"))

r.NoRoute(func(c *gin.Context) {
        // This cannot be reached as a result of the StaticFS call
	c.File("./public/custom404.html")
})
```

**Comment by okyantoro** [comment]
Basically gin handle the routing before dispatching any callback handler and we know that the ```http.FileServer()``` handle the static file after calling the callback. Also if we try to do file checking inside ```gin.handleHTTPRequest()``` method, we don't have any information about which handler handle static file.
One of the solution is to add logic to check file existence inside ```router.createStaticHandler()``` before delegating to ```http.FileServer()```.
I made a pull request https://github.com/gin-gonic/gin/pull/1220 
Let's discuss if you have any suggestion or comment about this

**Comment by thinkerou** [comment]
#1663 have fixed.
