### ISSUE TITLE
cannot use sse.Event literal

### ISSUE THREAD

**Issue by nicolasStevenin** [gin-gonic/gin#1189]
Hello !
When I try to test the project github.com/gin-gonic/gin in version 1.2 it fails with

./context.go:663: cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
        sse.Event does not implement render.Render (missing WriteContentType method)
./context_test.go:737: cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
        sse.Event does not implement render.Render (missing WriteContentType method)
./middleware_test.go:239: cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
        sse.Event does not implement render.Render (missing WriteContentType method)
FAIL    github.com/gin-gonic/gin [build failed] 

Thank you very much

**Comment by thinkerou** [comment]
@nicolasStevenin master branch fixed it, please see https://github.com/gin-gonic/gin/pull/781

**Comment by thinkerou** [comment]
@nicolasStevenin the issue have fixed, please use new gin version, thanks, if you still have any problem  please reopen the issue.
