### ISSUE TITLE
BindQuery not support pointer

### ISSUE THREAD

**Issue by Jiachang-Cai** [gin-gonic/gin#1190]
`
package main

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

type User struct {
	UserName *string `form:"user_name" binding:"required"`
}

func main()  {
	r := gin.Default()
	r.GET("/user", getUser)
	r.Run(":8085")
}

func getUser(c *gin.Context) {
	var user User
	if err := c.BindQuery(&user); err == nil {
		c.JSON(http.StatusOK, gin.H{"message": "valid!"})
	} else {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
	}
}
`

**Comment by ziyoumeng** [comment]
Because release v1.2 not support BindQuery，you should get newest code.

**Comment by thinkerou** [comment]
Implement in #1336  . try it in the latest master branch.
