### ISSUE TITLE
How to use ShouldBind, ShouldBindJSON, ShouldBindQuery in v1.2

### ISSUE THREAD

**Issue by liuzhaowei55** [gin-gonic/gin#1194]
I can not found these function in gin v1.2 。

**Comment by egiathamaershada** [comment]
if you are asking about how to use them, i think you can't in v1.2
but you can use context.[ShouldBindWith](https://github.com/gin-gonic/gin/blob/master/context.go#L507)
which is actually the base version of those functions
those functions were added at master that maybe the case why you can't find them
or you may want to pull from the master

**Comment by liuzhaowei55** [comment]
OK,thx
