### ISSUE TITLE
encoding/xml cannot marshal maps

### ISSUE THREAD

**Issue by alexandernyquist** [gin-gonic/gin#12]
This code from the documentation:

    r.GET("/someXML", func(c *gin.Context) {
        c.XML(200, gin.H{"message": "hey", "status": 200})
    })

Will result in a `xml: unsupported type: gin.H` error.

Marshalling a specific type would of course work:

    type Response struct {
        	Name string
    }
    c.XML(200, Response{"Alexander Nyquist"})

    // <Response><Name>Alexander Nyquist</Name></Response>

**Comment by manucorporat** [comment]
@alexandernyquist This was fixed a long time ago haha
