### ISSUE TITLE
Why I get 404 by curl -I

### ISSUE THREAD

**Issue by wantg** [gin-gonic/gin#1201]
```
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run() // listen and serve on 0.0.0.0:8080
}
```

```
$ curl -i http://127.0.0.1:8080/ping
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Mon, 18 Dec 2017 10:16:51 GMT
Content-Length: 18

{"message":"pong"}

```
$ curl -I http://127.0.0.1:8080/ping
```
HTTP/1.1 404 Not Found
Content-Type: text/plain
Date: Mon, 18 Dec 2017 10:17:13 GMT
Content-Length: 18

same url

**Comment by delphinus** [comment]
`curl -I` makes HEAD request for the url.  So you should set handler with the `c.HEAD()` method.

**Comment by wantg** [comment]
but

```
$ curl -i http://httpbin.org/get
```
HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Mon, 18 Dec 2017 11:37:11 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0.000696182250977
Content-Length: 216
Via: 1.1 vegur

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.54.0"
  }, 
  "origin": "116.226.107.226", 
  "url": "http://httpbin.org/get"
}

```
$ curl -I http://httpbin.org/get
```
HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Mon, 18 Dec 2017 11:37:17 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0.000608921051025
Content-Length: 216
Via: 1.1 vegur

**Comment by delphinus** [comment]
That is why httpbin.org/get can accept GET & HEAD (& OPTIONS).  It is a bit strange, but true.

```
curl -X OPTIONS -v http://httpbin.org/get
*   Trying 50.17.234.140...
* TCP_NODELAY set
* Connected to httpbin.org (50.17.234.140) port 80 (#0)
> OPTIONS /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: meinheld/0.6.1
< Date: Mon, 18 Dec 2017 12:59:55 GMT
< Content-Type: text/html; charset=utf-8
< Allow: OPTIONS, HEAD, GET

...
```

**Comment by jeffreims** [comment]
You don't get a 404 from http://httpbin.org/get because that webserver does handle HEAD requests.

The HEAD request will just return the headers without the document body.

You currently don't have a handler set for HEAD like @delphinus already mentioned.

**Comment by wantg** [comment]
thanks
