### ISSUE TITLE
How to create router, that will match any request?

### ISSUE THREAD

**Issue by bynov** [gin-gonic/gin#1207]
Hi,

I need to handle all requests in one route.
For example, I have website with many urls, smth like /, /users, /users/list ... etc
I want to use only one route to handle all this, something like 
r.Any("*", handle) and all my requests need to handle by this route.
How can I make it?

Thanks for help

**Comment by lucense** [comment]
I think you need to use middleware  instead of routing

**Comment by BlakeMesdag** [comment]
``` golang
router.Any("/*proxyPath", handler)
```

Access path from handlers with:
``` golang
func someHandler(c *gin.Context) {
    c.Param("proxyPath")
}
```
