### ISSUE TITLE
BindJson sometimes very slow

### ISSUE THREAD

**Issue by jenenliu** [gin-gonic/gin#1210]
```
    var currenttime = time.Now()
    startlabel := currenttime
    if c.BindJSON(&kccomparereq) == nil {
        cost := time.Now().Sub(currenttime)
        fmt.Println("====[", startlabel, "]====After Bind Json, time cost: ", cost)
    }
```
Hi, I use gin for my web server, and recently I found some requests take more time then it should be.
So I track all part of time cost of the request, then I find some request, BindJson function is slow, which
is about *5s*, and most of time it is several ms.

I try to switch from standard json to jsoniter, but the resul is the same, there are stil some 2s.

The request is a image base64 data, which is always ~80k, I log the size, and there is not different from other requests.

I try to google but can't find any thing help, and thanks for your job, gin is really awesome.

**Comment by thinkerou** [comment]
Maybe you should record every function which run time, include json decode and validate.

**Comment by thinkerou** [comment]
@jenenliu please post more than info, i.e. `kccomparereq`, and so on. thanks!

**Comment by chainhelen** [comment]
@jenenliu Maybe [go-torch](https://github.com/uber/go-torch) can help you.

**Comment by jenenliu** [comment]
thanks
