### ISSUE TITLE
Is there any way to reload the HTML templates while server is running ?

### ISSUE THREAD

**Issue by velomarc** [gin-gonic/gin#1225]
When I am debugging, I always need to make some changes to the HTML file, so I hope i can see the changes on the browser just by refreshing it, 
However, I have to restart the server, then the templates could be reloaded, after that I can see the changes, it's really inconvenient, Is there any way to reload the HTML templates while server is running? thanks

BTW: I tried debug mode, seems it does not work well

BTW2: this is the test code as below

```go

import	"github.com/gin-gonic/contrib/renders/multitemplate"

func adminRender(engine *gin.Engine) multitemplate.Render {
	render := multitemplate.New()
	pages, err := filepath.Glob("./webadmin/adminpages/*.html")
	if err != nil {
		Log.Error("err = %v", err)
		os.Exit(-1)
		return nil
	}

	for _, page := range pages {
		pageName := page
		pagetmpl := append([]string{pageName}, defaultTemplate()...)
		render.Add(pageName, template.Must(template.New(pageName).Funcs(engine.FuncMap).ParseFiles(pagetmpl...)))
	}

	return render
}

func MakeGinAdminHandler() http.Handler {

	Log.Info("entering...")

       gin.SetMode(gin.DebugMode)

	router := gin.New()
	router.Use(gin.Logger())
	router.Use(gin.Recovery())

	router.Static("/webadmin", "./webadmin")
	router.HTMLRender = adminRender(router)
... ...
}

```

**Comment by velomarc** [comment]
problem resolved,
I give up using the render from "multitemplate", I implemented my own render, and I let my render reload the template if it's under debug mode. it works well.

**Comment by foolin** [comment]
I am write simple gin template, support reload template. You can view the code: https://github.com/foolin/gin-template
