### ISSUE TITLE
Is there a way to create authentication system like Rails's `has_secure_password`?

### ISSUE THREAD

**Issue by johnunclesam** [gin-gonic/gin#1226]
Is there a way to create authentication system like Rails's `has_secure_password`?

I'm new to Gin / Golang and I come from Rails.

I don't understand if there is a way in gin-gonic like the Rails's system with `has_secure_password`, `bcrypt` and `password_digest`.

I'm wrong?

https://www.pluralsight.com/guides/ruby-ruby-on-rails/token-based-authentication-with-ruby-on-rails-5-api#creating-the-user-model

**Comment by appleboy** [comment]
See: https://github.com/go-gitea/gitea/blob/7a2a3fbafc5b15bb460787a2fca9db8f1e09e78e/models/user.go#L407-L421
