### ISSUE TITLE
load handler files from subdirectory

### ISSUE THREAD

**Issue by calvinsug** [gin-gonic/gin#1227]
Hi guys, i'm just learning Go Lang for 3 days, Following tutorial from a website, and the tutorial says to put handler files in the same folder. I'm just wondering if i could put my handler files to specific folder, let say: handlers folder.

The desired folder structure will be like this:
[project's-folder]/main.go
[project's-folder]/routes.go
[project's-folder]/handlers/handlers.user.go
[project's-folder]/models/models.user.go

Is it possible ? Because it is possible to import all of html files from subdirectory using this code:

` router := gin.Default()`
`  router.LoadHTMLGlob("templates/*")`

**Comment by lutzhorn** [comment]
`handlers.user.go` is a strange name for a Go file. Why do you name it like this?

**Comment by calvinsug** [comment]
i'm following this tutorial : https://semaphoreci.com/community/tutorials/test-driven-development-of-go-web-applications-with-gin

and if it is a strange name, what is the best name convention ? I thought the alternative name is:

main.go
routes.go
handlers/users_handler.go
models/user.go

**Comment by lutzhorn** [comment]
* Just `routes.go`. I'd not use dots `.` as part of the file name.
* Sub folders won't work, don't use them.

**Comment by calvinsug** [comment]
Roger that, so it would be better to put a lot of files inside my project folder (all handler,model, and middleware files in the same folder)

**Comment by calvinsug** [comment]
i think this is the answer i'm looking for : https://stackoverflow.com/a/15051192/4511009
i have tried it and it works! Thanks for your assistance, this issue can be closed now.

**Comment by adis-me** [comment]
@calvinsug If this issue is resolved for you, please click on the button **Close issue** below.

**Comment by thinkerou** [comment]
closing, if still need please reopen, thanks!
