### ISSUE TITLE
Issue with HandleContext and sync pool

### ISSUE THREAD

**Issue by manavo** [gin-gonic/gin#1230]
Hi!

If I'm not mistaken, the HandleContext function should not return the context to the sync pool, right? https://github.com/gin-gonic/gin/blob/master/gin.go#L337

HandleContext will only ever be used to handle an adjusted Context, which will already be returned to the pool from the [ServeHTTP method](https://github.com/gin-gonic/gin/blob/master/gin.go#L320).

So if HandleContext returns it too, it might cause all kind of issues, right?

Sorry I'm not providing any benchmarks or tests with this, it is just a gut feeling for now.

Thanks,
Phil

**Comment by japettyjohn** [comment]
@manavo This is not a gut feeling matter - this is causes all kinds of issues.

Now on [line 339](https://github.com/gin-gonic/gin/blob/master/gin.go#L339) I've been chasing down errors of concurrent map RW and writing on finished request. Once I commented this everything resolved.

**Comment by manavo** [comment]
Based on the MRs I’m guessing this can be closed, so doing so now!
