### ISSUE TITLE
why Request.URL, Host & Scheme are empty?

### ISSUE THREAD

**Issue by jhaoheng** [gin-gonic/gin#1233]
Hi

I build gin & use curl to request api
> use "github.com/happierall/l" to make the log pretty

use `l.Log(c.Request.URL)` and the log are below
> c is `c *gin.Context`

```
    URL:    &url.URL{
        Scheme:     "",
        Opaque:     "",
        User:       (*url.Userinfo)(nil),
        Host:       "",
        Path:       "/v1/playback/demo/videmo/id123/1516375842496",
        RawPath:    "",
        ForceQuery: false,
        RawQuery:   "",
        Fragment:   "",
    },
```

why Host & Scheme are empty?

**Comment by ssskip** [comment]
because RequestURI is relative.

**Comment by tmm1** [comment]
> because your RequestURI is relative.

what does that mean?

**Comment by weletry** [comment]
> because your RequestURI is relative.

so how can i  get the absolute_uri?

**Comment by ivan-fr** [comment]
hello,

Why the url struct from *gin.context is empty in localhost ??

**Comment by fermin-silva** [comment]
I'm accessing this url in my server: http://local.mininoticias.com.ar:8084/

If I print
```
fmt.Println("request url:", c.Request.URL)
fmt.Println("request host:", c.Request.Host)

```
I get:
```
request url: /
request host: local.mininoticias.com.ar:8084
```
So no host, scheme or anything in the url struct

Not sure why this issue was closed without any explanation

**Comment by GwynethLlewelyn** [comment]
I'd love to have an answer as well. At least `c.Request.Host` seems to be correct, but I just have to guess the Scheme. And yes, the call was a relative URI — so what?

**Comment by GwynethLlewelyn** [comment]
Ok, it seems that this was closed because it's not an issue with Gin, but with the weird way the underlying `http` library works: https://stackoverflow.com/questions/6899069/why-are-request-url-host-and-scheme-blank-in-the-development-server

The comments there give some ideas on how to extract the relevant data _if_ the call is a relative call...

I guess that's why this issue was closed.
