### ISSUE TITLE
undefined: render.Delims

### ISSUE THREAD

**Issue by bean-du** [gin-gonic/gin#1236]
error 
# github.com/bean-du/tbin/vendor/github.com/gin-gonic/gin
vendor/github.com/gin-gonic/gin/gin.go:48: undefined: render.Delims

how to fix it

**Comment by appleboy** [comment]
@bean-du Please update your github.com/gin-gonic/render to the latest version.

**Comment by gguridi** [comment]
There's a typo in the package name:
- github.com/gin-gonic/gin/render

**Comment by manishgajare** [comment]
even after following above steps i still keep on getting "undefined: render.Delims"
is there any other way i can deal with the situation?
