### ISSUE TITLE
New Release Tag

### ISSUE THREAD

**Issue by motleycrew** [gin-gonic/gin#1239]
Dep ensure fetches 1.2.0 which does not have SaveUploadedFile. 

https://github.com/gin-gonic/gin/issues/1025

Doing this in dep is not safe for production environments since it may break  builds.

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch="master"

Please add a new release tag to a stable version.

**Comment by jessie-codes** [comment]
My team is running into the same issue. We're doing the work around described above for our dev environment, but we'll really need to be on a stable version before we go to production.

**Comment by WeitBelou** [comment]
Hi! Are there any chances that this issue will be fixed soon?
We are currently running into the same issue with `vgo` that tries to fetch v1.2.0 version.

**Comment by CameronGo** [comment]
I know the version 1.3.0 milestone is still pending, but is it possible to version the existing commits in master to a current release version?  I don't think it makes sense to let all of this new functionality sit around for so long without being able to incorporate it into production packages.

**Comment by iyuq** [comment]
I think a new release with the bug fixed is in demand. Please release a 1.2.1 or somewhat to fix this, use the master branch is not a good solution for those who uses gin in production with version manager.

**Comment by dotchev** [comment]
There are about 150 commits since the last [release](https://github.com/gin-gonic/gin/releases).
`ShouldBind`, `ShouldBindJSON`, `ShouldBindQuery` are missing in that release.

**Comment by jessie-codes** [comment]
Is there any updates on this? The latest commit (https://github.com/gin-gonic/gin/commit/6d913fc343cfac80d656db5be67a0ffb1323ba0d) ended up breaking builds and we had to refactor code in order to account for the changes. We really need a new release so we can use some of the newer features without having to worrying about whether or not later commits are going to break our code.

**Comment by ritoon** [comment]
Could you please just let us know the reasons why there is no new version tag, tks ?

**Comment by carllhw** [comment]
Any progress ?

**Comment by ritoon** [comment]
With my team we finally decide to change the usage of the tag version to the commit version in dep. That was the only way to use the bug fix on the json struct that didn't bind with pointers. Usually this is not recommended but we have to move on.

**Comment by appleboy** [comment]
@ritoon Yes. Please try to use the commit version first. I don't know what time @javierprovecho come back?

**Comment by NarHakobyan** [comment]
someone who is contributing this repository needs to fork and continue work and do tags

**Comment by drPytho** [comment]
Any updates? What's the reason for no new release? If no progress is done here, is there a recommended commit to use instead?

**Comment by thinkerou** [comment]
Hi, everybody v1.3.0 have released! https://github.com/gin-gonic/gin/releases/tag/v1.3.0
