### ISSUE TITLE
MarshalJSON not being called

### ISSUE THREAD

**Issue by cbarraford** [gin-gonic/gin#1244]
With the given code below, it seems like the custom `MarshalJSON` function isn't being called with i hit the api endpoint. Should it be?

```
type User struct {
 FirstName string `json:"first"`
 LastName string `json:"last"`
 Fullname string `json:"full"`
}

func (u *User) MarshalJSON() ([]byte, error) {
    type Alias User
    return json.Marshal(&struct {
        FullName string `json:"full"`
        *Alias
    }{
        FullName: fmt.Sprintf("%s %s", u.FirstName, u.LastName),
        Alias:  (*Alias)(u),
    })
}

......

user := User{
  FirstName: "Bob",
 LastName: "Denver",
}

c.JSON(200, user)
```

I am not seeing the full name attribute filed out like i'd expect. Any thoughts on what i may be missing here?

**Comment by cbarraford** [comment]
I've been able to limit the issue to be something outside of `gin`, so closing ticket.

**Comment by mjip** [comment]
What was the fix you ended up finding?

**Comment by cbarraford** [comment]
sorry i don't remember

**Comment by DDevine** [comment]
The issue seems to be satisfying the interface on **`*User`** rather than **`User`**. Notice the small difference.

Try something like this:
```
func (u User) MarshalJSON() ([]byte, error) {
    type Alias User
    return json.Marshal(&struct {
        FullName string `json:"full"`
        *Alias
    }{
        FullName: fmt.Sprintf("%s %s", u.FirstName, u.LastName),
        Alias:  (*Alias)(&u),
    })
}
```
I'm *very* new to Go, so if this is not helpful for some reason please let me know because I don't want to mislead anybody. Having said that - I've tried it and it works for me!

**Comment by zsirfs** [comment]
@DDevine nice! When using the `*User`, only ptr can be called.

**Comment by YannikHinteregger** [comment]
Omg, thanks! Finding this cost me 2 days
