### ISSUE TITLE
when use context.Param() to get optional params from url,  it will always return a slash

### ISSUE THREAD

**Issue by CodingPapi** [gin-gonic/gin#1255]
router.GET("api/:fixed/*optional", func(context *gin.Context) {
	t1 := context.Param("fixed")
	t2 := context.Param("optional")
})

curl http://127.0.0.1:8000/api/user/123

t1 will be "user"
t2 will be "/123"

Is this a bug?
Thank you for any reply

**Comment by appleboy** [comment]
```go
router.GET("api/:fixed/:optional", func(context *gin.Context) {
  t1 := context.Param("fixed")
  t2 := context.Param("optional")
})
```

change `*optional` to `:optional`

**Comment by CodingPapi** [comment]
@appleboy Thank you for ur reply.
I do know use :optional can get param that without slash, but why there should be a "/" when get an optional param? Is there any way to get optional param without than "/" ?  Thank you for your kindness!

**Comment by CodingPapi** [comment]
:optional is a better way
