### ISSUE TITLE
unrecognized import path "gopkg.in/go-playground/validator.v8" in go get

### ISSUE THREAD

**Issue by vbmade2000** [gin-gonic/gin#1265]
I am getting following error output while performing **`go get github.com/gin-gonic/gin`**

> package gopkg.in/go-playground/validator.v8: unrecognized import path "gopkg.in/go-playground/validator.v8" (https fetch: Get https://gopkg.in/go-playground/validator.v8?go-get=1: dial tcp: lookup gopkg.in on 127.0.0.53:53: read udp 127.0.0.1:60877->127.0.0.53:53: i/o timeout)
> package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: dial tcp: lookup gopkg.in on 127.0.0.53:53: read udp 127.0.0.1:34155->127.0.0.53:53: i/o timeout)
> 

I tried using Glide and Govendor but same issue. Looks like gopkg.in/go-playground/validator.v8 is not available.

**Comment by joeybloggs** [comment]
GitHub experienced a DDoS attack and was down for approx 10 minutes and is the most likely cause.

It is also likely that Gopkg.in experienced some issues around the same time.

It appears to be up and working now, if you could please try again to see if the problem is resolved.
