### ISSUE TITLE
Wait until goroutine finishes and then response the data

### ISSUE THREAD

**Issue by danielckv** [gin-gonic/gin#1269]
**Hi!**

I tried to look in to the documentation of the GIN async process but I found old outdated functions  that already not exists.

I'm trying to figure out how to response a data that returned from a RPC job.
As right now, the route automatically responding status 200 and not waiting until the go-routine finish his job.

Found something called context.Done() that retunes a nil channel but I didn't understood how I can handle the channels as part of the context.

**Comment by tmm1** [comment]
Use Hijack()

**Comment by danielckv** [comment]
Just figured out that the architecture of our routing for API is not good for purpose of running async jobs so we using socket for that.

Thanks!
