### ISSUE TITLE
route "/stream/:roomid" in "examples/realtime-chat" got wrong code while post message with non-ascii character?

### ISSUE THREAD

**Issue by lonycc** [gin-gonic/gin#1288]

**Comment by thinkerou** [comment]
@tonyxyl Please post your example data, I use the follow curl it's ok:

`curl -v 'http://127.0.0.1:8080/room/123' -d 'user=tianou&message=のすべてのデータ' -H 'Content-Type: application/x-www-form-urlencoded' -X POST`

`curl -v 'http://127.0.0.1:8080/room/123' -d 'user=tianou&message=中文' -H 'Content-Type: application/x-www-form-urlencoded' -X POST`

and server can output:

```
event:message
data:tianou: のすべてのデータ

event:message
data:tianou: 中文
```

**Comment by tonyxyl** [comment]
i mean in the webbrowser.
