### ISSUE TITLE
Significant Slowdown in context.String() function

### ISSUE THREAD

**Issue by Arunpreet** [gin-gonic/gin#1289]
Hi,
I have the following function
```golang
func FoodBar(context * gin.Context){
	startTime := time.Now()
	Id := context.Query("id")
	maxContentId := context.Query("max_content_id")
	var TotalelapsedTime time.Duration
	var processingTime time.Duration
	if len(Id) > 0 && len(maxContentId) > 0 {
               //do DB/ Cache query
		outData, status := FoodBarHandler(Id, maxContentId)
		processingTime = time.Since(startTime)
		if status {
			context.String(http.StatusOK, string(outData))
			TotalelapsedTime = time.Since(startTime)
			glog.V(logLevelPerformenceInfo).Infof("FoodBar(), " +
				"processing time :%s, total execution time :%s", processingTime, TotalelapsedTime)
			return
		}
	}
	context.String(http.StatusForbidden, "Status failed")
	glog.V(logLevelPerformenceInfo).Infof("FoodBar(), " +
		"processing time :%s, total execution time :%s", processingTime, TotalelapsedTime)
	return
}
```
IN FooBar() the FooBarHandler does all the heavy lifting like DB/cache query, JSON encoding etc, but the timing measurement does not add up.
It seems like TotalelapsedTime(processing and writing the response back) is significantly taking more time than processingTime (processing). Here are some results

FoodBar(), processing time :400.284µs, total execution time :289.196008ms
FoodBar(), processing time :10.576482ms, total execution time :620.363321ms
FoodBar(), processing time :436.55µs, total execution time :391.341991ms
FoodBar(), processing time :544.983µs, total execution time :570.257745ms
FoodBar(), processing time :3.855597ms, total execution time :4.422912ms
FoodBar(), processing time :8.61613ms, total execution time :570.295792ms
FoodBar(), processing time :4.079823ms, total execution time :4.311607ms
FoodBar(), processing time :5.025624ms, total execution time :254.933137ms
FoodBar(), processing time :452.871µs, total execution time :1.932513ms
FoodBar(), processing time :975.258µs, total execution time :2.675737ms
FoodBar(), processing time :420.936µs, total execution time :1.550688ms
FoodBar(), processing time :384.235µs, total execution time :1.77858ms
FoodBar(), processing time :15.285014ms, total execution time :1.452023705s
`

So it seems like writing the response using context.String() is very slow. Is there any workaround for that or I am missing something?

I am running HTTPS on Gin (in release mode)

**Comment by sosedoff** [comment]
Can you specify what is happening in the `FoodBarHandler` handler. In any case you should at least have the test case where the app-specific stuff is isolated from the actual gin-related functionality.

**Comment by thinkerou** [comment]
1. your two `glog.V` can't differentiate;
2. search cache success and failure have differentiate.
closing the issue, I have question and please reopen it and post more details which help reproduce issue. thanks!
