### ISSUE TITLE
How can i customize url

### ISSUE THREAD

**Issue by getkokomi** [gin-gonic/gin#1291]
such as
 my user post a new article , customize a url link  
domain.com/customize.html or domain.com/cate/customize.html or
domain.com/date/customize.html 

but now my blog system only post article a fixed link .
such as domain.com/article/id.html 
so,what should I do?

**Comment by konojunya** [comment]
@tbure

If I make it, I select one of them as a user and move the system, I have three types as master data and save the data of the new article together with `type` in the DB. Based on that data, create HTML using `template`, and compare` type` at the requested URL and put it in the response body.

I'm sorry if I have a misplaced answer :(

**Comment by thinkerou** [comment]
```go
router.POST("/article/:id", func(c *gin.Context) {
    id := c.Param("id")
    // use id ....
```
right? @getkokomi

**Comment by getkokomi** [comment]
@thinkerou    i  think  i  need  customize any  url ,
   domain.com/(.*?)
   domain.com/xxxxnj/kdjj/...../jjfkkk

**Comment by getkokomi** [comment]
@thinkerou  Custom article URL

**Comment by thinkerou** [comment]
Please see #1207
