### ISSUE TITLE
RedirectFixedPath doesn't work on linux

### ISSUE THREAD

**Issue by 18959263172** [gin-gonic/gin#1297]
I want to post a request like this 
`127.0.0.1:8082//event/write`
and ,I found when I set  RedirectFixedPath true it would be redirect.
the question is my client do not support redirection.
So how can I fix this?
I want a function like auto strip slash or regex url .so could gin do that?

**Comment by thinkerou** [comment]
Please post some codes and your go version and linux info.

**Comment by thefury** [comment]
Is this still an issue? If there's been no movement since April, perhaps it should be closed.

**Comment by thinkerou** [comment]
if still have problem please post more details and reopen it, closing.
