### ISSUE TITLE
How-To: FormFile in Bind Object?

### ISSUE THREAD

**Issue by iamnande** [gin-gonic/gin#1298]
Hello there!

I'm trying to figure out if there's a way to simplify an upload handler by including the form file in with the bind object.

```go
type UploadRequest struct {
  Image       interface{} `form:"image" binding:"required"`
  Description string      `form:"description" binding:"required"`
  Owner       string      `form:"owner" binding:"required"`
}

func HandleUpload(c *gin.Context) {

  req := new(UploadRequest)
  if err := c.ShouldBind(req); err != nil {
    // fail brilliantly
  }
  // do wonderful upload-y type things

}
```

However, when CURLing an image up I receive a binding error:
```
$ curl -F 'description=super cool thing' -F 'owner=rbalboa27' -F 'image=@/path/to/image.iso' http://localhost:8000/api/image/v1.0/upload
bailing: Key: 'UploadRequest.Image' Error:Field validation for 'Image' failed on the 'required' tag
```

I've tried a few variations to try and "sniff" the type of UploadRequest.Image to no avail.

Is this type of thing supported/a feature within Gin?

**Comment by thinkerou** [comment]
Maybe https://github.com/gin-gonic/gin/pull/1264

**Comment by iamnande** [comment]
@thinkerou I'll close this and follow #1264. thanks!
