### ISSUE TITLE
segment conflicts with existing wildcard

### ISSUE THREAD

**Issue by 68696c6c** [gin-gonic/gin#1301]
I found a few other issues that look like they are related to this problem, but they are all closed and I'm not sure what the status of this bug is, so I'm making a new issue here...

As an example I've defined two routes, one to get a user by their ID, and another to get a user by their email:
```
	apiRoutes := r.Engine.Group("/api")
	apiRoutes.GET("/users/:id", GetUser)
	apiRoutes.GET("/users/email/:email", GetUser)
```

When I try and build, I get this error:
```
panic: path segment 'email/:email' conflicts with existing wildcard ':id' in path '/api/users/email/:email'
```

The problem is that these routes are NOT ambiguous and shouldn't conflict.  I'm using Gin in several APIs and run into this problem in all of them in various ways.  The above code is just a simplified demonstration of the bug.

Based on the closed issues I've found here:
https://github.com/gin-gonic/gin/issues/205
https://github.com/gin-gonic/gin/issues/388

That last issue referenced this open issue in httprouter:
https://github.com/julienschmidt/httprouter/issues/73

...but that issue hasn't been updated since 2015...

So it seems the Gin team is aware of this bug, but it isn't clear whether or not it's going to be fixed.  I'm just posting this to get some clarity on the problem.

Thanks!

**Comment by nazwa** [comment]
Hi @68696c6c - it's not really a bug, but a known limitation. The downside of not using regular expressions for route matching is that paths have to be unique. 

Unfortunately afaik this behavior is not going to change any time soon.

**Comment by 68696c6c** [comment]
Understood, thank you.

However, I was fiddling with this more today and found a workaround that I wanted to share here in case anyone else comes across this issue.

If I change my routes to look like this, everything works fine:
```
        apiRoutes := r.Engine.Group("/api")
	apiRoutes.GET("/users/:id", GetUser)
	apiRoutes.GET("/users/:id/email", GetUserByEmail)
```

Basically, both routes need to have the wildcard in the same position, and the wildcards need to be named the same thing.

**Comment by DavexPro** [comment]
> Understood, thank you.
> 
> However, I was fiddling with this more today and found a workaround that I wanted to share here in case anyone else comes across this issue.
> 
> If I change my routes to look like this, everything works fine:
> 
> ```
>         apiRoutes := r.Engine.Group("/api")
> 	apiRoutes.GET("/users/:id", GetUser)
> 	apiRoutes.GET("/users/:id/email", GetUserByEmail)
> ```
> Basically, both routes need to have the wildcard in the same position, and the wildcards need to be named the same thing.

Do you have some good alternatives?

I encounter the same problem...

**Comment by thinkerou** [comment]
why not change name? like:
```
apiRoutes := r.Engine.Group("/api/users")
apiRoutes.GET("/byid/:id", GetUser)
apiRoutes.GET("/byemail/:id", GetUserByEmail)
```

**Comment by Djumpen** [comment]
I needed such routes:
```
POST /users
GET /users/:id
GET /users/:id/status
**POST** /users/actions/some-action // panic
```
I have to switch to the next model:
```
POST /users
GET /users/user/:id
GET /users/user/:id/status
POST /users/actions/some-action
```

**Comment by Djumpen** [comment]
I needed such routes:
```
POST /users
GET /users/:id
GET /users/:id/status
POST /users/actions/some-action // panic
```
I have to switch to the next model:
```
POST /users
GET /users/user/:id
GET /users/user/:id/status
POST /users/actions/some-action
```

**Comment by arianitu** [comment]
This issue is big enough that I would never recommend gin for any serious project. The fact that you have to rename your routes because of this conflict is insanely annoying and the team constantly has to create weird routes to make everything work.

How much useful is this route optimization really? Typical REST frameworks are going to hit database limits before httprouter becomes a bottleneck.

I regret using gin and you get trapped at the beginning because there isn't a big red notice saying "gin does not support classic REST apis because of its insane httprouter implementation"

**Comment by vchakoshy** [comment]
Router:
```
r.GET("/auth/user/:id/", badUserSearchHandler)
// r.GET("/auth/user/search/", badUserSearchHandler)
```
bad Function
```
func badUserSearchHandler(c *gin.Context) {
	id := c.Param("id")
	if id == "search" {
		searchUser(c)
		return
	}
	userItem(c)
}
```

```
func searchUser(c *gin.Context) {
	qInput := strings.TrimSpace(c.Query("q"))
        .....
}
```

```
func userItem(c *gin.Context) {
	id := c.Param("id")
        ....
}
```

**Comment by millettmb** [comment]
Is there a way that we can specify the type of `:id` in the route? For my cases `:id` is always an int, so if the incoming route has an `int` in that field it has to pattern match to the `:id` routes, but if it has a string it will match to the other provided routes.

**Comment by kuchaguangjie** [comment]
Any solution yet?
`GET /:id` and `GET /count` conflict, it's very common,

**Comment by Andro999b** [comment]
Why this closed? GIN route matching is super ugly.

**Comment by pavelpatrin** [comment]
There was a PR to improve httprouter used by gin: https://github.com/julienschmidt/httprouter/pull/329.
Maybe we can ask @rw-access and @julienschmidt there to go forward with it.
Maybe start some crowdfunding to get it released?

**Comment by pavelpatrin** [comment]
Guys?
