### ISSUE TITLE
How to support same url pattern with different HTTP methods ?

### ISSUE THREAD

**Issue by GQHero** [gin-gonic/gin#1302]
For example,
POST /user/:id ---> update a user
GET /user/:id    ---> query a user

Thanks!

**Comment by delphinus** [comment]
```go
r := gin.New()
r.POST("/user/:id", hoo.Foo()) // update a user
r.GET("/user/:id", hoo.Bar()) // query a user
```

How about this?

**Comment by GQHero** [comment]
@delphinus Thanks.
I see, The conflict is between "POST /user/:id" and "POST /user/items/_search".
So how to solve this ?
Thanks.

**Comment by delphinus** [comment]
It is a limitation from httprouter that gin uses as an internal library for routing.  It cannot detect wildcard paths and others below the same parents (#388).  I think this is a spec, not a bug.

So you cannot use such routing.  I suggest that you add the plural form of routing, such as...

```
POST /users/:id
POST /user/item/_search
```

**Comment by GQHero** [comment]
aha, I see, Thanks!
