### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xieyiwen** [gin-gonic/gin#1303]
First of all, thanks for you reading !

When i request from 100+ threads to the server,gin.H will report error.
this is my response json 

`
c.JSON(http.StatusOK, gin.H{
		"code": "ok",
		"data": gin.H{
			"dna": md.GenerateDNA(),
		},
	})
`

sometimes gin.H will make nil point dereference

`
knode1_1  | runtime error: invalid memory address or nil pointer dereference  

knode1_1  | /usr/local/go/src/runtime/panic.go:491 (0x433462)  
knode1_1  | /usr/local/go/src/runtime/panic.go:63 (0x43236d)  
knode1_1  | /usr/local/go/src/runtime/signal_unix.go:367 (0x44995b)  
knode1_1  | /go/src/p/app/handler.metadata.go:87 (0xb92edb)  
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/context.go:107 (0xb7a482)
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/recovery.go:46 (0xb8c729) 
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/context.go:107 (0xb7a482)
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/logger.go:83 (0xb8ba5b)
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/context.go:107 (0xb7a482)
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/gin.go:359 (0xb83595)
knode1_1  | /go/src/vendor/github.com/gin-gonic/gin/gin.go:326 (0xb82d2a)
knode1_1  | /usr/local/go/src/net/http/server.go:2619 (0x69e323)
knode1_1  | /usr/local/go/src/net/http/server.go:1801 (0x69a46c)
knode1_1  | /usr/local/go/src/runtime/asm_amd64.s:2337 (0x462200)
`

What should i do with this problem?

**Comment by thinkerou** [comment]
Why not `/go/src/p/app/handler.metadata.go:87`?

**Comment by delphinus** [comment]
What code is in `md.GenerateDNA()`? You can see this error if you use more simplified code, such as `c.JSON(http.statusOK, gin.H{"bar": "foo"})` ?
