### ISSUE TITLE
https://gopkg.in/gin-gonic/gin.v1

### ISSUE THREAD

**Issue by kingeasternsun** [gin-gonic/gin#1311]
should i import
import "gopkg.in/gin-gonic/gin.v1
or 
"github.com/gin-gonic/gin"

**Comment by easonlin404** [comment]
please use `go get github.com/gin-gonic/gin` to get the last version and import `import "github.com/gin-gonic/gin"` in your code.

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/gin#start-using-it

Don't use `gopkg.in` service any more.
