### ISSUE TITLE
how define root  root ?

### ISSUE THREAD

**Issue by getkokomi** [gin-gonic/gin#1315]
Hello, i  need  r.GET("/:page",myhandler) ,how  do  it  ?

**Comment by delphinus** [comment]
You can switch the handler with the value from `c.Param(":page")`.  Such codes below...

```go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.New()
	r.GET("/:page", func(c *gin.Context) {
		switch c.Param("page") {
		case "foo":
			c.String(http.StatusOK, "Hello, foo!")
		case "bar":
			c.String(http.StatusOK, "Hello, bar!")
		default:
			c.String(http.StatusNotFound, "not found")
		}
	})
	r.Run(":5000")
}
```

```sh
$ curl 0:5000/foo
Hello, foo!
$ curl 0:5000/bar
Hello, bar!
$ curl 0:5000/foobar
not found
```

**Comment by delphinus** [comment]
Yes.  You cannot do that.  The wildcard path `:page` cannot live together with other concreate paths, such as `admin`, below the same parent `/`.  You should separate them into other ranks in paths.

```go
r.GET("/admin", ...)
r.GET("/others/:page", ...)
```

**Comment by Tom29** [comment]
@delphinus I think this is not good.
Not working with root path might affect to SEO or break many website url structures.
Many websites have this structure
`domain/abc-$id`
but also have
`domain/admin`
Ability to handle is a must have feature.

**Comment by delphinus** [comment]
I see... , but gin can't achieve that.  gin closely depends on [httprouter][] that cannot deal with such cases. ;(  You should use the switch-case routing I mentioned above.

[httprouter]: https://github.com/julienschmidt/httprouter

```go
func main() {
	r := gin.New()
	r.GET("/domain/:path", func(c *gin.Context) {
		switch p := c.Param("path"); {
		case p == "admin":
			adminHandler(c)
		case strings.HasPrefix(p, "abc-"):
			IDstr := strings.TrimPrefix(p, "abc-")
			ID, _ := strconv.Atoi(IDstr)
			abcHandler(c, ID)
		}
	})
	r.Run(":8080")
}

func adminHandler(c *gin.Context) {
	c.String(http.StatusOK, "adminHandler")
}
func abcHandler(c *gin.Context, ID int) {
	c.String(http.StatusOK, fmt.Sprintf("abcHandler: %d", ID))
}
```

**Comment by xjnxdwl** [comment]
@delphinus  Good job ! I think i need this , thank you !

**Comment by thinkerou** [comment]
closing
