### ISSUE TITLE
关于上传文件的一个小问题请教下

### ISSUE THREAD

**Issue by xhochipe** [gin-gonic/gin#1320]
您好：
gin怎么解决文件上传第一次请求是option的问题，我写了middleware

func Cors() gin.HandlerFunc {
	return func(c *gin.Context) {
		//method := c.Request.Method

		var headerKeys []string
		for k, _ := range c.Request.Header {
			headerKeys = append(headerKeys, k)
		}
		headerStr := strings.Join(headerKeys, ", ")
		if headerStr != "" {
			headerStr = fmt.Sprintf("access-control-allow-origin, access-control-allow-headers, %s", headerStr)
		} else {
			headerStr = "access-control-allow-origin, access-control-allow-headers"
		}

		c.Header("Access-Control-Allow-Origin", "*");
		c.Header("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE");
		c.Header("Access-Control-Max-Age", "3600");
		c.Header("Access-Control-Allow-Headers", "x-requested-with,Authorization");
		c.Header("Access-Control-Allow-Credentials","true");

		//c.JSON(http.StatusOK, "Options Request!")

		c.Next()
	}
}

router：
    	r.Use(cors.Cors())
	r.POST("file", v1.Upload)

请求file接口，每次都是option请求，导致上传文件失败

**Comment by fighterlyt** [comment]
你这个肯定是跨域问题，仔细看看跨域的相关配置和处理

2018-04-15 19:41 GMT+08:00 xhochipe <notifications@github.com>:

**Comment by miaojiuchen** [comment]
@xhochipe 请问这个问题你是怎么解决的？
