### ISSUE TITLE
How to re-write Context and use HandleContext function?

### ISSUE THREAD

**Issue by xerardoo** [gin-gonic/gin#1323]
Hi, I need to add some objects to my context, and recently I looked at this function but there is no test or sample documentation of how to use it.

`func HandleContext `
https://github.com/gin-gonic/gin/blob/master/gin.go#L331

**Comment by thinkerou** [comment]
Hi @xerardoo please see #1371 explain, thanks and I will close the issue, if still have problem please reopen.

**Comment by hsb1115284873** [comment]
engine.HandleContext(context)
