### ISSUE TITLE
Creating an Engine instance with the Logger and Recovery middleware already attached

### ISSUE THREAD

**Issue by cxk280** [gin-gonic/gin#1330]
I'm trying to start a Golang/Gin project I wrote a while back on the computer I just bought, and I'm getting the following error:

```
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

dial tcp [::1]:5432: connect: connection refused
exit status 1
```

I've never seen this before. My project was built using [this](https://github.com/Massad/gin-boilerplate) as boilerplate and worked until now.

What does this error even mean? How do I fix it?

**Comment by thinkerou** [comment]
Please see here https://github.com/gin-gonic/gin/issues/1115

**Comment by appleboy** [comment]
`5432`? can't connect to postgres. see https://github.com/Massad/gin-boilerplate#installation

**Comment by cxk280** [comment]
@appleboy: Yep, that was it. I forgot to import the database in my new installation. Thanks!
