### ISSUE TITLE
Recovery middleware leaks sensitive cookies, tokens, and headers into logs

### ISSUE THREAD

**Issue by dustin-decker** [gin-gonic/gin#1331]
Session cookies, API tokens, and authorization headers are all being leaked. The request is dumped if a handler hits a panic when using the recovery middleware: https://github.com/gin-gonic/gin/blob/65a65c2edd4e86f96634a553f07a25c38f2b1c75/recovery.go#L41

This is very insecure default behavior, and there appears to be no way to opt out other than not using the middleware.

**Comment by chainhelen** [comment]
@dustin-decker sorry, how do you define "leadked". This error is just logged in server, why leadked?

**Comment by dustin-decker** [comment]
It can make passwords, cookies, or any other sensitive requests readable in plaintext logs. No production HTTP server I know of does this by default, though some can be configured to do this. 
If you ship server logs somewhere for processing, aggregation, and viewing, then the problem becomes much more severe, and a lot of companies do this.

Twitter and Github recently publicly disclosed that they've accidentally logged passwords and advised people to change them: https://arstechnica.com/information-technology/2018/05/twitter-advises-users-to-reset-passwords-after-bug-posts-passwords-to-internal-log/

I will open a PR in a few minutes to address this issue in gin.

**Comment by chainhelen** [comment]
@dustin-decker  In my opinion, This is just a log middleware.

[`custom-middleware`](https://github.com/gin-gonic/gin/blob/bf7803815b0baa22ff7a10457932882dfbf09925/README.md#custom-middleware)

```
func Logger() gin.HandlerFunc {
	return func(c *gin.Context) {
		t := time.Now()

		// Set example variable
		c.Set("example", "12345")

		// before request

		c.Next()

		// after request
		latency := time.Since(t)
		log.Print(latency)

		// access the status we are sending
		status := c.Writer.Status()
		log.Println(status)
	}
}

func main() {
	r := gin.New()
	r.Use(Logger())

	r.GET("/test", func(c *gin.Context) {
		example := c.MustGet("example").(string)

		// it would print: "12345"
		log.Println(example)
	})

	// Listen and serve on 0.0.0.0:8080
	r.Run(":8080")
}
```

I think it depend on developer，but not web framework.  
En, just  my opinion.Maybe you are right, wait for the explain of gin's member.

**Comment by appleboy** [comment]
ping @javierprovecho @thinkerou

**Comment by thinkerou** [comment]
Generally, we set username/password in body, as you say, we not log request body. If user set username/password in query param, user should encrypt self-user. As @dustin-decker pull request, remove log dump, I think it's ok, because we have panic stack. This's my option.
