### ISSUE TITLE
memory comsuption for upload file

### ISSUE THREAD

**Issue by kiwionly** [gin-gonic/gin#1332]
Hi, 

I notice that when I upload large image ~ 9MB, it consumption a lot of memory, is this normal ?

It rise from around 3MB to near 30MB. ( MS windows 10)

Is my code correct to code in this way ? or I miss out something ?

```
	form, err := ctx.MultipartForm()

	if err != nil {
		ctx.AbortWithStatusJSON(http.StatusBadRequest, CreateError(err))
		return
	}

	var fileName string
	for k := range form.File {
		fileName = k
	}

	file, err := ctx.FormFile(fileName)

	if err != nil {
		ctx.AbortWithStatusJSON(http.StatusBadRequest, CreateError(err))
		return
	}

	if file.Size > 8<<20 {
		ctx.AbortWithStatusJSON(http.StatusBadRequest, CreateError(errors.New("file size is larger than 8MB")))
		return
	}
```

Regards,
kiwi

**Comment by nazwa** [comment]
Hi Kiwi,

Some memory increase is always expected. I've got a feeling that there is some data duplication going on. 

Can you try commenting everything above and uncommenting line by line to see which part causes the jump? I'd imagine it will first increase on `form, err := ctx.MultipartForm()` and then again on `file, err := ctx.FormFile(fileName)`
