### ISSUE TITLE
how about add pointer support in binding Form Params?

### ISSUE THREAD

**Issue by qazqwe1596357** [gin-gonic/gin#1334]
I see code in https://github.com/gin-gonic/gin/blob/master/binding/form_mapping.go, we can only support value field bind, do not support pointer type.

```
// example
type Params struct {
  Pa string `form:"pa"`  // which can success bind via form_mapping
  Pb *string `form:"pb"`  // which cannot bind via form_mapping
}
```

The reason is fieldKind in "func setWithProperType()" have not pointer type. 

Supporting pointer fields bind is useful we can easy know whether we pass the param. if we not passing it, it will keep nil value.
In Json Unmarshal can process pointer field also.

So do you think supporting pointer field parse in binding/form_mapping.go is a good idea?

**Comment by ritoon** [comment]
looks done did you test the new gin version
https://github.com/gin-gonic/gin/commit/2282be059be78f9f7f70a72ca4dd3bcfe5f972ee#diff-e1ee2d6085c74d622d08bb3927e7036c

**Comment by qazqwe1596357** [comment]
The response is too fast! Thanks a lot~

**Comment by appleboy** [comment]
Implemented in https://github.com/gin-gonic/gin/pull/1336
