### ISSUE TITLE
how to use Goroutine in Gin

### ISSUE THREAD

**Issue by zdlmaxwell** [gin-gonic/gin#1335]
can I use goroutione like:
    
   router := gin.Default()
   go router.POST("test", func(c *gin.Context) {
      ......
   })

**Comment by delphinus** [comment]
What do you want?  gin is based on `net/http` package, and that serves each request by an individual goroutine.  You do not need to worry about it.

**Comment by thinkerou** [comment]
Maybe you should see https://github.com/gin-gonic/gin#goroutines-inside-a-middleware firstly.

**Comment by thinkerou** [comment]
closing.

**Comment by apriil15** [comment]
> What do you want? gin is based on `net/http` package, and that serves each request by an individual goroutine. You do not need to worry about it.

I would like to give some advice to those who have the same question as me.
1. check the comment: https://pkg.go.dev/net/http#Serve
2. use a little time to trace source code: https://github.com/golang/go/blob/08e39a196186b0b2ce852a156515001b8de190dc/src/net/http/server.go#L3084
