### ISSUE TITLE
Why does the /json folder method not add a Unmarshal

### ISSUE THREAD

**Issue by gzatxm** [gin-gonic/gin#1339]
When I use "github.com/gin-gonic/gin/json",but no method "Unmarshal",Some inconvenient.

**Comment by delphinus** [comment]
That is an internal package, and users should use `encoding/json` simply.

Or are you contributing into gin?  Then, you should send PR with it.

**Comment by thinkerou** [comment]
@gzatxm as @delphinus pointed
if you still have problem please reopen and discuss
thanks
