### ISSUE TITLE
In r.NoRoute, using c.Redirect() would panic.

### ISSUE THREAD

**Issue by 3Horse** [gin-gonic/gin#1340]
**When** Static() exists, Noroute dose not work.
So I use the following way to realize custom 404 route.

	router.NoRoute(func(context *gin.Context) {
		staticFileThatIsBeingRequested := filepath.Join("/static/", context.Request.URL.Path)

		_, err := os.Stat(staticFileThatIsBeingRequested)
		if err != nil { //
			Log.Printf("404 : %s \n", context.Request.URL.Path)
			context.Redirect(404, "/404/404.html")

		} else { //
			Log.Printf("200 : %s \n", context.Request.URL.Path)
			context.File(staticFileThatIsBeingRequested)

		}
	})

When the requested file exists, it works properly.
When the requested file doesn't exist,  panic.

2018/04/29 00:30:17 [Recovery] 2018/04/29 - 00:30:17 panic recovered:
GET /login.html0 HTTP/1.1
Host: 192.168.0.4:9001
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
Cache-Control: max-age=0
Connection: keep-alive
Cookie: session_id=36e51344e46279a70853ffc25589054d
If-Modified-Since: Thu, 20 Aug 2015 05:44:37 GMT
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Cannot redirect with status code 404
/usr/local/go/src/runtime/panic.go:502 (0x4335b8)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/home/ktv/go/src/github.com/gin-gonic/gin/render/redirect.go:20 (0x985c79)
	Redirect.Render: panic(fmt.Sprintf("Cannot redirect with status code %d", r.Code))
/home/ktv/go/src/github.com/gin-gonic/gin/context.go:645 (0x98b922)
	(*Context).Render: if err := r.Render(c.Writer); err != nil {
/home/ktv/go/src/github.com/gin-gonic/gin/context.go:704 (0x98bedf)
	(*Context).Redirect: c.Render(-1, render.Redirect{
/home/ktv/go/src/github.com/gin-gonic/gin/context.go:704 (0x98bedf)
	(*Context).Redirect: c.Render(-1, render.Redirect{
/home/ktv/workspace/chen_web/src/lib/service.go:130 (0x9a1844)
	setRouters.func1: context.Redirect(404, "/404/404.html")
/home/ktv/go/src/github.com/gin-gonic/gin/context.go:107 (0x988ef2)
	(*Context).Next: c.handlers[c.index](c)
/home/ktv/go/src/github.com/gin-gonic/gin/recovery.go:47 (0x9993a9)
	RecoveryWithWriter.func1: c.Next()
/home/ktv/go/src/github.com/gin-gonic/gin/context.go:107 (0x988ef2)
	(*Context).Next: c.handlers[c.index](c)
/home/ktv/go/src/github.com/gin-gonic/gin/logger.go:83 (0x99865b)
	LoggerWithWriter.func1: c.Next()
/home/ktv/go/src/github.com/gin-gonic/gin/context.go:107 (0x988ef2)
	(*Context).Next: c.handlers[c.index](c)
/home/ktv/go/src/github.com/gin-gonic/gin/gin.go:395 (0x9907f7)
	serveError: c.Next()
/home/ktv/go/src/github.com/gin-gonic/gin/gin.go:388 (0x99060e)
	(*Engine).handleHTTPRequest: serveError(c, 404, default404Body)
/home/ktv/go/src/github.com/gin-gonic/gin/gin.go:326 (0x98ff92)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2694 (0x67b15b)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1830 (0x6772b0)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2361 (0x463090)
	goexit: BYTE	$0x90	// NOP

**Comment by w169q169** [comment]
Hi, As msg said,  Cannot redirect with status code 404. Redirect cannot use non-3 beginning status codes, you could check definitions of [http status.](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

**Comment by 3Horse** [comment]
@w169q169  I have changed it .

context.AbortWithStatus(404)
context.File(static404FilePath)

that works.

Thank u!
