### ISSUE TITLE
can i custom request in body?

### ISSUE THREAD

**Issue by arywidiantara** [gin-gonic/gin#1353]
i want to add new variable in body request, if i log c.Request i can find that new variable, thank you

**Comment by syssam** [comment]
https://medium.com/@xoen/golang-read-from-an-io-readwriter-without-loosing-its-content-2c6911805361
It maybe help u

**Comment by syssam** [comment]
var bodyBytes []byte
			if c.Request.Body != nil {
				bodyBytes, _ = ioutil.ReadAll(c.Request.Body)
			}
			bodyString := string(bodyBytes)
			fmt.Println(bodyString)

			newBody := []byte("Here is a string....")
			c.Request.Body = ioutil.NopCloser(bytes.NewBuffer(newBody))

			if c.Request.Body != nil {
				bodyBytes, _ = ioutil.ReadAll(c.Request.Body)
			}
			bodyString = string(bodyBytes)
			fmt.Println(bodyString)

**Comment by arywidiantara** [comment]
@syssam thankyou thats work for me,
but i have another problem, if request data is json i get some error
`http: invalid Read on closed Body`

**Comment by fwhezfwhez** [comment]
if you want to work like a client 
try 
```
 client:= http.Client{}
type struct Data{
 Arg1 string
Arg2 string
}
data:=Data{arg1,arg2}
value,_ := json.Marshal(data)
req:=http.NewRequest("POST","www.xxx.com",bytes.NewReader(value))
req.Header.Set("Content-Type","application/json")
client.Do(req)
```

if you want to add a key-value for a ctx
use
```go
c.Set("username","ft")
```

**Comment by thinkerou** [comment]
closing
