### ISSUE TITLE
Runtime Error BindJson

### ISSUE THREAD

**Issue by zwhitchcox** [gin-gonic/gin#1361]
I'm using Golang 1.10 with Gin (I'm not sure the version, but I'm using just `go get github.com/gin-gonic/gin`, and I'm getting a runtime error that there is `Undefined validation function on field Username`.

This is my code 

```go
type User struct {
	Username string `json:"username" binding:"required,min=4,max=30,alphanumunicode"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required"`
}
```

And it is failing on `alphanumunicode`, as defined in the [validation documentation](https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-Alphanumeric_Unicode).

It has failed on several other documented validation functions as well. Does gin limit to a subset of these validation functions?

**Comment by zwhitchcox** [comment]
Ok, just saw in the docs, gin uses [v.8](https://godoc.org/gopkg.in/go-playground/validator.v8#hdr-Baked_In_Validators_and_Tags) which doesn't have the newer validation functions. Is this on purpose? Can we go ahead and upgrade?

**Comment by thinkerou** [comment]
#1015
