### ISSUE TITLE
How can I get map[string]string filed on PostForm?

### ISSUE THREAD

**Issue by syssam** [gin-gonic/gin#1362]
How can I get map[string]string filed on PostForm?

**Comment by Ramzec** [comment]
Not sure, but maybe something like this
```
var formDate map[string]string
err := ctx.ShouldBind(&formDate)
```

**Comment by syssam** [comment]
ShouldBindonly support struct type.

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin#another-example-query--post-form

**Comment by syssam** [comment]
現在我就是手動For loop用post form獲取，然後換成map的結構，不過其實應該gin bind的時後自動處理

從我的 iPhone 傳送

**Comment by thinkerou** [comment]
please post some example code and why must use `map`, you also consider to use custom struct, right?

**Comment by syssam** [comment]
For example, multi language
name[zh-CN] = '姓名'
name[en] = 'Name'

the map key must be pass, else, you never know what language.
It is common struct for php or another languages.

I test it, golang framework iris can handle this case , and
https://github.com/go-playground/form also.
I think gin should handle this case, right?

Currently, gin bind form is not working, I need do this for every post form
before
    for _, value := range languages {
        form.Name[value] = c.PostForm("name[" + value + "]")
    }

從我的 iPhone 傳送

田欧 <notifications@github.com> 於 2018年6月5日 14:43 寫道：

please post some example code and why must use map, you also consider to
use custom struct, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gin-gonic/gin/issues/1362#issuecomment-394599265>, or mute
the thread

**Comment by thinkerou** [comment]
@syssam please see #1383

**Comment by syssam** [comment]
Yes, I see it.
But I think we should consider more situation, because map is not only map string.That’s why I have not implement by myself.

從我的 iPhone 傳送

**Comment by thinkerou** [comment]
@syssam Yes, but I think we should do complex, as far as possible simple.

**Comment by delphinus** [comment]
Just idea, how about this to use more flexible?

```go
type QueryString string

// these methods are copied from json.Number 
func (s QueryString) String() string { return string(s) }
func (s QueryString) Float64() (float64, error) {
  return strconv.ParseFloat(string(s), 64)
}
func (s QueryString) Int64() (int64, error) {
  return strconv.ParseInt(string(s), 10, 64)
}

dict := map[string]QueryString

...
```

and usage

```go
dict := c.QueryMap("ids")
dict["a"].String() // "1234"
dict["a"].Int64()  // 1234, nil
```

**Comment by thinkerou** [comment]
#1383 have supported map parameters for query string and post form.

**Comment by syssam** [comment]
How about bind?
https://github.com/gin-gonic/gin/blob/master/binding/form_mapping.go

**Comment by thinkerou** [comment]
not support form mapping bind now.

**Comment by thinkerou** [comment]
@syssam form map bind map #1387

**Comment by syssam** [comment]
@thinkerou Ya.
I'm looking.I'm not test it. however, base on these code, your function will skip, right?
```
		inputValue, exists := form[inputFieldName]

		if !exists {
			if defaultValue == "" {
				continue
			}
			inputValue = make([]string, 1)
			inputValue[0] = defaultValue
		}
```

**Comment by thinkerou** [comment]
@syssam please read #1387 comment, and you checkout my branch https://github.com/thinkerou/gin/tree/support-map-for-map-form

**Comment by syssam** [comment]
@thinkerou sorry for the late reply.Please make a html form, you will find out the problem.

**Comment by thinkerou** [comment]
@syssam your mean is what use `text/html` header, or use `curl .... -d 'a=1&b=2'`?

**Comment by syssam** [comment]
Just like
```
<form>
  <input type="text" name="name[a]"><br>
  <input type="text" name="name[b]">
</form>
```

**Comment by appleboy** [comment]
Please try the latest version and see the document. https://github.com/gin-gonic/gin#map-as-querystring-or-postform-parameters

**Comment by kync** [comment]
I was using gorm library to update models using a map(like db.Model(&user).Updates(map[string]interface{}{"uname": "hello", "age": 18, "actived": false})), and needed a bind method that binds request body to a map. I always use a gin context wrapper it has been good  practice for me and developed below code and works well for my needs.  That would be great if implemented directly in gin.
```
//AppContext gin context wrapper
type AppContext struct {
	*gin.Context
}
//BindMap decodes body to map, skips fields which are not in allowedFields
func (context AppContext) BindMap(obj map[string]interface{}, allowedFields ...interface{}) error {
	//Provides JSON and Form content types
	if context.Request.Method == "GET" {
		return nil
	}
	contentType := context.ContentType()
	switch contentType {
	case gin.MIMEJSON:
		return context.jsonBind(obj, allowedFields)
	case gin.MIMEPOSTForm, gin.MIMEMultipartPOSTForm:
		return context.formBind(obj, allowedFields)
	default:
		return errors.New("Unsupported content type")
	}
}

//jsonBind binds json into map
func (context AppContext) jsonBind(obj map[string]interface{}, allowedFields ...interface{}) (err error) {
	body, err := ioutil.ReadAll(context.Request.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(body, &obj)
}

//jsonBind binds form into json
func (context AppContext) formBind(obj map[string]interface{}, allowedFields ...interface{}) (err error) {
	if err = context.Request.ParseForm(); err != nil {
		return err
	}
	context.Request.ParseMultipartForm(defaultMemory)
	for k, v := range context.Request.Form {
		if libs.Contains(k, allowedFields) {
			obj[k] = v[0] //take first
		}
	}
	return nil
}
//Example usage:
//fields := make(map[string]interface{})
//err = appCtx.BindMap(fields, "age", "activated" )
```

**Comment by thinkerou** [comment]
#1749 merged!

**Comment by ltpquang** [comment]
@thinkerou hmm #1749 seems not to support bind query params yet?
