### ISSUE TITLE
ShouldBind sets a default value to *time.Time, cant use with gorm package

### ISSUE THREAD

**Issue by bsbak** [gin-gonic/gin#1364]
I have struct field ``` DeletedAt *time.Time `sql:"index"` ```
After ctx.ShouldBind(&mystruct) the value of DeletedAt field is not `nil`, but must be, becouse gorm(sql) package cant auto generate NULL for that field.

The problem is there:
github.com\gin-gonic\gin\binding\form_mapping.go

```
if inputFieldName == "" {
	inputFieldName = typeField.Name

	// if "form" tag is nil, we inspect if the field is a struct or struct pointer.
	// this would not make sense for JSON parsing but it does for a form
	// since data is flatten
	if structFieldKind == reflect.Ptr {

                //!!!!!!!!!!!!!! here first we need to check if field is not time.Time (pointer to time)
                // if it is - continue
                //something like
                if structField.Type().Elem() == reflect.TypeOf(time.Time{}) {
                          continue
                 }
                //-------------------------------
		if !structField.Elem().IsValid() {

                        //!!!!!!!!!!!! here is the problem, why set default value?????????? I need nil!!!
			structField.Set(reflect.New(structField.Type().Elem()))
		}
		structField = structField.Elem()
		structFieldKind = structField.Kind()
	}
	if structFieldKind == reflect.Struct {
		err := mapForm(structField.Addr().Interface(), form)
		if err != nil {
			return err
		}
		continue
	}
}
```

**Comment by syssam** [comment]
Using `form:"-"` ignore DeletedAt field

**Comment by bsbak** [comment]
@syssam yes it works, but bad that now i cant embed predefined struct gorm.Model and must rewrite every struct:
```
// gorm.Model
type Model struct {
    ID        uint `gorm:"primary_key"`
    CreatedAt time.Time
    UpdatedAt time.Time
    DeletedAt *time.Time `gorm:"index"`
}
```

**Comment by syssam** [comment]
Surely, However you can custom your own gorm.Model
I haven't using gorm.Model directly, because I think the ID name should be different on every Model.
Therefore, I have not this problem.

**Comment by thinkerou** [comment]
ref #610 @syssam should use `binding:"-"`, not `form:"-"`.

**Comment by syssam** [comment]
the binding tag is base on https://github.com/gin-gonic/gin/blob/master/binding/default_validator.go
It register TagName: "binding", you can register another name, like validate

**Comment by yangjianhua** [comment]
@bsbak  Hi, could you tell me how to solve this problem?

I tried, write a BaseModel just like gorm.Model, and set the `form:"-"`, it still not ignore "created_at", "updated_at" and "deleted_at" field.

Hope you have solved the problem, thanks in advance.

**Comment by bsbak** [comment]
@yangjianhua without seeing ur code cant say anything. form:"-" solved my problem. Try use db.Omit("created_at, updated_at, deleted_at").Create(...)

**Comment by yangjianhua** [comment]
@bsbak Thanks you, but omit only work on update method, right?

It seems not work on create
