### ISSUE TITLE
Context.Stream breaks on google app engine

### ISSUE THREAD

**Issue by wolfgangmeyers** [gin-gonic/gin#1366]
I noticed this problem when trying to use Context.Stream on google app engine. This line in response_writer.go is causing a panic:

https://github.com/gin-gonic/gin/blob/master/response_writer.go#L108

The error stack I'm getting looks like this:
```
panic: interface conversion: *appengine_internal.aecontext is not http.CloseNotifier: missing method CloseNotify

goroutine 7 [running]:
panic(0x181be80, 0xc0135467c0)
	go/src/runtime/panic.go:489 +0x2cf
github.com/gin-gonic/gin.(*responseWriter).CloseNotify(0xc016d9da20, 0x1c)
	github.com/gin-gonic/gin/response_writer.go:108 +0x43
github.com/gin-gonic/gin.(*Context).Stream(0xc016d9da20, 0xc008433588)
	github.com/gin-gonic/gin/context.go:769 +0x42
```

**Comment by wolfgangmeyers** [comment]
Opened this PR to address the issue - https://github.com/gin-gonic/gin/pull/1367

**Comment by appleboy** [comment]
@wolfgangmeyers Please fix the testing in your PR. Thanks.

**Comment by wolfgangmeyers** [comment]
Will do, sorry about that.

**Comment by thinkerou** [comment]
@wolfgangmeyers any progress? Please

**Comment by wolfgangmeyers** [comment]
Sorry, I ended up not using this. Going to close the issue.
