### ISSUE TITLE
go1.10.2 can't build with gin.

### ISSUE THREAD

**Issue by nevata** [gin-gonic/gin#1368]
# crypto/x509
In file included from /System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /System/Library/Frameworks/Security.framework/Headers/Security.h:43,
                 from /usr/local/Cellar/go/1.10.2/libexec/src/crypto/x509/root_cgo_darwin.go:17:
/System/Library/Frameworks/Security.framework/Headers/Authorization.h:192:7: error: variably modified 'bytes' at file scope
  char bytes[kAuthorizationExternalFormLength];
       ^~~~~

**Comment by appleboy** [comment]
Post your example code.
