### ISSUE TITLE
How to return custom error with Gin

### ISSUE THREAD

**Issue by latipovsharif** [gin-gonic/gin#1372]
I've asked a question in [stackoverflow](https://stackoverflow.com/questions/50523102/how-to-return-custom-error-with-gin) but cannot give answer for my question please can anybody look at it.

**Comment by syssam** [comment]
https://github.com/go-playground/validator/blob/v9/_examples/translations/main.go

**Comment by chainhelen** [comment]
[stackoverflow.com#how-to-return-custom-error-with-gin](https://stackoverflow.com/questions/50523102/how-to-return-custom-error-with-gin)
```
how to get structs json tag for field ?
``` 

You can get the tag by `reflect`

**Comment by latipovsharif** [comment]
Could you write an example of how to do that?

**Comment by syssam** [comment]
I have a simple sample here, you can reference here.
https://github.com/syssam/go-playground-sample/blob/master/main.go

I'm using v9, gin is using v8, you can upgrade the version follow this step.
https://github.com/go-playground/validator/tree/v9/_examples/gin-upgrading-overriding

**Comment by chainhelen** [comment]
@syssam Oh, it is excellent.

**Comment by latipovsharif** [comment]
@syssam Thank you very much.

**Comment by latipovsharif** [comment]
@syssam but how can use it with BindJSON?

**Comment by syssam** [comment]
BindJSON will bind the data and call binding.validate function.
Try you self first.
https://github.com/gin-gonic/gin/blob/master/binding/json.go

**Comment by latipovsharif** [comment]
@syssam thank you very much, you saved a lot of time for me!

**Comment by blackgreen100** [comment]
See also this for an example with latest Gin and validator versions: [Return custom error message from struct tag validation](https://stackoverflow.com/q/70069834/4108803)
