### ISSUE TITLE
How to get row binary data

### ISSUE THREAD

**Issue by DineshGuptaa** [gin-gonic/gin#1374]
Hi All,
I am newbie for Golang. I have to create the application that capture the audio raw data & post to the service. But I am unable to find the way to get the data server side. 

Please help me to get the data at server end

    `function sendAudio (dataView) {
	    return new Promise((resolve, reject) => {
	      var xhr = new XMLHttpRequest();
	      var url = 'https://localhost/soerest/api/v1/echo';
	      xhr.open('POST', url, true);
	      xhr.responseType = 'arraybuffer';
	      xhr.onload = (event) => {
	        console.log(xhr.response);
	      };

	      xhr.onerror = (error) => {
	          console.error(error);
	      };

	      xhr.onerror = (error) => {
	        this._log(error);
	        reject(error);
	      };
	      var BOUNDARY = 'BOUNDARY1234';
	      var BOUNDARY_DASHES = '--';
	      var NEWLINE = '\r\n';
	      var AUDIO_CONTENT_TYPE = 'Content-Type: audio/L16; rate=16000; channels=1';
	      var AUDIO_CONTENT_DISPOSITION = 'Content-Disposition: form-data; name="audio"';

	      var postDataStart = [
	        NEWLINE, BOUNDARY_DASHES, BOUNDARY, NEWLINE,
	        AUDIO_CONTENT_DISPOSITION, NEWLINE, AUDIO_CONTENT_TYPE, NEWLINE, NEWLINE
	      ].join('');

	      var postDataEnd = [NEWLINE, BOUNDARY_DASHES, BOUNDARY, BOUNDARY_DASHES, NEWLINE].join('');

	      var size = postDataStart.length + dataView.byteLength + postDataEnd.length;
	      var uint8Array = new Uint8Array(size);
	      let i = 0;

	      for (; i < postDataStart.length; i++) {
	        uint8Array[i] = postDataStart.charCodeAt(i) & 0xFF;
	      }

	      for (var j = 0; j < dataView.byteLength; i++, j++) {
	        uint8Array[i] = dataView.getUint8(j);
	      }

	      for (var j = 0; j < postDataEnd.length; i++, j++) {
	        uint8Array[i] = postDataEnd.charCodeAt(j) & 0xFF;
	      }
	      var payload = uint8Array.buffer;
	      
	      xhr.setRequestHeader('Content-Type', 'multipart/form-data; boundary=--' + BOUNDARY);
	      xhr.send(payload);
	    });
	  }
`

My server side code is as

    `func (spr *SpeechHandler) Speeche(c *gin.Context) {

	// curl -i http://localhost:8080/api/v1/echo
	fmt.Println("echo method has been called: ")
	// Multipart form
	multipart, err := c.Request.MultipartReader()//c.MultipartForm()
	if err != nil {
		c.String(http.StatusBadRequest, fmt.Sprintf("get form err: %s", err.Error()))
		return
	}
	for {
		mimePart, err := multipart.NextPart()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Printf("Error reading multipart section: %v", err)
			break
		}
		disposition, params, err := mime.ParseMediaType(mimePart.Header.Get("Content-Disposition"))
		if err != nil {
			break
		}
	}
    }`

I am getting error
    `multipart: NextPart: EOF`

Please help me where I am doing wrong. I am stuck here :-(

Thanks you to all in advance.

Regards,
Dinesh Gupta

**Comment by thinkerou** [comment]
please read #854  thanks! (you should search old issue before ask question

**Comment by DineshGuptaa** [comment]
Thanks
