### ISSUE TITLE
How is concurrency in gin

### ISSUE THREAD

**Issue by WhoisZihan** [gin-gonic/gin#1378]
Hi,

I'm wondering if gin support concurrent process of requests. If I have much more clients than server, does gin have a goroutine for each request or it process every request in sequence? If it does support, is there an example to get high concurency?

Thanks

**Comment by thinkerou** [comment]
please see #1335 (please search issue and pull request before ask question) thanks!

**Comment by WhoisZihan** [comment]
Thanks for the answer
