### ISSUE TITLE
bind to string in post body

### ISSUE THREAD

**Issue by zwhitchcox** [gin-gonic/gin#1380]
So, my post request looks something like this:

```js
fetch('/endpoint', {method: "POST", body: "my string"})
```

And, I'm trying to bind the body to a string like this:

```golang
var x string
c.Bind(&x)
```

But I'm getting the error `reflect: NumField of non-struct type`.

What is the appropriate way to get the body as a string, or do I need to just use the http Request.Body as a reader?

**Comment by zwhitchcox** [comment]
Was able to accomplish my goal with 3 lines:

```golang
	buf := new(bytes.Buffer)
	buf.ReadFrom(c.Request.Body)
	str := buf.String()
```

where str is the string containing the post body

**Comment by luga97** [comment]
> Was able to accomplish my goal with 3 lines:
> 
> ```go
> 	buf := new(bytes.Buffer)
> 	buf.ReadFrom(c.Request.Body)
> 	str := buf.String()
> ```
> 
> where str is the string containing the post body

Why is this not possible with Bind? Out of curiosity.

**Comment by Rospaccio** [comment]
A possible alternative:

```
        // c *gin.Context
	data, _ := c.GetRawData()
	text := fmt.Sprintf("%s", data)
```
