### ISSUE TITLE
Upgrade golang version?

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#1381]
Now golang have released version 1.10, and gin have not use 1.7 or 1.8 `context` feature and so on.
We may point out `require golang 1.7` and `require golang 1.8` period of time.

ref: https://golang.google.cn/doc/devel/release.html#policy

**Comment by appleboy** [comment]
maybe we can add notes in README?

**Comment by thinkerou** [comment]
Yes @appleboy and add notes when starting gin, it's my option.

**Comment by appleboy** [comment]
@thinkerou Could you send the PR? thanks.

**Comment by thinkerou** [comment]
@appleboy Done, but now only add some readme and debug warn, when we upgrade go version later, we also need update these info.

**Comment by bjm88** [comment]
I'm on go 1.10.x but still getting this GIN-debug warning GIN-debug] [WARNING] Now Gin requires Go 1.6 or later and Go 1.7 will be required soon .  why ???

**Comment by BattleBas** [comment]
@thinkerou should the warning message not be printed if you are using a version higher then the required? I don't think I understand your comment about the warning being "fixed". Thanks!

I'm using 1.11 at the moment and was confused when I saw the warning thinking gin was somehow using an older version. Other users might run into a similar issue.

**Comment by thinkerou** [comment]
@bjm88 @BattleBas Hi, on #1572 I add go version judge, please help me review, thanks!

**Comment by thinkerou** [comment]
Suggestion:
- Maybe gin v1.5.0 no longer support go1.6 and gin v1.6.0 no longer support go1.7.
- And we also need to test gin bench every go version.

**Comment by mvolkmann** [comment]
I agree with others that this warning message about requiring Go 1.6 or later should not be output when we are running a newer version. I am on 1.12 and still see that warning every time a start a server that uses gin.

**Comment by dmarkham** [comment]
@appleboy  @thinkerou  Looks like we need to move on this sooner rather than latter. It looks like all `go1.6` builds are now just failing. With `go1.12` released and `go1.13` getting close. We should be killing off everything less than `go1.10`!

**Comment by thinkerou** [comment]
> go1.6 builds are now just failing

Yes.

> We should be killing off everything less than go1.10!

This is a daring plan. But I think we should only remove `go1.6`&`go1.7` support at `gin1.4.x`(transition time), and `gin1.5.x` will remove `go1.8`&`go1.9`. do you think?

**Comment by dmarkham** [comment]
Sorry, We should only kill 1.6 & 1.7 until we get  `go1.4.0` out.

**Comment by thinkerou** [comment]
#1851 merged!
