### ISSUE TITLE
Run Api's on port 8080 with https

### ISSUE THREAD

**Issue by Swatiparbhakar** [gin-gonic/gin#1384]
Hello, 
I am using gin-gonic for my application. I want to run all my api's on port 8080 with https method.
I am using below structure. Let me know if I need to follow the extra steps for this.
        <pre>r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run()</pre>

**Comment by chainhelen** [comment]
@Swatiparbhakar 
[gin.go#L282-L300](https://github.com/gin-gonic/gin/blob/caf3e350a548af1add9def68087ac53d1d000caa/gin.go#L282-L300) use `RunTLS` instead of `Run`

**Comment by Swatiparbhakar** [comment]
@chainhelen 
Thanks for your reply.
Can we use .crt file as well?

**Comment by chainhelen** [comment]
@Swatiparbhakar Just like  `RunTLS(":8080", "server.crt", "server.key")` 

In fact，see [gin.go#L294-L300](https://github.com/gin-gonic/gin/blob/07cbe116a058f13026fa6b23f675155968d47cc3/gin.go#L294-L300), it depend on `golang net/http ListenAndServeTLS`

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin/tree/master/examples/http2 @Swatiparbhakar
