### ISSUE TITLE
gin overrides status code and Content-Type

### ISSUE THREAD

**Issue by zwhitchcox** [gin-gonic/gin#1385]
So, if I use `c.BindJSON(&mystruct)`, and this fails, and then, I respond with my error message, `c.JSON(406, gin.H{"message", "my message"})`, gin overrides this and still responds with 400...So, I'd rather be able to set my own reponse code, but then, it also changes `Content-Type` to `text/plain`. Is this the undocumented intended behavior, or is this a bug?

**Comment by thinkerou** [comment]
If you can post some example code it's better, I search some old issue, maybe them useful, uncertainty.

**Comment by delphinus** [comment]
You'd better use `c.ShouldBindJSON()`.  `c.Bind*` will validate and set response if it has error.  `c.ShouldBind*` will validate only.

**Comment by syssam** [comment]
@delphinus right.
