### ISSUE TITLE
Issue with binding gorm.Model and pointer fields as a whole

### ISSUE THREAD

**Issue by tabula-rasa** [gin-gonic/gin#1386]
Hello. I have noticed, that Bind method does not work correctly with [gorm.Model's](http://gorm.io/docs/conventions.html#gorm-Model) DeletedAt pointer field. Binder populates it with a 0001-01-01 00:00:00+00 timestamp, though I don't have it set in the html form. This leads to an unexpected behavior, when newly created record (say User model, embedding gorm.Model struct) has not null DeletedAt timestamp and hence marked as deleted. Of course I can override gorm.Model with my own type and set `binding:"-"` to DeletedAt field, but this looks weird to me :) Thank you.
Ps: Just checked: binding:"-" tag does not help.

**Comment by tabula-rasa** [comment]
Just checked: `binding:"-"` tag does not help.

**Comment by syssam** [comment]
I think it is not a problem.Gin will set the default value(0001-01-01 00:00:00+00) when binding.
When DeletedAt is not nil, gorm.Model will not set the value, so you need set binding:"-" to tell gin which field should bind or not.

Else you need custom the gin bind function, to tell which Field is gorm.Model using.But I think it will hard to debug.Therefore, just add "-" tag

**Comment by tabula-rasa** [comment]
I see your point, but the default value for a *time.Time field is expected to be nil, atleast by all "orm"-s and their like. I tried binding:"-", but it unfortunately does not work in this case.

**Comment by syssam** [comment]
just try using form:"-", not binding:"-"
