### ISSUE TITLE
Non-semver release tags don't work with vgo

### ISSUE THREAD

**Issue by bcl** [gin-gonic/gin#1388]
I'm experimenting with vgo, and it won't recognize the v1.2 release when I list available releases:
    vgo list -t github.com/gin-gonic/gin
    github.com/gin-gonic/gin
        v1.1.1
        v1.1.2
        v1.1.3
        v1.1.4

I'm pretty sure this is because it is expecting semver tags. Would it be possible for you to add a tag for v1.2.0?

**Comment by thinkerou** [comment]
Hi @bcl gin have had `v1.2` tag, I think that it's `vgo` bug.
For example(in fact `hugo` have also `v0.41` and `v0.42` tag

```shell
➜  basic git:(vgo) ✗ vgo list -t github.com/gohugoio/hugo
github.com/gohugoio/hugo
	v0.18.1
	v0.20.1
	v0.20.2
	v0.20.3
	v0.20.4
	v0.20.5
	v0.20.6
	v0.20.7
	v0.22.1
	v0.24.1
	v0.25.1
	v0.27.1
	v0.30.1
	v0.30.2
	v0.31.1
	v0.32.1
	v0.32.2
	v0.32.3
	v0.32.4
	v0.36.1
	v0.37.1
	v0.38.1
	v0.38.2
	v0.40.1
	v0.40.2
	v0.40.3
```

**Comment by thinkerou** [comment]
Oh @bcl I see your comment https://github.com/golang/go/issues/25656#issuecomment-396092839

**Comment by DonMcNamara** [comment]
There is some discussion here:
https://github.com/golang/go/issues/23954#issuecomment-367098952

```Semver is always three numbers, and we only allow the canonical form so that there's no ambiguity about what if v1.1 and v1.1.0 are both defined.```

And here is the relevant part of the [semver spec](https://semver.org/):
```
A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.
```

**Comment by bcl** [comment]
Thanks for the pointer, I had missed that discussion. It's pretty clear that projects are going to need to use semver tagging and that vgo isn't going to kludge around it (other than the v0.0.0 commit hash option).

So it would be helpful if a v1.2.0 tag could be added, I don't see any reason why not, the next version is going to be v1.2.1 anyway, right?

**Comment by thinkerou** [comment]
change logs for v1.3.0 #1478

**Comment by thinkerou** [comment]
Hi, everybody v1.3.0 have released! https://github.com/gin-gonic/gin/releases/tag/v1.3.0
actually, vgo have support v1.2 style, please see https://github.com/golang/vgo/commit/afe80cfef620e1ab15b5ad9f9152ff6f7f3611d5
