### ISSUE TITLE
Question: Versioning formats: path and query string parameter

### ISSUE THREAD

**Issue by RoboFlax** [gin-gonic/gin#1395]
Hey,

im wondering how a sample code would look like that allows the REST-API user to specify the api version through the path or  query string paramter.

Reference: https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#121-versioning-formats

Can someone give me an example how it could be done?

**Comment by thinkerou** [comment]
please read readme https://github.com/gin-gonic/gin#parameters-in-path thanks
