### ISSUE TITLE
Can I use Client Cert for Auth in Gin?

### ISSUE THREAD

**Issue by Karmadon** [gin-gonic/gin#1397]
I use TLS connection with GIN
Now I need to implement client certificate authorization.
It's possible?

**Comment by thinkerou** [comment]
Hi @Karmadon https://github.com/gin-gonic/gin/tree/master/examples/http2 can you help?

**Comment by Karmadon** [comment]
@thinkerou THX

**Comment by VitaliyBratyshov** [comment]
For those who are interested, the example was moved here -  https://github.com/gin-gonic/examples/tree/master/http2

**Comment by ZenkieBear** [comment]
> For those who are interested, the example was moved here - https://github.com/gin-gonic/examples/tree/master/http2

I don't think that's a solution.
The Client cert checking is for mTLS, it needs configuration with TLS, but GIN didn't provide api to define this.
You can refer to this document https://venilnoronha.io/a-step-by-step-guide-to-mtls-in-go

**Comment by alexv-ds** [comment]
Example for gin 🙂

https://www.bastionxp.com/blog/api-gateway-security-mtls-authentication/
