### ISSUE TITLE
import gin  error 

### ISSUE THREAD

**Issue by zhagnfan** [gin-gonic/gin#1409]
run dep ensure error
Solving failure: No versions of github.com/mattn/go-isatty met constraints:
	v0.0.3: unable to deduce repository and source type for "golang.org/x/sys/unix": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sys/unix?go-get=1": Get http://golang.org/x/sys/unix?go-get=1: dial tcp 216.239.37.1:80: i/o timeout
	
looks like  can't find the package 'golang.org/x/sys/unix'

**Comment by thinkerou** [comment]
maybe you can consult https://github.com/gin-gonic/gin/pull/1128
