### ISSUE TITLE
failed to parse form to custom struct

### ISSUE THREAD

**Issue by micln** [gin-gonic/gin#1410]
sample code

```go
type A struct {
	b B
	c int
}

type B strcut{}

a := new(A)
c.bind(a)
```

first problem, if the field `b` parse failed, the code will return `errors.New("Unknown type")` (https://github.com/gin-gonic/gin/blob/master/binding/form_mapping.go#L129) and field c is no longer to parse. is it a bug ?

second, can you support custom parse for struct by a  interface. such as 

```go
type B strcut{}

type formParser interface{
	ParseForm([]string)
}

func (b *B) ParseForm(value []string) {
	
}
```

**Comment by thinkerou** [comment]
please see https://github.com/gin-gonic/gin#bind-form-data-request-with-custom-struct first, thanks!

**Comment by micln** [comment]
@thinkerou

just second problem is about how to parse custom struct

first problem means if parse field b failed. I hope gin would skip this filed and parse the rest fields c and other. so I could parse the failed field in my way. but now gin will stop parse and return err

**Comment by thinkerou** [comment]
because here return https://github.com/gin-gonic/gin/issues/279
but I think the case which continue to parse is a few cases, maybe gin should not do it, in my option.

**Comment by syssam** [comment]
@micln All right.
Gin bind form is implement very simple and have some inadequacies.However it is not easily to implement.
I think you should use ShouldBindJSON is better.

**Comment by chainhelen** [comment]
@micln ShouldBindJSON
