### ISSUE TITLE
Slash in optional paramters

### ISSUE THREAD

**Issue by sameer-coder** [gin-gonic/gin#1412]
Issue : I tried to use optional path parameters using a _wildcard(*)_ as mentioned in the documentation but when I parse the parameters  the last parameter also _includes a slash_

**Route :**
v1.DELETE("/userdata/jobs/:requestid/*trackingID",userdata.Request)

**Hitting the api using a REST client :** 
curl -X DELETE   http://127.0.0.1:9001/v1/userdata/jobs/123/555

**In controller:**
	requestid := c.Param("requestid")
	trackingID := c.Param("trackingID")

I get requestid as **123** and trackingID as **/555**

Why is the slash being included and gin is not auto detecting the parameter?

**Comment by thinkerou** [comment]
please see https://github.com/gin-gonic/gin/pull/1061 , but the pr need to cr.

**Comment by thinkerou** [comment]
And https://github.com/julienschmidt/httprouter/issues/222 https://github.com/julienschmidt/httprouter/issues/77 discuss reasoning.

**Comment by sameer-coder** [comment]
Thanks for the update @thinkerou
