### ISSUE TITLE
Does Gin support try_files capabilities like nginx?

### ISSUE THREAD

**Issue by ldnvnbl** [gin-gonic/gin#1414]
I want to do like bellow nginx conf with gin, so how to do?  thanks somebody can help me.
```
location / {
    try_files $uri $uri/ /index.html;
  }
```

**Comment by thinkerou** [comment]
IMO, gin not support and gin should not support, but what's your case?

**Comment by ldnvnbl** [comment]
@thinkerou I write a web app that use web router not server router. It's sounds I should use nginx before gin server.

**Comment by thinkerou** [comment]
Yes, you can use `"/*action"`, closing and still have problem please reopen, thanks!
