### ISSUE TITLE
when release next version?

### ISSUE THREAD

**Issue by wongoo** [gin-gonic/gin#1420]
it's a long time from the latest v1.2 released on Jul 2, 2017, when will be the next version released?

**Comment by tyan-boot** [comment]
New release needed.

My project which depends on "ShouldBindJSON" broken when i use v1.2 instead master. I use dep to update my dependences.

**Comment by junweiyang** [comment]
@javierprovecho please

**Comment by appleboy** [comment]
duplicate of #1239
