### ISSUE TITLE
hello,here  i have a question,/:mark/:index conflicts to /:mark/:query because wildcast

### ISSUE THREAD

**Issue by fwhezfwhez** [gin-gonic/gin#1422]
How can i change to fit two types of param filling like:
r.GET("/:mark/:index",f1)
r.GET("/:mark/:query",f2)

**Comment by syssam** [comment]
@fwhezfwhez @rhettli 
https://github.com/julienschmidt/httprouter/issues/175

**Comment by fwhezfwhez** [comment]
3q,i get it
