### ISSUE TITLE
How can I make the param bind like this ?

### ISSUE THREAD

**Issue by clearcodecn** [gin-gonic/gin#1424]
I have a url like that 
```
http://somesite.com/blog/1.html
```

code like that : 
```
r.GET("/blog/:id.html", func(ctx *gin.Context){
    id := ctx.Param("id")   // can`t get 
    id2 := ctx.Param("id.html")  // get 1.html  
})
```
I only want Id , how can I do about it !

**Comment by thinkerou** [comment]
because `id.html` is a coherent whole, you may be split `id2`, IMO.

**Comment by clearcodecn** [comment]
Will Gin Support it ?

**Comment by thinkerou** [comment]
Please read readme https://github.com/gin-gonic/gin#parameters-in-path thanks!

**Comment by syssam** [comment]
I think you can custom the middleware to do this.
It's not hard and few code.
https://github.com/gin-gonic/gin#custom-middleware

**Comment by clearcodecn** [comment]
ok thanks !
