### ISSUE TITLE
How can I change timezone when render time 

### ISSUE THREAD

**Issue by thuandoan274** [gin-gonic/gin#1429]
I want when render time by format json, it should be 
```2018-07-12T09:57:04.603Z```
But it auto change render to timezone +7  
```2017-11-10T09:15:07.519+07:00```
How can change timezone all whole project when render

**Comment by delphinus** [comment]
How about this?

```go
var someLocation *time.Location

func init() {
  someLocation, _ = time.LoadLocation("Some/Zone")
}

func timeInSomeLocation(t time.Time) time.Time {
  return t.In(someLocation)
}

func someHandler(c *gin.Context) {
  c.JSON(200, gin.H{
    "now": timeInSomeLocation(time.Now()),
  })
}
```

**Comment by thuandoan274** [comment]
I've solved that problem. Just set 
``` time.Local = time.UTC```
I met that problem when query from mongodb. @delphinus I think your idea is good for specify case. Thank you!
