### ISSUE TITLE
using socket.io in gin

### ISSUE THREAD

**Issue by qianqianyeye** [gin-gonic/gin#1430]
I tried to use socket.io in gin,but I met a problem,I use it this way
`     router.GET ( "/socket.io/",socketHandler)

	router.POST ( "/socket.io/",socketHandler)

	router.Handle ( "WS", "/socket.io/", socketHandler )

	router.Handle ( "WSS", "/socket.io/",socketHandler )`
and socketHandler
        `       sio.On("/", func() {
  
		log.Println("connect-----------")

	})

	sio.Of("/android").On("connect", func(ns *socketio.NameSpace) {

		KeyMap[ns.Id()]=ns

		log.Println("Pol Connected: ", ns.Id())

	})

	sio.Of("/android").On("disconnect", func(ns *socketio.NameSpace) {

		delete(KeyMap, ns.Id())

		log.Println("Pol Disconnected: ", ns.Id())

	})

       sio.ServeHTTP(c.Writer,c.Request)`

After page access, there is a  socketHandler method,but No output,Then the console prints 404.
The console has a lot of output 
`[GIN] 2018/07/16 - 00:16:38 | 404 |            0s |             ::1 | GET      /socket.io/?EIO=3&transport=polling&t=MIUkiRZ

`

**Comment by appleboy** [comment]
See my example:

https://github.com/go-ggz/ggz/blob/master/router/router.go#L120-L124

**Comment by doquangtan** [comment]
Use can use this lib [socket.io golang](https://github.com/doquangtan/socket.io-golang). It is socketio server version 4.x and it can using with client version 3.x, 4.x
