### ISSUE TITLE
Can we have a new Gin Gonic version, e.g. 1.3?

### ISSUE THREAD

**Issue by derFunk** [gin-gonic/gin#1434]
1.2 has been released one year ago.

Since then, a lot of new stuff came in to Gin Gonic: https://github.com/gin-gonic/gin/compare/v1.2...master.

When using a package management like `glide` which is using semantic versioning, `1.2` is the last version number available, missing a lot of the new stuff.

Could we get a version update soon?

**Comment by thinkerou** [comment]
please see #1239

**Comment by javierprovecho** [comment]
check #1478 for v1.3.0 changelog preview
