### ISSUE TITLE
repository does not work

### ISSUE THREAD

**Issue by SuccessorZailong** [gin-gonic/gin#1437]
can not add packages  from github.com/gin-gonic/gin@v1.2, I wonder if the repository work well?

**Comment by thuandoan274** [comment]
Can you give more information like screenshots ?

**Comment by SuccessorZailong** [comment]
![qq 20180724084634](https://user-images.githubusercontent.com/30924128/43110358-1beb5854-8f1e-11e8-9fb1-9c899e38d6c1.png)
![qq 20180724084916](https://user-images.githubusercontent.com/30924128/43110437-78d764a4-8f1e-11e8-84e4-59b215fe695f.png)

**Comment by thinkerou** [comment]
you can not request `github.com/gin-gonic/gin@v1.2`
