### ISSUE TITLE
c *gin.Context get parameter

### ISSUE THREAD

**Issue by qianqianyeye** [gin-gonic/gin#1439]
If I write this,c is *gin.Context

````
buf := make([]byte, 1024)                                                                                                      
id := c.PostForm("id")
fmt.Println(id)
n, _ := c.Request.Body.Read(buf)
var str string = string(buf[0:n])
````

I can get it id value,But I can't get str value

If I write this,

````
buf := make([]byte, 1024)

n, _ := c.Request.Body.Read(buf)

var str string = string(buf[0:n])
````

I can get str value

Now,I think  get the value of the two variables at the same time,How should I write?

c.PostForm does not get c.Request.Body.Read after execution,Vice versa

**Comment by thinkerou** [comment]
maybe you see #1341 which can help you.

**Comment by thinkerou** [comment]
duplicated #1295
