### ISSUE TITLE
gin.Context should use sync.Map

### ISSUE THREAD

**Issue by ajackson-cpi** [gin-gonic/gin#1449]
I'm seeing a "concurrent map" crash where a gin.Context.Copy() product in another goroutine is modifying a key while it's being read elsewhere. context.Context (which is the interface being implemented) will not have a problem with this.

**Comment by thinkerou** [comment]
but `sync.Map` in `go1.9` and `go1.9+`

**Comment by himyxia** [comment]
are there any circumstances that `context.Copy()` are called by multiple concurrency goroutines ?

**Comment by thinkerou** [comment]
ref #700 #1317 #1335
