### ISSUE TITLE
gin.Context Done() function does not work as expected

### ISSUE THREAD

**Issue by bonjefir** [gin-gonic/gin#1452]
I need to determine(in server-side) a request is cancelled from client. In the following code it take 5min even if we cancel the request from client to return `handleFunc`. But same code using the `net/http` package works [properly](https://play.golang.org/p/dbMWLnzUTl-).
```
func handleFunc(c *gin.Context) {
    ch := make(chan error, 1)
    go func() {
        time.Sleep(5 * time.Minute)
        ch <- nil
    }()

    select {
    case err = <-ch:
        fmt.Println(err)
    case <-c.Done():
        err = c.Err()
        fmt.Println(err)
    }

    c.HTML(200, "results", {})
}
```

**PS:** 

1) I used `go version go1.10.1 linux/amd64`

2) And `gin` commit: `a712f77`

**Comment by bonjefir** [comment]
Using `case <-c.Request.Context().Done():` instead of `case <-c.Done():` solved the problem

**Comment by syssam** [comment]
if solved the problem, please close the pr

**Comment by lorencio1** [comment]
The issue should be reopened.

Currently the function is like:

```go
// Done returns a channel that's closed when work done on behalf of this
// context should be canceled. Done may return nil if this context can
// never be canceled. Successive calls to Done return the same value.
func (c *Context) Done() <-chan struct{} {
	return nil
}
```

`return nil` make it useless and non-intuitive.

**Comment by thinkerou** [comment]
@lorencio1 please see #1690

**Comment by thinkerou** [comment]
merged
