### ISSUE TITLE
Check/Save http.Response before sending it back ?

### ISSUE THREAD

**Issue by dengoswei** [gin-gonic/gin#1455]
The `writermem` privated member inside gin.Context make it hard to wrapper the default http.ResponseWriter instance. 

Can I PR a new function to Wrapper/Replace the default http.ResponseWriter ?

**Comment by dengoswei** [comment]
Why We need wrapper the default http.ResponseWriter: 

1. Check http.Response before it send back to client, ie: encode checking, ..; 
2. Replace the response if StatusCode != 200 in some case;

**Comment by syssam** [comment]
Just simple write a middleware to handle this.

**Comment by syssam** [comment]
`c.AbortWithStatusJSON`
reference
https://github.com/gin-gonic/gin/blob/master/recovery.go

**Comment by dengoswei** [comment]
thx. but: 
1. AbortWithStatus doesn't work yet, I don't see anyway in the code check IsAbort; 
2. AbortWithStatus only work if HandlerFunc panic before call any Write/WriteHeader; 

Anyway, I dig little more into gin code, and decide that using decorator to work with the "save or replace the response before sending it to gin.Context".

**Comment by syssam** [comment]
I tested it.It should be work.

**Comment by dengoswei** [comment]
Don't fit the need, event it work..

**Comment by Mehrdad-Dadkhah** [comment]
@dengoswei 

Can help you this solution: https://stackoverflow.com/a/38548555/3994010 ?
