### ISSUE TITLE
Can I add some process before validator? 

### ISSUE THREAD

**Issue by pencil001** [gin-gonic/gin#1456]
According the code, the validator will run immediately after json decode. But I want to change some value before validator, for example, trim the string.

Is there some ways to arrive the target?

```
func decodeJSON(r io.Reader, obj interface{}) error {
	decoder := json.NewDecoder(r)
	if EnableDecoderUseNumber {
		decoder.UseNumber()
	}
	if err := decoder.Decode(obj); err != nil {
		return err
	}
	return validate(obj)
}
```

**Comment by syssam** [comment]
disable binding validation, then call validate by yourself
```
func init() {
    gin.DisableBindValidation()
}
```

**Comment by pencil001** [comment]
thx, I'll try it
