### ISSUE TITLE
change to test_helpers.go causes flag parsing to fail for cmd line app

### ISSUE THREAD

**Issue by srowles** [gin-gonic/gin#1462]
I have a command line app that imports some libraries that also import gin.

There has been a change to a non-test file - test_helpers.go that includes net/http/httptest under this PR. httptest should only be used in a file called _test.go to ensure it is excluded from compilation for non test code.

The PR is:

https://github.com/gin-gonic/gin/pull/1433

This is now causing my app to show httptest.serve as an option in flags:

```
  -httptest.serve string
        if non-empty, httptest.NewServer serves on this address and blocks
```

I also have a naive flag parser that requires all flags to have a value, so this change makes my app fail to run as there is an empty value for that flag.

Please can you revert this PR.

Thank you.

**Comment by thinkerou** [comment]
I commit one pull request which attempt to fix it, please see and use it test, thanks! #1463

**Comment by srowles** [comment]
@thinkerou that fixes the problem, yes
