### ISSUE TITLE
Custom validator documentation is incorrect

### ISSUE THREAD

**Issue by kurtzur** [gin-gonic/gin#1464]
The example code throws an `error binding.Validator.Engine undefined (type binding.StructValidator has no field or method Engine)`:

```go
if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
	v.RegisterValidation("bookabledate", bookableDate)
}
```

How can I register a custom validator?

**Comment by thinkerou** [comment]
please refer to https://github.com/gin-gonic/gin/blob/master/binding/default_validator.go

**Comment by kurtzur** [comment]
@thinkerou unfortunately that didn't help me. I'm following the example code [here](https://github.com/gin-gonic/gin#custom-validators). are you saying there's some additional boilerplate I need to add?

**Comment by thinkerou** [comment]
I run the [example](https://github.com/gin-gonic/gin/blob/master/examples/custom-validation/server.go) which can't reproduce the error `error binding.Validator.Engine undefined (type binding.StructValidator has no field or method Engine)`.
so your gin version what is?

**Comment by kurtzur** [comment]
@thinkerou I realized that I unintentionally using an older version of `gin`. Thanks for the help.
