### ISSUE TITLE
version for go mod 

### ISSUE THREAD

**Issue by dayuoba** [gin-gonic/gin#1465]
i'm trying go mod on go version 1.11beta3, the simplest code like below

```golang
package main
import "github.com/gin-gonic/gin"
func main() {
  r := gin.Default()
  r.GET("/", func(c *gin.Context) {
   //  try c.BindQuery here
  })
  r.Run(":8080")
}
```

when i run `go run .` go installs a gin of version 1.14, and then it faild with c.BindQuery undefined.
i've tried to sepcify the version v1.2 `go get -u github.com/gin-gonic/gin@v1.2` but also failed with version can not be found.

anyone can give me some suggestions?

**Comment by thinkerou** [comment]
duplicated #1388

**Comment by dayuoba** [comment]
@thinkerou thx for your reply, is there any quick alternative for me to use gin with go mod? if i fork this repo and re-tag it v1.2.0?

**Comment by thinkerou** [comment]
@dayuoba yes, that will use yourself gin-branch.

**Comment by dayuoba** [comment]
@thinkerou ok, 谢谢。: )
