### ISSUE TITLE
use c.BindJSON can cause PANIC

### ISSUE THREAD

**Issue by thunpin** [gin-gonic/gin#1472]
Hi guys,
I was creating my API test when I found this problem.
Assume that the sender can send a null JSON content, like that:
```go
req, _ := http.NewRequest(method, path, **nil**)
```

How can I test this in my service? If I try use the BindJSON a PANIC will be thrown.

**Comment by thinkerou** [comment]
@thunpin please post your example code, thanks!

**Comment by thunpin** [comment]
**test side:**
...
r := gin.Default()
req, _ := http.NewRequest(method, path, nil)
req.Header.Set("Content-Type", "application/json")
w := httptest.NewRecorder()
r.ServeHTTP(w, req)


**server side:**
user := &domain.User{}
err := context.BindJSON(user)

**Comment by isgj** [comment]
I don't think this is a bug. From [godocs](https://godoc.org/net/http#Request) `Body` field it says that on the server the `Body` is always non-nil, so you will never have to handle this case. The *panic* is caused by `Decode` (you are passing nil as Body) so everything is doing what it should do.

**Comment by thunpin** [comment]
Oops, my bad.

Thanks to clarify.
