### ISSUE TITLE
gopkg import failing

### ISSUE THREAD

**Issue by bpmason1** [gin-gonic/gin#1488]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- gin version (or commit ref): b869fe1415e4b9eb52f247441830d502aece2d4d
- git version: 2.7.4
- operating system: Ubuntu 16.04

## Description
`go get gopkg.in/gin-gonic/gin.v1` is failing.

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/gin/issues/1311
