### ISSUE TITLE
How can I get gin*context on Custom Validators

### ISSUE THREAD

**Issue by syssam** [gin-gonic/gin#1489]
How can I get gin*context on Custom Validators

**Comment by thinkerou** [comment]
@syssam sorry, I don't understand your mean, you point `binding.Validator`?

**Comment by syssam** [comment]
https://github.com/gin-gonic/gin#custom-validators
I write some validation, but it base on gin.Context
So, How can I get the context on the validator

**Comment by thinkerou** [comment]
@syssam gin.Context depends on validator, not validator depends on gin.Context, IMO, it will circle dependent.

**Comment by syssam** [comment]
@thinkerou I have set the variable on the Middleware, for example, c.Set("user", "admin")
Then, I want to write a common validator, which validate is admin or not when model Binding.
Now, I need call a validate function to check it by myself after model Binding.
