### ISSUE TITLE
Undefined contexts: BindingBody, JsonpJSON, AsciiJSON and Reader

### ISSUE THREAD

**Issue by DavidNeko** [gin-gonic/gin#1495]
When I try to execute
`go build -v .
`

I got

github.com/gin-gonic/gin
#github.com/gin-gonic/gin
../../../../mygo/src/github.com/gin-gonic/gin/context.go:575:22: undefined: binding.BindingBody
../../../../mygo/src/github.com/gin-gonic/gin/context.go:759:18: undefined: render.JsonpJSON
../../../../mygo/src/github.com/gin-gonic/gin/context.go:772:17: undefined: render.AsciiJSON
../../../../mygo/src/github.com/gin-gonic/gin/context.go:810:17: undefined: render.Reader

I'm not sure what happened here, it seems like several contexts are missing...
How should I fix this?

**Comment by appleboy** [comment]
please follow the issue template: https://github.com/gin-gonic/gin/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by thinkerou** [comment]
@DavidNeko please use issue_template and please ensure gin version, I will close the issue, if still have any problem, please reopen it, thanks!
