### ISSUE TITLE
Question about middleware

### ISSUE THREAD

**Issue by businiaowyf** [gin-gonic/gin#1515]
## Question
May I setup a middleware for certain api?  
- description
For example, I hve 2 apis in the same group, one requires login first, one not.
So can I use middleware for only one api in that group?

- gin version (or commit ref):
1.3.0

**Comment by syssam** [comment]
sure.
https://github.com/gin-gonic/gin#using-middleware

**Comment by thinkerou** [comment]
As @syssam pointed, thanks! closing

**Comment by businiaowyf** [comment]
It's my fault for not reading the guide carefully. Thanks so much!

**Comment by businiaowyf** [comment]
```
// Per route middleware, you can add as many as you desire.
r.GET("/benchmark", MyBenchLogger(), benchEndpoint)
```
