### ISSUE TITLE
Response header prints application/json but client finally gets text/plain

### ISSUE THREAD

**Issue by ameykpatil** [gin-gonic/gin#1518]
I am writing a micro-service & have a simple APIs built using gin. In case of error, response-headers do not have a header `Content-Type` as `application/json` instead it comes as `text/plain`. This does not happen in case of success but only in case of error. 

I am sending an error using `AbortWithStatusJSON`. After which I am printing `Content-Type` header & the value comes out to be `application/json; charset=utf-8`.
```go
c.AbortWithStatusJSON(http.StatusBadRequest, customErrorObj)
fmt.Println(c.Writer.Header().Get("Content-Type")) //prints application/json; charset=utf-8
```
But on client I get the header value as `text/plain`.

The entire flow in an concise way is as follows -
**route --> validator --> controller --> error-handler**

main.go
```go
func main() {
  router := gin.New()
  router.Use(middlewares.HandleErrors)
  router.GET("/labels", middlewares.ValidateQueryParams, controllers.GetLabels)
  // .. other routes
  router.Run(":" + constants.Env.Port)
}
```
middlewares.HandleErrors
```go
func HandleErrors(c *gin.Context) {
  c.Next() // execute all the handlers

  // at this point, all the handlers finished. Let's read the errors!
  if len(c.Errors) == 0 {
    return
  }

  err := c.Errors.Last()
  // .. create customErrorObj using err
  
  c.AbortWithStatusJSON(http.StatusBadRequest, customErrorObj)
  fmt.Println(c.Writer.Header().Get("Content-Type"))
}
```
middlewares.ValidateQueryParams
```go
type labelQuery struct {
  Name     string `form:"name" json:"name,omitempty"`
  Category string `form:"category" json:"category,omitempty"`
}

func ValidateQueryParams(c *gin.Context) {
  var labelQueryParams labelQuery
  if err := c.Bind(&labelQueryParams); err != nil {
    c.AbortWithError(http.StatusBadRequest, err)
    return
  }
  c.Set("labelQueryParams", labelQueryParams)
}
```
controllers.GetLabels 
```go
func GetLabels(c *gin.Context) {
  
  v, ok := c.Get("labelQueryParams")
  if !ok {
    c.AbortWithError(http.StatusBadRequest, errors.New('invalid query params'))
    return
  }

  labelQueryParams, ok := v.(labelQuery)
  if !ok {
    c.AbortWithError(http.StatusBadRequest, errors.New('error in converting query params'))
    return
  }

  labels, err := labelService.GetLabels(labelQueryParams.Name, labelQueryParams.Category)
  if err != nil {
    c.AbortWithError(http.StatusBadRequest, err)
    return
  }

  c.JSON(http.StatusOK, gin.H{"records": labels})
}
```

- gin version (or commit ref): v1.2

What all things I have tried?
- Replacing all `c.Bind` with `c.ShouldBind`
- Replacing `c.AbortWithStatusJSON` with `c.JSON`

Any help would be appreciated.

**Comment by syssam** [comment]
Please check which part case this problem.
I see your code is c.AbortWithError, not c.AbortWithStatusJSON

**Comment by ameykpatil** [comment]
@syssam The execution flow goes like this
```route --> validator (AbortWithError) --> controller (AbortWithError) --> error-handler (AbortWithStatusJSON)```

- I am calling `AbortWithError` since I don't want to execute subsequent handlers & also return an error.
- The last part of the execution flow is error-handler where I am calling `AbortWithStatusJSON` so I am expecting it to set the `Content-Type` as `application/json`
- I am printing value of `Content-Type` header which prints `application/json` but client still receives `text/plain` 
- Just to be sure, I tried by replacing all the `AbortWithError` calls with `AbortWithStatusJSON` & the issue still remains the same

**Comment by ameykpatil** [comment]
Other things that I tried but the issue is still there -
- Tried with `gin v1.3`
- Tried by replacing `c.Bind` with `c.ShouldBind`

**Comment by syssam** [comment]
AbortWithError will case this problem.
Just change all AbortWithError to AbortWithStatusJSON

**Comment by ameykpatil** [comment]
@syssam I have already tried replacing `AbortWithError` with `AbortWithStatusJSON` but the problem still persist.

**Comment by syssam** [comment]
Here is my tested code.
If you using AbortWithError will clear header at the end.
You can't write header on the other way.
https://github.com/gin-gonic/gin/issues/633
<pre>
package main

import (
	"errors"
	"net/http"

	"github.com/gin-gonic/gin"
)

func HandleErrors(c *gin.Context) {
	c.Next() // execute all the handlers

	// at this point, all the handlers finished. Let's read the errors!
	if len(c.Errors) == 0 {
		return
	}

	c.AbortWithStatusJSON(http.StatusBadRequest, c.Errors)
}

type labelQuery struct {
	Name     string `form:"name" json:"name,omitempty"`
	Category string `form:"category" json:"category,omitempty"`
}

func ValidateQueryParams(c *gin.Context) {
	var labelQueryParams labelQuery
	if err := c.ShouldBindQuery(&labelQueryParams); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, err)
		return
	}

	c.Set("labelQueryParams", labelQueryParams)
	c.Next()
}

func GetLabels(c *gin.Context) {
	v, ok := c.Get("labelQueryParams")
	if !ok {
		c.AbortWithStatusJSON(http.StatusBadRequest, errors.New("invalid query params"))
		return
	}

	labelQueryParams, ok := v.(labelQuery)
	if !ok {
		c.AbortWithStatusJSON(http.StatusBadRequest, errors.New("error in converting query params"))
		return
	}

	c.AbortWithStatusJSON(http.StatusBadRequest, errors.New("Testing error"))
	return

	c.JSON(http.StatusOK, gin.H{"records": labelQueryParams})
}

func main() {
	router := gin.New()
	router.Use(HandleErrors)
	router.GET("/labels", ValidateQueryParams, GetLabels)
	router.Run()
}
</pre>

**Comment by syssam** [comment]
AbortWithError() -> AbortWithStatus() -> c.Writer.WriteHeaderNow()
WriteHeaderNow will write the header, then you can't change.
You need set the write `c.Writer.Header().Set("Content-Type", " application/json; charset=utf-8")`
before call AbortWithError

**Comment by ameykpatil** [comment]
@syssam Thanks.
Setting header before calling `AbortWithError` did the trick.
```go
c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
c.AbortWithError(http.StatusBadRequest, err)
```

Just in case anyone arrives at this issue, what I am finally doing is.
Instead of calling `c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")` before every `AbortWithError` call,
I am setting it at the very initial point in error handling middleware.
```
func HandleErrors(c *gin.Context) {
  c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
  c.Next() // execute all the handlers
   .
   .
}  
```
Closing the issue.
