### ISSUE TITLE
document and common question archived

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#1522]
Background:
  - Now we have `README.md` document which includes most useful document, but some common question are frequently asked. So we should archive the frequently question and add some architecture document.

Hope everyone can take part in the work, thanks!

example:
  - how to build one effective middleware? #1521 
  - about template
  - and so on.

**Comment by isgj** [comment]
Are you considering making a web-site for Gin? Instead of using the `gh-pages` branch in this repository
you can create a new repository that is dedicated for the web-site so the examples, docs and other can be structured well. The `README.md` should be cleaner without the examples.

**Comment by thinkerou** [comment]
@isgj approve to create a new repository and migrate `gh-pages` branch.

**Comment by nakabonne** [comment]
Does anyone already working on this issue?
If no one is working, may I take part in the work?

**Comment by isgj** [comment]
Hi everyone i started [here](https://gitlab.com/isgj/gin-web) an idea for a new website. It is really at the beginning and a lot has to be done. At the moment it looks like 

![screenshot from 2018-09-28 16-33-44](https://user-images.githubusercontent.com/20517048/46215025-a811e800-c33c-11e8-9b9c-29768f12a674.png)
 
It is made with [hugo](https://gohugo.io).
Anything that pass by your mind is welcome.

**Comment by charly3pins** [comment]
Hi @isgj , I like the idea of using Hugo! Maybe it's better create the repo in github to facilitate the contribution? I'm interested on contribute in it if it's possible

**Comment by isgj** [comment]
Sure [here](https://github.com/isgj/gin-web) it is. I'm using `hugo` for the first time so please be polite :fearful:

**Comment by dlaub3** [comment]
I can help with this site as well. I use Hugo for my blog, so I have _some_ experience.

**Comment by appleboy** [comment]
@thinkerou maybe we need the new domain and create a new repository to put the source of website using Hugo.

**Comment by thinkerou** [comment]
OK, I see... at weekends.

**Comment by syssam** [comment]
@appleboy gin is a framework, why not use gin?

**Comment by appleboy** [comment]
@syssam We don't have the free VM to host the website using the gin framework.

**Comment by dlaub3** [comment]
It might be possible to run a free Heroku instance or use https://glitch.com. Then we could use Gin, but we may not have a custom domain name.

**Comment by appleboy** [comment]
I think Hugo is the best solution for everyone. We can create a new repo and choose the free [theme of Hugo](https://themes.gohugo.io/). I can buy a new domain for gin framework.

**Comment by isgj** [comment]
If you want here is some work already done [https:github.com/isgj/gin-web](https://github.com/isgj/gin-web). I can transfer the ownership of the repo.

**Comment by thefury** [comment]
I completely agree that a static site would be better suited for this. Unless there's something I'm missing, there's no need to add the operational complexity of running a framework based site.

**Comment by appleboy** [comment]
The following steps we need to do.

1. create a new repo for documentation webpage (maybe website name of repo)
2. buy a new domain and set custom domain in new repo.
3. integrate Travis with Hugo to deploy static page.

cc @javierprovecho @thinkerou

**Comment by thinkerou** [comment]
@appleboy agreed!

**Comment by appleboy** [comment]
update status: New domain: [gin-gonic.com](https://gin-gonic.com/) already done. Thanks for @javierprovecho . Everyone can watch the [website repo](https://github.com/gin-gonic/website).

**Comment by thinkerou** [comment]
first commit includes init hugo project and theme option, please see and review https://github.com/gin-gonic/website/pull/1, thanks!

**Comment by thinkerou** [comment]
Hi everybody, the first version Gin website have completed, thanks everybody!
please see https://gin-gonic.com/
