### ISSUE TITLE
How can I bind from form-data with array objects ?

### ISSUE THREAD

**Issue by thuandoan274** [gin-gonic/gin#1523]
I have form-data like send by using postman. But I don't know how to create struct to bind that data
![screenshot from 2018-08-31 16-38-01](https://user-images.githubusercontent.com/39752625/44905481-5cb7ea00-ad3c-11e8-8cd2-6dd63b4bc722.png)

Anyone can have me please!

**Comment by thinkerou** [comment]
please see `QueryArray` and `PostFormArray`

**Comment by thuandoan274** [comment]
This is my struct 
```
type BusinessPayloadRequest struct {
	Location struct {
		Latitude  float64 `form:"latitude" bson:"latitude"`
		Longitude float64 `form:"longitude" bson:"longitude"`
	} `form:"location" bson:"-"`
	AddressComponents []AddressComponents `form:"addressComponents[]" bson:"addressComponents"`
	WorkingHours      []WorkingHour       `form:"workingHours" bson:"workingHours"`

}

type WorkingHour struct {
	OpenHour    int `form:"openHour" bson:"openHour"`
	OpenMinute  int `form:"openMinute" bson:"openMinute"`
	CloseHour   int `form:"closeHour" bson:"closeHour"`
	CloseMinute int `form:"closeMinute" bson:"closeMinute"`
}
```
How use c.Bind but seem doesn't working

**Comment by syssam** [comment]
Bind does not support these type, you need post json data.
Bind form only support a basic type, like string, int..etc

**Comment by thuandoan274** [comment]
Yes, I think like you. Ok I'll use content type application/json

**Comment by aight8** [comment]
I think this should be supported because HTML forms without JS cannot send any JSON encoded forms. Furthermore if a file field is included in the form, multipart form encoding is the only possible option.

**Comment by Double1996** [comment]
please fix this

**Comment by bingtianyiyan** [comment]
hello,is there any plan to  support form for bind array,this is very useful func!

**Comment by rfx77** [comment]
Same problem here. I ended up using https://github.com/go-playground/form
