### ISSUE TITLE
Blurred Lined

### ISSUE THREAD

**Issue by daniejo** [gin-gonic/gin#1525]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
- gin version (or commit ref):
- operating system:

**Comment by daniejo** [comment]
![6fb1c2af-98b2-4006-b009-8a5257586200](https://user-images.githubusercontent.com/42870805/44949124-cb409900-ae5d-11e8-8d98-637866e6b7c5.jpg)

**Comment by thinkerou** [comment]
@daniejo please post more details, thanks!
