### ISSUE TITLE
adding support for go-playground/validator.v9 

### ISSUE THREAD

**Issue by tomriddle1234** [gin-gonic/gin#1527]
- go version:1.11
- gin version (or commit ref):1.3
- operating system: ubuntu 18.04

## Description
validator.v9 supports validating unicode alphanumerical values etc. 
Could be useful for locale supports, wish to update soon.

https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-Alpha_Unicode

**Comment by thinkerou** [comment]
@tomriddle1234 please see #1015 pull request, thanks!
