### ISSUE TITLE
How to ignore binding validation for specific struct filed in bind phase?

### ISSUE THREAD

**Issue by Alireza-Ta** [gin-gonic/gin#1531]
Hello there
First of all thanks for that awesome work!
I think the title speaks itself but for more I've got a user struct like so : 
```golang
type User struct {
	Id        int       `json: "id"`
	Username  string    `json:"username" binding:"required,min=5,max=32"`
	Email     string    `json:"email" binding:"required,email"`
	Password  string    `json:"password" binding:"min=8,max=64"`
	Bio       string    `json:"bio"`
	CreatedAt time.Time `json:"created_at" sql:"type:timestamptz"`
	UpdatedAt time.Time `json:"updated_at" sql:"type:timestamptz"`
}
```
Sometime I would like to update a user without touching password field but I will get ```Password field must be 8 characters at least.```  when parsing bind method!
Is there a way to ignore it?
Thanks!

**Comment by syssam** [comment]
use omitempty
https://godoc.org/gopkg.in/go-playground/validator.v9
