### ISSUE TITLE
suggestion: add "RegisterShutdownHook(func())" to gin application

### ISSUE THREAD

**Issue by aceyin** [gin-gonic/gin#1536]
Hi, in most cases, an application needs to release some resources before it shutdown, for instance: close the datasource connection, or release some network connection.

so i think if it would be helpful if the gin framework can provide a "RegisterShutdownHook" function for developers to register their own business logic before application shutdown.

here is an example, i implement in my application:

_**register shutdown functions in database module**_

![image](https://user-images.githubusercontent.com/482266/45285491-db1f4380-b515-11e8-97a8-e1af168499a2.png)

_** call shutdown hooks before application shutdown **_

![image](https://user-images.githubusercontent.com/482266/45285568-0bff7880-b516-11e8-8e67-31672c74cdd4.png)

**Comment by thinkerou** [comment]
maybe one middleware is better.

**Comment by billyplus** [comment]
"before application shutdown"?
maybe it's aplication who should call ShutdownHooks, not gin.

**Comment by thinkerou** [comment]
closing
