### ISSUE TITLE
Nil Pointer Stoping Entire Server

### ISSUE THREAD

**Issue by MrThreepwood** [gin-gonic/gin#1537]
Go v1.11
Gin v1.3.0
Mac OS

I assume this is a setting issue, but I don't know what's going on. When I get a nil pointer exception in my server, it stops handling ALL requests. There are no logs and the request hangs. Future requests that would not cause a nil pointer also don't complete/hit breakpoints. I have a simple model that I deserialize the request into:

```
type HelloListWrapper struct {
	Requests []*HelloRequest `json:"data"`
	Errors []validations.ValidationErrors
}
```

I then loop over the nested requests and call things on them. If a client passes null in the json array, obviously I end up with a nil pointer, but I can't figure out what's happening after that. The program is still running, but there are no logs and no other requests make it through, but also appear to still be received (postman doesn't immediately say Could not get any response, and instead is waiting). I've had this happen with other nil pointers while I've been developing as well.

**Comment by thinkerou** [comment]
@MrThreepwood please post mini server code and http client, it can help us reproduce as soon as possible. thanks!

**Comment by MrThreepwood** [comment]
On further examination, this appears to be an Intellij issue. I'm not sure exactly what's wrong with Intellij, but as long as I run rather than debug, or run from the command line, it appears to work. Thanks for your time, I'll open up an issue on Jetbrains' tracker once I narrow it down.

**Comment by kaustubhmallik** [comment]
@MrThreepwood I also experienced the same issue when using Goland. At that time, I thought there is something wrong with my code. Thanks for posting it here. 👍

**Comment by thinkerou** [comment]
closing, `It's a know issue for deleve` https://github.com/derekparker/delve/issues/852
