### ISSUE TITLE
gopkg.in is error

### ISSUE THREAD

**Issue by zcx2001** [gin-gonic/gin#1538]
Go v1.11
Gin v1.3.0
Mac OS

can't go get gopkg.in/go-playground/validator.v8 
gopkg.in is error

![image](https://user-images.githubusercontent.com/1219360/45351106-ee9adf00-b5e7-11e8-891e-be927e63bd49.png)

Can you provide direct access url?

**Comment by chainhelen** [comment]
@zcx2001  You can't access it by browser directly. And what you need is vpn (because you are in china).

**Comment by zcx2001** [comment]
I already use VPN.  And please look at the pictures. It is gopkg.in feedback error that cannot connect to GitHub.

**Comment by andilesteve** [comment]
https://github.com/niemeyer/gopkg/issues/63

**Comment by chainhelen** [comment]
# root @ iZ2zehbv3lrr68hy0bu46zZ in ~/workspace/go/src/gopkg.in [17:51:26] 
$ go get gopkg.in/go-playground/validator.v8
package gopkg.in/go-playground/validator.v8: unrecognized import path "gopkg.in/go-playground/validator.v8" (parse https://gopkg.in/go-playground/validator.v8?go-get=1: no go-import meta tags ())

# root @ iZ2zehbv3lrr68hy0bu46zZ in ~/workspace/go/src/gopkg.in [17:51:44] C:1
$ go get gopkg.in/go-playground/validator.v9
package gopkg.in/go-playground/validator.v9: unrecognized import path "gopkg.in/go-playground/validator.v9" (parse https://gopkg.in/go-playground/validator.v9?go-get=1: no go-import meta tags ())

**Comment by thinkerou** [comment]
now ok? I can get it right.
![image](https://user-images.githubusercontent.com/4488261/45353705-27d64d80-b5ee-11e8-83df-7ca63e7927b5.png)

**Comment by andilesteve** [comment]
#niemeyer/gopkg#63

**Comment by thinkerou** [comment]
closing, have fixed!
