### ISSUE TITLE
Access to Router options

### ISSUE THREAD

**Issue by jgoodall** [gin-gonic/gin#154]
is it possible to set the [Router](https://github.com/julienschmidt/httprouter/blob/master/router.go#L112) options? Specifically, to set `RedirectTrailingSlash`?

**Comment by 13k** [comment]
what about adding the below?

```go
type RouterOptions struct {
  RedirectTrailingSlash bool
  RedirectFixedPath bool
  HandleMethodNotAllowed bool
}

func (e *Engine) SetRouterOptions(options RouterOptions) {}
```

and possibly even:

```go
func (e *Engine) NewWithOptions(RouterOptions) *Engine {}
```
