### ISSUE TITLE
How to fix request url without using redirect method

### ISSUE THREAD

**Issue by NewBieQing** [gin-gonic/gin#1545]
I want to let request url is compatible with different url style, such as api/v1/test_url and api/v1/testUrl will be direct to the same handler, but i don't want to use Redirect method，is there any other method that can help me?
Now, i use this method ：

```go
func(c *gin.Context) {
		service.RequestInfoLog(c)
		req := c.Request
		path := req.URL.Path
		if fixedPath, ok := fixRequestUrl(path); ok {
			req.URL.Path = fixedPath
			code := 301
			if req.Method != "GET" {
				code = 307
			}
			http.Redirect(c.Writer, req, req.URL.String(), code)
		} else {
			c.Next()
		}
	}
```

but i found that when i use protobuf to transmit data and if the request is redirected, i couldn't decode the protobuf data, is there any mistake in my method?

**Comment by thinkerou** [comment]
@NewBieQing you should use `Group`, like:

```go
func handle(c *gin.Context) {
	println("handle ...")
}

func main() {
	r := gin.Default()

	v := r.Group("api/v1/")
	v.GET("test_url", handle)
	v.GET("testUrl", handle)

	r.Run()
}
```
