### ISSUE TITLE
not print color log when go version is 1.10/1.11

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#1547]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: go 1.11
- gin version (or commit ref): master
- operating system: mac

## Description
Here can see go 1.8 1.9 1.10 1.11 print log: https://travis-ci.org/gin-gonic/gin/builds/428455260?utm_source=github_status&utm_medium=notification

when go version is 1.9 it will print log:

![image](https://user-images.githubusercontent.com/4488261/45535407-f4cfcc00-b830-11e8-96a3-b5d516f3e8c2.png)

else print log:

![image](https://user-images.githubusercontent.com/4488261/45535437-0f09aa00-b831-11e8-9d7c-0acd99d7fd41.png)

**Comment by thinkerou** [comment]
`println(isatty.IsTerminal(os.Stdout.Fd()))` on https://github.com/gin-gonic/gin/blob/master/logger.go#L60 will print `false` on go 1.11, but `println(isatty.IsTerminal(os.Stdout.Fd()))` on single file will print `true` on go 1.11. I don't know why?

**Comment by thinkerou** [comment]
ping @mattn @thesyncim thanks

**Comment by mattn** [comment]
I didn't change anything for mac. (as far as I remember)

**Comment by thinkerou** [comment]
@mattn thank you for yourreply.

**Comment by BrandonZacharie** [comment]
I got colors on macOS High Sierra and now Mojave. I only lose colors when running [gin](https://github.com/codegangsta/gin) (i.e. `gin -p 5000 -i run main.go`) which wraps the process.

**Comment by kaustubhmallik** [comment]
@thinkerou will you be able to pick it, otherwise, I would love to help.

**Comment by thinkerou** [comment]
@kamronbatman welcome
