### ISSUE TITLE
Gin post form binding will throw error if post int 0

### ISSUE THREAD

**Issue by qshuai** [gin-gonic/gin#1548]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
- gin version (or commit ref):
- operating system:

## Description
```
func main() {
	r := gin.Default()
	r.POST("/login", Login)

	r.Run(":8090")
}

type LoginParam struct {
	User string `form:"user" binding:"required"`
	Age  string `form:"age" binding:"required"`
}

func Login(c *gin.Context) {
	fmt.Println(c.PostForm("user"))
	fmt.Println(c.PostForm("age"))
	var l LoginParam
	err := c.ShouldBind(&l)
	if err != nil {
		panic(err)
	}
}
```
I post the form via curl:
```
curl -v --form user='qishuai' --form age=0 http://127.0.0.1:8090/login
// error:
// Key: 'LoginParam.Age' Error:Field validation for 'Age' failed on the 'required' tag
```
But I want the `age` field is required, and 0 is a valid input. How will I deal with?

**Comment by syssam** [comment]
Try --form age='0'

**Comment by qshuai** [comment]
@syssam Correct the above Struct defined:
```
type LoginParam struct {
	User string `form:"user" binding:"required"`
	Age  int    `form:"age" binding:"required"`
}
```

**Comment by thinkerou** [comment]
@qshuai your gin version? go version? I use your first code run OK and curl also OK.

**Comment by syssam** [comment]
@qshuai 
https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-Required
so age should be String

**Comment by qshuai** [comment]
@thinkerou Sorry, the struct should be the following:
```
type LoginParam struct {
	User string `form:"user" binding:"required"`
	Age  int    `form:"age" binding:"required"`
}
```

**Comment by qshuai** [comment]
@syssam I read the full document about the package `validator`, and I found the more efficient way:
```
type LoginParam struct {
	User string `form:"user" binding:"required"`
	Age  int    `form:"age" binding:"gte=0,required"`
}
``` 

It will meet my requirement. But here the field `Age` may be not suitable. Thanks.

**Comment by syssam** [comment]
@qshuai Actually, it is not a problem, because of the age default value is zero, even value is empty.
On the other hand, any situation need age = 0?

**Comment by syssam** [comment]
@qshuai just simply using max=8

**Comment by qshuai** [comment]
@syssam `max` validate function will not claim `required`. And I want the number according to `[0-8]`, as to `int` may be a negative number. So it will be `validate:"min=0,max=8,required"` .

**Comment by syssam** [comment]
@qshuai 
option to you.
For me, I'm using `valid:"between=0|30"` on my validator package.
https://github.com/syssam/go-validator

**Comment by qshuai** [comment]
@syssam Thanks for your advice.

**Comment by chainhelen** [comment]
#1246
