### ISSUE TITLE
HTTP status code is illegible

### ISSUE THREAD

**Issue by BrandonZacharie** [gin-gonic/gin#1552]
- go version: go1.11 darwin/amd64
- gin version (or commit ref): v1.3.0
- operating system: macOS High Sierra

## Description
White text on a yellow background is completely illegible... I can think of three different ways to solve this; make the text color darker, keep the text white and make the background darker, or add support for configuring the text and/or background color.

## Screenshots
![screen shot 2018-09-15 at 13 53 03](https://user-images.githubusercontent.com/27306/45590565-94ec2a80-b8ef-11e8-8fee-a28bf2542e8a.png)

**Comment by thinkerou** [comment]
Hi, @BrandonZacharie please help me see #1547 and so I need to ensure it and then attempt to fix this. thanks!
