### ISSUE TITLE
Unecessary external dependencies are being downloaded.

### ISSUE THREAD

**Issue by JeremyLoy** [gin-gonic/gin#1566]
## Description

When declaring `gin` as a dependency using the latest `master` commit, unnecessary dependencies are declared in your `go.mod/go.sum` due to the `examples/` directory containing executable `go` programs.

Those programs should be removed or moved to another Github repository.

## Steps to reproduce

1. make a sample hello-world application using `go modules` and `gin`.
1. declare `gin@master` as a dependency using `go get github.com/gin-gonic/gin@master`
1. observe that unnecessary dependencies such as `google.golang.org/grpc v1.15.0`, `google.golang.org/appengine` etc are added to your own `go.sum`

**Comment by thinkerou** [comment]
ref #1569

**Comment by thinkerou** [comment]
ref: https://github.com/golang/go/issues/28156 #1604

**Comment by xiaost** [comment]
I think https://github.com/gin-gonic/gin/blob/master/tools.go is one of the evils.
Many dependency management tools may introduce `grpc` by the import in `tools.go`

**Comment by thinkerou** [comment]
@xiaost `tools.go` have removed!
