### ISSUE TITLE
ShouldBind JSON doesn't seem to work (using axios)

### ISSUE THREAD

**Issue by mikevoid101** [gin-gonic/gin#1567]
- go version: go version go1.10.3 linux/amd64
- gin version (or commit ref): v1.3.0
- operating system: Ubuntu 18.04

## Description

I am using axios to send a POST request to my gin application, however it doesn't seem to be able to bind the json payload to my validation struct. If I submit a form instead of sending an ajax request, the validation works, otherwise all my validations fail because neither `ShouldBind` or `ShouldBindJSON` seem to pick-up the json payload I am sending with axios.

Simple axios request:

```javascript
axios.post('/api/register', {
        name: 'test',
        email: 'test@test.com',
        password: 'test100',
        confirm: 'test100',
      })

```

Validation struct:
```go
type UserModelValidation struct {
	Rules struct {
		Name     string `form:"name" json:"name" binding:"exists,min=5,max=255"`
		Email    string `form:"email" json:"email" binding:"exists,email"`
		Password string `form:"password" json:"password" binding:"exists,min=6,max=255"`
	}
}
```

then I call `ShouldBind` (tried with `ShouldBindJSON` too) and check if there are any validation errors, if there are, I return them as a JSON response (see screenshot).

## Screenshots

Ajax request:

![image](https://user-images.githubusercontent.com/32217690/45946987-4b8c9100-bffb-11e8-802d-5ff7bb562e80.png)

Here is what I get using axios, all my validations fail:

![image](https://user-images.githubusercontent.com/32217690/45947016-665f0580-bffb-11e8-8c12-acc60e826dd4.png)

If I use a form to send the POST request, the validation finally kicks in:

![image](https://user-images.githubusercontent.com/32217690/45946878-e9cc2700-bffa-11e8-8844-c11205f8ef96.png)

What is the problem here? Thanks in advance.

**Comment by thuandoan274** [comment]
BindJSON didn't working with me :((
