### ISSUE TITLE
Send data/message with Redirect

### ISSUE THREAD

**Issue by olegsobchuk** [gin-gonic/gin#1578]
Is it possible send data/payload with `redirect` request? 
For example after create user I do `redirect`, but I need send message ("User created successfully") to notify user about result.
```
c.Redirect(301, "/")
```

**Comment by isgj** [comment]
You should handle this with your `Session`.

**Comment by olegsobchuk** [comment]
@isgj my bad, you absolutely right, thanks.

**Comment by olegsobchuk** [comment]
Maybe another question related to redirect, may be answered...

Why I can't use code 201 in `redirect` function

**Comment by isgj** [comment]
201is StatusCreated. The `Redirect` code is 301. If you respond with `201` it won't redirect and probably will mess with the browser history.

**Comment by olegsobchuk** [comment]
@isgj ok thx
this issue can be closed
