### ISSUE TITLE
static middleware not work

### ISSUE THREAD

**Issue by train860** [gin-gonic/gin#158]
I use this middleware:
https://github.com/gin-gonic/contrib/tree/master/static

like this:

r := gin.Default()
r.Use(static.Serve("/assets")) 
r.NotFound(static.Serve("/assets"))

but,it's not work!

my project tree
![cd9fac54-3c30-4782-a194-b01ec2e792e7](https://cloud.githubusercontent.com/assets/6874537/5156757/308c91f2-731a-11e4-8faa-86380dfd41e7.png)

**Comment by javierprovecho** [comment]
@train860 sorry for delay

You should be using ' r.Static()' to serve files, now that it is integrated into Gin Framework. I post an example:

```go
package main
import "github.com/gin-gonic/gin"

func main() {
    r := gin.Default()
    r.Static("/assets", "./assets")
    // Listen and server on 0.0.0.0:8080
    r.Run(":8080")
}
```
Also, if an issue is related with a middleware from contrib, you should post it next time in that repository.
