### ISSUE TITLE
ShouldBind File ?

### ISSUE THREAD

**Issue by x-t0xid** [gin-gonic/gin#1591]
- go version: go1.11.1 windows/amd64
- gin version (or commit ref): v1.4.0-dev
- operating system: Windows 10 x64

I have a upload operation with more info. I use Should bind but not working. 

```go

// RegisterForm ...
type RegisterForm struct {
	FullName string                `form:"full_name" binding:"required"`
	Email    string                `form:"email" binding:"required"`
	Image    *multipart.FileHeader `form:"image" binding:"required"`
	Password string                `form:"password" binding:"required"`
}

```

and binding here.

```go
        tmpForm := RegisterForm{}
	if err := ctx.ShouldBind(&tmpForm); err == nil {
                // .... 
	} else {
		fmt.Println(err.Error())
	}

```

Output: 

> Key: 'RegisterForm.Image' Error:Field validation for 'Image' failed on the 'required' tag

Request (Postman):
![adsiz](https://user-images.githubusercontent.com/10995965/46904091-ae30c880-cee7-11e8-88f8-51444b5d272a.png)

**Comment by thinkerou** [comment]
issue ref: #1263 and pr ref: #1264

**Comment by thinkerou** [comment]
@ghost #1264 merged!
