### ISSUE TITLE
Static middleware returns wrong content type for `.js` files.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [gin-gonic/gin#1595]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: go version go1.9 windows/amd64
- gin version (or commit ref): caf3e35 ("doc: update readme for adding binding about skip validate (#1359)", 2018-05-31)
- operating system: Microsoft Windows [版本 10.0.15063]

## Description
Same as [this issue](https://github.com/labstack/echo/issues/1038#issuecomment-369889841) , I found it maybe a common problem for the  web framework in Go. And I found [this floor](https://github.com/labstack/echo/issues/1038#issuecomment-369946800) and [this floor](https://github.com/labstack/echo/issues/1038#issuecomment-410294904) is useful as I fixed it by add [the line `mime.AddExtensionType(".js", "application/javascript")`](https://github.com/zhengxiaoyao0716/zworld/blob/e6e4a9f272b3e2ecef7917da4448ef14f8a7ad61/server/server.go#L59).

**Comment by boolow5** [comment]
for those who still get wrong content type check in your middle ware any of them doing the following:

```
// c being the gin.Context pointer of the request
c.Writer.Header().Set("Content-Type", "application/json")
```
Make sure you use a group that doesn't have that middleware applied

**Comment by Jack-Kingdom** [comment]
This issue is too old to discuss. Suggest close.

**Comment by muzea** [comment]
Also encountered this problem. Adding `mime.AddExtensionType(".js", "application/javascript")` to program, it's worked for me.
