### ISSUE TITLE
Why can't I start this way? How to solve this problem?

### ISSUE THREAD

**Issue by q920447939** [gin-gonic/gin#1603]
![1l52ckz689w lnnyuyul q](https://user-images.githubusercontent.com/15419380/47209307-9b743300-d3c2-11e8-8952-6b0567e9cdbb.png)

**Comment by q920447939** [comment]
![bz1t8jc0i4 rfc0 75a3a2](https://user-images.githubusercontent.com/15419380/47209425-e8f0a000-d3c2-11e8-8be6-bc5ead84b637.png)
Then I used this method, but still can't

**Comment by q920447939** [comment]
![5p3s u ktj y_ ih6 9xwqj](https://user-images.githubusercontent.com/15419380/47209563-3b31c100-d3c3-11e8-95d4-b00a9c468331.png)
"ggin" is  Alias

**Comment by thinkerou** [comment]
please read readme https://github.com/gin-gonic/gin#html-rendering and use mini example code. thanks!
