### ISSUE TITLE
Gin is more and more bloated now

### ISSUE THREAD

**Issue by IIInsomnia** [gin-gonic/gin#1604]
## Description
When `go get` Gin, it will pull many unnecessary dependences, like `grpc`、`golang.org/x/crypto` 、`golang.org/x/sys`、`golang.org/x/lint` etc.

**Comment by thinkerou** [comment]
`go.mod` could lead to the issue, I will fix it, thanks!

**Comment by thinkerou** [comment]
@IIInsomnia please give me reproduce steps, thanks!

**Comment by thinkerou** [comment]
ref: https://github.com/golang/go/issues/28156

**Comment by thinkerou** [comment]
duplicated #1566
