### ISSUE TITLE
Oauth2 plugin

### ISSUE THREAD

**Issue by kokizzu** [gin-gonic/gin#161]
Is there oauth2 integration/plugin for gin? (just like github.com/GoIncremental/negroni-oauth2 or github.com/martini-contrib/oauth2)

**Comment by javierprovecho** [comment]
@kokizzu sorry for delay

You have https://github.com/gin-gonic/contrib/tree/7e5b9ae6856cd129f8f6b4125eef815c5494bf1c/jwt , after that you can extend it.
