### ISSUE TITLE
No way to change POST max size

### ISSUE THREAD

**Issue by mastrolinux** [gin-gonic/gin#163]
In the http module usually you can do:

```req.Body = http.MaxBytesReader(rw, req.Body, 5 << 20)```

and have a byte limit on POST request as big as you want. In gin there is no Body so it is very hard to change these settings.

Is there a workaround? Can you implement a POST max size limit configuration?

**Comment by tomsteele** [comment]
I've done:
```
c.Request.Body = http.MaxBytesReader(c.Writer, c.Request.Body, size)
```

And it has worked.

**Comment by mastrolinux** [comment]
Will give it a try, thanks.

**Comment by mastrolinux** [comment]
I think you have the Context just after the POST is submitted but it is not submitted if the size is bigger that the limit. You approach works to decrease the size but not to increase it apparently. I guess the Context is callable inside the request only but after it is done.
