### ISSUE TITLE
error in /usr/local/Cellar/go/1.10.3/libexec/src/encoding/json/decode.go:171

### ISSUE THREAD

**Issue by Maybrittnelson** [gin-gonic/gin#1635]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: 1.10.3

## Description
front-end post  request body 
{"name":"g","key_id":"221bce6492eba70f","key_secret":"6eb80603e85842542f9736eb13b7e3","header":{"cache_control":"10"},"property":"0"}
back-end throw error in /usr/local/Cellar/go/1.10.3/libexec/src/encoding/json/decode.go:171
error info in Screenshots
## Screenshots
![image](https://user-images.githubusercontent.com/20365012/48257195-cc3d0a80-e44c-11e8-829f-32b3df0caef7.png)

**Comment by thinkerou** [comment]
@Maybrittnelson please post more info, like: server demo code and curl command.... thanks!

**Comment by Maybrittnelson** [comment]
sry, i get it . input type is not right, it use default text

**Comment by Maybrittnelson** [comment]
> @Maybrittnelson please post more info, like: server demo code and curl command.... thanks!

sry, i get it . input type is not right, it use default text
