### ISSUE TITLE
Not able to deploy on Google App Engine

### ISSUE THREAD

**Issue by sublee** [gin-gonic/gin#1639]
- go version: 1.9.7
- gin version (or commit ref): 37854ee10f7161843c338d9a9fa87f9398aacbbe
- operating system: Ubuntu

## Description

Since 37854ee10f7161843c338d9a9fa87f9398aacbbe, Gin started to import `syscall` at `recovery.go`. This made Gin apps not able to be deployed in Google App Engine. Because Google App Engine doesn't allow to import `syscall` for security reason.

> The majority of pure Go packages work on Google App Engine. A package may not work because of one of these reasons:
> 
> - The package imports `syscall` or `unsafe`.
> - The package uses cgo or assembly.
> - The package requires functions in packages that are locked down, such as writing to disk, or direct network access.

In https://cloud.google.com/appengine/kb/, I could find those restrictions.

## Screenshots

![image](https://user-images.githubusercontent.com/19982/48310935-acd3e800-e5da-11e8-9764-22d79f1a003b.png)

**Comment by thinkerou** [comment]
@sublee thanks your feedback, I will handle it tonight.

**Comment by justinfx** [comment]
Sorry, I haven't had any experience with GAE so I wasn't aware of that limitation. After a quick search on the matter, I think you may be right, @thinkerou. Seems assertion will have to end once you have the OpError and do string testing to see if it's EPIPE or ECONNRESET. You may also be able to see if calling [OpError.Temporary()](https://golang.org/pkg/net/#OpError.Temporary) works just for the ECONNRESET check.

**Comment by thinkerou** [comment]
please see #1640 thanks!
