### ISSUE TITLE
Engine.Run* methods should return an error

### ISSUE THREAD

**Issue by campadrenalin** [gin-gonic/gin#164]
This is the traditional Go http way of doing things, but why hew to tradition? Because it handles a failure to bind to the specified address in a much cleaner way than the current code, for one thing. I'd much rather not bury the relevant information in a skyscraper of panic traceback data when people try to run my server and have something else on :8080 already.

Example of the Traditional Way, as applied to Gin:

```go
package main

import (
    "log"

    "github.com/gin-gonic/gin"
)

func Main() {
    g := gin.Default()
    g.GET("/ping", func(c *gin.Context) {
        c.String(200, "pong")
    })
    log.Println(g.Run()) // Returns an error, so we log.Println it!
}
```

This also helps to catch other edge cases, providing a nice way of bubbling up fatal server failures where a traceback would be pointless/inappropriate.

**Comment by javierprovecho** [comment]
@campadrenalin sorry for delay.

If I understanded you right, is better to return the 'err' instead of panicking?

**Comment by manucorporat** [comment]
I do not agree with that. I would strongly recommend to restore the `panic()`.

panic() is perfectly fine in Go for initialisation errors or bad internal states (like assertions),  or bad configuration.

Run() and RunTLS() are both shortcuts of `http.ListenAndServe(addr, engine)`.
If you want to handle the error you should call:
```go
g := gin.Default()
if err := http.ListenAndServe(":80", g); err != nil {
  // you probably have to PANIC here, most of the cases this situation is a not-going
}
```

Run() was created to avoid having to write all that code.
