### ISSUE TITLE
Multiple slashes in path is not working

### ISSUE THREAD

**Issue by QianChenglong** [gin-gonic/gin#1644]
## Description

Multiple slashes in path can't be routed!

In stdlib http, the [ServeMux](https://golang.org/src/net/http/server.go?s=40985:41006#L2313) use `cleanPath` on `path`. 

![image](https://user-images.githubusercontent.com/1881126/48471233-65de3080-e82e-11e8-9b52-61f5d58c1292.png)

## Screenshots

![image](https://user-images.githubusercontent.com/1881126/48470955-ca4cc000-e82d-11e8-84f4-fbcd51103e68.png)

**Comment by QianChenglong** [comment]
@thinkerou 
![image](https://user-images.githubusercontent.com/1881126/48471310-9c1bb000-e82e-11e8-80b9-ea3232b8984a.png)
![image](https://user-images.githubusercontent.com/1881126/48471331-a63dae80-e82e-11e8-8fcc-55ee9e4124ed.png)

**Comment by QianChenglong** [comment]
![image](https://user-images.githubusercontent.com/1881126/48471613-4562a600-e82f-11e8-8a0a-d86d122c0a28.png)

In my project, I just cleanPath on it. I'm not sure it's ok on other situation.

**Comment by thinkerou** [comment]
@QianChenglong I want to know which scenario use `//`?

**Comment by QianChenglong** [comment]
The user of API is others, can not be controlled.

**Comment by thinkerou** [comment]
Now gin can set `gin.RedirectFixedPath`, and then it will return `301` which can't execute it.

**Comment by QianChenglong** [comment]
I had tried that feature.It rediect by 307.But which i need and other router supports direct process.

**Comment by thinkerou** [comment]
ref: #789

**Comment by QianChenglong** [comment]
1. Redirect depends caller folloew which can't be promised.
2. Redirect means more round trip time which is not reasonable.
3. In my suitation, the URL is same meaning, so should be processed directly!

**Comment by dmarkham** [comment]
This will also cause Path Parameters to get missed. 
`GET : http://localhost:8180//49cEhsh5Hg`
`router.GET("/:myparam", someHandler())`
`myparam` in this case will be empty. :-1:
