### ISSUE TITLE
Gin sets up the logger

### ISSUE THREAD

**Issue by gq-tang** [gin-gonic/gin#1665]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
- gin version (or commit ref):
- operating system:

## Screenshots

Gin can sets up the logger,like this
gin.SetLogger(logger)

**Comment by billyplus** [comment]
use io.Writer instead.
```
logfile, err := os.OpenFile("simgame.log", os.O_RDWR|os.O_APPEND|os.O_CREATE, 0644)
if err != nil {
	return
}
logWriter := log.NewSyncWriter(io.MultiWriter(os.Stderr, logfile))

r:=gin.New()
r.Use(gin.LoggerWithWriter(logWriter))
```
