### ISSUE TITLE
BindQuery not support time pointer, when non specified form fieldName

### ISSUE THREAD

**Issue by allwmh** [gin-gonic/gin#1672]
```
type User struct {
	QueryTime *time.Time `binding:"omitempty"`
}

func main() {
	r := gin.Default()
	r.GET("/user", getUser)
	r.Run(":8085")
}

func getUser(c *gin.Context) {
	var user User
	if err := c.ShouldBindQuery(&user); err == nil {
		log.Infof("%+v", user)
		c.JSON(http.StatusOK, user)
	} else {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
	}
}
```
curl http://localhost:8085/user

the resulst is 
```
{
QueryTime: "0001-01-01T00:00:00Z"
}
```
form_mapping.go:15
![image](https://user-images.githubusercontent.com/5651367/49061636-37a81a00-f24c-11e8-97b8-5db9885228ef.png)
gin version is v1.3.0

**Comment by thinkerou** [comment]
@allwmh welcome to commit pull request, thanks!

**Comment by robbbsen** [comment]
Commented this topic at #1611.
In general `*time.Time` fields are not left `nil` when using binding (`ShouldBind()` in my case).
Therefore my database query that builds up on that is not returning any data.

Its `gin` + `gorm`. I've used `gorm.Model` in my structs to auto-append `CreatedAt`, `UpdatedAt` and `*DeletedAt`.

Hope this gets fixed some day. For all the new coders running into the same struggle of _searching for the bug_.
