### ISSUE TITLE
"wildcard route conflicts with existing children"

### ISSUE THREAD

**Issue by wodim** [gin-gonic/gin#1681]
```go
router.GET("/:something/", Blabla)
router.GET("/:something/else", Bleble)
router.GET("/:something/:different/:again", Blibli)
```

`panic: wildcard route ':different' conflicts with existing children in path '/:something/:different/:again'`

Am I doing something wrong or is this simply not allowed?

**Comment by b3lc0d3** [comment]
https://github.com/gin-gonic/gin/issues/1301

**Comment by wodim** [comment]
Wow, that is terrible.

**Comment by thinkerou** [comment]
expected, thanks! you should re-write your route.

**Comment by wodim** [comment]
Saying it's "expected" makes it double terrible, because it means you will never get around to fix it.

There is no way Gin should confuse Bleble with Blibli: Bleble has two slashes, and Blibli has three!

In the end I had to write my own router like this:

```go
router.GET("/", ViewHome)
router.GET("/:first", ViewRouterOne)
router.GET("/:first/:second", ViewRouterTwo)
router.GET("/:first/:second/:third", ViewRouterThree)
router.GET("/:first/:second/:third/:fourth", ViewRouterFour)
```

Then from those functions you can redirect requests to the correct view functions. I hope this is useful to someone.

**Comment by safwanolaimat** [comment]
how this routes cause conflict
```
pGroup.POST("/fork", controllers.Fork)
pGroup.POST("/:id/process", controllers.processN)
```

**Comment by marloncristian** [comment]
Am I the only one who doesn't understand why something so basic is not implemented in gin?

**Comment by wodim** [comment]
https://github.com/gin-gonic/gin/issues/2016#issuecomment-523204888

**Comment by LaysDragon** [comment]
> Am I the only one who doesn't understand why something so basic is not implemented in gin?

me either,such basic functional route supported by most http server in the world but not in gin

**Comment by insomnius** [comment]
How can i fix this? Where should i start to contribute to fix this?

**Comment by LaysDragon** [comment]
> How can i fix this? Where should i start to contribute to fix this?

It's httprouter's problem that gin currently based on
checkout this issue  https://github.com/gin-gonic/gin/issues/2016

**Comment by ridwanakf** [comment]
is this limitation still persist now?

**Comment by appcypher** [comment]
Wow! Gin routing pattern matching is a mess. Now I have to refactor my app to use another framework.

**Comment by shivamganwani** [comment]
@appleboy
 
Member
[appleboy](https://github.com/appleboy) commented [on Apr 8, 2021](https://github.com/gin-gonic/gin/issues/1681#issuecomment-815538271)

Fix!!

**Comment by appleboy** [comment]
@shivamganwani Thank you for classifying.
