### ISSUE TITLE
ctx.XML how to handle <![CDATA[%s]]> tag

### ISSUE THREAD

**Issue by ByLuxury** [gin-gonic/gin#1683]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
- gin version (or commit ref):
- operating system:

**Comment by zsirfs** [comment]
use encoding/xml tag: https://kapeli.com/dash_share?docset_file=Go&docset_name=Go&path=golang.org/pkg/encoding/xml/index.html%23pkg-constants&platform=go&repo=Main&source=golang.org/pkg/encoding/xml/&version=1.13.7

```
type Body struct {
  Say `xml:"say,cdate"`
}
```
below will rendering the result:

```
<xml>
  <say>[!CDATA[%s]]</say>
</xml>
```
