### ISSUE TITLE
ClientIP() using X-Forwarded-For and X-Real-Ip should be opt-in

### ISSUE THREAD

**Issue by wodim** [gin-gonic/gin#1684]
`ClientIP()` using `X-Forwarded-For` and `X-Real-Ip` by default without any kind of warning is appalling security-wise.

It is trivial for an attacker to spoof any IP address if the app is listening directly on a public port without a reverse proxy or if the reverse proxy is not properly configured. For example, if the reverse proxy is configured to use `X-Real-Ip`, it will seemingly work correctly, but `X-Forwarded-For` takes precedence so the remote IP address can still be spoofed.

**Comment by billyplus** [comment]
There is `ForwardedByClientIP bool` to check if clientip is forwarded.

```
r := gin.New()
r.ForwardedByClientIP = false
```

```
func (c *Context) ClientIP() string {
	if c.engine.ForwardedByClientIP {
		clientIP := c.requestHeader("X-Forwarded-For")
		clientIP = strings.TrimSpace(strings.Split(clientIP, ",")[0])
		if clientIP == "" {
			clientIP = strings.TrimSpace(c.requestHeader("X-Real-Ip"))
		}
		if clientIP != "" {
			return clientIP
		}
	}
```

**Comment by sorenisanerd** [comment]
Not fixed.

**Comment by sorenisanerd** [comment]
https://github.com/gin-gonic/gin/blob/bfc8ca285eb46dad60e037d57c545cd260636711/gin.go#L161-L162
