### ISSUE TITLE
Pass form data to c *gin.Context Postform for testing

### ISSUE THREAD

**Issue by Kacentdix** [gin-gonic/gin#1685]
Hello guys, 

I'm quite new to Go and have to write unitary tests.

The problem I'm facing is that I need to test func Login(c *gin.Context) and have to pass data to that context.postform(key) from my test in order to complete it. 

I've tried a few things but I don't know how to bind data to the post request from my test so that the context can access it. 

Sorry if the description isn't precise enough, I'm on my phone and will upload the code when I'll be back home on my computer.

Thanks and sorry if its a dumb question.

**Comment by Kacentdix** [comment]
Resolved

**Comment by carlows** [comment]
@Kacentdix so, how did you solve it?
