### ISSUE TITLE
file.Filename should not be trusted. There should be a sanitize function, or give a warning in docs.

### ISSUE THREAD

**Issue by ganlvtech** [gin-gonic/gin#1693]
- go version: 1.11
- operating system: Windows 10 64bit

## Description

https://github.com/gin-gonic/gin/blob/cce49582d617333c72f4d86abd8ef0e62eb778a0/examples/upload-file/single/main.go#L26

```go
file, _ := c.FormFile("file")
c.SaveUploadedFile(file, file.Filename)
```

We must not trust user input `file.Filename`!

## Reproduce

First, start `examples/upload-file/single/main.go` server.

```bash
cd ~/go/src/github.com/gin-gonic/gin/examples/upload-file/single
go run main.go
```

Start a new terminal and upload a file (such as the `main.go` itself) with cURL.

```bash
curl -X POST -F 'file=@main.go; filename=../main.go' http://127.0.0.1:8080/upload
```

Then, you will find the uploaded file is at `~/go/src/github.com/gin-gonic/gin/examples/upload-file/main.go`. Upload a file to parent dir is really dangerous.

I don't know if it's by design. But I think, at least, there should be a warning asking developers to sanitize the input properly.

## Solution

The simplest way may be

```go
import "path/filepath"

file, _ := c.FormFile("file")
filename := filepath.Base(file.Filename)
c.SaveUploadedFile(file, filename)
```

This will restrict the upload file to current directory.

**Comment by thinkerou** [comment]
please commit pull request, thanks!

**Comment by thinkerou** [comment]
#1699 merged!
