### ISSUE TITLE
Question: gin.LogFormatterParams.Latency and TimeStamp?

### ISSUE THREAD

**Issue by RealLau** [gin-gonic/gin#1701]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: 1.11 
- gin version (or commit ref): latest gin (add_customize_redis_example v1.09)
- operating system: darwin/amd64 on Mac OSX 10.14.1

## Description
I guess:
- **gin.LogFormatterParams.Latency** shows how much time the server cost to process a certain request;
- **gin.LogFormatterParams.TimeStamp** shows the time when the server begin to process a certain request, NOT the time the server receive that request(maybe that request is standing in line and waiting)
Do I make any misunderstanding? Hope someone can give a verification to help out. Thanks in advance:)

**Comment by thinkerou** [comment]
ref pull request #1677 @sairoutine can you help see the question? thanks!

**Comment by sairoutine** [comment]
>gin.LogFormatterParams.Latency

Yes. You are right.

>gin.LogFormatterParams.TimeStamp

No. `TimeStamp` shows the time after the server returns a response.

**Comment by RealLau** [comment]
Thanks for ur answer @thinkerou @sairoutine . Will close this issue.
