### ISSUE TITLE
PostForm seems to be unset

### ISSUE THREAD

**Issue by cajus** [gin-gonic/gin#1703]
- go version: 1.11
- gin version (or commit ref): v1.3.0
- operating system: Fedora 29 / linux

## Description

I'm doing some "first time" gin-gonic adventure currently and I'm quite happy with it. Now I came across my first POST route defined like

```golang
	r.POST("/foo", func(c *gin.Context) {
		fmt.Println(c.ContentType())
		a, _ := c.GetRawData()
		fmt.Println(string(a))
		fmt.Println(c.PostForm("id"))
	})
```

and I'm trying to send a form with id=123 using curl

```
curl -X POST --data "id=123" http://localhost:8088/foo
```

which prints

```
application/x-www-form-urlencoded
id=123

```
on the console. From the examples of *README.md*, I'd expect the `c.PostForm("id")` to return something more than an empty string.

So - I'm feeling a bit stupid in the moment... Do I have to do anything else to access the value of "id"?

**Comment by cajus** [comment]
Sigh. I guess I got trapped in debugging. `GetRawData()` eats it all. Works now. Sorry for the noise.

**Comment by jin-pin-mei-le** [comment]
I have the same problem

 
![image](https://user-images.githubusercontent.com/73807441/115017651-6bea0700-9ee9-11eb-8f9b-3f9ff8694c07.png)
