### ISSUE TITLE
use pre defined Router

### ISSUE THREAD

**Issue by rezam90** [gin-gonic/gin#1704]
Hi
I'm trying to switch to `gin`, but wanted to know it better.
I'm currently using gin's router as explained in examples.

for example, if I need to define the routers in other package, then I pass the `*Engine` to that function to get routes defined.

But I wanted to know If there is an option to pass an already defined `Router` from other packages to the gin. seems complicated :). there is such an option in `ExpressJs`.

```js
...
var router = express.Router()

router.get('/test', (req, res) => res.send('ok') )
...
app.use('/group', router)
```
As you see, there is a 'router' which is passed to the app.

Is it possible in gin?

**Comment by thinkerou** [comment]
@rezam90 you should learn gin's project: https://github.com/gin-gonic/gin#users

**Comment by rezam90** [comment]
Thanks @thinkerou
