### ISSUE TITLE
Regarding the copyright in file headers

### ISSUE THREAD

**Issue by samueldcs** [gin-gonic/gin#1710]
There is something weird going on regarding the "Copyright" claim in file headers, like that:
https://github.com/gin-gonic/gin/blob/678e09c736505225e28d8c585087b84faaf4bb80/auth.go#L1-L3
If it's protected by the MIT license in the `LICENSE.md` file, then it's not really all rights reserved. Plus, the year is outdated.

**Comment by javierprovecho** [comment]
@samueldcs copyright year rarely is updated, it marks the start of the copyright notice. check this answer about "all rights reserved" https://opensource.stackexchange.com/a/2123
