### ISSUE TITLE
500 error in post handler not working

### ISSUE THREAD

**Issue by peterbe** [gin-gonic/gin#173]
I have something like this:
```go
    r = gin.Default()
    ...
	r.POST("/v1/faces", func(c *gin.Context) {
		...bla bla bla...
		_, err = io.Copy(out, file)
		if err != nil {
			fmt.Println(err)
			c.String(500, "error happened")
			return
		}
                ...bla bla bla...
       })
```

When I run this, I get a 200 error code and a blank response body. The console event says:
```
[GIN] 2014/12/08 - 08:45:07 | 200 |    915.646us | ::1 POST /v1/faces
```

I tried `c.String(500, "internal server error")` in a very simple GET handler and that worked.

**Comment by javierprovecho** [comment]
@peterbe sorry for delay.

I can not replicate this with the latest commit. Wherever it was, it is fixed now. I have just checked.
