### ISSUE TITLE
Using gin.Context together with context.Context 

### ISSUE THREAD

**Issue by DenLilleMand** [gin-gonic/gin#1734]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: 1.11.4
- gin version (or commit ref): 1.3
- operating system: Arch linux

## Description
My setup is a gin router in front of a `99designs/gqlgen` graphql handler which uses the regular `net/http` package.

My problem is that i wrote my basic authentication middleware as a gin handler, it takes the basic auth header and validates it etc. Fetches the user from the database and sets it inside of the gin.Context with `context.Set("user", usr)`. When i try to access this through the `context.Context` object later in the middleware chain this is gone.

I fixed this by setting this line in my gin middleware:
```
func (uc *UserController) AuthenticateUserKey() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Request = c.Request.WithContext(c)
                // ... do some authentication stuff and fetch/set the user
``` 

Otherwise i will just get a error when i try to get the `"user"` key from the context.Context.

I could do this in some middleware after the `authenticateUserKey` call, which would look nicer i guess. But i still think that using the gin context exactly like a regular context might have some issues, i am not sure how solid the gin implementation of the regular context methods are, as far as i can read some of them don't work at all which might ruin it for other developers.

My question is, how have people in similar situations dealt with this?

**Comment by jwentworth** [comment]
We use gin for context. context.Context's in general do not all implement all functionality. gin.Context provides values accessible using (context).Value.

It does not provide Done or Deadline, so if you need a cancellable context or a deadline you should wrap your gin.Context using the appropriate context.Context values.

context's are designed to be nested with higher level functionality overwritten or supplementing lower level functionality. With how gin is set up gin.Context will always be the inner most context (you can not add a context that gin.Context wraps)
