### ISSUE TITLE
Large File Upload Mystery 

### ISSUE THREAD

**Issue by medyagh** [gin-gonic/gin#1741]
Hi there when i try to upload a large file (for example 17 ML)

I get this error in my browser (after hitting submit and file being uploaded at 17%)

```
dancegeek.net unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_CLOSED
```

and on the router side I have no log that it even received a request POST.

while reading github issues, I tried using with and without these options:

``` 
router.MaxMultipartMemory = 640 << 20 
```

```
	s := &http.Server{
		Addr:           ":80",
		Handler:        router,
		ReadTimeout:    200 * time.Second,
		WriteTimeout:   20 * time.Second,
		MaxHeaderBytes: 640 << 20, // 640 MiB
	}
	s.ListenAndServe()
```

and regarldess of using those options I still see the same behavior.

here is my html code

```
    <form action="/user/upload" id="uploadform" method="post" enctype="multipart/form-data">
        Name: <input type="text" name="name"><br /><br />
        Type:
        <select name="dance_type" required="required">
            <option value="Salsa" selected>Salsa</option>
            <option value="Tango">Tango</option>
            <option value="Kurdish">Kurdish</option>
        </select><br /><br />
        File: <input type="file" id="file" class="filepond" name="file" required="required"><br>
            <input type="submit" value="Submit">
    </form>

```

and my upload handler go code is just like the example code

```
	session := sessions.Default(c)
	fileHeader, err := c.FormFile("file")

```
but in this case, the POST request wont even reach the handler...

I have no idea how to solve this Mystery, my own guts says I have to change something on the client side but I am not sure what !

**Comment by medyagh** [comment]
Mystery solved, the problem was I was using cloudflare as CDN and it had a limit. sorry for bugging . hopefully it will be helpful for someone else.

**Comment by orange-oranje** [comment]
I am reading this so late, was trying to find if there are any inbuilt limits on file size, it seems there are no limis

 ```router.MaxMultipartMemory```

I would reduce this, this is not indicative of the file size, it is rather a limit on memory to use before spilling to disk. You should have a lot of memory on the upload API box to handle multiple uploads then.
