### ISSUE TITLE
Its tedious to restart the server, for every small change

### ISSUE THREAD

**Issue by pranshuchittora** [gin-gonic/gin#1743]
OS: Linux

For every small change, I had to restart the server.
- Kill the process
- Kill the occupied port `fuser -i -k 8080/tcp` (Closing the connection)
- Then `go run`

### Solution / Package
I node.js world this problem is solved using [nodemon](https://www.npmjs.com/package/nodemon).
Is there any similar package in go.

**Comment by dmarkham** [comment]
Everyone looks happy with  @nerdbaggy  suggestion can we close this Issue?
