### ISSUE TITLE
Something after 1.3.0 breaking string formatting of query params in Default Logger

### ISSUE THREAD

**Issue by NickDubelman** [gin-gonic/gin#1746]
I was working on an app that doesn't lock in its dependencies and noticed something after 1.3.0 release is causing the default logger to print query params like the following:

```
[GIN] 2019/01/17 - 07:59:20 | 200 |    2.594888ms |    69.420.69.420 | POST     /api/someRoute/otherRoute?thing=Borat%!A(MISSING)zumat&otherThing=Pamel%!a(MISSING)4&blah=true&id=69
```

I saw that there are some changes going on with query params-- it seems like the %20 stuff in the URL needs to be escaped so GO doesnt think these are string formatting parameters.

**Comment by thinkerou** [comment]
@NickDubelman what's your correct uri?

**Comment by NickDubelman** [comment]
I made up that example, but basically if the URL were `?foo=bar%20Saw` or something, it would turn into `bar(MISSING)aw` or something, because it thinks the %20S is a string formatting directive

**Comment by thinkerou** [comment]
fixed
