### ISSUE TITLE
Gin QPS test is low and cpu low

### ISSUE THREAD

**Issue by zhengchengbin610** [gin-gonic/gin#1748]
- With issues:
  - I  test  mixphp ，nginx , gin for a simple api test , find the qps of gin is lowest , following is my test information and result, some one can tell me is my test wrong or  how can i  modify ?

- go version:  go1.11.2 linux/amd64
- gin version (or commit ref): v1.3.0 ( b869fe14 )
- operating system: compile system ubuntu-16.04  and  run system ubuntu-14.04
## Description
     I  use ab test the qps for gin ,and also test nginx and php, only test a simple api, 
    test command ：
        ab -n 1000000 -c 1000 http://52.1.47.196:8080/test

##Result Screenshots:
![mixphp-qps](https://user-images.githubusercontent.com/26518131/51449477-291b4200-1d67-11e9-9908-f072a971f71d.png)
![nginx-qps](https://user-images.githubusercontent.com/26518131/51449480-30425000-1d67-11e9-9ff8-ce9f7a1d0950.png)
  
  cpu use:
     mixphp 100% cpu use
     nginx 45%-55% cpu use
     gin  5%-30%  cpu use
 
My question:
   if  my test way is wrong ? I  think this not the golang language performance, I want someone can help me ,thanks
  if also find  In the process of testing, it starts very fast and then looks slower and slower

**Comment by zhengchengbin610** [comment]
![gin-qps](https://user-images.githubusercontent.com/26518131/51450626-5fa78b80-1d6c-11e9-92d9-47ecbdfc5a02.png)

**Comment by thinkerou** [comment]
@zhengchengbin610 please post your gin code, thanks!

**Comment by thinkerou** [comment]
please use 
```
	gin.SetMode(gin.ReleaseMode)

 	router := gin.New()
```
instead of 
```
        router := gin.Default()
```

**Comment by zhengchengbin610** [comment]
@thinkerou   I  use export GIN_MODE=release to run if the same ?

**Comment by zhengchengbin610** [comment]
I  tested the result is set the env value GIN_MODE=release , I see the run information is set ok.

**Comment by appleboy** [comment]
@zhengchengbin610 You can reference the https://github.com/the-benchmarker/web-frameworks

**Comment by zhengchengbin610** [comment]
@appleboy  thanks your relay, I  will test it later , but I use the web test tool ab is not right ? ab tool is the common web api test tool.

**Comment by appleboy** [comment]
@zhengchengbin610 Yes, maybe you can try another tool like [wrk](https://github.com/wg/wrk).

**Comment by zhengchengbin610** [comment]
@thinkerou  why? Ab is a well-known test tool

**Comment by zhengchengbin610** [comment]
wrk test result :
[wrk-nginx-gin](https://user-images.githubusercontent.com/26518131/51453831-9be2e800-1d7c-11e9-82c9-bc974db3c7f3.png)

**Comment by zhengchengbin610** [comment]
Mybe anyone  can help me to explain this ?? mybe the gin framework is so slow ??

**Comment by thinkerou** [comment]
please post one example code, I try it!

**Comment by zhengchengbin610** [comment]
@thinkerou  Thank you replay, I  posted my example code before,you can try it.

**Comment by igorrius** [comment]
Also you could try to up GC to 400+%

**Comment by zhengchengbin610** [comment]
@igorrius  Sir , how should I do , can you tell me ?

**Comment by zhengchengbin610** [comment]
I  also test the golang net/http ,the same test way , the QPS about 37347 , more than nginx 32000 qps, but gin only about 2400 qps

**Comment by zhengchengbin610** [comment]
@igorrius  I  set  debug.SetGCPercet(400) , but the test result about 2000 qps

**Comment by zhengchengbin610** [comment]
Do you test Gin the performance is very high ? only me test is so ?

**Comment by igorrius** [comment]
@zhengchengbin610 my a minute ago simple test with AB

test app (GIN_MODE=release)
```
package main

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

func main() {
	r := gin.New()
	r.GET("/test", func(c *gin.Context) {
		c.String(http.StatusOK, "ok") // 2Kb response
	})
	_ = r.Run() // listen and serve on 0.0.0.0:8080
}
```

ab results
```
 >ab -n 100000 -c 50  http://localhost:8080/
...
Server Hostname:        localhost
Server Port:            8080

Document Path:          /test
Document Length:        2 bytes

Concurrency Level:      50
Time taken for tests:   4.588 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      11800000 bytes
HTML transferred:       200000 bytes
Requests per second:    21796.12 [#/sec] (mean)
Time per request:       2.294 [ms] (mean)
Time per request:       0.046 [ms] (mean, across all concurrent requests)
Transfer rate:          2511.66 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.3      1       3
Processing:     0    1   0.3      1       8
Waiting:        0    1   0.3      1       5
Total:          0    2   0.2      2       9

```
test laptop
```
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.15.0-43-generic
WM: GNOME Shell
GTK Theme: Ambiance [GTK2/3]
CPU: Intel Core i7-7820HQ @ 8x 3.9GHz [25.0°C]
RAM: 13053MiB / 32044MiB
```

**Comment by zhengchengbin610** [comment]
Okay,I  will  test it again tomorrow ,tks

**Comment by zhengchengbin610** [comment]
Okay,I  will  test it again tomorrow ,tks

**Comment by roychowdhuryrohit-dev** [comment]
Isn't lower cpu use relates to better performance per watt increasing overall efficiency ?

**Comment by thinkerou** [comment]
```
$ go version
go version go1.10.3 linux/amd64
```
![image](https://user-images.githubusercontent.com/4488261/51579833-5994e480-1efd-11e9-8e60-3b069af60141.png)

**Comment by zhengchengbin610** [comment]
@thinkerou  Yes, my test result QPS about 37000, Gin the performance is very good.

**Comment by thinkerou** [comment]
@zhengchengbin610 I use default setting, not change anything. Thanks!
