### ISSUE TITLE
pull response time from gin

### ISSUE THREAD

**Issue by SandroJijavadze** [gin-gonic/gin#1757]
branch = "master"
  digest = "1:6375f542808927c64c4938b160697a53b597f3db29cd0cf7faa576b8dd251155"
  name = "github.com/gin-gonic/gin"
  revision = "500ebd9ea866c57427aeaddc31f374adedd4084b"

go version:
1.11.4

I cannot seem to find any way to pull the same response time that gin outputs to stdout (in microseconds). I am talking about this (174.138µs)
![image](https://user-images.githubusercontent.com/23349818/51987856-c93a3f00-24bc-11e9-90b8-d18184ecf7af.png)
I am currently using this snnippet in middleware:
`		
start := time.Now() `
`c.Next()`
`end := time.Now().Sub(start)
`
But It does not match to whatever the gin prints to stdout.

I have searched both repo, google and package files through IDE tools but cannot find any built in way to do this.
Could you confirm that this feature does not exist? 
Or point me to the direction how could I calculate exactly the same or closely matching time? 

Can it be done without gin.Logger()  ?
I use custom logger and I just want latency value.
Thanks

**Comment by thinkerou** [comment]
as @sairoutine said, thanks!

**Comment by ringsaturn** [comment]
I have a demo this by changing `ResponseWriter`

https://github.com/ringsaturn/ginmiddlewares/blob/master/cmd/example/main.go

See more https://github.com/gin-gonic/gin/issues/2493#issuecomment-912986064
