### ISSUE TITLE
Router returning incorrect HTTP codes

### ISSUE THREAD

**Issue by ysimonson** [gin-gonic/gin#176]
The router currently returns 404 when there's a matching path, but no matching verb. Instead it should return a 405

**Comment by javierprovecho** [comment]
Thank you @ysimonson 

What I see is that it is not an error, but an undeveloped feature. This should be developer on `httprouter` but because how it is made, I don't think it would be possible.

**Comment by javierprovecho** [comment]
@ysimonson well, when I said it would not be possible, never mind. Check https://github.com/julienschmidt/httprouter/pull/51 . Thank you for discovering this.

**Comment by javierprovecho** [comment]
@ysimonson pull request was merged

**Comment by ysimonson** [comment]
Cool, thanks @javierprovecho !
