### ISSUE TITLE
Throwing panic with recovery continues calling middlewares

### ISSUE THREAD

**Issue by marczahn** [gin-gonic/gin#1770]
I found a strange behaviour but maybe it is intended:

I have middleware A and B and C which are chained.
In middleware A all panics are cought with a defer. It calls Next() on the gin.Context
Middleware B throws a panic and thus does not call Next().

What I expect: Middleware C is not called. But actually it is called indeed. Is this supposed to be like this and why?

This is middleware A:
```
...
defer func() {
	if rc := recover(); rc != nil {
		l.WithField("recover", rc).Error("Panic occured")
		c.JSON(http.StatusInternalServerError, "Internal error")
	}
}()
c.Next()
...
```

**Comment by easonlin404** [comment]
would you post your example in more detail?

**Comment by jbonzo** [comment]
I think you need to incorporate `c.Abort` into your logic. `c.Abort` is the only way to signal the chain to stop moving forward.

**Comment by marczahn** [comment]
Ah yes - That makes absolutely sense. The problem doesn't exist anymore. Thanks for this idea - So simple at the end :-)
