### ISSUE TITLE
I want to do like bellow nginx conf with gin, so how to do? thanks somebody can help me.

### ISSUE THREAD

**Issue by iwkoo** [gin-gonic/gin#1772]
I want to do like bellow nginx conf with gin, so how to do? thanks somebody can help me.

```
location / {
    try_files $uri $uri/ /index.html;
  }
```

**Comment by holyzhuo** [comment]
I think you can use gin start a http server,and use nginx proxy this port.
```  
location / {
            proxy_pass http://127.0.0.1:8090;
        }
```

**Comment by bytejedi** [comment]
`location /api/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass http://127.0.0.1:9000/;   # this is your gin http server, Notice the slash at the end
        }`

**Comment by holyzhuo** [comment]
```
location ^~ /api {
   proxy_pass http://127.0.0.1:9000;
}
```
i think you need this config
