### ISSUE TITLE
Proposal: split examples to alone repo

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#1775]
For making the `gin` repo simple and reducing dependencies, I suggest we create one repo `gin-gonic/examples` saves example code.

cc @javierprovecho @appleboy 

thanks!

**Comment by solarhell** [comment]
LGTM. Especially when i am using `go module`.

**Comment by thinkerou** [comment]
repo has created and moved code, please see https://github.com/gin-gonic/examples

**Comment by solarhell** [comment]
I have another question: do you need to remove some unused deps from 'go.mod' and release a new version for `gin`? Just want to know 😉.

**Comment by thinkerou** [comment]
@solarhell `gin1.4` should not remove `examples`, it will be removed to `gin1.5`.

**Comment by appleboy** [comment]
@thinkerou Add repo link of exmaple in README.

**Comment by thinkerou** [comment]
@appleboy OK
