### ISSUE TITLE
qps setting and graceful shutdown 

### ISSUE THREAD

**Issue by 18959263172** [gin-gonic/gin#1781]
Can gin set max qps?
I think gin use one conection one gorutine ,can I set max connection that gin accecpted ?
Also ,I notice the exapmle https://github.com/gin-gonic/gin/blob/master/examples/graceful-shutdown/close/server.go
what's the deference between close and shutdown 
the code in the repo example use close(),it's not shutdown right?

**Comment by easonlin404** [comment]
you can reference https://github.com/gin-gonic/gin/issues/955#issuecomment-310819621 to limit the number of current requests.
