### ISSUE TITLE
Ignore specified from default router logging?

### ISSUE THREAD

**Issue by alshdavid** [gin-gonic/gin#1798]
Say I have the following application 

```go
func main() {
	auth := authority.Create(authConfig)

	r := gin.Default()
	r.GET("/ping", handler.PingGet)

	base := r.Group(baseURL)

	oauth := base.Group("/oauth")
	oauth.GET("/login", handler.LoginGet(oAuthConfig))
	oauth.GET("/callback", handler.CallbackGet(oAuthConfig))

	api := base.Group("/api")
	api.Use(auth.TokenMiddleware())
	api.GET("/whoami", handler.WhoAmIGet)
	api.GET("/overview", handler.OverviewGet())

	r.NoRoute(handler.SPAGet(publicFolder, baseURL))
	r.Run("0.0.0.0:5000")
}
```

By default `gin.Default()` will print a log for all routes.
I'd like to ignore `/ping` and everything on `/oauth`

Can I configure the default router to do that, or must I build my own?

**Comment by appleboy** [comment]
You can custom the gin logger.

```go
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	// Creates a router without any middleware by default
	r := gin.New()

	// Global middleware
	// Logger middleware will write the logs to gin.DefaultWriter even if you set with GIN_MODE=release.
	// By default gin.DefaultWriter = os.Stdout
	r.Use(gin.LoggerWithConfig(gin.LoggerConfig{
		SkipPaths: []string{"/ping_1"},
	}))

	// Recovery middleware recovers from any panics and writes a 500 if there was one.
	r.Use(gin.Recovery())

	r.GET("/ping_1", func(c *gin.Context) {
		c.String(200, "pong_1")
	})

	r.GET("/ping_2", func(c *gin.Context) {
		c.String(200, "pong_2")
	})

	// Listen and serve on 0.0.0.0:8080
	r.Run(":8080")
}
```

**Comment by solarhell** [comment]
@appleboy If this feature landed in `gin 1.3`?

BTW, i am using following workaround currently.
![image](https://user-images.githubusercontent.com/10279583/53859019-4b1b0c00-4017-11e9-9387-7a448f9c9a2d.png)

**Comment by alshdavid** [comment]
> ```go
> LoggerWithConfig
> ```

I don't seem to have access to this when using 

```
go get -u github.com/gin-gonic/gin
```

Any idea why I wouldn't have the latest `logger.go`?

**Comment by appleboy** [comment]
@alshdavid What is your go vendor tool? Or try to use the go module in go1.11 version.

**Comment by alshdavid** [comment]
I am using go modules and go 1.12. It is pulling version `1.3`

On a fresh project

```
go mod init newproject
go get -u github.com/gin-gonic/gin
```

The source I get for gin doesn't match the source I see in Github.
Does go cache modules?

**Comment by appleboy** [comment]
Try

```
go get -u github.com/gin-gonic/gin@master
```

**Comment by thinkerou** [comment]
@alshdavid I think you use `go mod` not `go get...`.
step1: run `go mod init github.com/thinkerou/gintest`
step2: write code, import gin package
step3: run `go mod tidy`, not use `go get` command

**Comment by appleboy** [comment]
@thinkerou `go get` will get the latest version from `github release page`.

**Comment by sairoutine** [comment]
Currently, `LoggerWithConfig` is only in master branch.
It is a new feature for future release v1.4.

**Comment by adangadang** [comment]
LoggerWithConfig   rerate

**Comment by appleboy** [comment]
I closed the issue. You can download the v1.5 version or try [gin-logger](https://github.com/gin-contrib/logger).
