### ISSUE TITLE
is it possible to handel /index /index.html for one route?

### ISSUE THREAD

**Issue by qtkc** [gin-gonic/gin#1806]
I know if i do like this,it will works

```
func public(r *gin.Engine) {
	r.GET("/index", sth)
	r.GET("/index.html", sth)
        r.GET("/index.json", sth)
        r.GET("/index.xml", sth)
}
```
But it's not cool,right?  And if there are many routes in my project,this'll be a complete mess...

In short words,just want handel .html .json .xml match with the original route path .
Does gin support this?

ps:don't want use a DIY function  to fix the problem,for example:

```
func GenPath(r *gin.Engine,path string)  {
	r.GET(path, sth)
	r.GET(path + ".html", sth)
	r.GET(path + ".json", sth)
	r.GET(path + ".xml", sth)
}
```

because it will make too many route handel any way...

**Comment by thinkerou** [comment]
@qtkc sorry, I don't know you mean.
