### ISSUE TITLE
404 with url like this:  http://localhost:4200//api/auth/login

### ISSUE THREAD

**Issue by autumn2019** [gin-gonic/gin#1813]
- go version: go version go1.11.4 darwin/amd64
- gin version (or commit ref): 1.3.0
- operating system: Mac OS 10.13.6

## Description

```
	auth := new(controller.AuthController)
	authGroup := router.Group("/api/auth")
	{
		authGroup.POST("/login", auth.Login)
	}
```

Visit the url:  `http://localhost:4200/api/auth/login` , I get success。
Visit the url:  `http://localhost:4200//api/auth/login` ，it's return `404`.

How should I code this route? 

Thanks in advance for your time.

**Comment by autumn2019** [comment]
#1644 与这个重复了。

**Comment by thinkerou** [comment]
I use gin1.4.0, it's ok.
![image](https://user-images.githubusercontent.com/4488261/57513712-7a186b80-7341-11e9-9059-bc573f74d5ce.png)
