### ISSUE TITLE
Add GitHub explore topic

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#1818]
please see https://github.com/github/explore

Add topic and display like this:

![image](https://user-images.githubusercontent.com/4488261/54575258-5cf4aa00-4a2e-11e9-82c1-965f79204fed.png)

**Comment by thinkerou** [comment]
ref: https://github.com/github/explore/pull/656

**Comment by thinkerou** [comment]
done!

**Comment by dmarkham** [comment]
Nice Job @thinkerou looks good.
