### ISSUE TITLE
start new project from Gin build error

### ISSUE THREAD

**Issue by huangxiaoye** [gin-gonic/gin#1821]
go build
endor/github.com/gin-gonic/gin/binding/default_validator.go:48:14: undefined: validator.Config
vendor/github.com/gin-gonic/gin/binding/default_validator.go:49:29: too many arguments in call to validator.New

- go version: 1.12.0
- gin version :1.13.0
- operating system:macos 10.14.3

**Comment by dmarkham** [comment]
@huangxiaoye I'm trying to reproduce your error and have not been successful yet. Is there a way you can give more details on how to reproduce this error? Can you also double check your gin version.

**Comment by dmarkham** [comment]
@appleboy  @thinkerou  can we close this due to inactivity, short of details, and no other users reporting it.
