### ISSUE TITLE
Styling breaks when request takes long

### ISSUE THREAD

**Issue by mjarkk** [gin-gonic/gin#1823]
- go version: `go version go1.10.4 linux/amd64`
- gin version (or commit ref): `5acf6601170bb49a1958c055d66d54ba152dc34b`
- operating system: `elementary OS 5.0 Juno`

## Description
If a request takes long like web sockets the logging gets a bit messed up  
see the screenshot  
This request takes long because it's a web-socket

## Screenshots
![Screenshot from 2019-03-22 11-55-43](https://user-images.githubusercontent.com/15320763/54820524-c5968d80-4c9f-11e9-8250-3276de92d79d.png)

**Comment by dmarkham** [comment]
@thinkerou  what are you thoughts about just reducing the resolution of the duration when it gets above a defined threshold? Lets say  1m. Once any request duration goes above 1m  it's precision in the default logger truncates to seconds.

**Comment by thinkerou** [comment]
@dmarkham this is a good thinking, maybe I also set max width for websocket request, please see #1825 do you think? thanks!

**Comment by dmarkham** [comment]
For this issue at least this is what I was thinking.

**Comment by dmarkham** [comment]
Of course `duration.Truncate()` was not added until 1.9 so that makes my patch less interesting :(  But that is 4 versions ago. Go only supports 2 versions back, *hint* *hint*. Maybe we can get within 4?
