### ISSUE TITLE
proposal: add isWebsocket and isIPv6 config to LogFormatterParams

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#1825]
relevant issue/pull request: #1282 #1823 
request method is websocket, user can set `isWebsocket`; address is IPv6, user can set `IPv6`.
like this:

```
type LogFormatterParams struct {
	Request *http.Request

	// TimeStamp shows the time after the server returns a response.
	TimeStamp time.Time
	// StatusCode is HTTP response code.
	StatusCode int
	// Latency is how much time the server cost to process a certain request.
	Latency time.Duration
	// ClientIP equals Context's ClientIP method.
	ClientIP string
	// Method is the HTTP method given to the request.
	Method string
	// Path is a path the client requests.
	Path string
	// ErrorMessage is set if error has occurred in processing the request.
	ErrorMessage string
	// BodySize is the size of the Response Body
	BodySize int
	// Keys are the keys set on the request's context.
	Keys map[string]interface{}
	// isTerm shows whether does gin's output descriptor refers to a terminal.
	isTerm bool
	isWebsocket bool
        isIPv6 bool
}
```
default value is `false`.

**Comment by dmarkham** [comment]
The only reason I see to have the 2 new values added into the param list is if you plan on adding the bools into the default logs.   

I feel like we already have to move to fixed width *36* for `ipv6` if we really want `ipv4` and `ipv6` to look pretty next to each other as referenced here #1282.  

Websocket requests are not the only requests that can last very long so I would just prefer to fix it more generically. (long requests get the precision truncated in the default logger)

**Comment by thinkerou** [comment]
@dmarkham thanks! I agree with you.
