### ISSUE TITLE
use einhorn to monitor and zero-downtime restart

### ISSUE THREAD

**Issue by badoet** [gin-gonic/gin#183]
can we add einhorn binding on start so that we have zero-downtime restart
see goji for reference.
their einhorn implementation is very beautiful.

**Comment by manucorporat** [comment]
I will work in the feature!

**Comment by dcu** [comment]
@badoet @manucorporat I wrote a little library that should work with gin (and others) here:

https://github.com/dcu/http-einhorn

**Comment by manucorporat** [comment]
@dcu man! that looks genius. looks like the perfect solution for integrating einhorn with any router. Much better than a dependent implementation (like goji's).

I will review it this evening, and I hope I contribute to that project. Let's work to make it front-page in HN.

**Comment by badoet** [comment]
@dcu awesome stuff!
im intending to switch over to a golang solution that works like einhorn
something like
github.com/rcrowley/goagain
or github.com/fvbock/endless
not sure what are the differences 
any thoughts?

**Comment by badoet** [comment]
update:
i tried using the http-einhorn library.
it works great on first load. but after a few hours, accessing the `einhornsh` in server will cause timeout error and leave the golang app stranded.
i have decided to move to endless instead. although the app ends up not having a supervisor parent, at least the design works perfectly.
