### ISSUE TITLE
how could i add a  gin.Contenxt.method() when i new a gin.Engine

### ISSUE THREAD

**Issue by birdycn** [gin-gonic/gin#1833]
```
//controller.go

func OneApi(c *gin.Context) {
	appG := app.Gin{C: c}
	appG.Response(http.StatusOK, 200, 'helloword')
}
```
```
//app.go

type Gin struct {
	C *gin.Context
}

func (g *Gin) Response(httpCode, code int, data interface{}) {
	g.C.JSON(httpCode, gin.H{
		"code": code,
		"data": data,
	})
	return
}

```

This is the way I realize now.
But I think it's not a best way，because it must write 'app.gin{C:c}' when i want to call Response().

**Comment by dmarkham** [comment]
So I have noticed for me, most of the time when you work this hard to do what you want there is a better way. Can you explain a little more why your trying to add this method? What is your thinking / problem your trying to solve with this new method?  

I know you asked how to add a method, but I would like to change the way your thinking about it a little. If your goal is to get a helper method to respond, I would have tried something more like this.
```
func main() {
	r := gin.Default()
	r.GET("/ping", oneApi)
	r.Run()
}

func oneApi(c *gin.Context) {
	response(c, http.StatusOK, 200, "helloword")
}

func response(c *gin.Context, httpCode, code int, data interface{}) {
	c.JSON(httpCode, gin.H{
		"code": code,
		"data": data,
	})
	return
}
```
With that said, unless your writing some lower level library or have a really good use case, or just really know what your doing I would generally stay away from empty interfaces like  `data interface{}`.  

This is a little better. Hope this helps.

```

func main() {
	r := gin.Default()
	r.GET("/ping", oneApi)
	r.Run()
}

type Res struct {
	StatusCode int
	Data       string
}

func oneApi(c *gin.Context) {
	response(c, Res{http.StatusOK, "helloword"})
}
func response(c *gin.Context, r Res) {
	c.JSON(r.StatusCode, gin.H{
		"code": r.StatusCode,
		"data": r.Data,
	})
	return
}
```

**Comment by birdycn** [comment]
> 所以我注意到了我，大多数时候你努力工作以做你想做的事情有更好的方法。您能解释一下为什么尝试添加此方法吗？您尝试使用这种新方法解决的想法/问题是什么？
> 
> 我知道你问过如何添加方法，但我想改变你对它的思考方式。如果你的目标是获得一个帮助方法来响应，我会尝试更像这样的东西。
> 
> ```
> func main() {
> 	r := gin.Default()
> 	r.GET("/ping", oneApi)
> 	r.Run()
> }
> 
> func oneApi(c *gin.Context) {
> 	response(c, http.StatusOK, 200, "helloword")
> }
> 
> func response(c *gin.Context, httpCode, code int, data interface{}) {
> 	c.JSON(httpCode, gin.H{
> 		"code": code,
> 		"data": data,
> 	})
> 	return
> }
> ```
> 话虽如此，除非你写一些较低级别的库或有一个非常好的用例，或者只是真的知道你在做什么，我通常会远离空接口 `data interface{}`。
> 
> 这好一点。希望这可以帮助。
> 
> ```
> 
> func main() {
> 	r := gin.Default()
> 	r.GET("/ping", oneApi)
> 	r.Run()
> }
> 
> type Res struct {
> 	StatusCode int
> 	Data       string
> }
> 
> func oneApi(c *gin.Context) {
> 	response(c, Res{http.StatusOK, "helloword"})
> }
> func response(c *gin.Context, r Res) {
> 	c.JSON(r.StatusCode, gin.H{
> 		"code": r.StatusCode,
> 		"data": r.Data,
> 	})
> 	return
> }
> ```

thanks

**Comment by dmarkham** [comment]
@thinkerou Issue seems resolved.
