### ISSUE TITLE
Need extensive documentation

### ISSUE THREAD

**Issue by alwindoss** [gin-gonic/gin#1834]
Current State:
Getting started with minimalistic examples

What is needed:
Comprehensive guide, a step by step approach. This framework has a lot of potential but new users like me struggle to find answers.

**Comment by thinkerou** [comment]
@alwindoss thanks!
documentation please visit: gin-gonic.com
example please see github.com/gin-gonic/examples which includes many example, i.e, basic.

**Comment by alwindoss** [comment]
I think a better job of documentation can be done.
