### ISSUE TITLE
response a json,how could i make the cases "lowercase"?

### ISSUE THREAD

**Issue by birdycn** [gin-gonic/gin#1835]
Example:
`
type T struct {
    Foo int
}
`

response,will tips:
`
{"Foo":42}
`

but i want to get 
`
{"foo":42}
`

In many cases, it is very difficult to define lowercase one by one. Is there a simple way?

**Comment by pollen5** [comment]
Add the json property in the struct like so:
```go
type T struct {
  Foo int `json:"foo"`
}
```
That tells what to name the key when serializing to json

**Comment by zxcV32** [comment]
Thanks, @ravener for the response. I was wondering if there is some kind of configuration that I can do once so I don't have to write the extra text every time?

For example,

Instead of 
```go
type T struct { 
  FooBar string `json:"fooBar"`
}
```
I only do this
```go
type T struct { 
  FooBar string
}
```
but get this
```json
{"fooBar":42}
```
