### ISSUE TITLE
What happened to all the documentation?

### ISSUE THREAD

**Issue by tnolet** [gin-gonic/gin#1838]
Hi,

Where did all the super handy documentation in the README.md go? The new site is not really usable and misses a lot of the detailed stuff that was here before.

I'm now using the version at this commit to look up stuff. https://github.com/gin-gonic/gin/blob/f38a3fe65f102dd765e097166e6a41f9e99777f6/README.md

Please bring back the README.md as it was, the new site makes Gin not a very attractive to use Go project.

**Comment by M-Anwar** [comment]
+1 agree with this. Please bring back the documentation or make it available in full on the new website.

**Comment by thinkerou** [comment]
thanks! @tnolet @M-Anwar 

> make it available in full on the new website

what's issue about new website?

And the website documentation come from old README completely.

**Comment by M-Anwar** [comment]
@thinkerou It seems like most of the documentation is there now under `examples`. For some reason the scroll bar wasn't rendering on the side navigation bar and it looked like the documentation was missing. Looks good now.

**Comment by tnolet** [comment]
@thinkerou 

The website is not searchable and there is no index of topics at the beginning. Now all relevant info is crammed into a corner which is not wide enough and needs a ton of scrolling. 

I can totally help you fix this. Maybe just grab a template from something like docusaurus and add free Algolia search. Happy to help with that.

![image](https://user-images.githubusercontent.com/3802923/55540800-017c1a80-56c4-11e9-9509-3c4c571f828c.png)

**Comment by appleboy** [comment]
We reverted the readme first and will improve the document website.

**Comment by tnolet** [comment]
@appleboy please ping me if you need help. I've  made some well received documentation sites in the past. Examples are:
- https://vamp.io/documentation/using-vamp/v1.0.0/deployments/
- https://checklyhq.com/docs/

**Comment by y4code** [comment]
Somebody know where i can read NOT ROLLBACK version document translated into Chinese?
