### ISSUE TITLE
Vendor dependency cells-v1.4.1 having AGPL 3.0 licenses

### ISSUE THREAD

**Issue by asadhu** [gin-gonic/gin#1839]
- go version: 1.11.5
- gin version (or commit ref): 1.3.0
- operating system: unix

## Description
We are using gin-gonic which internally uses json-iterator(even though not being used in the project). When I vendor all the dependencies I find that json-iterator have a dependency on cells-v1.4.1 which is AGPL 3.0 and shouldn't be used.

Please can we update to not use such dependencies which overrides the default License permissions for json-iterator

## Screenshots
<img width="551" alt="Screen Shot 2019-04-03 at 9 31 45 AM" src="https://user-images.githubusercontent.com/10854334/55482867-64ea4780-55f3-11e9-8d3a-877f315c8e2d.png">

**Comment by dmarkham** [comment]
So I'm not seeing `cells` referenced anywhere in `gin` or `json-iterator`,  I also see you opened an issue over on `json-iterator`. 

Can you please give more details to help me track this down.  I checked all 3 files you are listed none seem to reference `pydio/cells`

**Comment by thinkerou** [comment]
@asadhu please post more details and reopen if you need, thanks!
