### ISSUE TITLE
Binding multipart.FileHeader but not working

### ISSUE THREAD

**Issue by sunzhenyucn** [gin-gonic/gin#1845]
I tried to binding `multipart.FileHeader` to struct but not working, help plz!!
I send request used Postman:

![post_information_1](https://user-images.githubusercontent.com/20114873/55578923-9e34cb80-5749-11e9-8970-7c6c8ae2bdd9.jpg)
![post_information_2](https://user-images.githubusercontent.com/20114873/55578930-a12fbc00-5749-11e9-8010-91cae8875269.jpg)

- Go Version: go 1.12 linux/amd64
- Operating System: Ubuntu 16.04

This is code:

Struct:

```go
ExtractAttributeRequest struct {
		Image       *multipart.FileHeader `form:"image" binding:"required"`
		ImageBase64 string                `form:"image_base64"`
}
```

Binding part:

```go
var req ExtractAttributeRequest
err := c.MustBindWith(&req, binding.FormMultipart)
```

And i got this error message: `Key: 'ExtractAttributeRequest.Image' Error:Field validation for 'Image' failed on the 'required' tag`

**Comment by vkd** [comment]
I cannot reproduce this error.

gin branch: master
```
func main() {
	r := gin.New()
	r.POST("/", func(c *gin.Context) {
		var req struct {
			Image       *multipart.FileHeader `form:"image" binding:"required"`
			ImageBase64 string                `form:"image_base64"`
		}
		err := c.MustBindWith(&req, binding.FormMultipart)
		if err != nil {
			c.String(500, "error: %v\n", err)
			return
		}
		c.String(200, "ok\n")
	})
	r.Run(":8000")
}
```

```
$ curl localhost:8000 -X POST -H "Content-Type:multipart/form-data" -F "image=@/home/user/image.jpg"
ok
```

Can you give more examples? What version of gin are you using?

**Comment by sunzhenyucn** [comment]
> I cannot reproduce this error.
> 
> gin branch: master
> 
> ```
> func main() {
> 	r := gin.New()
> 	r.POST("/", func(c *gin.Context) {
> 		var req struct {
> 			Image       *multipart.FileHeader `form:"image" binding:"required"`
> 			ImageBase64 string                `form:"image_base64"`
> 		}
> 		err := c.MustBindWith(&req, binding.FormMultipart)
> 		if err != nil {
> 			c.String(500, "error: %v\n", err)
> 			return
> 		}
> 		c.String(200, "ok\n")
> 	})
> 	r.Run(":8000")
> }
> ```
> ```
> $ curl localhost:8000 -X POST -H "Content-Type:multipart/form-data" -F "image=@/home/user/image.jpg"
> ok
> ```
> Can you give more examples? What version of gin are you using?

Thank you for your reply, my gin version is v1.3.0, I will try to use master branch.

**Comment by uneight** [comment]
@thinkerou Can i use shouldbind for not require file filed? If i use omitempty and not present the file field, i get message "http: no such file"

**Comment by thinkerou** [comment]
@uneight please see the example https://github.com/gin-gonic/examples/tree/master/file-binding thanks!

**Comment by jimmy-insignia** [comment]
@uneight @thinkerou I also have this problem and already see the example and still get an error. if I want to make file *Optional*, I still get error "http: no such file". how can I bind optional file to struct?

My code:
```
// UpdateUserRequest UpdateUserRequest
type UpdateUserRequest struct {
	Name            string                `form:"name" binding:"required"`
	Email           string                `form:"email"`
	Phone           *string               `form:"phone"`
	LinkedIn        *string               `form:"linkedin"`
	ExperienceYears *int                  `form:"experience_years"`
	CV              *multipart.FileHeader `form:"cv" binding:"omitempty"`
}

var params datatransfers.UpdateUserRequest
if err := c.ShouldBindWith(&params, binding.FormMultipart); err != nil {
	c.Error(err)
	return
}
```

Returned `"http: no such file"`

**Comment by 0Rohan** [comment]
use  `c.FormFile("file")`
