### ISSUE TITLE
Cannot find package "github.com/golang/protobuf/proto"...

### ISSUE THREAD

**Issue by softwareeverything** [gin-gonic/gin#1850]
When I tried to run main.go it gives an error being "cannot find package "github.com/golang/protobuf/proto""

```
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run() // listen and serve on 0.0.0.0:8080
}
```

**Comment by clock21am** [comment]
can you please try command **go get github.com/golang/protobuf/proto** ?

**Comment by clock21am** [comment]
is your go version 1.6 or more than that ?. I am afraid gin doesn't support prior version than 1.6.

**Comment by softwareeverything** [comment]
Thanks, clock21am. My go version 1.12 on Windows 8.1 operating system. I know that 1.12 is the latest version of go. There is no any package on "https://github.com/golang/protobuf/proto" url. How can i fix this?

**Comment by clock21am** [comment]
ooh my bad can you please try https://github.com/golang/protobuf ?
