### ISSUE TITLE
There is no way to protect from csrf attack in gin-goind

### ISSUE THREAD

**Issue by sadegh-shahbazi** [gin-gonic/gin#1855]
- With issues:There is no way to protect from csrf attack in gin-goind
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:1.12
- gin version (or commit ref):
- operating system:windows 10

## Description
the only package to use for csrf middleware for gin-gonic is 
https://github.com/utrack/gin-csrf/
it was not powerful
and it's not working any more...

what should we do?

**Comment by mikeee** [comment]
I've replied to an issue you created in the [utrack/gin-csrf repo](https://github.com/utrack/gin-csrf/issues/14) - works fine for me 🙌

Failing that you can use other csrf middleware such as [gorilla/csrf](https://github.com/gorilla/csrf)

**Comment by dmarkham** [comment]
@sadegh-shahbazi did these work for you? If so lets close this issue.
