### ISSUE TITLE
Similar URL strange bug

### ISSUE THREAD

**Issue by vasiliyaltunin** [gin-gonic/gin#1860]
Ok, it very strange bug and i solve it, but i post it here, so maybe if some one have similar problem, can also easy solve it.

Ok i have two GET url controller functions:

```
	r.GET("/arc/predp", GetPredprArcList)
	r.GET("/arc/predpid", GetPredpIDArcList)

```

When i develop and test it locally it works just fine, but when i put it on production server with https i have strange problem:

`/arc/predp` works just fine, but `/arc/predpid` not processed at all, i just put 
`fmt.Println("\nArc ID List")` in `GetPredpIDArcList` and it never writes in output.

But, when i try to use Yandex.Browser and enable it `Turbo mode`, it similar Opera `Turbo mode` all works just fine, but in Firefox it works us described above.

So i try change URL's to like this:

```
	r.GET("/arc_predp", GetPredprArcList)
	r.GET("/arc_predpid", GetPredpIDArcList)

```

and all works just fine.

It all very strange and i hope this helps some one or maybe there is really some bug in Gin and it helps fix it.

**Comment by thinkerou** [comment]
```
➜  ~ cat g.go
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.GET("/arc/predp", GetPredprArcList)
	r.GET("/arc/predpid", GetPredpIDArcList)
	r.Run()
}

func GetPredprArcList(c *gin.Context) {
	c.String(200, "It's not ID")
}

func GetPredpIDArcList(c *gin.Context) {
	c.String(200, "It's ID")
}
```
It's run fine.

**Comment by vasiliyaltunin** [comment]
Well, i use github.com/markbates/goth and github.com/gorilla/sessions so it may be only appear in few times and specific situations, but anyway i hope this help some one.
