### ISSUE TITLE
How to upload file directory

### ISSUE THREAD

**Issue by NoGroceries** [gin-gonic/gin#1862]

**Comment by NoGroceries** [comment]
go-version&system: go1.11.5 windows/amd64
gin-version:v1.4.0-dev

**Comment by thinkerou** [comment]
what's mean? please post more details. thanks!

**Comment by appleboy** [comment]
@NoGroceries See the examples: https://github.com/gin-gonic/examples/tree/master/upload-file

**Comment by NoGroceries** [comment]
> what's mean? please post more details. thanks!

for example: i want upload folder a, it includs file b, c

**Comment by appleboy** [comment]
@NoGroceries Please zip the source file and upload the zip file then unzip.

**Comment by NoGroceries** [comment]
> @NoGroceries Please zip the source file and upload the zip file then unzip.

thank you
