### ISSUE TITLE
How do you think bilibili-common a China company leaked code copy from gin?

### ISSUE THREAD

**Issue by JonSnow47** [gin-gonic/gin#1863]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: 1.8+
- gin version (or commit ref): all
- operating system: linux

## Description
I think bilibili-common copy or reference from gin.

## Screenshots
https://github.com/xiaozaiziwyt/backup-openbilibili-go-common/blob/af2bea9c31465a9a2a5ef362b4f08667d2334109/library/net/http/blademaster/context.go#L30

**Comment by soenggam** [comment]
Bilibili is a victim😭

**Comment by JonSnow47** [comment]
> Bilibili is a victim😭

I thought you can use it, or fork it and so, but should't copy it.

**Comment by aleimu** [comment]
The web framework needs to implement the http protocol, which is similar, which is normal.Don't be too picky!

**Comment by thinkerou** [comment]
thanks! closing.
