### ISSUE TITLE
write tcp 127.0.0.1:7070->127.0.0.1:34514: write: connection reset by peer

### ISSUE THREAD

**Issue by llakes** [gin-gonic/gin#1864]
- go version: go1.12.3 linux/amd64
- gin version (or commit ref):  1.4
- operating system: Debian GNU/Linux 8 (jessie)

## Description
When I visit a particular path, I get "**2019/04/23 14:29:45 write tcp 127.0.0.1:7070->127.0.0.1:34514: write: connection reset by peer**" in the production environment. But everything works fine in testing (without nginx). Please How do I debug this problem. Thank you.

**Comment by dmarkham** [comment]
We will really need a lot more info on your setup to help you debug this. I suspect in your effort to make a small reproducible setup, you will end up solving the issue.

**Comment by llakes** [comment]
`
//ContactUs contact form controller function
func ContactUs(c *gin.Context, r *gin.Engine) {
	db := c.MustGet("DB").(*pg.DB)
	templateName := "contact_form.tmpl"
	templateSource, _ := GetTemplate(c.GetHeader("User-Agent"))
	template := templateSource + templateName
	var errA error
	formErrs := make(map[string]string)
	var con contactBind
	var catS []*CatStruct
	var name, email string

	session := sessions.Default(c)
	suser := session.Get("sessionUserID")
	if suser != nil {
		err := db.Model(&models.User{}).Where("id = ?", suser.(int64)).
			Column("name", "email").Limit(1).Select(&name, &email)
		panicIf(err)
	}

	for x, y := range models.CATS {
		count, err := db.Model(&models.HelpdeskTopic{}).
			Where("category = ?", x).Count()
		panicIf(err)
		ct := CatStruct{y, fmt.Sprintf("/support/category/%s", x), x, count}
		catS = append(catS, &ct)
	}
	cxt := map[string]interface{}{
		"cats": catS,
	}

	if c.Request.Method == POST {
		if errA = c.ShouldBind(&con); errA == nil {
			var cok bool
			sck := session.Get("support_post")
			if sck != nil {
				var captchaID string
				codec := utils.GetRedisCache()
				err := codec.Get(sck.(string), &captchaID)
				if err != nil {
					cok = false
					err = codec.Delete(sck.(string))
					panicIf(err)
					formErrs["Captcha"] = "Captcha error"
				} else {
					cok = captchaVerifyHandle(captchaID, con.Captcha)
					err = codec.Delete(sck.(string))
					panicIf(err)
					if !cok {
						formErrs["Captcha"] = "Captcha error"
					}
				}
			} else {
				cok = false
				formErrs["Captcha"] = "Captcha error"
			}
			if suser != nil {
				cok = true
			}
			if cok {
				sub := fmt.Sprintf("Re: %s", con.Subject)
				topic := models.HelpdeskTopic{
					Subject:     con.Subject,
					Sender:      con.Name,
					SenderEmail: con.Email,
					Category:    con.Category,
				}
				err := db.Insert(&topic)
				panicIf(err)
				msg := models.HelpdeskMessage{
					Message:     con.Message,
					Sender:      con.Name,
					SenderEmail: con.Email,
					Public:      false,
				}
				err = db.Insert(&msg)
				panicIf(err)
				ht2m := models.HelpdeskTopicMessage{
					HelpdeskTopicID:   topic.ID,
					HelpdeskMessageID: msg.ID,
				}
				err = db.Insert(&ht2m)
				panicIf(err)
				eMsg := fmt.Sprintf(`
			{"Name":"processHelpdesk",
			"Stuffs":
			{
				"action": "update_topic",
				"topicID": "%d",
				"messageID": "%d",
				"public": "true",
				"subject": "%s",
				"message": "%s",
				"sender": "%s",
				"senderEmail": "%s",
				"category": "%s",
				"adminMsg": "false",
				"AdminMessage": "[What is the message? -- set adminMsg to 'true']",
			}
		}
		`, topic.ID, msg.ID, sub, con.Message, con.Name, con.Email, con.Category)
				SendMailAdmin(sub, eMsg, con.Email)
				m := "Query sent successfully"
				next := "/support/public/" + topic.HelpID
				AddFlashMessage(c, "success", m)
				c.Redirect(301, next)
				return
			}
		}
	}

	var urlFilterString string
	paths := strings.Split(fmt.Sprintf("%s", c.Request.URL), "?")
	if len(paths) > 1 {
		if len(paths) > 2 {
			urlFilterString = strings.Join(paths[1:], "?")
		} else {
			urlFilterString = paths[1]
		}
	}
	urlFilter, err := url.ParseQuery(urlFilterString)
	panicIf(err)
	_, pageFilter := processFilter(urlFilter)

	category := c.Param("cat")
	var hts []*models.HelpdeskTopic
	var count int
	if category == "" {
		count, err = db.Model(&hts).OrderExpr("helpdesk_topic.created_at DESC").
			Apply(urlvalues.Pagination(urlvalues.Values(pageFilter))).
			Where("public = ?", true).SelectAndCount()
		panicIf(err)
		cxt["title"] = "Public Topics"
	} else {
		count, err = db.Model(&hts).Where("category = ?", category).
			Where("public = ?", true).OrderExpr("helpdesk_topic.created_at DESC").
			Apply(urlvalues.Pagination(urlvalues.Values(pageFilter))).
			SelectAndCount()
		panicIf(err)
		cxt["title"] = models.CATS[category]
	}
	cxt["hts"] = hts
	cxt["count"] = count
	if errA != nil {
		formErrs = processFormErrors(errA, formErrs)
	}
	contactForm(c, template, formErrs, cxt, name, email, category)
	return
}

`

`
//contactForm contact form
func contactForm(c *gin.Context, template string, formErrs map[string]string,
	cxt map[string]interface{}, name, email, category string) {
	var form *forms.Form

	captchaID, filePath := generateCaptchaHandler(6)
	randKey := utils.GenerateUUID()
	session := sessions.Default(c)
	session.Set("support_post", randKey)
	session.Save()
	codec := utils.GetRedisCache()
	codec.Set(&cache.Item{
		Key:        randKey,
		Object:     captchaID,
		Expiration: 5 * time.Minute,
	})

	form = forms.BaseForm(POST, fmt.Sprintf("%s", c.Request.URL), csrf.TemplateField(c.Request), false).Elements(
		fields.TextField("name").SetLabel("Name").
			AddError(formErrs["Name"]).
			AddClass("smooth large__input").SetID("name").
			SetParam("required", "required").
			SetValue(name).
			SetParam("maxlength", "150").
			SetParam("placeholder", "Name"),
		fields.EmailField("email").SetLabel("Email").
			AddError(formErrs["Email"]).
			SetValue(email).
			AddClass("smooth large__input").SetParam("required", "required").SetID("email").
			SetParam("placeholder", "Email"),
		fields.SelectField("category", cats).SetLabel("Category").
			AddError(formErrs["Category"]).
			AddSelected(category).
			AddClass("smooth").SetParam("required", "required").SetID("category"),
		fields.TextField("subject").SetLabel("Subject").
			AddError(formErrs["Subject"]).
			AddClass("smooth large__input").SetID("subject").
			SetParam("maxlength", "150").
			SetParam("placeholder", "Subject"),
		fields.TextAreaField("message", 10, 50).SetLabel("Message").
			AddClass("smooth").SetParam("required", "required").SetID("subject").
			AddError(formErrs["Message"]).SetParam("placeholder", "Message"),
	)

	suser := session.Get("sessionUserID")
	if suser == nil {
		form = form.AddField(
			fields.CaptchaField("captcha", captchaID, filePath).SetLabel("Captcha").
				AddClass("smooth").SetParam("required", "required").SetID("captcha").
				SetParam("autocomplete", "off").
				SetParam("autocorrect", "off").
				SetParam("spellcheck", "false").
				AddError(formErrs["Captcha"]).
				SetParam("autocapitalize", "off"),
		)
	}
	form = form.AddField(fields.SubmitButton("submit", "Submit").AddClass("btn btn-sm btn-a btn-primary").SetID("submit_btn"))

	cxt["form"] = form
	if len(formErrs) != 0 {
		m := "Please correct the errors below."
		AddFlashMessage(c, "error", m)
	}
	HTMLRender(200, template, c, contextProcessor(cxt, c))
	return
}

`

HTMLRender is used by every view function
