### ISSUE TITLE
convert http.Request to gin.context

### ISSUE THREAD

**Issue by 18959263172** [gin-gonic/gin#1869]
hi guys, for some reason I want to convert a http.Request and http.response to gin.context, could anybody do that?

**Comment by dmarkham** [comment]
Hello @18959263172 
Most of the time you want to do this for `middleware`. I think looking into `WrapF` and `WrapH` would be helpful to you. 

https://github.com/gin-gonic/gin/blob/202f8fc58af47ab5c8e834662ee7fc46deacc37d/utils.go#L38-L43
