### ISSUE TITLE
how to transform gin.Context.Keys  use Reverse Proxy 

### ISSUE THREAD

**Issue by NoGroceries** [gin-gonic/gin#1871]
```
func ReverseProxy(host string) gin.HandlerFunc {
	return func(c *gin.Context) {
		director := func(req *http.Request) {
			req.URL.Scheme = "http"
			req.URL.Host = host
		}
		proxy := &httputil.ReverseProxy{Director: director}
		proxy.ServeHTTP(c.Writer, c.Request)

	}
}
```
how to set gin.Context.Keys from source to target server

**Comment by AndyFoolish** [comment]
I just read the `ServeHTTP` source code，`ServeHTTP` come from official module, so you can not use gin.Context.Keys directly. But you can deal with the `req.URL.Body` or other params instead

**Comment by NoGroceries** [comment]
> I just read the `ServeHTTP` source code，`ServeHTTP` come from official module, so you can not use gin.Context.Keys directly. But you can deal with the `req.URL.Body` or other params instead

3q，I used ‘req.Header’

**Comment by NoGroceries** [comment]
> I just read the `ServeHTTP` source code，`ServeHTTP` come from official module, so you can not use gin.Context.Keys directly. But you can deal with the `req.URL.Body` or other params instead

3q，I used ‘req.Header’
