### ISSUE TITLE
How can I get user/password from url with gin

### ISSUE THREAD

**Issue by AndyFoolish** [gin-gonic/gin#1872]
## Description
I am a gin beginner, and code just like this:
```
url = "http://user:password@127.0.0.1:8000"
router.POST("/test", testHandler)
func testHandler(c *gin.Context) {
    //c.Request.URL
}
```
I want to get **"user","password"** from `c.Request.URL`, but I got only `/test` when I print the  `c.Request.URL`.

Does anyone have an idea?

**Comment by thinkerou** [comment]
You should use `c.Request.Host`.

**Comment by AndyFoolish** [comment]
> You should use `c.Request.Host`.

I print the `c.Request.Host`, unfortunately I only got the `ip:port`

**Comment by cgetzen** [comment]
For others looking for answers:
```
c.Request.Header["Authorization"]
```
is a 1-item slice of strings with the value `Basic dXNlcm5hbWU6cGFzc3dvcmQ=`.
If you base64 decode that value, it will be `username:password`.
