### ISSUE TITLE
gin release process

### ISSUE THREAD

**Issue by dmarkham** [gin-gonic/gin#1882]
Now that @appleboy  and @thinkerou  are able to do releases. I would like to propose some changes in the process.
**Issue**:
1. Things land on master for months before an official release. This causes a few issues,

* People might wrongfully think new features or methods on master before a release are covered under the Semantic Versioning guarantees.
 
* Releasing a `PATCH` will end up releasing code that was on master, waiting for the next `MINOR` release. This has a side effect of making us slow to release `PATCH`'s because we know it's going to effect everything currently on master.

**Proposal**:

I would like to propose we cut a branch from master for the next `MINOR` release after we do a release then we merge all the new issues for that Milestone into that.

e.x:   When we release  `1.4.0` we create a `1.5.0` branch and take all new feature pull requests into the `1.5.0` branch. This way if we need to preform a `PATCH` release we can quickly merge a `PATCH` into master and then release `1.4.1`, without having to bring in all the current work we are doing for `1.5.0`.  Once `1.5.0`  closes all the milestones or meets it's deadline and becomes stable, It's merged into master and tagged `1.5.0` and we cut a `1.6.0` branch and start over.

Feedback welcome!

**Comment by thinkerou** [comment]
@dmarkham thanks!
Now we should do the follow steps:
1. which one opening pull request need merge to `gin1.4`?
2. which one issue need complete and commit pull request and merge to `gin1.4`?

**Comment by dmarkham** [comment]
> @dmarkham thanks!
> Now we should do the follow steps:
> 
> 1. which one opening pull request need merge to `gin1.4`?

#1851 is I think the one we should start with. 

> 2. which one issue need complete and commit pull request and merge to `gin1.4`?

Sorry I do not understand the question.
