### ISSUE TITLE
I'm new.How to write test in jin?

### ISSUE THREAD

**Issue by EveryDayNew** [gin-gonic/gin#1884]
//main
package main

import (
	"fmt"
)

func main()  {

	r := router.NewRouter()
	r.Run(addr)
}
//router
package router

import (
	"github.com/gin-gonic/gin"
	"xflow-be/controller"
)
func NewRouter() *gin.Engine {
	app := gin.New()
	skelCtl := controller.NewSkelController()
	skelGroup := app.Group("/skel")
	{
		skelGroup.POST("/get", skelCtl.Get)
		skelGroup.POST("/del", skelCtl.Del)
		skelGroup.POST("/list", skelCtl.List)
		skelGroup.POST("/add", skelCtl.Add)
		skelGroup.POST("/update", skelCtl.Update)
		skelGroup.POST("/get_by_field", skelCtl.GetByField)
	}
	return app
}
//controller
package controller

type SkelController struct {
	BaseController
}

func NewSkelController() *SkelController {
	return &SkelController{}
}
func (ts *SkelController) List(ctx *gin.Context) {
	if ents, err := ts.newService().List(); err != nil {
		ts.ReplyFail(ctx, err)
	} else {
		ts.ReplyOk(ctx, ents)
	}
}

**Comment by igorrius** [comment]
You could using https://golang.org/pkg/net/http/httptest/ package.

**Comment by thinkerou** [comment]
@EveryDayNew Maybe you should read gin unittest file.
