### ISSUE TITLE
gin/json package not found,when i use golang1.12.5 version.

### ISSUE THREAD

**Issue by daheige** [gin-gonic/gin#1887]
golang1.12.5 version:
Gin is using the golang1.12.5 version, and the go mod mechanism is enabled. When the project code is compiled, the compilation does not pass, and the gin/json package cannot be found.

**Comment by thinkerou** [comment]
@daheige can you post your example code?
gin have no `gin/json` package.

**Comment by daheige** [comment]
My example code is the demo provided by your official website. When I compile this simple example in the Linux environment, I can't find the gin/json package directly on the terminal. I try to copy the json internal package of gin1.4.0 to Its upper level directory, and then compiled to pass, I initially suspected that go1.12.5 has bugs for internal package support, or gin processing is wrong.

**Comment by daheige** [comment]
https://github.com/gin-gonic/gin/tree/v1.4.0/internal/json maybe this package of gin1.4.0 has bug,when i use golang1.12.5.

**Comment by dmarkham** [comment]
@daheige  are you using  `govendor` or `GO111MODULE` ? 
or are you just building master in you `$GOPATH`?

**Comment by daheige** [comment]
go mod is enabled.

**Comment by daheige** [comment]
i use go mod.

**Comment by daheige** [comment]
GO111MODULE=auto,my code outside gopath.

**Comment by dmarkham** [comment]
I'm not yet able to reproduce this... what OS are you on, trying to see what would be different. 


```
dmarkham@New-Dawn:~/sample  $ go run main.go 
go: finding github.com/gin-gonic/gin v1.4.0
go: downloading github.com/gin-gonic/gin v1.4.0
go: extracting github.com/gin-gonic/gin v1.4.0
go: finding github.com/ugorji/go v1.1.4
go: finding golang.org/x/net v0.0.0-20190503192946-f4e77d36d62c
go: downloading github.com/ugorji/go v1.1.4
go: extracting github.com/ugorji/go v1.1.4
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] Listening and serving HTTP on :8080
^Csignal: interrupt
dmarkham@New-Dawn:~/sample  $ go version 
go version go1.12.5 linux/amd64
```

**Comment by daheige** [comment]
Sorry, I found the problem. I used gin1.3.0 in my code,I tried gin1.4.0 these days, and then I import “github.com/gin-gonic/gin/json” in my previous code. Package, when I compile, I can't find it. Here I suggest that when upgrading gin1.4.0, can you not remove the json package from the previous 1.3.0?

**Comment by thinkerou** [comment]
@daheige `gin1.3.0` gin/json package code: https://github.com/gin-gonic/gin/blob/v1.3.0/json/json.go

```
// +build !jsoniter

package json

import "encoding/json"

var (
	Marshal       = json.Marshal
	MarshalIndent = json.MarshalIndent
	NewDecoder    = json.NewDecoder
)
```

If you want to use json package, I suggest you use `encoding/json`.

**Comment by daheige** [comment]
Thank you, this way is OK, I read the 1.3.0 source code, you are doing a layer of JSON packaging, making it more efficient than the original JSON package, so I think in 1.4.0, can you keep Or, in the upgrade log, this is good for developers. By reading your source code, it seems that you haven't seen what every version of gin has done, and whether it can be upgraded, like Google's projects, is listed.

**Comment by thinkerou** [comment]
@daheige thanks! it should record upgraded log, sorry about the point.
