### ISSUE TITLE
Url param does not support top-level path binding

### ISSUE THREAD

**Issue by daheige** [gin-gonic/gin#1888]
I found that the routing path does not support the following url param form, router.GET("/:name/*action", func(c *gin.Context) {
Name := c.Param("name")
Action := c.Param("action")
Message := name + " is " + action
c.String(http.StatusOK, message)
})
But when I use gorilla/mux or go-chi/chi framework, they both support, can support such a path in gin, because many developers do have such a requirement, your gin package has not supported this Function, can it be supported in versions after 1.4.0?

**Comment by dmarkham** [comment]
Hello @daheige ,

Maybe I do not understand what you mean, This I think does what your asking for.

```
package main
import (
	"net/http"
	"github.com/gin-gonic/gin"
)
func main() {
	r := gin.Default()
	r.GET("/:name/:action", func(c *gin.Context) {
		Name := c.Param("name")
		Action := c.Param("action")
		Message := Name + " is " + Action + "\n"
		c.String(http.StatusOK, Message)
	})
	r.Run() // listen and serve on 0.0.0.0:8080
}
```

**Comment by daheige** [comment]
yes,you are right! current gin doesn’t support this way.

**Comment by thinkerou** [comment]
@daheige 
![image](https://user-images.githubusercontent.com/4488261/57432978-db6d0b80-7269-11e9-87ab-c7edfb0e230f.png)

**Comment by daheige** [comment]
package main
import (
	"net/http"
	"github.com/gin-gonic/gin"
)
func main() {
	r := gin.Default()
	r.GET("/:name/:action", func(c *gin.Context) {
		Name := c.Param("name")
		Action := c.Param("action")
		Message := Name + " is " + Action + "\n"
		c.String(http.StatusOK, Message)
	})
        r.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK,"ok")
	})
        r.GET("/a/b/c", func(c *gin.Context) {
		c.String(http.StatusOK,"ok")
	})
	r.Run() // listen and serve on 0.0.0.0:8080
}


please go run this code,it will throw panic

**Comment by thinkerou** [comment]
@daheige because `/:name/:action` and `/a/b/c` conflict. please see https://github.com/gin-gonic/gin/issues/388
