### ISSUE TITLE
New useful middleware

### ISSUE THREAD

**Issue by olebedev** [gin-gonic/gin#190]
Hi, guys.
I just wrote middleware for gin framework. To serve embedded by [go-bindata ](https://github.com/jteeuwen/go-bindata) static files. See it [here](https://github.com/olebedev/staticbin). 
Thoughts?

**Comment by javierprovecho** [comment]
Looks great, please submit a PR to [gin-gonic/contrib](https://github.com/gin-gonic/contrib) adding a link to your repo in the `README.md`

**Comment by olebedev** [comment]
@javierprovecho https://github.com/gin-gonic/contrib/pull/15
