### ISSUE TITLE
hi，I want  use http.server config ,like ReadTimeout, disableKeepAlives

### ISSUE THREAD

**Issue by LinuxForYQH** [gin-gonic/gin#1900]
I so love gin route, tree struct route is so perfect
if I want use http.Server config ReadTimeout , Only just do 

```go
r := gin.Default()
  r.GET("/ping", func(c *gin.Context) {
    c.JSON(200, gin.H{
      "message": "pong",})
})
service := &http.Server{Addr: ":9991",Handler:r}
service.ReadTimeout = time.Duration(time.Second*5)
service.ListenAndServe()
```

But I wantn't use like that,I want gin have a config Param. if  gin have a idea like that ,I want pull my request.

**Comment by sja1n** [comment]
you can give the timeout option in server struct itself like:

```
r := gin.Default()
  r.GET("/ping", func(c *gin.Context) {
    c.JSON(200, gin.H{
      "message": "pong",})
})
service := &http.Server{
Addr: ":9991",
Handler:r,
WriteTimeout: 10 * time.Second,
ReadTimeout:  10 * time.Second,
}
service.ListenAndServe()
```

**Comment by LinuxForYQH** [comment]
![image](https://user-images.githubusercontent.com/13944100/59502637-e2beaf00-8ed0-11e9-8631-703f791a9e8e.png)
一样的，你是国人吧(#^.^#)
