### ISSUE TITLE
conflict wildcard with difference endpoint name

### ISSUE THREAD

**Issue by TendiF** [gin-gonic/gin#1904]
- go version: 1.12.5
- operating system:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

## Description

why these two those lines give error 

    admin.PUT("/customer/:fixed", adminController.UpdateCustomer)
    admin.PUT("/customer/package/:fixed", adminController.UpdateCustomerPackage)

here panic message

`panic: 'package' in new path '/admin/customer/package/:fixed' conflicts with existing wildcard ':fixed' in existing prefix '/admin/customer/:fixed'`

anyone can explain, and I dont get it for solution from here [github](https://github.com/gin-gonic/gin/issues/205)

**Comment by thinkerou** [comment]
gin based on https://github.com/julienschmidt/httprouter, like issue: https://github.com/julienschmidt/httprouter/issues/73
