### ISSUE TITLE
error description of release v1.4.0

### ISSUE THREAD

**Issue by scarbo87** [gin-gonic/gin#1908]
Guys, you wrote in description to release [v1.4.0](https://github.com/gin-gonic/gin/releases/tag/v1.4.0) that included PR [NEW context: inherits context cancellation and deadline from http.Request context for Go>=1.7 #1690](https://github.com/gin-gonic/gin/pull/1690), but you reverted this code. Why?

**Comment by thinkerou** [comment]
@scarbo87 sorry about gin v1.4.0 release description, that pull request reverted and please see https://github.com/gin-gonic/gin/pull/1736, thanks!
maybe we should release gin v1.4.1 to fix some issue. cc @appleboy

**Comment by appleboy** [comment]
@scarbo87 I updated the release documentation in `v1.4.0`.
