### ISSUE TITLE
open index.tmpl: no such file or directory

### ISSUE THREAD

**Issue by ypapax** [gin-gonic/gin#191]
I get code from example with [html templates](https://github.com/gin-gonic/gin#html-rendering). I created file `site.go` in folder `/path/to/site` and run it with command `cd /path/to/site; go run site.go`
```go
package main
import (
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.LoadHTMLTemplates("templates/*")
	r.GET("/", func(c *gin.Context) {
		obj := gin.H{"Title": "Hello"}
		c.HTML(200, "index.tmpl", obj)
	})
	r.Run(":8080")
}

```

It gives error:
```bash
[GIN] 2015/01/05 - 16:56:35 | 500 |    662.277us | [::1]:64119  GET /
Error #01: open index.tmpl: no such file or directory 
     Meta: [index.tmpl map[Title:Hello]]
```

Although I create file `/path/to/site/templates/index.tmpl`.

**Comment by javierprovecho** [comment]
Also download latest commit from develop.

**Comment by Nixarn** [comment]
Doesn't work for me, I get the same problem. Maybe it's an OS issue? I'm on OSX

**Comment by imZack** [comment]
Same issue here, OS: Ubuntu

**Comment by bredov** [comment]
@Nixarn, @imZack, make sure that you use `develop` branch of repository.
```shell
$ cd $GOPATH/src/github.com/gin-gonic/gin
$ git checkout develop
```
Fix was not yet merged into `master` branch.

**Comment by imZack** [comment]
@bredov Great job! It works.
