### ISSUE TITLE
govendor  修改成gomod  之后， go mod 报github.com/ugorji/go版本不对

### ISSUE THREAD

**Issue by lppgo** [gin-gonic/gin#1910]
- With issues:
build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/home/lucas/local/work/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2 (/home/lucas/local/work/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181209151446-772ced7fd4c2)

- go version:
go version go1.12.5 linux/amd64
- gin version (or commit ref):
- operating system:

## Screenshots
![image](https://user-images.githubusercontent.com/37990195/58156456-b1bfd580-7ca8-11e9-96bd-a3f700e5b578.png)

**Comment by thinkerou** [comment]
please #1673
