### ISSUE TITLE
Drop go1.8/go1.9 support

### ISSUE THREAD

**Issue by dmarkham** [gin-gonic/gin#1912]
Drop go1.8/go1.9 support to stay somewhat close to go's supported versions and keep people from having to do workarounds to stay compatible with older versions of go.

**Comment by dmarkham** [comment]
@appleboy  @thinkerou   I think this should be a gin `1.5` milestone, does anyone have any reasons this should be an issue?

**Comment by thinkerou** [comment]
I agree @dmarkham 
gin1.5 support go1.10,1.11,1.12,1.13
gin1.6 support go1.11,1.12,1.13,1.14

**Comment by TonyPythoneer** [comment]
@thinkerou Please follow @dmarkham ‘s PR.
The issue has PR can get resolved. thx!
