### ISSUE TITLE
How to write router like /:account/:project ?

### ISSUE THREAD

**Issue by xia0ta0** [gin-gonic/gin#192]
Just like  the path of GitHub, github.com/julienschmidt/httprouter  can't support it.
thanks.

**Comment by xia0ta0** [comment]
https://github.com/dimfeld/httptreemux is better for routing, only slightly slower than httprouter.

**Comment by jamie-stackhouse** [comment]
Why is this not supported with httprouter?

**Comment by olebedev** [comment]
This s already supported with httprouter and gin. See README.md for details.

**Comment by jamie-stackhouse** [comment]
I was hoping we could get a response from @xia0ta0 because I was fairly certain httprouter actually benchmarks a lookalike of the Github API in a router shootout.

**Comment by javierprovecho** [comment]
@itsjamie @olebedev closing this, no hope @xia0ta0 will respond
