### ISSUE TITLE
It seems there's cache when use c.PostForm

### ISSUE THREAD

**Issue by colortell** [gin-gonic/gin#1927]
- With issues:
Hi all, when using c.PostForm to get parameters from ajax, it seems there's cache in it, and the values do not change for times.

- go version: 1.11.2
- gin version (or commit ref): latest
- operating system: Mac OS

**Comment by ori-saporta83** [comment]
I've had an issue with this as well. If the context is reused by the pool, it doesn't clear the form cache which creates a serious problem with the post params.

**Comment by christinaa** [comment]
Noticed the same, POST parameters obtained via `PostForm` seemed to be behaving strangely when using the builtin Go web server (through `ListenAndServe`).

Operating system: Ubuntu 18.04
Go version: 1.12.5
Gin version: master (as of the time of writing this: 73c4633943d596bdbeaa7d02cebdd4bd0c4f4630)

**Comment by happyEgg** [comment]
+1

**Comment by thinkerou** [comment]
may be related to #1920 I will check it. thanks!

**Comment by thinkerou** [comment]
Hi, guys, who can post one mini example to reproduce the issue, and I commit #1931 to attempt to fix it.

**Comment by colortell** [comment]
@thinkerou  Hi thinkerou,it's cool,  i've tested again after "context.go" modified as [#1931](https://github.com/gin-gonic/gin/pull/1931), it seems everything goes well now, thanks!

**Comment by maxchagin** [comment]
Hi!
I have the same bug! Create a simple test app with a demo https://github.com/maxchagin/gin-ajax-bug

go version: 1.12.5 (tried 1.12.4, 1.12.1, 1.11.10)

gin version (or commit ref): latest

operating system: Windows (Ubuntu, docker image golang)

I also have a old build gin in which everything works fine

**Comment by yakjuly** [comment]
+1

**Comment by CNbluer** [comment]
+1 very seriously problem, hope to solve it as soon as possible

**Comment by lovepepsi** [comment]
+1

**Comment by crazywako** [comment]
+1

**Comment by Racle** [comment]
+1

**Comment by thinkerou** [comment]
#1931 merged, please help us check, thanks!

**Comment by happyEgg** [comment]
下载其他三方库时造成这个库升级，后果是线上出现问题了，总监取消了我的年终奖，我该怎么办😢

**Comment by yakjuly** [comment]
golang的几个web框架 维护的都不怎么样，这个issue暴露出了 维护人员少 测试少的问题。如此重大的bug 修复后也没加过tag，建议把1.4.0 tag删了重做 不然谁用谁倒霉。

**Comment by hantmac** [comment]
如果在生产环境使用开源框架的话，还是建议fork一份，自己的开发人员自己维护，跟进社区版本的同时做好测试，发现问题也可以快速反馈，社区也需要这样的反馈。

**Comment by thinkerou** [comment]
please use release version in the production

**Comment by thinkerou** [comment]
@yakjuly sorry about the issue and the issue only exist the master branch.

**Comment by yakjuly** [comment]
@thinkerou Sorry, 是我看错了 v1.4.0是没问题的。
