### ISSUE TITLE
current panic make cpu skyrocket to 96%+,maybe this is bug.

### ISSUE THREAD

**Issue by daheige** [gin-gonic/gin#1929]
https://github.com/gin-gonic/gin/blob/73c4633943d596bdbeaa7d02cebdd4bd0c4f4630/render/json.go#L58
When the response is written to the writer, after the panic occurs here, the capture of the machine causes the CPU to skyrocket, which is close to 96%. When the 100% is reached, the request is lost, and the http service hangs.

**Comment by daheige** [comment]
the production gin version is v1.4.0,current panic leads to cpu skyrocketing.The current write stream write failed, and then the current request is caught in the panic, I made a recovery capture in the program, but in a few minutes, the cpu skyrocketed, causing the http service to crash. I checked the log and found that it was thrown. Out of panic

**Comment by daheige** [comment]
Online services have been online for several months, and today I suddenly encountered such problems.

**Comment by daheige** [comment]
My program online service more than 10 million users

**Comment by thinkerou** [comment]
> after the panic occurs here
why happen?

**Comment by daheige** [comment]
In the case of network fluctuations, load balancing uses long connections. Some requests are canceled on the client side, but the upsteam of the load balancing configuration is forwarded to the current gin http service. An error occurs because the write stream writer writes an exception. Render/json.go 58 lines throw panic, I made a defer recover capture in the middleware. In the few minutes during this period, the cpu of the whole machine suddenly soared to 96%+. Although the bottom layer of golang was recovered, the continuous request came over, which caused the server to hang directly, which affected the normal business service.

**Comment by daheige** [comment]
When the gin http service is restarted, there are still requests coming in at this time, but some of the requested clients have canceled the request, and this time the golang gin running http service does not know that the client has cancelled the request, or Write json data to this writer, and found that there is a problem by printing the log. In less than a minute, the cpu of the whole machine has soared to over 90%. The whole problem was checked for an afternoon. Through repeated positioning, I feel that there may be a bug here. I only consulted you how to solve the whole problem.

**Comment by dmarkham** [comment]
It is weird we panic instead of just returning the error. Wonder why that is.

**Comment by daheige** [comment]
At that time, the amount of network requests was too high, and it lasted for about 3 minutes. The qps of the machine reached more than 1200. However, my server configuration is very high, 8-core cpu, and 64G memory. The bottom of the http service is that each request is an independent request, but for such a large request, I think it can be handled, but my server is hanging up, when I look at the cpu up to 90%, it is incredible. When the panic appeared in this line, I was captured in the upper middleware. I captured all the stack information through the runtime. I preliminarily concluded that the request was too large at the time, causing the CPU to skyrocket, causing our service to hang.

**Comment by daheige** [comment]
It is possible that the request is too high, and a large number of goroutine processing requests are not coming. I checked the machine's memory usage by less than 50% at that time, but the CPU has reached more than 90%.

**Comment by daheige** [comment]
But when I ran my footsteps, there was no problem opening 1 million independent coroutines.

**Comment by guonaihong** [comment]
Post the recovery code you added

**Comment by daheige** [comment]
After two days of troubleshooting, and pprof found that when the project started, redisgo was initialized, using the connection pool, and redisgo's connection pool occupies a large amount of memory and tcp connections, resulting in memory leaks, gin framework processing, in this line Unable to write the response to the response stream, so the service crashed, this is the main reason, but there is a little bit of gin1.4.0 concurrent qps obviously no gorilla/mux latest version performance.

**Comment by enefuture** [comment]
Hi
    I have the same problem，cpu skyrocket to 90%，I want to kown How to solve this problem？

**Comment by daheige** [comment]
please look my desc. your problem maybe tcp pool nums is more

**Comment by guoyahao** [comment]
> 请看我的desc。你的问题可能是tcp pool nums更多

同样的问题 我想知道您那边是怎么解决的？

**Comment by daheige** [comment]
Control the number of connection pools for these services of redisgo mysql, especially the Redis connection pool. Adjust the maximum number of connections and the number of idle connections appropriately, and remove those connection pool configurations that are useless. When you are finished using the redis and mysql connection pool, remember to release the connection handle to the connection pool.

**Comment by daheige** [comment]
If the business uses ioutil to read the post request, the default is 512 bytes to read the request body, so after reading, remember to do the defer Close operation on the request connection handle, release the request connection, prevent the tcp connection from getting long time. Release, and prevent memory leaks, causing CPU to skyrocket.

**Comment by daheige** [comment]
A large number of requests in the gin render json.go 58 throwing panic (err) will take up a lot of cpu, in the stress test, when the number of requests reaches 10000, the machine's cpu skyrocket, this may be a bug. I think that panic should not be thrown here. If panic is thrown in the middleware and the stack information is recorded, although the interface response is ok, other interfaces will be affected.

Please see point 4 of the wrk test below to reproduce this panic problem.

https://github.com/daheige/go-api/blob/master/readme.md#wrk-%E5%B7%A5%E5%85%B7%E5%8E%8B%E5%8A%9B%E6%B5%8B%E8%AF%95

**Comment by daheige** [comment]
Everyone, this issue has been resolved, please look gin recovery.go Recovery func,thanks to the gin team's contribution to the http framework.

**Comment by ginman86** [comment]
@daheige How has this been resolved, is there a code change or PR that has addressed this issue or did you implement a workaround? I see no code changes within recovery.go and am wondering if updating will actually fix our problem. Thanks.

**Comment by daheige** [comment]
please look this https://github.com/daheige/go-api/blob/master/app/middleware/log.go recovery func,or look my go-api main.go and router.go

**Comment by daheige** [comment]
broken pipe of gin can’t resolved this bug,broken pipe has many

**Comment by Demitroi** [comment]
I have a similar issue, in the rush hours the http server doesn't response, but the app is still running.

I use the gin.Default() with no aditional middleware.

**Comment by daheige** [comment]
The gin router created by gin.Default is missing when capturing the broken pipe problem. Please see how I handled this broken pipe. I used gin.New() and then handled the broken pipe problem in the log recover middleware. Maybe it can solve your problem.

**Comment by daheige** [comment]
@Demitroi please look my code of go-api

**Comment by Demitroi** [comment]
@daheige i tried download go api using go get

```sh
go get -u -v github.com/daheige/go-api
go: downloading github.com/daheige/go-api v1.2.0
go: github.com/daheige/go-api upgrade => v1.2.0
go get: github.com/daheige/go-api@v1.2.0: parsing go.mod:
        module declares its path as: go-api
                but was required as: github.com/daheige/go-api
```

Please change module's name.

**Comment by Demitroi** [comment]
I tested in the vscode terminal and cmd. The vscode terminal is too slow and impact the router performance. By using the go-api recover the performance is not affected.

Check it out.

https://github.com/Demitroi/gin-issues-1929

**Comment by daheige** [comment]
@Demitroi thank you for your test report. I found this bug because of the large number of broken pipe online, gin.Default was not captured, resulting in a large number of recovers and the CPU skyrocketed, memory leaked, after comparing the recover provided by gin.Default The middleware has some omissions about the broken pipe situation, which is not comprehensive. For example, io timeout, `request headers: small read buffer`, `unexpected EOF` these broken pipe cases appear

**Comment by daheige** [comment]
@Demitroi The recover middleware I provided was processed. I added some of the broken pipe problems that I encountered in the online production environment. It has been running for more than half a year, and I have never encountered this CPU explosion problem.

**Comment by daheige** [comment]
> @daheige i tried download go api using go get
> 
> ```shell
> go get -u -v github.com/daheige/go-api
> go: downloading github.com/daheige/go-api v1.2.0
> go: github.com/daheige/go-api upgrade => v1.2.0
> go get: github.com/daheige/go-api@v1.2.0: parsing go.mod:
>         module declares its path as: go-api
>                 but was required as: github.com/daheige/go-api
> ```
> 
> Please change module's name.

This is a project, not a component or framework, so I don’t think it’s necessary to change the name here

**Comment by Demitroi** [comment]
@daheige i'll change the gin.Default middleware for a custom middleware with broken pipe fixes. I hope this will work. gin.Default must have the broken pipe fixes, maybe is necessary to do a pull request?

**Comment by daheige** [comment]
@Demitroi  Thank you, gin.Default does need to correct the broken pipe situation, the current gin version does not completely cover some scenarios.

**Comment by daheige** [comment]
@Demitroi  https://github.com/gin-gonic/gin/blob/master/recovery.go#L48,the judgment here, if the first if judgment is not satisfied, and then continue to judge, calling the ToUpper method is completely a waste, which is equivalent to doing two ToUpper operations. I propose to change to https://github.com/daheige/go-api/blob/master/app/middleware/log.go#L80 to do a capital conversion
