### ISSUE TITLE
How would I set a certain endpoint to proxy to a different server?

### ISSUE THREAD

**Issue by tleyden** [gin-gonic/gin#193]
For example, in my REST api, I want anything destined for the /proxy endpoint to be proxied to another server running on a different ip/port.  

Go has `httputil.NewSingleHostReverseProxy` built-in to provide this functionality, but I'm not seeing how I would tell gin to use this for an endpoint.  Any tips?

**Comment by tleyden** [comment]
It seems like if the `Engine.router` field were exposed, plugging in a httputil.NewSingleHostReverseProxy would be straightforward (as mentioned in https://github.com/gin-gonic/gin/issues/154, it's not exposed)

Or is there a better way?

**Comment by javierprovecho** [comment]
sorry for delay @tleyden 

You can try this:

```go
	r.GET("/proxy", func(c *gin.Context) {
		u, err := url.Parse("http://yourhost")
		if err == nil {
			proxy := httputil.NewSingleHostReverseProxy(u)
			proxy.ServeHTTP(c.Writer, c.Request)
		} else {
			c.Writer.Write([]byte(err.Error()))
		}
	})
```

You will need to import `"net/http/httputil"` and `"net/url"`


Source: http://stackoverflow.com/questions/21270945/how-to-read-the-response-from-a-newsinglehostreverseproxy

**Comment by tleyden** [comment]
Thanks!
