### ISSUE TITLE
Set the cookie attribute “SameSite = None”

### ISSUE THREAD

**Issue by vsubramoney** [gin-gonic/gin#1934]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: go1.12.5
- gin version (or commit ref):
- operating system: windows/amd64

## Description
Compilation fails with the error undefined: http.SameSiteNoneMode
when I set the value of SameSite to  http.SameSiteNoneMode 
```
newCookie := &http.Cookie{
				Name:     MatchCookieName,
				Domain:   GetRootDomain(r),
				MaxAge:   CookieMaxAge,
				Expires:  time.Now().Add(CookieMaxAge),
				Value:    matchCookieAfter.EncodeToBase64(),
				SameSite: http.SameSiteNoneMode,
				Secure:   true,
				Path:     "/",
}
```
Golang right now supports the following values for SameSite Cookie attribute
 http.SameSiteLaxMode, http.SameSiteStrictMode, http.SameSiteDefaultMode. A 4th value SameSiteNoneMode should be added to support Chrome release of version 76 in July 2019.

**Comment by thinkerou** [comment]
maybe you should see https://github.com/gin-gonic/gin/pull/1615 thanks!

**Comment by vsubramoney** [comment]
I checked #1615, there is no mention of None. I only see the changes for 'Lax' and 'Strict'. "None" is a constant that should be added to support the upcoming google chrome version 76.

**Comment by roychowdhuryrohit-dev** [comment]
> maybe you should see #1615 thanks!

Is it feature merged with gin framework ? I checked the doc and there's no feature for setting SameSite attribute for cookie in Gin.

**Comment by marcaurelian** [comment]
Any updates on this? I can confirm SameSite: http.SameSiteLaxMode works while SameSite:SameSiteNoneMode doesn't.

**Comment by thinkerou** [comment]
#1615 merged！
