### ISSUE TITLE
[Go Get] Undefined sync.Pool in gin.go:44

### ISSUE THREAD

**Issue by vegax87** [gin-gonic/gin#194]
I run "go get" command to import Gin-Gonic but there's an error in gin.go, line 44

go get github.com/gin-gonic/gin
../../go/src/github.com/gin-gonic/gin/gin.go:44: undefined: sync.Pool

**Comment by slimmy** [comment]
What is your `go version`?

**Comment by vegax87** [comment]
Solved, I updated my go version to 1.4
