### ISSUE TITLE
timeout middleware

### ISSUE THREAD

**Issue by vearne** [gin-gonic/gin#1941]
I want to develop a timeout middleware, but I' found only can do it by fix context.Status()

// Status sets the HTTP response code.
func (c *Context) Status(code int) {
   c.writermem.WriteHeader(code)    ->   c.Writer.WriteHeader(code)
}
                   
[reference]
https://github.com/golang/go/blob/003dbc4cda6a1418fc419461799320521d64f4e5/src/net/http/server.go#L3209

**Comment by appleboy** [comment]
Try timeout middleware: https://github.com/gin-contrib/timeout

**Comment by ciokan** [comment]
> Try timeout middleware: https://github.com/gin-contrib/timeout

That middleware does not work due to a bug that has almost a year by now. (panic: http: wrote more than the declared Content-Length)

**Comment by duaneking** [comment]
> Try timeout middleware: https://github.com/gin-contrib/timeout

That middleware is not functional, and has multiple breaking bugs.

**Comment by vearne** [comment]
try timeout middleware https://github.com/vearne/gin-timeout

**Comment by v0vanec** [comment]
That https://github.com/gin-contrib/timeout middleware is totally broken, we also tried and could not use it.
