### ISSUE TITLE
Gin Parameters of the receiving form cache issue

### ISSUE THREAD

**Issue by migopher** [gin-gonic/gin#1945]
There is a cache problem with the post request, resulting in the following post parameters becoming the same
`
GOROOT=D:\code\golang #gosetup
GOPATH=D:\code\gopath\go #gosetup
D:\code\golang\bin\go.exe build -o C:\Users\cits\AppData\Local\Temp\___go_build_demo3_go.exe D:/code/gopath/go/src/demo/demo3.go #gosetup
C:\Users\cits\AppData\Local\Temp\___go_build_demo3_go.exe #gosetup
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /                         --> main.main.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8080
[1]
[GIN] 2019/06/11 - 14:35:03 | 200 |            0s |       127.0.0.1 | POST     /
[1]
[GIN] 2019/06/11 - 14:35:06 | 200 |            0s |       127.0.0.1 | POST     /
[1]
[GIN] 2019/06/11 - 14:35:09 | 200 |            0s |       127.0.0.1 | POST     /
`
@thinkerou @appleboy @austinheap @javierprovecho

**Comment by migopher** [comment]
@

**Comment by thinkerou** [comment]
#1931
