### ISSUE TITLE
Am I doing something wrong with the template?

### ISSUE THREAD

**Issue by defia** [gin-gonic/gin#195]
in readme, it says:
####HTML rendering

Using LoadHTMLTemplates()

```go
func main() {
	r := gin.Default()
	r.LoadHTMLGlob("templates/*")
	r.GET("/index", func(c *gin.Context) {
		obj := gin.H{"title": "Main website"}
		c.HTML(200, "index.tmpl", obj)
	})

	// Listen and server on 0.0.0.0:8080
	r.Run(":8080")
}
```
```html
<h1>
	{{ .title }}
</h1>
```

From my understanding, I create a folder names templates in binary's folder, put index.tmpl in the templates folder. And then run binary in its own folder.  

But It says cannot find specific file.  

If I move index.tmpl to binary's folder, everything's ok.

What's wrong?

**Comment by defia** [comment]
https://github.com/gin-gonic/gin/issues/119
ok, i've seen this issue.

**Comment by mvader** [comment]
For now you can use this workaround:
```go
b, _ := ioutil.ReadFile("path")
file := string(b)

r.GET("/", func(c *gin.Context) {
		c.Writer.(http.ResponseWriter).Header().Set("Content-Type", "text/html")
		c.Writer.WriteHeader(200)
		c.Writer.Write([]byte(file))
}
```

That snipped does not use the template library but you get the idea.
