### ISSUE TITLE
binding:"required" failed

### ISSUE THREAD

**Issue by 0x00b** [gin-gonic/gin#1950]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
- gin version (or commit ref):
- operating system:

## Description
```
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"net/http"
)

type Body struct {
	Name string `binding:"required"`
	Age  int
}

func main() {
	engine := gin.Default()
	engine.POST("/test", func(c *gin.Context) {
		b := &Body{} //b is *Body, ShouldBindBodyWith get **Body, Maybe it’s a mistake
		if err := c.ShouldBindBodyWith(&b, binding.JSON); err != nil {
			c.JSON(http.StatusBadRequest, err)
		}
		c.JSON(http.StatusOK, b)
	})

	engine.Run(":80")
	return

}

```
$ curl -XPOST localhost/test -d '{}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    19  100     2    306     32 --:--:-- --:--:-- --:--:--   338{"Name":"","Age":0}

curl should get an error, but an object.

because of the defaultValidator just validate *Body.
```
func (v *defaultValidator) ValidateStruct(obj interface{}) error {
	value := reflect.ValueOf(obj)
	valueType := value.Kind()
	if valueType == reflect.Ptr {
		valueType = value.Elem().Kind()
	}
	if valueType == reflect.Struct {
		v.lazyinit()
		if err := v.validate.Struct(obj); err != nil {
			return err
		}
	}
	return nil
}
```

**Comment by guonaihong** [comment]
No no no, you took the pointer once more
``` go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"net/http"
)

type Body struct {
	Name string `binding:"required"`
	Age  int
}

func main() {
	engine := gin.Default()
	engine.POST("/test", func(c *gin.Context) {
		b := &Body{} 
		
		if err := c.ShouldBindBodyWith(b /*---> here here here look me*/, binding.JSON); err != nil {
			c.JSON(http.StatusBadRequest, err)
			return
		}

		c.JSON(http.StatusOK, b)
	})

	engine.Run(":8080")
	return

}

```

**Comment by 0x00b** [comment]
I just put it there to give a notice, don't take pointer once more.

**Comment by guonaihong** [comment]
Your question is very good.

**Comment by 0x00b** [comment]
Thank you very much, but I know the reason,   I mentioned this issue just give a hint, because I found some careless programmers wrote such code.

发自我的 iPhone
