### ISSUE TITLE
Which companies use gin-gonic/gin in production?

### ISSUE THREAD

**Issue by chughpiyush** [gin-gonic/gin#1954]
Hi everyone!

I'm curious to know which companies are using gin-gonic/gin in production already. Any particular pros/cons that you noticed on your way to production...

If you use it in any of your products, please let me know. I would like to include a list of such companies in README.md, it can be inspiring for others to see which companies are already using gin-gonic/gin and it can help them get comfortable knowing about success from the others.

CC'ing a few of the contributors: @manucorporat @thinkerou @javierprovecho @appleboy @easonlin404 @vkd @pinscript @sairoutine @msoedov @jbampton @mopemope @se77en @kmulvey @dmarkham @chainhelen

**Comment by thinkerou** [comment]
https://github.com/bilibili/kratos ?

**Comment by akashsharma95** [comment]
Razorpay

**Comment by phillipCouto** [comment]
Eckler Ltd.

**Comment by danielnegri** [comment]
Our team at Kaplan Test Prep. Happy to answer any questions.

- [Kaptest](https://www.kaptest.com/) - Better score. Better job. Better life.
- [Atom](https://learnwithatom.com/) - A learning experience platform by Kaplan.

**Comment by thinkerou** [comment]
closing.
