### ISSUE TITLE
support bind http header param

### ISSUE THREAD

**Issue by guonaihong** [gin-gonic/gin#1956]
When I refactored some services, I found that gin does not have a function that binds the http header. I think it would be very good if I had this function.
```go
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
)

type testHeader struct {
	Rate   int    `header:"Rate"`
	Domain string `header:"Domain"`
}

func main() {
	r := gin.Default()
	r.GET("/", func(c *gin.Context) {
		h := testHeader{}

		if err := c.ShouldBindHeader(&h); err != nil {
			c.JSON(200, err)
		}

		fmt.Printf("%#v\n", h)
		c.JSON(200, gin.H{"Rate": h.Rate, "Domain": h.Domain})
	})

	r.Run()
}

```

**Comment by guonaihong** [comment]
Now the master branch has the ShoudBindHeader function.

**Comment by xxiaocheng** [comment]
> .

How can I use it with the go module. It still can't be used when I use `import "github.com/gin-gonic/gin"`. Thank you.

**Comment by guonaihong** [comment]
The v1.5 version does not come out, the temporary method can specify the commit id。

require github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641

**Comment by xxiaocheng** [comment]
> The v1.5 version does not come out, the temporary method can specify the commit id。
> 
> ### Edit the go.mod file
> ```
> require github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641
> ```

I edit the go.mod and run `go mod tidy` ,but the function still can`t be used for me .

**Comment by xxiaocheng** [comment]
> The v1.5 version does not come out, the temporary method can specify the commit id。
> 
> ### Edit the go.mod file
> ```
> require github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641
> ```

Thank you very much. It work for me now.

**Comment by guonaihong** [comment]
I can do it here. You look at my complete process

* Create a working directory
```bash
mkdir use_gin && cd use_gin/
go mod init demo
```

* edit go.mod
```bash
module demo

go 1.13

require github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641

```

* edit demo.go
```go
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
)

type header struct {
	Page int `header:"page"`
	Size int `header:"size"`
}

func main() {
	g := gin.Default()
	g.GET("/", func(c *gin.Context) {
		h := header{}
		err := c.ShouldBindHeader(&h)
		if err != nil {
			fmt.Printf("fail:%s\n", err)
			return
		}

		c.JSON(200, h)
	})

	g.Run()
}

```
* run demo
```bash
env GOPROXY=https://goproxy.cn go run demo.go
```

* Success log
```bash
go: finding github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> main.main.func1 (3 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] Listening and serving HTTP on :8080

```

**Comment by xxiaocheng** [comment]
> I can do it here. You look at my complete process
> 
> #### Create a working directory
> ```shell
> mkdir use_gin && cd use_gin/
> go mod init demo
> ```
> 
> #### edit go.mod
> ```shell
> module demo
> 
> go 1.13
> 
> require github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641
> ```
> 
> #### edit demo.go
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"github.com/gin-gonic/gin"
> )
> 
> type header struct {
> 	Page int `header:"page"`
> 	Size int `header:"size"`
> }
> 
> func main() {
> 	g := gin.Default()
> 	g.GET("/", func(c *gin.Context) {
> 		h := header{}
> 		err := c.ShouldBindHeader(&h)
> 		if err != nil {
> 			fmt.Printf("fail:%s\n", err)
> 			return
> 		}
> 
> 		c.JSON(200, h)
> 	})
> 
> 	g.Run()
> }
> ```
> 
> #### run demo
> ```shell
> env GOPROXY=https://goproxy.cn go run demo.go
> ```
> 
> #### Success log
> ```shell
> go: finding github.com/gin-gonic/gin db9174ae0c2587fe1c755def0f88cb9aba9e9641
> [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
> 
> [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
>  - using env:	export GIN_MODE=release
>  - using code:	gin.SetMode(gin.ReleaseMode)
> 
> [GIN-debug] GET    /                         --> main.main.func1 (3 handlers)
> [GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
> [GIN-debug] Listening and serving HTTP on :8080
> ```

The vscode can't recognize this function just now. But it already work for me  I think maybe it`s vscode`s bug,

**Comment by guonaihong** [comment]
ok

**Comment by colsaurabh** [comment]
ShouldBindHeader function is not binding according to json parameters in struct(As with other bindings). Rather its getting bind to golang names defined in the struct.

**Comment by guonaihong** [comment]
I have time tomorrow to look at your question.&nbsp;



---Original---
