### ISSUE TITLE
Static "panic: a Handle is already registered for this path"

### ISSUE THREAD

**Issue by matejkramny** [gin-gonic/gin#196]
Getting similar output to:
```
$ gin -i
[gin] listening on port 3000
[GIN-debug] GET   /*filepath                --> github.com/gin-gonic/gin.func·005 (3 handlers)
[GIN-debug] HEAD  /*filepath                --> github.com/gin-gonic/gin.func·006 (3 handlers)
[GIN-debug] GET   /*filepath                --> github.com/gin-gonic/gin.func·005 (3 handlers)
panic: a Handle is already registered for this path
```

With code:

```
r := gin.Default()

r.Static("/", "./templates")
r.Static("/", "./public")
```

I want to mount both `./templates` and `./public` onto the root path.. I understand the implications of file conflicts, however this is possible with Martini (or express-js for that matter).

It seems that registering two file handlers for the same path is impossible (by design). What's the best way to go around this?

Thanks for making Gin! Its awesome :).

**Comment by matejkramny** [comment]
Similar error happens when using an alternative mount path for the _second_ `r.Static`.

Eg:

```
[GIN-debug] GET   /*filepath                --> github.com/gin-gonic/gin.func·005 (3 handlers)
[GIN-debug] HEAD  /*filepath                --> github.com/gin-gonic/gin.func·006 (3 handlers)
[GIN-debug] GET   /assets/*filepath         --> github.com/gin-gonic/gin.func·005 (3 handlers)
panic: conflict with wildcard route
```

code:

```
r := gin.Default()

r.Static("/stuffs", "./templates")
r.Static("/assets", "./public")
```

**Comment by devalphac** [comment]
I also encountered a similar situation!

/ public
---- / css
-------- / style.css
-------- / app.css
---- / js
------- / app.js

when I leave r.Static ("/ Assets", "./public")

I visit the URL localhost: 8080 / Assets / css
list:
* style.css
* app.css

why?

**Comment by javierprovecho** [comment]
@matejkramny well, those are restrictions of httprouter, and I don't see a way of doing this with handlers. the bad solution is to develop a custom handler to serve both folders.

@devalphac i don't understand you comment. if you map `./public` folder into `/assets` path, it is normal that if you request the path `/assets/css` it shows `style.css` and `app.css`.

**Comment by matejkramny** [comment]
Thanks for clarifying @javierprovecho

**Comment by javierprovecho** [comment]
@matejkramny should i close this?

**Comment by matejkramny** [comment]
if i find a solution i'll post it here.

Thanks
