### ISSUE TITLE
why not move the temp file rather than copy the same file when upload a large file?

### ISSUE THREAD

**Issue by caihangui** [gin-gonic/gin#1962]
- go version: go1.12.5 darwin/amd64
- gin version (or commit ref): v1.4.0-dev
- operating system: MacOS 10.14.5

## Description
when we upload a large file，gin framework will call `ioutil.TempFile` to write to disk and flush buffer.
```
// formdata.go  line 85 and line 86

// too big, write to disk and flush buffer
file, err := ioutil.TempFile("", "multipart-")
```

**However, when we call `SaveUploadedFile` to save file, gin calles the `io.Copy` to create a new file.
My question is that why not move the temp file rather than copy the same file.Moving may be better than copying in effect.**

```
func (c *Context) SaveUploadedFile(file *multipart.FileHeader, dst string) error {
	src, err := file.Open() // here, it opens the temp file
	if err != nil {
		return err
	}
	defer src.Close()

	out, err := os.Create(dst) // and here, it create a new file
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, src) // copy file from tempfile to targe file
	return err
}
```

**Comment by dmarkham** [comment]
@caihangui great question!

I agree moving is way faster... but it breaks if you cross a file-system boundary. Making move of limited use when your working on unknown systems.   

The best thing to do is create the temp file in the same directory as the final file and then use move. But this is not always an option.

**Comment by caihangui** [comment]
@dmarkham Thank you for your answer. 

You are right ! I think I had understanded what you mean.

**Comment by TonyPythoneer** [comment]
@caihangui Please close this issue if it resolves your question.
