### ISSUE TITLE
How do I limit the number of connections?

### ISSUE THREAD

**Issue by zc2638** [gin-gonic/gin#1964]

**Comment by TonyPythoneer** [comment]
The question is not clear. Please edit and describe the detail.

**Comment by guonaihong** [comment]
https://github.com/aviddiviner/gin-limit

Look at this to meet your requirements?

**Comment by zc2638** [comment]
> https://github.com/aviddiviner/gin-limit
> 
> Look at this to meet your requirements?

Yes,it's what I want.
So, I must use middleware to realize it?
Thank You!

**Comment by guonaihong** [comment]
It doesn't have to be this way, you can even copy the code into your project, which is a major way of gin multiplexing code.
