### ISSUE TITLE
Errors in startup and operation of the latest version

### ISSUE THREAD

**Issue by uzdz** [gin-gonic/gin#1965]
Go version：1.12.5
Govendor version：v1.0.9

When I started, I reported the following error：
# go_web/vendor/github.com/gin-gonic/gin
vendor/github.com/gin-gonic/gin/context.go:35:26: undefined: binding.MIMEYAML
vendor/github.com/gin-gonic/gin/context.go:583:29: undefined: binding.YAML
vendor/github.com/gin-gonic/gin/context.go:588:29: undefined: binding.Header
vendor/github.com/gin-gonic/gin/context.go:642:31: undefined: binding.YAML
vendor/github.com/gin-gonic/gin/context.go:647:31: undefined: binding.Header
vendor/github.com/gin-gonic/gin/context.go:656:9: undefined: binding.Uri
vendor/github.com/gin-gonic/gin/context.go:873:17: undefined: render.PureJSON
vendor/github.com/gin-gonic/gin/context.go:889:17: undefined: render.ProtoBuf

When I switched to version @v1.3.0, it started normally.

Is this the latest version of the bug?

**Comment by thinkerou** [comment]
please use `v1.4.0`.

**Comment by uzdz** [comment]
![image](https://user-images.githubusercontent.com/28328355/60381327-a325c480-9a85-11e9-97e6-272117abecd4.png)

![image](https://user-images.githubusercontent.com/28328355/60381325-9b662000-9a85-11e9-8734-029dfde643fc.png)

![image](https://user-images.githubusercontent.com/28328355/60381330-aa4cd280-9a85-11e9-99bf-099af31d6734.png)

The use of version v1.4.0 still reported errors.

**Comment by thinkerou** [comment]
because your gin version still is `v1.3.0` at local vendor directory. maybe you have not use govendor.
If you remove `vendor/github.com/gin-gonic/gin`, it should success.
thanks!

**Comment by uzdz** [comment]
Successful, should be version conflict, manual removal `vendor/github.com/gin-gonic/gin`, download version 1.4 can be used normally.
