### ISSUE TITLE
Can not direct output html piece to browser . 

### ISSUE THREAD

**Issue by cloudtrends** [gin-gonic/gin#197]
Can not direct output html piece to browser. 

```go
router.GET("/query", func(c *gin.Context) {
       c.String(200, "html format  code ");
      
    })
```

Should allow user write custom header infos , such as `"text/html"`. 

```go
c.Request.Header.Set("Content-Type", "text/html");
```
is overrided by `c.String` function.

**Comment by matejkramny** [comment]
The documentation says that using `c.String` sets the Content-Type to `test/plain` so you can't have html code there.

There is a function `c.Html` to render a html file, is this what you're looking for?

**Comment by cloudtrends** [comment]
yes , c.Html is can do what I want .

But it's too heavy .  I just want to write some simple ( very simple ) html code output to browser . 

Can we add c.HtmlString  to gin ?

**Comment by matejkramny** [comment]
I see what you mean.

Maybe serve your html from disk? I think gin caches the files so it doesn’t read the file every time..  

Matej Kramny

**Comment by egeozcan** [comment]
I have the same problem, I need to render a very simple piece of HTML and want to keep enjoying single-file deployments^^ It should be easy to support this, I guess?

**Comment by manucorporat** [comment]
@egeozcan @matejkramny @cloudtrends
I am going to remove c.HTMLString() in Gin v1.

- Very dangerous. I do not want developers it is safe to use HTMLString().
- HTML tempting is working great

Solution:
1. Use HTTP templating
2. Use String() + change Content-Type manually. String() will not override your Content-Type!!

```go
c.Writer.Header().Add("Content-Type", "text/html")
c.String(200, "<html>%s</html>", unsafeString)
```
or
```go
c.Header("Content-Type", "text/html")
c.String(200, "<html>%s</html>", unsafeString)
```
