### ISSUE TITLE
Gin Project Scaffolding CLI is highly neeeded

### ISSUE THREAD

**Issue by cyantarek** [gin-gonic/gin#1972]
When starting a fresh project each time, we need to create folders, configure many things. But it would be better to scaffold a boilerplate from a common standard boilerplate, like "vue webpack" or "create-react-app" cli tools.

Please consider this. We love Gin

**Comment by guonaihong** [comment]
At the moment, gin is still very lightweight. Can you send out your usual template code? Whether to add this function under evaluation
