### ISSUE TITLE
 write: broken pipe

### ISSUE THREAD

**Issue by iwalkerr** [gin-gonic/gin#1975]
- With issues:
  -  http: panic serving [::1]:59934: write tcp [::1]:8888->[::1]:59934: write: broken pipe

- go version: 1.12.6
- gin version (or commit ref): 1.4
- operating system: mac

## Description
 http: panic serving [::1]:59934: write tcp [::1]:8888->[::1]:59934: write: broken pipe

## Screenshots
![1111](https://user-images.githubusercontent.com/43042929/60646520-22dcd600-9e6e-11e9-8c8b-83295bd2b9d7.jpg)

**Comment by guonaihong** [comment]
Write: broken pipe error Usually the client terminates abnormally

**Comment by ankur-lt** [comment]
@guonaihong , what is the solution from gin to resolve this?
