### ISSUE TITLE
which version tag supports go 1.9

### ISSUE THREAD

**Issue by fwhezfwhez** [gin-gonic/gin#1983]
strings.Builder undefine, go 1.9 lib doesn't contain it. I notice this change for gin is recently merged from byte->strings.Builder in `error.go`,`debug.go`.

For some reason, project can't upgrade from go 1.9 to go1.12, is there a tag of gin supporting go 1.9 or not?

3q~

**Comment by thinkerou** [comment]
please use `gin v1.4.0` release version. 
the feature only exist the master branch now.
