### ISSUE TITLE
what is the code block({}) use?

### ISSUE THREAD

**Issue by ailncode** [gin-gonic/gin#1987]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:go1.12.4
- gin version (or commit ref):v1.4.0
- operating system:windows

## Description
First thanks for the contributors of gin. 
I don't know what is the code block({}) use?
Where is it necessary?

**Comment by thinkerou** [comment]
please see https://github.com/gin-gonic/gin#custom-delimiters

**Comment by ailncode** [comment]
func main() {
	router := gin.Default()

	// Simple group: v1
	v1 := router.Group("/v1")
	{
		v1.POST("/login", loginEndpoint)
		v1.POST("/submit", submitEndpoint)
		v1.POST("/read", readEndpoint)
	}

	// Simple group: v2
	v2 := router.Group("/v2")
	{
		v2.POST("/login", loginEndpoint)
		v2.POST("/submit", submitEndpoint)
		v2.POST("/read", readEndpoint)
	}

	router.Run(":8080")
}
Sorry,it's not my answer.
In this case:
What is the '{}' after group use?
