### ISSUE TITLE
Is there a way support dynamically to bind http path to handle function ?

### ISSUE THREAD

**Issue by cloudtrends** [gin-gonic/gin#199]
I had use gin in several of my golang apps .  

In order to make my app more flexible , I want dynamicall bind http path to handle function , such as

( demo code )

there is a array of http path :   urls_path = [ "/someGet" , "/somePost"  "/somePut" ]

foreach one in urls_path:
     if one == "/someGET" :
               bind(one , getting)
     else if one == "/somePost":
               bind(one, posting)
      else 
                bind(one, putting)

the final result will the same as  writting them statically in golang code: 
    r.GET("/someGet", getting)
    r.POST("/somePost", posting)
    r.PUT("/somePut", putting)

Can I ?

**Comment by matejkramny** [comment]
You can probably do that using regex, or use placeholders `/:some`?

Regex isn't supported in this library i think but placeholders are.

**Comment by cloudtrends** [comment]
I got your idea !

thanks a lot .


I close the issue .
