### ISSUE TITLE
restful uri conflicts with existing wildcard

### ISSUE THREAD

**Issue by layxyer** [gin-gonic/gin#1990]
Here's sample code:
```
func RegisterDemoRoute(r *Engine) {
	v1 := r.Group("api/v1/sys")
	{
		v1.GET("users/:id", service.GetSysUser)
		// conflicts with existing wildcard for "v1.GET("users/:id", service.GetSysUser)"
		v1.GET("users/:id/roles", service.GetSysUserRolePageList)
	}
}
```
"users/:id" and "users/roles" are conflicts,but Java web can do this,What should I do under gin?

**Comment by layxyer** [comment]
I verified that springmvc can use "/users/{id}" and "/users/roles" and "/users/1122" to give priority to uri matching. The parameters in matching uri will also check the type. Can gin be done?

**Comment by thinkerou** [comment]
please see https://github.com/gin-gonic/gin/issues/388
