### ISSUE TITLE
How can render a templete with a templete file and some html piece into it

### ISSUE THREAD

**Issue by solomn1991** [gin-gonic/gin#1994]
I crawl some html code as souce data.and I want to insert these pieces into html  after gin render the code .How can I implement it,anyone help me ？

page.tmpl
```
<html>
  <body>
  {{.body}}
  </body>
<html>
```

router code
```
s = `<body>I 'm body<body>`
r.GET("/page", func(c *gin.Context) {
  c.HTML(200,"page.tmpl", 
			"body":s,
  })
})
```

**Comment by thinkerou** [comment]
please read `readme` https://github.com/gin-gonic/gin#html-rendering thanks!

**Comment by solomn1991** [comment]
no related examle in readme  https://github.com/gin-gonic/gin#html-rendering

**Comment by solomn1991** [comment]
Can you give me a full example.I just a new gopher.

**Comment by solomn1991** [comment]
No answer about related code.can U give me a full code example




------------------ 原始邮件 ------------------
发件人: "thinkerou"<notifications@github.com>; 
发送时间: 2019年7月17日(星期三) 晚上8:22
收件人: "gin-gonic/gin"<gin@noreply.github.com>; 
抄送: "Cer"<765170680@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [gin-gonic/gin] How can render a templete with a templete fileand some html piece into it (#1994)




please read readme https://github.com/gin-gonic/gin#html-rendering thanks!

**Comment by yy1987316** [comment]
`s = `<body>I 'm body<body>`
r.GET("/page", func(c *gin.Context) {
  c.HTML(200, "page.tmpl", "body": template.HTML(s))
})`
