### ISSUE TITLE
LoggerWithFormatter and gin.Context

### ISSUE THREAD

**Issue by FrankIT60** [gin-gonic/gin#1997]
Ciao,

I use `*gin.Context.Set()` for share variable between middleware.
how can I use a variable injected by a previous mw in the `LoggerWithFormatter()` mw ?

Tanks in advance
Franco

**Comment by kotyara85** [comment]
@FrankIT60  did you find the answer?

**Comment by FrankIT60** [comment]
No

**Comment by FrankIT60** [comment]
I solved with param.Keys["logkey"] in gin.LoggerWithFormatter.
