### ISSUE TITLE
Support for 405 Method Not Allowed

### ISSUE THREAD

**Issue by martensson** [gin-gonic/gin#20]
Would be great to easy add support for status 405, specially when creating a REST API.

And do you have any example adding a more verbose access logger? Logging response-code, user-agent, client-ip, etc?

Keep up the good work! :+1:

**Comment by javierprovecho** [comment]
Sorry for delay. Support for HTTP 405 has been added https://github.com/julienschmidt/httprouter/pull/51 . Closing this issue now.
