### ISSUE TITLE
context.ShouldBindHeader undefined

### ISSUE THREAD

**Issue by moeen** [gin-gonic/gin#2001]
I'm trying to use a go package manager for my project. I've tried both dep and go module but the 
ShouldBindHeader method is undefined.
I get the following error:
`context.ShouldBindHeader undefined (type *gin.Context has no field or method ShouldBindHeader)
`

- go version: go1.12.7 linux/amd64
- gin version (or commit ref): v1.4.0
- operating system: Ubuntu 19.04

**Comment by guonaihong** [comment]
ShouldBindHeader is a feature of the future gin 1.5 release. Gin1.4 does not include this function, you can get this function on the master branch.
