### ISSUE TITLE
Can not bind using POST (time)

### ISSUE THREAD

**Issue by abaybek** [gin-gonic/gin#2002]
- go version: 1.12.7
- gin version: 1.4.0 :
- operating system: linux/amd64

## Description
```golang
type Person struct {
	Birthday time.Time `xml:"birthday" json:"birthday" form:"birthday" time_format:"2006-01-02"`
}

func startPage(c *gin.Context) {
	var person Person
	if err := c.ShouldBind(&person); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, err.Error())
		return
	}
	c.JSON(http.StatusOK, person)
}

func main() {
	r := gin.Default()
	r.GET("/", startPage)
	r.POST("/", startPage)
	r.Run()
}
```
The above code works only when I send GET request. When I send POST it can not validate it.

## Screenshots
![image](https://user-images.githubusercontent.com/23114068/61899401-2f1ff480-af3d-11e9-9f97-8122d9d381f4.png)
![image](https://user-images.githubusercontent.com/23114068/61899423-3a732000-af3d-11e9-9dba-d91a8ea5f1bd.png)

How can I validate time field when I want to use POST request?

**Comment by guonaihong** [comment]
I can do it here.

client:
```
curl  -d 'birthday=2019-03-04' 192.168.6.214:8080
```
output:
```
{"Birthday":"2019-03-04T00:00:00+08:00"}
```

**Comment by abaybek** [comment]
Yeah. I want to send JSON object. x-www-form-urlencoded request works fine.

Can you test with this request.
`curl  --data '{"birthday": "2019-03-04"}' -H "Content-Type: application/json" 0.0.0.0:8080`

**Comment by guonaihong** [comment]
time_format is designed for custom tags such as form, query, header, etc., does not contain json, yaml library
```
package main

import (
    "encoding/json"
    "fmt"
    "time"
)

type Person struct {
    Birthday time.Time `xml:"birthday" json:"birthday" form:"birthday" time_format:"2006-01-02"`
}

func main() {
    s := []byte(`{"birthday": "2019-03-04"}`)
    p := Person{}
    fmt.Println(json.Unmarshal(s, &p))

}
```
output:
```
parsing time ""2019-03-04"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "T"
```

The mistake you posted has something to do with the behavior of the golang JSON standard library, which can only be done at present.

**Comment by abaybek** [comment]
Thanks, found solution at [stackoverflow](https://stackoverflow.com/questions/25087960/json-unmarshal-time-that-isnt-in-rfc-3339-format).
