### ISSUE TITLE
Occassionally  Context.JSON Cost 15 Minute

### ISSUE THREAD

**Issue by figoxu** [gin-gonic/gin#2003]
- With issues:
  - SomeTimes,Context.JSON Cost More Than Ten Minutes

- go version: go1.12.1 darwin/amd64
- gin version : github.com/gin-gonic/gin v1.4.0
- operating system:  Linux  4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Description
In Our Production Environment, Context.JSON Cost 15Minute When Gin Render A Json Which Has 675KB . We Did Not Change Any Code Of The Following Func . Just Upgrade Gin Version From "github.com/gin-gonic/gin v1.3.0"  To "github.com/gin-gonic/gin v1.4.0" . Did Any Changes In Context.JSON ?

## Sample Code
``` golang
import  (
	"github.com/gin-gonic/gin"
	"github.com/quexer/utee"
)

func (p *Hdl) xxxxxHandler(c *gin.Context) {
       pl := utee.NewPerfLog(100, logEntry)
       defer pl.Done()
       // do some query  ...
       pl.Tick("c")
       c.JSON(200, gin.H{
                 "data": page,
                 "now":  utee.Tick(),
       })
      pl.Tick("d")
}
```

**Comment by thinkerou** [comment]
please post mini code which can reproduce the issue. thanks!

**Comment by figoxu** [comment]
`	
import (
	"github.com/gin-gonic/gin"
	"github.com/quexer/utee"
)

func (p *Hdl) xxxxxHandler(c *gin.Context) {
       // do some query  ...
        pl.Tick("c")
	c.JSON(200, gin.H{
		"data": page,
		"now":  utee.Tick(),
	})
	pl.Tick("d")
}`

**Comment by figoxu** [comment]
[xxx.zip](https://github.com/gin-gonic/gin/files/3434392/xxx.zip)
I Am Try To Write An Example To Occur The Err 。 Still Now Is Not Occur In This Example 。

**Comment by thinkerou** [comment]
```
func main() {
	g := gin.Default()

	v := AutoGenerated{}
	err := json.Unmarshal([]byte(ttt), &v)
	utee.Chk(err)
	// gin.SetMode(gin.ReleaseMode)
	fmt.Println("Try To Occur Err")
	g.GET("/get", func(c *gin.Context) {
		//for {
		startTick := utee.Tick()
		//c, _ := gin.CreateTestContext(httptest.NewRecorder())
		c.JSON(http.StatusOK, &v)
		endTick := utee.Tick()
		if endTick-startTick > 60*1000 {
			utee.Chk(errors.New("cost many times"))
		}
		// }
	})

	g.Run()
}
```
it's ok!
