### ISSUE TITLE
conflicts with existing wildcard

### ISSUE THREAD

**Issue by divinerapier** [gin-gonic/gin#2005]
- go version:
$ go version
go version go1.12.7 darwin/amd64
- gin version (or commit ref):
v1.4.0
- operating system:

## Description
`panic: ':name' in new path '/reservations/:name/inspect' conflicts with existing wildcard ':id' in existing prefix '/reservations/:id'`

## Screenshots
routers like below will panic
![image](https://user-images.githubusercontent.com/21213088/62099829-e6ac6200-b2c1-11e9-854b-dc3ff189b01c.png)

but this is ok
![image](https://user-images.githubusercontent.com/21213088/62099915-460a7200-b2c2-11e9-8efe-d793cc29c872.png)

I wonder the reason.

Thanks.

**Comment by thinkerou** [comment]
please search and read old issue, this is not a bug. thanks!
