### ISSUE TITLE
parse map params failed!!!

### ISSUE THREAD

**Issue by lanshipeng** [gin-gonic/gin#2021]
- With issues:
 json: cannot unmarshal string into Go struct field Channel.extend_data of type map[string]string

## 
![image](https://user-images.githubusercontent.com/21244175/63206479-adf4f100-c0e7-11e9-9be1-785e350c0795.png)

**Comment by lanshipeng** [comment]
@EdwardBetts @EdwardBetts need your help ! thank you

**Comment by lanshipeng** [comment]
@srid @EdwardBetts need your help ! thank you

**Comment by vkd** [comment]
When content-type is JSON then default go `json.Decode(...)` is used that is not support unmarshaling string into map.
Only `Form` binding supports converting string into map.
