### ISSUE TITLE
fullPath not matched with request url

### ISSUE THREAD

**Issue by yangyucardinfo** [gin-gonic/gin#2022]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
1.12.5
- gin version (or commit ref):
latest master
- operating system:

## Description
when i run the program in my local environment, the fullpath is success.
but once run in the linux server, the fullpath doest match the request url

**Comment by yangyucardinfo** [comment]
if i register the shorter path after the longer path ,i get wrong fullpath. for example:
#```
router.PUT("/user/:userName/address", relay());
router.PUT("/user/:userName", relay());
```
when i call /user/:userName, i got fullPath as /user/:userName/address

**Comment by thinkerou** [comment]
@yangyucardinfo you can write this router, it will error, like this:
```
panic: ':userName' in new path '/user/:userName' conflicts with existing wildcard ':userName' in existing prefix '/user/:userName'
```
