### ISSUE TITLE
How to carry data when redirecting

### ISSUE THREAD

**Issue by jwwb681232** [gin-gonic/gin#2024]
### Description
I have a post data form，When the form input is out of order, the program redirects to the previous page and prompts for some error messages
#### The solution I tried 1
```golang
if err != nil {
    c.Redirect(http.StatusMovedPermanently,"/register")
    c.Abort()
    return
}
```
I don't know how to carry data to a html page this way. I've tried to use session, but it makes the problem more complicated.

#### The solution I tried 2
```golang
if err != nil {
    flash := map[string]interface{}{
        "code":http.StatusConflict,
        "message":[]string{"The email address already exists"},
    }
    c.HTML(http.StatusFound,"auth/register.html",flash)
    return
}
```
One of the deadliest problems with this approach is that the template is loaded, but pressing F5 to refresh the page prompts you to submit the form repeatedly

### Problem
After validation fails, how can you present the form validation information on the template

**Comment by YanxinTang** [comment]
I'm using `session.AddFlash` to carry data when redirecting. I hope there is a more elegant way to achieve
