### ISSUE TITLE
Segment download error 

### ISSUE THREAD

**Issue by gonboy** [gin-gonic/gin#2036]
GIN
```go
router.Static("/release", "./release")
router.Run(":80")
```
GO Server 
```go
http.Handle("/", http.FileServer(http.Dir("./")))
http.ListenAndServe(":80", nil)
```
Through this method, http header
```
Range: bytes=1-1024
```
**Gin**: Segment download error , couldn't download all. only Download only part
**GO Server**: Segment download always OK

**Comment by thinkerou** [comment]
please post example which can run for reproducing issue, and then re-open, thanks!
