### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by denouche** [gin-gonic/gin#2039]
Hello
It is possible to have a new release?
With go1.13 and gin 1.4.0 I have some troubles installing dependencies:
```
github.com/xxxxxxx/handlers imports
	github.com/gin-gonic/gin imports
	github.com/gin-gonic/gin/binding imports
	github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/home/denouche/workspace/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/home/denouche/workspace/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)
```

This is working using master, that's why I ask for a release.
Thanks in advance!

**Comment by qoo2p5** [comment]
Hi. I have the same error with go1.12. A new release is a must-have, otherwise people just can't use this library...

**Comment by bcmills** [comment]
Note that you don't have to wait for a release to start using a fix from head — `go get` accepts commit hashes, and will automatically synthesize an appropriate semantic [pseudo-version](https://golang.org/cmd/go/#hdr-Pseudo_versions) corresponding to the requested commit.

**Comment by thinkerou** [comment]
#2109
