### ISSUE TITLE
v0.5 release candidate

### ISSUE THREAD

**Issue by javierprovecho** [gin-gonic/gin#204]
Hello everyone,

Just finished my exams and pushed for release candidate a new version.

# Changelog
Here is the changelog:

###Gin 0.5 (Jan 4, 2015)

- [NEW] Content Negotiation
- [FIX] Solved security bug that allow a client to spoof ip
- [FIX] Fix unexported/ignored fields in binding

# Contributors
Here is all the people that helped on it. Please forgive if I forgot someone.

**@andredublin (Andre Dublin)**
- Fix typo in comment

**@bredov (Ludwig Valda Vasquez)**
- Fix html templating in debug mode

**@dickeyxxx (Jeff Dickey)**
- Add example about serving static files

**@dutchcoders (DutchCoders)**
- ★ Fix security bug that allows client to spoof ip
- Fix typo. r.HTMLTemplates -> SetHTMLTemplate

**@jamie-stackhouse (Jamie Stackhouse)**
- Add more shortcuts for router methods

**@JasonSoft (Jason Lee)**
- Fix typo in comment

**@kelcecil (Kel Cecil)**
- Fix readme typo

**@loongmxbt (Saint Asky)**
- Fix typo in example

**@mirzac (Mirza Ceric)**
- Fix debug printing

**@mopemope (Yutaka Matsubara)**
- Add Pluggable View Renderer Example

**@se77en (Damon Zhao)**
- Improve color logging

**@slimmy (Jimmy Pettersson)**
- Added messages for required bindings

**@smira (Andrey Smirnov)**
- Add support for ignored/unexported fields in binding

**@yosssi (Keiji Yoshida)**
- Fix link in README

# Future plans

*Short-term:* I will update the contrib repository with this version on friday, any pull request is welcome.

*Medium-term:* Next version is expected when I resolve nearly all issues. Hope to do it within a month.

*Long-term:* Before the month of June I hope to push the v1.0 with a stable API.

# Help wanted

Now that I finished my exams, I have plenty time to focus on this project and I hope keep up to what you expect from Gin.

Thank you all.

**Comment by se77en** [comment]
Congrats!

**Comment by jamie-stackhouse** [comment]
Definitely. Hopefully you studied enough for your exams!

**Comment by tnolet** [comment]
@javierprovecho Great news! So, does this fix the issue where JSON fields that are marked as "required" are still being passed as empty instead of failing the request?

**Comment by javierprovecho** [comment]
@tnolet Not sure what issue do you mean, but v0.5 pushes all changes to master from all past months. I didn't have any issue with JSON required, however before v0.6 almost all open issues will be resolved. If you still have problems with that, please tag here the issue or open a new one. Thank you.

**Comment by javierprovecho** [comment]
@tnolet @jamie-stackhouse @se77en pushing v0.5 final right now. Closing this issue. Thank you all.
