### ISSUE TITLE
Terminal Output Values

### ISSUE THREAD

**Issue by muhammet-mucahit** [gin-gonic/gin#2042]
I searched for old issues but I can't find anything. If it exists, just link it and close the issue.

[GIN] 2019/09/06 - 08:33:33 | 200 |  1.187118477s |       127.0.0.1 | POST     /v1/get_data

I want to get these informations (date, time, execution_time etc.) How can I do that?

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin#custom-log-format
