### ISSUE TITLE
Broken Pipe error

### ISSUE THREAD

**Issue by lcplj123** [gin-gonic/gin#2048]
Well,maybe it's an old question!
**I got the following error mesage when i use gin。**
[31m2019/09/08 08:14:30 write tcp 49.250.250.20:9898->223.104.191.124:65360: write: broken pipe
GET /goods/purchase?t=1567901650&channel=Grid&director=01090229&areacode=JS&cid=251906911&sign=5e0a840b0811a5d4e5678c23bda21754&_=1567901649421
Host: 62218.122.97:9898  (real network addr)
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,en-US;q=0.8
Connection: keep-alive
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Redmi Note 4X Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36 Html5Plus/1.0
X-Requested-With: com.tydic.ydmh

**but when i search access log， i found the http status is 200 OK。
[GIN] 2019/09/08 - 08:14:30 | 200 |   5.11835173s | 223.104.191.124 | GET      /goods/purchase?t=1567901650&channel=Grid&director=01090229&areacode=JS&cid=251906911&sign=5e0a840b0811a5d4e5678c23bda21754&_=1567901649421

it confused me， i got a panic，but the connection is 200. who knows why？**

Gin version is v1.4.0 ，and the golang version is go1.13

**Comment by thinkerou** [comment]
@lcplj123 please search and read https://github.com/gin-gonic/gin/issues?q=is%3Aissue+broken+is%3Aclosed
