### ISSUE TITLE
panic: wildcard route conflicts with existing children

### ISSUE THREAD

**Issue by carr123** [gin-gonic/gin#205]
```go
router.GET("/api/test/basic_data_set_link", control.GetBasicDataSetLink())
router.GET("/api/:user_id/requestedgroups", control.GetRequestedGroups()) 
```
the above two lines conflict, and cause panic.
but it seems no problem.  so, what's wrong with my code ??
thanks.

**Comment by javierprovecho** [comment]
Hello @carr123 , this is not a problem or issue from Gin, is from httprouter instead because how its made.

I suggest the following:

```go
// ...
router.GET("/api/:user_id/requestedgroups", GetRequestedGroups) 
// ...
    if strings.HasPrefix(c.Request.RequestURI, "/api/test/basic_data_set_link") {
        return control.GetBasicDataSetLink(c)
    } else {
        // your original "control.GetRequestedGroups" hanlder code ...
    }
// ...
```

**Comment by wrunk** [comment]
Thanks @javierprovecho this is helpful (and thanks for this project it is great). I am wondering if httprouter is too simple for mainstream use, and if you guys plan to support other routers like https://github.com/dimfeld/httptreemux ? We have the same problem as carr123 and would prefer to avoid too many wrappers. Thanks.

**Comment by olebedev** [comment]
@wrunk +1

**Comment by javierprovecho** [comment]
@wrunk no plans at the moment, everything of gin is around httprouter, and so speed and performance. Thank you for discovering me httptreeremux, I liked it!, I should compare speed against httprouter, and if it doesn't go so much slower, I think I will give it a try.

Closing this issue.

**Comment by samehkhaliel** [comment]
Is there any plans to support httptreeremux soon ?

**Comment by beef9999** [comment]
Hey guys, this is a very critical problem. You should have noticed how many developers are asking solutions for this situation in Google.

I understand it's a HttpRouter limitation, but shall we sacrifice some performance and make gin more user friendly ?

**Comment by beef9999** [comment]
I deleted those cursing comments, and hereby give out my solution.

After all, it's your own project. You didn't force people to use it.

```
    router.GET("/v1/images/:path1", GetHandler)           //      /v1/images/detail
    router.GET("/v1/images/:path1/:path2", GetHandler)    //      /v1/images/<id>/history

func GetHandler(c *gin.Context) {
    path1 := c.Param("path1")
    path2 := c.Param("path2")

    if path1 == "detail" && path2 == "" {
        Detail(c)
    } else if path1 != "" && path2 == "history" {
        imageId := path1
        History(c, imageId)
    } else {
        HandleHttpError(c, NewHttpError(404, "Page not found"))
    }
}
```

**Comment by kofj** [comment]
I need wildcard route at root, like `/:any` at my url shortener project. But gin not support it, so I use `router.NoRoute`.

**Comment by gordenavia** [comment]
Fix this fucking thing already!

**Comment by PercyPham** [comment]
This should not be closed, the solution is not ideal. In my case, I have to use middleware in between. For example:

```
router.GET("/active", findActive)

router.Use(someMiddleware())

router.GET(":id", findByID)
```

It would be very cumbersome to deal with this using solutions above.

**Comment by bh7cw** [comment]
> This should not be closed, those solutions are not ideal. In my case, I have to use middleware in between, for example:
> 
> ```
> router.GET("/active", findActive)
> 
> router.Use(someMiddleware())
> 
> router.GET(":id", findByID)
> ```
> 
> It would be very cumbersome to deal with this using solutions above.
> 
> #### Edited:
> I made a workaround like this:
> 
> ```
> router.Get("/:id", h.findActive, someMiddleware(), h.findByID)
> ```
> 
> And in `findActive()`:
> 
> ```
> func (h handler) findActive(c *gin.Context) {
>   id := c.Param("id")
>   if id == "active" {
>     active := h.service.GetActive(c.Request.Context())
>     response.Success(c, active)
>     c.Abort()
>     return
>   }
>   c.Next()
> }
> ```
> 
> However, I still find it ugly and not straight forward, hope Gin will implement someway else in future.

This is great. I meet the similar problem:
- /v1/user/self: basic auth
- /v1/user/:id: public
The conflict panics.
This solution works for my issue.
