### ISSUE TITLE
Build / go.mod error for github.com/ugorji/go/codec

### ISSUE THREAD

**Issue by bjm88** [gin-gonic/gin#2050]
Adding Gin to my go.mod on a new project, go 1.12.5, seeing this error....

cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/Users/ben/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2 (/Users/ben/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181209151446-772ced7fd4c2)

**Comment by bjm88** [comment]
seems to be solved with something like this

replace github.com/ugorji/go v1.1.4 => github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43

**Comment by thinkerou** [comment]
@bjm88 yes
