### ISSUE TITLE
Logger support for file:linenumber (log.Lshortfile style) in development mode

### ISSUE THREAD

**Issue by itsjamie** [gin-gonic/gin#206]
It would be nice to integrate into development mode adding the file and linenumber that added an error to  to populate a caller field.

Internal to the log package this is what is used to determine the caller, can't use this with the logging middleware for Gin because it would always report the line inside the Gin logger that does the printf.

```go
if l.flag&(Lshortfile|Llongfile) != 0 {
   // release lock while getting caller info - it's expensive.
   l.mu.Unlock()
   var ok bool
   _, file, line, ok = runtime.Caller(calldepth)
   if !ok {
   	file = "???"
   	line = 0
   }
   l.mu.Lock()
}
```

I think it would have to be a change to when you register an error, it would need to do runtime.Caller then, and populate a field in the Error that would be added to the logline if in dev mode.

Thoughts?

**Comment by jamie-stackhouse** [comment]
Tagging #96.

**Comment by javierprovecho** [comment]
I like the idea. Better logs are always better if they are more precise. And because of being in development mode, it is not essential to care about performance, not in this case. I'll be looking into it for v0.6.

**Comment by javierprovecho** [comment]
@itsjamie i wasn't able to develop this for v0.6 but i'll keep it in mind.

**Comment by phemmer** [comment]
I also would like something similar to this. But more than just the line number. It would be nice if the `gin.Error` type contained the full stack trace. Let the logger deal with logging only the top-most frame.

I would also argue that this is more important to have in production mode than development. When an error occurs in production, you often don't know how to reproduce it. Thus a stack trace can be vital.

> And because of being in development mode, it is not essential to care about performance, not in this case

I don't see performance as an issue, even in production. If you're throwing thousands of errors per second, then I think you have bigger issues than the logging overhead :-)

**Comment by itsjamie** [comment]
The reason I would at least not want this to be always-on would be that by all appearances it is actually a fairly expensive operation to get the information. The standard lib actually releases the mutex on the logger to prevent nasty things from happening while it is being called. 

Suddenly you have a section of code for something related to telemetry able to block a requests processing so you can log properly. I can't see where this is ever something you would want to encourage. But we might be using errors differently in Gin.

One example is that we log a missing Authorization header to our API as an error as we want to be able to track the Requestor IP for potential blacklisting, and include offending user-agents so we can detect issues with our SDKs. However we definitely don't need a stack trace here, as there is a pretty clear callpath.

I almost think that a production error where I would want a full stack trace would be a panic, because if I've gotten to the point where the reason for why a call errors is not immediately obvious, you will want to know most likely what was happening in your goroutines at the time of the error. The panic itself will get recovered if you are using `gin.Recovery()`.

Just my 2c.

In retrospect however, now that I see this is still open, Gin has a pluggable architecture for loggers, so I'm going to close this ticket, and if I build one I'll send it as a PR to the contrib repo. Thanks for the library.

**Comment by phemmer** [comment]
I've opened #484 to continue the issue.
