### ISSUE TITLE
MVC skeleton/examples for Gin

### ISSUE THREAD

**Issue by redstrike** [gin-gonic/gin#208]
MVC pattern is the de facto standard for web app. I have tried to implement it with Gin by myself, but it looks naive and maybe too simple.

So, will Gin supports MVC?

**Comment by matejkramny** [comment]
imho, its up to you to design the application in an MVC way and not Gin's responsibility.

**Comment by javierprovecho** [comment]
@redstrike, as @matejkramny said, its up to how you do with your project.

Some tips to accomplish this, is to separate the handlers from the main Go file. Also is to create a folder in the root of your project named `templates` or `views` where your `*.tmpl` resides.

Hope it helped.

**Comment by redstrike** [comment]
Thanks for your tips. My MVC implementation works as expected, I just wonder if the author of Gin or someone who has better EXP than me, could do better in an idiomatic way of Gin :D

Last week, I got some problems with Gin's template render path. Did you fix them completely in master? https://github.com/gin-gonic/gin/issues/119

**Comment by javierprovecho** [comment]
@redstrike you are welcome, I'm one of the authors by the way.

v0.5 which is expected for the weekend, joins all changes in the past months.
v0.6 will resolve almost all issues actually open, and is expected in a month.

Thank you for tagging issue 119, I`ll take a look.

**Comment by javierprovecho** [comment]
@redstrike did you check the corrected example in [`README.md`](https://github.com/gin-gonic/gin#html-rendering)? I paste it for you here:

```go
func main() {
    r := gin.Default()
    r.LoadHTMLGlob("templates/*")
    r.GET("/index", func(c *gin.Context) {
        obj := gin.H{"title": "Main website"}
        c.HTML(200, "index.tmpl", obj)
    })

    // Listen and server on 0.0.0.0:8080
    r.Run(":8080")
}
```
```html
<h1>
    {{ .title }}
</h1>
```

**Comment by redstrike** [comment]
That works, but it doesn't work if I do this:
```Go
func main() {
    r := gin.Default()
    r.LoadHTMLGlob("templates/*")

    // I want to organize more tmpl in each controler's view folder
    r.GET("/user/edit", func(c *gin.Context) {
        obj := gin.H{"title": "User"}
        c.HTML(200, "user/edit.tmpl", obj)
    })

    r.GET("/home", func(c *gin.Context) {
        obj := gin.H{"title": "Home"}
        c.HTML(200, "home/index.tmpl", obj)
    })

    // Listen and server on 0.0.0.0:8080
    r.Run(":8080")
}
```
I don't think below is the correct way to go...
```Go
func main() {
    r := gin.Default()

    r.GET("/user/edit", func(c *gin.Context) {
        r.LoadHTMLGlob("templates/user/*")
        obj := gin.H{"title": "User"}
        c.HTML(200, "edit.tmpl", obj)
    })

    r.GET("/home", func(c *gin.Context) {
        r.LoadHTMLGlob("templates/home/*")
        obj := gin.H{"title": "Home"}
        c.HTML(200, "index.tmpl", obj)
    })

    // Listen and server on 0.0.0.0:8080
    r.Run(":8080")
}
```
