### ISSUE TITLE
Does BindUri works with POST/PATCH/PUT methods?

### ISSUE THREAD

**Issue by goldyfruit** [gin-gonic/gin#2082]
Hi guys,

I would like to know if `BindUri` works with HTTP `POST`, `PATCH` and `PUT` methods?
So far I'm unable to make the validation working as it should.

Route:
```
private.PATCH("/node/properties/:id", nodeSetProperties)
```

Structure:
```
type NodeID struct {
	UUID string `uri:"id" binding:"required" example:"852c5716-d551-4fb0-8995-9a35e9181fa3" format:"string"`
}
```

Handler:
```
func nodeSetProperties(c *gin.Context) {
	var nodeID structure.NodeID
	if err := c.BindUri(&nodeID); err != nil {
		httputil.NewError(c, http.StatusBadRequest, globalRequestData["X-Request-Id"], err)
		return
	}
	code := _nodeSetProperties(c.Param("id"))
	if code == 200 {
		c.JSON(code, gin.H{"return":  "success"})
	}
}
```

I'm agree that it's not the best way how the data should be passed but I'm just wondering. 
Thanks for your help :)

- go version: `1.12.5`
- gin version (or commit ref): `v1.4.0`
- operating system: `Linux`

**Comment by vkd** [comment]
Yes, it works. Do you have a problem with this?

**Comment by goldyfruit** [comment]
@vkd thanks for your answer.

My code above doesn't work, if I remove `category` or `id` from the URI then I got a `404` but nothing about the binding.

**Comment by vkd** [comment]
Could you please provide a minimal full reproducible example with a curl command request? Because I don't understand what you mean in line: "if I remove category or id from the URI ...".

**Comment by goldyfruit** [comment]
@vkd Sure.

When I set the ID in the URL `852c5716-d551-4fb0-8995-9a35e9181fa3` everything is working as expected.
```
$ curl -s -X PATCH http://localhost:8000/v1/node/properties/852c5716-d551-4fb0-8995-9a35e9181fa3 --data '{"payload": "dell"}'
```
Result:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Tue, 08 Oct 2019 00:06:04 GMT
Content-Length: 122

{"return":"success"}
```

Now if I remove `852c5716-d551-4fb0-8995-9a35e9181fa3` from the URL I got `404` instead of the `400` bad request.

```
$ curl -s -X PATCH http://localhost:8000/v1/node/properties --data '{"payload": "dell"}'
```

Result:
```
HTTP/1.1 404 Not Found
Content-Type: text/plain
X-Request-Id: b93114cc-f535-441a-a91f-ad7b97ccdb6a
Date: Tue, 08 Oct 2019 00:08:26 GMT
Content-Length: 18

404 page not found
```

**Comment by vkd** [comment]
@goldyfruit thanks for your detailed answer. Now I see what's wrong.

Unfortunately these routes are not equal:
```
private.PATCH("/node/properties/:id", nodeSetProperties)
private.PATCH("/node/properties", nodeSetProperties)
```
And you need to add the second one explicitly.

**Comment by goldyfruit** [comment]
@vkd That is the thing, I just want to make sure that `:id` parameter is provided to this route. I though it was the purpose or `BindUri` make sure URI parameters are provided.

**Comment by vkd** [comment]
But without `:id` parameter it will not be the same route.

**Comment by goldyfruit** [comment]
> But without `:id` parameter it will not be the same route.

Thanks :)

**Comment by goldyfruit** [comment]
@vkd Just to give feedback after adding the route :)
```
  "message": "Key: 'NodeID.UUID' Error:Field validation for 'UUID' failed on the 'required' tag",
```
Thanks again.
