### ISSUE TITLE
Context.JSON response wrong Content-Type and unknown keyword Content-Regulation

### ISSUE THREAD

**Issue by limen** [gin-gonic/gin#2087]
- go version: go1.12.6 linux/amd64

- gin version (or commit ref): 

github.com/gin-gonic/gin v1.4.0 h1:3tMoCCfM7ppqsR0ptz/wi1impNpT7/9wQtMZ8lr1mCQ=

github.com/gin-gonic/gin v1.4.0/go.mod h1:OW2EZn3DO8Ln9oIKOvM++LBO+5UPHJJDH72/q/3rZdM=

- operating system: CentOS 7 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## Description
If use Context.JSON,
response header is like

> HTTP/1.1 200 OK
Server: nginx
Date: Thu, 05 Sep 2019 02:23:36 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 90
Connection: keep-alive
Content-Regulation: application/json; charset=utf-8

the function below works properly.

```
func renderJSON(ctx *gin.Context, resp interface{}) {
	jsonData, err := json.Marshal(resp)
	if err != nil {
		panic(err)
	}
	ctx.Status(http.StatusOK)
	ctx.Header("Content-Type", "application/json; charset=utf-8")
	ctx.Writer.Write(jsonData)
}
```

**Comment by vkd** [comment]
I see in your response headers example the `Server: nginx` line, but it is not a `gin` response header.

Can you provide a reproducible example with a curl command?

**Comment by limen** [comment]
@vkd Thank you for your attention. See the screenshots below.
![选区_137](https://user-images.githubusercontent.com/3460683/66696442-a6745180-ecfe-11e9-8a60-541909b51672.png)
![选区_138](https://user-images.githubusercontent.com/3460683/66696447-ad9b5f80-ecfe-11e9-823b-973badeb373f.png)

**Comment by vkd** [comment]
Please don't use a screenshot to show code/logs.
And this is still not a reproducible example.

Btw, for me everything works file:
```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello", func(c *gin.Context) {
		c.JSON(200, map[string]interface{}{
			"hello": "world",
		})
	})
	g.Run(":9000")
}
```
```
$ curl -v http://localhost:9000/hello
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> GET /hello HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Sat, 12 Oct 2019 07:16:20 GMT
< Content-Length: 18
<
{"hello":"world"}
* Connection #0 to host localhost left intact
```

**Comment by limen** [comment]
Sorry, I can't copy the output as text so far, the screenshots is second plan.
In my Ubuntu 14.04 desktop, the code works properly.
I think the problem is platform related, and it's not easy to reproduce.

**Comment by vkd** [comment]
I think we can close the issue as not reproducible.
Feel free to reopen the issue if you can provide more details to reproduce.

**Comment by limen** [comment]
OK
