### ISSUE TITLE
multiple modules

### ISSUE THREAD

**Issue by wingsxdu** [gin-gonic/gin#2089]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:1.13
- gin version (or commit ref):1.4.0
- operating system:

## Description
When I use gin and build,there is someting wrong go module like this:
`build what5: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (C:\Users\beihai\go\pkg\mod\github.com\ugorji\go@v1.1.4\codec)
        github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f (C:\Users\beihai\go\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20181022190402-e5e69e061d4f)`

So I try to add `github.com/ugorji/go v1.1.7` in my go.mod file,and it works.
Mybe you should fix this in new releases

## Screenshots

![Annotation 2019-10-09 130944](https://user-images.githubusercontent.com/47047644/66453434-e3d6a600-ea96-11e9-9288-83fc1408ff11.png)

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin/issues/1673
