### ISSUE TITLE
When will  call the v1.5 tag?

### ISSUE THREAD

**Issue by kylesliu** [gin-gonic/gin#2091]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version:
- gin version (or commit ref):
- operating system:

## Description

- We now need a function on the master branch, but not on v1.4, when will I ask for a 1.5 tag?

**Comment by thinkerou** [comment]
#2109
