### ISSUE TITLE
How to jsoniter LowerCaseWithUnderscores()

### ISSUE THREAD

**Issue by micfan** [gin-gonic/gin#2098]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: go version go1.12.6 windows/amd64
- gin version (or commit ref):  v1.3.0
- operating system: Win10

## Description
The below lines won't use the lower case from jsoniter, no matter with the flag `-tags=jsoniter` or not, the `Marshal()` method blocked there, did some one had successfully make it work?

```go

import	"github.com/json-iterator/go"
import	"github.com/json-iterator/go/extra"

func handler(ctx *gin.Context) {
    extra.SetNamingStrategy(extra.LowerCaseWithUnderscores)
    var s, _ = jsoniter.Marshal(j)
    ctx.String(http.StatusOK, string(s))
}
```

**Comment by ShiinaOrez** [comment]
Can u provide the variable called ``j`` in your part of code...? And it seems like the issue about package ``jsoniter``, why u commit it to here...

**Comment by micfan** [comment]
Emm... `j` is an `interface{}` to be Marshal(). I found when build with jsoniter, the extra package not work. 

Now I have gave up that package, turn tu use the default JSON package of Golang...
