### ISSUE TITLE
Please provide support for global route.

### ISSUE THREAD

**Issue by webgini** [gin-gonic/gin#210]
Hello , i want to have support for global route , i mean suppose i want route that can response if no other route is found. like route.Any("*",handler) . i don't know if there is any functionality like it or not. it would be great.

**Comment by achedeuzot** [comment]
I've seen the syntax `route.Any(...)` be used for a route set on all HTTP Verbs, e,g:

    route.Any("/smthg", smthgHandler)
    // being equivalent to 
    route.GET("/smthg", smthgHandler)
    route.POST("/smthg", smthgHandler)
    route.PUT("/smthg", smthgHandler)
    route.DELETE("/smthg", smthgHandler)
    route.OPTIONS("/smthg", smthgHandler)
    route.LINK("/smthg", smthgHandler)
    route.UNLINK("/smthg", smthgHandler)

Which could be useful for gin.

About your problem, why don't you use a catch-all parameter like ` route.GET("/*anything", anythingHandler)` or you could use the `NotFound` handler to obtain that behaviour (even though it's not a very "clean" way to do it).

**Comment by jamie-stackhouse** [comment]
The router package that Gin uses under the hood, httprouter, supports the exact use case of a handler for requests that are not handled by any other route. I don't know off the bat if it is exposed via Gin.

**Comment by techjanitor** [comment]
NotFound is already initialized when you use Gin, regardless of middleware:

https://github.com/gin-gonic/gin/blob/develop/gin.go#L52

**Comment by techjanitor** [comment]
After looking at the code some more I guess the 'global route' can be set by NoRoute:

https://github.com/gin-gonic/gin/blob/master/gin.go#L95

**Comment by techjanitor** [comment]
So just as an example, you'd use it like this:
```
        r := gin.Default()

        r.NoRoute(ErrorController)
```

```
func ErrorController(c *gin.Context) {

        c.JSON(404, gin.H{"error_message": "not found"})

        return

}
```

You get the picture.

**Comment by donileo** [comment]
@techjanitor i implemented what you're suggesting but the NoRoute function will not call the handlers if the resource is status code 405 = 'Method Not allowed' which happens if a invalid Request such as Post is made to a Get route. I believe the NoRoute should also cover this as to truly make it global.

**Comment by javierprovecho** [comment]
@donileo it should, but at first view it would require a refractor of the code if gin context is needed, if not, you can use latest update from httprouter and specify a handler for method not allowed through gin wrap. I'll take it into consideration for developing into next version ( > v0.7)

**Comment by donileo** [comment]
Sounds good.. as a fyi what I did was take a look at your gin.go file and implement an extra method called NoMethod for handling 405 errors. Pretty much a copy and paste implementation of your 404 logic but to handle a 405. So far its working fine though I don't know if it'll pass your tests or if theres anywhere else where making this change will affect.

**Comment by javierprovecho** [comment]
@donileo if you like, could you make a PR of it? thanks

**Comment by donileo** [comment]
Sure. working on that right now

**Comment by manucorporat** [comment]
@achedeuzot https://github.com/gin-gonic/gin/commit/53329e46464d83189a9df401ab3882257064c0db

**Comment by manucorporat** [comment]
@webgini https://github.com/gin-gonic/gin/blob/develop/routergroup.go#L91-L102
