### ISSUE TITLE
Avoid parsing query strings every time ctx.Query() is called

### ISSUE THREAD

**Issue by betabandido** [gin-gonic/gin#2100]
Calling `ctx.Query` involves calling `url.Query`, which needs to parse all the query strings. While `ctx.Query` will typically be called at most once in a handler, it might be called several times per request in the different middleware stages.

I have not quantified the overhead of doing so, but depending on the depth of the middleware pipeline, there might actually be some latency increase just because of parsing the query strings again and again.

Making `ctx.Query` cache the result of `url.Query` would make subsequent calls to `ctx.Query` faster. Does this look like a good idea to you? Can you anticipate any issue that might occur? If this sounds good to you, I can make a PR and evaluate the impact on latency.

**Comment by ShiinaOrez** [comment]
Please check the source code you're reading is the latest... if u wanna call ``gin.Context.Query()``, you would call ``gin.Context.getQueryCache()`` at first. 
Part of source code:
```go
func (c *Context) getQueryCache() {
	if c.queryCache == nil {
		c.queryCache = c.Request.URL.Query()
	}
}
```

**Comment by betabandido** [comment]
Oh, that's cool! Unfortunately that feature is not in the latest stable release. Are there any plans to create a new release?

**Comment by ShiinaOrez** [comment]
I think it would be included in a new stable-release, don't be worry about that.
Performance is always the CORE of programming, there may be a number of other places where performance needs to be improved prior to using cache for parameters, so your issue may be of lower priority.

This issue should be closed : )
