### ISSUE TITLE
Question of gin.engine.trees

### ISSUE THREAD

**Issue by qiujiafei123** [gin-gonic/gin#2101]
import "github.com/gin-gonic/gin" before, why route tree len too big

![](https://pic2.hanmaker.com/86fd264a56bcbdacc7.png?imageHeight=650#imageWidth=264)
![](https://pic2.hanmaker.com/4226c5498abb6b2286.png?imageHeight=1197#imageWidth=578)

The tree becomes normal after using gin.Default
![](https://pic2.hanmaker.com/237d634d0aa1a015b6.png?imageHeight=929#imageWidth=436)

this is my gin version gin@1.4.0

**Comment by ShiinaOrez** [comment]
在提出这个issue的时候, 你首先应该去搞清楚全局变量中切片是如何声明的以及切片的长度和容量问题, 其次, 你的描述和你的截图让你的Issue变得非常混乱, 并没有详细的对应关系, 并且依赖IDE来查看变量的值有可能是IDE本身的锅, 建议在代码中进行检查.

**Comment by qiujiafei123** [comment]
> 在提出这个issue的时候, 你首先应该去搞清楚全局变量中切片是如何声明的以及切片的长度和容量问题, 其次, 你的描述和你的截图让你的Issue变得非常混乱, 并没有详细的对应关系, 并且依赖IDE来查看变量的值有可能是IDE本身的锅, 建议在代码中进行检查.

很感谢你的提醒， 刚才试了可以明确是ide的问题， 你提的几点我会改进，再次感谢
