### ISSUE TITLE
After gin middleware c.Next, if an exception is thrown, the following code can't get the error code.

### ISSUE THREAD

**Issue by ningkexin** [gin-gonic/gin#2113]
``` go
		c.Set("ResponseParams", params)
		content, exist := c.Get("returnData")
		if !exist {
			c.JSON(c.Writer.Status(), code.ServerException)
			return
		}
		marshal, err := json.Marshal(content)
		if err != nil {
			c.JSON(c.Writer.Status(), code.ServerParamsException)
			return
		}
```

The exception is thrown in the above code or panic after the next code can not get the status code will prompt the following:
```log
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
```

**Comment by ShiinaOrez** [comment]
可以提供一下中间件的代码吗? 或者较为完整的逻辑. 只提供如此不完整的代码片段无法解决问题, 我暂时只能推断出不合理的地方:

gin.Context.JSON方法内部调用gin.Context.Render方法, 而Render方法包含了对于gin.Context.Writer的WriterHeaderNow()的调用:

https://github.com/gin-gonic/gin/blob/0ce46610292cc8877a914b1cee41acd5dc9da7ae/context.go#L808

但是在您的代码的调用中, 使用了类似于``Context.JSON(Context.Writer.Status(), json)``的用法, 也就是说传入``JSON``方法的``code``参数是通过已经被写入的``ResponseWriter``来获取的. 这就建立在了``Writer``已经被写过的前提之上, 而在被``Written``的``Writer``之上继续进行新的``WriteHeader()``操作, 自然会发出Warning.

https://github.com/gin-gonic/gin/blob/393a63f3b020df89d42695064443760c7d0a0dc8/response_writer.go#L60-L67

**Comment by ningkexin** [comment]
@ShiinaOrez 这边要封装加密相关中间件 流程：客户端加密请求->中间件解密->api处理->将返回值调用c.Set保存->在 c.Next 后续执行加密 返回给客户端。
上述问题中 c.Next 后 我发现出现panic或者其他异常错误，无法获取当前接口返回的状态码（这是否和使用中间件恢复服务有关系？）！
那么请问如何在c.Next 后获取 statusCode

**Comment by ShiinaOrez** [comment]
c.Next() 和状态码没有任何的关系啊, 你要检查你的代码中对于状态码有修改的地方..., c.Next()只负责让下一个handler去继续执行, 不会处理Header的信息, 你不发代码我也没办法看具体的问题在哪里...

**Comment by ningkexin** [comment]
It is correct to call c.AbortWithStatusJSON after c.Next
