### ISSUE TITLE
how to disable gin log

### ISSUE THREAD

**Issue by hzxgo** [gin-gonic/gin#2115]
I have so many logs like this "[GIN] 2019/10/29 - 17:34:07 | 200 |     152.814µs", how can I disable the gin logs?

**Comment by mnvx** [comment]
https://github.com/gin-gonic/gin/issues/598#issuecomment-212580625

**Comment by xctest** [comment]
didnt works for me, the console still print logs, its so weird.....

**Comment by mnvx** [comment]
Try next.

```go
ginMode := "release"
gin.SetMode(ginMode)
r := gin.New()
r.Use(gin.Recovery())
```

**Comment by gangming** [comment]
[#1798](url)

**Comment by gangming** [comment]
#1798
