### ISSUE TITLE
How to bind part of request body with validate struct?

### ISSUE THREAD

**Issue by Corgi-Google** [gin-gonic/gin#2124]
For example,
Client request body is 
```json
{
  "data": {
    "user_id": "l5jR4eib",
    "password": "password"
  },
  "verify_char": "y8S26y"
}
```
And i hava a struct:
```golang
type data struct {
    UserId
    Password
}
```
I want to bind the "data" field to the validate struct, not all fields.So how can i get it ?

**Comment by SennoYuki** [comment]
type A struct{
     Data *data `json:"data"`
}
