### ISSUE TITLE
Slow release cadence

### ISSUE THREAD

**Issue by betabandido** [gin-gonic/gin#2128]
The latest release (v1.4.0) was six months ago (and there have been quite a few fixes after that). The previous release (v1.3.0) goes back more than one year ago, and the one before was released more than two years ago. 

Also, after release v1.2 there hasn't been any minor release (e.g., v1.4.1).

So, I was wondering what the release plan for Gin is. I understand there needs to be a balance between stability and releasing very often. But, the current cadence seems to be rather slow. Is this something intentional?

**Comment by thinkerou** [comment]
v1.5.0 released.
