### ISSUE TITLE
JSON Binding when incorrect type is passed in

### ISSUE THREAD

**Issue by appleton** [gin-gonic/gin#2131]
## Description

I would like to use binding to validate JSON body input to my HTTP handlers, but I get a panic when the incorrect type is passed in. Am I doing something wrong? Should I be type checking my JSON input _before_ calling the `Bind` function?

## How to reproduce

I have a request struct like this:

```go
type myRequest struct {
	MyValue string `json:"my_value" binding:"required"`
}
```

I would like to make use of `context.BindJSON()` to validate input and marshal the request into a struct.

```go
	req := &myRequest{}
	if err := c.BindJSON(req); err != nil {
		c.JSON(400, c.Errors)
		return
	}
```

This works fine until I pass in a non-string value to the POST body, at which point I get a panic.

```
POST /my-endpoint

{
  "my_value": 1
}
```

## Expectations

Validation fails and I can return a `400` from the handler.

## Actual result

produces:
```
panic: interface conversion: error is *json.UnmarshalTypeError, not validator.ValidationErrors [recovered]
	panic: interface conversion: error is *json.UnmarshalTypeError, not validator.ValidationErrors
```

## Environment

- go version: 1.13.1
- gin version (or commit ref): 1.4.0
- operating system: MacOS

**Comment by vkd** [comment]
I cannot reproduce this error:
```
package main

import "github.com/gin-gonic/gin"

type myRequest struct {
	MyValue string `json:"my_value" binding:"required"`
}

func main() {
	e := gin.Default()
	e.POST("/", func(c *gin.Context) {
		req := &myRequest{}
		if err := c.BindJSON(req); err != nil {
			c.JSON(400, c.Errors)
			return
		}
	})
	e.Run(":9000")
}
```

```
curl -X POST localhost:9000 -d '{"my_value": 1}'
{"error":"json: cannot unmarshal number into Go struct field myRequest.my_value of type string"}
```

## Environment

- go version: 1.13.1
- gin version (or commit ref): v1.4.0 and master
- operating system: MacOS

**Comment by appleton** [comment]
Argh, I'm so sorry for wasting your time! I have a bug in a function which translates `c.Errors` into another format for the JSON response and of course I didn't test it without that removed first.

Sorry again!
