### ISSUE TITLE
Does Bind still not support the []* multipart.fileheader type

### ISSUE THREAD

**Issue by ne1llee** [gin-gonic/gin#2133]
Does Bind still not support the []* multipart.fileheader type?

version: 1.4.0

**Comment by vkd** [comment]
Issue: #1878
PR: #1949 
Will be supported in [v1.5.0](https://github.com/gin-gonic/gin/pull/2109/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR14)
