### ISSUE TITLE
gin mode unknown: debug

### ISSUE THREAD

**Issue by GimignanoF** [gin-gonic/gin#2134]
## Description

I'm trying to follow this tutorial for setting up a gin gonic server
[https://dev.to/cmelgarejo/creating-an-opinionated-graphql-server-with-go-part-2-46io](https://dev.to/cmelgarejo/creating-an-opinionated-graphql-server-with-go-part-2-46io). However when i try to run the server, this error pops up:
`
panic: gin mode unknown: debug
`

In the .env file I have the GIN_MODE variable set like this

`
GIN_MODE=debug
`

I don't understand what is wrong with this, as the variable value should be correct

## How to reproduce

Set the environment variable for GIN_MODE like this

```
GIN_MODE=debug
```

## Expectations

The server runs in debug mode

## Actual result

The server crash

## Environment

- go version: 1.12
- gin version (or commit ref): 1.4.0
- operating system: Windows 10 1909

**Comment by vkd** [comment]
I can't reproduce this problem, everything works fine for me:
```
$ GIN_MODE=debug go run main.go
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /                         --> main.main.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :9000
```


## Environment

- go version: go1.13.1
- gin version (or commit ref): v1.4.0 and master
- operating system: MacOS

**Comment by GimignanoF** [comment]
Idk why, but I've updated the Go version to 1.13.4 and now it works ¯\_(ツ)_/¯
