### ISSUE TITLE
func (*Context) FullPath in documentation but not released yet

### ISSUE THREAD

**Issue by orov-io** [gin-gonic/gin#2140]
Hi all,
I'm using the Gin framework for go developments. Actually, I need to use the function Fullpath that you says in documentation, but this function is missing in the stable version (v1.4.0 at this moment).

To solve this, I decided to use the last master commit (db9174ae0c25), but this break compatibility with the validator (v8 -> v9). Now, binding:"exists" is breaking the application.

So please, it would be nice if you didn't document functions that still can't be used without compromising the system. The fullpath function should not be seen in the official documentation until it moves to a stable version (which will already be a v2, as there is no backward compatibility in the master line anymore).

**Comment by thinkerou** [comment]
v1.5.0 released!
