### ISSUE TITLE
Question on routes grouping

### ISSUE THREAD

**Issue by aeon3k** [gin-gonic/gin#2152]
Hi,
I have two different router groups for 2 different purposes.
I'd like to be able to call the same function from those 2 groups but with a different parameter. Is it possible to do so and if it is the case, how can I do that ?

```
v1API := router.Group("v1")
{
		v1API.POST("/items", GetItems(context?, false))
}
v2API := router.Group("v2")
{
		v2API.POST("/items", GetItems(context? , true ))
}
```
thanks in advance for your help

**Comment by vkd** [comment]
I prefer this way:
```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/items", GetItems(true))
	g.POST("/items", GetItems(false))
	g.Run(":9000")
}

func GetItems(param bool) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.String(200, "%t", param)
	}
}
```

**Comment by aeon3k** [comment]
Hi Dmitry
Thanks for you answer.
I already knew this technique but I wanted to know if there was a way of
doing it via grouping.


Le lun. 25 nov. 2019 à 20:29, Dmitry Kutakov <notifications@github.com> a
écrit :

**Comment by vkd** [comment]
Sorry, but I don't understand what kind of problem you want to solve. Please provide more details.
And what's wrong with this example?
```
v1API := router.Group("v1")
{
	v1API.POST("/items", GetItems(false))
}
v2API := router.Group("v2")
{
	v2API.POST("/items", GetItems(true))
}

...

func GetItems(param bool) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.String(200, "%t", param)
	}
}
```

**Comment by aeon3k** [comment]
this is what I was looking for. Thanks.
