### ISSUE TITLE
[Break-Backward] use encode replace json marshal increase json encoder speed not in release notes

### ISSUE THREAD

**Issue by makubit** [gin-gonic/gin#2158]
- Should point in release notes that there was a change in WriteJSON, what is breaking backward

## Description
Bumping gin version to 1.5 has broken our tests. There is a difference in implementation in WriteJSON. Gin 1.5 uses `encoder := json.NewEncoder(w)` instead of `jsonBytes, err := json.Marshal(obj)`. This difference causes adding a new line at the end of the result object (because it's now an encoder), which is break-backward.

## Difference in code

```
func WriteJSON(w http.ResponseWriter, obj interface{}) error {
	writeContentType(w, jsonContentType)
	jsonBytes, err := json.Marshal(obj)
	if err != nil {
		return err
	}
	w.Write(jsonBytes)
	return nil
}

func WriteJSON(w http.ResponseWriter, obj interface{}) error {
	writeContentType(w, jsonContentType)
	encoder := json.NewEncoder(w)
	err := encoder.Encode(&obj)
	if err != nil {
		return err
	}
	return nil
}
```

## Tests previously

```
       assert.Equal(t, "{\"foo\":\"bar\",\"html\":\"\\u003cb\\u003e\"}", w.Body.String())
```

## Tests after updating gin version to 1.5

```
	assert.Equal(t, "{\"foo\":\"bar\",\"html\":\"\\u003cb\\u003e\"}\n", w.Body.String())
```

## Environment

- go version: 1.13
- gin version (or commit ref): 1.5
- operating system: windows

**Comment by thinkerou** [comment]
@makubit thanks! https://github.com/gin-gonic/gin/releases/tag/v1.5.0 done!
