### ISSUE TITLE
Getting new gin version is failing

### ISSUE THREAD

**Issue by chelsea76** [gin-gonic/gin#2161]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

Getting new gin version using go is failing

## How to reproduce

>  $ go get github.com/gin-gonic/gin
package github.com/go-playground/validator/v10: cannot find package "github.com/go-playground/validator/v10" in any of:
/usr/local/go/src/github.com/go-playground/validator/v10 (from $GOROOT)
/Users/dipeshprajapati/Workspace/go/src/github.com/go-playground/validator/v10 (from $GOPATH)
$

## Expectations

Should be able to get Master version without any error

## Actual result

> >  $ go get github.com/gin-gonic/gin
package github.com/go-playground/validator/v10: cannot find package "github.com/go-playground/validator/v10" in any of:
/usr/local/go/src/github.com/go-playground/validator/v10 (from $GOROOT)
/Users/dipeshprajapati/Workspace/go/src/github.com/go-playground/validator/v10 (from $GOPATH)
$

## Environment

- go version: 1.9
- gin version (or commit ref): Master
- operating system: Mac OS

**Comment by EtienneR** [comment]
You're Go version is too old... 

>the first need Go installed (version 1.11+ is required)
https://github.com/gin-gonic/gin#installation

**Comment by rujews** [comment]
please upgrade your go version to 1.11+ and try it again.
@chelsea76

**Comment by ianchildress** [comment]
i'm using `go version go1.12.6 linux/amd64` and receiving the same error.

**Comment by gipsh** [comment]
moving from 1.10 to 1.12.10 worked for me.

**Comment by chelsea76** [comment]
Yes worked with Go 1.11.
