### ISSUE TITLE
Log Color

### ISSUE THREAD

**Issue by Flipped199** [gin-gonic/gin#2168]
gin输出日志不能正常显示颜色

[GIN] 2019/12/05 - 21:41:08 |?[97;42m 200 ?[0m|      1.9874ms |       127.0.0.1 |?[97;44m GET     ?[0m /

**Comment by rujews** [comment]
控制台输出的只有状态码和请求的方法有颜色，看下你是否使用了`gin.DisableConsoleColor()`函数禁止了控制台的颜色。 @Flipped199

**Comment by appleboy** [comment]
Please talk in English.
