### ISSUE TITLE
using gin.DefaultWriter = io.MultiWriter(f, os.Stdout) can't write to log file

### ISSUE THREAD

**Issue by hantmac** [gin-gonic/gin#2184]
## Description
Writing to log file failed.
I use the following code to open gin log setting:
```
f, err := os.Create("./logs/log.log")
	if err != nil {
		log.Error("Open Log File Failed", err)
	}
	gin.DefaultWriter = io.MultiWriter(f, os.Stdout)
	log.Info("Init Gin log set ")
```
## How to reproduce

```
f, err := os.Create("./logs/log.log")
	if err != nil {
		log.Error("Open Log File Failed", err)
	}
	gin.DefaultWriter = io.MultiWriter(f, os.Stdout)
	log.Info("Init Gin log set ")
```

```
package main

import (
	"github.com/gin-gonic/gin"
       "os"
       "io"
       "log"
)

func main() {
	g := gin.Default()
       f, err := os.Create("./logs/log.log")
	if err != nil {
		log.Error("Open Log File Failed", err)
	}
	gin.DefaultWriter = io.MultiWriter(f, os.Stdout)
	log.Info("Init Gin log set ")
```
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```

## Expectations
The log will wirte into `./logs/log.log`

## Actual result
In ` ./logs/log.log`  not found the logs.

## Environment

- go version: 1.13
- gin version (or commit ref): 1.15
- operating system: mac os

**Comment by rujews** [comment]
Because `gin.Default ()` uses the `Logger` middleware, you need to assign a`io.Writer` to `gin.DefaultWriter` in order to be effective.

Correct code：

```
func main() {

	f, err := os.Create("./logs/log.log")
	if err != nil {
		fmt.Println("Open Log File Failed", err)
	}
	gin.DefaultWriter = io.MultiWriter(f, os.Stdout)

	g := gin.Default()
	fmt.Println("Init Gin log set ")
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```
@hantmac

**Comment by hantmac** [comment]
> Because `gin.Default ()` uses the `Logger` middleware, you need to assign a`io.Writer` to `gin.DefaultWriter` in order to be effective.
> 
> Correct code：
> 
> ```
> func main() {
> 
> 	f, err := os.Create("./logs/log.log")
> 	if err != nil {
> 		fmt.Println("Open Log File Failed", err)
> 	}
> 	gin.DefaultWriter = io.MultiWriter(f, os.Stdout)
> 
> 	g := gin.Default()
> 	fmt.Println("Init Gin log set ")
> 	g.GET("/hello/:name", func(c *gin.Context) {
> 		c.String(200, "Hello %s", c.Param("name"))
> 	})
> 	g.Run(":9000")
> }
> ```
> 
> @hantmac

Thanks!
