### ISSUE TITLE
Param with path

### ISSUE THREAD

**Issue by eksnow** [gin-gonic/gin#2187]
Router `r.GET("/admin:MODE", HandleAdmin)`
Hander `mode := c.Param("MODE")`

HTTP GET `http://127.0.0.1:8088/v2d0/admin:offline`
Result `mode = ":offline"` 
is BUG?

**Comment by DreamsOfImran** [comment]
@equinoxe1 , Can you please elaborate on your question?

**Comment by thinkerou** [comment]
you should write `r.GET("/admin/:MODE`)`
