### ISSUE TITLE
conflicts with existing wildcard 

### ISSUE THREAD

**Issue by susanDao** [gin-gonic/gin#2195]
I have two path:

1. /v1a:com
2./v1:coms

When i start the server, i get the panic :

- "panic: path segment 'a:com' conflicts with existing wildcard ':com' in path '/v1a:com'"

why? the ":", in my case , does not mean a wildcard. Is that reasonable？

**Comment by flaviostutz** [comment]
I need this too! 
I think #1730 is about the same issue.

**Comment by susanDao** [comment]
> I need this too!
> I think #1730 is about the same issue.


Have you solved it ？ i am going to add a flag to identify the ":" is a wildcard or not......
