### ISSUE TITLE
How to reset queryCache?

### ISSUE THREAD

**Issue by gloomyzerg** [gin-gonic/gin#2197]
I want to change value of query string from Middleware
```
$ curl http://localhost:8201/?test=1
```

```
 _ = c.Query("test")
params, _ := url.ParseQuery(c.Request.URL.RawQuery)
test:= params.Get("test") 
fmt.Println(test) //output 1

params.Set("test","2")
c.Request.URL.RawQuery = params.Encode()
fmt.Println(c.Query("test")) //output 1

```
how to reset queryCache?

## Environment

- go version:
- gin version (or commit ref): 1.5
- operating system:

**Comment by yeqown** [comment]
@gloomyzerg 

maybe you should change the `RawQuery` before calling `c.Query` like:
```go
// _ = c.Query("test")
params, _ := url.ParseQuery(c.Request.URL.RawQuery)
test := params.Get("test") 

params.Set("test","2")
c.Request.URL.RawQuery = params.Encode()
fmt.Println(c.Query("test")) // output 1
```

actually, `c.Query` called `c.GetQueryArray`, like the code describes if you have called `c.Query` before you reset `Request.URL`, the `queryCache` will not update

```go
func (c *Context) getQueryCache() {
	if c.queryCache == nil {
		c.queryCache = c.Request.URL.Query()
	}
}

// GetQueryArray returns a slice of strings for a given query key, plus
// a boolean value whether at least one value exists for the given key.
func (c *Context) GetQueryArray(key string) ([]string, bool) {
	c.getQueryCache()
	if values, ok := c.queryCache[key]; ok && len(values) > 0 {
		return values, true
	}
	return []string{}, false
}
```

**Comment by baderkha** [comment]
@gloomyzerg did you end up implementing this as i couldn't get it to work with the above code , the cache doesn't want to reset somehow.

**Comment by YoghurtFree** [comment]
> @gloomyzerg
> 
> maybe you should change the `RawQuery` before calling `c.Query` like:
> 
> ```go
> // _ = c.Query("test")
> params, _ := url.ParseQuery(c.Request.URL.RawQuery)
> test := params.Get("test") 
> 
> params.Set("test","2")
> c.Request.URL.RawQuery = params.Encode()
> fmt.Println(c.Query("test")) // output 2
> ```
> 
> actually, `c.Query` called `c.GetQueryArray`, like the code describes if you have called `c.Query` before you reset `Request.URL`, the `queryCache` will not update
> 
> ```go
> func (c *Context) getQueryCache() {
> 	if c.queryCache == nil {
> 		c.queryCache = c.Request.URL.Query()
> 	}
> }
> 
> // GetQueryArray returns a slice of strings for a given query key, plus
> // a boolean value whether at least one value exists for the given key.
> func (c *Context) GetQueryArray(key string) ([]string, bool) {
> 	c.getQueryCache()
> 	if values, ok := c.queryCache[key]; ok && len(values) > 0 {
> 		return values, true
> 	}
> 	return []string{}, false
> }
> ```

thanks, this solve my question about "how to reset queryCache"
