### ISSUE TITLE
cache static files (js and css files)

### ISSUE THREAD

**Issue by MostajeranMohammad** [gin-gonic/gin#2200]
Hi
are there any way to cache assets files in gin?
I want to serve assets files from memory to fast up server responding. (because i think it's faster if I read files from RAM instead HDD.)
Is it a good idea?
If it was , should i use redis or i must implement my own code to do this?

I hope anyone say to me: " gin do that , you don't need implement it :-) "

**Comment by rujews** [comment]
for static files，you should use `nginx` cache，try `proxy_cache` config.

**Comment by MostajeranMohammad** [comment]
![Screenshot from 2020-01-03 17-01-09](https://user-images.githubusercontent.com/46950343/71725923-c709fe80-2e4a-11ea-919b-a2958ec1fe64.png)

Does anyone confirm this?
