### ISSUE TITLE
Remove contents of the Authorization header while dumping requests for broken pipe failure

### ISSUE THREAD

**Issue by joycehuh** [gin-gonic/gin#2201]
- With issues:

## Description

https://github.com/gin-gonic/gin/pull/1836 
This PR fix the issue partially, with brokenpipe case, the entire httpReques containing the user credentials is still being logged as error. 

## How to reproduce
Client cancel a downloading request will lead to broken pipe panic, and the RecoveryWithWriter method will log it as errors including the entire http request which contains sensitive user info like Authorization token etc.

## Expectations
No logging of sensitive user data in the log.

## Actual result
Logs contain sensitive user data when encounter broken pipe failure.

## Environment

- go version: go1.13.4
- gin version (or commit ref): v.1.5.0
- operating system: Linux

**Comment by zachnewburgh** [comment]
I also ran into this issue, which is caused by:

```
if isBrokenPipe {
  logger.Printf("%s\n%s%s", err, string(httpRequest), reset)
```
https://github.com/gin-gonic/gin/blob/540b1eff7069128df5d95e09968569f2266d9a6a/recovery.go#L79

Is there any update on progress to resolve this issue?

**Comment by ghoshabhi** [comment]
Thank you @zachnewburgh for fixing this! This was indeed an issue.
