### ISSUE TITLE
context.JSON adds a new line to end of JSON response

### ISSUE THREAD

**Issue by kishaningithub** [gin-gonic/gin#2209]
## Description

context.JSON() adds a new line character \n to end of JSON response

## How to reproduce

Clone [this repo](https://github.com/kishaningithub/gin-newline) and run 

```bash
$ GIN_MODE=release go run gin-newline.go
```

## Expectations

Newline character ("\n") must not get added to the end of `{"message":"hello world"}`

## Actual result

new line character gets added

## Environment

- go version: 1.13.5
- gin version (or commit ref): v1.5.0
- operating system: mac os

**Comment by jpninanjohn** [comment]
Before 1.5, context.JSON was using json.Marshal [Refer Here](https://github.com/gin-gonic/gin/blob/v1.4.0/render/json.go#L69-L77). In 1.5 this was changed to use encoder.Encode(). [Refer Change](https://github.com/gin-gonic/gin/blob/v1.5.0/render/json.go#L69-L74)

Encoder adds a line at the end. [Refer to this code](https://github.com/golang/go/blob/master/src/encoding/json/stream.go#L217)

An [issue](https://github.com/golang/go/issues/37083) about this is raised in the golang repository also.

**Comment by KaushikNeelichetty** [comment]
Linking the [PR](https://github.com/gin-gonic/gin/pull/1546#issuecomment-564482419) which caused this issue in the name of performance improvement trading correctness and that too without numbers.

**Comment by sayeedhussain** [comment]
This is causing an issue for me. I have a use case where I have a java service that acts as a front for a go service. The java service directly forwards the response headers but deserializes the response json from go using jackson which trims off the **newline** character and then again serializes it.  Hence, the consumers of my java service are getting a content length mismatch issue between content-length header and actual content body.

**Comment by igorfraa** [comment]
for those who do not appreciate this change and expect JSONs ending with newline, a straightforward middleware that appends a newline after every response:

```
// MiddlewareNewlineAppender returns a Gin middleware that should be executed just after the handler.
// It appends a newline character to the response for 'curl/*' useragent.
func MiddlewareNewlineAppender() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		ctx.Next() // First call the next handler in the chain.
		useragent := ctx.Request.UserAgent() // Then perform the actual job of appending a newline character.
		if strings.HasPrefix(useragent, "curl") {
                    _, _ = ctx.Writer.WriteString("\n")
		}
	}
}
```
