### ISSUE TITLE
SetCookie broken

### ISSUE THREAD

**Issue by sguillia** [gin-gonic/gin#2214]
Hello

It seems you have made a breaking change 4 hours ago (our CI broke)

In source file, SetCookie expects 8 parameters
https://github.com/gin-gonic/gin/blob/master/context.go#L778

In the README, SetCookie expects 7 parameters
https://github.com/gin-gonic/gin/blob/master/README.md
```go
c.SetCookie("gin_cookie", "test", 3600, "/", "localhost", false, true)
```

On the CI
```
... not enough arguments in call to c.SetCookie
	have (string, string, number, string, string, bool, bool)
	want (string, string, int, string, string, http.SameSite, bool, bool)
```

Could you please update the README so that it is consistent with the source code? Otherwise, it is hard to find out where the problem comes from, and which one is the good prototype :-)

From commit f94406a087079bfa5a924cc8095ba753160e885c

Best

**Comment by tmathews** [comment]
Oof

**Comment by owenwatts** [comment]
when i go get the 1.5.0 version, i can't get newest code with samesite option in SetCookie funciton
