### ISSUE TITLE
when use the sessions, memory  leak

### ISSUE THREAD

**Issue by 858806258** [gin-gonic/gin#222]
I read this find the reason  https://github.com/gorilla/sessions/commit/44fb592008c2ecfbfc89725a8ae1638711dfa423
sessions use this package github.com/gorilla/context   have some  global variables, the variables never be clear. 
the doc of  gorilla/context is here http://www.gorillatoolkit.org/pkg/context
finally!forgive me ,I am not good at Englsih.

**Comment by manucorporat** [comment]
this is already fixed! check contrib
