### ISSUE TITLE
Google Cloud Function,  "Function panic: handlers are already registered for path"

### ISSUE THREAD

**Issue by createchange** [gin-gonic/gin#2225]
## Description

I have created a couple of functions that live as Google Cloud Functions. The functions serve as Slack slash commands, with the `ParserGCP` function returning a dialog box that users can make selections on, and the `DialogGCP` function making a database call and returning the appropriate information. I have constructed the following code to handle the requests:

```
// ParserGCP handles initial requests
func ParserGCP(rw http.ResponseWriter, rr *http.Request) {
	r.Use(helpers.AddRequestToContext(rr))
	r.Handle("POST", "/parser", func(c *gin.Context) { handlers.ParseSlash(c) })
	r.ServeHTTP(rw, rr)

}

// DialogGCP handles user submitted dialog box requests
func DialogGCP(rw http.ResponseWriter, rr *http.Request) {
	r.Use(helpers.AddRequestToContext(rr))
	r.Handle("POST", "/dialog", func(c *gin.Context) { handlers.ParseDialog(c) })
	r.ServeHTTP(rw, rr)
}
```

The above works 50% of the time. The other half of the time, the function fails with the error in the subject line: "Function panic: handlers are already registered for path"

I am confused by as nowhere else in the code do I identify any other handlers - what you see above are the only handler declarations and there is certainly no duplication of handlers at all. I would suspect that each call of the functions would spawn a new environment anyway (and it's important to note that it's always the first instantiation of the function that creates the error), so I am kind of lost on what would be causing this. Unfortunately, Google and previous issues didn't provide the direction I was hoping for.

## Expectations

100% successful completion of the functions.

## Actual result

See log results below. Please note the existence of failing and successful requests:
![image](https://user-images.githubusercontent.com/29058450/73868742-42721d80-4806-11ea-9f80-787282a85a7d.png)

## Environment

- go version: v1.13.4
- gin version (or commit ref): v1.5.0
- operating system: function running on GCP, GO version 1.13

**Comment by createchange** [comment]
Turns out that r.Handle directives to the init function resolved the errors I was getting. Not sure why, but works for me.

**Comment by shakilbd009** [comment]
> Turns out that r.Handle directives to the init function resolved the errors I was getting. Not sure why, but works for me.

so basically you wrapped 
func init(){
r.Handle("POST", "/dialog", func(c *gin.Context) { handlers.ParseDialog(c) })
r.ServeHTTP(rw, rr) }
and made it worked? above works for me too or I am getting the same handlers are already registered, but wondering why
