### ISSUE TITLE
Is `application/x-www-form-urlencoded` supported at the moment?

### ISSUE THREAD

**Issue by zerkms** [gin-gonic/gin#223]
It's not mentioned in the doc block at https://github.com/gin-gonic/gin/blob/master/context.go#L286

And also when I use another product (https://github.com/smira/aptly) that uses `gin` internally I cannot find out how to encode array for application to marshall it properly.

    -H "Content-Type: application/json; charset=utf-8" --data '{"PackageRefs":["Pall test-build 2.3.19-0 e5a407129146e72a"]}'

This is the request that passes.

The corresponding structure looks like

    var b struct {
        PackageRefs []string
    }

I tried various combinations of

    --data 'PackageRefs[0]=Pall test-build 2.3.19-0 e5a407129146e72a'

which included removing the `0` index and all possible permutations of encoding of the string (like using `+` for spaces, or `%20` or encoding `[` and `]` additionally, etc).

So my final question is - is `gin` currently able to marshall the ``application/x-www-form-urlencoded`` request into that struct?

If so, how the request body should look like?

**Comment by techjanitor** [comment]
Yes, for binding:
https://github.com/gin-gonic/gin/blob/3fbac59e588fcc8dbc79e2810b47769a6db95f50/gin.go#L23

I don't know for sure if you can put form data into a slice as you can with JSON.  You could just split the input:

```
package main

import (
        "github.com/gin-gonic/gin"
        "strings"
)

func main() {
        r := gin.Default()

        r.POST("/post", func(c *gin.Context) {
                var f Form

                c.Bind(&f)

                split := strings.Split(f.PackageRefs, ",")

                output := strings.Join(split, " ")

                c.String(200, output)

        })

        r.Run(":8888")

}

// Binding from form values
type Form struct {
        PackageRefs string `form:"packagerefs" binding:"required"`
}
```

```
curl -XPOST -H "Content-Type: application/x-www-form-urlencoded" -d "packagerefs=whatever,dont,care"
```

**Comment by zerkms** [comment]
@techjanitor unfortunately the binding structure is not under my control.

And honestly I don't think it's a good idea since the array of strings is semantically more collect for a collection of strings rather than a string with arbitrary separator.

Let's see if any of dev team guys confirm it's a bug (?) and if it will be fixed if so.

**Comment by javierprovecho** [comment]
@zerkms sorry for delay

It does support it, because we wrap http.request .

About posting an array with www-form-urlencoded, here is an example for the following query:

## application/json
```json
{
    "PackageRefs" : [
        "Pall test-build 2.3.19-0 e5a407129146e72a"
    ]
}
```
## application/x-www-form-urlencoded
```
PackageRefs%5B0%5D=Pall+test-build+2.3.19-0+e5a407129146e72a
```

**Comment by zerkms** [comment]
And as I mentioned in the initial post - it does not work. The object is not marshalled from this request body.

**Comment by javierprovecho** [comment]
@zerkms sorry, I'll investigate it, but I think it can be a bug with http request form parsing.

**Comment by zerkms** [comment]
@javierprovecho yep, I'm sure I could google something from the `http.request`. I just don't have any Go background to provide more technical details...

**Comment by manucorporat** [comment]
@zerkms I do not understand this issue.
I just tried it, and it works perfectly.

My struct:
```go
type Struct struct {
	Names []string `form:"names"`
	Authors []string
	Value string   `form:"val"`
}
```

```
--data 'PackageRefs[0]=Pall test-build 2.3.19-0 e5a407129146e72a'
```
what is that?

do you want each word to be a different string inside the array?

**Comment by zerkms** [comment]
After half a year I used to living with the problem and honestly I cannot spend even more time to recreate the original environment to reproduce it again.

Let's treat it as not a bug.

Thank you.

**Comment by manucorporat** [comment]
@zerkms ok! don't worry. Thanks anyway.
