### ISSUE TITLE
Mutliple slashes in the url,like ////a////b will match /a/b

### ISSUE THREAD

**Issue by usernameisnull** [gin-gonic/gin#2239]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

Is this is a feature or I used it wrong, Mutliple slashes in the url,like a////b will match a/b,a little weired
## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
	"log"
)

func main() {
	r := gin.Default()
	r.GET("/a", func(c *gin.Context) {
		log.Printf("in handler1, url = %s", c.Request.RequestURI)
		c.JSON(200, c.Request.RequestURI)
	})
	r.GET("/a/b", func(c *gin.Context) {
		log.Printf("in handler1, url = %s", c.Request.RequestURI)
		c.JSON(200, c.Request.RequestURI)
	})
	r.Run(":9999")
}
```

## Expectations

```
$ curl -i http://localhost:9999//////a
http 404
$ curl -i http://localhost:9999//////a//////b
http 404
```

## Actual result

```
$ curl -i http://localhost:9999//////a
http 200, route /a was matched
$ curl -i http://localhost:9999//////a//////b
http 200, route /a/b was matched
```

## Environment

- go version: go version go1.12.14 windows/amd64
- gin version (or commit ref): v1.5.0
- operating system: windows

**Comment by usernameisnull** [comment]
OK,I found github handle the same,
https://github.com//////alberliu/gim////////issues//////2239
will match 
https://github.com/gin-gonic/gin/issues/2239
I just don't understand, did I miss something?

**Comment by appleboy** [comment]
@usernameisnull Already fixed in https://github.com/gin-gonic/gin/pull/2159, you can try it on the master branch or waiting for v1.6 release.

**Comment by usernameisnull** [comment]
good job,I have tried on the master
