### ISSUE TITLE
[Question] How to return XML data whose root node is <xml>

### ISSUE THREAD

**Issue by liangyuanpeng** [gin-gonic/gin#2243]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description
I need to return data some like : 
```
<xml>
         <Content>...</Content>
          ...
</xml>
```

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

type Message struct{
    Content string
}

func main() {
	g := gin.Default()
	g.GET("/hello", func(c *gin.Context) {
               var message = Message{Content:"123"}
		c.XML(200, &message)
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:9000/hello
<xml><Content>123</Content></xml>
```

## Actual result

```
$ curl -i http://localhost:9000/hello
<Message><Content>123</Content></Message>
```

## Environment

- go version: ``go version go1.13.4 linux/amd64``
- gin version (or commit ref): ``github.com/gin-gonic/gin v1.5.0``
- operating system:  ``ubuntu 16``

Thank any help!!

**Comment by shlinym** [comment]
```
type Message struct {
	XMLName xml.Name `xml:"xml"`
	Content string
}
```
```
curl http://localhost:4000/hello
<xml><Content>123</Content></xml>
```

define a XMLName will solve
