### ISSUE TITLE
Context doesn't have an interface.

### ISSUE THREAD

**Issue by SteveParrington** [gin-gonic/gin#225]
Hello! I'm currently working on a library to make writing tests for Gin web services easier. An obstacle in my path is that there is no interface for a Context, I'm creating some test helpers that will create a mocked context so I can fake requests. The lack of an interface makes this frustrating because if I just make my own interface I can't access the HTTP Request without doing a type conversion in my handler.

I propose creating a Context interface in Gin and adding a GetRequest() method to it. This wouldn't break API compatibility as long as we name the interface something other than Context and would be a great help to me. I'm happy to make the changes myself and submit a PR, I'd just like to know if it would be accepted or not.

**Comment by SteveParrington** [comment]
I have found an alternative approach that I think is better so I don't actually need the interface anymore, closing.

**Comment by javierprovecho** [comment]
@SteveParrington sorry for delay, I agree with you. Some of the points of Gin, is to make it as flexible as performance is not affected. Submit your PR when ready, and it will be merged after review. Thank you!
