### ISSUE TITLE
Release v1.6 version

### ISSUE THREAD

**Issue by appleboy** [gin-gonic/gin#2268]
@thinkerou Maybe we should move some items out of v1.6?

https://github.com/gin-gonic/gin/milestone/11

**Comment by thinkerou** [comment]
> @thinkerou Maybe we should move some items out of v1.6?
> 
> https://github.com/gin-gonic/gin/milestone/11

@appleboy Yes, I agree.

**Comment by thinkerou** [comment]
@appleboy I have updated some issue/pr, please review/check, thanks!

**Comment by appleboy** [comment]
ready to release v1.6.0 version. :) 👍

**Comment by appleboy** [comment]
https://github.com/gin-gonic/gin/releases/tag/v1.6.0
