### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by SedueRey** [gin-gonic/gin#227]
Hello,

I'm planning to use gin to get an RESTFull API but I don't see how shoud I use Gin to listen HTTPS connections. Is there any tutorial or video or contrib I could see?

Thanks,

**Comment by matejkramny** [comment]
I suggest you get nginx to listen to https and proxy the request to gin.

Matej Kramny

**Comment by SedueRey** [comment]
Cool! 
Same code for both listeners... I'll try. Thanks!

**Comment by gladkikhartem** [comment]
Nginx is not an option for some situations. Solution:

import  "net/http"

err := http.ListenAndServeTLS(address, SSLCert, SSLPrivKey, ginRouter)

**Comment by jiguangin** [comment]
good

**Comment by jiguangin** [comment]
> Nginx is preffered for SSL termination, because it's about 3 times faster in terms of handshaking. And Nginx better handles slow clients.
> However it's not an option for some situations. For example portable apps or similar.
> 
> Here's how to do out-of-the box SSL with gin:
> 
> ```
> import  "net/http"
> 
> err := http.ListenAndServeTLS(address, SSLCert, SSLPrivKey, ginRouter)
> ```

good

**Comment by thinkerou** [comment]
@jiguangin you can use `RunTLS(address, SSLCert, SSLPrivKey)`
