### ISSUE TITLE
How to support root level wildcard parameters in path?

### ISSUE THREAD

**Issue by MrJohnDo** [gin-gonic/gin#2286]
How do I achieve the following with Gin

router.GET("/: userHandle/*userAction", func(c *gin.Context) {
}

panic: wildcard route ': userHandle' conflicts with existing children in path '/:userHandle'

**Comment by MrJohnDo** [comment]
Anybody there? 36K stars!!!!! My ass.

**Comment by appleboy** [comment]
See the comment https://github.com/gin-gonic/gin/issues/2016#issuecomment-523204888
