### ISSUE TITLE
Timeout: It spend 31m45s, I don't know why since all time consuming is done.

### ISSUE THREAD

**Issue by KylinGu** [gin-gonic/gin#2287]
## Description

Recently, I am meeting a normal request spent 31m40s at some times. Usualy, it only spend 400ms.

## How to reproduce

I can't reproduce it.

## Expectations

normal case
`[GIN] 2020/03/19 - 15:50:06 | 200 |  469.636269ms |      172.18.0.1 | GET      /api/confMgr/v1/scenarioConfig/luaScript?enterprise_id=bb3exxxxx0ad11e7bd860242ac1xxxxx&app_id=c3f3e49531xxxxxd8bbb5b247c9a8db6&scenario_id=06e25665-e4fb-xxxx-xxxx-f1622cef3d0e`

## Actual result

abnormal case.
`[GIN] 2020/03/19 - 17:56:05 | 200 |        **31m40s** |      172.18.0.1 | GET      /api/confMgr/v1/scenarioConfig/luaScript?enterprise_id=bb3xxxxxf0ad11e7bd860242ac1xxxxx&app_id=c3f3e49531xxxxxd8bbb5b247c9a8db6&scenario_id=06e25665-e4fb-xxxx-xxxx-f1622cef3d0e`

## Environment

- go version: 1.3
- gin version (or commit ref):
- operating system: macOS: 10.15.3

**Comment by thinkerou** [comment]
@KylinGu please post more info, thanks!
