### ISSUE TITLE
Does Gin support regexp in route?

### ISSUE THREAD

**Issue by sshikaree** [gin-gonic/gin#229]
`router.GET("/year/(?P<year>[0-9]*)", handler)` or even
`router.GET("/year/\\d{0,4}", handler)`
does not work. Thanks!

**Comment by jbub** [comment]
No it does not. httprouter is using a tree structure to power its routing.

You can read about it here:
https://github.com/julienschmidt/httprouter#how-does-it-work

**Comment by sshikaree** [comment]
I Get It. Thanks for the answer!

**Comment by se77en** [comment]
So how do I use regexp in router? Anyone can give me a suggestion?

**Comment by nazwa** [comment]
Create a custom noRoute (404) handler and parse the url with your custom regexp code there :)

**Comment by TheRealKira** [comment]
I would make a parameter or catch all parameter then parse it inside the router with the regexp package:

In your routing:

router.GET("/myroute/:regex",regexMyrouteHandler)

Then in the handler:

RegString := c.Param("regex")
// Parse and pass to another handler based on match

**Comment by se77en** [comment]
@nazwa @TheRealKira both big thx~

**Comment by TheRealKira** [comment]
@se77en here's a better example I was responding from my phone before.
```go
//Route
r.GET("/users/:regex",UserHandler)
...
 //Import regexp wherever your UserHandler function is
import "regexp"
...
func UserHandler(c *gin.Context) {
	//Compile valid regular expression
	r, err := regexp.Compile(`[a-zA-Z0-9]`)
	if err != nil {
	   panic(err)
	   return
	}
	username := c.Param("regex")
	if r.MatchString(username) == true {
		//Param matches your regex
		c.JSON(200,gin.H{"match":"true"})
	} else {
		//Write error header and body no match
		c.JSON(400,gin.H{"match":"false"})
	}
}
```

**Comment by se77en** [comment]
@TheRealKira Thank you very very much!

**Comment by Tom29** [comment]
@TheRealKira the trouble is we can't use it in root router like this:
`r.GET("/:any", Handler)`
