### ISSUE TITLE
New behavior of r.Run binds to localhost, not 0.0.0.0, issues in Docker

### ISSUE THREAD

**Issue by DarthHater** [gin-gonic/gin#2292]
## Description

Hi! In gin `1.6.0` it appears starting a default gin instance will now bind to:

localhost:8080

Instead of previously it would bind to just :8080 (0.0.0.0)

This causes issues when used inside of Docker as it is binding to Docker's localhost rather than 0.0.0.0

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run()
}
```

More or less the example above should show gin starting on `localhost:8080` rather than `:8080` like in gin 1.5.0

## Expectations

The expectation is by default, gin should bind the way it previously did

A project that is setup to show this:

https://github.com/DarthHater/hello-world/tree/TestBranch

If you clone that repo, and run `docker-compose up`, you should see the project start on `:8080` as it is using gin 1.5.0, if you switch the go.mod to use gin 1.6.0, you'll see `localhost:8080`, and if you attempt to hit:

`http://locahost:8080/ping`

You'll see empty response, as although Docker has exposed 8080, it's not making it through to the host application since it is bound to Docker's `localhost` rather than the machines `0.0.0.0`

Let me know if there are any questions! I was teaching some friends how to use gin, etc... and ran into this while doing so.

**Comment by appleboy** [comment]
ref: #2216

**Comment by appleboy** [comment]
ping @keob Any thoughts about this?

**Comment by keob** [comment]
Sorry.If you use 0.0.0.0 on windows or mac os it will trigger a firewall block.

**Comment by appleboy** [comment]
@keob maybe you should pass the `localhost:8080` as parameter not change the default behavior in v1.5 version.

**Comment by keob** [comment]
@DarthHater  In the archlinux i can run it.

**Comment by keob** [comment]
user r.Run()

**Comment by keob** [comment]
![Screenshot_20200323_140350](https://user-images.githubusercontent.com/25259671/77286887-3b985f00-6d0f-11ea-9787-fba2e6f83163.png)

**Comment by appleboy** [comment]
@keob In my Linux server, I can reproduce this critical issue.

```go
package main

import "github.com/gin-gonic/gin"

func main() {
        r := gin.Default()
        r.GET("/ping", func(c *gin.Context) {
                c.JSON(200, gin.H{
                        "message": "pong",
                })
        })
        r.Run()
}
```

Write Dockerfile and build as below:

```
docker run -p 8081:8080 appleboy/line-login
```

Can't connect to the server.

**Comment by keob** [comment]
@appleboy Can you run it?

**Comment by appleboy** [comment]
I will bump new version `v1.6.1` to fix this issue today.

**Comment by keob** [comment]
I can run it localhost or 0.0.0.0 is ok

**Comment by appleboy** [comment]
@keob Can you post steps?

**Comment by keob** [comment]
DarthHater's demo i can run it,your demo i don't run it

**Comment by keob** [comment]
@appleboy

**Comment by appleboy** [comment]
@keob Please update gin to v1.6.0 version and try it again.

**Comment by keob** [comment]
@appleboy  I use 1.6.0 run the DarthHater's demo

**Comment by keob** [comment]
@appleboy I use your demo and gin v1.6.0 and user docker run --network -host can run it,but my pc 8080 port use it.I change port to r.Run(":9090").

**Comment by appleboy** [comment]
@keob You can't use the `--network host` mode.

**Comment by keob** [comment]
@appleboy not use --network host is run

**Comment by keob** [comment]
But i use 9090,docker proxy process running at 8080,so i change to 9090;

**Comment by keob** [comment]
@aadidenko

**Comment by appleboy** [comment]
Can you post docker run command and show the output log?

**Comment by keob** [comment]
please wait me,I delete it

**Comment by keob** [comment]
![image](https://user-images.githubusercontent.com/25259671/77290721-b8c7d200-6d17-11ea-8c2c-e84e4512c797.png)

**Comment by appleboy** [comment]
@keob You change the default source code.

```go
package main

import "github.com/gin-gonic/gin"

func main() {
        r := gin.Default()
        r.GET("/ping", func(c *gin.Context) {
                c.JSON(200, gin.H{
                        "message": "pong",
                })
        })
        r.Run()
}
```

You can't pass any value in `r.Run()`

**Comment by keob** [comment]
cant't run it. But i don't now why DarthHater's demo can run it.🤔🤔

**Comment by keob** [comment]
Sorry I write a bug

**Comment by appleboy** [comment]
@keob His example uses gin v1.5 version.

**Comment by keob** [comment]
oh!

**Comment by appleboy** [comment]
See the new release https://github.com/gin-gonic/gin/releases/tag/v1.6.1

**Comment by DarthHater** [comment]
Wow, went to sleep and woke up to a lot of feedback! Thanks y'all!

FWIW and I should have likely added this to my report I am using:

Docker on OS X (the two people seeing this issue were using High Sierra specifically). We are using Alpine linux as the host OS, and it MIGHT be related to Docker and how it set's up a network (we are using docker-compose to orchestrate). The app itself is mostly a joke, but the behavior caught me off guard, because if others were using gin in Docker, they'd likely sit and scratch their head for a while until they trip across it.

My suggestion if the `0.0.0.0` tripped OS X and Windows firewalls would be to detect the host OS and switch it based on that. That's easy enough with `runtime.GOOS`, from my perspective.
