### ISSUE TITLE
breaking change to v1.6.0 is inappropriate

### ISSUE THREAD

**Issue by chyroc** [gin-gonic/gin#2299]
https://github.com/gin-gonic/gin/pull/1615 is a breaking change

and it is released to v1.6.0

but for go version style, it is should be released to v2.0.0 and change `go.mod` to `github.com/gin-gonic/gin/v2` (and the package name is `gin` )

please revert https://github.com/gin-gonic/gin/pull/1615 and put the `SameSite` param to v2.0.0 

thanks.

**Comment by vincegio** [comment]
Yep, I agree.
Just updated and had the same issue.. Breaks the value of semver.

**Comment by appleboy** [comment]
@thinkerou What do you think? Maybe revert the PR and add the new method to update SameSite value in a cookie?

**Comment by thinkerou** [comment]
> @thinkerou What do you think? Maybe revert the PR and add the new method to update SameSite value in a cookie?

Yes, add new method, and sign old method `deprecated`?

**Comment by appleboy** [comment]
See the PR: #2306

**Comment by appleboy** [comment]
bump to v1.6.2 https://github.com/gin-gonic/gin/releases/tag/v1.6.2
