### ISSUE TITLE
Should I overwrite gin.DefaultWriter to change gin log writer

### ISSUE THREAD

**Issue by junyicc** [gin-gonic/gin#2303]
## Description

I am using [zap logger](https://github.com/uber-go/zap) in gin framework. At the very start, when I was searching for how to use zap to log the output from gin, someone recommended using zap logger in a middleware way.

However, I find another way work for me. Here is what I do

## How to reproduce

``` go
         ... ...

        // log rotate hooker
	hook := lumberjack.Logger{
		Filename: logPath,
		MaxSize:  1024,
		MaxAge:   7,
	}

	// writers for zap logger
	fileWriter := zapcore.AddSync(&hook)
	consoleWriter := zapcore.Lock(os.Stdout)

        // set writer for gin
        gin.DefaultWriter = io.MultiWriter(fileWriter, consoleWriter)

         ... ...
```

## My question

It is simple and a little tricky, but it works. It helps me to log the output from gin.

I wonder if there exists any side effects or performance problems that I overlook.

Is it a right way to do that?

**Comment by ilya2049** [comment]
A global variable DefaultWriter used to:
1) Gin debug information output, see gin/debug.go:debugPrint.
So if you need to forward gin debug information to specific io.Writer that it is a right way.
2) Write logs in gin logger middleware, see gin/logger.go:LoggerWithConfig.
If you didn't override io.Writer in logging middleware that logging middleware will write logs in your specific default io.Writer.

Also see a comment to DefaultWriter defenition in gin/mode.go. There is an example with DefaultWriter.

I think all overhead will depend on your implementation of io.Writer.

**Comment by junyicc** [comment]
@ilya2049 Thanks for your explanations.
In dev environment, it is quick to set gin output with `gin.DefaultWriter` which is convenient to debug.
In production environment, it is better to log with middleware using `gin.RecoveryWithWriter` and `gin.LoggerWithWriter` methods.
