### ISSUE TITLE
SetCookie broken again

### ISSUE THREAD

**Issue by sguillia** [gin-gonic/gin#2308]
Hello

There has been a breaking API change again, which is undocumented

Please read https://github.com/gin-gonic/gin/issues/2214, it's the same issue

Can you update the README?

Thank you

**Comment by shlinym** [comment]
In the latest version,  `http.SameSite` had been remove from SetCookie.
And I had pull a new request to update README.md, waiting for merged.
see [PR](https://github.com/gin-gonic/gin/pull/2312)
