### ISSUE TITLE
Validator path should be GitHub version?

### ISSUE THREAD

**Issue by Hanggi** [gin-gonic/gin#2310]
After upgrading the validator, I got an error.

```
        gopkg.in/go-playground/validator.v10: gopkg.in/go-playground/validator.v10@v10.2.0: parsing go.mod:
        module declares its path as: github.com/go-playground/validator/v10
                but was required as: gopkg.in/go-playground/validator.v10
```

And fixed it by rename the path to "github.com/go-playground/validator/v10"

Which is correct?

**Comment by thinkerou** [comment]
@Hanggi how do you update/upgrade?

**Comment by Hanggi** [comment]
@thinkerou I just modified the imported package path from 'v9' to 'v10'.

**Comment by thinkerou** [comment]
v10 has updated package name https://github.com/go-playground/validator#installation
