### ISSUE TITLE
Gin context.Set() and .Get() issue

### ISSUE THREAD

**Issue by Kyocfe** [gin-gonic/gin#2317]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## How to reproduce

```go
package main

import (
	"github.com/gin-gonic/gin"
)

func setRouter() {
    group.POST("",
        RequestBodyCheck(&RequestFormat{}),
	RequestHandler)
}

// RequestHandler for business logic
func RequestHandler(ctx *gin.Context) {
    reqData, _ := ctx.Get("request_body")
    // it doesn't necessary conversion success check
    body, ok := reqData.(*CreateRequest)
    if !ok {
        ctx.Status(http.StatusBadRequest)
        return
    }

    log.Println(body)
}

// RequestBodyCheck this handler is validation check for request body
func RequestBodyCheck(reqData interface{}) gin.HandlerFunc {
    return func(c *gin.Context) {
		// request body marshaling and validation check
		clear(reqData)
		body, _ := ioutil.ReadAll(c.Request.Body)
		marshal, err := reqBodyCheck(body, reqData)
		if err != nil {
			c.String(http.StatusBadRequest, "error occurred")
			return
		}
		log.Printf("Request Body : %s", body)
		c.Set("request_body", marshal)
		c.Next()
	}
}

func reqBodyCheck(body []byte, inter interface{}) (interface{}, error) {
	if err := json.Unmarshal(body, inter); err != nil {
		return nil, err
	}
	return inter, nil
}
```

## Expectations
Hi.
I am currently developing api with gin.
However, I have an issue and I inquire.
I am using a handler chain to validate the format for routers with a request body. Among them, if the format is valid, I try to store the requested data in the context using the c.Set ('') function and have the next handler use it. If this is a concurrent request, the data seems to be handled incorrectly. Am I using it wrong?

If you make a request to the router at the same time, there are seems to be a problem when overwriting other data.

Is there a problem in gin context's Set () and Get () functions in a concurrent request?

## Environment

- go version: 1.12
- gin version (or commit ref): v1.5.0
- operating system: ubuntu 16.04

**Comment by shlinym** [comment]
you set `c.Set("request_body", marshal)`, 
but get `reqData, _ := ctx.Get("req_body")`,
two key is not same, you cant' get valid value.

**Comment by Kyocfe** [comment]
i'm sorry that is a type.
key names are same.
request_body

**Comment by appleboy** [comment]
@Kyocfe Please try the v1.6.2 version to fix the issue.

**Comment by Kyocfe** [comment]
thank you for the answer.
but still not working..

**Comment by yeqown** [comment]
@Kyocfe it lookss like all handlers use the same variable `&RequestFormat{}` in your middleware `RequestBodyCheck`, try to use a new var in your middleware, if you can not assgin a sure type, may be you can pass a `pool` interface{}.

**Comment by Kyocfe** [comment]
@yeqown thank you for the answer
i will try this :)

**Comment by lmurature** [comment]
Hi @Kyocfe i'm currently having the same issue: a value is set and when i try to overwrite it and read, it gives me the old value for some reason.

Could you solve it?
