### ISSUE TITLE
undefined: sync.Pool

### ISSUE THREAD

**Issue by lgs** [gin-gonic/gin#234]
First time trying and I get the following err.:

<pre>
lsoave@basenode:~$  go get github.com/gin-gonic/gin
# github.com/gin-gonic/gin
go/src/github.com/gin-gonic/gin/gin.go:34: undefined: sync.Pool
</pre>

<pre>
lsoave@basenode:~/test$ go version
go version go1.2 linux/amd64
</pre>

**Comment by javierprovecho** [comment]
Hello,




Are you using Go 1.2?




Gin is only compatible with Go 1.3 and up.



—
Enviado desde Mailbox

**Comment by lgs** [comment]
@javierprovecho  thanks Javier, upgrading Golang it works



<pre>
lsoave@basenode:~$ go version
go version go1.4.1 linux/amd64

lsoave@basenode:~/test$ go get github.com/gin-gonic/gin

lsoave@basenode:~/test$ go run test.go
[GIN-debug] GET   /                         --> main.func·001 (3 handlers)
[GIN-debug] GET   /ping                     --> main.func·002 (3 handlers)
[GIN-debug] POST  /submit                   --> main.func·003 (3 handlers)
[GIN-debug] PUT   /error                    --> main.func·004 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2015/03/06 - 21:21:35 | 200 |     16.021µs | 127.0.0.1:32969 |   GET     /
[GIN] 2015/03/06 - 21:21:35 | 404 |        181ns | 127.0.0.1:32969 |   GET     /favicon.ico
[GIN] 2015/03/06 - 21:21:37 | 200 |     12.165µs | 127.0.0.1:32969 |   GET     /
</pre>
