### ISSUE TITLE
Change Timezone of Gin Application

### ISSUE THREAD

**Issue by ShubhamRathi** [gin-gonic/gin#2343]
I want my Gin application to run on a different timezone (Asia/Jakarta, UTC +7) and not take the system timezone. How do I do this?

**Comment by maxatome** [comment]
`env TZ=Asia/Jakarta /path/to/your/app` ?

**Comment by appleboy** [comment]
See the [answer](https://stackoverflow.com/a/54364082/998718)

```go
package tzinit

import (
    "os"
)

func init() {
    os.Setenv("TZ", "Africa/Cairo")
}
```

Import this tzinit package first thing in your main package like this:

```go
package main

import _ "path/to/tzinit"

// Your other, "regular" imports:
import (
    "fmt"
    "os"
    "time"
    ...
)
```
