### ISSUE TITLE
Any built-in way for converting form to struct in Gin

### ISSUE THREAD

**Issue by Alireza-Ta** [gin-gonic/gin#2344]
Hi there!
Is there any built-in approach to convert form values to structs like [gorilla/schema](https://github.com/gorilla/schema) or maybe use `c.Bind` method without validation that gives the same output?
Thanks!

**Comment by 2HgO** [comment]
Yes, there is. Just define a form struct tag for the field(s) in the struct with the corresponding form field names.
`
package main

import "github.com/gin-gonic/gin"

func main() {
  r := gin.Default()
  r.POST("/", postName)
  r.Run(":8080")
}

type name struct {
  Name string `form:"name"`
}

func postName(c *gin.Context) {
  var n name
  if err := c.ShouldBind(&n); err != nil {
    c.Error(err)
    c.AbortWithStatusJSON(400, gin.H{"error": "VALIDATION_ERROR"})
    return
  }
  c.JSON(200, gin.H{"data": n.Name})
}
`

making a POST request with a 
> name
form field should return a 200 with the name that was sent in the response.

**Comment by Alireza-Ta** [comment]
I'm familiar with what you represented but still `c.ShouldBind` validates at the end of the story!
Anyway, I figured out how to solve that problem without these things.
