### ISSUE TITLE
There is bug that form:",default=1", in some cases are not effective, fixed in PR #2361

### ISSUE THREAD

**Issue by iGoogle-ink** [gin-gonic/gin#2346]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

There is bug that form:",default=1", in some cases are not effective

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

type ListReq struct {
	PageNo   int `form:"page_no,default=1"`
	PageSize int `form:"page_size,default=60"`
}

func main() {
	g := gin.Default()
	g.GET("/list", func(c *gin.Context) {
		req := new(ListReq)
		if err := c.ShouldBindQuery(req); err != nil {
			c.String(400, "err:%+v", err)
			return
		}
		c.String(200, "page_no:%d,page_size:%d", req.PageNo, req.PageSize)
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:9000/list?page_no=&page_size=

page_no:1,page_size:60
```

## Actual result

```
$ curl -i http://localhost:9000/list?page_no=&page_size=

page_no:0,page_size:0
```

## Environment

- go version: 1.14.1
- gin version (or commit ref):v1.6.2
- operating system:Mac OS 15

**Comment by iGoogle-ink** [comment]
I created a pull request to fix this bug.
https://github.com/gin-gonic/gin/pull/2345

**Comment by appleboy** [comment]
How to do that if I want to set page_no as empty string, not zero?

**Comment by appleboy** [comment]
@iGoogle-ink @thinkerou What do you think?

**Comment by iGoogle-ink** [comment]
> @iGoogle-ink @thinkerou What do you think?

I think it will be strange，when http request `http://localhost:9000/list?page_no=&page_size=`，`page_no` and `page_size` = `”“`，they should be set default value.
I have tried that when http request `http://localhost:9000/list`，they can set default value

**Comment by thinkerou** [comment]
> > @iGoogle-ink @thinkerou What do you think?
> 
> I think it will be strange，when http request `http://localhost:9000/list?page_no=&page_size=`，`page_no` and `page_size` = `”“`，they should be set default value.
> I have tried that when http request `http://localhost:9000/list`，they can set default value

@iGoogle-ink If you use `page_no=&page_size=` which it mean you known it will use default value, so you should not use it. `default value` mean you don't need input `page_no=&page_size=`
