### ISSUE TITLE
Javascript encodeURIComponent does not match endpoint

### ISSUE THREAD

**Issue by rogierlommers** [gin-gonic/gin#236]
In order to learn Golang, I am building a "[read later](https://github.com/rogierlommers/readinglist-golang)" service. It uses a bookmarlet which sends an urlencoded get-request to my gin-gonic powered golang service. I'm using the endpoint below to add records (urls) to a slice. 

	r.GET("/add/:url", func(c *gin.Context) {
		url := c.Params.ByName("url")
		database = AddRecord(database, url)
		c.String(200, url)
	})

The problem is that it does not match the endpoint when the get parameter contains special characters like `%2F` (I get a 404). When I simple test `http://localhost:8080/add/test-url`, it's working fine. There must be something wrong with the encoded characters, but I can't figure out how to define the endpoint in gin-gonic which does this trick.

The bookmarklet I use is:

    javascript:location.href='http://localhost:8080/add/'+encodeURIComponent(window.location.href)

Example output is: `http://localhost:8080/add/https%3A%2F%2Fwww.reddit.com%2F`, but as mentioned above, this url does not match my /add endpoint and I can't figure out why.

Some more investigation learned that the `%2F` is causing the problem. I think this is a bug?

**Comment by rogierlommers** [comment]
Hmz, could be a bug in Golang?? http://stackoverflow.com/questions/28521723/include-2f-in-golang-http-newrequest/28523549#28523549

**Comment by manucorporat** [comment]
Sorry I missed this one. I am investigating it

**Comment by rogierlommers** [comment]
Yes, a possible workaround (`for this case`) would be to base64 the url and pass that: `javascript:location.href='http://read.lommers.org/add/'+btoa(window.location.href)`

**Comment by manucorporat** [comment]
great! but it is lame that they can not find a better solution! I close the issue
