### ISSUE TITLE
route

### ISSUE THREAD

**Issue by ganganlee** [gin-gonic/gin#2363]
product.GET("/:id",controller.GetProductById)
product.GET("/order/:id",controller.GetOrderWhitProduct)

When the two routes exist ,go build error

**Comment by DGKSK8LIFE** [comment]
> product.GET("/:id",controller.GetProductById)
> product.GET("/order/:id",controller.GetOrderWhitProduct)
> 
> When the two routes exist ,go build error

What's the build error that you get?
Have you considered the fact that you don't have a space in both `controller.`... after the commas?
Also, Are you sure that your method calls aren't incorrectly named (not the GIN ones, but the methods of controller)?

**Comment by DGKSK8LIFE** [comment]
It's probably either what I listed above, or that you just have two url ARGS with the same names.

**Comment by vishnukvmd** [comment]
Looks like it's a known limitation: https://github.com/gin-gonic/gin/issues/1681
You should instead try
```
product.GET("/:id",controller.GetProductById)
product.GET("/:id/order",controller.GetOrderWhitProduct)
```

**Comment by appleboy** [comment]
Please move to https://github.com/gin-gonic/gin/issues/1681 to discuss.
