### ISSUE TITLE
Sending field specific errors

### ISSUE THREAD

**Issue by jonathonharrell** [gin-gonic/gin#237]
The error messages in `*gin.Context.Errors` contain strings like "Required title". Is there a way to pull the field name so my API's can easily send back errors like `"errors":[ { "title":"Required" } ]` ? Hoping for a way to do it without assuming I can extract from the string with any consistency

I have something like this currently: 

```
    var response ErrorResponse
    response.Errors = make(map[string]string)
    response.Message = "Invalid request"
    for _, e := range c.Errors {
        response.Errors[e.Meta.(string)] = e.Err
    }
```

Which displays something like: `"errors":[ { "Operation aborted":"Required slug" } ]`

**Comment by appleboy** [comment]
@thinkerou yes. Thanks.
