### ISSUE TITLE
bug: /api/:code/download/  --重定向--> /api/:code/download/  

### ISSUE THREAD

**Issue by tgzl** [gin-gonic/gin#2370]
![image](https://user-images.githubusercontent.com/32809471/81548146-6f0e7600-93af-11ea-8145-a9c346846258.png)
访问的地址被重定向到原来的地址

api的定义为 api.GET("/:code/download/", HandleDownload)

解决方式是更改api为
api的定义为 api.GET("/:code/download", HandleDownload)

显然gin中的func joinPaths(absolutePath, relativePath string) string 并没有起作用
![image](https://user-images.githubusercontent.com/32809471/81548426-ddebcf00-93af-11ea-9dc7-d5b7601b6a0c.png)

**Comment by AliasT** [comment]
[好像就是这么设计的。](https://github.com/gin-gonic/gin/blob/d17270dd90c488308de3102d6951946ca0a5911f/gin.go#L59)

**Comment by thinkerou** [comment]
Yes. and please use English, thanks!
