### ISSUE TITLE
Gin response 404 with latest version (1.6.3) on Haproxy

### ISSUE THREAD

**Issue by yakuter** [gin-gonic/gin#2372]
We are using Haproxy on our server. Our gin version was **v1.4.0** end everyting was working great. However when I updated gin **v.1.6.3**, the service always responded with 404 in all routes. By the way, when I try to access directly, the responses are OK. So the problem is about Haproxy and gin v.1.6.3 I think.

Our Haproxy configuration is:
```
backend user-service
   reqrep ^([^\ ]*)\ /user(.*)     \1\ /\2
   balance roundrobin
   server manager01 127.0.0.1:8080
```
My dummy test service which responds 404 is this:
```
package main

import (
	"net/http"
	"github.com/gin-gonic/gin"
)

func main() {
	router := gin.Default()
	router.POST("/test", func(c *gin.Context) {
		name := c.Param("name")
		c.String(http.StatusOK, "Hello %s", name)
	})
	router.Run(":8080")
}
```

Should it be a bug or something in this version?

## Environment
- go version: 1.4.2
- gin version 1.6.3
- operating system: Ubuntu 18.04

**Comment by sculler** [comment]
I'm also getting 404 not found with the latest version, 1.6.3.

**Comment by appleboy** [comment]
@sculler So it is working on v1.5.x or v1.6.0? Thanks.

**Comment by sculler** [comment]
> @sculler So it is working on v1.5.x or v1.6.0? Thanks.

Yes, I downgraded to 1.5.0 and it seems to be working now.

**Comment by gavrilaf** [comment]
Have the same problem but in unit tests. After downgrading to 1.5.0 tests are passing again.

**Comment by shlinym** [comment]
@yakuter 
Is you test like this?

 `curl -X POST  http://localhost:8080/user/test`

after Haproxy, the url will be changed to `//test`, and gin response 404.

if it is, add `router.RemoveExtraSlash = true` after `gin.Default()` to solve it

In gin 1.6.0, RemoveExtraSlash is not true by default to improve performance
see more at https://github.com/gin-gonic/gin/blob/master/CHANGELOG.md#gin-v160

**Comment by yakuter** [comment]
Thank you @shlinym I tested and it worked. Thank you so much. My problem fixed now.
