### ISSUE TITLE
How to get raw request headers

### ISSUE THREAD

**Issue by ody5sey** [gin-gonic/gin#2373]
- With issues:
  

## Description

How to get raw http request headers, format like this,I want to write file

<img width="1570" alt="截屏2020-05-13 上午10 48 29" src="https://user-images.githubusercontent.com/60533474/81766000-c7588b80-9507-11ea-848f-a33eac2bb248.png">

## Environment

- go version: 1.14.2
- gin version (or commit ref): v1.6.2
- operating system: macOS

**Comment by buildscientist** [comment]
@ody5sey 

Have a look at the docs for [httputil.DumpRequestOut](https://golang.org/pkg/net/http/httputil/#DumpRequestOut). Here's a Go playground [example](https://play.golang.org/p/AfdqJFGRZqL) too.

**Comment by ody5sey** [comment]
Thank you very much, This is my solution

`
func RequestLogger() gin.HandlerFunc {
	return func(ctx *gin.Context) {
		fmt.Println(ctx.Request.Host, ctx.Request.RemoteAddr, ctx.Request.RequestURI)


		// Save a copy of this request for debugging.
		requestDump, err := httputil.DumpRequest(ctx.Request, true)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println(string(requestDump))


		ctx.Next()
	}
}
`
