### ISSUE TITLE
Headers are always written => gives a warning on hijacked connections

### ISSUE THREAD

**Issue by quetz** [gin-gonic/gin#238]
What subj says :) I have websocket handler that manages connection by itself and can't find a way to stop gin from writing headers. It happens in routergroup.go around line 60. context.Writer.WriterHeaderNow()

Is there any workaround, or maybe we need a flag like 'hijacked' in a context struct?

The warning in question is: "http: response.WriteHeader on hijacked connection"

**Comment by manucorporat** [comment]
I think this is always fixed here: https://github.com/gin-gonic/gin/commit/251b73fc70c4f75487ec827be7b0c3a3e877e11a

can you confirm?

**Comment by quetz** [comment]
Yeah, that fixes it. Thank you very much.

**Comment by mephux** [comment]
@manucorporat I think something may have been added recently to cause this again.. not a header write but a normal response.Write - anyone else having a similar issue? /cc @quetz

**Comment by quetz** [comment]
@mephux, not using Gin nowadays. Moved over to https://github.com/carbocation/interpose and http://www.gorillatoolkit.org/pkg/mux

**Comment by mephux** [comment]
@quetz ah, ok.

For anyone coming to this threat I found the problem - was an issue with the gzip middleware. (https://github.com/gin-gonic/contrib/pull/71)
