### ISSUE TITLE
the same port with nginx, not panic

### ISSUE THREAD

**Issue by ipv4sec** [gin-gonic/gin#2382]
the same port with nginx, not panic

## Description

my nginx conf:

```
server {
    listen       4000;
    server_name  localhost;
    location ~  {
        proxy_pass   http://127.0.0.1:3000;
    }
  }
```

and my code is
```
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	err := r.Run(":4000")
	if err != nil {
		panic(err)
	}
}
```
my nginx is runing used 4000, then run code with use 4000, why not panic ?

## Environment

- go version go1.14.2 darwin/amd64
- nginx version: nginx/1.17.10  (brew install nginx) 
- operating system: mac 10.15.4

**Comment by taiidani** [comment]
I'm not sure I'm entirely understanding the question here. Are you wanting Gin to panic if it publishes a port that Nginx is not configured to forward to?

As Nginx is upstream of Gin and attempting to send connections to it, Gin will not be able to observe those missed requests.

**Comment by ipv4sec** [comment]
I tried again. 
The problem is operating system: mac 10.15.4 
I used centos7.7 : `panic: listen tcp :4000: bind: address already in use`

**Comment by taiidani** [comment]
🤔 Well yes, if running on the same machine then Nginx and Gin won't be able to listen on the same port.

It looks like your Nginx is configured to talk to Gin on port 3000. If your goal here is to avoid the panic, can you modify your Go code to use port 3000 instead of 4000?

```diff
-	err := r.Run(":4000")
+	err := r.Run(":3000")
```

**Comment by ipv4sec** [comment]
No. 

the code `proxy_pass   http://127.0.0.1:3000` is unimportant

if my nginx conf:
```
server {
    listen       4000;
    server_name  localhost;

    location / {
        root   /tmp/;
        autoindex on;
    }
  }
```


mac os run:
```
➜  ~ lsof -i:4000
➜  ~ brew services start nginx
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)
➜  ~ lsof -i:4000             
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
nginx   84205 Loli    6u  IPv4 0x8bc741c02eaa89bd      0t0  TCP *:terabase (LISTEN)
nginx   84215 Loli    6u  IPv4 0x8bc741c02eaa89bd      0t0  TCP *:terabase (LISTEN)
```

then `go run main.go`:
```
➜  ~ lsof -i:4000
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
nginx     84205 Loli    6u  IPv4 0x8bc741c02eaa89bd      0t0  TCP *:terabase (LISTEN)
nginx     84215 Loli    6u  IPv4 0x8bc741c02eaa89bd      0t0  TCP *:terabase (LISTEN)
go_build_ 84810 Loli   10u  IPv6 0x8bc741c04a96f7ed      0t0  TCP *:terabase (LISTEN)
```

then i open chrome on 127.0.0.1:4000 show me the files on `/tmp/` and code not panic

then:
```
➜  ~ brew services stop nginx                        
Stopping `nginx`... (might take a while)
==> Successfully stopped `nginx` (label: homebrew.mxcl.nginx)
➜  ~ lsof -i:4000            
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
go_build_ 84810 Loli   10u  IPv6 0x8bc741c04a96f7ed      0t0  TCP *:terabase (LISTEN)
```

 then i open chrome on 127.0.0.1:4000/ping show me the code `"message": "pong"`


but when test on linux, the code is panic

so this bug is `mac 10.15.4`

**Comment by buildscientist** [comment]
@taiidani I think @ipv4sec is saying that on macOS gin.gonic services can bind to a port that has already been bound to. 

Either way though this isn't an gin.gonic issue. Port binding is OS level functionality so if macOS isn't correctly handling this there's not much gin.gonic can do about it.

**Comment by ipv4sec** [comment]
@buildscientist  @taiidani  

Aha. I found 
https://stackoverflow.com/questions/13726975/why-does-os-x-allow-listening-on-the-same-tcp-port-twice

so this question is `SO_REUSEPORT`

**Comment by buildscientist** [comment]
@ipv4sec 

That sounds correct but again I ask - what does this have to do with Gin? Gin doesn't handle low level/raw sockets - all of that is done by the net/http package internal to Go.

**Comment by ipv4sec** [comment]
Yes, you're right. I'm wrong. I didn't think about `Mac OS ` before, thank you very much
