### ISSUE TITLE
hi windows console also need color 

### ISSUE THREAD

**Issue by godtoy** [gin-gonic/gin#2383]
## Description
on windows console log have not color just print
```
[GIN] 2020/05/19 - 15:46:43 |?[97;42m 200 ?[0m|      1.9264ms | xxx |?[97;44m
```

and i use this lib to fix color print
```
github.com/shiena/ansicolor
```
maybe need  official  to solve it

**Comment by lyj0309** [comment]
same question 
when i use cmd or powershell 
![image](https://user-images.githubusercontent.com/50474995/82442153-ae387780-9ad1-11ea-8fe0-b4e99f01cdf5.png)

when i use bash 
![image](https://user-images.githubusercontent.com/50474995/82442067-8cd78b80-9ad1-11ea-87fd-63cda7d13a62.png)

**Comment by darkvertex** [comment]
Import `github.com/mattn/go-colorable` then do:
```
if runtime.GOOS == "windows" {
	gin.DefaultWriter = colorable.NewColorableStdout()
}
```

---
FYI this tip is hidden in the sourcecode:
https://github.com/gin-gonic/gin/blob/54175dbe72289b7524b53a0afd2e5bddfa7b6efc/mode.go#L36-L38
