### ISSUE TITLE
Bind function's request param question

### ISSUE THREAD

**Issue by ufwfqpdgv** [gin-gonic/gin#2384]
OldCommentStatus CommentStatusCode `form:"old_comment_status,default=-1" json:"old_comment_status,default=-1"` // form's default work but json's default do't work！！！

**Comment by AliasT** [comment]
#1928 #1052

**Comment by thinkerou** [comment]
@ufwfqpdgv yes

**Comment by kamly** [comment]
@ufwfqpdgv  have any good way?
