### ISSUE TITLE
Handling error like Java's Lombok @BadRequest @InternalError before compiling.

### ISSUE THREAD

**Issue by lz1998** [gin-gonic/gin#2392]
## Description
Error in golang is very annoying.
Is it possible to develop a solution to deal with error elegantly like Java's Lombok in GIN?
Maybe read comments in code and generate "if err!=nil......" before compiling.

## Example
Before compiling
**CONVERT**
```golang
    // @BadRequest
    err := c.ShouldBindJSON(&req)
```
**TO**
```golang
    err := c.ShouldBindJSON(&req)
    if err!=nil{
        // Bad request response
        return
    }
```

**Comment by lz1998** [comment]
Is there some IDE's plugins or other tools can do this?
As I known, CGO can read comments.

**Comment by buildscientist** [comment]
@lz1998 

I believe the error check/conditional you've referenced is considered idiomatic go.  Depending on your IDE you could also use an IDE template engine to replace strings like `err := c.ShouldBindJSON(&req)`

For example [GoLand](https://www.jetbrains.com/go/) has a feature called [live templates](https://www.jetbrains.com/help/go/using-live-templates.html) that implements this.
