### ISSUE TITLE
Important performance improvement

### ISSUE THREAD

**Issue by manucorporat** [gin-gonic/gin#24]
I just tested a new system to reduce the allocation and garbage collection overhead.

Some benchmarks:

Current (old) system:

```
BenchmarkGin_Param   5000000           340 ns/op         161 B/op          2 allocs/op
BenchmarkGin_Param5  5000000           537 ns/op         290 B/op          2 allocs/op
BenchmarkGin_Param20     1000000          1278 ns/op         774 B/op          2 allocs/op
BenchmarkGin_ParamWrite  5000000           384 ns/op         161 B/op          2 allocs/op
BenchmarkGin_GithubStatic   10000000           239 ns/op         128 B/op          1 allocs/op
```

New system:

```
BenchmarkGin_Param  10000000           249 ns/op          33 B/op          1 allocs/op
BenchmarkGin_Param5  5000000           442 ns/op         162 B/op          1 allocs/op
BenchmarkGin_Param20     1000000          1102 ns/op         646 B/op          1 allocs/op
BenchmarkGin_ParamWrite  5000000           319 ns/op          33 B/op          1 allocs/op
BenchmarkGin_GithubStatic   10000000           167 ns/op           0 B/op          0 allocs/op
```

But this is even better.
- It also reduces drastically the garbage collection stress in a full-loaded system.
- This system allows the community to extend the `gin.Context` (adding more static variables etc...) without degrading the performance
- The implementation is still hacky, the performance can be even better once we make this system CPU cache friendly

**Comment by imzye** [comment]
@manucorporat 
I run the example and see the following error.

log.Println("Done! in path " + cCp.Request.URL.Path)
