### ISSUE TITLE
Go 1.14

### ISSUE THREAD

**Issue by m8as** [gin-gonic/gin#2400]
Hello! When are you planning to change go version from 1.13 to 1.14?
Thank you!

**Comment by thinkerou** [comment]
@m8as what's mean? gin support go1.11+ please see https://github.com/gin-gonic/gin#installation

**Comment by m8as** [comment]
@thinkerou, i mean golang version in go.mod

**Comment by thinkerou** [comment]
it only identify. use go1.14 the same as go1.13

**Comment by m8as** [comment]
Okey, thank you
