### ISSUE TITLE
Templates overwriting each other

### ISSUE THREAD

**Issue by kjda** [gin-gonic/gin#241]
if you have the following templates

templates/index.tmpl
templates/group/index.tmpl

`r.LoadHTMLGlob("templates / ** / *.tmpl")`  will cause the root index.tmpl to be overwritten by group/index.tmpl

this means all your template file names must be globally unique! which looks like a bug

also the following will not work
```go
c.HTML(http.StatusOK, "group/index.tmpl",..)
```

**Comment by roosmaa** [comment]
That's how [html/template](http://godoc.org/html/template) package works. If you really want you can manually load the templates (by replicating [parseFiles](https://golang.org/src/html/template/template.go#L326) functionality) and passing them to [SetHTMLTemplate](http://godoc.org/github.com/gin-gonic/gin#Engine.SetHTMLTemplate) function.

I vaguely remember doing something similar several years ago. Back then I think it was more trouble than it was worth - some things had problem functioning correctly with template names like that. But it was ages ago, so those problems might not exist anymore.

Though the easiest option by far is just flattening your template directory (ie `group/index.tmpl` :arrow_forward: `group-index.tmpl`).

**Comment by manucorporat** [comment]
@kjda @roosmaa I think we can close this issue :)
