### ISSUE TITLE
(Question) how can i get value of context JSON from previous handler chain?

### ISSUE THREAD

**Issue by leeyjeen** [gin-gonic/gin#2411]
- in router
```
r.GET("/api/call",
		auth.LoginHandler,
		TokenParsing)
```

- handler chain: 
TokenParsing after LoginHandler 

```
func (mw *GinJWTMiddleware) LoginHandler(c *gin.Context) {
	/*
		...
	*/
			c.JSON(http.StatusOK, gin.H{
				"code":   http.StatusOK,
				"token":  token,
				"expire": expire.Format(time.RFC3339),
			})
}
```

```
func TokenParsing(c *gin.Context) {
	/*
		In here, is there a way to get 'token' value from login handler?
	*/
}
```
In TokenParsing handler, how can i get 'token' value from login handler? 
If anyone knows this, please let me know.. thank you

**Comment by bestgopher** [comment]
You should use `c.Set("token", token)`

**Comment by leeyjeen** [comment]
euh.. I was just stupid ... I knew that but I forgot I could customize mw.LoginResponse so I was excluding that..
Thanks to you, I came up with the idea that I can customize mw.LoginResponse and solved it by adding c.Set("token", token). 
Thank you xD
