### ISSUE TITLE
How to bind a domain name and serve only on domain not on ip?

### ISSUE THREAD

**Issue by xin344** [gin-gonic/gin#2435]
## Description

Hi, I would like gin serve only on a domain name not on ip or localhost, is there a way to do this? Thank you!

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run("www.domain_name.com:80")
}
```

## Expectations

```
Visit "http://www.domain_name.com" to show my index page,
ban "http://127.0.0.1" and "http://localhost" visiting.
```

## Actual result

```
I can visit either "http://www.domain_name.com", "http://127.0.0.1" or "http://localhost" to show my index page.
```

## Environment

- go version: 1.14.4
- gin version (or commit ref): latest 20200713
- operating system: Windows 10

**Comment by ap-in-git** [comment]
You can setup nginx and do reverse proxy if you like to listen from ip

**Comment by xin344** [comment]
OK, thank you a lot!
