### ISSUE TITLE
How do you return an object/model?

### ISSUE THREAD

**Issue by vbisbest** [gin-gonic/gin#2446]
I see in the examples how you return marshaled data.  For instance:

	c.JSON(http.StatusOK, gin.H{
		"code": 200,
		"msg":  "",
		"data": string(MYJSON),
	})

However this wraps the json into the data node.  I want to return my struct as a top level node.   I also see this example:
c.String(http.StatusOK, string(json))

However this I believe messes with the encoding as a straight string.  

I simply want to return my mode/object as json and not wrapped in a sub node.  Thank you.

**Comment by KaffineAddict** [comment]
You can simply call c.JSON with the second argument being and interface. For example

```
o := &Model{}
c.JSON(http.StatusOK, o)
```

**Comment by BoynChan** [comment]
Accutaly, gin.H is a alias of map[string]interface{}, you can just use c.JSON(200,${model}) and gin framework will do serialization work for this method

**Comment by vbisbest** [comment]
Thank you all, this was what I was looking for.
