### ISSUE TITLE
Unit Test effort

### ISSUE THREAD

**Issue by manucorporat** [gin-gonic/gin#246]
I have started an effort to increase the coverage of unit tests to 100%, in order to make Gin a production ready framework. If anyone is interested to help, please contact me so we can coordinate.

Thanks!
Stay tuned!

**Comment by tadeumaia** [comment]
Manu, I would like to help this on this effort. Will be a nice way to learn the framework as we are starting a new go project here and we're thinking about using Gin in a production env.

**Comment by kmulvey** [comment]
as would I

**Comment by TheDodd** [comment]
Let's do this.

**Comment by netroby** [comment]
How to add tests for gin powered project? would you please show us some example? i can not find tests in examples gin provided us.
