### ISSUE TITLE
Can not combine validators to make check for positive int work

### ISSUE THREAD

**Issue by andreyrusanov** [gin-gonic/gin#2469]
Description

Unable to make binding for positive int check work

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)


type PaginationQuery struct {
	Limit int `form:"limit" binding:"numeric,gte=0"`
	StartFrom int `form:"start_from" binding:"numeric,gte=0"`
}

func View (c *gin.Context) {
query := new(PaginationQuery)

if err := c.ShouldBindQuery(&query); err != nil {
	c.JSON(
		http.StatusUnprocessableEntity,
	 	BuildErrorResponse(err))  // returns custom error message and 422 code
	return
	}
}
.....
```

## Expectations

```
$ curl http://localhost:8201/hello/world?limit=-1
> 422 failed because of tag gte=0

$ curl http://localhost:8201/hello/world?limit=qwert
> 422 failed because of tag numeric
```

## Actual result
It works only gte=0 part but not for numeric part. When I try to pass non-digit value,  it fails with strconv.ParseInt error

## Environment

- go version: 1.14
- gin version (or commit ref): 1.6.3
- operating system: Ubuntu 16.04

**Comment by 2HgO** [comment]
This is the expected behaviour.

1. I do not know what you think the `binding` tags does but it is used to perform field validations after the values have been unmarshalled into the struct fields.
2. The type of the `limit` field is `int` so a non numeric string value cannot be unmarshalled into it. That is why a `strconv.ParseInt` error is returned by your request. Similarly, a `*json.UnmarshalTypeError` error would be returned if you were binding as JSON.
3. The numeric validator tag is used to validate that a string value contains a basic numeric value.

**Comment by andreyrusanov** [comment]
Thank you for the explanation. However, if I change data types to strings it also doesn't work in combination (perhaps it can't apply gte on string field?). 
So I am wondering is it ever possible to do without writing custom validator (for string field).

**Comment by 2HgO** [comment]
Yes, `gte` acts differently with number type fields (compares if the value is greater than or equal to the specified gte= value) and string type field (compares if the length of the string is greater than or equal to the specified gte= value). So you won't be able to use both together to achieve your desired goal. Is there a reason you can't use the `strconv.ParseInt` error?

If you still want to go ahead with validating that the string is a valid integer, you could try using `form:"limit,default=0" binding:"numeric,excludesall=-."`

**Comment by andreyrusanov** [comment]
Ah Ok, thank you for answer. I recently started with Gin and was curious how to do it in "idiomatic" way, because I supposed type check has to be a part of validation process with proper error returned.
