### ISSUE TITLE
Reroute incoming request based on their path

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [gin-gonic/gin#2470]
Is it possible to re-route an incoming request ? 
I have legacy routes I need to support, and I was wondering if I can add something like a middleware that checks if a given route starts with some prefix and them move it to a different route..

```go
        router := gin.New()
	router.Use(LegacyRouter())

	router.Use(gin.Recovery())
	systemRouter := router.Group("/") 
	noAuthRouter := router.Group("/"
	authRouter := router.Group("/") 
```

so in `LegacyRouter()`
i have this 

```go
func LegacyRouter() gin.HandlerFunc {
	return func(c *gin.Context) {
		pathParts := strings.Split(c.Request.URL.Path,"/")
		RemoveEmpty(&pathParts)
		if len(pathParts) > 0{
			if strings.EqualFold(pathParts[0], "legacyPrefix"){
				if len(pathParts) >= 5 {
					service := pathParts[2]
					action := pathParts[4]
					log.Printf("service: %s action: %s", service, action)
					c.Request.URL.Path = "/"+action
				}
			}
		}
		c.Next()
	}
}
```

I thought that if I change the request path then gin router will hop to the relevant gorup like `authRouter := router.Group("/")`

but it does't :\

any way to tell the router to move to a different route base on url path ?

**Comment by unbyte** [comment]
```go
r.GET("/test", func(c *gin.Context) {
    c.Request.URL.Path = "/test2"
    r.HandleContext(c)
})
r.GET("/test2", func(c *gin.Context) {
    c.JSON(200, gin.H{"hello": "world"})
})
```
see https://github.com/gin-gonic/gin#redirects

**Comment by arthurvaverko-kaltura** [comment]
OMG.. thanks .. I read this exact section .. and seems like its so important to read until the end :) .. 
I read the http redirect response and dropped the read... the actual answer was right there after ...
again, thanks,
