### ISSUE TITLE
Context.Engine  应该为 Context.engine

### ISSUE THREAD

**Issue by 420303865** [gin-gonic/gin#248]
Context.Engine 应该为不可导出的 以避免出现以下代码

Edit by @manucorporat:
Context.Engine Should not be exported to avoid the following code:

```go
package main

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

func main() {
	router := gin.Default()
	router.GET("/", func(c *gin.Context) {
		c.Engine.GET("/ping", func(c *gin.Context) { // Should not be
			c.String(http.StatusOK, "pong")
		})
	})

	router.Run(":8090")
}
```

**Comment by manucorporat** [comment]
Can you explain the issue in English? otherwise this issue will be closed.

**Comment by 420303865** [comment]
just like v0.1 the Context.Engine is not exported.
it is not necessary.

**Comment by techjanitor** [comment]
I do not agree with this. Having access to Engine from Context is very useful, specifically for HTML templates. I keep my route handlers in a separate package. 

```
        tmpl := template.Must(template.ParseFiles("main.tmpl", "index.tmpl"))

        c.Engine.HTMLRender = render.HTMLRender{
                Template: tmpl,
        }

        c.HTML(200, "base", m.Result)
```

**Comment by 420303865** [comment]
@techjanitor 

the gin provides a SetHTMLTemplate method
in your case
there is an [example](https://github.com/gin-gonic/gin/#html-rendering)

```go
import "html/template"

func main() {
    r := gin.Default()
    r.GET("/", func(c *gin.Context) {
        tmpl := template.Must(template.ParseFiles("main.tmpl", "index.tmpl"))
        r.SetHTMLTemplate(tmpl)
        c.HTML(200, "base", data)
   })
   r.Run(":8080")
}
```

**Comment by manucorporat** [comment]
@techjanitor @420303865 this is a tricky issue. I don't remember why I made context.Engine an exported variable.

@techjanitor you code may looks good, but that is SOO unsafe. you are modifying a global variable inside a request. If your app is configured with `GOMAXPROCS` > 0, then:

```go
        tmpl := template.Must(template.ParseFiles("main.tmpl", "index.tmpl"))

        c.Engine.HTMLRender = render.HTMLRender{
                Template: tmpl,
        }
        // <<< here another request in a different thread could modify c.Engine.HTMLRender
        // even worse, two threads could modify the variable at the same time. and you get a race condition.
        c.HTML(200, "base", m.Result)
```

router.HTMLRender should be initialised at the beginning otherwise you should use `c.Render` directly.

```go
tmpl := template.Must(template.ParseFiles("main.tmpl", "index.tmpl"))
c.Render(200, render.HTML{
    Template: tmpl,
    Name: main.templ,
    Data: yourData,
})
```

or use the template directly:

```go
tmpl := template.Must(template.ParseFiles("main.tmpl", "index.tmpl"))
c.Header("Content-Type", "text/html; charset=utf-8")
tmpl.ExecuteTemplate(c.Writer, "main.tmpl", yourData)
```

**Comment by techjanitor** [comment]
Ahh interesting, thanks for the info. I didn't think about using c.Render. That might be a good example to put in the readme.

**Comment by manucorporat** [comment]
yeah! I may rename `c.Engine` to `c.engine`, it is very error-prone.

Question you @techjanitor: why do you try to load the template in each request? I assume it is a very expensive operation.

**Comment by techjanitor** [comment]
Because i'm a bad programmer ;D

**Comment by YamiOdymel** [comment]
Annnnnd... I have no idea how do I get the `RouteInfo` since I cannot access the `engine` from the handler.

**Comment by bbiao** [comment]
Want to get the RoutesInfo from a handler, any idea?

**Comment by thinkerou** [comment]
@bbiao https://github.com/gin-gonic/gin/blob/master/gin.go#L263

**Comment by bbiao** [comment]
> @bbiao https://github.com/gin-gonic/gin/blob/master/gin.go#L263

thanks @thinkerou 
Before ask I have read the code.
What I mean it that I can't get the gin.Engine from the gin.Context, and so I can't call the RoutesInfo method.

**Comment by 420303865** [comment]
@bbiao 
```go
func (h *handler) Test(c *gin.Context) {
	routeInfo := gin.RouteInfo{
		Method:      c.Request.Method,
		Path:        c.FullPath(),
		Handler:     c.HandlerName(),
		HandlerFunc: c.Handler(),
	}
	c.String(http.StatusOK, routeInfo.Handler)
}
```

**Comment by 420303865** [comment]
@bbiao 
or you need

**Comment by 420303865** [comment]
@bbiao 
or https://github.com/gin-gonic/gin#redirects

**Comment by bbiao** [comment]
> @bbiao
> 
> ```go
> func (h *handler) Test(c *gin.Context) {
> 	routeInfo := gin.RouteInfo{
> 		Method:      c.Request.Method,
> 		Path:        c.FullPath(),
> 		Handler:     c.HandlerName(),
> 		HandlerFunc: c.Handler(),
> 	}
> 	c.String(http.StatusOK, routeInfo.Handler)
> }
> ```

Thanks, I have already resolved my problem by using the lastest code and the gin.Context.FullPath() method.
