### ISSUE TITLE
[pr] Profile Context.Error(err error)*Error, better performance when err is nil

### ISSUE THREAD

**Issue by fwhezfwhez** [gin-gonic/gin#2480]
Hello, When `c.Error(e)` is called if e is nil, it will panic.

This pull request is to support `c.Error(nil)`

**Comment by p3ym4n** [comment]
any new ideas about this?
it's hard to always ignore the return value of the `c.Error()`, I was thinking that maybe it's just fine to use the `c.Errors` when we want it.
also maybe just a simple check to ignore the nil error it's a lot better than panic.

**Comment by fwhezfwhez** [comment]
If e is nil, c.Error should not be called maybe.
