### ISSUE TITLE
[question] How to execute code with context regardless of path?

### ISSUE THREAD

**Issue by CaptainZidgel** [gin-gonic/gin#2496]
I would like to know how I can execute code with context. I need the context so I can read Sessions. I'd like to do that without writing code for getting sessions every route.

To clarify, I am using an external [library](https://pkg.go.dev/github.com/gin-contrib/sessions?tab=doc) to manage sessions. Context is required to get a session. If I am trying to extract user information from that session, I do not want to have to do it on every GET route. I would like to call this code once and let every path beneath that inherit the User information. (I do not want to call a function on every route either, not that that would be feasible in my case anyway).
My first thought was router.Group(), but that does not provide context, and as far as I assume, does not actually execute code until a path is used.

I understand this is a tricky question as context is intrinsically dependent on specific HTTP requests. Any help would be appreciated.

**Comment by mingzaily** [comment]
Try [goframe](https://github.com/gogf/gf).You'll like it.

**Comment by CaptainZidgel** [comment]
I've figured out what to do in gin.
The documentation does not do a good job of introducing users to concepts that might be new to them (it only includes examples with little commentary), but this is what the often-mentioned-rarely-explained middleware is for.

Define a function like this:
```
func MiddlewareName() gin.HandlerFunc {
	return func(c *gin.Context) {
    }
}
```

You can then apply this with .Use to the gin engine (as I do) or also to Routing .Group s as docs show
```
g := gin.Default()
g.Use(MiddlewareName()) //you can also include a parameter for this function if you wanted to pass some information from the main function to the middleware, which I do with database info
```

Inside the Middleware Function, you can set variables
```
c.Set("varName", value)
```

Then you can get it inside a routing handler.
```
g.GET("/", func(c *gin.Context) {
    varName, exists := c.Get("varName")
    ...
```
This is not as simple as I would like it, where one could simply inherit a value just by being the handler, but I don't think that's even possible with Go. Regardless, 1 statement is a massive improvement over what I had to do before.
