### ISSUE TITLE
Too many handlers error

### ISSUE THREAD

**Issue by michaeldebarros** [gin-gonic/gin#2497]
I am getting this error: (*RouterGroup).combineHandlers: panic("too many handlers")

I found the code for the panic:
`func (group *RouterGroup) combineHandlers(handlers HandlersChain) HandlersChain {
	finalSize := len(group.Handlers) + len(handlers)
	if finalSize >= int(abortIndex) {
		panic("too many handlers")
	}
	mergedHandlers := make(HandlersChain, finalSize)
	copy(mergedHandlers, group.Handlers)
	copy(mergedHandlers[len(group.Handlers):], handlers)
	return mergedHandlers
}`

Where **abortIndex ** is: `const abortIndex int8 = math.MaxInt8 / 2`.

First I don`t really understand this index, must be some kind of safety.

But the fact is that I have only 33 handlers (plus the static assets)  and I am getting this error.

When I restart the server the error goes away. But it comes back after a while.

Am I missing something?

**Comment by athe0i** [comment]
@michaeldebarros Hello. Do you have any example to reproduce this? From this part `When I restart the server the error goes away. But it comes back after a while.` - it feels like at some point your handlers are added to the handlers chain at least one more time, which then goes up to 66 handlers and exceeds abortIndex(which is like 64). 
Newbie here, sorry if it doesn't make a lot of sense :blush:

**Comment by michaeldebarros** [comment]
Hello, @athe0i . Thanks for the reply.  

"it feels like at some point your handlers are added to the handlers chain at least one more time". I thought about it also, but can't figure out where. Will look into it.

But still, seems to me that `abortIndex` is too low, event for a small to medium size app.

**Comment by athe0i** [comment]
@michaeldebarros can you provide your group defenition? at least partial? `But the fact is that I have only 33 handlers (plus the static assets) and I am getting this error.` - feels like a mixup, ie handler supposed to be like a middleware, not an endpoint. i've made brain-dead test to see if there are any limits on number of endpoints for one group and seems there are none(at least 1K worked). however - if you have 64 middlewares it would fail indeed. 
Again, sorry if i am missing out something :) 
Here is an example:
```
func setupRouter() *gin.Engine {
	r := gin.Default()

	// this works
	r.Group("/")
	{
		for i := 0; i < 65; i++ {
			r.GET("/ping" + strconv.Itoa(i), pong)
		}
	}

	// this fails
	r.Group("/m", getMiddlewares()...)

	return r
}

func pong(c *gin.Context) {
	c.JSON(200, gin.H{"message": "pong"})
}

func getMiddlewares() []gin.HandlerFunc {
	m := make([]gin.HandlerFunc, 64)

	for i := range m {
		m[i] = func (c *gin.Context) {
			c.Set("key" + strconv.Itoa(i), i)
		}
	}

	return m
}
```

**Comment by michaeldebarros** [comment]
Makes sense. If you have 60 middleware handlers there must be something wrong. I'll look into my code and provide paste some here.

**Comment by michaeldebarros** [comment]
I guess I found it.

I have a dispatcher that was suppose to rout each request to a specific *gin.Engin, according to the subdomain.  But seems to me that every time there is a request I am adding another *gin.Engine (which conforms to the http.Handler interface). 

`type dispatcher map[string]http.Handler

func (dsp dispatcher) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	domainParts := strings.Split(r.Host, ".")
	if mux := dsp[domainParts[0]]; mux != nil {
		mux.ServeHTTP(w, r)
	} else {
		http.Error(w, "Not found", 404)
	}
}`


I think this may do the trick.

`type dispatcher map[string]http.Handler

var mux http.Handler

func (dsp dispatcher) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	domainParts := strings.Split(r.Host, ".")
	if mux = dsp[domainParts[0]]; mux != nil {
		mux.ServeHTTP(w, r)
	} else {
		//! TODO: custom 404
		http.Error(w, "Not found", 404)
	}
}`

**Comment by michaeldebarros** [comment]
No. It did not. Got the same error again.

**Comment by michaeldebarros** [comment]
Closing the issue because it was an error in my code.
