### ISSUE TITLE
How do I serve an svg as an image?

### ISSUE THREAD

**Issue by 01AutoMonkey** [gin-gonic/gin#250]
If I go to http://upload.wikimedia.org/wikipedia/commons/7/76/Pagoda.svg I view the svg in the browser as an image, that is I don't see the svg "xml" text but the image itself.

When I serve my svg folder with gin however the svg's are treated as XML file's, how can I change that?

`r.Static("/trees", "./json/svg/")`

**Comment by 01AutoMonkey** [comment]
Okay so it wasn't gin related, I had to put `xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" version="1.0"` in my svg files and then everything worked

**Comment by pedroFP** [comment]
https://upload.wikimedia.org/wikipedia/commons/7/76/Pagoda.svg
