### ISSUE TITLE
c.ShouldBindBodyWith should not consume a request body

### ISSUE THREAD

**Issue by momotaro98** [gin-gonic/gin#2502]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

This issue is related to #439, #1810.

I think `c.ShouldBindBodyWith` should not consume a request body for next binding. 

When I read the current [README doc about this method](https://github.com/gin-gonic/gin#try-to-bind-body-into-different-structs), I thought it doesn't but it does so I've got an EOF error like the example below.

I think it's now confusing for users.

Thanks. 

## How to reproduce

```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
)

type MyStruct struct {
	Key string `json:"key" binding:"required"`
}

func MyMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		var h MyStruct

		if err := c.ShouldBindBodyWith(&h, binding.JSON); err != nil {
			c.JSON(400, gin.H{
				"message": fmt.Sprintf("%+v", err),
			})
			return
		}

		c.Next()
	}
}

func main() {
	r := gin.Default()
	r.Use(MyMiddleware())
	r.POST("/post", func(c *gin.Context) {
		var h MyStruct

		decoder := json.NewDecoder(c.Request.Body)
		err := decoder.Decode(&h)
		if err != nil {
				c.JSON(400, gin.H{
					"message": fmt.Sprintf("%+v", err),
				})
				return
		}

		c.JSON(200, gin.H{
			"message": "ok",
		})
	})
	r.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}

```

## Expectations

```
$ curl --location --request POST 'http://localhost:8080/post' \
--header 'Content-Type: application/json' \
--data-raw '{
    "key": "value"
}'
{"message":"ok"}
```

## Actual result

```
$ curl --location --request POST 'http://localhost:8080/post' \
--header 'Content-Type: application/json' \
--data-raw '{
    "key": "value"
}'
{"message":"EOF"}
```

## Environment

- go version: go1.15 darwin/amd64
- gin version (or commit ref): 3100b7cb05a8072b76d31686d8a7b4f9b12df4be
- operating system: darwin/amd64

**Comment by A-0-5** [comment]
As per my understanding the `ShouldBindBodyWith `  Method  will read the body and copy it into the context if you wish to reuse the body the you must invoke it with `ShouldBindBodyWith` again as per the implementation below

https://github.com/gin-gonic/gin/blob/caf2802593277033683c4e8cb5f22c81cc35eae8/context.go#L715

using c.Request.Body is bound to return EOF since the HttpRequest Body is still an io.ReadCloser which was already read the first time you called `ShouldBindBodyWith` So if you use the ShouldBindBodyWith Method int POST Handler it should work 
```golang
func main() {
	r := gin.Default()
	r.Use(MyMiddleware())
	r.POST("/post", func(c *gin.Context) {
		var h MyStruct

		err := c.ShouldBindBodyWith(&h,  binding.JSON)
		if err != nil {
				c.JSON(400, gin.H{
					"message": fmt.Sprintf("%+v", err),
				})
				return
		}

		c.JSON(200, gin.H{
			"message": "ok",
		})
	})
	r.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}
```
