### ISSUE TITLE
Gin's Context implementation of context.Context

### ISSUE THREAD

**Issue by Julio-Guerra** [gin-gonic/gin#2516]
Hello,

[Based on those lines](https://github.com/gin-gonic/gin/blob/master/context.go#L1100-L1116) implementing the `context.Context` interface, Gin should either proxy those calls to `c.Request.Context()` or otherwise not implement `context.Context` at all. This leads to mistakes and errors since one can think Gin's context will behave as a request context...

Same with the value storage which should also go into the request context in my opinion if you really want to implement `context.Context`.

**Comment by kszafran** [comment]
This has been solved by https://github.com/gin-gonic/gin/pull/2769, but weirdly it's not present in v1.7.3.
