### ISSUE TITLE
Documentation grammar fix: Middleware, not Middlewares.

### ISSUE THREAD

**Issue by biztos** [gin-gonic/gin#252]
Hi there!

I am enjoying my taste of Gin, and thought I would help by pointing out a typo in the documentation.

The plural of "middleware" is not "middlewares" but simply "middleware" -- just like "software."

cheers

-- kf.

**Comment by manucorporat** [comment]
@biztos english is not my mothertongue. are you sure about that?

**Comment by austinheap** [comment]
:+1:

**Comment by manucorporat** [comment]
@biztos @austinheap thank you! http://english.stackexchange.com/questions/257120/middleware-vs-middlewares

@javierprovecho your fix was merged!
