### ISSUE TITLE
Can gin support HTTP/3?

### ISSUE THREAD

**Issue by snowdream** [gin-gonic/gin#2523]
## Description

Can gin support HTTP/3?

## Environment

- go version go1.15.2 darwin/amd64
- gin version (or commit ref): v1.6.3
- operating system: macOS

**Comment by thinkerou** [comment]
related: https://github.com/golang/go/issues/32204

**Comment by iFrozenPhoenix** [comment]
@thinkerou while waiting for an official decision from the GO team, actually it doesn't look like this is a priority there, maybe the existing implementation from https://github.com/lucas-clemente/quic-go can be used. As I have seen a few large GO projects use this library already, namely traefik and caddy.
As http/3 changes the connection from tcp to udp it would be good to gain experiences with this before it is really mainstreamed. Well, a short google search leads to the fact that about 23 % of all websites are already using http/3. Probably behind services like Cloudflare which implement this via reverse proxying, but nevertheless.
What do you think about it?

**Comment by thinkerou** [comment]
experimental support, please see #3210

**Comment by vrnvu** [comment]
Any updates?

**Comment by PoacherBro** [comment]
any updates? want to have a rc version 😄

**Comment by appleboy** [comment]
@PoacherBro I will continue #3210 PR.

**Comment by appleboy** [comment]
Waiting for https://github.com/golang/go/issues/58547 QUIC implementation

**Comment by marten-seemann** [comment]
Hi guys, author maintainer of [quic-go](https://github.com/quic-go/quic-go) here 👋

Have you considered using quic-go for your HTTP/3 support? quic-go is a mature and optimized QUIC stack that, among many many others, is powering HTTP/3 support in the Caddy webserver.

Happy to help out or to give pointers, if there's interest. Just let me know :)

**Comment by maggie44** [comment]
> Hi guys, author maintainer of [quic-go](https://github.com/quic-go/quic-go) here 👋
> 
> Have you considered using quic-go for your HTTP/3 support? quic-go is a mature and optimized QUIC stack that, among many many others, is powering HTTP/3 support in the Caddy webserver.
> 
> Happy to help out or to give pointers, if there's interest. Just let me know :)

Someone made a start over here. But it was never seen through: https://github.com/gin-gonic/gin/pull/3210#event-11783110309

**Comment by bound2** [comment]
#3210 is now merged. Can close this.
