### ISSUE TITLE
implement ".Unwrap() error" on Error type

### ISSUE THREAD

**Issue by LeGEC** [gin-gonic/gin#2525]
## Description

The 'Error' type defined in errors.go does not implement ".Unwrap() error", which prevents the usage of "errors.Is()" and "errors.As()"

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

type TestStrErr string

func (e TestStrErr) Error() string { return string(e) }

func main() {
	testErr := TestStrErr("some error")

	err := &gin.Error{Err: testErr}

	if errors.Is(err, testErr) {
	    fmt.Println("match with testErr ok")
	}
	
	var unwrap TestStrErr
	if errors.As(err, &unwrap) {
	    fmt.Println("succesfully unwrapped as a TestStrErr")
	}
}
```

## Expectations

output :
```
match with testErr ok
succesfully unwrapped as a TestStrErr
```
## Actual result

no output

## Environment

- go version: go version go1.14.2 linux/amd64
- gin version (or commit ref):  540b1eff7069128df5d95e09968569f2266d9a6a
- operating system:  linux

**Comment by LeGEC** [comment]
A more useful use case was asked by this user on StackOverflow :  
[How to assert error type json.UnmarshalTypeError when caught by gin c.BindJSON ?](https://stackoverflow.com/q/64278486/86072)

He wants to tell apart "this is a JSON parsing error" from "the JSON is ok, this is a validation error"

With the correct implementation of the `.Unwrap() error` method, this boils down to :
```go
// gErr is a gin.Error
var jsErr *json.UnmarshalTypeError
if errors.As(gErr, &jsErr) {
    fmt.Println("the json is invalid")
} else {
    fmt.Println("this is something else")
}
```

**Comment by thejdavid** [comment]
It would also help for other issues for other data types such as trying to un parse an invalid time.Time. in such case it wouldn't return a json parsing error but a time parsing error.
It might be useful to differentiate / group parsing errors from binding errors.

**Comment by thinkerou** [comment]
#2526 merged

**Comment by jhannah-mm** [comment]
@thejdavid wrote:
> It would also help for other issues for other data types such as trying to un parse an invalid time.Time. in such case it wouldn't return a json parsing error but a time parsing error.
> It might be useful to differentiate / group parsing errors from binding errors.

Ya, it seems that even under 1.7.1 there's still no useful information regarding where in a JSON POST the `UnmarshalType` casting failure occurred... 
```
POST {
   "start_date": "invalid_date"    // time.Time
}
parsing time ""invalid_date"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "invalid_date"" as "2006"
```
Hoping it would say `start_date`... somewhere / somehow
