### ISSUE TITLE
required binding erratic behavior

### ISSUE THREAD

**Issue by gregzuro** [gin-gonic/gin#253]
For a json object with all elements as 'required':

If all the items have the initialization value ("" for strings, 0 for ints, etc.) then the bind succeeds... even if some of the items are not provided.

If one or more of the items has a non-init value, then any other item(s) with an init value causes a binding error for the latter item(s).

This is with e2fa89777e344782ef5d31929f095f4589c35dcc (0.5 - LAG in master)

**Comment by thinkerou** [comment]
Please see https://github.com/gin-gonic/gin#model-binding-and-validation, I think it's ok. @appleboy close the issue?
