### ISSUE TITLE
Assets conflict with Link when it contains parameters

### ISSUE THREAD

**Issue by bashery** [gin-gonic/gin#2530]
Assets cannot be submitted to dynamic routed pages. Each page link contains parameters that cannot access the assets.
for example:
``` router.Static ("/a'', "./assets") ```
And the
``` router.GET ("/acount /:name'', acount)```
The browser does not request assets like this:
```http://localhost:8080/a/imgs/turtel.jpg```
Instead it sends the request like this:
```http://localhost:8080/acount/a/imgs/turtel.jpg```
If the assets are presented in a corresponding path, for example:
```router.Static ("/acount/a'',  "./assets '')```
A new conflict will arise with ```router.GET ("/acount/:name", acount)```

**Comment by athe0i** [comment]
@bashery hey! unfortunately this is a known issue.... you can read more about it here: #2016

**Comment by bashery** [comment]
@athe0i Thanks

**Comment by bashery** [comment]
#2416
