### ISSUE TITLE
Root static resource router not supported

### ISSUE THREAD

**Issue by oyoungs** [gin-gonic/gin#2537]
After I registered other routers, when I want to register the static resources router to the path "/",  it told me "CONFLICTS"

My code:
```go
func main() {
        router := gin.Default()

	router.Use(gin.Logger())

	router.Use(gin.Recovery())

	router.StaticFS("/", http.Dir("public"))

	v1 := router.Group("/api/v1")

	{
		task := v1.Group("/task")

		api.NewTaskApi(task)

	}

	router.Run(":3408")
}
```

errors like that:
```bash
panic: '/api/v1/task/' in new path '/api/v1/task/' conflicts with existing wildcard '/*filepath' in existing prefix '/*filepath'
```

**Comment by athe0i** [comment]
@oyoungs `router.StaticFS` registers param path into the router with `/*filepath` which creates conflict with everything else in the root path. my suggestion would be to use something like `router.StaticFS("/public", http.Dir("public"))` . static and param paths collision is known issue - #2016

**Comment by oyoungs** [comment]
I tried, but in the front-end file "index.html", all request url is based on the path "/":

```
├── asset-manifest.json
├── favicon.ico
├── index.html
├── manifest.json
├── service-worker.js
└── static
    ├── css
    │   └── main.6d1949a3.css
    ├── js
    │   ├── 0.81fb3f90.chunk.js
    │   ├── 1.b9d9e99d.chunk.js
    │   └── main.86df6cbc.js

```
So my static source path must be "/", else it will tell me "404 Not Found"

But if I use the http.ServeMux, the static resource path "/" and the api router "/api/v1" are compatible( '/api/v1' has higher priority )
