### ISSUE TITLE
how to forward all log to a file?

### ISSUE THREAD

**Issue by shrimpywu** [gin-gonic/gin#255]
does gin-gonic has similar API as martini can easily re-direct log to a file
e.g
````go
   m.Map(log.New(f, "[martini]", log.LstdFlags))    
````

**Comment by manucorporat** [comment]
How about this? https://github.com/gin-gonic/gin/commit/6c788a43004f9763178738a2c2f7a6d276fd60d5

```go
gin.DefaultLogFile = os.Stdout

router := gin.Default()
```

the idea: the logger middleware takes the `gin.DefaultLogFile` as default file.

but you can be even more explicit:

```go
yourfile, _ := os.Create("server.log")

router := gin.New()
router.Use(gin.LoggerWithFile(yourfile))
```

**Comment by slimmy** [comment]
I would have a look at http://golang.org/pkg/io/#MultiWriter to enable both logging to the console and file, works really well.

**Comment by manucorporat** [comment]
you could still use MultiWriter()
```go
myfile, _ := os.Create("server.log")
gin.DefaultLogFile = io. MultiWriter(myfile, os.Stdout)

router := gin.Default()
// ...
```

**Comment by shrimpywu** [comment]
+1 for DefaultWriter

**Comment by manucorporat** [comment]
ok, it's done!
