### ISSUE TITLE
todo: fix cmd/vet error

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/gin#2553]
go version: master branch
issue info: `internal/bytesconv/bytesconv.go:14:8: possible misuse of reflect.StringHeader`
more info: https://travis-ci.org/github/gin-gonic/gin/jobs/742893211

ref go issue: https://github.com/golang/go/issues/40701

**Comment by wuhuizuo** [comment]
@thinkerou golang/go#40701 was closed.
