### ISSUE TITLE
when post a image use goroutine ,Context.Copy is failed.

### ISSUE THREAD

**Issue by tangtang666** [gin-gonic/gin#2556]
# Description

 I use goroutine to deal a post function,but if i send two post in the same time or one by one ,i get this this error: [debug]error on parse multipart form array: multipart: NextPart: http: invalid Read on closed Body

## How to reproduce

![image](https://user-images.githubusercontent.com/12507576/98926742-a8689f80-2512-11eb-974e-57261877d1bc.png)

```
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"log"
	"time"
)

func main() {
	r := gin.Default()
	r.POST("/long_async", func(c *gin.Context) {
		// create copy to be used inside the goroutine
		cCp := c.Copy()
		go func() {
			// simulate a long task with time.Sleep(). 5 seconds
			fmt.Println(cCp.PostForm("log_id"))
			image, _ := cCp.FormFile("image")
			fmt.Println(image.Filename)
			time.Sleep(5 * time.Second)
			// note that you are using the copied context "cCp", IMPORTANT
			log.Println("Done! in path " + cCp.Request.URL.Path)
		}()
	})

	// Listen and serve on 0.0.0.0:8080
	r.Run(":8080")
}

```

## Environment

- go version:1.15.3
- gin version (or commit ref):v1.6.3
- operating system:Mac os 10.15.7

**Comment by dahaihu** [comment]
It is not a bug!

when request finishes, the body will be closed by net/http. https://github.com/gin-gonic/gin/issues/1237

gin.Context.Copy() copy the addres of  http.Request
```
type Context struct {
	writermem responseWriter
	Request   *http.Request
	Writer    ResponseWriter
        ...
}
```
when the request finishes, the Reqeust.Body is closed. then you use PostForm or FormFile, they all read data from gin.Context.Request.Body, however it is closed.

you should read data, and transfer the data to goroutine, it will be ok!

**Comment by tangtang666** [comment]
Thanks，I had use a struct solove it.

**Comment by tangtang666** [comment]
> when request finishes, the body will be closed by net/http. #1237
> 
> gin.Context.Copy() copy the addres of http.Request
> 
> ```
> type Context struct {
> 	writermem responseWriter
> 	Request   *http.Request
> 	Writer    ResponseWriter
>         ...
> }
> ```
> 
> when the request finishes, the Reqeust.Body is closed. then you use PostForm or FormFile, they all read data from gin.Context.Request.Body, however it is closed.
> 
> you should read data, and transfer the data to goroutine, it will be ok!

Thanks，I had use a struct solove it.
