### ISSUE TITLE
Delete methed cannot get data from body

### ISSUE THREAD

**Issue by Xieyuschen** [gin-gonic/gin#2565]
I implements a delete method by gin, and I get data form body like this:
```go
func Delete(context *gin.contex){
        id:=context.PostForm("id")
        //do some logical codes
}
```
But I found that the id is an empty string which means **the context doesn't contain `id` param in body**(I'm not sure, but I think it has a high possibility).
I found there is a closed issue(#396) but it was closed without solving method. I'm confused about this .

**Comment by libi** [comment]
> I implements a delete method by gin, and I get data form body like this:
> 
> ```go
> func Delete(context *gin.contex){
>         id:=context.PostForm("id")
>         //do some logical codes
> }
> ```
> 
> But I found that the id is an empty string which means **the context doesn't contain `id` param in body**(I'm not sure, but I think it has a high possibility).
> I found there is a closed issue(#396) but it was closed without solving method. I'm confused about this .

https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

**Comment by dahaihu** [comment]
Maybe it is your problem, the code below can read post form params
```package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)
func main() {
	r := gin.Default()
	r.DELETE("/delete", func(c *gin.Context) {
		id:=c.PostForm("id")
		c.JSON(http.StatusOK, fmt.Sprintf("id is %s", id))
	})
	r.Run("localhost:8081") // listen and serve on 0.0.0.0:8080
}
```

In terminal, you can use curl to get the id result， pelease ignore the params `noparams` in curl
` curl -X DELETE localhost:8081/delete -F "id=10"`

![image](https://user-images.githubusercontent.com/33454450/101324051-8e697500-38a4-11eb-8225-a12a56ae072a.png)

**Comment by Xieyuschen** [comment]
> Maybe it is your problem, the code below can read post form params
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"github.com/gin-gonic/gin"
> 	"net/http"
> )
> func main() {
> 	r := gin.Default()
> 	r.DELETE("/delete", func(c *gin.Context) {
> 		id:=c.PostForm("id")
> 		c.JSON(http.StatusOK, fmt.Sprintf("id is %s", id))
> 	})
> 	r.Run("localhost:8081")
> }
> ```
> 
> In terminal, you can use curl to get the id result， pelease ignore the params `noproxy` in curl
> ` curl -X DELETE localhost:8081/delete -F "id=10"`
> 
> ![image](https://user-images.githubusercontent.com/33454450/101324051-8e697500-38a4-11eb-8225-a12a56ae072a.png)

Thank you for your help. Acctually this happened at `Wechat-micro-app` plateform, because it limits the frontend usage(e.g it doesn't support dom, how stupid). I use postman do this delete method successfully, I assume this caused by this foolish narrow plateform:(

**Comment by dahaihu** [comment]
> > Maybe it is your problem, the code below can read post form params
> > ```
> > package main
> > 
> > import (
> > 	"fmt"
> > 	"github.com/gin-gonic/gin"
> > 	"net/http"
> > )
> > func main() {
> > 	r := gin.Default()
> > 	r.DELETE("/delete", func(c *gin.Context) {
> > 		id:=c.PostForm("id")
> > 		c.JSON(http.StatusOK, fmt.Sprintf("id is %s", id))
> > 	})
> > 	r.Run("localhost:8081")
> > }
> > ```
> > 
> > 
> > In terminal, you can use curl to get the id result， pelease ignore the params `noproxy` in curl
> > ` curl -X DELETE localhost:8081/delete -F "id=10"`
> > ![image](https://user-images.githubusercontent.com/33454450/101324051-8e697500-38a4-11eb-8225-a12a56ae072a.png)
> 
> Thank you for your help. Acctually this happened at `Wechat-micro-app` plateform, because it limits the frontend usage(e.g it doesn't support dom, how stupid). I use postman do this delete method successfully, I assume this caused by this foolish narrow plateform:(

At last, you know that it is not gin's problem,  you could close this issue.

**Comment by Xieyuschen** [comment]
> > > Maybe it is your problem, the code below can read post form params
> > > ```
> > > package main
> > > 
> > > import (
> > > 	"fmt"
> > > 	"github.com/gin-gonic/gin"
> > > 	"net/http"
> > > )
> > > func main() {
> > > 	r := gin.Default()
> > > 	r.DELETE("/delete", func(c *gin.Context) {
> > > 		id:=c.PostForm("id")
> > > 		c.JSON(http.StatusOK, fmt.Sprintf("id is %s", id))
> > > 	})
> > > 	r.Run("localhost:8081")
> > > }
> > > ```
> > > 
> > > 
> > > In terminal, you can use curl to get the id result， pelease ignore the params `noproxy` in curl
> > > ` curl -X DELETE localhost:8081/delete -F "id=10"`
> > > ![image](https://user-images.githubusercontent.com/33454450/101324051-8e697500-38a4-11eb-8225-a12a56ae072a.png)
> > 
> > 
> > Thank you for your help. Acctually this happened at `Wechat-micro-app` plateform, because it limits the frontend usage(e.g it doesn't support dom, how stupid). I use postman do this delete method successfully, I assume this caused by this foolish narrow plateform:(
> 
> At last, you know that it is not gin's problem, you could close this issue.

Yes it is, thanks for your help:)
