### ISSUE TITLE
Unicode urls

### ISSUE THREAD

**Issue by fdelbos** [gin-gonic/gin#257]
Hi,

I encounter what I believed may be a bug with unicode urls:
say I have the following route

```go
r.GET("/:role", FilterRole(), func(c *gin.Context) {
    url := c.Params.ByName("role")
}
```

If the `:role` param is to be unicode encoded a possible route may be `http://127.0.0.1:53286/%E4%B8%AD%E5%9B%BD` if generated using `url.QueryEscape("中国")` (unicode urls seems to always be escaped but modern browser display them as unicode...)

But when I call a `c.Params.ByName("role")` I do not get the escaped string `"%E4%B8%AD%E5%9B%BD"`, instead I get the unicode string `"中国"` which doesn't match.

Any idea on how to fix this issue?

By the way, thanks for the awesome framework

**Comment by manucorporat** [comment]
Well, that looks exactly like the correct behaviour.
```go
c.Params.ByName("role")
```
should return the unicode version.

In fact it would be a bug if `c.Params.ByName("role")` return `"%E4%B8%AD%E5%9B%BD"` instead of `"中国"`.

**Comment by fdelbos** [comment]
Ok, I tested and other routers do that as well. So my apologies, you are correct.

It's just that I had trouble wrapping my head around encodings... I ll figure out something.

thanks.

**Comment by manucorporat** [comment]
ok!
