### ISSUE TITLE
Can't set headers after AbortWithError

### ISSUE THREAD

**Issue by AndySpf** [gin-gonic/gin#2571]
## Description
    I used c.JSON() to return after json binding failed. But the Content-Type in response header is "text/plain; charset=utf-8".  

   After trying.I found that all headers setting after c.Writer.WriteHeaderNow() are invalid.
 
 How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

type User1 struct {
	UserName string `json:"username"`
	Date     int    `json:"date"`
}

func main() {
	h := gin.New()
	h.POST("/api/ct", func(c *gin.Context) {
		var u User1
		if err := c.BindJSON(&u); err != nil {
			c.JSON(400, "fail")
			return
		}

		c.JSON(200, "ok")
	})

	h.Run(":4000")
}
```

## Expectations
 The Content-Type in response header is "application/json; charset=utf-8". That is, the header can be set correctly

## Actual result

![1123](https://user-images.githubusercontent.com/33141719/100606400-544c2080-3344-11eb-8858-ebcd9555621f.jpg)

## Environment

- go version: go1.14.9 darwin/amd64
- gin version (or commit ref):  gin 1.6.3
- operating system: darwin/amd64

**Comment by AndySpf** [comment]
Can I add the following code to the ShouldBindJSON function,  so that we can use BIndJSON or ShouldBIndJSON as needed
`c.Error(http.StatusBadRequest, `err).SetType(ErrorTypeBind)`

**Comment by imxyb** [comment]
you can use `ShouldBindJSON`

```go
h.POST("/api/ct", func(c *gin.Context) {
		var u User1
		if err := c.ShouldBindJSON(&u); err != nil {
			c.JSON(400, "fail")
			return
		}

		c.JSON(200, "ok")
	})
```

**Comment by AndySpf** [comment]
> you can use `ShouldBindJSON`
> 
> ```go
> h.POST("/api/ct", func(c *gin.Context) {
> 		var u User1
> 		if err := c.ShouldBindJSON(&u); err != nil {
> 			c.JSON(400, "fail")
> 			return
> 		}
> 
> 		c.JSON(200, "ok")
> 	})
> ```

**Comment by AndySpf** [comment]
But the ShouldBindJSON does not add error to c.Errors. I need to deal with it in all the places I use.
