### ISSUE TITLE
Static file serving returns 404 error code when using r.Static

### ISSUE THREAD

**Issue by dragonDScript** [gin-gonic/gin#2579]
## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
        r.Static("/static", "../static")
	r.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:8201/static/file.webp
<File here>
```

## Actual result

```
$ curl -i http://localhost:8201/static/file.webp
404 error
```

## Environment

- go version: v1.15
- gin version (or commit ref): 1.6.3
- operating system: ubuntu 20.04

# Other important information

This is the minimal project structure:
```
- cmd
  - main.go
- static
   - a file.webp
```

**Comment by seblegall** [comment]
Hi,

Did you check twice the static file path?

In your example, I can see : 
* `static/a_file_inside_static_folder.webp`
* `static/file`
* `- a file.webp`

The only doubt was about the ability for Gin to serve the `../` directory. But I just checked, it works perfectly fine.
Also, I'd be very surprised if it was a go v1.15 bug.

My guess is that you have a typo somewhere.

**Comment by dragonDScript** [comment]
> Hi,
> 
> Did you check twice the static file path?
> 
> In your example, I can see :
> 
> * `static/a_file_inside_static_folder.webp`
> * `static/file`
> * `- a file.webp`
> 
> The only doubt was about the ability for Gin to serve the `../` directory. But I just checked, it works perfectly fine.
> Also, I'd be very surprised if it was a go v1.15 bug.
> 
> My guess is that you have a typo somewhere.

1. Yep, a lot of times. I have edited the original question to avoid confusion.

**Comment by cpl** [comment]
If you are running like this:
```bash
go run ./cmd/*.go
```
Then your relative path to the static directory is not `../static` but `./static`. The path is not realtive to the main package, it is relative to where you're running from (current working dir).

See if
```go
        r.Static("/static", "./static")
}
```
works.

OR `cd cmd && go run main.go`.

**Comment by dragonDScript** [comment]
fixed. thanks for your help
