### ISSUE TITLE
The Project is stopped?

### ISSUE THREAD

**Issue by danitw** [gin-gonic/gin#2587]

**Comment by m-nouredini** [comment]
This is my question too, releases seem old and far behind the master.

**Comment by TJM** [comment]
Also the website is blank?

**Comment by appleboy** [comment]
@TJM I fixed the website before and you can see it now. https://gin-gonic.com/

**Comment by appleboy** [comment]
@m-nouredini @danitw We will release the 1.7 version asap after the only one PR merge. See the milestone: https://github.com/gin-gonic/gin/milestone/12

**Comment by ReOneK** [comment]
> This is my question too, releases seem old and far behind the master.
the next version is coming???
i need choose one webframe of go,should i choose gin?

**Comment by ReOneK** [comment]
> @m-nouredini @danitw We will release the 1.7 version asap after the only one PR merge. See the milestone: https://github.com/gin-gonic/gin/milestone/12

so there are maybe a new version coming??
