### ISSUE TITLE
The get request cannot get the value containing the percent sign

### ISSUE THREAD

**Issue by Sunday1024** [gin-gonic/gin#2589]
## Description

If the get request parameter contains a percent sign, the corresponding value will not be obtained

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:8201/hello/world?name=%Hello
%Hello
```

## Actual result

```
$ curl -i http://localhost:8201/hello/world?name=%Hello
<>
```

**Comment by athe0i** [comment]
`c.Param`(https://github.com/gin-gonic/gin#parameters-in-path) would get value from the body or url params, to get query param you should use `c.Query`(https://github.com/gin-gonic/gin#querystring-parameters)
also - according to your example gin is running on port 9000, while you are getting 8201 from curl.

**Comment by Doarakko** [comment]
Percentages need to be encoded.
```
http://localhost:8201/hello/world?name=%25Hello
```

ref: https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters
