### ISSUE TITLE
ANNOYING Bind JSON

### ISSUE THREAD

**Issue by batara666** [gin-gonic/gin#2619]
Your Bind Json, Should Bind, ShouldBindJSON etc etc things is waste of time, 

trying to get simple json body, it was simply done with net/http:

```
		var payload user
		err := json.NewDecoder(r.Body).Decode(&payload)
		if err != nil {
			log.Println(err)
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
```

but I HAVE TO SPEND ABOUT 1HOURS+ JUST FOR FINDING WHY MY GIN GOT 400 WITHOUT ANY MESSAGE ON SERVER SIDE

**Comment by yeqown** [comment]
You don't have to use `ShouldBind` or any binding method, this is just a wrapper for parameters parsing automatically. Without any binding method, you can do as following:

```go
err := json.NewDecoder(ctx.Request.Body).Decode(&payload)
// handle error
```

by the way, I'm confusing why you got nothing when the `400` status code has reported?
