### ISSUE TITLE
appengine example not working with latest SDK

### ISSUE THREAD

**Issue by vinayaknagpal** [gin-gonic/gin#262]
When running the appengine example in source tree, I see the following error

http_runtime.py:285] bad runtime process port ['[GIN-debug] GET   /                         --> main79457.func\xc2\xb7001 (1 handlers)\n']

**Comment by fwlab** [comment]
Same issue here. It works if deployed (on the production Google App Engine Servers). It does not work on the local server.

**Comment by manucorporat** [comment]
I think this is already fixed in develop branch. App Engine doesn't support fmt.Print(), we changed it to log.Print() some time ago.

**Comment by greivinlopez** [comment]
I have the same issue here.  Hope the new release to be ready soon! :)

**Comment by manucorporat** [comment]
@greivinlopez Gin v1 was released yesterday :) can you update your version of Gin?

**Comment by greivinlopez** [comment]
@manucorporat Thank you. Updated to the latest version and the previous problem was solved, now I receive the following error:

ERROR    2015-05-23 22:18:13,402 http_runtime.py:343] bad runtime process port ['[GIN-debug] [WARNING] Running in DEBUG mode! Disable it before going production\n']
ERROR    2015-05-23 22:18:40,537 http_proxy.py:116] bad runtime process port ['[GIN-debug] [WARNING] Running in DEBUG mode! Disable it before going production\n']

Any ideas? Workarounds?

**Comment by manucorporat** [comment]
Workarounds:
```go
gin.SetMode(gin.ReleaseMode)
```

Fix: looks like we can not use stdout at all... I am not sure how to fix it. I switched from `fmt` to `log` for printing logs, but looks like it is not enough.

**Comment by manucorporat** [comment]
@greivinlopez https://github.com/gin-gonic/gin/commit/e2adae90033ee85ec093b181089a722a8fa541f1

**Comment by manucorporat** [comment]
you should use:

```go
gin.SetMode(gin.ReleaseMode) // probably we should make it the default mode...
router := gin.New()
// ...
```

**Comment by greivinlopez** [comment]
It works!  Great!.
As this is just for App Engine I think is enough to include the line and comment in the app engine example and point it out in the documentation.

Thank you very much man.
Your project is amazingly fast and I love its simplicity.

**Comment by manucorporat** [comment]
@greivinlopez great! please let me know if any trouble with App Engine! :)

**Comment by nazwa** [comment]
I know this has been discussed in another issue, but I really believe release mode should be the default setting in gin. Or it should be very very very highlighted in the documentation that people need to explicitly set it before going to production.

**Comment by manucorporat** [comment]
@nazwa I think "very very very highlighted in the documentation" is a better solution. If release is the default mode, many developers will miss important bugs.

I have included this warning in v1:
https://github.com/gin-gonic/gin/commit/eb91af753db3d2bc6b86eb3ed3f94fac76a67eb4

**Comment by nazwa** [comment]
Nice, that should do the job.
