### ISSUE TITLE
Is it possible to bind query inside Middleware by passing struct type?

### ISSUE THREAD

**Issue by tprei** [gin-gonic/gin#2628]
## Description

Can you validate data inside a middleware handler? I'd like to do something like this:

``` go
func Binder(t reflect.Type) gin.HandlerFunc {
    return func(c *gin.Context) {
        obj := reflect.New(t).Elem().Interface()
        if err := c.BindQuery(&obj); err != nil {
            c.AbortWithStatus(http.StatusBadRequest)
            return
        }

        c.Set(t.Name(), obj)
    }
}
```

So that later on I could access, let's say, the query data validated to a struct named "Subject" (with gin bindings) by doing:

```go
sub := c.MustGet("Subject").(Subject)
```

Here what's happening is that `obj` is empty. Is this possible? If not by passing `reflect.Type`, could it be done using an interface object? (Maybe one that all types that require validation implement)

**Comment by justinrush** [comment]
this is an interesting idea - do you ever get this working?

**Comment by almost-porchat** [comment]
Not really, I just gave up and used a defined type inside the implementation like `ThisBinder` which just instantiates `This` and binds to it.

**Comment by almost-porchat** [comment]
I guess we will have to wait for generics :D

**Comment by tprei** [comment]
I managed to do something very similar @justinrush 

I created the following middleware

```go
var allowedTypes = []binding.Binding{
	binding.Query,
	binding.Form,
	binding.FormPost,
	binding.FormMultipart,
}

func Bind(name string, data interface{}, bindingType binding.Binding) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		ok := false
		for _, b := range allowedTypes {
			if b == bindingType {
				ok = true
			}
		}
		if !ok {
			ctx.AbortWithError(
				http.StatusInternalServerError,
				fmt.Errorf("Bind function only allows %v\n", allowedTypes),
			)
		}
		_ = ctx.MustBindWith(data, bindingType)
		ctx.Set(name, data)
	}
}

```

Remember to pass a pointer to your desired type in the call, like so:

`router.GET("/something", Bind("Object", &myObject, binding.Query)`

I used only these types because they allow `ShouldBind` to be called multiple times, whereas `JSON`, `XML` and others consume the Request body.

This way you can pass multiple Bind middlewares and if the validation fails it automatically aborts with `http.StatusBadRequest`
