### ISSUE TITLE
Variation of the Unix timestamp issue

### ISSUE THREAD

**Issue by zettelmj** [gin-gonic/gin#2634]
Hi,

I am running into a variation of https://github.com/gin-gonic/gin/issues/1979 difference in my case is that the timestamp is in milliseconds. My approach would be to follow https://github.com/ThomasObenaus/gin/commit/ecddd0378397087c6524e6924e4a8995ee215d2a example and extend the supported format to not only support unix and unixnano but also unixmilli.

Would such a PR be welcome?

Thank you
Jens

**Comment by takanuva15** [comment]
I was just looking whether gin can do a binding directly from milliseconds and I'm confused - was this ever implemented? 
Or do we need to keep dividing the timestamp by 1000 to fit the "unix" time_format when submitting requests through gin?
