### ISSUE TITLE
Access-Control-Allow-Origin cannot be modified

### ISSUE THREAD

**Issue by a1292999652** [gin-gonic/gin#2649]
## Description

I have a middleware that dynamically changes the value of "Access-Control-Allow-Origin", but it is always invalid. What's the problem?

## How to reproduce

```
func Cors() gin.HandlerFunc {
	return func(c *gin.Context) {
		origin := c.Request.Header.Get("Origin")
		c.Writer.Header().Set("Access-Control-Allow-Origin", origin)
		c.Writer.Header().Set("Access-Control-Max-Age", "86400")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE, UPDATE")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Access-Control-Allow-Origin, Origin, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		c.Writer.Header().Set("Access-Control-Expose-Headers", "Content-Length")
		c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
	}
}
```
![微信图片_20210301161321](https://user-images.githubusercontent.com/31630317/109469707-5a6bad80-7aa9-11eb-8dc0-17ba81e41133.png)
![b57fab0a475514e3656e981232a5b43](https://user-images.githubusercontent.com/31630317/109469711-5cce0780-7aa9-11eb-90a4-7aabcb1d4414.png)
![e0ef3bc443fa6d1130bd2f87e335daf](https://user-images.githubusercontent.com/31630317/109469716-5d669e00-7aa9-11eb-9af0-c3535e2af26b.png)

## Environment

- go version: 1.16
- gin version (or commit ref):1.3.1
- operating system:windows10

**Comment by tunglv-1933** [comment]
I'm using the same environment but I don't face the problem above.
did u resolve it?

**Comment by a1292999652** [comment]
I close this question now, the main reason is do not use cookies after cross-domain
