### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by bfosberry** [gin-gonic/gin#266]
Hi

we are using a custom v0.6 fork with the static service bug fix on top of it, since develop and master seem unstable. Is there a stable gin-gonic hosted branch/tag we can use that contains the latest fixes, or can you tag a stable release?

thanks!

**Comment by manucorporat** [comment]
@bfosberry we are released the first stable version: https://github.com/gin-gonic/gin/releases/tag/v1.0rc1
tons of improvements, better performance, complete suite of unit tests and the API is frozen

**Comment by bfosberry** [comment]
Fantastic! thanks for following up
