### ISSUE TITLE
how to convert unit64 to string 

### ISSUE THREAD

**Issue by xiongdi9456** [gin-gonic/gin#2660]
I got some data from mysql and return the list to client, how to convert all uint64 data to string by default
```
type User struct {
		ID         uint64 `json: "id"`
		Customerid uint64 `json: "customerid"`

}
```

**Comment by oybekmuzropov** [comment]
I think It works
`type User struct {
		ID         uint64 `json:"id,string"`
		Customerid uint64 `json:"customerid,string"`

}`

**Comment by xiongdi9456** [comment]
@oybekmuzropov thank you
