### ISSUE TITLE
Can I disable gin's stdout?

### ISSUE THREAD

**Issue by allencloud** [gin-gonic/gin#267]
Hi, 

Now I am using a lot on gin. And now I wonder if I can disable gin's stdout ?

If there is some , then how?

Thanks.

**Comment by techjanitor** [comment]
Just initialize gin with New instead of Default. I assume you're talking about the Logger middleware.

```
gin.New()
r.Use(gin.Recovery())
```

**Comment by allencloud** [comment]
Yes, I do not hope to use Stdout but Logger middleware instead. Thank you very much.

**Comment by techjanitor** [comment]
Well the Logger is always going to write to stdout. Unless you redirect the output to a file, or use something like supervisord. If you want to write to a specific file without redirection you'd have to write your own Logger middleware.

**Comment by nazwa** [comment]
@allencloud this might be the droid you are looking for:

```go
gin.SetMode(gin.ReleaseMode)
```

Took me weeks before i found it :)

**Comment by allencloud** [comment]
Thanks a lot @nazwa . It works perfectly.   :)

**Comment by itmard** [comment]
```$ export GIN_MODE=release```

**Comment by wrfly** [comment]
@allencloud 

Try this:
```golang
gin.SetMode(gin.ReleaseMode)
gin.DefaultWriter = ioutil.Discard
```

**Comment by saitofun** [comment]
// init gin.Engine like this
engine = gin.Default()
engine.RouterGroup.Handlers = engine.RouterGroup.Handlers[0:0]
engine.Use(gin.Recovery())

**Comment by saitofun** [comment]
`// init gin.Engine like this
engine = gin.Default()
engine.RouterGroup.Handlers = engine.RouterGroup.Handlers[0:0]
engine.Use(gin.Recovery())`
