### ISSUE TITLE
How to detach middleware?

### ISSUE THREAD

**Issue by spolischook** [gin-gonic/gin#2677]
## Description

I have a function New that create a routes and attach middleware that check the security (access rights) for eash request.  
I would like to remove this middleware in my tests, so I need somehow detach it  

In the ideal world, I would like to have a func e.g. `g.Unuse`

## How to reproduce

```go
package router

import (
	"github.com/gin-gonic/gin"
)

func New() {
	g := gin.Default()
        g.Use(AuthMiddleware()) // How detach this in tests?
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	return g
}
```

**Comment by elvin-zheng** [comment]
u should mock function AuthMiddleware or mock request header in test
