### ISSUE TITLE
Using gin.CreateTestContext, and then engine.HandleContext causes panic if params are not filled in

### ISSUE THREAD

**Issue by stlimtat** [gin-gonic/gin#2690]
## Description

Panic in tree.go:446 when calling router.HandleContext on a context that does not have params parsed

## How to reproduce

```
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	"github.com/gin-gonic/gin"
)

func main() {
	w := httptest.NewRecorder()
	ctx, engine := gin.CreateTestContext(w)
	engine.GET("/hello/:name", func(ctx *gin.Context) {
		ctx.String(http.StatusOK, "Hello %s", ctx.Param("name"))
	})
	var err error
	ctx.Request, err = http.NewRequest(http.MethodGet, "/hello/something", nil)
	if err != nil {
		panic(err)
	}
	engine.HandleContext(ctx)

	fmt.Print("We should get here")
}
```

## Expectations

```
$ curl http://localhost:8201/hello/world
We should get here
```

## Actual result

```
$ curl -i http://localhost:8201/hello/world
[GIN-debug] GET    /hello/:name              --> main.main.func1 (1 handlers)
panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).getValue(0xc000327a40, 0x18464ce, 0x9, 0xc00031a120, 0x1000001010c00, 0x0, 0x0, 0x0, 0xc00031a120, 0x0, ...)
      /go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/tree.go:446 +0x1105
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00037e4e0, 0xc000310100)
       /go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:482 +0x2f9
github.com/gin-gonic/gin.(*Engine).HandleContext(0xc00037e4e0, 0xc000310100)
      /go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:456 +0x52
main.main()
       cmd/scratch/main.go:22 +0x27d
Exiting.
```

## Environment

- go version: 1.16.3
- gin version (or commit ref): 1.7.1
- operating system: macosx

**Comment by lawzava** [comment]
Facing same issue on v1.7.0 and v1.7.1; v1.6.x is fine

**Comment by jhartman86** [comment]
Just ran into this as well. Seems the code attempting to expand the capacity of the params slice at line 446 in `tree.go` doesn't handle expanding the underlying capacity properly.

**Comment by linxing** [comment]
@mamil stil can not get the param

**Comment by linxing** [comment]
`package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	"github.com/gin-gonic/gin"
)

func main() {
	w := httptest.NewRecorder()
	ctx, engine := gin.CreateTestContext(w)
	engine.GET("/hello/:name", func(ctx *gin.Context) {
                log.Println(ctx.Param("name"))
		ctx.String(http.StatusOK, "Hello %s", ctx.Param("name"))
	})
	var err error
	ctx.Request, err = http.NewRequest(http.MethodGet, "/hello/something", nil)
	if err != nil {
		panic(err)
	}
	engine.HandleContext(ctx)

	fmt.Print("We should get here")
}
`

**Comment by jhartman86** [comment]
Issue still seems to be present w/ version `1.7.4`

**Comment by paullaffitte** [comment]
I'm also getting this issue

**Comment by ossan-dev** [comment]
Hey, I rerun the code in the issue and I got the following result:
```
go run .
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /hello/:name              --> main.main.func1 (1 handlers)
We should get here
```
I think that the issue could be closed. 
Thanks

**Comment by appleboy** [comment]
fixed in https://github.com/gin-gonic/gin/pull/3502
