### ISSUE TITLE
Matching prefixes among multiple routers causes 404

### ISSUE THREAD

**Issue by muety** [gin-gonic/gin#2696]
I'm not particularly experienced with Gin, so I might well have gotten something wrong here. However, the following behavior appears strange to me. Consider this small example:

```go
package main

import (
	"net/http"
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.New()

	// useless because of https://github.com/golang/go/blob/a7e16abb22f1b249d2691b32a5d20206282898f2/src/net/http/fs.go#L587, but anyway ...
	r.StaticFile("/index.html", "./public/index.html")
	r.StaticFile("/robots.txt", "./public/robots.txt")
	r.GET("/:id", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "success"})
	})
	
	r.Run()
}
```

## Expected vs. actual behavior
```bash
$ curl http://localhost:8080/aaaa # -> shall return 200, does return 200
$ curl http://localhost:8080/iaaa # -> shall return 200, does return 404
$ curl http://localhost:8080/raaa # -> shall return 200, does return 404
```

If I remove the `robots.txt` handler, the third request will be `200` instead. Looks like if my request's path has a prefix, which is also a prefix of one of the other handlers, things get messed up.

Might be a duplicate of https://github.com/gin-gonic/gin/issues/2682.

**Comment by muety** [comment]
In version 1.6.3 the above code yields a panic instead, which, I suppose, relates to the change made in https://github.com/gin-gonic/gin/pull/2663.

```
panic: wildcard segment ':id' conflicts with existing children in path '/:id'
```

**Comment by appleboy** [comment]
Please upgrade to [v1.7.2](https://github.com/gin-gonic/gin/releases/tag/v1.7.2)
