### ISSUE TITLE
request for example of database middleware

### ISSUE THREAD

**Issue by tvmaly** [gin-gonic/gin#270]
Could you provide an examples of using a database connection in middleware?

**Comment by nazwa** [comment]
It works just like any other database connection. If you have a global variable then you can access it directly or pass it as a parameter into the 'constructor'. This might not compile straight away, but you get the idea.

```
func Authentication(con *sql.DB) gin.HandlerFunc {
	query := "SELECT user_id FROM users WHERE token = ?"
	
	return func(c *gin.Context) {
		tokenHeader := c.Request.Header.Get("Token")
		var user_id int

		err := conn.QueryRow(query, token).Scan(&user_id)
		if err != nil {
			// UNAUTHORISED ERROR ERROR ERROR
		}
		c.Set("UserID", user_id)
		c.Next()

	}
}
```

**Comment by tvmaly** [comment]
thank you
