### ISSUE TITLE
Migrating to Protobuf V2 module

### ISSUE THREAD

**Issue by himanshpal** [gin-gonic/gin#2725]
The https://github.com/golang/protobuf module has been superseded by the google.golang.org/protobuf module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. https://github.com/golang/protobuf is now marked as deprecated and gin still uses an older version of plugin

**Comment by ilovesusu** [comment]
https://github.com/golang/protobuf/pull/1306

**Comment by thinkerou** [comment]
#2827 thanks
