### ISSUE TITLE
I tried to use GetInt and GetInt64 to find the integer, but I found it with Query. I don’t want to convert it, just get

### ISSUE THREAD

**Issue by baerwang** [gin-gonic/gin#2753]
127.0.0.1:8080/task/operating?id=618588721544957952&option=3

![16239241528073](https://user-images.githubusercontent.com/52104949/122375863-310e5900-cf96-11eb-9fce-84ba690e1519.png)

**Comment by thinkgos** [comment]
GetInt64() is you set that you store a new key/value pair exclusively for this context, not from query or param. [cast](https://github.com/spf13/cast)  is easy casting from one type to another type when you get a string from query.

**Comment by myml** [comment]
You can use ShouldBindQuery.
```go
func Operating(c *gin.Context) {
	var query struct {
		Option string `form:"option"`
	}
	c.ShouldBindQuery(&query)
	log.Println(query.Option)
}
```
