### ISSUE TITLE
Attaching handlers that occur before hitting the muxer

### ISSUE THREAD

**Issue by itsjamie** [gin-gonic/gin#276]
If we could expose an API method like ```.Before(gin.Handler) ``` that allows a user to wrap the muxer with a handler.

**Comment by techjanitor** [comment]
Isn't that essentially how middleware already behaves?

**Comment by itsjamie** [comment]
Yes, however I believe the first handler is the routing. Right now, I wrap the returned gin.engine, so that I can modify the request method. I couldn't find a way to do that in the gin API. If it isn't exposed that's fine.

**Comment by manucorporat** [comment]
what is the purpose? modifying the request before it hits the muxer?

**Comment by itsjamie** [comment]
Yes.

Currently...

```
router := gin.New()
router.Use(middleware.AuthRequired(loginVerifyKey, *jwtAudience, *loginIssuer, pool))
controllers.UserController.Attach(router)

// The very first thing we do is override the method, then run it through gin
server := middleware.Gzip(router)
server = middleware.MethodHandler(server)

//Finally, register the Router
log.Println(http.ListenAndServe(*port, server))
```

The Gzip and MethodHandler middlewares are standard http.Handler (http.Handler) style functions that wrap gin before the muxer and gin.context takes over.

MethodHandler is just changing the request method based on the form value _method or X-HTTP-Override-Method, purely for clients that can't send certain/custom HTTP verbs easily.

**Comment by manucorporat** [comment]
@itsjamie I think your code is perfectly fine.

Adding a `.Before()` would be hacky.
- Context.Next() would not work as expected.
- Also it could be confusing for developers, what should they use? Before() or Use()
- Gin will work at different layers of abstraction. HTTP mutex and Proxy?

I think your current code looks clean and represents exactly what you want to do. Adding a `.Before()` could introduce more problems. In my opinion it does not worth it.

**Comment by itsjamie** [comment]
Sounds good. :)

**Comment by zannet** [comment]
@itsjamie How to attach the router, may I know how to implement this function controllers.UserController.Attach(router) ?
