### ISSUE TITLE
How to easy handle file upload with gin?

### ISSUE THREAD

**Issue by netroby** [gin-gonic/gin#278]
How to easy handle file upload with gin?
can you show us some example?

**Comment by nazwa** [comment]
This is for images, but the same concept applies for normal files. (can't do backticks on my phone, will fix the formatting later :) )

file, _, err := c.Request.FormFile("file")
x, _, err := image.Decode(file)
// Do something with the image + error handling for above 2 
jpeg.Encode(f, file, &settings)

**Comment by netroby** [comment]
Thanks.
