### ISSUE TITLE
[Bug]mixed param and non-param paths 

### ISSUE THREAD

**Issue by waising** [gin-gonic/gin#2786]
gin version 1.7.2

"/get/abc" = value1
"/get/:param" = value2

GET /get/abc => value1
GET /get/a => value2
GET /get/xyz => value2
GET /get/abcd => 404 (should be value2)

**Comment by zihengCat** [comment]
@waising 
Known issue for wildcard router conflicts. You should avoid writing router rules like this. Try the following: 

```go
router.GET("/api/v1/:param", func(c *gin.Context) {
    if c.Param("param") == "abc" {
        // do something for typical param
    }
    // normal case ...
})
```

**Comment by qm012** [comment]
same mistake as #2762

**Comment by kszafran** [comment]
I wouldn't say it's a "mistake". Isn't this exactly the problem that was supposed to be fixed by the new router?

**Comment by appleboy** [comment]
@qm012 I can reproduce the issue with the latest commit https://github.com/gin-gonic/gin/commit/d4ca9a0fb1211108f0a893634ee01b0006890c16

```go
package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
)

func handler01(c *gin.Context) {
	fmt.Println(c.Params)
	c.String(200, "ok01")
}

func handler02(c *gin.Context) {
	fmt.Println(c.Params)
	c.String(200, "ok02")
}

func main() {
	g := gin.Default()
	g.GET("/get/abc", handler01)
	g.GET("/get/:param", handler02)
	g.Run(":9090")
}
```

result:

```sh
/abc  200 ok02
/a    404
/ab   200 ok02
/xyz  200 ok02
/abcd 200 ok02
```

**Comment by qm012** [comment]
@appleboy Please give me some time. I am trying to solve this problem. There is no problem with the first-level route match, but if the multi-level route is greater than or less than the current path, it will not match the original one

**Comment by appleboy** [comment]
@qm012 Thanks.

@waising @zihengCat We move to https://github.com/gin-gonic/gin/pull/2796 for discussion in the fueture.
