### ISSUE TITLE
Mixed params and exact paths after last slash can cause a 404

### ISSUE THREAD

**Issue by VincentYe123** [gin-gonic/gin#2799]
> We have three routers, as following 

```
Router1 "/get/:id"
Router2 "/get/user_info"
Router3 "/get/uuid"
```

> We test these three routers with some requests:
/get/aID -> Router1
/get/user_info -> Router2
/get/uuid -> Router3

> /get/uID -> 404(Expect Router1)
So, if there are some param starts with the prefix 'u' in this example, it will not get the right router.

## Environment

- go version:1.16.3
- gin version (or commit ref):1.7.2
- operating system:macOS

**Comment by wxning1107** [comment]
+1

**Comment by qm012** [comment]
#2796 has fixed this bug
@appleboy @thinkerou  Do we need to release a new minor version (1.7.3)

**Comment by qm012** [comment]
@wxning1107 @VincentYe123  Use the latest code to see if you have fixed the problem
```shell
go get -u github.com/gin-gonic/gin@master
```

**Comment by appleboy** [comment]
@qm012 Yes, I will bump the new version v1.7.3

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/gin/releases/tag/v1.7.3

**Comment by wxning1107** [comment]
thx
