### ISSUE TITLE
add support to disabe keepalive

### ISSUE THREAD

**Issue by oryband** [gin-gonic/gin#280]
If gin would've used `http.Server`, I could've just done the following:
```go
// s is a http.Server instance
s.SetKeepAlivesEnabled(false)
```
But gin doesn't allow that. So, [how do we accomplish this](https://godoc.org/net/http#Server.SetKeepAlivesEnabled)?

**Comment by bolshoy** [comment]
:+1: 
could be especially useful for scalable REST servers, so single-request connections don't linger.

**Comment by manucorporat** [comment]
https://github.com/gin-gonic/gin#custom-http-configuration

```
	router := gin.Default()

	s := &http.Server{
		Addr:           ":8080",
		Handler:        router,
		ReadTimeout:    10 * time.Second,
		WriteTimeout:   10 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}
	s.SetKeepAlivesEnabled(false)
	s.ListenAndServe()
```

**Comment by oryband** [comment]
@manucorporat amazing and simple. Thanks.

**Comment by palrohitg** [comment]
@manucorporat would be great if we specify, how to configure the custom timeout in seconds example: it node.js we can specify the  keepalive timeout in seconds.
