### ISSUE TITLE
Use dependabot upgrading github.com/gin-gonic/gin-1.7.3 error: checksum mismatch

### ISSUE THREAD

**Issue by sunshineplan** [gin-gonic/gin#2806]
I recently use github dependabot to maintain my repository's dependencies automatically.
But when upgrading gin-gonic v1.7.3, an error was happened when testing. That happened in all my repositories.
For example: https://github.com/sunshineplan/mytasks/runs/3235041486?check_suite_focus=true
```
verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch
downloaded: h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=
go.sum:     h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
```
It tells dependabot automatic generated checksum is not correct.
Is this dependabot's problem, or something happened when releasing?

**Comment by puppywang** [comment]
git.windimg.com/giantart/art-monetd imports
        github.com/gin-gonic/gin: github.com/gin-gonic/gin@v1.7.3: verifying module: checksum mismatch
        downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
        sum.golang.org: h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=


Same issue here, but I got downloaded as yours in go.sum and sum for your downloaded, maybe the binary have been changed ?

**Comment by thynquest** [comment]
Hello 
I have a same problem here. I tried `go clean -modcache` and `go mod tidy` but I get the same error

**Comment by andysnowden** [comment]
Same issue here, tired manually clearing the cache and still happened.

**Comment by thynquest** [comment]
It looks like it is related to the 1.7.3 version. only the 1.7.3 version seems to have that problem. since I do not have specific needs I picked the 1.7.2 version

**Comment by SimonPrague** [comment]
I have the same problem :-S

**Comment by allesan** [comment]
Same problem for me.

**Comment by UnderTreeTech** [comment]
+1

**Comment by 0xtej** [comment]
@thinkerou Please confirm if the bits on the server changed. Why is the checksum different?

**Comment by jivot** [comment]
Encountered the same problem while trying to install go-admin project, which depends on gin v1.7.3
```
github.com/gin-gonic/gin@v1.7.3: verifying module: checksum mismatch
	downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
	sum.golang.org: h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=
```

**Comment by tetsuyanh** [comment]
+1

**Comment by dmmarkov** [comment]
Have the same issue with athens-proxy

```
github.com/gin-gonic/gin@v1.7.3: verifying module: checksum mismatch
	downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
	sum.golang.org: h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```

**Comment by hackersean** [comment]
verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch
	downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
	go.sum:     h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=

**Comment by rapgru** [comment]
Same issue using dependabot-gitlab:
`ERROR: [REDACTED=>gomod] verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch`

**Comment by appleboy** [comment]
Can't reproduce the issue?

```
github.com/gin-gonic/gin v1.7.3 h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=
github.com/gin-gonic/gin v1.7.3/go.mod h1:jD2toBW3GZUr5UMcdrwQA10I7RuaFOl/SGeDjXkfUtY=
```

cc @thinkerou

**Comment by rapgru** [comment]
Note: The 1.7.3 release points to commit https://github.com/gin-gonic/gin/commit/92eeaa4ebbadec2376e2ca5f5749888da1a42e24 which is not part of this repository.

**Comment by appleboy** [comment]
@rapgru I create a new project or upgrade the gin from my old project. All can't reproduce the issue.

**Comment by sunshineplan** [comment]
@appleboy If I upgrade my repo myself, this problem will not happen. It only happens in dependabot in my case. I don't know why dependabot recorded the wrong checksum. Is it possible release was published twice, so dependabot recorded the previous one.

**Comment by SimonPrague** [comment]
Can gin-gonic simply make a new clean release even if no files are changed? It's obviously broken release and it breaks so many apps around. Making a new version number and new release seems like the logical solution.

**Comment by rr-nick-tan** [comment]
same here, even fails on the the simple go get :
```
$ go get github.com/gin-gonic/gin
github.com/gin-gonic/gin@v1.7.3: verifying module: checksum mismatch
        downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
        sum.golang.org: h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by zachspar** [comment]
Having the same issue over here:
```
go: downloading github.com/gin-gonic/gin v1.7.3
go: downloading github.com/jinzhu/now v1.0.1
go: verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch
        downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
        go.sum:     h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=
```

**Comment by appleboy** [comment]
I bump the new version to fix the issue. https://github.com/gin-gonic/gin/releases/tag/v1.7.4 Please help to try.

**Comment by sunshineplan** [comment]
v1.7.4 fixed my problem.

**Comment by SimonPrague** [comment]
Fixed thanks!
