### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by xuxiangyang** [gin-gonic/gin#281]
Hi, I want to learn gin， but I found that examples provided by gin are too small to tell me how to build a real project with gin.
could gin provided some examples like revel or rails? I think that will help lots of people....

**Comment by manucorporat** [comment]
yeah! you are right. can you give one example of something you would like to see?

**Comment by xuxiangyang** [comment]
I think a blog will be ok. MVC，just like rails. I can not write it with gin, you can make the basic directory, write some codes. like posts CURD. I think that I could help you to write the other things, such as comments.

I think we should use gin as api server, so I think we should give a blog with json response

sorry for my English.... I hope I could make a contribution to gin

Thx

**Comment by nguyenthenguyen** [comment]
Me too! I'm beginner! But I write a blog or simple blog use gin in my api server! This is  [my project!](https://github.com/golang-vietnam/forum/blob/master/cmd/server.go)

**Comment by biorisk** [comment]
More examples for beginners is probably a better use of your time, but I'd appreciate some more advanced examples on middleware. Gin has been great for getting up and running quickly and it has saved my project from disaster. However, after about two months of active development, I'm now starting to run into some problems as I start adding middleware from contrib. I'd like to see examples that illustrate how to use gzip, cache, sessions together. I don't understand the framework well enough to prevent them from stepping on each others toes. For example, I can use gzip or cache (in memory), but together, I get complaints from the browser about the compression scheme. Seem like I'm missing something obvious, but I haven't figured it out yet.

**Comment by javierprovecho** [comment]
We will release some examples once gin reach stable v1. I'll keep you updated. ;)

**Comment by no1youknowz** [comment]
Would be nice to see an MVC example when version 2 comes out.

**Comment by appleboy** [comment]
+1
