### ISSUE TITLE
Issues related to unmatched routing and middleware authentication

### ISSUE THREAD

**Issue by TNED** [gin-gonic/gin#2813]
I found that when the middleware is running authentication and other functions that may send out error messages, if the user uses a route that has not been registered for routing, the authentication process of the middleware will be executed. At this time, we are not It is hoped that the logic of authentication is executed, but the client is told that this page does not exist.

**Comment by jimbirthday** [comment]
@TNED 
Can you show your code and request, otherwise you can't troubleshoot

**Comment by TNED** [comment]
`e := gin.New()
	e.Use(func(c *gin.Context) {
		if c.Request.URL.Path != "/not-login" {
			// check login
			c.Abort()
			c.JSON(200, "需要登录")
			return
		}
	})
	e.NoRoute(func(c *gin.Context) {
		c.JSON(404, "Page not Found.")
	})
	e.GET("/not-login", func(c *gin.Context) {
		c.JSON(200, "not-login")
	})
	e.GET("/required-login", func(c *gin.Context) {
		c.JSON(200, "required-login")
	})
	_ = e.Run()`

It is expected that when visiting /not-page, page not found is returned.

**Comment by jimbirthday** [comment]
@TNED 

I think it is only necessary to increase the routing group, and only use middleware in the routing group that requires permission authentication

```
import (
	"github.com/gin-gonic/gin"
)

func main() {
	e := gin.Default()

	e.NoRoute(func(c *gin.Context) {
		c.JSON(404, "Page not Found.")
	})

	group := e.Group("/")
	group.Use(func(c *gin.Context) {
		if c.Request.URL.Path != "/not-login" {
			// check login
			c.Abort()
			c.JSON(200, "need login")
			return
		}
	})
	group.GET("/not-login", func(c *gin.Context) {
		c.JSON(200, "not-login")
	})
	group.GET("/required-login", func(c *gin.Context) {
		c.JSON(200, "required-login")
	})
	_ = e.Run()
}

```
![image](https://user-images.githubusercontent.com/38313933/128664897-e7d3c519-8b21-4e91-b221-96595cf8952d.png)



![image](https://user-images.githubusercontent.com/38313933/128664872-28b101e6-1886-4af0-a989-e644f11393d8.png)

**Comment by TNED** [comment]
> @TNED
> 
> I think it is only necessary to increase the routing group, and only use middleware in the routing group that requires permission authentication
> 
> ```
> import (
> 	"github.com/gin-gonic/gin"
> )
> 
> func main() {
> 	e := gin.Default()
> 
> 	e.NoRoute(func(c *gin.Context) {
> 		c.JSON(404, "Page not Found.")
> 	})
> 
> 	group := e.Group("/")
> 	group.Use(func(c *gin.Context) {
> 		if c.Request.URL.Path != "/not-login" {
> 			// check login
> 			c.Abort()
> 			c.JSON(200, "need login")
> 			return
> 		}
> 	})
> 	group.GET("/not-login", func(c *gin.Context) {
> 		c.JSON(200, "not-login")
> 	})
> 	group.GET("/required-login", func(c *gin.Context) {
> 		c.JSON(200, "required-login")
> 	})
> 	_ = e.Run()
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/38313933/128664897-e7d3c519-8b21-4e91-b221-96595cf8952d.png)
> 
> ![image](https://user-images.githubusercontent.com/38313933/128664872-28b101e6-1886-4af0-a989-e644f11393d8.png)

Yes, I know that you can add relevant middleware to the routing group, but I don’t think this solution can solve this problem. I am visiting a page that does not exist. As long as the page I visit meets the routing group rules, then this problem will appear. NS.

**Comment by TNED** [comment]
@jimbirthday
This is a good idea, but I always feel that something is too much.
