### ISSUE TITLE
HTML templates do not work with contrib/cache

### ISSUE THREAD

**Issue by biorisk** [gin-gonic/gin#283]
If I use templates using gin's default approach, e.g., c.HTML(http.StatusOK, "mytemplate", gin.H{ "values": values }), with the in-memory cache from contrib/cache, the page is delivered correctly the first time, but I get an empty page on subsequent requests. However, if I render the template to a string and use c.HTMLString(http.StatusOK, mystring), subsequent requests are delivered correctly (and are coming from the in memory cache).

**Comment by manucorporat** [comment]
I am investigating this issue

**Comment by biorisk** [comment]
Thank you for taking a look. Any progress? Let me know if you want a working example.

**Comment by appleboy** [comment]
@biorisk Please update https://github.com/gin-contrib/cache
