### ISSUE TITLE
 undefined: sync.Pool

### ISSUE THREAD

**Issue by mignev** [gin-gonic/gin#284]
This is result of `go get github.com/gin-gonic/gin` on MacOS

→ go get github.com/gin-gonic/gin
# github.com/gin-gonic/gin
code/src/github.com/gin-gonic/gin/gin.go:36: undefined: sync.Pool

**Comment by bdwilliams** [comment]
What version of Go is installed?

`go version`

I believe that Gin requires 1.3+

**Comment by mignev** [comment]
Yep my Go installations was old. 1.2.x. Now with the latest version of Go everything is okay! :)

Thanks.
