### ISSUE TITLE
New feature! HTTP streaming

### ISSUE THREAD

**Issue by manucorporat** [gin-gonic/gin#285]
I am experimenting with several new APIs:

```
c.Stream(stepFunction)
c.SSEvent(name, message)
```

I expect this will help developers to build simple and stable streaming correctly with Go and Gin.

I created a realtime-chat example: https://github.com/gin-gonic/gin/blob/develop/examples/realtime-chat/main.go

The implementation: 
https://github.com/gin-gonic/gin/blob/470b7e1010b3ceee8574fda670143f73710a04e5/context.go#L383-L412
https://github.com/gin-gonic/gin/blob/470b7e1010b3ceee8574fda670143f73710a04e5/render/ssevent.go

Feedback is welcome!

**Comment by manucorporat** [comment]
`c.Stream()` is a general purpose abstraction for streaming, you can stream anything, text, json, a video!
this is NOT websockets, it is a HTML request, the connection is never upgraded.
The objective of streaming is not full-duplex.

`c.SSEvent()` is an implementation of Server-Sent Events! a very cool and simple tool for event-driven streaming. http://www.html5rocks.com/en/tutorials/eventsource/basics/

**Comment by bradrydzewski** [comment]
I've been playing with this the past few days and it is great. The server-sent-event implementation was really simple to get working. I would love to see the `Event.Id` and `Event.Retry` parameters exposed through gin. I ended just using the `sse` library directly in conjunction with the `Stream`, which worked fine as well:

```Go
	var id int
	c.Stream(func(w io.Writer) bool {
		id++
		sse.Encode(w, sse.Event{
			Id: strconv.Itoa(id),
			Event: "message",
			Data:  ...,
		})
		return true
	})

**Comment by manucorporat** [comment]
I am redesigning the c.Render() function. c.Render() is the parent of c.JSON, c.XML, c.HTML
right now it was "slow" to use that function, since it uses variadic arguments (compiler inlining and an additional heap allocation is required). Also I used `interface{}` a lot, what was unsafe, due the compiler can not give 

I have proposed a new API.

- No variadic
- No heap allocation
- Static typed (you can detect bugs at compiler time)
- New API.

The new API is what you probably are interested in:

you can still use `c.SSEvent(code, eventName, data)`

or use sse.Event directly:
```go
c.Render(200, sse.Event{
    Name: "my event,
    Id: "1255",
    Data: data,
})
```

**Comment by manucorporat** [comment]
Another examples:
c.JSON is a shortcut for 

```go
c.Render(200, render.JSON{data})
```

The Gin API is changing a lot right now, but it will be frozen in v1.

https://github.com/gin-gonic/gin/commit/947b53d4a26f24d9842fd1539e8a65fee590a8a8
https://github.com/manucorporat/sse/commit/320b4a6ccac258cfc2479ef91a27505d98c96949

**Comment by djamelfel** [comment]
@manucorporat: they are a non sence for me, sse.Event cannot be used as type render.Render in argument to c.Render

**Comment by manucorporat** [comment]
@djamelfel are you sure? yes, it can be.

Just tried:
```go
	r.GET("/ping", func(c *gin.Context) {
		c.Render(-1, sse.Event{
			Event: "hola",
		})
	})
```

**Comment by djamelfel** [comment]
You're right, it's because i used an old version of gin.

**Comment by dalu** [comment]
For me this just isn't working either behind nginx or directly.
The responses either get buffered and never sent or sent non-stop, or when adding a sleep of 1 second sent randomly in heaps.

**Comment by metal3d** [comment]
Same problem as @dalu excepting that the problem for me is only behind nginx. I cannot "flush" to output.

**Comment by dalu** [comment]
@metal3d it is. I wrote a blog post about it
https://blog.icod.de/2018/12/17/angular-eventsource-go-and-wasted-lifetime/

**Comment by metal3d** [comment]
@dalu sorry for the latency, Actually I found the exact same solution myself weeks ago :)

Thanks a lot.

**Comment by berlinsaint** [comment]
> @dalu sorry for the latency, Actually I found the exact same solution myself weeks ago :)
> 
> Thanks a lot.

@metal3d  what's the solution? can you describe it ?
