### ISSUE TITLE
Expose group absolutePath 

### ISSUE THREAD

**Issue by osiloke** [gin-gonic/gin#286]
Hi,
I would like to have access to a groups absolutePath so that i can generate reverse url. Is there any reason why this is not exposed.

Thanks

**Comment by manucorporat** [comment]
Can you provide a sample code of how you would use `AbsolutePath`?

**Comment by osiloke** [comment]
Sure,
For example, when i create a group for an auth handler and then decide to get the full url path to a password reset link. Something similar to the following. You will notice that i need absolutepath only in a nested group which gin allows anyway.

main.go
```
router := gin.New() 
some_group := router.Group("api/v1")
some_group.GET("bleh", handler)
authHandler := AuthHandler{some_group.Group("auth")}
authHandler.Routes()
```

authHandler.go
```
import (
  "progwebtech.com/resource/worksmart/configvars" //global config which can be set from anywhere
...
)
type AuthHandler struct{
   RouterGroup         *gin.RouterGroup
}

func (a *AuthHandler) Routes(){ 
   a.RouterGroup.GET("reset/:token", handler)
}
...
func (a *AuthHandler) GenerateEmail(){ 
  var token = "blah"
   var reset_url = configvars.Get("public_url")  + a.RouterGroup.AbsolutePath + reverse("reset/:token", token)
   email.Send("Please reset at {{.url}}", url)
}
```

**Comment by manucorporat** [comment]
mmmh ok. How about to expose it as BasePath? probably absolute path is misleading

what do you think?

**Comment by manucorporat** [comment]
https://github.com/gin-gonic/gin/commit/3066c3575440ea1f5d9a9633ce889c15101eb117

**Comment by manucorporat** [comment]
@osiloke it's done! https://github.com/gin-gonic/gin/commit/3066c3575440ea1f5d9a9633ce889c15101eb117

**Comment by osiloke** [comment]
Sweet, thanks!

**Comment by manucorporat** [comment]
@osiloke I may make the variable unexpected again. this was a bad solution :( but! I can expose a method called `BasePath()`.

How does it sounds?

**Comment by osiloke** [comment]
Thats fine, that would be easier to refactor. May i ask why you decided to go against exporting the var?

**Comment by manucorporat** [comment]
@osiloke I want to reduce side effects as much as possible, if the gin API protects against side effect changes, everybody's code is easier to debug and more secure.

Exporting the var, means that their value can be changed anytime.

**Comment by thinkerou** [comment]
closing, issue have completed.
