### ISSUE TITLE
How to convert UTC time to my local time?

### ISSUE THREAD

**Issue by shmilyhurt** [gin-gonic/gin#2864]
hello:
a model is:
```
type Plan struct {
	Id       int       `gorm:"primary_key"`
	User     int       `gorm:"column:user;not null"`
	Title    string    `gorm:"column:title;not null;size:128"`
	Start    string    `gorm:"type:date;column:start"`
	End      string    `gorm:"type:date;column:end"`
	Created  time.Time `gorm:"autoCreateTime;column:created;type:datetime"`
	IsDelete int       `gorm:"column:is_delete;default:1"`
}
```
input is:
```
type PlanInput struct {
	User  int    `json:"user" form:"user"  binding:""`
	Title string `json:"title" form:"title"  binding:""`
	Start string `json:"start" form:"start"  binding:"" gorm:"type:date;column:start"  `
	End   string `json:"end" form:"end"  binding:"" gorm:"type:date;column:end"`
}
```

but when I send  datetime from vue 
this:
![image](https://user-images.githubusercontent.com/55658709/132995343-83be4244-371f-443e-a891-c60e9d762654.png)
I got datetime in gin:
![image](https://user-images.githubusercontent.com/55658709/132995274-2af5763c-a59e-40ef-bb73-cdd1ad2764d4.png)

Obviously, this is a time zone issue。
How to solve this problem?
And I also wonder if there is a way to set the time zone globally?
Thanks!

**Comment by Asuha-a** [comment]
jftr, You should store datetime in UTC unless there is some particular reason.
That's why gin automatically converts local time to UTC.

**Comment by gouguoyin** [comment]
You can try https://github.com/golang-module/carbon

**Comment by shmilyhurt** [comment]
> You can try https://github.com/golang-module/carbon

`carbon.Parse("2021-09-07T16:00:00.000Z", carbon.Shanghai).ToDateTimeString()`=>2021-09-08 00:00:00
It looks like it's easy to switch times.
But does this also mean that each time the storage time needs to be converted ?
There is no way to change time zones globally, but thank you all the same
