### ISSUE TITLE
Why not use master branch

### ISSUE THREAD

**Issue by leedstyh** [gin-gonic/gin#288]
godoc.org use master brach, so we always get old docs if you do not update master branch

**Comment by manucorporat** [comment]
We are doing tons of API changes. Gin is under heavy development, we have added tons of features, complete suite of unit tests, bug fixes, better API. BUT! gin v1. is very close and it will froze the API.

I want to release a v1.0rc1 this week, we will merge in in master. After this point we will merge into master very frequently, but we will continue working in develop as a normal basis. This allow us to move faster, pushing new features without the fear of breaking someone's project.

**Comment by leedstyh** [comment]
OK, and good to know v1 is coming.

Nice job!

**Comment by manucorporat** [comment]
Check out the changelog for v1:
https://github.com/gin-gonic/gin/blob/caa75c620153398c334dba46601a92dc9cc00c5d/CHANGELOG.md

**Comment by manucorporat** [comment]
@leedstyh Gin v1.0rc1 released and merged in master!
https://github.com/gin-gonic/gin/releases/tag/v1.0rc1
