### ISSUE TITLE
Logger middleware causes `SIGTRAP: trace trap` when used with gorm and sqlite driver

### ISSUE THREAD

**Issue by jeffbmartinez** [gin-gonic/gin#2890]
## Description

The `gin.Logger()` middleware seems to cause a crash with a `SIGTRAP: trace trap` when combined with Gorm's sqlite driver. There is a good chance it is a processor/OS specific issue, but I can't test on other environments at the moment.

I was able to trace the issue to a call to `isatty.IsTerminal(w.Fd())` at [logger.go:220](https://github.com/gin-gonic/gin/blob/v1.7.4/logger.go#L220). `w` ends up being `os.Stdout` for the default logger, and it seems this call is causing the crash, at least on my system.

The culprit is most likely the `isatty` library, which I demonstrate below. I'll open a bug ticket there too, but wanted to post here to let you know your dependency will need updating if/when a fix becomes available.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
	_ "gorm.io/driver/sqlite"
)

func main() {
	gin.Default()

	// Also breaks with:
	// router := gin.New()
	// router.Use(gin.Logger())
}
```

The following further simplified code also has a similar crash, which points to the `mattn/go-isatty` that `gin` is using internally:

```
package main

import (
	"os"

	"github.com/mattn/go-isatty"
	_ "gorm.io/driver/sqlite"
)

func main() {
	isatty.IsTerminal(os.Stdout.Fd())
}
```

## Expectations

`gin.Default()` is usable, shouldn't crash when combined with gorm and sqlite.

## Actual result

Actual result is similar to following:

```
jeff:~/code/gin-logger-sqlite-sigtrap$ go run .
SIGTRAP: trace trap
PC=0x7fff20438ca4 m=0 sigcode=1

goroutine 0 [idle]:
syscall.syscall(0x4400ae0, 0x1, 0x40487413, 0xc00029fe90)
	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00029fe00 sp=0xc00029fde0 pc=0x406103b
syscall.syscall(0x40aa686, 0xc00004c678, 0xc00029feb8, 0x40aa5b8)
	<autogenerated>:1 +0x26 fp=0xc00029fe48 sp=0xc00029fe00 pc=0x4066d46
golang.org/x/sys/unix.ioctl(0x46bf9c8, 0x4, 0x1000000000006)
	/Users/jeff/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc00029fe78 sp=0xc00029fe48 pc=0x4400779
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/jeff/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/ioctl.go:63
github.com/mattn/go-isatty.IsTerminal(0x46bf9c8)
	/Users/jeff/go/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc00029fee8 sp=0xc00029fe78 pc=0x4400b90
main.main()
	/Users/jeff/code/gin-logger-sqlite-sigtrap/gin-logger-sqlite-sigtrap.go:20 +0xce fp=0xc00029ff80 sp=0xc00029fee8 pc=0x44bfb0e
runtime.main()
	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/proc.go:255 +0x227 fp=0xc00029ffe0 sp=0xc00029ff80 pc=0x4036ca7
runtime.goexit()
	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00029ffe8 sp=0xc00029ffe0 pc=0x40646e1

goroutine 1 [syscall]:
syscall.syscall(0x4400ae0, 0x1, 0x40487413, 0xc00029fe90)
	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00029fe00 sp=0xc00029fde0 pc=0x406103b
syscall.syscall(0x40aa686, 0xc00004c678, 0xc00029feb8, 0x40aa5b8)
	<autogenerated>:1 +0x26 fp=0xc00029fe48 sp=0xc00029fe00 pc=0x4066d46
golang.org/x/sys/unix.ioctl(0x46bf9c8, 0x4, 0x1000000000006)
	/Users/jeff/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc00029fe78 sp=0xc00029fe48 pc=0x4400779
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/jeff/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/ioctl.go:63
github.com/mattn/go-isatty.IsTerminal(0x46bf9c8)
	/Users/jeff/go/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc00029fee8 sp=0xc00029fe78 pc=0x4400b90
main.main()
	/Users/jeff/code/gin-logger-sqlite-sigtrap/gin-logger-sqlite-sigtrap.go:20 +0xce fp=0xc00029ff80 sp=0xc00029fee8 pc=0x44bfb0e
runtime.main()
	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/proc.go:255 +0x227 fp=0xc00029ffe0 sp=0xc00029ff80 pc=0x4036ca7
runtime.goexit()
	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00029ffe8 sp=0xc00029ffe0 pc=0x40646e1

rax    0x0
rbx    0xc00029fe00
rcx    0x4400ae0
rdx    0xc00029fe90
rdi    0x1
rsi    0x40487413
rbp    0x208f0f6b0
rsp    0x208f0f678
r8     0x4afc220
r9     0x0
r10    0x2ccb3b98
r11    0x4a98000
r12    0x0
r13    0x0
r14    0xc0000001a0
r15    0x2c925b55
rip    0x7fff20438ca4
rflags 0x202
cs     0x2b
fs     0x0
gs     0x0
exit status 2
jeff:~/code/gin-logger-sqlite-sigtrap$
```

## Environment

- go version: `go1.17.1 darwin/amd64`
- gin version (or commit ref): `github.com/gin-gonic/gin v1.7.4`
- operating system: `macOS Big Sur, version 11.5.2` on M1 processor

**Comment by jeffbmartinez** [comment]
Update: I decided to nuke my system and reinstall all dependencies for my project and upgrade and the problem is gone. I'll close this but leave it in place in case someone else gets unlucky and finds a similar problem.

I didn't go library by library, but I noticed I had a few slightly out of date sqlite libs. My money is on one of those not playing nicely with `isatty`.

**Comment by naisk133** [comment]
@jeffbmartinez 
Hi Jeff, I am facing the same problem on my M1 Macbook but I'm not sure how can I nuke my system and reinstall all dependencies like you have mentioned. It would be great if you can please explain about it more how to solve this issue.
Thank you so much in advanced :)

**Comment by jeffbmartinez** [comment]
By "nuke" I mean I deleted all the libraries from my computer and reinstalled them.

You might try just updating all libraries first, and see if that resolves it for you. For example:
```
go get -u
go mod tidy
```

Good luck!

**Comment by windvalley** [comment]
> 



> By "nuke" I mean I deleted all the libraries from my computer and reinstalled them.
> 
> You might try just updating all libraries first, and see if that resolves it for you. For example:
> 
> ```
> go get -u
> go mod tidy
> ```
> 
> Good luck!

Thanks a lot!  This works for me.
