### ISSUE TITLE
How to limit upload file size

### ISSUE THREAD

**Issue by hasaranga** [gin-gonic/gin#2898]
how to limit the upload file size to save the server bandwidth?

**Comment by hasaranga** [comment]
Is is possible to change the value of **maxBodyBytes**  according to the token posted by the user?
`token := c.PostForm("token")`

**Comment by hasaranga** [comment]
No, actually it's the **session id** posted by the user. I want to limit the upload size according to the **session id**. But the issue is when using `c.PostForm("token")` within the middleware, MaxBytesReader ignores the size limit.

`func bodySizeMiddleware(c *gin.Context) {

	_ = c.PostForm("token") // this line causes MaxBytesReader to ignore maxBytes! Why?

	var maxBytes int64 = 1024 * 1024 * 5 // 5MB

	var w http.ResponseWriter = c.Writer
	c.Request.Body = http.MaxBytesReader(w, c.Request.Body, maxBytes)

	c.Next()
}`

**Comment by hasaranga** [comment]
Just got another simple idea: generate a one-time `upload token` for a session id. When uploading, the client passes it on URL and we can get it from `c.Query("utoken")` in the middleware as you mentioned earlier. Client also passes its session id in `PostForm` to validate the upload. In the middleware we can change the `maxBytes` according to the `upload token`. Once the upload saved, `upload token` will be removed from the database. Each new upload require to get a new `upload token` from the server.

How is that? Can you find any flows in this mechanism?

**Comment by hasaranga** [comment]
Solution: put the session id in headers. Then call `token := c.Request.Header.Get("token")` within the middleware.

Thanks lot RcrdBrt for the support!

**Comment by appleboy** [comment]
See the [example](https://github.com/gin-gonic/examples/tree/master/upload-file/limit-bytes)
