### ISSUE TITLE
Issue with custom CORS header middleware

### ISSUE THREAD

**Issue by mattatcha** [gin-gonic/gin#29]
I have created a the following middleware function but It doesn't seem to be working properly.  When I do an options request I get a 404 and I get `http: multiple response.WriteHeader calls` in my console.

```
func CORSMiddleware() gin.HandlerFunc {
    return func(c *gin.Context) {

        c.Writer.Header().Set("Content-Type", "application/json")
        c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
        c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
        if c.Req.Method == "OPTIONS" {
            fmt.Println("options")
            c.Abort(200)
            return
        }
        // c.Next()
    }
}
```

I have mounted it as the before anything else with the following.

```
r.Use(CORSMiddleware())
```

**Comment by qwertmax** [comment]
has someone successful experience with cors?

**Comment by nazwa** [comment]
@qwertmax - Super basic approach but works very well.

```
    r.Use(func(c *gin.Context) {
               // Run this on all requests   
               // Should be moved to a proper middleware 
		c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type,Token")
		c.Next()
	})

	r.OPTIONS("/*cors", func(c *gin.Context) {
              // Empty 200 response
	})

```

**Comment by qwertmax** [comment]
I'm using smth like this right now.

    func CORSMiddleware() gin.HandlerFunc {
	     return func(c *gin.Context) {
     		     c.Writer.Header().Set("Access-Control-Allow-Origin", "http://domain.com")
	     	     c.Writer.Header().Set("Access-Control-Max-Age", "86400")
		     c.Writer.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE, UPDATE")
		     c.Writer.Header().Set("Access-Control-Allow-Headers", "Origin, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		     c.Writer.Header().Set("Access-Control-Expose-Headers", "Content-Length")
		     c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")

		     if c.Request.Method == "OPTIONS" {
			     fmt.Println("OPTIONS")
			     c.AbortWithStatus(200)
		     } else {
			     c.Next()
		     }
	     }
     }

**Comment by shivkumarsingh7** [comment]
Hello I am getting multiple headers on 2 nd request.
<img width="770" alt="screen shot 2018-08-17 at 4 43 18 pm" src="https://user-images.githubusercontent.com/10324098/44263499-d4feb580-a23c-11e8-9541-06726317eb26.png">

**Comment by qwertmax** [comment]
@shivkumarsingh7 can you describe a little bit more your problem?

**Comment by shivkumarsingh7** [comment]
I am using middleware with below code

`func CORSMiddleware() gin.HandlerFunc {
     return func(c *gin.Context) {
         c.Writer.Header().Set("Access-Control-Allow-Origin", "http://domain.com")
         c.Writer.Header().Set("Access-Control-Max-Age", "86400")
         c.Writer.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE, UPDATE")
         c.Writer.Header().Set("Access-Control-Allow-Headers", "Origin, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
         c.Writer.Header().Set("Access-Control-Expose-Headers", "Content-Length")
         c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")

         if c.Request.Method == "OPTIONS" {
             fmt.Println("OPTIONS")
             c.AbortWithStatus(200)
         } else {
             c.Next()
         }
     }
 }


r.Use(CORSMiddleware())`

It's working properly with package "github.com/gin-gonic/gin" but When I am changing package to "gopkg.in/gin-gonic/gin.v1" I am getting multiple headers on 2nd request.

**Comment by qwertmax** [comment]
@shivkumarsingh7 may be because you receive 2 responses (OPTIONS and than GET/POST/whatever) ?

**Comment by shivkumarsingh7** [comment]
@qwertmax apart from the option and one get, post, put or delete I am getting header twice in one response only

**Comment by g10guang** [comment]
Deal with http OPTIONS method currently:

```go
engine := gin.Default() // return *gin.Engine
engine.Use(CorsMW)        // incomplete
group := engine.Group("/prefix") // return *gin.RouterGroup
group.GET("/path", handlerFunc)
```

404 Happend:
```go
engine := gin.Default()
engine := engine.Group("/prefix")
group.Use(CorsMW)
group.GET("/path", handlerFunc)
```

- Request will be processed by Engine's Middleware **before** matches the route config.
- Request will be processed by RouterGroup's Middleware **after** matches the route config.

So we use CorsMiddleware in *gin.Engine will process all CORS correctly.
