### ISSUE TITLE
There are still some bugs about router

### ISSUE THREAD

**Issue by dploop** [gin-gonic/gin#2900]
The #2767 didn't solve the problem completely, here is how to reproduce:

```golang
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func main() {
	router := gin.Default()
	router.GET("/a/b", handler("/a/b"))
	router.GET("/a/:p/c", handler("/a/:p/c"))
	router.GET("/:p/d", handler("/:p/d"))
	_ = router.Run(":8080")
}

func handler(s string) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.String(http.StatusOK, s)
	}
}
```

## Expectations

```
$ curl 'http://127.0.0.1:8080/a/d'
/:p/d
```

## Actual result

```
$ curl 'http://127.0.0.1:8080/a/d'
404 page not found
```

## Suggestion
The backtracking progress need a stack for help, and it can't be solved by just caching the latest node.
So there are two ways:

- /:p and /a can not appear at the same time, just like httprouter
- we should use a stack data structure to help the backtracking

**Comment by Crushla** [comment]
I have no  this mistake here
![选区_006](https://user-images.githubusercontent.com/42992376/140674669-11026782-49a3-43de-a35a-e0da2a068f99.png)

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases
