### ISSUE TITLE
Would you please make a release which fix  #2697  c.ClientIP() bug in #2832

### ISSUE THREAD

**Issue by menduo** [gin-gonic/gin#2909]
@appleboy Would you please make a release which fix  #2697  c.ClientIP() bug in #2832 

Thanks.

- With issues:
  - Would you please make a release which fix  #2697  c.ClientIP() bug in #2832

## Environment

- go version:
- gin version (or commit ref): v1.7.4
- operating system:

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases
