### ISSUE TITLE
gin.Context.JSON with a struct as reply always give 500 error

### ISSUE THREAD

**Issue by norx85** [gin-gonic/gin#291]
When i try to use gin.Context.JSON(200, instanceOfAStruct) the server always give a 500 error, as in this example:
```
type ExampleResp struct {
	Success bool `json:"success"`
	Data string `json:"data"`
}

func getRequestHandler(c *gin.Context) {
	resp := ExampleResp {
		Success : true,
		Data : "ssdfsd",
	}
	c.JSON(200, resp)
}
```

This example give me a 500 error with no message and no log in the console output (even if in gin.DebugMode)

**Comment by manucorporat** [comment]
@norx85 I can not reproduce your problem. could you checkout the `develop` branch and try again?
