### ISSUE TITLE
[Discussion] How to retrieve the token set using `c.SetCookie`

### ISSUE THREAD

**Issue by afzal442** [gin-gonic/gin#2910]
`func (c *Context) Cookie(name string) (string, error)`

## Description

I tried to retrieve my cookie using that function but failed to get it. Getting error: `http: named cookie not present`

Could you suggest to me any solution? It would be great.

## How to reproduce

I add here part of my snippet for the time being;

```
c.SetCookie("token", token, 60*60*24, "/", "localhost", false, true)

c, err := c.Cookie("token")
fmt.Println(c, err)
```

I tried out with working example, it seems no working;

- https://github.com/gin-gonic/gin#set-and-get-a-cookie
O/P: Cookie Value: NotSet

Expected: Some value
## Environment

- go version:
- gin version (or commit ref):
- operating system:

**Comment by afzal442** [comment]
Any help would be appreciated. Thanks.

// @RcrdBrt, @kszafran

**Comment by kszafran** [comment]
Take a look at the source code of `SetCookie`: https://github.com/gin-gonic/gin/blob/master/context.go#L897 It pretty much simply calls `http.SetCookie`: https://github.com/golang/go/blob/master/src/net/http/cookie.go#L168, which formats the cookie and adds it to response headers.

If you really have to, you could call `c.Writer.Header().Values("Set-Cookie")` (where `c` is the `*gin.Context`), which will give you all the cookies set to be returned, look for the one you need, and parse it. There does not seems to be built-in support for parsing Set-Cookie headers in the Go standard library, though (https://github.com/golang/go/issues/25194), so you might need to parse it yourself or look for third party libs.
