### ISSUE TITLE
Using http.Handler?

### ISSUE THREAD

**Issue by techjanitor** [gin-gonic/gin#293]
I'd like to use something like authboss that has its own http.Handler:
https://godoc.org/gopkg.in/authboss.v0#Authboss.NewRouter

With Gorilla Mux you can attach the handler to a routegroup like so:
```
mux.PathPrefix("/auth").Handler(ab.NewRouter())
```

I see httprouter has this functionality as well:
http://godoc.org/github.com/julienschmidt/httprouter#Router.Handler

Can you do something similar with Gin? If I just wrapped it in a context would it handle the routing correctly still? Thanks!

**Comment by manucorporat** [comment]
I just added a Wrap() function to help developers with this problem.
https://github.com/gin-gonic/gin/commit/4f855faef2b0b87b51fe03e71f0e07aea3e45ea3

```go
router := gin.Default()
router.GET("/auth/*w", gin.Wrap(ab.NewRouter())
// ...
```

**Comment by manucorporat** [comment]
ok, I am testing a new Any() router that matches the all the standard HTTP methods.
```go
router := gin.Default()
router.Any("/auth/*w", gin.Wrap(ab.NewRouter())
```

**Comment by techjanitor** [comment]
Cool thanks. I didn't realize you guys had dumped httprouter. ;D

**Comment by manucorporat** [comment]
@techjanitor v1 is using a modified version of HttpRouter integrated in the repo :)
btw, probably gin.Wrap() does not help you... because I created it for wrapping `http.HandlerFunc`, not `http.Handler`.

How about this?
```go
func WrapF(f http.HandlerFunc) HandlerFunc {
	return func(c *Context) {
		f(c.Writer, c.Request)
	}
}

func WrapH(h http.Handler) HandlerFunc {
	return func(c *Context) {
		h.ServeHTTP(c.Writer, c.Request)
	}
}
```

**Comment by manucorporat** [comment]
Since, ab.NewRouter() returns a `http.Handler`, you would use:

```go
router.Any("/auth/*w", gin.WrapH(ab.NewRouter())
```

**Comment by techjanitor** [comment]
Thank you for implementing this, but maybe they should be named HandlerFunc and Handler? That seems to be a kind of standard in other routing apis, and the current names are kind of ambiguous. It may prevent some questions in the future. ;D

**Comment by manucorporat** [comment]
I know... but HandlerFunc and Handler are already taken... also HandleFunc usually means the callback itself. so it would be still confusing.

I chose a short name because most of the people will use it inlined.
```go
router.GET("/path", gin.WrapF(myhandler))
```

so I didn't want to overload the people's code.
(same idea under the "gin" name)

Anyway this is still open to changes, I am going to reopen the issue, so people can give their 2 cents.

**Comment by techjanitor** [comment]
Would it be possible to make it a method on RouterGroup? Like

```
func (group *RouterGroup) Handler(handler http.Handler) {
	group.handle("Any", "*", WrapH(handler))
}
```


```
auth := r.Group("/auth").Handler(ab.NewRouter())
```

**Comment by ralph327** [comment]
What about changing WrapH() and WrapF() to NetHandler() and NetHandlerFunc()? This way it's a little more obvious that it's a wrapper for net/http.

**Comment by manucorporat** [comment]
@ralph327 maybe... i just don't like `NetHandlerFunc` and `NetHandler` seem too long. and another problem: ~~developers~~ humans usually expect nouns for types and verbs for functions.

@techjanitor I don't really want this to be a "feature", this is just a helper.
In addition, there is another method called `Handle`:
```go
group.Handle("GET", "/path/", handler)
```

so addition, something called `Handler` and uses Any() doesn't sound like a good idea. For this issue better to be explicit.

**Comment by alehano** [comment]
What about using http.Handler as a middleware?

**Comment by manucorporat** [comment]
@alehano same thing.

```go
router.Use(gin.WrapH(yourHttpHandler))
```

WrapH Just does:

```go 
handler.ServeHTTP(context.Writer, context.Request)
```

**Comment by alehano** [comment]
I have middleware like 
```
Mw(h http.Handler) http.Handler{}
```

**Comment by manucorporat** [comment]
@alehano gin has built-in support for middlewares

**Comment by alehano** [comment]
For example I want to use https://github.com/thoas/stats
It has Handler(h http.Handler) http.Handler

**Comment by alehano** [comment]
For example, I want github.com/justinas/nosurf  in a group.
There is a method nosurf.NewPure(handler http.Handler) http.Handler

**Comment by dalu** [comment]
how about
`WrapHandlerFunc` and `WrapHandler`

**Comment by robvdl** [comment]
I haven't been able to figure out how to use nosurf as a middleware either, but I can wrap the entire router using nosurf.NewPure(router) and start up the Gin app this way which works:

``` go
router := gin.Default()
http.ListenAndServe(":8080", nosurf.NewPure(router))
```

**Comment by robvdl** [comment]
If anyone knows how to wrap nosurf as a Gin middleware, please let me know, I have been trying and trying this for hours already and all I just can't seem to figure out is how to wrap nosurf as a Gin middleware.

I tried:

``` go
r := gin.Default()
r.Use(gin.WrapH(nosurf.NewPure))
r.Use(gin.WrapF(nosurf.NewPure))
r.Use(gin.WrapH(nosurf.New))
r.Use(gin.WrapF(nosurf.New))
```

None of the above work.

@manucorporat sorry to bother you and maybe we want to move this to a new issue, but it would be really useful to have some info on how to get nosurf working, wrapped as a Gin middleware, as nosurf is possibly *the* most used csrf middleware used in Go applications it's quite important to have a guide. In fact, it was one of the very first things I tried to get going in my Gin app and probably many others are trying this out too reading previous comments.

All I could get going, is wrap the entire router object using the example in my previous comment.

However, I really want to see if this can be wrapped as a Gin middleware.

**Comment by alehano** [comment]
+1

**Comment by lawlite** [comment]
+1

**Comment by kamac** [comment]
+1

**Comment by dre1080** [comment]
:+1:

**Comment by calle-gunnarsson** [comment]
+1

**Comment by webus** [comment]
+1

**Comment by iyee** [comment]
+1

**Comment by Depado** [comment]
+1

**Comment by dom3k** [comment]
+1

**Comment by turtlemonvh** [comment]
Similar issue: I was trying to wrap https://github.com/NYTimes/gziphandler, which has this signature:

```go
func GzipHandler(h http.Handler) http.Handler
```

I came up with this pattern: https://gist.github.com/turtlemonvh/6cd23ef13e1e290717ef, inlined below:

```go
type NextRequestHandler struct{
	c *gin.Context
}

// Run the next request in the middleware chain and return
// See: https://godoc.org/github.com/gin-gonic/gin#Context.Next
func (h *NextRequestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.c.Next()
}

// Wrap something that accepts an http.Handler, returns an http.Handler
func WrapHH(hh func(h http.Handler) http.Handler) gin.HandlerFunc {
	// Steps:
	// - create an http handler to pass `hh`
	// - call `hh` with the http handler, which returns a function
	// - call the ServeHTTP method of the resulting function to run the rest of the middleware chain

	return func(c *gin.Context) {
		hh(&NextRequestHandler{c}).ServeHTTP(c.Writer, c.Request)
	}
}
```

**Comment by turtlemonvh** [comment]
That method doesn't completely work for more complex request handlers that return a wrapped `http.ResponseWriter` in the call to `ServeHTTP` for downstream requests.

I fixed that by wrapping the response writer in `NextRequestHandler.ServeHTTP`.

That implementation is in [the gist](https://gist.github.com/turtlemonvh/6cd23ef13e1e290717ef).

**Comment by turtlemonvh** [comment]
It's a package now: https://github.com/turtlemonvh/gin-wraphh

**Comment by gwatts** [comment]
To add a note to a closed issue, i wrote my own adapter for middleware which leverages the request context to pass state down the chain and does not then create a new handler on each request:

https://github.com/gwatts/gin-adapter

You can then do:
```golang
engine.Use(adapter.Wrap(nosurf.NewPure)) 
```

or, if you  want to configure the middleware, you can get access to the handler to pass to the middleware:

```golang
nextHandler, wrapper := adapter.New()
ns := nosurf.New(nextHandler)
ns.SetFailureHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    http.Error(w, "Custom error about invalid CSRF tokens", http.StatusBadRequest)
}))
engine.Use(wrapper(ns)) 
```

**Comment by HazCod** [comment]
A shame that this is not possible out-of-the-box. Thanks @gwatts!

**Comment by Aroaming** [comment]
very good
