### ISSUE TITLE
Why not release version 1.7.5?

### ISSUE THREAD

**Issue by haiyux** [gin-gonic/gin#2932]
We want to use clientip, but not used Run().

**Comment by bnisarg1** [comment]
When 1.7.5 will be released ,  will this issue will be resolved?
https://github.com/gin-gonic/gin/issues/2473

**Comment by Bogon** [comment]
？？？

**Comment by appleboy** [comment]
I will take it.

**Comment by menduo** [comment]
Yes, still waiting for #2909

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases

**Comment by haiyux** [comment]
ok, and i thank you！

**Comment by menduo** [comment]
Thank you, it was a bit late, but finally caught up.
