### ISSUE TITLE
There is no func SetTrustedProxies in release 1.7.4

### ISSUE THREAD

**Issue by kaibox-git** [gin-gonic/gin#2939]
Try to inspect /gin.go
If you switch to 
go get -u github.com/gin-gonic/gin@master
you'll find it, but by tag 1.7.2

**Comment by Bisstocuz** [comment]
It seems that @appleboy is preparing for it. I think the new release will be published soon.
https://github.com/gin-gonic/gin/issues/2862#issuecomment-969834900

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases
