### ISSUE TITLE
why the constant 'Version' defined in version.go of v1.7.4  is "v1.7.3"?

### ISSUE THREAD

**Issue by jincheng9** [gin-gonic/gin#2940]
# Description
why the constant Version defined in version.go of v1.7.4  is "v1.7.3"?
![image](https://user-images.githubusercontent.com/1326520/141766068-b41af069-8f2d-4f3f-a94d-3bf82226aa88.png)

## Expectations
The value of constant Version should be "v1.7.4" which matches with the release version.

## Environment
- gin version (or commit ref): v1.7.4

**Comment by thinkerou** [comment]
@jincheng9 this is an issue, thanks!

**Comment by jincheng9** [comment]
@thinkerou thanks for the reply.  In some scenarios, developers may log the version of dependency modules for debugging issues. Hope the next release can fix this bug.  :)

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases

**Comment by jincheng9** [comment]
@thinkerou thanks~
