### ISSUE TITLE
go get -u github.com/gin-gonic/gin errror

### ISSUE THREAD

**Issue by buqiuwenda** [gin-gonic/gin#2949]
/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine)
../../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine
../../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine
../../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath)

**Comment by princefishthrower** [comment]
@buqiuwenda - getting this exact same thing, I'm very new to go - did you find a solution?

**Comment by Keegan-y** [comment]
Thanks a lot. That solved my problem.  @princefishthrower

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases
