### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hussein-shaikh** [gin-gonic/gin#2950]
Using golang 1.17.3
Gin installation gives error 
# github.com/gin-gonic/gin
go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine)
go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine
go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine
go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath)
go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:510:20: engine.UnescapePathValues undefined (type *Engine has no field or method UnescapePathValues)
![Screenshot from 2021-11-21 23-44-03](https://user-images.githubusercontent.com/58821906/142773993-eb06d7a8-13e1-4ddf-b22f-b408fe689a40.png)

**Comment by tommasinigiovanni** [comment]
same error for me

```
#11 33.56 # github.com/gin-gonic/gin
#11 33.56 ../pkg/mod/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine)
#11 33.56 ../pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine
#11 33.56 ../pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine
#11 33.56 ../pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath)
#11 33.56 ../pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:510:20: engine.UnescapePathValues undefined (type *Engine has no field or method UnescapePathValues)
```

**Comment by hussein-shaikh** [comment]
works fine with gin 1.7.4 , seems like 1.7.5 have this error

**Comment by niklucky** [comment]
Got the same error. I've installed 1.7.4 and everything is fine now:

```
go mod edit -require github.com/gin-gonic/gin@v1.7.4
go get -v -t
```

**Comment by fclairamb** [comment]
Yes it's a broken release:
## v1.7.4 ✅ 
```bash
$ go get github.com/gin-gonic/gin@v1.7.4
```

## v1.7.5 🟥 
```bash
$ go get github.com/gin-gonic/gin@v1.7.5
# github.com/gin-gonic/gin
../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine)
../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine
../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine
../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath)
../../../go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:510:20: engine.UnescapePathValues undefined (type *Engine has no field or method UnescapePathValues)
```

It seems you removed the tag from Github, that's good. 

In my case the dependency update was triggered by renovate and was left open after the tag removal. I guess a lot of people will be impacted similarly.

**Comment by shixinghong** [comment]
> Using golang 1.17.3 Gin installation gives error
> 
> # github.com/gin-gonic/gin
> go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine) go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath) go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:510:20: engine.UnescapePathValues undefined (type *Engine has no field or method UnescapePathValues) ![Screenshot from 2021-11-21 23-44-03](https://user-images.githubusercontent.com/58821906/142773993-eb06d7a8-13e1-4ddf-b22f-b408fe689a40.png)


same error with me 
I have been use v1.7.4
Waiting for fix the bug

**Comment by thinkerou** [comment]
@all
please see #2948, thanks and sorry!

**Comment by Bisstocuz** [comment]
> @ALL please see #2948, thanks and sorry!

@thinkerou Hi, there! I handled one v1.7.5 copy by myself, you can refer to it:
https://github.com/Bisstocuz/gin/tree/v1.7.5

**Comment by shiqianz** [comment]
I think is the go context broken it. each func need set the ctx.

**Comment by thinkerou** [comment]
Released v1.7.6 using the code of v1.7.4 version to fix the error at first, please see https://github.com/gin-gonic/gin/releases/tag/v1.7.6, thanks!

**Comment by new-789** [comment]
For the time being, the v1.7.5 version can be pointed to the v1.7.4 version through replace, such as: github.com/gin-gonic/gin v1.7.5 => github.com/gin-gonic/gin v1.7.4 can be used normally, Look forward to the 1.7.5 version to fix the bug soon

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases
