### ISSUE TITLE
版本1.7.5不能正常工作

### ISSUE THREAD

**Issue by ycyxuehan** [gin-gonic/gin#2955]
我今天使用命令`go get -u github.com/gin-gonic/gin`尝试更新包，发现版本从1.7.4更新到1.7.5。但是代码无法工作，错误如下：
# github.com/gin-gonic/gin
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/context.go:735:13: c.engine.AppEngine undefined (type *Engine has no field or method AppEngine)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:154:3: unknown field 'UseRawPath' in struct literal of type Engine
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:156:3: unknown field 'UnescapePathValues' in struct literal of type Engine
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:508:11: engine.UseRawPath undefined (type *Engine has no field or method UseRawPath)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.5/gin.go:510:20: engine.UnescapePathValues undefined (type *Engine has no field or method UnescapePathValues)

我看github上并没有release1.7.5，为什么我可以下载到这个版本的包呢

**Comment by bearx3f** [comment]
duplicate #2950

**Comment by Bisstocuz** [comment]
v1.7.5 应该是项目维护者测试意外使用了 `proxy.golang.com` 的命令，导致 `pkg.go.dev` 就直接收录了这一版本，实际上1.7.5并没有发布。
解决：使用 `go get github.com/gin-gonic/gin@v1.7.4` 回退版本。

另外，国际项目建议使用英文开 issue，这样能让你获得更广泛的开发者的支持。😁

**Comment by ycyxuehan** [comment]
> v1.7.5 应该是项目维护者测试意外使用了 `proxy.golang.com` 的命令，导致 `pkg.go.dev` 就直接收录了这一版本，实际上1.7.5并没有发布。 解决：使用 `go get github.com/gin-gonic/gin@v1.7.4` 回退版本。
> 
> 另外，国际项目建议使用英文开 issue，这样能让你获得更广泛的开发者的支持。😁

谢谢，我知道国际项目应该使用英文，但是我使用中文的目的是希望中国开发者能够获得重视。不要一上github，再不见中国开发者

**Comment by thinkerou** [comment]
v1.7.7 have released, thanks! https://github.com/gin-gonic/gin/releases
