### ISSUE TITLE
What's the purpose of ginS

### ISSUE THREAD

**Issue by jincheng9** [gin-gonic/gin#2957]
## Description

I checked the contents of ginS directory and find it's a singleton implementation of gin.Engine.

If we need only a single gin.Engine, we can implement it when the process inits or setups.
 
I am not sure the scenaro to use ginS.   Am I missing something?

@thinkerou @appleboy

**Comment by jincheng9** [comment]
@manucorporat

**Comment by kszafran** [comment]
I think it's just a default server for convenience, kind of like `http.Get` and `http.Post` from the standard library. I wouldn't use it in production, but maybe it would be useful in some simple scripts. The readme for that package says:
> This is API experiment for Gin.

**Comment by jincheng9** [comment]
@kszafran I agree.  Its' kind of a wrapper for methods in gin.go.  Let's close this issue.
