### ISSUE TITLE
Graceful Restarts?

### ISSUE THREAD

**Issue by pyros2097** [gin-gonic/gin#296]
How about integrating zero downtime restarts in gin server? Maybe using endless?

https://github.com/fvbock/endless

**Comment by manucorporat** [comment]
Adding a library like that may opens a new world of issues. I am not considering a built-in support for this right now. Even though, I am interested in `zero downtime restarts`.

If you want to start using `endless` right now, just do this:
```go
router := gin.Default()
router.GET("/", handler)
// [...]
endless.ListenAndServe(":4242", router)
```

**Comment by elliotlings** [comment]
I don't think it should be included in the library, it may be confusing for people just getting started with the library and may become an issue during development. I'm currently doing what @manucorporat suggested.

**Comment by dongtian3240** [comment]
good tools is quick my develop speek!

**Comment by jacktuck** [comment]
github.com/braintree/manners is an alternative too.

**Comment by appleboy** [comment]
@jacktuck Thanks. I already create new PR #561 to update README.

**Comment by HaroldHoo** [comment]
https://github.com/HaroldHoo/srvmanager

**Comment by walleliu1016** [comment]
> Adding a library like that may opens a new world of issues. I am not considering a built-in support for this right now. Even though, I am interested in zero downtime restarts.
> 
> If you want to start using `endless` right now, just do this:
> 
> ```go
> router := gin.Default()
> router.GET("/", handler)
> // [...]
> endless.ListenAndServe(":4242", router)
> ```

endless not supported under windows platform.

**Comment by BlaiseAntony** [comment]
Why not add this functionality in gin lib itself? Do we have any blocker for it?
