### ISSUE TITLE
[Not an issue] Something to feel proud

### ISSUE THREAD

**Issue by kishaningithub** [gin-gonic/gin#2963]
Gin tutorial in has been featured has been featured in the "12 years of go" blog by Russ Cox and the Go team

https://go.dev/blog/12years

Line in the above blog
> One highlight is the new tutorial “Developing a RESTful API with Go and Gin”, which is also available in interactive form using Google Cloud Shell.

**Comment by jincheng9** [comment]
cheers

**Comment by jincheng9** [comment]
@kishaningithub would you please close this issue? Let the open issues be the truly problems we need to address. 
Thanks.

**Comment by kishaningithub** [comment]
Yes closing it 👍
