### ISSUE TITLE
gin has no gracefully shutdown method

### ISSUE THREAD

**Issue by lowang-bh** [gin-gonic/gin#2969]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description
I think gin should give a method  go gracefully shutdown server;
Althrouth we can use http.server to implement it, but it is not beautiful.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	// g.Run(":9000")

       g.GracefulRun(:9000)
}
```

## Expectations

```
$ curl http://localhost:8201/hello/world
Hello world
```

## Actual result

```
$ curl -i http://localhost:8201/hello/world
<YOUR RESULT>
```

## Environment

- go version:
- gin version (or commit ref):
- operating system:

**Comment by jincheng9** [comment]
@lowang-bh Currently you can use third-party solution to do this. Gin may implement in future release.

**Comment by lowang-bh** [comment]
> @lowang-bh Currently you can use third-party solution to do this. Gin may implement in future release.

Thanks for your reply.

**Comment by jincheng9** [comment]
@lowang-bh cheers, many 3rd solutions can implement this with Gin. such as `endless`.

**Comment by octocat-1** [comment]
If Gin is going to provide a `Run` method, it should also provide a `Shutdown` method. Sometimes you want to stop the server from running from within the program, and there is no way to do that.

**Comment by octocat-1** [comment]
Example source code changes might be...

```golang
type Engine struct {
  Server http.Server
}

// Run attaches the router to a http.Server and starts listening and serving HTTP requests.
// It is a shortcut for http.ListenAndServe(addr, router)
// Note: this method will block the calling goroutine indefinitely unless an error happens.
func (engine *Engine) Run(addr ...string) (err error) {
  defer func() { debugPrintError(err) }()
  if engine.isUnsafeTrustedProxies() {
    debugPrint("[WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.\n" +
       "Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.")
  }

  address := resolveAddress(addr)
  debugPrint("Listening and serving HTTP on %s\n", address)

  engine.Server = &http.Server{
    Addr:  address,
    Handler: engine
  }

  err = engine.Server.ListenAndServe(address, engine)
  return
}

func (engine *Engine) Stop() (err error) {
  err := engine.Server.Shutdown(gin.Context)
  return
}
```

**Comment by octocat-1** [comment]
I also do not understand how @appleboy [graceful shutdown examples](https://github.com/gin-gonic/examples/blob/master/graceful-shutdown/graceful-shutdown/notify-with-context/server.go) works with `gin.context` that is provided to the the routes. I will often pass `gin.context` to requests made within my routes, but how are those requests supposed to know when the server is being gracefully shutdown?

Should these contexts be `gin.Context`?
``` golang
// Line 18
ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)

// Line 49
ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
```

**Comment by FlyingOnion** [comment]
Great solutions. I want to provide a suggestion too. If gin implements a graceful shutdown method, please also provide an option to **not enable the method** too. This could avoid conflicts with users' own solutions. Maybe there will be two channels catching signals and however you press Ctrl+C the program will not exit. ~~So glad to see that occurs.~~

**Comment by appleboy** [comment]
I write the simple library for graceful shutdown. See: https://github.com/appleboy/graceful

**Comment by cedric-appdirect** [comment]
I have created a PR to add graceful shutdown to gin: https://github.com/gin-contrib/graceful/pull/2 . I would appreciate any feedback on it as that repository doesn't seems to receive any attention at the moment.

**Comment by Bluebugs** [comment]
The PR has been approved and merged. There is now a working https://github.com/gin-contrib/graceful implementation available. I would think this should close this issue.

**Comment by appleboy** [comment]
@Bluebugs Can you help to write documentation in [gin-contrib/graceful](https://github.com/gin-contrib/graceful)?
