### ISSUE TITLE
does gin have a IDL method like proto3 or thrift to define a api service?

### ISSUE THREAD

**Issue by SpringTY** [gin-gonic/gin#2974]
## Description

does gin have an IDL method like proto3 or thrift to define a api service?

for example , i have an echo api
i want to define it like before
does gin has an IDL tool to generate basic code including field verify, model generate?

```
message EchoRequest{
  string content = 1;   
}
message EchoData{
 string content = 1;
}
message EchoResponse{
 int status = 1;
 string message = 2;
 EchoData data = 3;   
}
service{
api EchoResponse Echo(EchoRequest )(api.get='/echo')
}
```

**Comment by jincheng9** [comment]
@SpringTY Gin does not have this kind of stuff.

**Comment by SpringTY** [comment]
ok Grapgql can do it, gqlgen is satisfied
