### ISSUE TITLE
LoadHTMLGlob `http://.... `  exception

### ISSUE THREAD

**Issue by w22296437978** [gin-gonic/gin#2994]
Will take `//` as a comment
![image](https://user-images.githubusercontent.com/39508539/146942511-17ac9c91-e215-4791-a0e0-fbd95df2c069.png)

**Comment by w22296437978** [comment]
![image](https://user-images.githubusercontent.com/39508539/146942683-e7bfa142-1d01-4aef-ba83-34bf22225c65.png)

**Comment by jincheng9** [comment]
please provide more details, such as your sample code.
