### ISSUE TITLE
How to bind post form data to struct?

### ISSUE THREAD

**Issue by shizzic** [gin-gonic/gin#2995]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description
![Снимок экрана (121)](https://user-images.githubusercontent.com/55199603/146987327-064be7d2-9afd-4de6-8ab5-56bb5a94ee1c.png)

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

type Person struct {
	username string `form:"username"`
}

func main() {
	r.POST("/registration", func(c *gin.Context) {
		var person Person

		if c.ShouldBind(&person) == nil {
			log.Println(person.username)
		}
	})

	Run()
}
```

## Expectations

```
21/12/2021 12:43:22 nickname
```

## Actual result

```
21/12/2021 12:43:22
```

## Environment

- go version: 1.17.3
- gin version (or commit ref): last
- operating system: ubuntu 20.04

**Comment by jincheng9** [comment]
the binding field should be uppercase, use "Usename"

`type Person struct {
	Username string `form:"username"`
}`

**Comment by shizzic** [comment]
> the binding field should be uppercase, use "Username"
> 
> ```go
> type Person struct {
> 	Username string `form:"username"`
> }
> ```

Yea, it's worked. I know that question is silly, but i kinda newby in golang. Thank you)

**Comment by jincheng9** [comment]
cheers
