### ISSUE TITLE
404 handler running on 405

### ISSUE THREAD

**Issue by Nebulizer1213** [gin-gonic/gin#3000]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

I have a post route in my api group. When I make a get request to that route it runs my NoRoute handler instead of my NoMethod handler.

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	apiGroup := g.Group("/api")
        apiGroup.POST("/contact", api.Contact)
        g.NoRoute(func(c *gin.context) {
            c.String(404, "404 Not Found")
       })
	 g.NoMethod(func(c *gin.context) {
            c.String(405, "405 Method Not Allowed")
       })
	g.Run(":9000")
}
```

## Expectations
```
$ curl http://localhost:9000/api/contact
405 Method Not Allowed
```

## Actual result
```
$ curl http://localhost:9000/api/contact
404 Not Found
```

## Environment

- go version: 1.17.5
- gin version (or commit ref): v1.7.7
- operating system: Windows

**Comment by jincheng9** [comment]
set 
```go  
g.HandleMethodNotAllowed = true
```

**Comment by Nebulizer1213** [comment]
thanks
