### ISSUE TITLE
will there be feature for add SameSite attribute in "SetCookie"?

### ISSUE THREAD

**Issue by shizzic** [gin-gonic/gin#3002]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

I know that SetCookie method of gin using method Set Cookie on http package. So i'm interesting, will there be this attribute in gin itself?
## How to reproduce

```
```

## Expectations

```
Like this:
c.SetCookie("token", "here'll be token", 30, "/", "https://domain.com", true, true, "None|Lax|Strict")
```

## Actual result

```
c.SetCookie("token", "here'll be token", 30, "/", "https://domain.com", true, true)
```

## Environment

- go version: 1.17.3
- gin version (or commit ref): 1.7.7
- operating system: Ubuntu 20.04

**Comment by tsln1998** [comment]
For example:

```go
r := gin.Default()
r.GET("/", func(c *gin.Context) {
  c.SetSameSite(http.SameSiteLaxMode)
  c.SetCookie(...)
})
```

**Comment by shizzic** [comment]
> For example:
> 
> ```go
> r := gin.Default()
> r.GET("/", func(c *gin.Context) {
>   c.SetSameSite(http.SameSiteLaxMode)
>   c.SetCookie(...)
> })
> ```

Thanks!
