### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by Nebulizer1213** [gin-gonic/gin#3003]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

I dosed my website, and I got a too many open files error which I expected. But a minute after i stopped it I was still getting the error.
Is there something I have to do to close the connection?

- go version: 1.17.5
- gin version (or commit ref): 1.7.7
- operating system: ubuntu-20.04

**Comment by jincheng9** [comment]
It seems your problem does not relate to Gin. you need to provide more details, such as the sample code.
