### ISSUE TITLE
RouterGroup.Static returning 404 for index.html

### ISSUE THREAD

**Issue by xiegeo** [gin-gonic/gin#302]
When using RouterGroup.Static, .../index.html redirect to .../ and .../ returns a 404 error. Even if said file exist.

This is caused by the use of a naive check of the path to see if it is an directory listing: https://github.com/gin-gonic/gin/blob/master/routergroup.go#L141

But net.http redirect .../index.html to .../ and serves .../index.html for .../ when possible: http://golang.org/src/net/http/fs.go?s=13208:13248#L344

Work around:

Use RouterGroup.StaticFS( ... , http.Dir( ... ) , true) to allow directory listing and index.html

Suggested fixes:

Replace 404 with a 403 error and directory listing denied message. This will help new developers (me) know that directory listing is turned off, and not some misspelled path.

Document that Static has listDirectory turned off. (or expose that option in Static)

Check for the existence of .../index.html instead of blocking all .../ requests

**Comment by manucorporat** [comment]
@xiegeo I think I found a perfect solution, but it has a downside.
is it ok if instead of listing the files a return an empty HTML and code=200?

**Comment by manucorporat** [comment]
Check out this new approach:

**Comment by manucorporat** [comment]
https://github.com/gin-gonic/gin/commit/98951c44aa637cbee2a17be00931395403bf8001

this takes advantage of `dirList()`, since that method does not change the status code!
https://github.com/golang/go/blob/master/src/net/http/fs.go#L70-L91

**Comment by xiegeo** [comment]
Thanks, this solves most of what I encountered.

I don't think it can be done without been hacky, as it modifies the behavior of something deep inside the standard library. It's ether a hack, duplicate/re-implement, or push a change to the standard library.
