### ISSUE TITLE
Update package of protobuf

### ISSUE THREAD

**Issue by pobearm** [gin-gonic/gin#3031]
The old package "github.com/golang/protobuf/proto" is deprecated.
It could be saw in it's mod file:
// Deprecated: Use the "google.golang.org/protobuf" module instead.
It would be better to update the package .

**Comment by loickengit** [comment]
The latest version is already using "google.golang.org/protobuf"

**Comment by pobearm** [comment]
I saw the latest code , is been updated. So i closed this issues.
