### ISSUE TITLE
Capturing URL fragments when URL contains :

### ISSUE THREAD

**Issue by al3xandru** [gin-gonic/gin#304]
I have some URLs in the form `.../u:<param>/...`. I've been trying to figure out if there's a way to capture only the param part (considering the URL matching uses `:` for capturing parameters), but I haven't found a solution. As a temporary solution I'm capturing everything including the `:` but this requires an extra validation on the handler.

**Comment by manucorporat** [comment]
@al3xandru  you can use:
```go
router.GET("/some/:param/stuff", parseParam, handler)
```

```go
func parseParam(c *gin.Context) {
    param := c.ParamValue("param")
    if param[0] != 'u' {
        c.String(404, "Not found")
        c.Abort() // aborts the handler chain
    }
}
```

**Comment by manucorporat** [comment]
@al3xandru the gin router is based in HttpRouter and it is that fast and efficient because of some assumptions, such as: a param starts after "/".

**Comment by al3xandru** [comment]
1. the `parseParam` approach is interesting, I'll give it a thought.

2. HttpRouter doesn't require `:` to be right after the `/` (e.g. `.../u:param/...` works). It just requires

    1. there is a single parameter in an URL segment (e.g. you cannot do `/:param1:param2/`)
    2. it expects that the presence of `:` and `*` in a route def means the usage of a parameter. (as a side note, afaik `*` is a valid character for an URL)
