### ISSUE TITLE
[Question] How to inspect TLS certificate data from clients?

### ISSUE THREAD

**Issue by jessicasmith666** [gin-gonic/gin#3079]
Is there a way to get the CA/Organisation name from a client that's initiating a session to a gin server through a custom client certificate?
Both the TLS.PeerCertificates and the TLS.VerifiedChains are returning nothing useful.

@appleboy @austinheap @javierprovecho @thinkerou Any ideas?

**Comment by arer0008** [comment]
I have the same problem with .Request.TLS.PeerCertificates, it's always returning an empty array. To get the information i hade to use net/http instead of gin.
`	certificates := r.TLS.PeerCertificates
	cert, err := x509.ParseCertificate(certificates[0].Raw)
	fmt.Println(cert.Subject)
	test := cert.Subject.Organization
	fmt.Println(test)`
Is there some way to do this in gin-gonic?
