### ISSUE TITLE
ListenAndServeTLS vanished

### ISSUE THREAD

**Issue by Dal-Papa** [gin-gonic/gin#311]
Hello guys,

I've put a comment in some commit you did that basically removed the TLS version of Run. 

Here it is : 
https://github.com/gin-gonic/gin/commit/b690611c381a2c9765ac7cdbd6588da7714c4790#commitcomment-11397410

Cheers,
Clem DAL PALU.

**Comment by manucorporat** [comment]
@Dal-Papa oh! shit! you are right. fixed!
https://github.com/gin-gonic/gin/commit/b96f68ce7b9844d4b36cbb992c2f82d770069dbd
