### ISSUE TITLE
how do we use ginS package?

### ISSUE THREAD

**Issue by asaqib27** [gin-gonic/gin#3121]

**Comment by jincheng9** [comment]
@asaqib27 no need to use this package.

**Comment by asaqib27** [comment]
> @asaqib27 no need to use this package.

I am just trying to understand why is this package even available? 

Could you please make me understand the use of this package in gin?

**Comment by kszafran** [comment]
See https://github.com/gin-gonic/gin/issues/2957

**Comment by jincheng9** [comment]
no need to use ginS package
