### ISSUE TITLE
Installation having problem Sync.Pool

### ISSUE THREAD

**Issue by cention-mujibur-rahman** [gin-gonic/gin#313]
Today I was doing command: go get github.com/gin-gonic/gin
#github.com/gin-gonic/gin
 github.com/gin-gonic/gin/gin.go:34:undefined: sync.Pool

**Comment by leedstyh** [comment]
Whats your go version? Gin needs Go 1.3 at least

**Comment by manucorporat** [comment]
@leedstyh is right. sync.Pool was introduced in Go 1.3.
https://github.com/gin-gonic/gin/issues/294

**Comment by cention-mujibur-rahman** [comment]
Thank you so much
