### ISSUE TITLE
RunTLS does not work

### ISSUE THREAD

**Issue by njuettner** [gin-gonic/gin#315]
The function RunTLS seems to be broken.  

```
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

var sslkey string = ""
var sslcert string = ""

func main() {
	router := gin.Default()
	router.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK, "hello world")
	})
	err := router.RunTLS("127.0.0.1:5443", sslcert, sslkey)
	if err != nil {
		fmt.Println("Server could not be started")
	}
}
```

After building, the application starts and listen

[GIN-debug] [WARNING] Running in DEBUG mode! Disable it before going production
[GIN-debug] GET   /                         --> main.func·001 (3 handlers)
[GIN-debug] Listening and serving HTTPS on 127.0.0.1:5443

I tried it also with a real certificate and a key but unfortunately it won't read them. Got the same message see below

```
curl https://127.0.0.1:5443
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:-9847
```

**Comment by njuettner** [comment]
Instead of using RunTLS function trying to run http.ListenAndServeTLS directly with an empty key and certificate

```
package main

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

var sslkey string = ""
var sslcert string = ""

func main() {
	router := gin.Default()
	router.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK, "hello world")
	})
	err := http.ListenAndServeTLS("127.0.0.1:5443", sslcert, sslkey, router)
	if err != nil {
		fmt.Println("Could not start WebServer")
	}
}
```
I get the response I expected:

[GIN-debug] [WARNING] Running in DEBUG mode! Disable it before going production
[GIN-debug] GET   /                         --> main.func·001 (3 handlers)
Could not start WebServer


Using a certificate and key which exists in the directory
```
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

var sslkey string = "./server.key"
var sslcert string = "./server.crt"

func main() {
	router := gin.Default()
	router.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK, "hello world")
	})
	err := http.ListenAndServeTLS("127.0.0.1:5443", sslcert, sslkey, router)
	if err != nil {
		fmt.Println("Could not start WebServer")
	}
}
```

[GIN-debug] [WARNING] Running in DEBUG mode! Disable it before going production
[GIN-debug] GET   /                         --> main.func·001 (3 handlers)

```
curl https://127.0.0.1:5443
hello world%
```

**Comment by manucorporat** [comment]
it is already fixed in master: https://github.com/gin-gonic/gin/issues/311

**Comment by njuettner** [comment]
Sorry forgot to mention its not the master branch, its developer branch :)

**Comment by manucorporat** [comment]
I just merged `master` into `develop`. thanks for the PR but it was already fixed :)
