### ISSUE TITLE
The current version has a security vulnerability

### ISSUE THREAD

**Issue by MCWertGaming** [gin-gonic/gin#3155]
## Description

Hi! I just go a security warning by Github because a dependency used by this project is marked as vulnerable. It can be found here https://github.com/advisories/GHSA-hp87-p4gw-j4gq. The package is `gopkg.in/yaml.v3` which is resolved in the current master, but the latest release (1.7.7) is over a year old and does not contain this fix.

It would be nice if you guys would create a new version of this module.

**Comment by sampalm** [comment]
Hi I'm also looking for a solution for this problem as well. For now what should we do?

**Comment by MCWertGaming** [comment]
Hey @thinkerou since you are maintainer of gin-gonic, can you please comment on this?

**Comment by thinkerou** [comment]
@MCWertGaming please see #3160 
when we use go-yaml v3, the unit test exception: 
```
=== RUN   TestRenderYAML
    render_test.go:240:
        	Error Trace:	render_test.go:240
        	Error:      	Not equal:
        	            	expected: "\"\\na : Easy!\\nb:\\n\\tc: 2\\n\\td: [3, 4]\\n\\t\"\n"
        	            	actual  : "|4-\n    a : Easy!\n    b:\n    \tc: 2\n    \td: [3, 4]\n    \t\n"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,7 @@
        	            	-"\na : Easy!\nb:\n\tc: 2\n\td: [3, 4]\n\t"
        	            	+|4-
        	            	+    a : Easy!
        	            	+    b:
        	            	+    	c: 2
        	            	+    	d: [3, 4]
        	            	+

        	Test:       	TestRenderYAML
```

**Comment by MCWertGaming** [comment]
@thinkerou thank you really much for looking into this. I have just seen that the master is using go-yaml.v2 but has it as a dependency. Any idea if the unit test broke because of a problem in V3 of the module? Or is it possible that the usage changed?

If no one is already looking into looking into a fix, I could check on that.

**Comment by thinkerou** [comment]
https://github.com/advisories/GHSA-hp87-p4gw-j4gq
I have fixed, please check!
please commit pr, thanks!

**Comment by hakandilek** [comment]
@thinkerou on which PR did you fix this? Can you please link?

I think the fix is not in v1.8.0. I still see both [yaml.v2 v2.4.0](https://github.com/gin-gonic/gin/blob/v1.8.0/go.mod#L16) and [yaml.v3 v3.0.0](https://github.com/gin-gonic/gin/blob/v1.8.0/go.mod#L30)

**Comment by MCWertGaming** [comment]
True, the current master uses V2 https://github.com/gin-gonic/gin/blob/master/go.mod#L16.

**Comment by appleboy** [comment]
See v1.8.0 https://github.com/gin-gonic/gin/releases/tag/v1.8.0

**Comment by appleboy** [comment]
@hakandilek @MCWertGaming Please help to review the https://github.com/gin-gonic/gin/pull/3164 PR. I will bump v1.8.1 after merging.

**Comment by appleboy** [comment]
Yaml v2 version can't reproduce the issue. See the comment https://github.com/go-yaml/yaml/issues/666#issuecomment-1133337993

**Comment by appleboy** [comment]
I will close the issue. Please feel free to reopen the issue if any further problems.
