### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by MCWertGaming** [gin-gonic/gin#3157]
## Description

Hey, I was wondering if the project is actively maintained. It seems like most of the time only the dependabot PRs are merged and no one is really looking into the newly opened issues and PRs. If the project lacks on maintaining, you (the maintainers and contributors) should look into finding a new maintainer. over 60 thousand projects here on github are relying on this library for their projects so we should keep it secure, recent and fix bugs and issues.

**Comment by appleboy** [comment]
We just released a new version v1.8.0 yesterday https://github.com/gin-gonic/gin/releases/tag/v1.8.0

**Comment by appleboy** [comment]
Duplicated of https://github.com/gin-gonic/gin/issues/490
