### ISSUE TITLE
binding validations cause weird text to be generated

### ISSUE THREAD

**Issue by bfosberry** [gin-gonic/gin#316]
Unsure if this is a gin issue or an issue with your validator, but:

```
_field validation for "_client_id" failed on the "required" tag
```

Converting to underscores seems to just bulk replace capital letters to underscores

**Comment by manucorporat** [comment]
@bfosberry I don't understand. can you provide more context?

**Comment by bfosberry** [comment]
Woah! Nvm, this is something our wonderful codebase is doing. Closing!
