### ISSUE TITLE
Breaking change in 1.8.0 - `RemoteIP` interface changed

### ISSUE THREAD

**Issue by istrel** [gin-gonic/gin#3167]
## Description

`RemoteIP` interface changed in commit - https://github.com/gin-gonic/gin/commit/0be805a67503c5ad903c57940b7e9c19d88d522a

Previous interface: `RemoteIP() (net.IP, bool)`
New interface: `RemoteIP() net.IP`

**Comment by zihengCat** [comment]
@Bisstocuz @appleboy @thinkerou
Keep backward compatibility or announce the breaking change？

**Comment by appleboy** [comment]
Updated release note and add break changes section.

https://github.com/gin-gonic/gin/releases/tag/v1.8.0

**Comment by appleboy** [comment]
See the comment https://github.com/gin-gonic/gin/issues/3166#issuecomment-1143570149
