### ISSUE TITLE
Cannot upgrade gin to 1.18

### ISSUE THREAD

**Issue by allesan** [gin-gonic/gin#3175]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description

I cannot upgrade to 1.18 version due to checksum mismatch.

## How to reproduce

```
$ go get -u github.com/gin-gonic/gin
go: downloading github.com/gin-gonic/gin v1.8.0
go: github.com/gin-gonic/gin@v1.8.0: verifying module: checksum mismatch
	downloaded: h1:gcAUpegZ91QWGm03w0CjjJ0+rjxmG3pbBbT0aiT82s8=
	sum.golang.org: h1:4WFH5yycBMA3za5Hnl425yd9ymdw1XPm4666oab+hv4=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

```

## Expectations

Successfull upgrade

## Actual result

checksum mismatch

## Environment

- go version: 1.18
- gin version (or commit ref): 1.7.7
- operating system: Linux

**Comment by appleboy** [comment]
try 

```sh
go get github.com/gin-gonic/gin@v1.8.1
```
