### ISSUE TITLE
Feature to add using goemphp/go-php/other library to make gin support php

### ISSUE THREAD

**Issue by onebyonetwo** [gin-gonic/gin#3226]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:8201/hello/world
Hello world
```

## Actual result

```
$ curl -i http://localhost:8201/hello/world
<YOUR RESULT>
```

## Environment

- go version:
- gin version (or commit ref):
- operating system:

**Comment by thinkerou** [comment]
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/4488261/177020905-63fef392-da06-4f70-880a-c5ef437b9835.png">
