### ISSUE TITLE
Export createTestContext as a test helper

### ISSUE THREAD

**Issue by danielalves** [gin-gonic/gin#323]
I'm trying to write tests for my controllers (using Gin, a file that groups route handlers), but I'm not being able to mock gin Contexts. Inside the [context_test.go file](https://github.com/gin-gonic/gin/blob/master/context_test.go), there's a method that does exactly that:

``` go
func createTestContext() (c *Context, w *httptest.ResponseRecorder, r *Engine) {
    w = httptest.NewRecorder()
    r = New()
    c = r.allocateContext()
    c.reset()
    c.writermem.reset(w)
    return
}
```

But it is not exported. I also cannot replicate it because `allocateContext` and Context's `engine` field are unexported too.

What do you think about creating a test-helpers module and exporting `createTestContext`?

**Comment by slimmy** [comment]
I've been meaning to ask this as well. My way of testing my middleware usually looks something like this

```go
func TestFooMiddleware(t *testing.T) {
    gin.SetMode(gin.TestMode)
    router := gin.New()
    router.Use(FooMiddleware())  //only use the mw I want to test
    router.GET("/test", func(c *gin.Context) {
        c.String(200, "OK")
    }

    w := httptest.NewRecorder()
    r, _ := http.NewRequest("GET", "/test", body)
    router.ServeHTTP(w, r)

    //assertions here
}   
```

Is this the correct way of testing middleware in gin?

**Comment by manucorporat** [comment]
@slimmy I think your code is the correct way. You can not test how a middleware aborts if you are using a fake context.

**Comment by manucorporat** [comment]
@danielalves I will merge your PR but you should understand the limitations.
createTestContext() was created to test the context itself.

You can not test if the context stops the execution (since there is not a handler chain associated).

**Comment by manucorporat** [comment]
https://github.com/gin-gonic/gin/blob/master/auth_test.go#L91-L126

**Comment by manucorporat** [comment]
How about this?

```go
func HandlerTest(handler HandlerFunc) *Engine {
	router := New()
	router.Use(handler)
	router.Any("/", func(c *Context) {
		c.String(http.StatusTeapot, "Called %s", c.Request.Method)
	})
	return router
}

func performRequest(r http.Handler, method, path string) *httptest.ResponseRecorder {
	req, _ := http.NewRequest(method, path, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	return w
}

func Test(t *testing.T) {
	r := HandlerTest(myMiddleware)
	w := performRequest(r, "GET", "/")
       
	// assert.Equal(...)
	// assert.Equal(...)
}
```

**Comment by danielalves** [comment]
@manucorporat Hey! Ok, I understand the limitations, but it is just what I need. For example, many of my tests look like this:

**Comment by danielalves** [comment]
@manucorporat Sorry to bother, but any updates on this?
I just wanted to add that using `router.ServeHTTP(w, req)` to test route handlers may be the most correct way (as in the link you've sent above) since the request goes all the way through the gin stack, but isn't it a little overkill for simple unit tests? I mean, for acceptance tests, where you do want to test everything together, that makes perfect sense. But, for unit tests, wouldn't it be simpler as I've suggested on my last comment?

**Comment by alediaferia** [comment]
**+1** for this

Actually this would help make make better unit tests.
I agree using `httptest.Recorder` is the right way most of the times but sometimes it is useful testing if my custom middleware actually sets the right values through `func (c *Context) Set(key string, value interface{})` without having to check status codes which may not make sense with that case.

**Comment by davisford** [comment]
@manucorporat can you suggest the best way to test middleware functions - i.e. I don't necessarily want to build up a whole http stack, just test a function where I pass in the context and manipulate the context, and then assert some state on the context after the function.  

i'm trying to figure out from this thread here the most appropriate way to create a context without building up a whole stack.

**Comment by pierrec** [comment]
Hello,

I understand all the benefits from having this as an exported function, but I have just run into an annoying side effect:
since the function CreateTestContext() imports "net/http/httptest", it also adds an entry in cli arguments (https://golang.org/src/net/http/httptest/server.go#L69), which messes up with my cli arguments in my program.

Thoughts?

**Comment by yehezkielbs** [comment]
Please consider the PR https://github.com/gin-gonic/gin/pull/707
It make `CreateTestContext()` public without importing `net/http/httptest`

**Comment by xiaods** [comment]
how about any udpate?

**Comment by tinchogob** [comment]
How about making Context an interface, so I could pass a mock implementation to test my middlewares?

**Comment by appleboy** [comment]
Hi All,

Fixed by https://github.com/gin-gonic/gin/pull/707

**Comment by genexp** [comment]
Thanks for this!
