### ISSUE TITLE
Wrong query binding struct tag

### ISSUE THREAD

**Issue by illiafox** [gin-gonic/gin#3235]
https://github.com/gin-gonic/gin/blob/b57163a0e4339d7feb393ff430a454f4e448cf9c/binding/query.go#L15-L21

`mapForm` searches `form` struct tag, not `query`

Fixed version:

```go
func (q queryBinding) Bind(req *http.Request, obj any) error {
	values := req.URL.Query()
	if err := mapFormByTag(obj, values, q.Name() ); err != nil {
		return err
	}
	return validate(obj)
}
```

**Comment by appleboy** [comment]
fixed in #3236 @illiafox Thanks.

**Comment by appleboy** [comment]
@illiafox Please open the new PR to fix the testing. #3236 can't pass the testing

**Comment by illiafox** [comment]
I guess the issue can be closed as the `query` tag is not used anywhere
