### ISSUE TITLE
Support Two or More Http Methods in One Function?

### ISSUE THREAD

**Issue by KiddoV** [gin-gonic/gin#3259]
## Description
Why ``Gin`` doesn't have something like this in ``Echo``?
https://github.com/labstack/echo/blob/ec92fedf21e817d2d52004a4178292404beb9eaa/group.go#L87
So we can have something like:
```Go
func main() {
	g := gin.Default()
	g.Match([]string{"GET", "POST", "PUT"}, "/hello/:name", handlerFunc)
}
```
Would it be better than this?
```Go
func main() {
	g := gin.Default()
	g.GET("/hello/:name", handlerFunc).POST("/hello/:name", handlerFunc).PUT("/hello/:name", handlerFunc)
}
```
...to prevent ... boilerplate?
Thanks,

**Comment by dxgzg** [comment]
you maybe use g.Any,it support any method.maybe help you

**Comment by KiddoV** [comment]
@dxgzg  ``gin.Any()`` will bring all http methods. What if I just want "GET" and "POST" only!!

**Comment by Albert-Gao** [comment]
easy, just write a high-order function to wrap it, you do not need Gin to support it

**Comment by KiddoV** [comment]
@Albert-Gao Can I have some code examples?

**Comment by Albert-Gao** [comment]
![image](https://user-images.githubusercontent.com/18282328/188289872-34ef8d88-488f-4469-93c9-d238f7e64a18.png)

you can create your own struct wrap the router, and attach the PostAndGet method for a more idiomatic golang experience, but sounds overkill for just a few more helper functions.

@KiddoV

**Comment by KiddoV** [comment]
Interesting! Thanks!
