### ISSUE TITLE
gin file structure problem

### ISSUE THREAD

**Issue by goldalworming** [gin-gonic/gin#326]
I tried to separate router and handler but nothing works

# command-line-arguments
./main.go:23: undefined: statsWorker
./main.go:30: undefined: rateLimit
./main.go:33: undefined: index
./main.go:34: undefined: roomGET
./main.go:35: undefined: roomPOST
./main.go:36: undefined: streamRoom

samples return same error

**Comment by manucorporat** [comment]
@goldalworming I don't understand what you are trying to do.
obviously it is not going to work if you remove half of the code.

**Comment by javierprovecho** [comment]
@goldalworming and if you post some code, better than good!

**Comment by dopgm** [comment]
@goldalworming , these are the functions, existing in the example, but their implementation was out of the the scope I believe. Try creating functions with these names or remove them.

**Comment by goldalworming** [comment]
ok, I've tried another way from scratch and have successfully run it. thanks

**Comment by mistbow-git** [comment]
Hi! I have same problem when I try to run app from Inellij IDEA 15 with Go plugin.
Any Idies?

**Comment by mistbow-git** [comment]
I have answer on my own question!
Before use Run on multiple file project You need to setup Run configuration. 
Run->Edit Confuguration, then press green +, choice Go Application and then change Run kind from File to Package.
Then type your package name and Save configuration.
Best regards!
