### ISSUE TITLE
is DisableBindValidation() or binding.Validator used?

### ISSUE THREAD

**Issue by kmulvey** [gin-gonic/gin#327]
I cant find any reference to the function or the variable it sets. Can it be removed or is it something that will be used in the future?

https://github.com/gin-gonic/gin/blob/master/mode.go#L55

**Comment by manucorporat** [comment]
@kmulvey https://github.com/gin-gonic/gin/blob/master/binding/binding.go#L33

I need to document that.

**Comment by kmulvey** [comment]
also, is init() needed? I deleted it and all the tests still pass.  Using print statements I can see it getting called but I couldn't find who calls it.

https://github.com/gin-gonic/gin/blob/master/mode.go#L32

**Comment by manucorporat** [comment]
init() is called by the runtime. it is very important.
https://golang.org/doc/effective_go.html#init
