### ISSUE TITLE
render html

### ISSUE THREAD

**Issue by centratelemedia** [gin-gonic/gin#3274]
howto render html tag from variable:

```
ctx.HTML(200, "user.html", gin.H{
		"title":   "User Management",
		"content": "<button>Private Button</button>",
		"users":   listUser,
	})
```
howt render ```<button>Private Button</button>``` as html tag?

**Comment by KKRaver** [comment]
Have you tried passing the button as template.HTML instead of string?

**Comment by centratelemedia** [comment]
@KKRaver, no i don't know about template.HTML is this golang standard package or gin gonic?

**Comment by centratelemedia** [comment]
thank got answer from [https://github.com/gin-gonic/gin/issues/1045](url)
