### ISSUE TITLE
Format with Go 1.19 formatter

### ISSUE THREAD

**Issue by Aoang** [gin-gonic/gin#3276]
I add support for Go1.19 tests [here](https://github.com/gin-gonic/gin/pull/3275).

New markup syntax introduced for Go 1.19. 
> Go 1.19 adds support for links, lists, and clearer headings in doc comments. As part of this change, gofmt now reformats doc comments to make their rendered meaning clearer. See “Go Doc Comments” for syntax details and descriptions of common mistakes now highlighted by gofmt. As another part of this change, the new package go/doc/comment provides parsing and reformatting of doc comments as well as support for rendering them to HTML, Markdown, and text.
> 
> https://tip.golang.org/doc/comment

Do we need to follow up on it? I'd be happy to open a PR if needed.

**Comment by thinkerou** [comment]
@Aoang please, thanks!
