### ISSUE TITLE
httprouter missing in Godeps ?

### ISSUE THREAD

**Issue by nlamirault** [gin-gonic/gin#328]
There is no link on httprouter [1] in the Godeps file.
```bash
Godeps/_workspace/src/github.com/gin-gonic/gin/context.go:13:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
```

[1]: github.com/julienschmidt/httprouter

**Comment by slimmy** [comment]
If im not mistaken Gin now includes a modified source of httprouter. If you have a look at https://github.com/gin-gonic/gin/blob/master/tree.go you can see the copyright notice at the top.

Nowhere in the Gin source code is httprouter imported.

**Comment by nlamirault** [comment]
ok thanks.

**Comment by manucorporat** [comment]
@slimmy is right
