### ISSUE TITLE
validator 版本升级需求

### ISSUE THREAD

**Issue by agclqq** [gin-gonic/gin#3297]
validator升级到v10.11.0了，增加了required_if等相关的处理和中文翻译
https://github.com/go-playground/validator/releases/tag/v10.11.0

但目前gin的最新版本为v1.8.1，引用的validator版本为v10.10.0
https://github.com/gin-gonic/gin/releases/tag/v1.8.1

在gin的下个版本，validator的版本能更新吗，谢谢

**Comment by abrar71** [comment]
I also support this request, Thank you!

**Comment by thinkerou** [comment]
v1.9.1 have released, please see https://github.com/gin-gonic/gin/releases/tag/v1.9.1, thanks!

**Comment by 888go** [comment]
效验中文提示, 应该怎么弄, 好像弄不了吧. 都写死在gin里面了
