### ISSUE TITLE
How to handle the checkbox status in a form?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [gin-gonic/gin#3303]
## Description

Hi,

After a lot of googling, I couldn't find anything.
There is some content about Checkbox groups but it doesn't meet my need.

## How to reproduce

This is the form:

```html
<form action="/p1" method="post">
<label for="ex-checkbox">a checkbox</label>
<input type="checkbox" name="ex-checkbox" />
</form>
```

Go code:

```
.......

type CheckboxForm {
// checked or unchecked > true or false
	CheckboxStatus bool `form:"ex-checkbox"`
}
var form CheckboxForm
err = c.ShouldBind(&form)
if err != nil {
panic(err)
}
fmt.Println(form)
....
```

## Expectations

if checkbox is cheched field is true, or false

**Comment by thoohv5** [comment]
input checkbox value is no or "", so not use boolean, use string;  judge value

**Comment by Gasoid** [comment]
```html
<input type="checkbox" name="ex-checkbox" value="yes"/>
```

```go
type CheckboxForm {
	CheckboxStatus string `form:"ex-checkbox"`
}
```

**Comment by SeanTolstoyevski** [comment]
Thank you so much.

I will try it.

**Comment by abo1000ody** [comment]
> ## Description
> Hi,
> 
> After a lot of googling, I couldn't find anything. There is some content about Checkbox groups but it doesn't meet my need.
> 
> ## How to reproduce
> This is the form:
> 
> ```
> <form action="/p1" method="post">
> <label for="ex-checkbox">a checkbox</label>
> <input type="checkbox" name="ex-checkbox" />
> </form>
> ```
> 
> Go code:
> 
> ```
> .......
> 
> type CheckboxForm {
> // checked or unchecked > true or false
> 	CheckboxStatus bool `form:"ex-checkbox"`
> }
> var form CheckboxForm
> err = c.ShouldBind(&form)
> if err != nil {
> panic(err)
> }
> fmt.Println(form)
> ....
> ```
> 
> ## Expectations
> if checkbox is cheched field is true, or false
> 
> ## Actual result
> ## Environment
