### ISSUE TITLE
Suggest: using https://github.com/unrolled/render for rendering

### ISSUE THREAD

**Issue by ericwq** [gin-gonic/gin#334]
can you consider this?

**Comment by slimmy** [comment]
Considering it is already easy to integrate it with gin (https://github.com/unrolled/render#gin) what are the upsides to bring this dependancy into gin? Are there any performance improvements?

**Comment by manucorporat** [comment]
There is not good reason for this:
1. Gin's built-in rendering has been strongly optimized:
2. HTML rendering is customisable by creating your own render

```
BenchmarkOneRouteJSONExternal	 1000000	      2666 ns/op	     528 B/op	       9 allocs/op
BenchmarkOneRouteJSON	 1000000	      1077 ns/op	      56 B/op	       3 allocs/op
```
