### ISSUE TITLE
panic: handlers are already registered for path

### ISSUE THREAD

**Issue by ajmeese7** [gin-gonic/gin#3354]
## Description

Similar to #196, I am experiencing the error `panic: handlers are already registered for path '/'`.

The big difference is that I am using a closed-source tool to which I only have access to the binary, so I have no access to or control over the `go` code. It seems that no one else has ran into this issue with the tool, so I was wondering if this problem is something I could run into as a result of a configuration error.

Do any of the below settings look like they could produce this error to you? I don't know much about go and I know nothing about this framework, so I was hoping someone could assist me here:

```text
[nps]
downroute = '/:target/assert/:sys'
npcport = ':80'
npcroute = '/:target/favicon.ico'
npsport = ':3200'
npuaddr = '/namehere'
redirect = 'http://www.domainhere.com'
```

Thanks!

**Comment by ajmeese7** [comment]
@Cookiery 
> I have no access to or control over the `go` code

As my issue says, I don't have the source code, I only have a binary available.

**Comment by Cookiery** [comment]
Sorry, through your configuration, I don't see any problems.

**Comment by ajmeese7** [comment]
Fair enough, figured it was worth checking here just in case. Closing this out now, cheers!
