### ISSUE TITLE
context.Bind never returns an error

### ISSUE THREAD

**Issue by rafbgarcia** [gin-gonic/gin#340]
Hey, just a question:

I realized that the code below will never execute `return err` because `c.AbortWithError(400, err).SetType(ErrorTypeBind)` aborts the request, is that correct?

Is that the expected behavior? If so, wouldn't it be better to not return anything instead?

```go
func (c *Context) BindWith(obj interface{}, b binding.Binding) error {
	if err := b.Bind(c.Request, obj); err != nil {
		c.AbortWithError(400, err).SetType(ErrorTypeBind)
		return err
	}
	return nil
}
```

**Comment by manucorporat** [comment]
@rafbgarcia
> I realized that the code below will never execute return err because c.AbortWithError(400, err).SetType(ErrorTypeBind) aborts the request, is that correct?
no, `c.Abort()` (and family) is not a panic. i.e. c.Abort() will return and continue the execution of the current scope.

c.Abort() tells the router to do not call the next handler in the chain
so if you have a chain of 4 handlers: logger -> gzip ->auth -> indexHandler 

if the `auth` handler (or middleware) calls c.Abort() it will tell the system to do not continue calling the rest of handlers in the chain, so indexHandler will not be called in that request.

**Comment by manucorporat** [comment]
```go
router := gin.New()
// global handler (middleware)
router.Use(func(c *gin.Context) {
    c.Abort()
    fmt.Println("THIS IS CALLED!!!)
})

router.GET("/", func(c *gin.Context) {
    // this code will never be called, since the previous handler always cancels the requests!
    fmt.Println("this will never be printed :(")
})
```

understand?

**Comment by rafbgarcia** [comment]
Hey @manucorporat, you're totally right, I wasn't properly handling the error that `Bind` returns, my bad dude.

**Comment by manucorporat** [comment]
you have the possibility to handle the errors by using a middleware, so you do not poison your normal flow code with error management.

Just create a middleware: like
```go
func handleErrors(c *gin.Context) {
   c.Next()

   // read c.Errors
}
```

this way your code would look like this:
```
router.GET("/", func(c *gin.Context) {
    var obj JSONStruct
    if c.Bind(&obj) == nil {
        // handle success
    } // error case is handled by the middleware!
})
```

https://github.com/gin-gonic/gin/blob/master/logger.go#L28-L39

you are free to use any method, I think the middleware method is good if your project is getting complex.
Because you move all your error management to one place.

**Comment by rafbgarcia** [comment]
@manucorporat, that's really great, I just learned one more thing today! haha

Already implemented that solution in my project, thanks a lot.

:+1:

**Comment by manucorporat** [comment]
@rafbgarcia glad! I was helpful :) last tip!
In our case, we filter the errors by type:
- public ones -> send in the response as JSON
- private ones -> send to [sentry](https://getsentry.com/welcome/) + syslog 

```go
// by using ByType()
// errors from c.Bind() or public ones.
publicErrors := c.Errors.ByType( gin.ErrorTypeBind | gin.ErrorTypePublic )

// or iterating
for _, err := c.Errors {
   if err.IsType(gin.ErrorTypePublic |  gin.ErrorTypeBind) { 
        // error is from bind or public
   }else if err.IsType(gin.ErrorTypePrivate) {
        // error is private 
   }
}
```

https://github.com/gin-gonic/gin/blob/master/errors.go#L16-L20

**Comment by rafbgarcia** [comment]
@manucorporat really good stuff dude, thanks for sharing!

We're working on a totally new project, so it'll definitely help us in a near future :)

:+1:

**Comment by manucorporat** [comment]
@rafbgarcia you are welcome!

**Comment by nazwa** [comment]
@manucorporat Ha I had no idea BindWith automatically aborts and adds the error to the error queue. That's quite handy. Is this 'new'?

**Comment by manucorporat** [comment]
@nazwa no, it has been there since the first release of Gin. but everything have been improved a lot.
Just remember, adding the error to the error queue does nothing. It will write in the response. "Leaking" information through HTTP is always in your hand!

**Comment by nazwa** [comment]
Yea totally. Looks like I've got a bunch of code to update haha.

**Comment by manucorporat** [comment]
@nazwa good idea! if you just wrote something simple. it may be more convenient to check the error returned by `c.Bind()` directly.

but if you are developing something serious (like we do). it is a good idea to move apart the error management code.

**Comment by nazwa** [comment]
I still need to get my head around proper error management strategy. It's all linked to the other error discussion we had and it's not gin specific. Especially abstracting public / private errors and automating error throwing process.

**Comment by manucorporat** [comment]
Another pattern around Bind, it to use the new Bind() middleware. It is mostly an experiment, it works this way:

```go
type User struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

func main() {
	r := gin.Default()
	r.POST("/ping", gin.Bind(User{}), func(c *gin.Context) {
		user := JSON(c).(*User) // at this point user is ensured to be VALID!!
		fmt.Println("name: %s", user.Name)
		fmt.Println("age: %d", user.Age)

		c.JSON(200, user) // echo!
	})
	r.Run(":8080")
}

func JSON(c *gin.Context) {
	return c.MustGet(gin.BindKey)
}
```

**Comment by nazwa** [comment]
Nice, that looks like a pretty decent solution. 

On a side note, we've recently survived out first gigantic traffic spike since moving to gin from php and everything was handled perfectly. So well done!

**Comment by rafbgarcia** [comment]
@manucorporat that's nice :+1:

**Comment by nazwa** [comment]
This is an old one, but I finally had a chance to update the code and the `gin.Bind` middleware is brilliant. Saves so much effort.

@manucorporat one thing that's definitely missing is a shortcut method for public errors. 
```go
c.Error(ErrorInvalidReferalCode).SetType(gin.ErrorTypePublic)

// Maybe... ?
c.PublicError(ErrorInvalidReferalCode)
```
Setting `ErrorTypePublic` all the time get's quite repetitive :smile:

**Comment by manucorporat** [comment]
@nazwa hi, I am finally back to work after the vacations, I will review all the pending issues in the next couple of days, sorry for the delay.

I want to keep the interface as simple as possible, how about this?:
```go
c.Error(ErrorInvalidReferalCode).Public()
```

**Comment by nazwa** [comment]
So was I :smile: I agree with you on this, polluting the interface is not a good option. 
Your suggestion still requires another function call, so I think let's just leave it as it is at the moment for clarity.
