### ISSUE TITLE
http: proxy error: dial tcp [::1]:3001: connect: connection refused

### ISSUE THREAD

**Issue by Aashir1** [gin-gonic/gin#3407]
## Description

I just setup the gin and test very basic GET request. However, server always throwing an error **http: proxy error: dial tcp [::1]:3001: connect: connection refused** and couldn't figure out whats wrong with my code.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.GET("/", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run()
}

```

## Expectations

```
$ curl http://localhost:3000/
{"message":"pong"}
```

## Actual result

```
$ curl http://localhost:3000/
Received nothing in response
```

## Environment

- go version: 1.19.3 darwin/arm64
- gin version (or commit ref): v1.8.1
- operating system: M1 Macbook Pro

**Comment by liuliqiang** [comment]
Hi @Aashir1 ,

I think there might be a proxy setting in your env, can you show the output for following command executed in your command line?

```
# env | grep -i http
```

**Comment by Aashir1** [comment]
> 

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/25276195/203101434-0660d26f-3af1-45ea-948c-0fdc4317cd00.png">
I'm getting nothing in response

**Comment by mstmdev** [comment]
Can you provide the `GIN-debug` log? If you are not setting up the `PORT` environment, the default port should be `8080`, but you access the web server by `3000` port.

**Comment by Aashir1** [comment]
SS after hitting on port 3000
<img width="942" alt="image" src="https://user-images.githubusercontent.com/25276195/203231574-1ca62ed3-e296-49f5-a9ad-57e100e04cd7.png">

and Yes, I have set the `PORT=3000` in .env file. I think development mode is a `Debug mode` right?
@mstmdev

**Comment by mstmdev** [comment]
It looks like using `github.com/codegangsta/gin` to implement live-reloading. Please try to remove `PORT=3000` in the .env file, because the proxy server port is `3000`.
@Aashir1

**Comment by mstmdev** [comment]
Maybe you should execute the below command to check your workspace and code.
```shell
cat /User/aashirkhan/go/bin/gin/main.go
```

**Comment by Aashir1** [comment]
> It looks like using `github.com/codegangsta/gin` to implement live-reloading. Please try to remove `PORT=3000` in the .env file, because the default port of proxy server is `3000`. @Aashir1

It's working, I just removed `PORT=3000` from .env file
