### ISSUE TITLE
Remove <html> <head> <body>

### ISSUE THREAD

**Issue by chihiro-yabuta** [gin-gonic/gin#3409]
Hello.
I'm trying to create HTML api it means server responds HTML tag.
Now, I tested simple case.
This is my code.

<img width="1077" alt="スクリーンショット 2022-11-22 15 20 25" src="https://user-images.githubusercontent.com/114799344/203240323-4501fe58-169f-41c5-9bc1-67f7167b041a.png">

I intend to get only p tag.

<img width="1399" alt="スクリーンショット 2022-11-22 15 19 48" src="https://user-images.githubusercontent.com/114799344/203240275-7406a383-4b6f-4fe5-a041-1704ba1d33de.png">

but as you can see, HTML has other basic tags.

how do I remove them?

**Comment by dongsuo** [comment]
Have you tried `c,String`?

**Comment by chihiro-yabuta** [comment]
thank you for your reply, @dongsuo
but it is simple case, actually I want to get **SVG** tag.
if I use string or writer, I got wrapped pre tag

<img width="1398" alt="スクリーンショット 2022-11-22 16 29 38" src="https://user-images.githubusercontent.com/114799344/203252189-c4ee7ea3-d713-44dd-aaeb-35f63055465e.png">

if I attach html, I could get but html is not pure svg.

[branch](https://github.com/chihiro-yabuta/cardme/blob/dev-server/server/api/main.go#L17)

<img width="1401" alt="スクリーンショット 2022-11-22 16 35 07" src="https://user-images.githubusercontent.com/114799344/203252963-9916c17d-f586-4808-ad2e-4cca10a2e068.png">

so I can't get api through url directly.

actually, I want to get api

```
<img src={url} />
```

like this.

**Comment by dongsuo** [comment]
I think the `pre` tag is added by Chrome. Try check the response in `cURL` or postman, or network tab of Chrome Devtools?
Also I don't know what your purpose is, but I advice you use JSON struct to wrap your html string like this: 
```
{
  "html_snippet":  "<img src={url} />"
}

**Comment by chihiro-yabuta** [comment]
<img width="1260" alt="スクリーンショット 2022-11-22 17 34 20" src="https://user-images.githubusercontent.com/114799344/203264949-55664bc7-e499-4cb0-ba02-477efe653a43.png">

but safari renders as well.

I want to get **SVG**, not string.
and img is example.
I mean I want to be enable to distribute SVG image from url.

**Comment by chihiro-yabuta** [comment]
<img width="1400" alt="スクリーンショット 2022-11-22 18 02 10" src="https://user-images.githubusercontent.com/114799344/203271423-fe32fd90-f974-42fb-b84d-f9d9acc1d3f9.png">

 I want to render like this

**Comment by chihiro-yabuta** [comment]
@dongsuo
<img width="1400" alt="スクリーンショット 2022-11-22 18 02 10" src="https://user-images.githubusercontent.com/114799344/203271423-fe32fd90-f974-42fb-b84d-f9d9acc1d3f9.png">

 I want to render like this

**Comment by chihiro-yabuta** [comment]
<img width="1400" alt="スクリーンショット 2022-11-23 10 51 00" src="https://user-images.githubusercontent.com/114799344/203455083-58598271-2bfd-4ec1-bc3e-d780afb2cd22.png">

```
c.Writer.Header().Set("Content-Type", "image/svg+xml")
```

is answer for me.
