### ISSUE TITLE
[Question] How to get multidomain/subdomain (virtualhost) routing?

### ISSUE THREAD

**Issue by lawlite** [gin-gonic/gin#347]
Hello there!
I have a question: How to get multidomain/subdomain (virtualhost) routing?

I tried this,

    r := gin.Default()
    r.GET("example1.com/", func(c *gin.Context) { // http://example1.com
        c.String(200, "welcome to example1.com")
    })
    r.GET("example2.com/", func(c *gin.Context) { // http://example2.com
        c.String(200, "welcome to example2.com")
    })

but it didn't work, so I looked features of HttpRouter.
https://github.com/julienschmidt/httprouter#multi-domain--sub-domains

I referred that and tried this.

    r := gin.Default()
    r2 := gin.Default()
    ...
    ...
    hs := make(HostSwitch)
    hs["example1.com"] = r
    hs["example2.com"] = r2
    http.ListenAndServe(":80", hs)

Now, it works like I intended. But I think that this is not good. (Because I am a beginner of Golang.)

Is there a better way to do it?

And I wanna request one more thing.

Please support LoggerWithWriter (logger.go) function to write its host like
"[GIN] example1.com 2015/06/23 (...)"
"[GIN] example2.com 2015/06/23 (...)"
.

Thank you! I started to learn Golang recently and I starred Gin just yesterday, this framework is awesome.

**Comment by dkoston** [comment]
You'll need to use a different router per host (as shown in your working example) because the routes are expected to be different for each host. If you use named functions, it's possible to re-use the functions in both host's routes. 

If you need to use a custom logging format, I suggest writing a logger middleware that suits your needs. You could choose 2 options:

1.  Support custom logging formats based on how the middleware is instantiated (more challenging but useful to the community)
2.  Write the middleware to support your specific logging format (easier but less useful to others)

You can use both the logger and commonlog middleware as examples:

https://github.com/gin-gonic/gin/blob/master/logger.go
https://github.com/gin-gonic/contrib/blob/master/commonlog/commonlog.go

**Comment by javierprovecho** [comment]
Checkout this example from httprouter:





Multi-domain / Sub-domains
Here is a quick example: Does your server serve multiple domains / hosts? You want to use sub-domains? Define a router per host!

// We need an object that implements the http.Handler interface.
// Therefore we need a type for which we implement the ServeHTTP method.
// We just use a map here, in which we map host names (with port) to http.Handlers
type HostSwitch map[string]http.Handler

// Implement the ServerHTTP method on our new type
func (hs HostSwitch) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    // Check if a http.Handler is registered for the given host.
    // If yes, use it to handle the request.
    if handler := hs[r.Host]; handler != nil {
        handler.ServeHTTP(w, r)
    } else {
        // Handle host names for wich no handler is registered
        http.Error(w, "Forbidden", 403) // Or Redirect?
    }
}

func main() {
    // Initialize a router as usual
    router := httprouter.New()
    router.GET("/", Index)
    router.GET("/hello/:name", Hello)

    // Make a new HostSwitch and insert the router (our http handler)
    // for example.com and port 12345
    hs := make(HostSwitch)
    hs["example.com:12345"] = router

    // Use the HostSwitch to listen and serve on port 12345
    log.Fatal(http.ListenAndServe(":12345", hs))
}





NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by javierprovecho** [comment]
If you want to have a heavy virtual host configuration with different routes, then use httprouter example,

**Comment by manucorporat** [comment]
It depends on your requirements. What do you want to do? what is host dependent?
if each host has a different set of routes, then yes, you should use different router instances, that is perfectly fine.

but if you are going to share the same routes, you could try to use a middleware and check `c.Request.Host`.

>Please support LoggerWithWriter (logger.go) function to write its host like
"[GIN] example1.com 2015/06/23 (...)"
"[GIN] example2.com 2015/06/23 (...)"

good idea!

**Comment by lawlite** [comment]
Thanks a lot!
