### ISSUE TITLE
Panic  context.engine is nil

### ISSUE THREAD

**Issue by cxy1620541673** [gin-gonic/gin#3483]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	ctx := &gin.Context{}
        ctx.Done()
}
```

## Expectations

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
```

![image](https://user-images.githubusercontent.com/6916669/215996314-21bf78be-bd14-4926-bbfe-2689e29732cb.png)

**Comment by ZackaryWelch** [comment]
Duplicate of https://github.com/gin-gonic/gin/issues/3178
