### ISSUE TITLE
How can i get the url pattern with context

### ISSUE THREAD

**Issue by blight19** [gin-gonic/gin#3493]
hello 
     When i want code RESTAPI ,I want to get a url pattern so that i can use casbin to control permissions,but i can't get it.
     the code is 
`
func (a *BasicAuthorizer) CheckPermission(c *gin.Context) bool {
	user := a.GetUserName(c)
	method := strings.ToLower(c.Request.Method)
	path := c.Request.URL.Path
	allowed, err := a.enforcer.Enforce(user, path, method)
	if err != nil {
		panic(err)
	}
	return allowed
}

`
the url is 
POST   /admin/user/:id

**Comment by whatwewant** [comment]
just `c.Request.RequestURI`

**Comment by blight19** [comment]
> just `c.Request.RequestURI`
I didn't express it clearly,i want to get all the url,and finally use it to casbin ,and then check the premission.
finally i use c.HandlerName()
