### ISSUE TITLE
Need to be able to choose the action delimiters of templates

### ISSUE THREAD

**Issue by zaibon** [gin-gonic/gin#35]
I'm using Gin with angularjs, since angular also use {{ }} we have change the action delimiters of go templates.

**Comment by dalu** [comment]
? wontfix?
Was this fixed or not?

**Comment by barrongineer** [comment]
I use ```Context.Data(code, content-type, data)``` to serve Angular templates. Hope this helps anyone struggling with this...

**Comment by diegogub** [comment]
I solved it doing so:

`html, err := template.New("").Delims("[[", "]]").ParseFiles("site/index.html", "site/login.html", "site/signup.html")
	if err != nil {
		panic(err)
	}
	router.SetHTMLTemplate(html)`

**Comment by behouba** [comment]
This also worked for me:

```
...
router.Delims("[[", "]]")
router.LoadHTMLGlob("website/templates/*")
...
```
