### ISSUE TITLE
Expose gin.Context handlers field

### ISSUE THREAD

**Issue by danielalves** [gin-gonic/gin#351]
Hi guys,

I'm writing a gin Statsd middleware so I can measure request handlers performance. The idea is to label requests stats just like NewRelic does for other languages. The pattern will be something like: `repo.user.app.module.handlermethod`. I'm facing a problem, though: I couldn't find a good way to get the current request handler.

I know you've recently added the `gin.Engine Routes() ` method. I could get its result and perform a pattern matching against the current request `URL.Path`, but: **1)** I would be replicating logic that's already inside gin **2)** It would be a performance waste since gin already did it before calling the middleware.

Looking at gin's code, I've found that this issue would be solved just by exposing the `gin.Context handlers` field. Or, if there are safety concerns about users altering it after  initialization, we could just offer a method that returns a copy of it, like:

```go
// gin.go
func (c *Context) AllHandlers() HandlersChain {
	handlersCopy := make(HandlersChain, len(c.handlers))
	copy(handlersCopy, c.handlers)
	return handlersCopy
}
```
That way, I could implement the statsd middleware with something like:

```go
func statFromPath(path string) string {
	return strings.Replace(path, "/", ".", -1)
}

func StatsdMiddleware(engine *gin.Engine) gin.HandlerFunc {

	return func(c *gin.Context) {

		requestHandler := c.AllHandlers().Last()
		fn := runtime.FuncForPC(reflect.ValueOf(requestHandler).Pointer())
		stat := strings.ToLower(statFromPath(fn.Name())))

		statsdUtils.MeasureAndWriteTimingFor(stat, func() {
			c.Next()
		})
	}
}
```
What do you think?

**Comment by manucorporat** [comment]
I am worried about people using it to create dangerous hacks. Like it happened with the infamous `Context.Engine`.

why do you need to label the requests with the handler name? why the path does not work?

**Comment by manucorporat** [comment]
How about this?

```go
func (c *Context) HandlerName() string {
	return nameOfFunction(c.handlers.Last())
}
```

**Comment by danielalves** [comment]
@manucorporat In a RESTful api, the path could contain parameters, for example: /player/:player-id/cards -> player/1234/cards -> player.1234.cards. The fact is, you do not want to track timing separately for each possible parameter, but for a certain route handler. Someone could say that I could strip the parameters from the path, what gets us to the real problem: instrumentation should not care about the path, but the method used to handle that path. After all, I could use any method to handle a given path. And this is exactly what NewRelic does for Ruby, C# and so on: it logs handlers, not paths.

**Comment by manucorporat** [comment]
@danielalves ok! that sounds like a perfect use case! that is all what I needed.

is HandlerName() ok for you? if so. a better name?

**Comment by danielalves** [comment]
@manucorporat Yes, this also a good solution! And about the dirty hacks you said, that's why I suggested a method that returns a copy of the handles array, not the real thing :smile: 
But anyway, your code would also solve my problem

**Comment by manucorporat** [comment]
@danielalves right, but the copy of the handlers does not prevent to an "alternative" middleware system.

**Comment by danielalves** [comment]
@manucorporat Hum, I get it. So `HandlerName`, it is! :+1:

**Comment by danielalves** [comment]
@manucorporat Any idea when it'll be available at master?

**Comment by manucorporat** [comment]
@danielalves now!! https://github.com/gin-gonic/gin/commit/95c08d5f84a404a197a0264951489b105ed8ad2d

Thanks for the report!

**Comment by danielalves** [comment]
@manucorporat Wow! Fast! You're welcome! :smile:

**Comment by oryband** [comment]
hey @danielalves , did you finish this middleware? care to release it? i'm working on a statsd middleware as well, which does a slightly different thing. we might be able to merge them as one.

**Comment by danielalves** [comment]
Hey @oryband! I don't mind at all, but I need to do a lot of cleaning first. I'll work on it and will definitely let you know when its ready.

**Comment by oryband** [comment]
@danielalves just created a PR with my middleware. Feel free to review and suggest further additions: gin-gonic/contrib#55

**Comment by danielalves** [comment]
@oryband Cool! :+1:

**Comment by danielalves** [comment]
@oryband It took me sometime, but here it is: https://github.com/descomplica/pencil It is not as configurable as yours, but I think it glues things and makes life easier for devs :blush:

**Comment by oryband** [comment]
thanks @danielalves , it looks nice! i think it can integrate well with my middleware, since it accepts an interface.

@manucorporat have you seen the pr?

**Comment by danielalves** [comment]
@oryband Cool!

**Comment by manucorporat** [comment]
@oryband @danielalves sorry everybody, I have been disconnected for vacations, but I am back to work with the batteries fully charged!

**Comment by danielalves** [comment]
:+1:
