### ISSUE TITLE
c.Param don't parse parameters starting with 'p' and 'l'

### ISSUE THREAD

**Issue by murongg** [gin-gonic/gin#3513]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description
c.Param don't parse parameters starting with 'p' and 'l'

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:UUID", func(c *gin.Context) {
	        uuid := c.Param("UUID")
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:9000/hello/g2wycubs7rh7tay4eako
Hello g2wycubs7rh7tay4eako
```

## Actual result

```
$ curl http://localhost:9000/hello/g2wycubs7rh7tay4eako
404 page not found
```

## Environment

- go version: go1.19.4
- gin version (or commit ref):v1.7.0
- operating system: macOS 13.1 / Docker 20

**Comment by thinkerou** [comment]
please use the latest version v1.9.0, thanks!
