### ISSUE TITLE
Refresh page

### ISSUE THREAD

**Issue by Marini83** [gin-gonic/gin#352]
Hello,

I'm a total newb at react/ go / gin environment.  I modified an index.jsx page and even though i restarted the server , the updates are not showing up?! what gives... 

I'm also running webpack.

**Comment by javierprovecho** [comment]
Hi there,




If I understand you right, you try to serve an static index.js file, you make a change on it, and even after restarting the server you don't see the changes?




This seems to be a cache problem with your browser.




Try deleting your cache, or accessing again from an incognito tab.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by Marini83** [comment]
Hello  Javier,

Yes, I'm trying to use React so I modified one of the header files.  I did restart the server and tried incognito mode but to no success. Looks pretty simple but not sure what to do,  I start the server using "go run server.go"

**Comment by zeroactual** [comment]
Just to be clear, you're getting your file from the server, but it's showing the old version from before you made your changes?

Assuming you're using chrome an easy way to check that your browser hasn't cached the old file open up the developer tools (F12 key on windows) navigate to the network tap and check the disable cache checkbox. If you refresh the page with that option turned on, it should download the newer file for you.

**Comment by Marini83** [comment]
I did turn off caching but it still displays the old one...

I'm actually basing it off of this boilerplate https://github.com/weisuke/react-reflux-go-boilerplate  

It is using webpack as well.

**Comment by manucorporat** [comment]
@Marini83 this is very unlikely to be a gin issue since Gin does not implement any kind of caching.
- Gin issue (probably not)
- Go Standard Library issue (very very unlikely)
- Webpack issue
- Your browser
- A reverse proxy you are using (nginx?)
- CDN?
- React stack issue
- You could be serving a unmodified copy of index.jsx (due a wrong path).

I can not diagnose without more information: configuration, source code...

**Comment by javierprovecho** [comment]
@Marini83, as manu said, it is probably a proxy you have in middle, or a wrong path. if you can give us some code and your folder structure, maybe we can help further.

**Comment by Marini83** [comment]
This is index.jsx which I tried to modify. I think it could be webpack caching....
    var React = require('react');
    var Link = require('react-router').Link;
 
     require('./style.scss')

     var Header = React.createClass({
      render() {
        return (
            <div className="header">
                <nav>
                    <ul className="nav nav-pills pull-right">
                        <li role="presentation" className="active">
                            <Link to="dashboard">Dashboard</Link>
                        </li>
                        <li role="presentation">
                            <Link to="about">About</Link>
                        </li>
                    </ul>
                </nav>
                <h3 className="text-muted">I changed this Text but nothing happened</h3>
            </div>
            )
          }
       });

     module.exports = Header;

**Comment by Marini83** [comment]
Javier it was a wrong path,  I want to thank you guys for your help!  After restarting the server and webpack i realized something wasn't adding up.
