### ISSUE TITLE
Cant delete Date header

### ISSUE THREAD

**Issue by alvarolm** [gin-gonic/gin#354]
c.Writer.Header().Del("Date") or c.Header("Date", "") doesn't seems to have any affect, im using this middleware:
```
func removeDate(c *gin.Context) {
	c.Writer.Header().Del("Date")
	//c.Header("Date", "")
}
```

**Comment by alvarolm** [comment]
works:
```
func removeDate(c *gin.Context) {
	K := c.Writer.Header()
	K["Date"] = nil
}
```

**Comment by manucorporat** [comment]
@alvarolm I would like to know why `c.Writer.Header().Del("Date")` didn't work.
I will check out the standard library source code.

**Comment by alvarolm** [comment]
http://golang.org/src/net/http/server.go?h=Date#L664
