### ISSUE TITLE
panic in validator

### ISSUE THREAD

**Issue by semihalev** [gin-gonic/gin#355]
Hi All,

I received panic on every request. Here the panic log.

2015/06/28 19:32:06 Panic recovery -> runtime error: index out of range
/usr/local/go/src/runtime/panic.go:387 (0x466f18)
        gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:12 (0x4660ae)
        panicindex: panic(indexError)
/root/go/src/gopkg.in/bluesuncorp/validator.v5/validator.go:369 (0x6dbd16)
/root/go/src/gopkg.in/bluesuncorp/validator.v5/validator.go:333 (0x6da7b2)
/root/go/src/gopkg.in/bluesuncorp/validator.v5/validator.go:324 (0x6da600)
/root/go/src/github.com/gin-gonic/gin/binding/default_validator.go:20 (0x6195e7)
        (*defaultValidator).ValidateStruct: if err := v.validate.Struct(obj); err != nil {
/root/go/src/github.com/gin-gonic/gin/binding/binding.go:60 (0x619539)
        validate: return Validator.ValidateStruct(obj)
/root/go/src/github.com/gin-gonic/gin/binding/json.go:24 (0x61ab4e)
        jsonBinding.Bind: return validate(obj)
<autogenerated>:6 (0x61b177)
/root/go/src/github.com/gin-gonic/gin/context.go:244 (0x528fb2)
        (*Context).BindWith: return c.BindWith(obj, binding.JSON)
/root/go/src/github.com/gin-gonic/gin/context.go:235 (0x528e6e)
        (*Context).Bind: // else --> returns an error

**Comment by semihalev** [comment]
+Go version is 1.4.2

**Comment by manucorporat** [comment]
@semihalev can you show the code that triggers the panic + struct?

**Comment by manucorporat** [comment]
it may be an issue of the validator @joeybloggs

**Comment by manucorporat** [comment]
@semihalev A workaround is to disable the validation:
```go
func init() {
    gin.DisableBindValidation()
}
```

This will disable all the validations, even the successful ones, but at least it will not panic until we fix it.

**Comment by joeybloggs** [comment]
Yes the code would be helpful also which version of validator do you have v5.x.x 

I published some updates, however they should be completely backward compatible.

**Comment by semihalev** [comment]
The validator version is latest 5.9.

The code:
```go
type ExternalCMD struct {
	Userid string      `json:"userid"`
	Action uint32      `json:"action"`
	Data   interface{} `json:"data,omitempty"`
}

func kickAction(c *gin.Context) {
	var ecmd ExternalCMD
	c.Bind(&ecmd)

	var user *User
	users.Lock()
	for _, tmpuser := range users.m {
		if tmpuser.mIzmoId == ecmd.Userid {
			user = tmpuser
		}
	}
	users.Unlock()

	if user == nil {
		c.JSON(http.StatusOK, gin.H{"status": "error", "message": "user not found"})
		return
	}

	if ecmd.Action == 10000 {
		user.Disconnect()
	}

	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

v1.POST("/kick", kickAction)
```

The POST Payload: {"userid":"123456", "action":10000}

**Comment by semihalev** [comment]
I tested validator 5.8.1, same result.

**Comment by joeybloggs** [comment]
@manucorporat @semihalev 

if I could get what values are set within the ExternalCMD struct before passing it to validate.Struct I will look into this asap.

**Comment by joeybloggs** [comment]
please see https://github.com/bluesuncorp/validator/issues/85 for more comments, it seems to be a bug within validator regarding type interface.

**Comment by semihalev** [comment]
gin.DisableBindValidation() solved the problem. @joeybloggs marked bug.

**Comment by manucorporat** [comment]
I will keep this open to track the state of the bug.

**Comment by joeybloggs** [comment]
hopefully this should now be solved with the 5.9.1 release, please let me know if there are anymore issues.

P.S. there is one other issue in 5.9.x I'm working on updating the Flatten() function to handle the new dive functionality that slipped my mind...but if your not using, no problems

**Comment by manucorporat** [comment]
@joeybloggs good job! but when is this going to be merged in production? is this going to be a hotfix in v5? or will I need to change the import to v6?

**Comment by joeybloggs** [comment]
5.9.1 is already released

**Comment by manucorporat** [comment]
@joeybloggs good job! I think we can close this issue.
@semihalev

**Comment by thinkong** [comment]
I'm sorry to bring this issue from the dead.... 
But if i use "binding:required" and then not send that specific node in the JSON it will crash my server...
only leaving "Field Validation for "xxx" failed on the "required" tag

is it supposed to do this? I want this to be required but if i enable this... my server will be very vulnerable to attacks..

**Comment by javierprovecho** [comment]
@thinkong it is not supposed to do that. 

cc/ @manucorporat

**Comment by joeybloggs** [comment]
@thinkong It seems like validation passed, from the error message you received but strange that your server would crash.

Could you provide a stack trace, the code and POST data you used, I could then take a look to at least verify that validation succeeded or caused an issue.

**Comment by joeybloggs** [comment]
@thinkong is this an issue or related to your updated comment here: https://github.com/gin-gonic/gin/issues/365?

cc/ @javierprovecho @manucorporat

**Comment by thinkong** [comment]
@joeybloggs I can't get a stack trace.. (it doesn't show me any) it just spits out "Field Validation for "xxx" failed on the "required" tag" and exits the program.. 
I guess i double posted this issue on #365

**Comment by joeybloggs** [comment]
@thinkong would you be able to provide a code sample and the data you posted? I may be able to find something

**Comment by thinkong** [comment]
@joeybloggs 

basically 
`````
type InnerStruct struct {
        D  interface `json:"d" binding:"required"`
        A int      `json:"ma" binding:"required"`
        B int      `json:"mi" binding:"required"`
    } 

type MyJsonName struct {
    AStruct InnerStruct `json:"d"`
    P int    `json:"pid"`
    S string `json:"sid"`
}
`````
then if i pass 
`````
{
  "sid": "sadfasdfasdf-asdfas-asdfsadf",
  "pid": 12312312312123,
  "d": {}
}
`````

it crashes/panics

**Comment by joeybloggs** [comment]
Thanks I'll take a look tomorrow morning

**Comment by thinkong** [comment]
@joeybloggs 
oh.. someone on my team added a log.Fatal(err) in the code.. causing these.. 
Really sorry for the confusion.

**Comment by joeybloggs** [comment]
OK just glad it's all sorted out, and that it wasn't the validator :)

**Comment by joeybloggs** [comment]
@javierprovecho @manucorporat I think this can be closed now it was not an issue with the validator that prompted the reopening of this issue.
