### ISSUE TITLE
Why should we rely on github.com/chenzhuoyu/base64x? but this library is not used in the source code at all

### ISSUE THREAD

**Issue by BigCatGit** [gin-gonic/gin#3567]
## Why should we rely on github.com/chenzhuoyu/base64x? but this library is not used in the source code at all

go.mod
github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311 // indirect

go.sum
github.com/chenzhuoyu/base64x v0.0.0-20211019084208-fb5309c8db06/go.mod h1:DH46F32mSOjUmXrMHnKwZdA8wcEefY7UVqBKYGjpdQY=
github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311 h1:qSGYFH7+jGhDF8vLC+iwCD4WpbV1EBDSzWkJODFLams=
github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311/go.mod h1:b583jCggY9gE99b6G5LEC39OIiVsWj+R97kbl5odCEk=

Please let me know the reason, thank you

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin/commit/8374ed2268e39c1033f6f3dc5c794b399285f164

**Comment by BigCatGit** [comment]
thanks
