### ISSUE TITLE
Reverse route generation

### ISSUE THREAD

**Issue by rafroehlich2** [gin-gonic/gin#357]
I would like to help in adding the ability for routes to be named in the router and then reconstructed elsewhere in the application. One of the ways I was looking into doing this was to simply add named methods to the router.

``` go
router.NamedGET("show-user", "/users/:id", userShow)
```

The advantage to this would be to not change the return type of the router methods and lose chaining. The named routes could be added to the engine for access through the `context`.

``` go
func userShow(c *gin.Context) {
    url := c.Route("user-show").With(gin.Pair{"id": 44}).URL
    // or
    path := c.Route("user-show").With(gin.Pair{"id": 44}).Path
}
```

Does this seem in the scope of the framework? If so, what changes to the API would be welcomed to accomplish this?

**Comment by manucorporat** [comment]
@rafroehlich2 what is the use case of this?

**Comment by rafroehlich2** [comment]
@manucorporat  The use case would be similar to the function of the Rails link helpers. When generating links in templates or JSON responses you can use the one provided to the router to keep them up to date. In a JSON server I built I use a similar method to handle HATEOAS.

**Comment by dre1080** [comment]
@manucorporat :+1:  would also like something like this for use in templates...

**Comment by ahmet** [comment]
:+1:

**Comment by douglarek** [comment]
+1

**Comment by EagleChen** [comment]
👍

**Comment by Joey92** [comment]
+1 i really need this to set the location header on REST API responses

**Comment by adred** [comment]
Please implement this.

**Comment by wangzitian0** [comment]
+1, It will be easy to generate Restful Hypermedia API if here support this feature.

**Comment by jmp0xf** [comment]
+1

**Comment by vchakoshy** [comment]
+1

**Comment by Solution** [comment]
Is there any chance to get this feature to gin? cc @appleboy @austinheap @javierprovecho @thinkerou

**Comment by pior** [comment]
Every services I've been working on has needed this at some point.
Definitely needed 👍

**Comment by mehran-prs** [comment]
+1

**Comment by pior** [comment]
This issue has not received much attention since 2015. 
Is this a matter of developer bandwidth?
Would a PR implementing this be accepted? (assuming it would meet the expected code quality)

**Comment by appleboy** [comment]
@pior PR Welcome.

**Comment by pedrorijo91-hofy** [comment]
hey. what's the status of this feature request? is there any known workaround? or has everyone been solving it in it's own custom way? would be good to change a URL in routing and dont break a ton of templates with manual reverse route 😄
