### ISSUE TITLE
binding post form-data

### ISSUE THREAD

**Issue by thellimist** [gin-gonic/gin#361]
I'm sending post request as form-data (shown below) but `c.Bind(&json, binding.Form)` doesn't bind form-data instead it binds URL parameters (localhost:8080?name=XXX&...). 

`c.PostForm` works fine.

`binding.Form` should bind form-data for POST.

----

POST /signup HTTP/1.1
Host: localhost:8080
Cache-Control: no-cache
Postman-Token: a7f408c6-1749-f9c8-0a57-801a2a0448f6
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW<br/>Content-Disposition: form-data; name="name"<br/><br/>FormName<br/>----WebKitFormBoundary7MA4YWxkTrZu0gW<br/>Content-Disposition: form-data; name="email"<br/><br/>Form@Mail.com<br/>----WebKitFormBoundary7MA4YWxkTrZu0gW

**Comment by manucorporat** [comment]
Well, this is due the stupid behaviour of `http.Request.Form` which mixes all the form values.
Two workarounds:
- Rename the keys, don't use the same names in the query and the multipart.
- Use `c.BindWith(&obj, binding.FormMultipart)`

**Comment by manucorporat** [comment]
@thellimist make sure you update gin. I just added it:
https://github.com/gin-gonic/gin/commit/4194adce4cd5c971281999706b801a643750bfaa

**Comment by manucorporat** [comment]
@thellimist closing issue...
