### ISSUE TITLE
Having trouble getting the form data in a POST request

### ISSUE THREAD

**Issue by faeronsayn** [gin-gonic/gin#364]
```go
// LoginJSON stuff
type LoginJSON struct {
	User     string `json:"user" binding:"required"`
	Password string `json:"password" binding:"required"`
}

func Create(c *gin.Context) {
	var json LoginJSON
	c.Bind(&json) // This will infer what binder to use depending on the content-type header.
	if json.User == "manu" && json.Password == "123" {
		c.JSON(http.StatusOK, gin.H{"status": "you are logged in"})
	} else {
		c.JSON(http.StatusUnauthorized, gin.H{"status": "unauthorized"})
	}
}
```

the Create handler is called from a POST request. I'm using Postman to test the post calls and it's simply not recognizing it. The response is unauthorized, even when I have "manu" and "123" as my User and Password. 

<img width="1069" alt="screen shot 2015-07-04 at 7 22 53 pm" src="https://cloud.githubusercontent.com/assets/3820846/8509711/2f35eec6-2282-11e5-9dbf-1abecec137fb.png">

I have also tried `c.BindWith(&json, binding.Form)`. Both of them do not work.

I've also tried `c.PostForm("User")` and that doesn't get me `"manu"` it just gives me an empty string. Not exactly sure how to get simple form data without and binding or validation, I just want to get the data.

**Comment by manucorporat** [comment]
you are not parsing json!

```go
type LoginForm struct {
    User     string `form:"user" binding:"required"`
    Password string `form:"password" binding:"required"`
}
```
notice I changed `json:"user"` to `form:"user"`

**Comment by faeronsayn** [comment]
@manucorporat, not sure what i'm doing wrong but it's not working for me. 

Something simple like this 

```
func Create(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"response": c.PostForm("stuff")})
}
```

I'm getting `{"response": ""}` as my response. Here is a screenshot

<img width="1083" alt="screen shot 2015-07-04 at 11 50 47 pm" src="https://cloud.githubusercontent.com/assets/3820846/8510237/d2e81f74-22a7-11e5-82f8-df70cc12db76.png">

**Comment by javierprovecho** [comment]
@faeronsayn check out possible solutions:

1 - are you using a `POST` handler?
```go
r.POST("/", func(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"response": c.PostForm("stuff")})
})
```
2 - are you sending correctly the post request? try this:
```bash
$ curl -X POST --data "stuff=123" localhost:8080
{"response":"123"}
```

**Comment by manucorporat** [comment]
@faeronsayn it works for me:
<img width="1440" alt="screen shot 2015-07-05 at 13 22 36" src="https://cloud.githubusercontent.com/assets/127379/8511486/f4a3b99a-2318-11e5-80d6-96b5e00dbb34.png">

**Comment by manucorporat** [comment]
@faeronsayn I see you configured a header manually? `Header (1)`
can you show it to us?

**Comment by javierprovecho** [comment]
To give you better assistance we request full code or large part of it. If you have any problem making it public here, you can send it to either @manucorporat 's or my email (1).




1. javiertitan@gmail.com



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by faeronsayn** [comment]
@manucorporat ahh, it seems like removing the header did the trick. Slightly weird though. The header just identified the content-type to `application/json`. Here is the screenshot.

<img width="1073" alt="screen shot 2015-07-05 at 3 20 50 pm" src="https://cloud.githubusercontent.com/assets/3820846/8513021/862fd5d2-2329-11e5-88b6-e9dcb7901502.png">

**Comment by javierprovecho** [comment]
@faeronsayn of course not, because you are not sending JSON, you are sending form based data.

**Comment by manucorporat** [comment]
@faeronsayn 
> ahh, it seems like removing the header did the trick. 

once you removed the wrong content-type, Postman was able to set the correct one under the hood.

>So if I'm sending whole objects as my form-data, this might not work? Here is the screenshot.

 as @javierprovecho said, there is no way it would work. `form-data` format is not JSON, it is a completely different data format. so, if you are declaring that the data in the body is json, `c.Bind()` will try to decode it as a json string, this process will obviously fail returning a "invalid json syntax" error.

**Comment by faeronsayn** [comment]
Hi @manucorporat and @javierprovecho. I want to POST JSON data from the client. If I do that from the client, how can I access that JSON data with golang and gin? I know if I was simply using `net/http` package I could use the `req.Body` and use `json.Decoder` to get the JSON. Does gin provide similar functionality or handle this in a better fashion?

**Comment by ovr** [comment]
Btw, When I was trying Postman with `form-data`, it's not possible to get POST values
Seems it's way is not supported

```
err := request.ParseForm()
username := request.Form.Get("username")
```

Username will be always ""

But another `x-www-form-urlencoded` is working correct

Maybe this will help someone to detect an error

Sorry for off topic

**Comment by EtienneR** [comment]
@ovr `form-data` working fine without header define in Postman and using `c.Bind()` into the go file.

**Comment by luthfirrahmanb** [comment]
guys i have a little problem, i want to post the data and test it from postman, but the data is null on xampp

![image](https://cloud.githubusercontent.com/assets/18209502/25335096/bd986922-291b-11e7-9247-0364d09125c6.png)
and this is my code:
`package main

import (
	"bytes"
	"database/sql"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "root:@tcp(127.0.0.1:3306)/gotest")
	if err != nil {
		fmt.Print(err.Error())
	}
	defer db.Close()

	err = db.Ping()
	if err != nil {
		fmt.Print(err.Error())
	}
	type Person struct {
		Id         int
		First_Name string
		Last_Name  string
	}
	router := gin.Default()

	router.POST("/person", func(c *gin.Context) {
		var buffer bytes.Buffer
		first_name := c.PostForm("first_name")
		last_name := c.PostForm("last_name")
		stmt, err := db.Prepare("insert into person (first_name, last_name) values(?,?);")
		if err != nil {
			fmt.Print(err.Error())
		}
		_, err = stmt.Exec(first_name, last_name)

		if err != nil {
			fmt.Print(err.Error())
		}

		buffer.WriteString(first_name)
		buffer.WriteString(" ")
		buffer.WriteString(last_name)
		defer stmt.Close()
		name := buffer.String()
		c.JSON(http.StatusOK, gin.H{
			"message": fmt.Sprintf(" %s successfully created", name),
		})
	})

	router.Run(":3000")
}
`
Thanks :)

**Comment by EtienneR** [comment]
Add data binding in your "Person" struct.

```go
type Person struct {
	Id         int
	First_Name string `db:"first_name" form:"first_name"`
	Last_Name  string `db:"last_name" form:"last_name"`
}
```

Then get values from the form.

```go
person:= db.Person{}
c.Bind(&person)

if article.First_Name != "" && person.Last_Name != "" {
	stmt, err := db.Prepare(`INSERT INTO person (first_name, last_name) VALUES (?,?)`, person.First_Name, person.Last_Name)
}
```

**Comment by luthfirrahmanb** [comment]
@EtienneR  thanks for your help sir, but i have another little problem, the error message is 

> db.Person undefined (type *sql.DB has no field or method Person)

and this is my code:
`package main

import (
	"bytes"
	"database/sql"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "root:@tcp(127.0.0.1:3306)/gotest")
	if err != nil {
		fmt.Print(err.Error())
	}
	defer db.Close()

	err = db.Ping()
	if err != nil {
		fmt.Print(err.Error())
	}
	type Person struct {
		Id         int
		First_Name string `db:"first_name" `
		Last_Name  string `db:"last_name"`
	}
	router := gin.Default()
	router.POST("/person", func(c *gin.Context) {
		var buffer bytes.Buffer

		person := db.Person{}
		c.Bind(&person)

		if person.First_Name != "" && person.Last_Name != "" {
			stmt, err := db.Prepare(`INSERT INTO person (first_name, last_name) VALUES (?,?)`)
		}

		if err != nil {
			fmt.Print(err.Error())
		}

		if err != nil {
			fmt.Print(err.Error())
		}

		name := buffer.String()
		c.JSON(http.StatusOK, gin.H{
			"message": fmt.Sprintf(" %s successfully created", name),
		})

	})

	router.Run(":3000")
}
`
Thanks :)

**Comment by EtienneR** [comment]
`person := Person{}` instead of `person:= db.Person{}`

**Comment by jin-pin-mei-le** [comment]
> Add data binding in your "Person" struct.
> 
> ```go
> type Person struct {
> 	Id         int
> 	First_Name string `db:"first_name" form:"first_name"`
> 	Last_Name  string `db:"last_name" form:"last_name"`
> }
> ```
> 
> Then get values from the form.
> 
> ```go
> person:= Person{}
> c.Bind(&person)
> 
> if article.First_Name != "" && person.Last_Name != "" {
> 	stmt, err := db.Prepare(`INSERT INTO person (first_name, last_name) VALUES (?,?)`, person.First_Name, person.Last_Name)
> }
> ```

success !!!
