### ISSUE TITLE
how to dynamic validate the params? 

### ISSUE THREAD

**Issue by itnik** [gin-gonic/gin#365]
eg: the user's attributes in different function has defferent required attributes. for example in login function the account and password are required but in update function the id is required. so how can i solve this problem?

**Comment by javierprovecho** [comment]
@itnik can you post your actual code to understand better which are your paths and where are your parameters?

**Comment by thinkong** [comment]
I've a similar problem... (or it may be a different problem) 
I have tried 
`````
type MyStruct struct{
A,B string
C interface{}
}
`````
and then tried to do
`````
var obj MyStruct
 c.BindJSON(&obj)
`````

but it keeps showing me a validator error.. 
how would i properly bind a json so that "C" is optional and could be anything?

**Comment by itnik** [comment]
@javierprovecho @thinkong 
like this .I have a obj 

type User struct {
	Id            string `json:"id"`
	Account       string `json:"account"`
	Password      string `json:"password"`
	Nick          string `json:"nick"`
	Sign          string `json:"sign"`
	Avatar        string `json:"avatar"`
}

when i do login function
I should validate the Account and Password ,right.so i should change this obj like this

type User struct {
	Id            string `json:"id"` 
	Account       string `json:"account" binding:"required"`
	Password      string `json:"password" binding:"required"`
	Nick          string `json:"nick"`
	Sign          string `json:"sign"`
	Avatar        string `json:"avatar"`
}

right?
when i want to create the delete function the attribute Id should be required.so i change the obj again like this

type User struct {
	Id            string `json:"id" binding:"required"` 
	Account       string `json:"account" binding:"required"`
	Password      string `json:"password" binding:"required"`
	Nick          string `json:"nick"`
	Sign          string `json:"sign"`
	Avatar        string `json:"avatar"`
}

If i do like this the problem is coming.
both of this two function show me the validator errors..

**Comment by javierprovecho** [comment]
@thinkong check #355 and update gin `go get -u github.com/gin-gonic/gin`, it should work now.

**Comment by manucorporat** [comment]
@itnik you can not change a struct at runtime, it is just not possible in Go.
Workarounds:
- Validate it yourself
- Create different structs for each use case

**Comment by thinkong** [comment]
@javierprovecho hmm... updating gin didn't quite work.. I just disabled validation for now..

**Comment by itnik** [comment]
@manucorporat  yes i see,so i ask how to validate the attribute in dynamic way. in this case ,i just validate the attribute in my own way. i think the validation practicability is not strong.i hope the author can improves it

**Comment by javierprovecho** [comment]
@thinkong hey, manu ( @manucorporat ) found the error, it is related with the validation package, not gin. For now, disable validation until a fix has been pushed to validation repository.

**Comment by thinkong** [comment]
@javierprovecho OK good to know

**Comment by javierprovecho** [comment]
@thinkong https://github.com/bluesuncorp/validator/issues/106

**Comment by manucorporat** [comment]
@thinkong we are kind of disappointed with the existing validation libraries. In the meantime, we will develop our own fork of `go-validator`. https://github.com/gin-gonic/validator

**Comment by joeybloggs** [comment]
I will look at this asap, what values got assigned to MyStruct?

**Comment by manucorporat** [comment]
@joeybloggs anything. Just do a request like:
{ "C":"" } or {"C": "a"} or {"C": 2}

**Comment by joeybloggs** [comment]
@itnik @javierprovecho @manucorporat 
the issue has been fixed in release 5.10.1

sorry for the inconvenience, there are just so many scenarios to check and this one slipped through the cracks.

To answer some of the questions above, you can make validation optional on a field via the following validation `binding:"omitempty,len=0"` and the length validation will only run when there is data in the field.

@itnik for dynamic validation, it is not possible within a struct, however it is possible to do with field validation, please see https://godoc.org/gopkg.in/bluesuncorp/validator.v5#Validate.Field or https://godoc.org/gopkg.in/bluesuncorp/validator.v5#Validate.FieldWithValue ; the tag string passed in can be dynamic.

**Comment by itnik** [comment]
@joeybloggs okay.

**Comment by thinkong** [comment]
@joeybloggs ok updating gonic seems to work now (guess it updated to 5.10.1 :smile:

**Comment by thinkong** [comment]
this maybe a different issue.. but i;ll put it here anyway..

say i have something like the following
`````
type InnerStruct struct {
		D  struct{} `json:"d" binding:"required"`
		A int      `json:"ma" binding:"required"`
		B int      `json:"mi" binding:"required"`
	} 

type MyJsonName struct {
	AStruct InnerStruct `json:"inner"`
	P int    `json:"p"`
	S string `json:"s"`
}

`````

when i try to bind that to an appropriate json it says 

"Field validation for "A" failed on the "required" tag

ofcourse disabling validation will work.. so.. is this a bug or am i using it wrong?

**Comment by joeybloggs** [comment]
@itnik just aheads up in v6 & v7 of the validator package it is now possible to do conditional validation using one of the two following functions https://godoc.org/gopkg.in/bluesuncorp/validator.v7#Validate.StructPartial
https://godoc.org/gopkg.in/bluesuncorp/validator.v7#Validate.StructExcept
