### ISSUE TITLE
add option to UseNumber() in gin.Context.BindJSON()

### ISSUE THREAD

**Issue by oryband** [gin-gonic/gin#368]
When receiving a json object with number values and calling `context.BindJSON()` (or `context.Bind()`), the numbers will be unmarshalled to `float64` values. If needed, this can be switched to unmarshalling into `int` by using `json.Decoder.UseNumber()`. However, `BindJSON()` doesn't give this control. This should be added somehow:
- maybe a global switch, though this doesn't give per-request control.
- maybe an additional parameter or `...` parameter
- any other idea?

**Comment by oryband** [comment]
@bredov

**Comment by cch123** [comment]
Is there any plan on this issue?
I've met the same problem...and have to deal with it by myself
