### ISSUE TITLE
Performance of for loop and printing it's result in template

### ISSUE THREAD

**Issue by vadimyer** [gin-gonic/gin#370]
I'm new to Go and gin-gonic (so far, not even a programmer) so excuse my ignorance if this is a simple question and I make something wrong.

I've created a slice, filled it through for loop and pushed the slice to template:
```go
a := make([]int, 1000)
for i := 0; i < 1000; i++ {
        a[i] = i
}

c.HTML(http.StatusOK, "index.tmpl", gin.H{
        "a": a,
})
```

index.tmpl:
```{{ range .a }} {{ . }} {{ end }}```

I'm comparing performance with php. I used to test my php scripts with loader.io, pushing 5k/s of concurrent connections for 1 minute. In php, the for loop is almost the same thing, I create an array, make a loop, push each iteration into it, and then pass the array to template, where I just foreach the array and receive the same result.

But performance in case of php is, well, better. I get more successful responses (over 25-30k) for a 1 min period, while my gin/go app is breaking after 1000-1500 successful responses.

Notes: I'm using the same configuration of PCs and other software, nginx as front-end server.

**Comment by manucorporat** [comment]
@vadimyer if you use FasCGI, then it is probably not the same configuration.
if your server multi-core?

1. If Gin is running in debug mode. I will reload from disk and parse the template from scratch for everysingle request.
2. Have you changed runtime.GOMAXPROCS()? by default Go runtime will only use a single CPU thread, since you performance test is highly concurrent and the 
3. Make sure the Go program have enough file descriptors to handle 5k concurrent open sockets. Raise the ulimit (use a conservative value). Probably 25.000
4. A simple PHP code using HHVM can run very very fast.

Add this code before initializing the gin router:

```go
	runtime.GOMAXPROCS(runtime.NumCPU())
	gin.SetMode(gin.ReleaseMode)
```

**Comment by vadimyer** [comment]
@manucorporat both boxes are fully similar 1 core test boxes with same configuration of sysctl.conf, and nginx. Things like somaxconn and file descriptors, and many many others are already tuned in nginx and kernel.
Gin is running in release mode, it gives 250k successful responses (out of 300k possible) for hello world (passing the variable into html template). For comparison, php's hello world gives only around 130k, also, I use standard PHP56, not even PHP7, not to mention HHVM.
Since I have only 1 core available, tuning GOMAXPROCS won't help?

**Comment by manucorporat** [comment]
it looks like it is a `*template.Template` performance issue:
Understand that `template.Template` was probably not created with the idea of passing thousands of variables.

Probably the fastest way to render 1000 numbers is not using a template.Template. but instead writing directly to `c.Writer`.

Your performance test does not really measure the performance of Go or Gin, it is a stress test for `html/template`.

This is probably the fastest way to write 1000 numbers:
```go
	var buff bytes.Buffer
	for i := 0; i < 1000; i++ {
		fmt.Fprint(&buff, "%d ", i)
	}
	c.Header("Content-Type", "text/html")
	buff.WriteTo(c.Writer)
```

**Comment by vadimyer** [comment]
@manucorporat thanks a lot, this example helps. I understand that this is not a go/gin related issue.

But what if I really need to pass say 100 items to the template (this is rather common) and not suffer real bad? Not plain numbers, but like 2D arrays with lots of fields. From what point should I go to understand this better?

P.S. The result with this example is around 85k.

**Comment by manucorporat** [comment]
@vadimyer 100 items are not 1000. I think this is important. The requirements in software are really important. Engineers choose different algorithms, and data structures depending of the kind and size of data.

So 100 items is probably ok. Anyway, it is still a expensive operation that blocks the current thread.
I have seen a 4x performance improvements when running `GOMAXPROCS=8`.

Also, the standard library, compiler and GC are improving very fast in Go, so expect that the raw performance will be improved through the years. Go is still very young.

My advice: do not worry to much about performance until it becomes a real bottleneck.
