### ISSUE TITLE
Query: Prevent client from using insecureskipverify flag

### ISSUE THREAD

**Issue by SamarSidharth** [gin-gonic/gin#3704]
## Description

How can we prevent client from using the insecureskipverify flag.

**Comment by kaylee595** [comment]
In traditional one-way authentication, only the server needs to present a valid certificate, and the client just verifies the server's certificate. Did you mean two-way authentication?
You can try the following code, I haven't tested it:
```golang
	engine := gin.Default()
	engine.GET("ping", func(c *gin.Context) {
		c.String(http.StatusOK, "pong")
	})
	serverCert, err := tls.LoadX509KeyPair("server.crt", "server.key")
	if err != nil {
		panic(err)
	}
	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{serverCert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
	}
	server := &http.Server{
		Addr:      ":443",
		Handler:   engine,
		TLSConfig: tlsConfig,
	}
	gkayleeo.Must_(server.ListenAndServeTLS("server.crt", "server.key"))
```

**Comment by kaylee595** [comment]
The server cannot directly control whether the client uses the insecureskipverify flag, as this is a client configuration option. This flag is used to skip the verification of the server certificate when the client initiates an HTTP request. The server can only force the client to provide a valid certificate in the server configuration, but cannot intervene in the specific behavior of the client.
In traditional one-way authentication, only the server needs to present a valid certificate, and the client just verifies the server's certificate. Did you mean two-way authentication? You can try the following code, I haven't tested it, The key point is tls.RequireAndVerifyClientCert:
```golang
	engine := gin.Default()
	engine.GET("ping", func(c *gin.Context) {
		c.String(http.StatusOK, "pong")
	})
	serverCert, err := tls.LoadX509KeyPair("server.crt", "server.key")
	if err != nil {
		panic(err)
	}
	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{serverCert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
	}
	server := &http.Server{
		Addr:      ":443",
		Handler:   engine,
		TLSConfig: tlsConfig,
	}
	gkayleeo.Must_(server.ListenAndServeTLS("server.crt", "server.key"))
```

**Comment by SamarSidharth** [comment]
Thank a lot @kaylee595 for the clarification. This really helped
