### ISSUE TITLE
Appending gin.H

### ISSUE THREAD

**Issue by ClanStyles** [gin-gonic/gin#373]
Is there an easy way to use middleware to append to gin.H for example during auth, if you'd wantto append IsAuthed as a flag every call and then User object.

**Comment by manucorporat** [comment]
@ClanStyles this is an example of how the an simple auth middleware works:
https://github.com/gin-gonic/gin/blob/master/auth.go#L46-L58

it uses `c.Abort()` when the user is not authenticated and c.Set() to pass the User object.

**Comment by ClanStyles** [comment]
Right, then on return You'd still have to create a gin.H{ "UserKey": c.MustGet(gin.AuthUserKey) } 

I want to avoid doing this in 15 places. I'm thinking of passing the same gin.H as a param around but I'm finding I need this for title, auth, user object etc.. 

I'm just wondering if there's another way

**Comment by manucorporat** [comment]
@ClanStyles I don't understand.
what do you mean with "on return You'd still have to create a gin.H"?

**Comment by leedstyh** [comment]
Your can use `c.Keys` directly:

In your middlewares, you `c.Set(k, v)`, and in your final handler pass the `c.Keys` to your template.

Of course, you DON'T use `c.Keys` in `c.JSON()`, cause that will expose every filed in your `c.Keys`.

**Comment by manucorporat** [comment]
@leedstyh that was clever!

**Comment by ClanStyles** [comment]
I apologize for my unstructured question.

@leedstyh yeah this is what I was looking for... a solution to having set title, auth info, etc.. "boiler plate" view items every view and interacting with them in the in views.
