### ISSUE TITLE
I'm getting the 

### ISSUE THREAD

**Issue by rickyManalo** [gin-gonic/gin#3735]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:9000/hello/world
Hello world
```

## Actual result

```
$ curl -i http://localhost:9000/hello/world
<YOUR RESULT>
```

## Environment

- go version:
- gin version (or commit ref):
- operating system:

**Comment by VarusHsu** [comment]
It work fine on my conputer, So any problem? @rickyManalo

**Comment by rickyManalo** [comment]
I don't know why this got posted, but just ignore it. I'll be deleting this now

**Comment by rickyManalo** [comment]
I don't seem to have permission to delete this. Whoever has permission, please delete this issue. I don't really know why this got posted. I have another post that is the real issue I was going to post
