### ISSUE TITLE
Experimental Gin Logo!

### ISSUE THREAD

**Issue by manucorporat** [gin-gonic/gin#374]
![path4201](https://cloud.githubusercontent.com/assets/127379/8634385/ff8ed456-27f6-11e5-8b14-c089e33f3ae1.png)

thanks @javierprovecho !

**Comment by manucorporat** [comment]
we are still open to new ideas and proposals!

**Comment by joeybloggs** [comment]
awesome! 

maybe make the liquid the same blue as many of the gopher images out there and yellow for the wedge?

**Comment by javierprovecho** [comment]
@joeybloggs Well that make sense according to golang images and logos but not to the original purpose of the gintonic color. I'm thinking about it.

**Comment by esantoro** [comment]
I like it.

**Comment by adred** [comment]
Not minimalistic.

**Comment by lidashuang** [comment]
:+1:

**Comment by kaelliu** [comment]
i think you should make more colors in logo:D

**Comment by jcmartins** [comment]
need colors

**Comment by javierprovecho** [comment]
![gin-logo](https://cloud.githubusercontent.com/assets/2457529/14544333/d5e3cc6a-0298-11e6-9a5d-ab9ebdcba511.jpg)

does this please you? (@jcmartins, @kaelliu @joeybloggs)

**Comment by appleboy** [comment]
👍  Good color.

**Comment by esantoro** [comment]
I liked the black and white better.

**Comment by joeybloggs** [comment]
A little lighter blue like the golang gopher https://raw.githubusercontent.com/golang-samples/gopher-vector/master/gopher-front.png like @otraore had suggested and I think it would look great

**Comment by kaelliu** [comment]
cool color!@javierprovecho

**Comment by seejohnrun** [comment]
👍  The color is cool
