### ISSUE TITLE
Required tag in boolean type works incorrectly

### ISSUE THREAD

**Issue by Yeuoly** [gin-gonic/gin#3740]
## How to reproduce

```go
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	var request struct {
		IsDefault bool `json:"is_default" binding:"required"`
	}
	g := gin.Default()
	g.POST("/", func(c *gin.Context) {
		err := c.ShouldBind(&request)
		if err != nil {
			c.JSON(400, gin.H{
				"message": err.Error(),
			})
			return
		}
		c.JSON(200, gin.H{
			"message": "ok",
		})
	})
	g.Run(":9000")
}


```

## Expectations

```
$ curl -H "Content-Type: application/json" -X POST --data '{"is_default":false}' http://localhost:9000
{"message":"Key: 'IsDefault' Error:Field validation for 'IsDefault' failed on the 'required' tag"}
```

## Actual result
actually, it's excepted to be 'ok', bug validator return an error, the required tag should only check if form has 'is_default' but not check if it's false

## Environment

- go version: 1.20.1
- gin version (or commit ref):github.com/gin-gonic/gin v1.9.1
- operating system: MacOS

**Comment by Yeuoly** [comment]
I am clear that remove required tag would fix it, but in my view, it's a bug

**Comment by zanmato** [comment]
You can use `*bool` if you want to force your users to post `is_default`

**Comment by Yeuoly** [comment]
yes it's a way to solve this problem, but as a developer who are new into gin, It's confusing

**Comment by zanmato** [comment]
It's because of `required` comparing with the types' empty value, and the empty value for a `bool` is `false`. You'd have the same issue if `is_default` was an `int` and you passed `0`, because `0` is the empty value of an `int`.

**Comment by Yeuoly** [comment]
thanks for your explanation! looks like it's a problem related to a more fundamental reason. can we just make it less confusing? maybe I can provide a PR to solve this.

**Comment by Yeuoly** [comment]
Thanks! It’s helpful!
