### ISSUE TITLE
c.ClientIP()可被 x-forwarded-for请求头伪造

### ISSUE THREAD

**Issue by DokiDoki1103** [gin-gonic/gin#3767]
<img width="1020" alt="图片" src="https://github.com/gin-gonic/gin/assets/62740231/6fd92f86-40bf-4460-b683-640c6d6c459a">
<img width="917" alt="图片" src="https://github.com/gin-gonic/gin/assets/62740231/800a04c0-ba23-40c6-8033-6be4ec88ba0a">

如果用户自己指定了 x-forwarded-for 则 c.ClientIP() 获取的是被伪造的ip

**Comment by gasaimaple** [comment]
0.0.0.0 is a trusted proxy, thus the header you set is trusted.

**Comment by DokiDoki1103** [comment]
不对，我想要获取用户的真实IP，但是client IP 会被用户伪造

**Comment by gasaimaple** [comment]
It behaves as expected. If you are looking for a way to ignore header passed by trusted proxy, use RemoteIP() instead.

**Comment by DokiDoki1103** [comment]
ok thanks
