### ISSUE TITLE
middleware ordering

### ISSUE THREAD

**Issue by clanstyles** [gin-gonic/gin#378]
I want to order my middleware so that at the end of every request, the final act is to save the session.

Example: 

```
router.Use(MongoDB(session))
router.Use(SessionSave())

func SessionSave() gin.HandlerFunc {
    return func(c *gin.Context) {
        defer func() {
            if err := sessions.Default(c).Save(); err != nil {
                log.Println("failed to save session", err)
            }
        }()
        c.Next()
    }
}
```

The problem is that session save never happens. My thought is that the next() happens, but everything has rendered by that point. If I do the save before the Next() the rest of the middleware doesn't happen like AuthRequired() during my routes that are auth only.

**Comment by davisford** [comment]
You figure this out?  Is there a way to order middleware so it runs after the main handler?

**Comment by nazwa** [comment]
```go

func SessionSave() gin.HandlerFunc {
    return func(c *gin.Context) {

// Call next to jump into the next handler
        c.Next()

// Then process the response
            if err := sessions.Default(c).Save(); err != nil {
                log.Println("failed to save session", err)
            }
    }
}

```

**Comment by thinkerou** [comment]
As nazwa pointed, you not use `defer()`. closing. thanks!
