### ISSUE TITLE
Some open web applications to study?

### ISSUE THREAD

**Issue by esantoro** [gin-gonic/gin#380]
Hi!

I think it would be a nice improvement to the documentation to maintain a list of open source projects using the gin framework, so that people learning gin can study real-world examples.

**Comment by mark-rushakoff** [comment]
You can use godoc.org's [list of importers for the gin package](https://godoc.org/github.com/gin-gonic/gin?importers) to discover other open source repositories using gin. The downside is that there isn't filtering or sorting to know which consumer is "best" (or even good) to look at.

**Comment by appleboy** [comment]
@javierprovecho I create example section to record project list using the gin framework. https://github.com/gin-gonic/gin/pull/588
