### ISSUE TITLE
api docs inaccessible

### ISSUE THREAD

**Issue by zestze** [gin-gonic/gin#3804]
## Description

the documentation server for gin-gonic.com seems to have an expired SSL cert:

![image](https://github.com/gin-gonic/gin/assets/14320702/a5ca049d-9cc3-4024-b739-67cb750e79ea)

## How to reproduce

go to [gin-gonic.com](https://www.gin-gonic.com)

## Expectations

api documentation would be accessible in the browser via gin-gonic.com

## Actual result

docs are not accessible at gin-gonic.com

**Comment by novrian** [comment]
same here

**Comment by twogozi** [comment]
me too

**Comment by maniSHarma7575** [comment]
same here

**Comment by pckrishnadas88** [comment]
Same issue still not resolved.
![Uploading Screenshot 2023-12-19 at 8.18.48 AM.png…]()

**Comment by J-tt** [comment]
For those looking for a workaround, you can use the Wayback Machine to access an older version of the docs:

https://web.archive.org/web/20230000000000*/https://gin-gonic.com/docs/examples/param-in-path/

**Comment by J-tt** [comment]
I couldn't get it working 100% but I've thrown up a temporary version of the docs here: https://gin-docs.jett.dev/docs/

**Comment by TranceDevCode** [comment]
i have the same problem too

**Comment by FarmerChillax** [comment]
same here

**Comment by Noah-mm-x** [comment]
same here

**Comment by Shawn-Cui** [comment]
haven't solved yet

**Comment by feiquan666** [comment]
Is this framework not maintained by anyone else

**Comment by Wiblz** [comment]
ridiculous

**Comment by novrian** [comment]
> Thanks for reporting this, it should be fixed now.
> 
> I had Cloudflare SSL configuration set to "strict", asuming that GitHub Pages would serve a valid certificate, but for some reason it is not doing it, so I switched it back to "full".
> 
> ![dash cloudflare com_26abb5c2fb67a7989ddaa1c74f9a21f9_gin-gonic com_ssl-tls](https://github.com/gin-gonic/gin/assets/2457529/92635983-0bb2-4631-bcc0-672949edc360)

Thanks @javierprovecho
