### ISSUE TITLE
Gin recognizes some URL characters but not others (http://localhost:3459/What%3F.html but not http://localhost:3459/What?.html)

### ISSUE THREAD

**Issue by 01AutoMonkey** [gin-gonic/gin#384]
My markdown converter converts `[What?]()` to the link `http://localhost:3459/What?.html` or `/What?.html` but when I go there I get `404 page not found`, but if I manually change the `?` character to `%3F` everything works.

My relevant gin code:

```go
func serve(dir string) {
  //gin.SetMode(gin.ReleaseMode)
  r := gin.Default()
  r.Static("/", dir+"/compiled")
  r.Run(":3459")
}
```

Is it possible to make gin recognize my URLs even if they have `?` in them? Could this perhaps have  something to do with my use of r.Static?

**Comment by itsjamie** [comment]
This is because the ? is a reserved character for notating the start of a query string.

Rather than getting Gin to recognize the URL, I imagine the easier route would be encoding the URL from the markdown converter.

**Comment by 01AutoMonkey** [comment]
Escaping URLs in the markdown converter did the job.
