### ISSUE TITLE
500 errors when making HEAD requests

### ISSUE THREAD

**Issue by tshr** [gin-gonic/gin#385]
Hi,

Since upgrading to v1.0rc1 we've been seeing intermittent 500s being returned by gin coupled with the error "Redirecting to HTTPS". It seems like the call to c.Writer.Written() on line 171 of secure.go is returning false even though http.Redirect(w, r, url.String(), status) is being called from within the process function. We did not see this error prior to upgrading from 0.x. Here is how we are configuring our secure handler:

```
securer := secure.Secure(secure.Options{
    SSLRedirect:          strings.ToLower(os.Getenv("FORCE_SSL")) == "true",
    SSLProxyHeaders:      map[string]string{"X-Forwarded-Proto": "https"},
    STSSeconds:           315360000,
    STSIncludeSubdomains: true,
    FrameDeny:            true,
    ContentTypeNosniff:   true,
    BrowserXssFilter:     true,
})
```

Is there something we need to update to ensure these types or requests return only 301s and redirect correctly? Thanks!

**Comment by juddernaught** [comment]
Hi, I've been having this issue as well and it looks like this issue hasn't been responded to, so thought I'd comment. Thanks!

**Comment by tshr** [comment]
Hi a little more info on this: We are able to replicate the 500 error when HEAD requests are made to any http endpoint in our app. They should be returning 301s.  HEAD requests to https endpoints result in 404s (while GETs return 200s). Is some extra configuration needed to make HEAD requests behave as expected?

**Comment by javierprovecho** [comment]
there is no additional configuration for this to work.




this must be a bug. I will take a look at this issue is the most critical from all.




sorry for the delay in answering.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by tshr** [comment]
Great thank you for investigating. Please let me know if you'd like any more information from me.

**Comment by javierprovecho** [comment]
@tshr i'm still looking at it, i'm debugging the new router. sorry for delay

**Comment by tshr** [comment]
Thanks @javierprovecho !

**Comment by BrodrickChilds** [comment]
@javierprovecho - any traction on this front?  Still seeing the same error over here.

**Comment by javierprovecho** [comment]
we have just made a corrected version in the airport. when we take land, we will push it to develop.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by javierprovecho** [comment]
finally we are not pushing it there, instead we'll refractor contrib into separate repositories under a new organization called git-contrib. we'll keep you updated.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by javierprovecho** [comment]
hey @tshr @brodickchilds



checkout https://github.com/gin-contrib/secure


it is not finished, and we need to check tests, even they pass.




check examples folder too!



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by tshr** [comment]
Great, thanks for continuing to work on this. Please let me know when this will be ready to test. The HEAD issue has been our only complaint with gin otherwise we've been really enjoying the framework!
