### ISSUE TITLE
I want to use shouldmindbodywith first and then use formafile, but it doesn't work right now

### ISSUE THREAD

**Issue by AsadYao** [gin-gonic/gin#3906]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/hello/:name", func(c *gin.Context) {
		c.String(200, "Hello %s", c.Param("name"))
	})
	g.Run(":9000")
}
```

## Expectations

```
$ curl http://localhost:9000/hello/world
Hello world
```

## Actual result

```
$ curl -i http://localhost:9000/hello/world
<YOUR RESULT>
```

## Environment

- go version:
- gin version (or commit ref):
- operating system:

**Comment by RedCrazyGhost** [comment]
Please rewrite the issue content to submit valuable information.

**Comment by RedCrazyGhost** [comment]
json and form cannot be sent in the same request because the content-type is restricted in the request header.

**Comment by AsadYao** [comment]
thank you
