### ISSUE TITLE
New release with validator.v8?

### ISSUE THREAD

**Issue by davisford** [gin-gonic/gin#393]
Any chance you can publish a new version that upgrades to v6?  

https://godoc.org/gopkg.in/bluesuncorp/validator.v6

**Comment by asdine** [comment]
+1

**Comment by manucorporat** [comment]
@davisford asdine  of course! I was disconnected for vacations.

**Comment by davisford** [comment]
The reason I'm most interested in v6 is that he cleaned up the error structure significantly and made it much simple to deal with -- I'm waiting to finish up my specific handling of validation errors in my own project until then.

**Comment by joeybloggs** [comment]
just a heads up @manucorporat & @davisford 

v7 has been released and is a drop in replacement for v6, unless custom functions have been created, hence the version bump.

v7 allow for cross struct cross field validations using tags see notes here: https://github.com/bluesuncorp/validator/releases/tag/v7

**Comment by davisford** [comment]
Looks good, thanks @joeybloggs -- @manucorporat if you want, I can try to send a PR with an upgrade to v7?

**Comment by davisford** [comment]
@manucorporat any word on this?  i haven't looked at how much work it is, but as stated earlier, i'd be happy to take a stab at it and submit a pr

**Comment by joeybloggs** [comment]
Just an fyi v8 just released https://github.com/bluesuncorp/validator/releases/tag/v8.0.1

Hopefully no more releases for a while as I've made v8 as bullet-proof as I can for the foreseeable future.

biggest new feature besides changes is allowing registering of alias validations. I.e  can tell validator the tag "iscolor" is an alias for "hexcolor|rgb|rgba|hsl|hsla"

**Comment by Dashed** [comment]
any movement on this?

**Comment by davisford** [comment]
@manucorporat are you still developing gin or have you moved on?  I only ask b/c last commit was about a month ago.  I may fork the repo so I can move forward.

**Comment by Dashed** [comment]
@davisford do you have a PR/commits for this?

**Comment by davisford** [comment]
No, I was waiting for @manucorporat but he's gone dark, so I will likely fork and upgrade and send a pr...I just don't have time to do it right now, but plan to do it in the next couple weeks.

**Comment by no1youknowz** [comment]
any movement on this, was a PR generated, does one need to be done?  Thanks

**Comment by joeybloggs** [comment]
Isn't it already done? The godep and code are using v8 as far as I can see

**Comment by no1youknowz** [comment]
Thanks for pointing that out, i just re-grabbed gin.  I see v8 instead of v5.  Sorry for the noise! :+1:
