### ISSUE TITLE
Please consider remove github.com/bytedance/sonic from dependencies

### ISSUE THREAD

**Issue by hailinzhg** [gin-gonic/gin#3932]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description
module `github.com/bytedance/sonic` is not well maintained and it's sum changes violently.
![image](https://github.com/gin-gonic/gin/assets/156624061/681bd5bf-a6f0-4a96-9af2-058512e2c3e4)

## Environment

- go version: v1.21.9
- gin version (or commit ref): v1.9.0
- operating system:

**Comment by hailinzhg** [comment]
https://github.com/bytedance/sonic/issues/622

**Comment by AsterDY** [comment]
Sorry for disturbing you. We pushed a new version (sonic [v1.11.6](https://github.com/bytedance/sonic/releases/tag/v1.11.6) ) to resolve this problem

**Comment by hailinzhg** [comment]
> Sorry for disturbing you. We pushed a new version (sonic [v1.11.6](https://github.com/bytedance/sonic/releases/tag/v1.11.6) ) to resolve this problem

Thanks for your reply.

**Comment by hailinzhg** [comment]
Gin is a good framework and I'm grateful for all the contributors. But now it seems it's carrying too much dependencies that someone may not need. Wish the pluggable functions moved to separate go modules so that users can plug in when need, that will greatly help a go project's simplicity.
