### ISSUE TITLE
Warning link doesn't point to anything anymore

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [gin-gonic/gin#3938]
The following warning points to a nonexistent link:
```
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
```
## Environment

- go version: 1.22.2
- gin version (or commit ref): v1.9.1
- operating system: Linux

**Comment by snowdusk** [comment]
Readme's git logs show that
'Don't trust all proxies' was added on commit 2d3d6d2f1355f21a77f8ef6cf45a5bc531c8c935 (2021/10/24)
and was removed on commit 82e1c53cc0a3b0bdb7baab6b95d05a7ec796f7a2 (2023/01/02, messags is 'docs(readme): move more example to docs/doc.md')
So readme-don-t-trust-all-proxies is https://github.com/gin-gonic/gin/blob/master/docs/doc.md#dont-trust-all-proxies
