### ISSUE TITLE
Vulnerability in golang.org/x/net/http2 version < 0.23.0

### ISSUE THREAD

**Issue by yinonel** [gin-gonic/gin#3944]
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-6531285
This issue is caused by the usage of package golang.org/x/net/http2 in version < 0.23.0.
Vulnerability is allocation of resources without limits or throttling

- gin version (or commit ref): 1.9.1

**Comment by LuizWeitz** [comment]
Hi @yinonel, please check this PL #3920, the code update is done, but await approved!

**Comment by codespearhead** [comment]
@yinonel Can you close this now that #3950 was merged?

**Comment by appleboy** [comment]
Fixed in v1.10.0 version.
