### ISSUE TITLE
I need a public api like  `combineHandlers`. 

### ISSUE THREAD

**Issue by dyxushuai** [gin-gonic/gin#395]
I have a `Group` instance with some common handlers. Then I define some route rule with this `Group`.
If I need more common handlers with this `Group` after these...

e.g.

``` go
r := gin.New()
g := r.Group("/path", handler1, handler2)
g.POST("/to", handler)
g.GET("/method", handler)
g.xxx(handler3)
```

`xxx` is what I want.

**Comment by JohnSmithX** [comment]
I think I can use `next()`  solve the problem.

**Comment by thinkerou** [comment]
yes, `next()`.
