### ISSUE TITLE
DELETE request and body data

### ISSUE THREAD

**Issue by theduke** [gin-gonic/gin#396]
In a DELETE request, 

``` go
token := c.Request.FormValue("auth_token")
```

Results in an empty string, event though auth_token is definitely in the Body.
Is it possible that the body is not properly parsed for a delete request?

**Comment by dalu** [comment]
http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request
body in DELETE is supposed to be ignored

**Comment by WeiChieh-Chen** [comment]
why closed? I encounter the same problem

**Comment by Xieyuschen** [comment]
I encountered the same question, I guess that needs a special content-type or get from context by other ways:(
