### ISSUE TITLE
multiple c.Query in GET

### ISSUE THREAD

**Issue by thellimist** [gin-gonic/gin#397]
is there a way to get all the parameters with the same name from a request like `http://localhost:8080/test?id=5&id=10`. 

`c.Query("id")` only gets the first one.

**Comment by leedstyh** [comment]
So you need go build-in lib `http://golang.org/pkg/net/url/#Values`

In your case:

`ids, ok := c.Request.Form["id"]`

**Comment by thellimist** [comment]
I'm getting as with `GET` method. Request `http://localhost:8080/test?id=5&id=10`, `ids, ok := c.Request.Form["id"]` returned `ok: false, ids: []`.

**Comment by leedstyh** [comment]
Try calling `c.Request.ParseForm()` before `ids, ok := c.Request.Form["id"]`

**Comment by thellimist** [comment]
That was the missing part.

**Comment by shenwei356** [comment]
Thanks! This helps me.
