### ISSUE TITLE
binding issue with multipart form

### ISSUE THREAD

**Issue by TheInsideMan** [gin-gonic/gin#398]
Hello Im getting the below error. This error has only started since switching to a multipart form with file being posted. Any advice much appreciated. 

```
$ curl -X POST --form "icon=@ak2.jpg"  --cookie 'session=91b5sdfdsfdsm' "http://127.0.0.1:8080/v1.0/apps" --form data='{"json_name":"test json name","title":"Test"}'
```

```
Panic recovery -> reflect: NumField of non-struct type
/usr/local/go/src/runtime/panic.go:387 (0x40145d8)
    gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/reflect/type.go:657 (0x416ffca)
    (*rtype).NumField: panic("reflect: NumField of non-struct type")
/usr/local/go/src/src/github.com/gin-gonic/gin/binding/form_mapping.go:16 (0x4162831)
    mapForm: for i := 0; i < typ.NumField(); i++ {
/usr/local/go/src/src/github.com/gin-gonic/gin/binding/form.go:20 (0x4162693)
    formBinding.Bind: if err := mapForm(obj, req.Form); err != nil {
<autogenerated>:2 (0x4163e77)
/usr/local/go/src/src/github.com/gin-gonic/gin/context.go:244 (0x40851e2)
    (*Context).BindWith: if err := b.Bind(c.Request, obj); err != nil {
/usr/local/go/src/src/gin-api/controllers/apps.go:1119 (0x405fe68)
    CreateApps: c.BindWith(&json_tmp, binding.Form)
```

```
func CreateApps(c *gin.Context) {
    var json_tmp map[string]interface{}
    c.Bind(&json_tmp)
    ...
}
```

**Comment by z0rr0** [comment]
Hello,
I have a same problem but for simple HTTP form, it occurs always.

```go
type Form struct {
    Token   string `form:"token" binding:"required"`
    Content string `form:"content" binding:"required"`
    Info    string `form:"info"`
    Wait    uint   `form:"wait"`
}

// handler code
form := &Form{}
if c.Bind(&form) != nil {
    // handling
}
```

```
/go/src/runtime/panic.go:387 (0x413ec8)
        gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/go/src/reflect/type.go:657 (0x4e31da)
        (*rtype).NumField: panic("reflect: NumField of non-struct type")
/project/src/github.com/gin-gonic/gin/binding/form_mapping.go:16 (0x5ba0f1)
        mapForm: for i := 0; i < typ.NumField(); i++ {
/project/src/github.com/gin-gonic/gin/binding/form.go:22 (0x5b9f53)
        formBinding.Bind: if err := mapForm(obj, req.Form); err != nil {
<autogenerated>:2 (0x5bb7a7)
/project/src/github.com/gin-gonic/gin/context.go:270 (0x4badc2)
        (*Context).BindWith: if err := b.Bind(c.Request, obj); err != nil {
/project/src/github.com/gin-gonic/gin/context.go:259 (0x4bac7e)
        (*Context).Bind: return c.BindWith(obj, b)
/project/src/myproject/utils/utils.go:159 (0x4b734f)
        HandlerForward: if c.Bind(&form) != nil {
```

**Comment by mr-linch** [comment]
@z0rr0 you pass pointer to pointer, but need just pointer:
```golang
type Form struct {
    Token   string `form:"token" binding:"required"`
    Content string `form:"content" binding:"required"`
    Info    string `form:"info"`
    Wait    uint   `form:"wait"`
}

// handler code
form := &Form{}
if c.Bind(form) != nil {
    // handling
}
```

**Comment by z0rr0** [comment]
@mr-linch oh, thanks :smiley:

**Comment by littletwolee** [comment]
Hi gays ,I have a error like @TheInsideMan 
var user map[string]interface{}
err = c.Bind(user)

if I use map the error is:
// reflect: call of reflect.Value.Elem on map Value
and if use point ,the error is 
//reflect: NumField of non-struct type
any body can help me? Thx a lot

**Comment by easonlin404** [comment]
@littletwolee could you post your sample code to reproduce issue?

**Comment by littletwolee** [comment]
@easonlin404 
like these
var (
		//idstr, name, pwd string
		err  error
		id   int
		user map[string]interface{}
	)
	err = c.Bind(&user)
	err = modules.Test.UpdateUser(id, user)
	if err != nil {
		goto ERR
	}
the error is "reflect: NumField of non-struct type"

if modify the code from "c.Bind(&user)" to "c.Bind(user)"
the error is "reflect: call of reflect.Value.Elem on map Value"

my struct is 
type User struct {
	ID   int    `json:"id" form:"id"`
	Name string `json:"name" form:"name" binding:"required"`
	Pwd  string `json:"pwd" form:"pwd" binding:"required"`
}

can you guys help me? Thx a lot

**Comment by easonlin404** [comment]
@littletwolee gin are assuming the binding is using structs only, so you have to use `struct` instead of `map` just like:

```go
package main

import (
	"github.com/gin-gonic/gin"
)

type User struct {
	ID   int    `json:"id" form:"id"`
	Name string `json:"name" form:"name" binding:"required"`
	Pwd  string `json:"pwd" form:"pwd" binding:"required"`
}

var (
	err error
	id  int
	// user map[string]interface{} //you can't binding with map
)

func main() {
	r := gin.New()

	r.GET("/", func(c *gin.Context) {
		var user User
		err = c.Bind(&user)

		if err != nil {
			//...omitted
		}

		//...omitted
	})

	r.Run()
}

```

**Comment by littletwolee** [comment]
thx @easonlin404, But I think this is a missing func. I need to have more rules with our fontend. It's very crazy.T.T

**Comment by easonlin404** [comment]
@littletwolee What's your scenario? You want to dynamically building params?

**Comment by littletwolee** [comment]
@easonlin404 Yep.I want get params is simply. Like map. I think request or form params were kv pairs. So, use map or struct were all good.

**Comment by littletwolee** [comment]
@easonlin404 Mumm.I have a scenario.
my struct like this 
type user struct {
      Name string
      Pwd   string 
}
Ok, Now I get a Http PUT request, It want to modify Name only.And I usr org package to control it.If I give orm a struct, it will change all fields. The param Pwd will be change from "xxx" to "".But I only to change Name.
So I want have a map[string]interface{} to complete it.
Like this. I'm not make sure you was clearly. My english is not good, thx a lot !!!

**Comment by thinkerou** [comment]
@TheInsideMan @littletwolee If you use form post map, please see #1387 , thanks a lot!

**Comment by thinkerou** [comment]
#1749 merged!
