### ISSUE TITLE
Suggestion: Better error support

### ISSUE THREAD

**Issue by dalu** [gin-gonic/gin#399]
So far we can call c.Error(error) and add a function at the end of the request/response cycle to check if len(c.Errors)>0.

However sometimes you have success messages, sometimes warning messages or error messages.

I'd like to return something like
```
[
{"type":"success","message":"Your registration was successful"},
{"type":"warning","message":"You have not provided your IBAN. You can add this later under account preferences"}
]
```

Something like
c.Msgs.Push("type","message")
c.Msgs.JSON(200)

Of course you could create your own package to do this. But it would be more elegant if the context would have built in support for something like this.

Right now I have
```
func (h *AccountHandler) handleErrors(c *gin.Context) {
	if len(c.Errors) > 0 {
		o := new(Output)
		for _, v := range c.Errors {
			o.Messages = append(o.Messages, Message{Type: "error", Text: v.Error()})
		}
		c.JSON(500, o)
	}
}
```
which is called at the end of every handler or rather
```
func (h *AccountHandler) DefaultHandler(c *gin.Context) {
	switch c.Param("action") {
	case "register":
		h.register(c)
	case "login":
	case "forgot":
	case "reset":
	case "logout":
	default:
		http.NotFound(c.Writer, c.Request)
	}
	h.handleErrors(c)
}
```

**Comment by dalu** [comment]
On second thought, c.Set c.Get can be used for this.

**Comment by nazwa** [comment]
Out of interest, why do you use action parameter + switch to determine your handlers instead of registering them individually?

As to your error handling problem, if you have to return multiple errors and warnings in a single request, I would make a new type for them and output that instead of trying to differentiate them using the c.Error. I feel like c.Error should be used for actual errors rather than communication with users.

Something along the lines of:

```go
type ResponseType struct {
	Errors   []string `json:",omitempty"`
	Warnings []string `json:",omitempty"`
}

func (r *ResponseType) AddWarning(msg string) {
	r.Warnings = append(r.Warnings, msg)
}
```

**Comment by dalu** [comment]
I can pass options to the handler and I can inject that handler into other handler's constructors.
And should I want it I can mount those handlers on different routes, useful for e.g. a file upload handler that has an option to handle image files only and another handler to handle videos.
I'd like to keep one structure for all handlers and every handler should have options and should be injectable into other handlers.
So for instance every handler needs the AccountHandler because every resource is bound to the account,be it profile, file, blog or whatever.
In AccountHandler I already have the mgo session cloned and all I need to do from e.g. ProfileHandler is h.AccountHandler.AccountId(c) and it would parse the jwt, do a db query and return the account id.
With mgo you need to Clone() the main connection and Copy() and defer Close() and do your querying. So this way everything is abstracted and managed by the mgo driver.

And let's say I need net/http compatibility I can easily change c.Writer and c.Request to w and r.
It's a big project I'm working on and I want to follow 1 scheme for everything. Imagine 300 individual routes all with single handlers. A mess. And I want re-usable packages. Or at least semi-resuable ones, since Go is so literal about everything.

I'm just using gin for router.Group and so I won't have to use gorilla/context since this has this feature already.

Yeah I was thinking about something like this. Add it to the context with Set and Get it at the end. Would be better if something like this was built in, but Set/Get works too.

**Comment by dalu** [comment]
btw should I clone the context before passing it around?

**Comment by nazwa** [comment]
Only if you are passing it into a new goroutine :)
