### ISSUE TITLE
gin/render/text/WriteString - parameter interface issue

### ISSUE THREAD

**Issue by bolshoy** [gin-gonic/gin#400]
Here's the function signature:

``` go
WriteString(w http.ResponseWriter, format string, data []interface{})
```

Now let's assume that we are replacing the gin context writer with our custom one, like in gzip middleware:

``` go
writer := c.Writer
context.Writer = &gzipWriter{c.Writer, gz}
```

If we now call context.Write it will use our custom writer as needed, but context.String will not - because it calls WriteString, which uses a generic interface http.ResponseWriter and not  gin.ResponseWriter. I think the signature should be 

``` go
WriteString(w gin.ResponseWriter, format string, data []interface{})
```

Another option is for gzipWriter to implement WriteString interface, which is not intuitive (and probably needs also Size() and Written()...)

**Comment by gonboy** [comment]
Yes. I found gzip is invalid.
```go
package main

import (
	"fmt"
	"github.com/gin-gonic/contrib/gzip"
	"github.com/gin-gonic/gin"
)
func main() {
	r := gin.Default()
	r.Use(gzip.Gzip(gzip.BestCompression))
	r.GET("/ping", func(c *gin.Context) {
		fmt.Println("return string")
		c.String(200, "welcome to china, baby")
	})
	r.Run(":80")
}
```
**GOPATH\src\github.com\gin-gonic\contrib\gzip\gzip.go**
```go
func Gzip(level int) gin.HandlerFunc {
	return func(c *gin.Context) {

		if !shouldCompress(c.Request) {
			return
		}

		gz, err := gzip.NewWriterLevel(c.Writer, level)
		if err != nil {
			return
		}

		c.Header("Content-Encoding", "gzip")
		c.Header("Vary", "Accept-Encoding")
		c.Writer = &gzipWriter{c.Writer, gz}

		defer func() {
			c.Header("Content-Length", "0")
			gz.Close()
		}()
		c.Next()
	}
}
```

**questions:**
1. if set 
`c.Header("xxxContent-Encoding", "aaa")`
`c.Header("123Content-Encoding", "aaa")`
you can track the before Http header .
but if set
`c.Header("Content-Encodingxxxx", "aaa")`
couldn't track it
2.  couldn't find any zip information . except: **`Vary: Accept-Encoding`**
```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
Date: Thu, 19 Jan 2017 07:36:37 GMT
Content-Length: 22
welcome to china, baby
```

**Comment by thinkerou** [comment]
Please see @easonlin404 comment https://github.com/gin-gonic/gin/issues/792#issuecomment-311292463
