### ISSUE TITLE
Print Request Body empty

### ISSUE THREAD

**Issue by tihuinc** [gin-gonic/gin#401]
I'm new to Go and Gin, and am having trouble printing out the full request body.

I want to be able to read the request body from third party POST, but I'm getting empty request body.
```
curl -u dumbuser:dumbuserpassword -H "Content-Type: application/json" -X POST --data '{"events": "3"}' http://localhost:8080/events
```

My entire code is as follow. Any point is appreciated.

```
package main

import (
  "net/http"
  "fmt"
  "github.com/gin-gonic/gin"
)

func main() {
  router := gin.Default()
  authorized := router.Group("/", gin.BasicAuth(gin.Accounts{
     "dumbuser": "dumbuserpassword",
  }))
  authorized.POST("/events", events)
  router.Run(":8080")
}

func events(c *gin.Context) {
  fmt.Printf("%s", c.Request.Body)
  c.JSON(http.StatusOK, c)
}
```

**Comment by ironiridis** [comment]
Probably because `c.Request.Body` [is an io.ReadCloser](http://godoc.org/net/http#Request), so you need to read from it, not simply print the string value of it.

**Comment by tihuinc** [comment]
Thanks, ironiridis, I figured it out with help from Stackoverflow too.
Thread here: http://stackoverflow.com/questions/31911579/gin-golang-empty-req-body.
