### ISSUE TITLE
Different 404 handler for different group

### ISSUE THREAD

**Issue by jerome-laforge** [gin-gonic/gin#4045]
## Description

I have an api group, and I want it to have a different 404 handler than the main group.
I want to do something like this:

```go
r.Group("/a").NoRoute(func(ctx *gin.Context) {
	// manage no route for /a
})
r.Group("/b").NoRoute(func(ctx *gin.Context) {
	// manage no route for /b
})
```
But it is not possible with current `RouterGroup`

I don't want use workaround explained here #2999, since I want to compose handler func with `ctx.Next()`, `ctx.Abort()` and other complex things.

**Comment by JimChenWYU** [comment]
Base one the current structure of gin, I dont think `gin` can solve your problem.

> Just group by prefix

![image](https://github.com/user-attachments/assets/8719248f-08dd-4c6b-951f-27680dd49830)

> All routes will be registered to engine.Handlers

![image](https://github.com/user-attachments/assets/3ea95f7b-202e-4e30-a60f-b45424c6e503)
![image](https://github.com/user-attachments/assets/a7cc68b8-3772-486f-bae4-ae99f688b47f)

> So only provides the global `404` handler

![image](https://github.com/user-attachments/assets/3738f0fd-cfb3-43ea-9bf9-d44b16bd8fb0)

**Comment by jerome-laforge** [comment]
Thanks for this confirmation @JimChenWYU

**Comment by jerome-laforge** [comment]
I won't use gin.NoRoute(), instead of I will use this workaround:

```go
func noRoute(r *gin.Engine, basePath string, hfs ...gin.HandlerFunc) {
	r.Any(basePath+"/:path", hfs...)
}
...
noRoute(r, "/a", func(ctx *gin.Context) {
	// manage no route for /a
})
noRoute(r, "/b", func(ctx *gin.Context) {
	// manage no route for /b
})
```

Thx again @JimChenWYU for your support

**Comment by jerome-laforge** [comment]
Another workaround that is more robust but also more weird, it is use 2 gin.Engine for each group (the global mergeEngine  & the specific engineOnlyForA or engineOnlyForB)

```go
mergeEngine := gin.New()

// manage all routes + noroutes for /a/*
{
	engineOnlyForA := gin.New()
	engineOnlyForA.GET("/a/bc", func(c *gin.Context) {
		// do stuff for /a/bc
	})
	engineOnlyForA.GET("/a/de", func(c *gin.Context) {
		// do stuff for /a/de
	})
	engineOnlyForA.NoRoute(func(c *gin.Context) {
		// no route for /a/*
	})

	mergeEngine.Any("/a/*path", gin.WrapH(engineOnlyForA))
}

// manage all routes + noroutes for /b/* 
{
	engineOnlyForB := gin.New()
	engineOnlyForB.GET("/b/cd", func(c *gin.Context) {
		// do stuff for /b/cd
	})
	engineOnlyForB.GET("/b/ef", func(c *gin.Context) {
		// do stuff for /b/ef
	})
	engineOnlyForB.NoRoute(func(c *gin.Context) {
		// no route for /b/*
	})

	mergeEngine.Any("/b/*path", gin.WrapH(engineOnlyForB))
}
```
