### ISSUE TITLE
Engine.Run() reads env: PORT

### ISSUE THREAD

**Issue by manucorporat** [gin-gonic/gin#405]
I am going to add a new behaviour to `Engine.Run()`.
- Back-compatible: it will continue working as expected when an address is provided: `router.Run(":3000")`
- NEW: no parameter: `router.Run()`
  Under this API, gin will try to read the `PORT` environment variable and use it.
  If the `PORT` variable is not defined, ":8080" would be used by default.
- Under discussion: **Support for App Engine**
  can we detect in runtime that we are running under the app engine environment?
  if so, router.Run() should use the app engine's api.

**Comment by manucorporat** [comment]
Why this? the same code will run in your desktop, ec2 instance, heroku, elastic beanstalk and app engine...

```go
r := gin.Default()
r.GET("/", indexHandler)
r.Run()
```

**Comment by se77en** [comment]
Nice change

**Comment by man2d** [comment]
Guys, the hardcoded port value is overriden by PORT environment variable.
The documentation says:
    // router.Run(":3000") for a hard coded port
So why does environment variable has bigger priority?
