### ISSUE TITLE
reopen "Gin Context implementation breaks context.Context contract #3888"

### ISSUE THREAD

**Issue by huangjilaiqin** [gin-gonic/gin#4074]
this commit did not fix problem,just replace 0 to ContextRequestKey
[#3897](https://github.com/gin-gonic/gin/pull/3897)
![image](https://github.com/user-attachments/assets/497cc3e5-7a70-42ff-9232-0959d6fe6e51)

this code can solve this problem
![image](https://github.com/user-attachments/assets/92be54da-e9d8-4970-8bee-d56502f7db12)

**Comment by huangjilaiqin** [comment]
@FarmerChillax @appleboy check this please

**Comment by FarmerChillax** [comment]
see: https://github.com/gin-gonic/gin/issues/3993#issuecomment-2172593121

**Comment by FarmerChillax** [comment]
> this code can solve this problem

this is a break change, I would not recommend making such changes in a widely used framework.

**Comment by huangjilaiqin** [comment]
this is the root cause, ContextRequestKey==0 make otel's func SpanFromContext can not get the Span but get the c.Request
![image](https://github.com/user-attachments/assets/fde0a985-7cd2-4a62-a4de-c09136cc02cc)
![image](https://github.com/user-attachments/assets/9076888b-1a56-46aa-8d98-d019b15eda44)

**Comment by FarmerChillax** [comment]
In otel the currentSpanKey is Type of traceConrextKeyType.  In here, you can set `ContextWithFallback = true `  to solue this problem

see: https://github.com/gin-gonic/gin/issues/3993#issuecomment-2172593121

with Go Context standards:
```
The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context. Users of WithValue should define their own types for keys. To avoid allocating when assigning to an interface{}, context keys often have concrete type struct{}. Alternatively, exported context key variables' static type should be a pointer or interface.
```

ref: https://pkg.go.dev/context#WithValue

**Comment by FarmerChillax** [comment]
Minimum case:
```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/gin-gonic/gin"
	"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin"
	"go.opentelemetry.io/contrib/propagators/b3"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.4.0"
	"go.opentelemetry.io/otel/trace"
)

var applicationName string = "demo"

func main() {
	RegisterTracer(applicationName)
	app := gin.Default()
	gin.SetMode(gin.ReleaseMode)
	app.ContextWithFallback = true
	app.Use(otelgin.Middleware(applicationName))
	app.GET("/", func(ctx *gin.Context) {
		traceID, spanID, isSampled := GetTraceInfo(ctx)
		fmt.Printf("traceID: %v; spanID: %v; isSampled: %v\n", traceID, spanID, isSampled)
	})

	if err := app.Run(":8080"); err != nil {
		log.Fatalln(err)
	}
}

func GetTraceInfo(ctx context.Context) (traceID string, spanID string, isSampled bool) {
	spanCtx := trace.SpanContextFromContext(ctx)

	if spanCtx.HasTraceID() {
		traceID = spanCtx.TraceID().String()
	}
	if spanCtx.HasSpanID() {
		spanID = spanCtx.SpanID().String()
	}

	isSampled = spanCtx.IsSampled()

	return traceID, spanID, isSampled
}
func RegisterTracer(serviceName string) {
	otel.SetTextMapPropagator(b3.New(b3.WithInjectEncoding(b3.B3MultipleHeader)))

	batcher := sdktrace.NewBatchSpanProcessor(nil)

	res, err := resource.New(context.Background(),
		resource.WithFromEnv(),
		resource.WithProcess(),
		resource.WithTelemetrySDK(),
		resource.WithHost(),
		resource.WithAttributes(
			semconv.ServiceNameKey.String(serviceName),
		),
	)
	if err != nil {
		log.Fatalln(err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithResource(res),
		sdktrace.WithSpanProcessor(batcher),
		sdktrace.WithSampler(sdktrace.ParentBased(sdktrace.AlwaysSample())),
	)

	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
}
```

In shell:
```
$ go run main.go
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

traceID: 68e41a688d27fa3c9f895417414b6dc5; spanID: de7b716f74c755e8; isSampled: true
[GIN] 2024/10/15 - 09:57:34 | 200 |      67.291µs |       127.0.0.1 | GET      "/"
```

**Comment by huangjilaiqin** [comment]
yes, this really work ,thk
> In otel the currentSpanKey is Type of traceConrextKeyType. In here, you can set `ContextWithFallback = true ` to solue this problem
> 
> see: [#3993 (comment)](https://github.com/gin-gonic/gin/issues/3993#issuecomment-2172593121)
> 
> with Go Context standards:
> 
> > The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions
> > between packages using context. Users of WithValue should define their own types for keys. To avoid allocating when
> > assigning to an interface{}, context keys often have concrete type struct{}. Alternatively, exported context key variables'
> > static type should be a pointer or interface.
> 
> ref: https://pkg.go.dev/context#WithValue

**Comment by FarmerChillax** [comment]
Add example in https://github.com/gin-gonic/examples/pull/171 @appleboy
