### ISSUE TITLE
Convert pascal case to camel case or snake case when converting to JSON

### ISSUE THREAD

**Issue by faeronsayn** [gin-gonic/gin#409]
When we're outputting JSON i'd like to be able to convert my PascalCase properties on my model to camelCase for JSON. How can I do that? I want the whole API to communicate through camelCase but I want my go model properties to stay Pascal Case. Any good solution for this?

**Comment by mvader** [comment]
Using struct tags:
```go
type Foo struct {
    MyProp string `json:"my_prop"`
}
```

**Comment by faeronsayn** [comment]
that did it for me, thanks :+1:

**Comment by Azbesciak** [comment]
There is no something... Generic, like configuration? Because of the re PascalCase = public I have to put annotation for each struct to keep json convention? Guys...

**Comment by erizocosmico** [comment]
@Azbesciak no, gin uses the functionality in "encoding/json" package which does not allow such configurations. Every field you need with a different name needs to be annotated with a struct tag.
