### ISSUE TITLE
How to output an array of ids instead of an array of objects in JSON

### ISSUE THREAD

**Issue by faeronsayn** [gin-gonic/gin#413]
```go
type Group struct {
    ID          uint       `json:"id"`
    Name        string     `json:"name"`
    Description string     `json:"description"`
    Users       []User     `json:"users"`
    HashID      string     `json:"hashId"`
    CreatedAt   time.Time  `json:"createdAt"`
    UpdatedAt   time.Time  `json:"updatedAt"`
    DeletedAt   *time.Time `json:"deletedAt"`
}
```

Now I have `Users` key that is an array of User objects. But in my output JSON I just want to output the ids of the users and not all of the user objects. Any easy way of doing that?

**Comment by TheRealKira** [comment]
If your other values are zeroed out you can use `json:"myName,omitempty"`

**Comment by thellimist** [comment]
http://stackoverflow.com/questions/31467326/golang-modify-json-without-struct

check this post there are some options you can use
