### ISSUE TITLE
LoadHTMLGlob should ignore invalid files

### ISSUE THREAD

**Issue by atavism** [gin-gonic/gin#417]
I use vim, and whenever I'm editing an HTML template, a swap file's created in the same directory which always causes Gin to crash when I do a refresh. I naturally could disable the creation of these files, or move them to another directory, but wouldn't it make more sense for Gin to ignore non *.html and *.tmpl files instead?

Or another possibility: just don't panic if an invalid template is encountered. Skip files with bad syntax. Log it as an error and continue.

**Comment by liamsymonds** [comment]
Agreed - LoadHTMLGlob fails when it comes across a sub-directory too.

**Comment by thinkerou** [comment]
I think that you should write regex pattern to solve it.

**Comment by thinkerou** [comment]
maybe https://github.com/gin-gonic/gin/pull/1296 can help you.

**Comment by thinkerou** [comment]
Now gin not exists the problem, when start gin have the follow info:

```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (3):
	-
	- .index.tmpl.swp
	- index.tmpl

[GIN-debug] GET    /index                    --> main.main.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8080
```
cc @appleboy

**Comment by thinkerou** [comment]
use `router.LoadHTMLGlob("template/*.tmpl")` it's ok, it will ignore `*.tmpl.swp` file.
