### ISSUE TITLE
gin-gonic/gin/gin.go:56: cannot use engine.handle404 (type func(http.ResponseWriter, *http.Request)) as type http.Handler in assignment

### ISSUE THREAD

**Issue by netroby** [gin-gonic/gin#418]
github.com/gin-gonic/gin
../../src/github.com/gin-gonic/gin/gin.go:56: cannot use engine.handle404 (type func(http.ResponseWriter, *http.Request)) as type http.Handler in assignment:
 func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)
../../src/github.com/gin-gonic/gin/gin.go:57: cannot use engine.handle405 (type func(http.ResponseWriter, *http.Request)) as type http.Handler in assignment:
 func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)

**Comment by jame298** [comment]
revert github.com/julienschmidt/httprouter version to 8c199fb6259ffc1af525cc3ad52ee60ba8359669

**Comment by netroby** [comment]
Did that fixes it ? or should i close this issue?

**Comment by jame298** [comment]
Yes, httprouter has a commit 70708e46004c7bcb09b70e685a8b74a690135387

https://github.com/julienschmidt/httprouter/commit/70708e46004c7bcb09b70e685a8b74a690135387

Allow chaining of any http.Handler, not just http.HandlerFunc.

use old version of httprouter, can fix it.
