### ISSUE TITLE
Projects which uses Gin

### ISSUE THREAD

**Issue by thellimist** [gin-gonic/gin#419]
I couldn't find big open source projects which uses gin. Is there a list or could we create a list?

**Comment by javierprovecho** [comment]
I heard about a debian repository server which was using it, I don't remember its name.




To know who is using publicly, we could start by here: 




https://github.com/search?p=1&q=import+%22github.com%2Fgin-gonic%2Fgin%22&type=Code&utf8=%E2%9C%93



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by widnyana** [comment]
or you can look [here](http://godoc.org/github.com/gin-gonic/gin?importers)

**Comment by javierprovecho** [comment]
wow, that list looks awesome! thank you  @widnyana !



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by thellimist** [comment]
@widnyana I agree to javier. The list is awesome thanks!

**Comment by widnyana** [comment]
@javierprovecho @thellimist sure, you're welcome :)
