### ISSUE TITLE
Exit status from docker stop

### ISSUE THREAD

**Issue by aaronjwood** [gin-gonic/gin#422]
I have a systemd service that runs a docker container which runs my program using gin. I noticed that when I issue a `systemctl stop firewall` it stops successfully but it shows as failed due to the exit status not being 0. I've masked a few things below but it gives you the general idea of the output:

```
firewall.service - My firewall service
   Loaded: loaded (/etc/systemd/system/firewall.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2015-09-04 21:33:31 UTC; 3min 18s ago
  Process: 32695 ExecStop=/usr/bin/docker stop firewall (code=exited, status=0/SUCCESS)
 Main PID: 32386 (code=exited, status=2)

Sep 04 21:32:12 docker[32366]: c7923528965d: Download complete
Sep 04 21:32:12 docker[32366]: c7923528965d: Download complete
Sep 04 21:32:12 docker[32366]: Status: Image is up to date for <IP>:<PORT>/firewall:1.0
Sep 04 21:32:12 systemd[1]: Started My firewall service.
Sep 04 21:33:31 systemd[1]: Stopping My firewall service...
Sep 04 21:33:31 docker[32695]: firewall
Sep 04 21:33:31 systemd[1]: firewall.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 04 21:33:31 systemd[1]: Stopped My firewall service.
Sep 04 21:33:31 systemd[1]: Unit firewall.service entered failed state.
Sep 04 21:33:31 systemd[1]: firewall.service failed.
```

Could this be from docker trying to gracefully stop the process running inside the container but gin is throwing this exit code upon being stopped?

**Comment by javierprovecho** [comment]
exit code `!= 0` is normal, because all goroutines are forced to stop by the scheduler, maybe you want to use graceful shutdown to return a custom exit code https://github.com/gin-gonic/gin#graceful-restart-or-stop
