### ISSUE TITLE
POST request and json body

### ISSUE THREAD

**Issue by nlamirault** [gin-gonic/gin#424]
hi
i try to test POST request : 

``` go
package main

import (
    "fmt"

    "github.com/gin-gonic/gin"
)

type FOO struct {
    URL string `json:"url" binding:"required"`
}

func main() {
    r := gin.Default()
    r.GET("/ping", func(c *gin.Context) {
        c.String(200, "pong")
    })
    r.POST("/foo", func(c *gin.Context) {
        var url FOO
        c.BindJSON(&url)
        fmt.Printf("URL to store: %v\n", url)
    })
    r.Run(":8080") // listen an
}

```

But i can't bind to JSON : 

``` bash
$ curl -i -X  POST http://localhost:8080/foo \
  -H "Accept: application/json" -H "Content-type: application/json" \
  -d '{ "url": "http://www.google.fr" }'
HTTP/1.1 400 Bad Request
Date: Mon, 07 Sep 2015 12:15:57 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

Any idea ? where i make an error ?
Thanks.

**Comment by aacanakin** [comment]
`Content-type` should be `Content-Type` I guess

**Comment by nlamirault** [comment]
```bash
$ curl -i -X  POST http://localhost:8080/foo -H "Accept: application/json" -H "Content-Type: application/json" -d '{ "url": "http://www.google.fr" }'
HTTP/1.1 400 Bad Request
Date: Mon, 07 Sep 2015 14:45:57 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

**Comment by aacanakin** [comment]
Can you also try to add binding import to your imports ?
```go
package main

import (
    "fmt"
    "github.com/gin-gonic/binding"
    "github.com/gin-gonic/gin"
)
```

**Comment by nlamirault** [comment]
i try using 

```go
"github.com/gin-gonic/gin/binding"
```
but i've got this error during build : 
```bash
urls.go:22: imported and not used: "github.com/gin-gonic/gin/binding"
```

**Comment by aacanakin** [comment]
Well, I just tried doing the older version of yours(without the imports but with Content-Type). It works on my machine. Please make sure that you're at the latest version. 
```
$ go get -u github.com/gin-gonic/gin
```

**Comment by nlamirault** [comment]
According to my gb manifest file i m using commit **704d690ac0e25fcd060ff82f75f913e879e65a3c**

**Comment by toin0u** [comment]
@nlamirault It's working for me as well :)

![foo](https://i.imgur.com/N7VHDoB.png)

**Comment by cwkuo** [comment]
@nlamirault  Maybe curl was running with the environment variable $http_proxy ?
Try this one:
$ curl -i -X  POST http://localhost:8080/foo \
 **--noproxy '*'** \
  -H "Accept: application/json" -H "Content-type: application/json" \
  -d '{ "url": "http://www.google.fr" }'

**Comment by AdamNowaczyk** [comment]
For anyone getting to this point and trying to figure out why their code is not working, my problem was the fact, that struct attributes were lowercase... so changing this:

```
type LoginCommand struct {
	username string `json:"username"`
	password string `json:"password"`
}
```

to this:

```
type LoginCommand struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
```

Solved the problem... Rest of the code:

```
v1.POST("/login", func(c *gin.Context) {
	var loginCmd LoginCommand
	c.BindJSON(&loginCmd)
	c.JSON(http.StatusOK, gin.H{"user": loginCmd.Username})
})
```

Not sure if that's a bug or something. This is my first day with Go lang in general :p. Maybe this will help someone to resolve their issue.

**Comment by blackvirus18** [comment]
@adammck Your solution worked but I am just wondering why such a thing is happening.

**Comment by AdamNowaczyk** [comment]
@blackvirus18 Now I know that it's golang standard that public members should be started with upper case, private with lowercase. That's why in the first struct username and password members where not accessible. This is in fact pretty cool idea and works fine after getting used to :D.

**Comment by cyantarek** [comment]
> For anyone getting to this point and trying to figure out why their code is not working, my problem was the fact, that struct attributes were lowercase... so changing this:
> 
> ```
> type LoginCommand struct {
>     username string `json:"username"`
>     password string `json:"password"`
> }
> ```
> to this:
> 
> ```
> type LoginCommand struct {
>     Username string `json:"username"`
>     Password string `json:"password"`
> }
> ```
> Solved the problem... Rest of the code:
> 
> ```
> v1.POST("/login", func(c *gin.Context) {
>     var loginCmd LoginCommand
>     c.BindJSON(&loginCmd)
>     c.JSON(http.StatusOK, gin.H{"user": loginCmd.Username})
> })
> ```
> Not sure if that's a bug or something. This is my first day with Go lang in general :p. Maybe this will help someone to resolve their issue.

It's not a bug. Un-exported fields can not be used for json

**Comment by humbertovaz** [comment]
`messages={messages.sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt))}`

This helped me
