### ISSUE TITLE
c.Abort() not working for me

### ISSUE THREAD

**Issue by tsmith123** [gin-gonic/gin#426]
I have implemented a middleware to check App IDs:

```
func CheckAppId(appC *core.Context) gin.HandlerFunc {
    return func(c *gin.Context) {
        //get Basic Auth credentials
        appId, token, _ := c.Request.BasicAuth()

        if appId == "" {
            c.JSON(http.StatusOK, gin.H{"code": "MISSING_APP_ID", "message": "Your request is missing an application id"})
            c.Abort() //finish here if this block is executed
        }

        //find app_id in database
        app := core.App{}
        err := appC.Db.C("apps").Find(bson.M{"id" : appId}).One(&app)
        if err != nil { //no app found
            c.JSON(http.StatusOK, gin.H{"code": "INVALID_APP_ID", "message": "The application id provided could not be found"})
            c.Abort()
        }

        c.Next()
    }
}
```

When I make a request with BasicAuth credentials everything is fine but when I make a request without any credentials both JSON responses are being returned even though I have `c.Abort()` included in the code. It should abort after the first conditional without moving on to the next. Is there something I'm doing wrong here?

**Comment by nazwa** [comment]
I had the same problem, you have to manually return from the function. Abort only stops next middleware from executing :)
