### ISSUE TITLE
Can I out html file without template preprocessing?

### ISSUE THREAD

**Issue by aliksend** [gin-gonic/gin#428]
I use angular and have code like

``` html
<div> {{someval}} </div>
```

When using html rendering it is failing 'cos go try to process as template and it can't.
It working good when

``` go
r.StaticFile("/", "./public/index.html")
```

But if I try

``` go
r.StaticFile("/*", "./public/index.html")
```

to working with html5 routing in angular, server fails with 

```
URL parameters can not be used when serving a static file
```

How can I solve it?

**Comment by RobertJGabriel** [comment]
bump

**Comment by javierprovecho** [comment]
@aliksend now at [v1.2](https://github.com/gin-gonic/gin/releases/tag/v1.2) you can use [custom template renderer](https://github.com/gin-gonic/gin#custom-template-renderer) and/or [custom delimiters](https://github.com/gin-gonic/gin#custom-delimiters)
