### ISSUE TITLE
How to Debug Hex encoding problem?

### ISSUE THREAD

**Issue by windweller** [gin-gonic/gin#429]
Hi!!

I'm using Gin framework for a web server. I start to see some weird errors popping up. It wasn't there before:

```
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
Go error encoding/hex: invalid byte: U+0075 'u'
[GIN] 2015/09/10 - 23:41:28 | 200 |    8.505736ms | 17.218.239.229 |   HEAD    /
Go error encoding/hex: invalid byte: U+0075 'u'
```

The program is not shut down but this message makes me nervous. It doesn't appear every fixed time (like every minute), but it does come and appear after a while. Does anyone knok how to fix this bug (how to find the troubling file) and is it related to Gin?

**Comment by javierprovecho** [comment]
@windweller probably it may be a wrong char sent by the http client you are using, never saw this error however we need more info if you still see it. reopen if this happens you again
