### ISSUE TITLE
Write Status only

### ISSUE THREAD

**Issue by bradrydzewski** [gin-gonic/gin#435]
Hi there, I've been using gin quite extensively in one of my projects, and there are often times I'd like to only return the status code (no body). Would you be open to a pull request that allows the following:

```
c.NoContent(http.StatusOK)
```

or even simply:

```
c.Status(http.StatusOK)
```

Currently I'm doing `c.Response().WriteHeader(http.StatusOK)`, however, I think the above helper functions are a bit more readable and more consistent with how I interact with gin for everything else. Thanks!

**Comment by cwkuo** [comment]
Maybe you could use:

    c.String(http.StatusOK, "")

or

    c.AbortWithStatus(http.StatusOK)

**Comment by javierprovecho** [comment]
(cleaning old issues) `c.Status(http.StatusOK)` is already available (http://godoc.org/github.com/gin-gonic/gin#Context.Status)
