### ISSUE TITLE
Dependency Injection in Gin

### ISSUE THREAD

**Issue by phrozen** [gin-gonic/gin#436]
How to do dependency injection with Gin, for example for testing/mocking, or to have a Middleware that make a Copy of the database session in each request? (ie. MongoDB)

Have searched far and wide and I can't find any examples.

I'm currently injecting my DB Session Copy into the context map via middleware (defer close) and then extracting it with a function inside my handler with type assertion, I think that's the correct/only way, but it just doesn't feel right.

**Comment by andviro** [comment]
There are some nice ideas in this [blog entry](http://www.alexedwards.net/blog/organising-database-access).
