### ISSUE TITLE
Parse Non standard POST form

### ISSUE THREAD

**Issue by c0ze** [gin-gonic/gin#438]
Hello,

I need to parse a POST request which has something like 

```
",eventType=Exit,Name=Zone0,SiteID=test,DeviceID=00b09dc9e,DT=2015-09-18T03:07:37\r\n"
```

in the body. Unfortunately it is comma separated. Is there a way to configure a custom Binder for these type of requests ? Is there an example somewhere ?

Thanks for the great software !

**Comment by dvwright** [comment]
Have you tried c.PostForm or c.Query('eventType') or c.Params.ByName? e.g.

```
    r.POST("/post", func(c *gin.Context) {
        evntT := c.Query("eventType")
        name := c.PostForm("name")
        message := c.PostForm("message")
    })
```

If you have and they don't find them you could provide your own parsing method directly on the body of the request. e.g.

```
    r.POST("/post", func(c *gin.Context) {
        x, _ := ioutil.ReadAll(c.Request.Body)
        fmt.Printf("%s", string(x))
        // methods to split fields/values ..
```

**Comment by appleboy** [comment]
see https://github.com/gin-gonic/gin/pull/857

**Comment by c0ze** [comment]
Thank you, I ended up parsing the body myself.
