### ISSUE TITLE
BindJSON returns EOF

### ISSUE THREAD

**Issue by DVassilev** [gin-gonic/gin#439]
I am trying to use context#BindJSON but it returns EOF. If I replace it with a JSON Decoder it works fine.

A sample of the code:
http://hastebin.com/torosarosi.go

Anyone know as to why it may be returning EOF?

**Comment by mvader** [comment]
Can you provide an example of the JSON you're using?

**Comment by renannprado** [comment]
Using the latest version of Gin I sometimes Get EOF error too while doing `ctx.Bind(&myStruct)` and it's intermittent.

**Comment by nscarlson** [comment]
Same problem here!

**Comment by tboerger** [comment]
Without further details it's hard to reproduce such an issue, for my cases it works totally fine.

**Comment by vjeantet** [comment]
Hello, i had this issue too, the problem occurs when i read from the Request Body twice.

**Comment by jackzh8** [comment]
Hi all, it's just need to comment the code in BindWith method of context.go file, then it will break the response, you can handle the error response on your own.
`// BindWith binds the passed struct pointer using the specified binding engine.
// See the binding package.
func (c *Context) BindWith(obj interface{}, b binding.Binding) error {
	if err := b.Bind(c.Request, obj); err != nil {
// 		c.AbortWithError(400, err).SetType(ErrorTypeBind) // let developer to handle error response.
		return err
	}
	return nil
}`

**Comment by ramabmtr** [comment]
Hi all, I just realized that when I validate JSON using `c.BindJSON` and that JSON is not a valid JSON, `EOF` will returned.
This happen because Gin will try to decode that JSON first using `json.NewDecoder(req.Body).Decode(obj)` before validating.

Can you try validate your JSON first are they valid or not?

for @vjeantet issue, read request body (`c.Request.Body`) before validating will trigger `EOF` too because after you read request body, it will closed automatically by system. This will affect `BindJSON` to return `EOF` because request body is not present anymore.

Please CMIIW, I'm quite new at Golang 😄 
and sorry for my english

**Comment by dlb233** [comment]
Same problem. it will happened when I use ***Decoder.Decode***  after  ***ctx.Bind***. Guess it's because of the former function will mark a terminated sign to the Context or something like that, so the second function returns EOF.

How can I receive the other parameter that do not exist at the parameter struct if I can only read context once?

I'm a green hand of golang, this question confused me a lot.

**Comment by rmrf** [comment]
same issue, then find the reason, 

I have a ioutile read  `c.Request.Body` before the BindJson, after delete the ioutil read, issue gone.

**Comment by lucabelluccini** [comment]
The BindJSON is reading the body, so we are at EOF if the context Body get read multiple times.

What would be the best approach? Storing it somewhere?

**Comment by yunfengsay** [comment]
same to me 
![image](https://user-images.githubusercontent.com/15527378/31494147-abdbc2ba-af17-11e7-9f69-e549c5585b26.png)
![image](https://user-images.githubusercontent.com/15527378/31494158-b23c43d2-af17-11e7-8d49-f9dd0448282a.png)

**Comment by delphinus** [comment]
@yunfengsay 
Your example seems to load JSON from body, but body is none because it is GET request. GET request should have no body.

https://stackoverflow.com/questions/978061/http-get-with-request-body
> Yes, you can send a request body with GET but it should not have any meaning.

**Comment by chunbaise** [comment]
I had this issue too, the problem occurs when i read from the Request Body twice.
What would be the best approach? Thanks

**Comment by FrankenSteinxD** [comment]
I have this issue too when I read from the request body more than once.

**Comment by ruanyanghui** [comment]
![image](https://user-images.githubusercontent.com/34758693/44379358-260df280-a538-11e8-9fcc-42cf4fcb43c2.png)
You can try Copy()

**Comment by thinkerou** [comment]
Hi, all, please use `ShouldBindBodyWith ` and see #1341 details which have fixed the issue, thanks!

**Comment by yw4c** [comment]
Cloning the context is work for me
`	return func(context *gin.Context) {

		c := *context
		context.Next()

		databyte, err := c.GetRawData()
		var req string
		if err != nil && len(databyte) == 0 {
			req = ""
		}
		req = string(databyte)

		log.Info().
			Str("path", c.Request.URL.Path).
			Str("method", c.Request.Method).
			Str("request-id", c.Request.Header.Get("x-request-id")).
			Str("request-data", req).
			Interface("header", c.Request.Header).
			Int("response-status",context.Writer.Status()).
			Msg("Access Log")
	}`

**Comment by lzhpo** [comment]
I guess you requestBody maybe not JSON, so you get EOF error.
You can use `ShouldBind` instead of `BindJSON`.
```
userReq := &user.PageUserReq{}
err := c.ShouldBind(userReq)
```

**Comment by ZhangDongling** [comment]
`unexpected EOF` may be caused by that:
In your request header, the value of `Content-Length` is smaller than the actual length of request body.
Just remove the `Content-Length` in the request header and it will work well.

**Comment by krystalics** [comment]
> Hello, i had this issue too, the problem occurs when i read from the Request Body twice.
yes 、I just have the same issue, I think the data stream has been read out , and the second time it will read the EOF directly.
When I remove the first bind , the other one works well!
maybe it can reset the cursor in the body stream?
very common operation
```go
json := make(map[string]interface{})
c.BindJSON(&json)
bodyStr, _ := jsoniter.MarshalToString(json)
```

**Comment by JulioCRFilho** [comment]
> Hello, i had this issue too, the problem occurs when i read from the Request Body twice.

This is the right answer, my middleware that prints the request body was causing the problem, seems foolish but it's true lol

**Comment by aminNazarii** [comment]
this issue occurs when you read body data twice.
with `ShouldBindBodyWith` method you can copy of body and solve EOF error.
like this
`
var req NewRequest
if err := ctx.ShouldBindBodyWith(&req, binding.JSON); err != nil {
    // do something
}
`

**Comment by SolomonSitotaw23** [comment]
this happens when I read the context before binding.
