### ISSUE TITLE
Redirect on 404?

### ISSUE THREAD

**Issue by 01AutoMonkey** [gin-gonic/gin#440]
New to gin and am experimenting with intercepting 404, so far I have this:

```go
...
r := gin.Default()
r.Use(createAndReload())
...
func createAndReload() gin.HandlerFunc {
    return func(c *gin.Context) {
        c.Next()
        status := c.Writer.Status()
        if status == 404 {
          createFile(c)
          c.Redirect(301, c.Request.URL.Path)
        }
    }
}
...
```

The intended behavior is that when you hit a 404 page gin creates that page (a static file) and then refreshes/reloades or "redirects" the user to the same page, which now exists.

But I'm having trouble overwriting 404, the above code just serves a 404 page with some additional text:

```
404 page not found
<a href="/test1">Moved Permanently</a>.
```

Do I have to do a `/:page` route that handles this so it never actually enters a 404 state, or can I continue using `r.StaticFS("/wiki", http.Dir(buildDir))` and when the static file doesn't exist I just intercept the process?

Also one problem with the `/:page` route solution, the content I want to serve is just static html so .StaticFS seems ideal, I can't serve through c.JSON or c.String, but maybe through c.HTML, but that requires me to make gin aware of "HTML Templates" which I guess would be `router.LoadHTMLGlob(buildDir+"/*")` but I'm not sure if that can "adjust" to created and deleted files in the build dir like .StaticFS can, which would leave me with somehow removing and adding "templates" (actualy just static html in this case) as they get added and removed in the filesystem.

**Comment by nazwa** [comment]
Ha, that's an interesting one. The `http/fs` appears to be doing its own 404 handling, which completely bypasses Gin's error handlers. I don't think there is actually much you can do except for manually checking if file exist in a middleware **before** passing it onto fs.

```go

func createAndReload() gin.HandlerFunc {
    return func(c *gin.Context) {

// Get file path and check if exists
// If not, create
// No need to redirect as FS fill pick it up now

// continue with the flow
        c.Next()

// 404 will never happen
/*
        status := c.Writer.Status()
        if status == 404 {
          createFile(c)
          c.Redirect(301, c.Request.URL.Path)
        } */
    }
}
```

**Comment by 01AutoMonkey** [comment]
Perfect, thanks.
