### ISSUE TITLE
Reload changed template files without restart?

### ISSUE THREAD

**Issue by AllenDang** [gin-gonic/gin#442]
After update template html files, is there anyway that gin could reload those files into memory without restart whole service?

**Comment by vinceyuan** [comment]
In debug mode, gin always reload templates. In release mode, gin loads templates only once.

**Comment by AllenDang** [comment]
I know gin will reload in debug mode. I'm asking about in release mode whether there is a plan to support hot reload. I don't want to restart my server everything just because one html file is changed.
