### ISSUE TITLE
How to compress the response with gin?

### ISSUE THREAD

**Issue by shengzhi** [gin-gonic/gin#445]
I want to compress the http response with gzip or deflate, the algorithm is determined by "Accept-Encoding" of request header. 
How to do it?

Thanks.

**Comment by nazwa** [comment]
Have a look at the Contrib repo. Not sure if it will work out of the box, but should at least point you in the right direction :smile:

https://github.com/gin-gonic/contrib/tree/master/gzip

**Comment by shengzhi** [comment]
Thanks nazwa!
