### ISSUE TITLE
How to log the response body?

### ISSUE THREAD

**Issue by qimingweng** [gin-gonic/gin#446]
I want to write a custom logger that, for 5xx errors, will log the response body, but I can't find any documentation on getters for the body, only setters. I imagine the body is streamed or takes an io.Writer shape so this is probably a little more complex; but would appreciate any guidance

**Comment by nazwa** [comment]
You need to create a custom Writer that caches the response. This is probably not the prettiest way of doing it, but it seems to work:

```go
type bufferedWriter struct {
	gin.ResponseWriter
	out    *bufio.Writer
	Buffer bytes.Buffer
}

func (g *bufferedWriter) Write(data []byte) (int, error) {
	g.Buffer.Write(data)
	return g.out.Write(data)
}

func E500() gin.HandlerFunc {
	return func(c *gin.Context) {

		w := bufio.NewWriter(c.Writer)
		buff := bytes.Buffer{}
		newWriter := &bufferedWriter{c.Writer, w, buff}

		c.Writer = newWriter

// You have to manually flush the buffer at the end
		defer func() {
			if c.Writer.Status() != 200 {
				fmt.Printf("%s\n", newWriter.Buffer.Bytes())
			}
			w.Flush()
		}()

// Run the execution chain
		c.Next()
	}
}
```


What you should maybe think about more is how you actually handle errors. Your app should never really throw 500 unless you intentionally triggered it, in which case you can have a proper error logging logic in place using maybe even something as simple as `c.Error()`

**Comment by qimingweng** [comment]
Thanks @nazwa I was just hoping there was a way to catch the response writer but I guess there isn't. It is more idiomatic, then, to log errors in some kind of global error catcher?

**Comment by nazwa** [comment]
Sadly don't think so. In all our projects we use something like this: https://github.com/gin-gonic/gin/issues/430#issuecomment-141774133 (it looks big, but that's only because this also handles form validation errors. Plus needs a proper clean up)
