### ISSUE TITLE
Transform Request/Response / Mappings

### ISSUE THREAD

**Issue by lucmichalski** [gin-gonic/gin#448]
Hi guys,

I was wondering if it was possible to:
- Transform an incoming request, I have a multipart image to convert into a base64 string and wrap it into a JSON payload, then I have several templates for the json (one per routes).
- Transform the output response by nesting the request of 4 routes queried with the previous transorm and combine results ?

I am looking to do something like https://github.com/daniel-j-h/DistributedSearch

Is it possible to do it with gin ? What would be the best golang http routeur to do that fast and with a low memory footprint ?

Cheers,
Luc

**Comment by javierprovecho** [comment]
@lucmichalski for both of them, yes, you can do it in gin.

for the 1st, you can use a mutex and store the parts on an array securely, then have an endpoint for checking if that array is complete or not, and encode it with the native library.

for the 2nd, you can query your 4 routes concurrently and wait until all of them have been resolved/returned using a `sync.wait`, then just append your results and post your response back.
