### ISSUE TITLE
Supports custom template functions

### ISSUE THREAD

**Issue by vinceyuan** [gin-gonic/gin#449]
I want to add a custom function to my html templates. I copied code from `gin.LoadHTMLGlob` and added `Funcs(funcMap)`, but the custom function only works in release mode. 

``` go
// Modified code from gin.LoadHTMLGlob
func loadHTMLGlob(engine *gin.Engine, pattern string) {
    funcMap := template.FuncMap{
        "customFunc": customFunc, // A custom template function
    }
    //if gin.IsDebugging() {
    //  debugPrintLoadTemplate(template.Must(template.New("").Funcs(funcMap).ParseGlob(pattern)))
    //  engine.HTMLRender = render.HTMLDebug{Glob: pattern}
    //} else {
    templ := template.Must(template.New("").Funcs(funcMap).ParseGlob(pattern))
    engine.SetHTMLTemplate(templ)
    //}
}
```

After researching, I found the cause. In debug mode, `debugPrintLoadTemplate(template.Must(template.New("").Funcs(funcMap).ParseGlob(pattern)))` only checks templates but does not really use them. gin always reloads templates without calling Funcs(funcMap) when rendering. 

I have to comment out the related code for debug mode. Custom function works now. But I have to restart the app to let the modified template work when developing. It's a little inconvenient. 
#### It will be great if gin supports custom template functions. I think many people need custom template functions.

I am not confident enough to make a pull request. I suggest adding a variable like funcMap and modifying code in gin/render/html.go like this:

``` go
func (r HTMLDebug) loadTemplate() *template.Template {
    t := template.New("")
    if funcMap != nil {
        t.Funcs(funcMap) // Set funcMap for custom template functions
    }
    if len(r.Files) > 0 {
        return template.Must(t.ParseFiles(r.Files...))
    }
    if len(r.Glob) > 0 {
        return template.Must(t.ParseGlob(r.Glob))
    }
    panic("the HTML debug render was created without files or glob pattern")
}
```

**Comment by nitsanfiverr** [comment]
Hey Guys, is there anything new with that ? I'm having the exact same issue and workaround now. 
It's really hard to develop like this... 

Thanks..

**Comment by vinceyuan** [comment]
@nitsanfiverr Nothing new. I'm still using the workaround.

**Comment by stanonyime** [comment]
@vinceyuan Please, can you provide more details on how the workaround fits into the router?

**Comment by vinceyuan** [comment]
@stanonyime Please see my post at the top. If you want to add custom function to your templates, do not use `gin.LoadHTMLGlob`, copy the sample function I provided to a .go file in your project and modify for your need. Then call it in main() like the following

```
	router := gin.Default()
	loadHTMLGlob(router, "views/*")
```

**Comment by stanonyime** [comment]
Thanks for your feedback. But when I tried it, it panics with:
```go
 cannot use templ (type *"text/template".Template) as type *"html/template".Template in argument to engine.SetHTMLTemplate
```

**Comment by vinceyuan** [comment]
Did u import "html/template"? Not text/template.

**Comment by stanonyime** [comment]
@vinceyuan Oh! Thanks

**Comment by changx** [comment]
@vinceyuan   You can use your own html render by implement interfaces `render.Render` and `render.HTMLRender`. 

```
type PageTemplate struct {
	TemplatePath string
	templates    *template.Template
}

type PageRender struct {
	Template *template.Template
	Data     interface{}
	Name     string
}

func (r PageTemplate) Instance(name string, data interface{}) render.Render {
        r.loadTemplates()
        return PageRender{
                Template: r.templates,
                Name:     name,
                Data:     data,
        }
}

func (r PageRender) Render(w http.ResponseWriter) error {
	header := w.Header()
	if val := header["Content-Type"]; len(val) == 0 {
		header["Content-Type"] = []string{"text/html; charset=utf-8"}
	}

	log.Printf("PageRender.Render")
	if len(r.Name) > 0 {
		log.Printf("Template [%s] with data [%v]\n", r.Name, r.Data)
		r.Template.ExecuteTemplate(w, r.Name, r.Data)
	} else {
		log.Printf("Template with data [%v]\n", r.Data)
		r.Template.Execute(w, r.Data)
	}

	return nil
}
```

```
r := gin.Default()
r.HTMLRender = PageTemplate{
    TemplatePath: "views/"
}
```

**Comment by appleboy** [comment]
V1.2 support custom template funcs. See the following example.

https://github.com/gin-gonic/gin#custom-template-funcs
