### ISSUE TITLE
Binding and Context.JSON 

### ISSUE THREAD

**Issue by marksalpeter** [gin-gonic/gin#451]
Any chance we could change Binding.Bind(_http.Request, interface{}) error to Binding.Bind(_http.Request, ...interface{}). I'm always parsing hash maps from the server. It would be nice to get multiple objects out of them using reflection and map[string]json.RawMessage. You don't have to make that the default implementation, and it wouldn't be a breaking change. I would just like to be able to write a binding that does this myself.

To that end, is there any way we could spin off rendering json into a "rendering" package, much like the "binding" package and then change Context.JSON(int, interface{}) to Context.JSON(int, ...interface{}). Again, I would like to be able to dynamically construct a map[string]interface{} from multiple models with reflection . This would also not be a breaking change. 

UPDATE: It looks like you already have a "render" package. I'm not sure if it can do what I wan't it to do though.

If neither of these changes sound outlandish to you, I would be happy to make them myself when I have time. But if these changes seem like ones you would not want to incorporate into the framework and support, I won't bother. Gin is really promising, but I just need a way to do these two things for me to switch. Thanks.

**Comment by thinkerou** [comment]
@marksalpeter I understand the change will break old app and can't change because gin have stable, right.

**Comment by marksalpeter** [comment]
Yep I figured as much. I basically wrote my own version of gin to use internally that does this. Maybe I'll release it one day ;)
