### ISSUE TITLE
App-engine example doesnt work.

### ISSUE THREAD

**Issue by carlosalarconb** [gin-gonic/gin#457]
App engine example doesnt work ...I got this error:
ERROR    2015-10-09 18:09:35,445 http_runtime.py:391] bad runtime process port ['[GIN-debug] GET   /                         --> main34740.func\xc2\xb7001 (1 handlers)\n']

**Comment by carlosalarconb** [comment]
fixed using gin.SetMode(gin.ReleaseMode)

**Comment by javierprovecho** [comment]
@carlosalarconb good to know, thanks for testing it out ;)
