### ISSUE TITLE
Is router path case-sensitive? why? 

### ISSUE THREAD

**Issue by shengzhi** [gin-gonic/gin#459]
Is there a way set router path to case-insensitive?

**Comment by javierprovecho** [comment]
@shengzhi no, there is not. If you need a "wildcard" path to emulate case-insensitive, you can use a parameter in path, however this is a hack and I don't recommend it. Gin doesn't allow regexp, and that's why it is so fast.

**Comment by shengzhi** [comment]
Thanks @javierprovecho, is it possible that add the feature into next version? As my understanding, just only need to convert path to lower letter before parsing router, is it?

**Comment by javierprovecho** [comment]
@shengzhi is not that simple. We search the handler directly on a tree by key, where key is the path and the verb. However I'll keep this issue open for the future.
