### ISSUE TITLE
Add a Readme for different plugins/middleware written for Gin 

### ISSUE THREAD

**Issue by 0x4139** [gin-gonic/gin#460]
contribution : https://github.com/0x4139/ginAuthentication

**Comment by robvdl** [comment]
This contrib package already adds sessions https://github.com/gin-gonic/contrib/tree/master/sessions and it uses gorilla sessions as a backend, so you can use whatever session store, redis, etc.

But I agree that a section for third party libraries is needed, either on the README, or wiki, whatever works best.

**Comment by javierprovecho** [comment]
@0x4139 you can make a PR with a edit to the README of gin-gonic/contrib if you don't want to merge it. However I'll add a more clear link to the top of the README in gin-gonic/gin, so new people can find the contrib repo easier.

**Comment by 0x4139** [comment]
@javierprovecho merge it where?

**Comment by javierprovecho** [comment]
@0x4139 here: https://github.com/gin-gonic/contrib/pulls

As I said, you can open a PR for all your code, or just a link inserted into the README
