### ISSUE TITLE
return a JSON data,is always more than a blank line

### ISSUE THREAD

**Issue by SmarkSeven** [gin-gonic/gin#462]
When I use c.JSON () on the server to return a JSON data, the data returned by the server in the Chrome browser to see the data is always more than a blank line

**Comment by javierprovecho** [comment]
@SmarkSeven I don't understand what you are trying to say... I can see perfectly a  response in Chrome 46. Could you explain better?

![image](https://cloud.githubusercontent.com/assets/2457529/10509923/4eb0ac56-7330-11e5-8962-7027911d6d25.png)
