### ISSUE TITLE
How to return plain text with content type "application/json; charset=utf-8"?

### ISSUE THREAD

**Issue by vinceyuan** [gin-gonic/gin#468]
I know `context.JSON()` returns the serialised object with content type `"application/json; charset=utf-8"`. But I want to skip serialising by returning __cached__ plain text, because my object does not change constantly.

Is it possible to use something like `context.String()` but set content type `"application/json; charset=utf-8"`?

Thanks.

**Comment by mattprice** [comment]
Check out [`context.Header()`](https://godoc.org/github.com/gin-gonic/gin#Context.Header). You should be able to do this:

``` go
context.Header("Content-Type", "application/json; charset=utf-8")
context.String(...)
```

**Comment by vinceyuan** [comment]
@mattprice Thanks for the reply. But it does not work because `context.String()` overwrites `Content-Type`.

**Comment by mattprice** [comment]
Odd. What about [`context.Data()`](https://godoc.org/github.com/gin-gonic/gin#Context.Data)?

``` go
context.Data(200, "application/json; charset=utf-8", []byte(someString))
```

**Comment by vinceyuan** [comment]
It looks promising. I will try. Thanks.

**Comment by vinceyuan** [comment]
@mattprice It works. Thanks!
