### ISSUE TITLE
How about change "golang.org/x/net/context" to "github.com/golang/net/context"

### ISSUE THREAD

**Issue by leedstyh** [gin-gonic/gin#469]
Sorry to bother you, but golang.org is blocked in China. It's hard to `go get` code here.

So how about change "golang.org/x/net/context" to "github.com/golang/net/context"

**Comment by muratsplat** [comment]
@leedstyh  You mean China government  banned  to access golang.org?

**Comment by leedstyh** [comment]
@muratsplat Yeah, it's banned!

**Comment by AlekSi** [comment]
Sorry, this will not work. Official import path is `golang.org/x/net/context`: https://github.com/golang/net/blob/master/context/context.go#L37
