### ISSUE TITLE
Someone still maintain?

### ISSUE THREAD

**Issue by mttrs** [gin-gonic/gin#476]
Looking at the commit, the last one is September... I'd like to use gin, but I'm afraid what this WF going to. Go version is 1.4, too. Could anyone know anything?

**Comment by lawlite** [comment]
I also wonder this: Does manucorporat still keep Gin Framework? I am worried about that he didn't make any public contributions since 17th august.

I really like Gin Framework, so I hope that this very-good-framework keeps moving forward.

(In comparison, Echo Framework which is similar to Gin Framework is updated frequently.)

**Comment by olebedev** [comment]
+1 to the question. Is it still maintained? I have just looked at Echo and it looks pretty well for me. But I love Gin and use it in my several projects and I don't want to migrate to Echo. Could you guys @manucorporat @javierprovecho  tell us about your plans?

**Comment by agaurav** [comment]
+1 . I too absolutely love it and use it in all my web projects.

**Comment by coolmenu** [comment]
any comments? thanks

**Comment by talbright** [comment]
+1

**Comment by gplume** [comment]
I think this could be related to #185 
@lawlite  Gin is v1 and stable now, it probably doesn't need the frequent updates your talking about...

**Comment by mttrs** [comment]
Many issues and pull-requests are still coming and it looks not to handle them well. Reply, comment and whatever.. v1 is probably stable, but many people want to improve the gin. I wanna know the milestone/future of gin. No change, no improvement.

**Comment by talbright** [comment]
There's been little activity in the past few months regarding commits to master, but yet clearly a decent amount of community interest given the PR queue. And from the looks of it some nice design decisions and tradeoffs were made with Gin.

FWIW -- the lack of movement though is a red flag for people that might be evaluating using Gin over other frameworks (the same people that might help out by contributing back bug fixes and improvements later on.)

**Comment by robvdl** [comment]
Sounds like some other experienced Gin community members need to be given repo access, if the owner is unable to maintain reviewing the pull requests, they might be able to take some of the load off and keep the project moving.

**Comment by javierprovecho** [comment]
Hello everyone,




This happens some time to time, that an issue appears asking if the framework is still maintained.




Short answer, it is maintained.




Long answer, not many people know that both Manu and me are students. Last week we were at dotGo, talking with cool people and working on Gin at the hotel.




We are picking most used middlewares from gin-gonic/contrib, rewriting them, and pushing into a new organization called gin-contrib. From now secure and cors do now 0 allocs per request.




About granting access to unknown people to a repository of +4000 stars, that requires a little more of thrust.




We will be focused on promoting some middlewares into officially maintained middlewares. We will also make an effort to improve docs.




Hope I have provided enough answers.




Best,

Javier.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by mttrs** [comment]
Thanks @javierprovecho for your reply. Glad to hear that it's maintained and you're working on the improvement. Looking forward to seeing the new things in gin-contrib and will contribute it if I find an interesting thing :)

Regards,
Mitsu

**Comment by talbright** [comment]
Thanks for the reply. I'm sure it takes a lot of trust to pick someone to help, but if you are students you probably need to consider doing so all the more, as I'm sure you have a lot on your plates :stuck_out_tongue_winking_eye: 

Regardless, best wishes....

**Comment by manucorporat** [comment]
@talbright @mttrs @lawlite  I have been pushing new official middleware for gin:
- Same unit testing requirements than Gin
- Same code quality
- Security audited
- API promise

https://github.com/gin-contrib/cors
https://github.com/gin-contrib/secure

they are still in a beta state.

**Comment by robvdl** [comment]
Thanks for the explanation.

@manucorporat how is github.com/git-contrib different to github.com/gin-gonic/contrib ?? Upto now I have been using the second one, should I be using the first one instead?

**Comment by javierprovecho** [comment]
@robvdl




The first one is a repo of middlewares, the second one is an organization of repos, where each one is a middleware.


This have a few benefits:

- CI don't fail for all if a single package does.

- Every import is sorted and its path is shorter.

- All packages at gin-contrib are directly supervised by the maintainers.




You should use the gin-contrib organization, but keep in mind this week we are importing and improving each one, so use with caution. As Manu said, they are in beta.





NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by manucorporat** [comment]
@robvdl the contrib repo does not scale well, also, the new middleware break the api, so a different URL is needed.

- All middleware will share the same API pattern.
- Repo per middleware allow us to maintain and audit them better.
- Once 1.0 is reached in the middleware, we will not break the api again.
- Security audited
- We not longer will accept third party middleware that could get unmaintained.

**Comment by santagada** [comment]
And what about gin repo itself... no one seems to be updating it.

**Comment by joeblew99** [comment]
Yes I am also wanting an answer about the main repo and maintenance of it please.
It was not answered.

If the truth is that the next phase if the project requires refactoring, due to breaking the project out into middlewares and hen ebreaking the core, then tell us. It's not like this is not unusual or a bad thing. In fact it shows that the project has a future and actually alleviates my and others con erns.

It's also quite normal that a project gets to that stage. It's very hard to have a fixed api, but still innovate under the hood. Eventually the public api has to break.

So please let us all know..

**Comment by javierprovecho** [comment]
Hi there,

Basically same as I said a week ago at #491.
We are in the middle of exams.

At least I'm satisfied that the project is stuck while stable and there are no critical bugs.

We have a lot of things to innovate, one of them is http2, other can be middleware...

Hope to get some free time by 1st/2nd week of february.

**Comment by no1youknowz** [comment]
1.6 is around the corner.  Would be great to get http2 beginning of feb!

Thanks!
