### ISSUE TITLE
is there any way to get  hot reload!

### ISSUE THREAD

**Issue by train860** [gin-gonic/gin#477]

**Comment by olebedev** [comment]
@train860 sure, take a look https://medium.com/@olebedev/live-code-reloading-for-golang-web-projects-in-19-lines-8b2e8777b1ea

**Comment by train860** [comment]
thank you！

**Comment by roma86** [comment]
@firetrain there is an simpler way https://github.com/pilu/fresh

**Comment by cosmtrek** [comment]
I write an tool [air](https://github.com/cosmtrek/air) based on [fresh](https://github.com/pilu/fresh), please have a try~

**Comment by chanhz** [comment]
https://github.com/silenceper/gowatch

**Comment by AgentCosmic** [comment]
I ended up writing my own tool because none of the above worked for me. xnotify will also let you auto test your app without needing to install another tool.
https://github.com/AgentCosmic/xnotify

**Comment by jeanlambert17** [comment]
You could use nodemon, install it globally and run `nodemon --exec go run main.go --signal SIGTERM`

**Comment by lissdy** [comment]
https://github.com/codegangsta/gin is helpful.

**Comment by dragonDScript** [comment]
> You could use nodemon, install it globally and run `nodemon --exec go run main.go --signal SIGTERM`

To use Nodemon users will have to install Node.js, NPM and others just to use nodemon. I would recommend to use fresh, air or gin directly.

This makes your "getting started", "contributing", or "building" section too much complex.

**Comment by stairclimber** [comment]
> @train860 sure, take a look https://medium.com/@olebedev/live-code-reloading-for-golang-web-projects-in-19-lines-8b2e8777b1ea

Is this HOT reload? I don't think so...

**Comment by MPMcIntyre** [comment]
I made this for one of my projects https://github.com/MPMcIntyre/go-again/ 

Hopefully its what you need
