### ISSUE TITLE
What is the best way to handle dynamic subdomains?

### ISSUE THREAD

**Issue by dre1080** [gin-gonic/gin#479]
An example is if you wanted users to have their own subdomains like GitHub Pages: `{username}.github.io`

**Comment by lawlite** [comment]
As far as I know, the routing has priority over context settings with a HttpRouter based framework like Gin.

So, how about this?

```Go
func (hs HostSwitch) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if handler := hs[r.Host]; handler != nil {
		handler.ServeHTTP(w, r)
	} else {
		if r.Host == "username.example.com" { // Or find strings.Split(r.Host, ".")[0] from database
			// Something action here...
			// http.Redirect? httputil.NewSingleHostReverseProxy? to username's page
			return
		}
		http.Error(w, "Forbidden", 403) // Gin's logger doesn't record this.
	}
}
```
HostSwitch example from https://github.com/julienschmidt/httprouter#multi-domain--sub-domains

**Comment by nazwa** [comment]
I would probably rewrite the domain in a proxy, like apache or ngingx, into

github.io/{username}/... 

and only then forward the request to gin. Seems like a much neater way of doing it than trying to extract the name from url manually. Especially as I'm sure you have some sort of a public facing proxy set up already.

**Comment by javierprovecho** [comment]
@dre1080 you can use nazwa solution

or create a unique router for each domain/subdomain, see https://github.com/julienschmidt/httprouter#multi-domain--sub-domains

or check `c.Request.Host` in your handler context.

Sorry for delay. I'm closing this because there is enough solutions posted.
