### ISSUE TITLE
Capture origin of error

### ISSUE THREAD

**Issue by phemmer** [gin-gonic/gin#484]
This is a continuation of #206 since the author closed it.
The idea is that when an error is raised, we should be able to find where the error came from. Currently, for many error sources, such as `context.JSON()`, we don't get to control the error message, so we can't add anything to identify the source, or what was going on at the time.
The best way to solve this would be to get a stack trace. If the `gin.Error` struct had a field for holding a stack trace, we could set a flag on the engine (which would be inherited by context) that would control whether or not to gather a stack trace on `Context.Error()`.
The loggers could then do what they want with the stack trace, such as showing the line number of the first frame outside the `gin` package, or the full stack.

Edit: It would probably also be good to capture the timestamp inside the error. This just in case there is a large delay going back down through the middleware stack before you get to the logger.

**Comment by thinkerou** [comment]
Now have been able capture, like:

```shell
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).insertChild(0xc0001a02a0, 0xff, 0xc0001ae388, 0x4, 0xc0001ae380, 0xc, 0xc0001a8300, 0x3, 0x3)
	/Users/tianou/GoProjects/src/github.com/gin-gonic/gin/tree.go:265 +0xb50
github.com/gin-gonic/gin.(*node).addRoute(0xc0001a0240, 0xc0001ae380, 0xc, 0xc0001a8300, 0x3, 0x3)
	/Users/tianou/GoProjects/src/github.com/gin-gonic/gin/tree.go:243 +0x269
github.com/gin-gonic/gin.(*Engine).addRoute(0xc000200000, 0x16834ab, 0x3, 0xc0001ae380, 0xc, 0xc0001a8300, 0x3, 0x3)
	/Users/tianou/GoProjects/src/github.com/gin-gonic/gin/gin.go:252 +0x145
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc000200000, 0x16834ab, 0x3, 0x1688eca, 0xc, 0xc0001a6048, 0x1, 0x1, 0x1744c01, 0xc0001a6048)
	/Users/tianou/GoProjects/src/github.com/gin-gonic/gin/routergroup.go:71 +0x1d3
github.com/gin-gonic/gin.(*RouterGroup).GET(0xc000200000, 0x1688eca, 0xc, 0xc0001a6048, 0x1, 0x1, 0x1744c80, 0xc000200000)
	/Users/tianou/GoProjects/src/github.com/gin-gonic/gin/routergroup.go:99 +0x7c
main.main()
	/Users/tianou/nor.go:14 +0xfd
exit status 2
```
