### ISSUE TITLE
How to get the actual TCP port number when listening on port 0

### ISSUE THREAD

**Issue by orangesoup** [gin-gonic/gin#489]
Hey!

I could have missed it, but is there any way to get the port number the server listens on when I start it on port 0?

My use case would be: running a normal http server on port 80, which would sometimes spawn another http servers but on port 0. In those spawned servers I would like to get the actual tcp port they're listening on (and then save it to the database or whatever...)

**Comment by ooesili** [comment]
You cannot access the port number that gets chosen when you use `Engine.Run`. However, you can access the port number if you create the listener yourself:

```go
r := gin.Default()
r.GET("/", func(c *gin.Context) {
	c.String(200, "Hello, world!")
})

ln, _ := net.Listen("tcp", ":0")

_, port, _ := net.SplitHostPort(ln.Addr().String)
fmt.Println("Listening on port", port)

http.Serve(ln, r)
```
