### ISSUE TITLE
A better way to send an error as JSON/XML, canceling next handlers

### ISSUE THREAD

**Issue by patrickdappollonio** [gin-gonic/gin#49]
I've been trying naively to send a 400 http status code with a JSON message in it, adding proper headers as "application/json" and a body with a proper error message. The first thing I thought was using `c.JSON(400, gin.H{"error": "error here"})` but if this appears in a middleware, and there are new handlers or middlewares following up, I receive `http: multiple response.WriteHeader calls` from the logs.

I assume the problem is that actually there's nothing underlying preventing to execute next middlewares / handlers if I send an error. I've checked the `auth.go` file with the basic auth middleware but that's only sending a 401 header, with no body at all.

So I've ended up doing this:

``` go
c.Writer.Header().Add("Content-Type", "application/json")
c.Fail(404, errors.New(errorMessage))
c.JSON(-1, gin.H{"error": errorMessage})
```

So I append first the proper JSON header, then calling fail (so, underlying the function properly cancels all the subsequent middlewares / handlers) and then, after a quick check to the JSON method, I've seen that if the header is 0 or up, the header gets added, but since I've already added one on `c.Fail()` I don't want a new one, so I pass `-1`.

Is there a proper way to send this? I mean, there's a shorthand for proper JSON responses but nothing that actually ends the subsequent middlewares even if I want to send a response body there.

**Comment by pkopac** [comment]
Hi! Please, could you mention this on the README.md, at least in one example? That would spare others searching in discussions for how to handle errors in gin. Thank you.
PS: nice framework!

**Comment by fabulousduck** [comment]
Currently i ama getting `type *gin.Context has no field or method Fail)` 
I have attached the error logger like so
`router.Use(gin.ErrorLogger(gin.ErrorTypeExternal))`

Was this feature removed or am i doing something wrong ?

**Comment by abdennour** [comment]
c.Fail undefined (type *gin.Context has no field or method Fail)
