### ISSUE TITLE
Error restoring dep of go-colorable with godep v35

### ISSUE THREAD

**Issue by moret** [gin-gonic/gin#496]
Hi. Yesterday there was a new release of [godep](https://github.com/tools/godep/releases/tag/v35). When running `godep restore` in gin with the new version on a Mac an error is thrown while restoring one of the projects dependencies in [go-colorable](https://github.com/mattn/go-colorable):
```
~ $ cd $GOPATH
goworkspace $ go get -u github.com/gin-gonic/gin
goworkspace $ cd src/github.com/gin-gonic/gin/
gin $ godep restore
godep: error restoring dep (github.com/mattn/go-colorable): Unable to find dependent package github.com/mattn/go-isatty in context of /<redacted>/goworkspace/src/github.com/mattn/go-colorable
gin $ godep version
godep v35 (darwin/amd64/go1.5.1)
gin $
```

**Comment by mbmc** [comment]
You might need to add the package
```go get github.com/mattn/go-isatty```
In my case, I also had to get
```go get golang.org/x/sys/unix```

**Comment by 178inaba** [comment]
Hello.
I was fixed this.
#500

**Comment by moret** [comment]
@178inaba LGTM

**Comment by manucorporat** [comment]
@moret this issue was already fixed. thanks for your help!
