### ISSUE TITLE
Add NYTimes/gizmo to benchmarks

### ISSUE THREAD

**Issue by robzienert** [gin-gonic/gin#503]
I'd be very interested to see the benchmark results of Gizmo as it compares to gin.

**Comment by mpmlj** [comment]
+1. Gizmo looks like a pretty solid project and an interesting alternative.

**Comment by techjanitor** [comment]
as far as i can tell gizmo just uses gorilla mux, which is already in the benchmarks:
https://github.com/NYTimes/gizmo/blob/master/web/func.go
