### ISSUE TITLE
c.JSON returns HTTP 500 - no stack trace

### ISSUE THREAD

**Issue by matejkramny** [gin-gonic/gin#505]
## Background

using `gin.Default()` and go 1.5

Code:

```
func (c *gin.Context) {
  // end up with NaN
  c.JSON(200, map[string]interface{}{
    "some": math.NaN(),
  })
}
```

## Whats happening
`json.Marshal` cannot marshal a `NaN` value. I happened to end up with `NaN` somehow and spent a long time debugging what was going on with the code, why the error wasn't being reported etc.

Note that gin tried to marshal the value and failed, however didn't print out the error message only returned HTTP 500 back.

## What should be happening

Cause panic() but be it caught via `gin.Recovery()`

The error isn't that I have NaN somewhere in the input but that the error from `json.Marshal` not being handled properly.

**Comment by bwiggs** [comment]
+1 Just got bit by this.

**Comment by manucorporat** [comment]
I just tried it and I got this:
```go
[GIN-debug] [ERROR] json: unsupported value: NaN
[GIN] 2016/01/26 - 16:05:18 | 500 |     135.619µs | ::1 |   GET     /
```

**Comment by manucorporat** [comment]
ok, I think I understand what you mean...
you probably be right... any rendering error should be propagated as a panic.

**Comment by manucorporat** [comment]
@bwiggs @matejkramny 
Now a render error throws a panic
(I also made the Recovery middleware to print the panic in red, so it can be debugged visually easier)
<img width="748" alt="screen shot 2016-01-26 at 17 46 59" src="https://cloud.githubusercontent.com/assets/127379/12587508/fa2fc6c8-c454-11e5-8698-a6b6a23bce57.png">

**Comment by manucorporat** [comment]
Fixed: https://github.com/gin-gonic/gin/commit/2fc2a3e7827d9033f00425eef78ec9f47d08ebf6
https://github.com/gin-gonic/gin/commit/7afb3238a3b703864c785ce626e0c7330a9c559b

**Comment by matejkramny** [comment]
Awesome :+1:
