### ISSUE TITLE
engine.Routes() -- Custom function names (need for swagger package)

### ISSUE THREAD

**Issue by loopfz** [gin-gonic/gin#506]
Writing a package that generates swagger spec using engine.Routes() and reflection, I encountered a fairly specific issue:
All gin.HandlerFunc that are closures will have the same name, not letting me distinguish between them.

Would it be possible to have a Setter to configure custom names for certain gin.HandlerFunc, letting me override runtime.FuncForPC(...).Name() in gin.nameOfFunction() ?

**Comment by thinkerou** [comment]
#1272 merged
