### ISSUE TITLE
Catching panics

### ISSUE THREAD

**Issue by joeblew99** [gin-gonic/gin#507]
I am wondering the best way to ensure the DAE.on does not go down.
1. Error handling on each e try route ?
2. Gin-sentry to catch and send to sentry. The gin-sentry repo has zero info on how to integrate into gin.
3. Restart on fail ?

Thanks..

**Comment by joeybloggs** [comment]
It looks like gin-sentry just has a single function that returns a gin.HandlerFunc which then can just be used as middleware

Call this function https://github.com/gin-gonic/gin-sentry/blob/master/recovery.go#L12 and use as any other middleware, but recommend adding the middleware right after any logging middleware to ensure the request gets logged even if it fails.
