### ISSUE TITLE
image upload via api

### ISSUE THREAD

**Issue by rmenn** [gin-gonic/gin#508]
Folks, 

I was just wondering if there was a way to upload images *not* using the form, i just have an api which is required upload an image. 

I have check around all of them seem to be a form upload.

**Comment by iwanbk** [comment]
@rmenn 
In client side, you can encode the image to base64, and then decode it in server.

**Comment by windyzboy** [comment]
@rmenn You can use `c.Request` to get `*http.Request` then get file from Multipart Form
https://golang.org/pkg/net/http/#Request.FormFile

**Comment by nazwa** [comment]
Or use websockets or raw upload! Possibilities are endless :+1:

**Comment by mpmlj** [comment]
@rmenn 
1. Send it as base64 with a form to your API, as @iwanbk mentioned above
2. Use imageFull := c.PostForm("imageFull") to get its body inside your API's controller
3. For example, save locally doing
str, err := util.DecodeBase64Image(imageFull)
...
b64data := str[strings.IndexByte(str, ',') + 1:]
data, err := base64.StdEncoding.DecodeString(b64data)
...
r := string(data)
...
ioutil.WriteFile("/tmp/" + filename, []byte(r), 0644)
...
etc...

Hope it helps,
D.

**Comment by manucorporat** [comment]
@rmenn or just using drop the raw binary image data, and read it from `c.Request.Body`.
