### ISSUE TITLE
After app shutdown port is not released

### ISSUE THREAD

**Issue by pavlik** [gin-gonic/gin#510]
If I start my web app it starts on port 9000. Then if I stop server (for example by pressing CTRL+Z), server stopped, but port is not released. Why this happened?

My app: https://github.com/pavlik/mimozaflowers/blob/master/server.go#L353

**Comment by kaelliu** [comment]
ctrl + z will stop program and hung it up,but ctrl + c will kill the process,try ctrl + c

**Comment by dolmen** [comment]
Confirming @kaelliu 's anwser.
This issue can be closed as invalid.
