### ISSUE TITLE
Support YAML for binding and rendering

### ISSUE THREAD

**Issue by jacek99** [gin-gonic/gin#514]
I love the fact that the Bind function can use Form or JSON depending on the content type header.

If would be great if it could support YAML as well (for input) and provide the eqivalent

    c.YAML(...)

methods, equivalent to what is there for JSON.

For some payloads, it can result in a noticeably smaller size on the wire (compared to JSON).

**Comment by javierprovecho** [comment]
@jacek99, I just took @bobbo code from (bobbo@b4f0b50) and merged in 007bd51

BTW, thanks @austinheap for marking this and many other issues :wink:

**Comment by appleboy** [comment]
Nice feature.
