### ISSUE TITLE
How to check abnormal disconnection when huge file is uploading to the GIN server. 

### ISSUE THREAD

**Issue by MyungjinJung** [gin-gonic/gin#515]
I've coded the Formfile upload-end point with GIN framework and it was nice work. 
however, I couldn't check up that client's browser being turned off also  defers  doesn't work.
I want to check this signal , function , something like that. 

Could you recommend me nice solution about this case of abnormal disconnection. ?

**Comment by manucorporat** [comment]
@MyungjinJung what is the size of the file? can you post some code you are using?

**Comment by MyungjinJung** [comment]
``` sh 
///  main code is that... 
handler := handles.NewSegmentUploadHandler(conf config)
gMux := gin.Default()
v1 := gMux.Group("api/v1")
{
		v1.POST("/CreateUploadSession/:expTime/:uploadType", handler.CreateUploadSession)
}


/// handler class 
func (up *UploadHandler)UploadMultiParts(c *gin.Context) {
  defer func(){ 
   fmt.print(" it does not work despite when http connection be closed from clients ")
 }()
}
```
Size was 30 to 40 mb ,
When user was losing the connection physically ,  the function of defer-er doesn't work at the "UploadMultiParts" block. 

thanks ., @manucorporat

**Comment by javierprovecho** [comment]
@MyungjinJung you can try to use this inside your handler:

```go
...
		notify := c.Writer.CloseNotify()

		go func() {
			<-notify
			fmt.Println("HTTP connection just closed.")
		}()
...
```

`c.Writer.CloseNotify()` is a channel from where you will receive a bool when the connection close. You can read more information about it here (https://golang.org/src/net/http/server.go#L111).

**Comment by itmoss** [comment]
@javierprovecho thanks for your great comment ,  I will try to code with that
