### ISSUE TITLE
Allow content-type to be changed when using c.JSON()

### ISSUE THREAD

**Issue by basco-johnkevin** [gin-gonic/gin#517]
We're using jsonapi spec - http://jsonapi.org/ and we need to use `application/vnd.api+json` as the content-type. Would be great if gin allows content-type to be changed when using c.JSON().

**Comment by manucorporat** [comment]
@basco-johnkevin it can be done:

```go
c.Header("Content-Type", "application/vnd.api+json")
c.JSON(200, data)
```
