### ISSUE TITLE
 App engine example fails to build. Bad import "syscall" in colorable_windows.go from GOPATH

### ISSUE THREAD

**Issue by jgidlow** [gin-gonic/gin#518]
If I try to run the app engine example using "goapp serve" the build fails with the following error:

```ERROR    2016-01-26 17:17:52,160 go_runtime.py:179] Failed to build Go application: (Executed command: C:\Program Files\Google\go_appengine\goroot\bin\go-app-builder.exe -app_base D:\Code\Go\gopath\src\app_engine\gin-example -arch 6 -dynamic -goroot C:\Program Files\Google\go_appengine\goroot -nobuild_files ^^$ -unsafe -gopath D:\Code\Go\gopath\ -print_extras_hash hello.go)```

```2016/01/26 17:17:52 go-app-builder: Failed parsing input: parser: bad import "syscall" in colorable_windows.go from GOPATH```

I think this error happens because one of the gin dependencies (go-colorable) is importing the syscall package which isn't allowed on App Engine?

I'm using go_appengine_sdk_windows_amd64-1.9.31 and Gin 1.0rc2.

**Comment by manucorporat** [comment]
@jgidlow  fixed: https://github.com/gin-gonic/gin/commit/60f66918f8a68dc817665cc7a38ba380d00a297c
