### ISSUE TITLE
Redirect should also accept 201 Created status code

### ISSUE THREAD

**Issue by jonhoo** [gin-gonic/gin#521]
According to [the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2):

> The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field.

Seems like a pretty good candidate for `c.Redirect` to me?

**Comment by manucorporat** [comment]
@jonhoo can you provide a valid URL to the spec please?

**Comment by austinheap** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html section 10.2.2

**Comment by jonhoo** [comment]
Sorry about that -- don't know what happened there. Fixed.

**Comment by manucorporat** [comment]
@jonhoo thanks! already fixed in develop branch: https://github.com/gin-gonic/gin/commit/97cd89427998b28491443b09649dc89aca1255bb

**Comment by jonhoo** [comment]
Nice! Thanks!
