### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by tigranbs** [gin-gonic/gin#522]
Hi I'm doing REST service as a separate part of big web application, it's great to write simple things on this, but now we have issue with handling sessions ....
Is it possible to implement it with <code>gin</code> ?

**Comment by Taik** [comment]
Have you looked at https://github.com/gin-gonic/contrib/tree/master/sessions? Seems like its what you're looking for.

**Comment by tigranbs** [comment]
oops sorry for stupid question !
Yes that's it

**Comment by haitgo** [comment]
great, I need this
