### ISSUE TITLE
go-socket.io

### ISSUE THREAD

**Issue by LicaSterian** [gin-gonic/gin#524]
Can anyone help setting up a server that also handles web-socket with gin?
Preferably I would like to use [github.com/googollee/go-socket.io](url)

Thanks.

**Comment by nazwa** [comment]
I don't have the code anymore but the way it worked was that you set up gin and socket.io as usual (https://github.com/googollee/go-socket.io#example) and then just map the socket handler to a gin handler

```
r.GET("/socket.io/", gin.WrapH(server))
```

That's it

**Comment by LicaSterian** [comment]
Thank's. I didn't know the `gin.WrapH` method part.

**Comment by c9s** [comment]
gin.WrapH is not a type

**Comment by c9s** [comment]
And gin doesn't work with github.com/googollee/go-socket.io

Tested:  go-socket.io + HTTP / HTTPS works pretty fine

Here is the error message I got when integrating gin with go-socket.io

```
WebSocket connection to 'wss://localhost:9096/socket.io/?EIO=3&transport=websocket&sid=95lAIzu8kRVD-ZwzHEjn' failed: Error during WebSocket handshake: Unexpected response code: 403
```

**Comment by javierprovecho** [comment]
@c9s check https://godoc.org/github.com/gin-gonic/gin#WrapF and https://godoc.org/github.com/gin-gonic/gin#WrapH

can you post an example code for that failure?

**Comment by doquangtan** [comment]
Use can use this lib [socket.io golang](https://github.com/doquangtan/socket.io-golang). It is socketio server version 4.x and it can using with client version 3.x, 4.x

```go
import (
	"github.com/gin-gonic/gin"
	socketio "github.com/doquangtan/socket.io/v4"
)

func main() {
	io := socketio.New()

	io.OnConnection(func(socket *socketio.Socket) {
		// ...
	})

	router := gin.Default()
	router.GET("/socket.io/", gin.WrapH(io.HttpHandler()))
	router.Run(":3300")
}
```
