### ISSUE TITLE
is master branch stable?

### ISSUE THREAD

**Issue by matejkramny** [gin-gonic/gin#527]
I just want to ask about your workflow, since I'm using `1.0rc1`, whether things committed to `master` are considered production-ready.

Keep up the awesome work :+1: :). Doing great!

**Comment by javierprovecho** [comment]
Hey @matejkramny ,

We always try to keep master bug-free. Same goes to develop, plus to be buildable. But most of Gin's followers use default branch (master) without problems. A merge from develop into master will be done soon. Also check @manucorporat 's new roadmap facing Gin v2 here: https://github.com/gin-gonic/gin/issues/523

Close this issue if I solved your doubts. And keep an eye on the project, good things are coming.

**Comment by matejkramny** [comment]
Cool thats good.

Thanks :)
