### ISSUE TITLE
How to set options in Session/cookies

### ISSUE THREAD

**Issue by no1youknowz** [gin-gonic/gin#534]
Trying something like this and other things.

```
options := sessions.Options{
    Path:     "/",
    Domain:   "www.foodev.com",
    MaxAge:   0,
    Secure:   false,
    HttpOnly: false,
}

sessions.Session.Options(options)
```

Getting

```
 not enough arguments in call to method expression "github.com/gin-gonic/contrib/sessions".Session.Options
```

Would be nice if in the readme/examples, it shows how to supplement these options.

Thanks

**Comment by mvader** [comment]
`sessions.Session` is a type, i think

`sessions.Default(ctx).Options(options)`

**Comment by no1youknowz** [comment]
> sessions.Default(ctx).Options(options)

How do I set "options" though?  What is the type?

**Comment by egag** [comment]
```
sessions.Default(c)
```
returns a sessions.Session
```
sessions.Session.Options(sessions.Options)
```
returns nothing.

Old question, please close.
