### ISSUE TITLE
Adding support for regular expressions based routing?

### ISSUE THREAD

**Issue by tsirolnik** [gin-gonic/gin#540]
Hey, so, first of all, I really love this framework. But,I've thought that adding a support for regex based routing would be really awesome.
Revel has support so maybe using their code would be an option?

**Comment by shawnye** [comment]
+1

**Comment by appleboy** [comment]
I think you need to post question in https://github.com/julienschmidt/httprouter

**Comment by kamronbatman** [comment]
@tsirolnik I think the consensus from what I have read on httprouter is to make middleware to do it for you.  The idea being that the performance hit for implicit regex is not worth it.
