### ISSUE TITLE
Binding POST request for "field[]" and "field"

### ISSUE THREAD

**Issue by RomanMinkin** [gin-gonic/gin#541]
Hi there,

any suggestions on how to bind `POST` requests like:

```
?names[]=foo&names[]=bar
```
and
```
?names=foo&names=bar
```

to 

```go
type Record struct {
	Names []string `json:"names" form:"names"`
}
```

I tried to use `json:"names[]" form:"names[]"`, but then it breaks `application/json`, `application/x-www-form-urlencoded`, etc.

Would appreciate any help and thanks in advance!

**Comment by tsirolnik** [comment]
What do you mean by  breaks application/json, application/x-www-form-urlencoded?

**Comment by appleboy** [comment]
Please refer: https://github.com/gin-gonic/gin/issues/466
