### ISSUE TITLE
does the `json:"-"` tag work when using c.JSON()?

### ISSUE THREAD

**Issue by thinkong** [gin-gonic/gin#544]
Hi 
I wanted to omit some parts of the struct when sending responces... but the `json` tag doesn't seem to work ..

Could it be something I did wrong?

My struct is a very deeply nested struct with pointers to other structs (no circular stuff)
`json:"-"`
`json:"someothername"` 
all seem to not work...

any help would be great

**Comment by ChasingLogic** [comment]
Have you tested marshalling the struct directly yourself to verify it's correct? c.JSON() just uses the stdlib JSON encoder (which in turn uses the Marshal function) so the tag should be working and do work for my code. However I'm not deeply nesting structs.

**Comment by javierprovecho** [comment]
The json tag is not defined by gin, but by `encoding/json` and now (master branch), `github.com/json-iterator/go`. Maybe your struct attributes are not exported, and not visible to the json encoder. Check https://golang.org/ref/spec#Exported_identifiers for more information.
