### ISSUE TITLE
Retry middleware

### ISSUE THREAD

**Issue by arvenil** [gin-gonic/gin#546]
I wonder if it is possible to retry handler execution, something like this:

``` go
func Retry() gin.HandlerFunc {
    return func(c *gin.Context) {
        c.Next()
        if c.IsAborted() {
            c.Index-- // or some other magical function to reset index to previous handler
            c.Next() // or just some generic function c.Retry()
        }
    }
}
```

**Comment by arvenil** [comment]
Well... after looking at source code of `IsAborted` which is `c.index = abortIndex` I don't thing so:/

**Comment by kamronbatman** [comment]
What are you trying to retry? If its custom middleware, then you could wrap it and retry it manually.
If you are trying to retry a complete chain, then I doubt it is possible without exposure to the chain itself so you could slice it and retry it manually.
