### ISSUE TITLE
Typo in gin_test.go ?

### ISSUE THREAD

**Issue by AlbinOS** [gin-gonic/gin#550]
Is there something wrong with the following assert line (see [gin_test.go](https://github.com/gin-gonic/gin/blob/develop/gin_test.go#L247)) : `assert.Regexp(t, wantRoute.Path, gotRoute.Path)` ?

As you already test the Path attribute [just above](https://github.com/gin-gonic/gin/blob/develop/gin_test.go#L246), I was wondering that you wanted to do something like `assert.Regexp(t, wantRoute.Handler, gotRoute.Handler)` instead. Is it correct ?

I was about to submit a PR but I wanted to check with you first.

**Comment by javierprovecho** [comment]
@AlbinOS yes, I think you are right! However, let me check this with the one who wrote this test.

Anyway, it doesn't make sense to compare twice the same variables.

Thank you for noticing this.

**Comment by AlbinOS** [comment]
@javierprovecho, you're welcome ! 

Can I submit a pull request for this ?

**Comment by appleboy** [comment]
@AlbinOS go ahead.
