### ISSUE TITLE
Bind form-data request with nested structures

### ISSUE THREAD

**Issue by Ganitzsh** [gin-gonic/gin#551]
Hi,

I have an struct `StructA` which contains another struct `StructB` as an attribute, like this:

``` go
type StructB struct {
    FieldB string  `form:"fieldB"`
}

type StructA struct {
    NestedStruct *StructB
    FieldA string `form:"fieldA"`
    ...
}
```

In my handler I'm `Bind`ing the request content to an `StructA` object:

``` go
func MyHandler(c *gin.Context) {
    var tmp StructA
    ...
    c.Bind(&tmp)
    ...
}
```

My form contains the field `fieldA` as well as `fieldB`, but `NestedStruct` stays `<nil>` after the `Bind` call.
Is manual binding the only way to achieve this at the time? Or am I missing something?

Thanks

**Comment by misekm** [comment]
Please is there any solution for this? I would like to use nested structs too. Thanks.

**Comment by Ganitzsh** [comment]
I found a trick, using reflection, you can wrap the B

**Comment by misekm** [comment]
Could you please show any sample code?

**Comment by qw4n7y** [comment]
any progress?

**Comment by thinkerou** [comment]
Hi @Ganitzsh , gin supports the follow not POINTER:

    type StructB struct {
        FieldB string  `form:"fieldB"`
    }

    type StructA struct {
        NestedStruct StructB // NOT POINTER <-------- here
        FieldA string `form:"fieldA"`
        // ...
    }

I will think about support POINTER, thanks.

**Comment by appleboy** [comment]
See the readme: https://github.com/gin-gonic/gin#bind-form-data-request-with-custom-struct

**Comment by nicolasvasquez** [comment]
I think that assign multiple names for diferent nested struct is tedius. For example:

`
type StructB struct {
    FieldB string  `form:"fieldB"`
}
`

**Comment by nicolasvasquez** [comment]
I think that assign multiple names for different nested struct is tedious. For example:

```
type StructB struct {
    Id  int  `form:"structb_id" json:"id"`
    Name  string  `form:"structb_name"  json:"name"`
}
type StructA struct {
    Id  string  `form:"structa_id" json:"id"`
    Name  string  `form:"structa_name" json:"name"`
    NestedStruct *StructB `form:"fieldB" json:"structb"`
}
```

The json bind for nested struct is more easily than form way. Is possible work with form as the json way and send only like `structb.name` for assign the name of the second struct??
