### ISSUE TITLE
Is it possible to cache a route?

### ISSUE THREAD

**Issue by hryamzik** [gin-gonic/gin#552]
Let's say I have a route that selects the \* from the database. I would like to limit amount of selections per second by caching results. I didn't find anything about cache in API docs though.

**Comment by nazwa** [comment]
You could write a small middleware that caches the response. There is one in gin-contrib already, but I don't think it works with current version of gin. But I'm sure you  can use it as inspiration.

**Comment by hryamzik** [comment]
@nazwa did anything change during last months? I can see some new commits in contrib/cache.

**Comment by nazwa** [comment]
@hryamzik I've been slightly out of touch with the project over the last month, but I know the guys have been working hard to improve things. Not sure about the middleware itself - give it a go :)

**Comment by appleboy** [comment]
@hryamzik Try https://github.com/gin-contrib/cache

**Comment by hryamzik** [comment]
@appleboy thanks! Readme example is broken there but [example.go](gin-contrib/cache/blob/master/example/example.go) seem to work. Except it always gives me current time on `/cache_ping` but I didn't investigate it yet.

**Comment by appleboy** [comment]
@hryamzik I will fix example on readme. Thanks for your friendly reminder.

**Comment by appleboy** [comment]
@hryamzik I fixed example and some wrong import path, please update your local cache package. See the detail: https://github.com/gin-contrib/cache/commit/8d033917bb5125d42c2db342c0198e6d19e28668
