### ISSUE TITLE
How to get all routes registered at runtime?

### ISSUE THREAD

**Issue by xpbliss** [gin-gonic/gin#569]
How to get all routes registered at runtime?

**Comment by widnyana** [comment]
first, I will [define](https://github.com/widnyana/gallang/blob/master/router.go#L17) all the route, then [register](https://github.com/widnyana/gallang/blob/master/boot.go#L34) all defined route, with this route registration [func](https://github.com/widnyana/gallang/blob/master/boot.go#L45)

did you look for something like that, @xpbliss ?

**Comment by xpbliss** [comment]
good!

**Comment by javierprovecho** [comment]
@widnyana thank you!

@xpbliss reopen if you had any more questions about this.

**Comment by adrian-moisa** [comment]
Any answer for this question?

**Comment by abrar71** [comment]
You can all the routes using `router.Routes()` and loop through the array to get `.Method` and `.Path` of each registered route

```go
for _, item := range router.Routes() {
	println("method:", item.Method, "path:", item.Path)
}
```
