### ISSUE TITLE
The example in readme invalid now

### ISSUE THREAD

**Issue by daxzhuo** [gin-gonic/gin#573]
I found that the PostForm() function has changed to PostFormValue(), also the same problem with  DefaultPostFormValue(), please update it in the readme file, it is confused.
![screenshot from 2016-04-01 13-06-47](https://cloud.githubusercontent.com/assets/7886167/14198266/a8c2f582-f80a-11e5-99e6-48cc10199f24.png)

**Comment by appleboy** [comment]
`PostForm`: https://github.com/gin-gonic/gin/blob/develop/context.go#L241
`DefaultPostForm`: https://github.com/gin-gonic/gin/blob/develop/context.go#L249

Please closed this issue.

**Comment by daxzhuo** [comment]
Sorry, my gin version is outdated.
