### ISSUE TITLE
Token based user authentication?

### ISSUE THREAD

**Issue by samphp90** [gin-gonic/gin#582]

**Comment by appleboy** [comment]
hi @samphp90 I think you can try [gin-jwt](https://github.com/appleboy/gin-jwt) middleware.

**Comment by javierprovecho** [comment]
@samphp90 checkout [gin-gonic/contrib](https://github.com/gin-gonic/contrib) where you can find lots of middlewares, some internal, and some external like @appleboy's [gin-jwt](https://github.com/appleboy/gin-jwt)

**Comment by samphp90** [comment]
Thanks this will help me. 💸

On Sat, Apr 9, 2016 at 4:21 PM, Javier Provecho Fernandez <
notifications@github.com> wrote:

> Closed #582 <https://github.com/gin-gonic/gin/issues/582>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gin-gonic/gin/issues/582#event-621051774>
>



-- 

*Thank You*

*Regards*
*Sameer Bele*

*+91 9886271494*

*Skype : sameerbele90*
