### ISSUE TITLE
[question] is that possible to use subtemplate in Gin?

### ISSUE THREAD

**Issue by uzmo** [gin-gonic/gin#583]
Hi there,

Is that possible to use subtemplate in Gin? For example,  decomposing one single page into main.html, header.html and footer.html for reuse. Any example?

BR, Kevin

**Comment by ilgaleanos** [comment]
Yes, in main:
``` go
func main() {
    r := gin.Default()
    // ...
     r.LoadHTMLGlob("templates/*")
    // ...
     r.Run() // listen and server on 0.0.0.0:8080
}
```
Template "A.html":

```html
<p>I'm a string</p>
```

in template "B.html":

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Demo</title>
	</head>
	<body>
		{{ template "A.html" }}
	</body>
</html>
```
if you call render in a function c.HTML(200, "B.html", "" ) output is:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Demo</title>
	</head>
	<body>
		<p>I'm a string</p>
	</body>
</html>
```
both A.html and B.html  are in the same folder "templates". If you need many folders, use " r.LoadHTMLGlob("templates/**/*")"

More info https://github.com/gin-gonic/contrib/tree/master/renders/multitemplate

**Comment by im7mortal** [comment]
Maybe it related with that issue #567 
Check go 1.6 "block" template feature. I think you want it.

**Comment by uzmo** [comment]
@ilgaleanos Thanks for the clarification.  Is that possible load templates structured as below?
templates/B.html
templates/sub/A.html
I tried, but failed.

BR, Kevin

**Comment by ilgaleanos** [comment]
I'm not know how do this but, if you need structure your templates easy way is: 
```go
r.LoadHTMLGlob("templates/**/*")
```
```text
|------templates
             |----sub1
                     |-----A.html
                     |-----layout.html
             |-----sub2
                     |-----B.html
                     |-----index.html
             |-----(not html here only folders)
                     |-----(not folder here only html)
```
gin see both A, B and layout for render. you should read #567 for best approach.

**Comment by im7mortal** [comment]
@ilgaleanos, @uzmo I found solution.
There are [a multitemplate render for gin](https://github.com/gin-gonic/contrib/tree/master/renders/multitemplate)

You need to combine the render and the blocks feature. Check examples there!

**Comment by appleboy** [comment]
New repo link: https://github.com/gin-contrib/multitemplate
