### ISSUE TITLE
context.AbortWithStatus() fails to write response header

### ISSUE THREAD

**Issue by roylou** [gin-gonic/gin#585]
If you call c.AbortWithStatus(400), it calls responseWriter.WriteHeader() and sets writer's status code. This however won't be written into response header because responseWriter.WriteHeaderNow() is not invoked. As a result you'll see 200 in response code.

The fix should be easy: let c.AbortWithStatus() call c.String() instead of s.Status(). I can submit a pull request if it sounds good to you.

**Comment by appleboy** [comment]
@roylou You can submit the pull request and update unit testing.
