### ISSUE TITLE
Content negotiation

### ISSUE THREAD

**Issue by alexandernyquist** [gin-gonic/gin#59]
My application will serve an API that is available via JSON and XML. There is currently not a convenient way of doing this in Gin. As it is now, I end up with a bunch of switch-cases.

What do you guys say about supporting (maybe a basic implementation) content negotiation (conneg)[0]? 

The most simple API could look something like this:

	r.GET("/ping", func(c *gin.Context) {
	    c.Negotiate(200, Response{foo: "Bar"})
	})

The response format is then inferred from the Accept-header.

We could also implement a mechanism to try and infer what to return based on URL parameters (`/api/?format=xml/json`) or file endings (`api.json/xml`).

Is this something you guys want to move forward with? If so, let me know and I'll implement it.

[0] http://en.wikipedia.org/wiki/Content_negotiation

**Comment by phisco** [comment]
I think it could be useful to allow extensions to the Negotiate method, because for example the default being an error could not be the best option for everyone, but as it is it is not possible to modify it, without modifying the library code.

**Comment by jarrodhroberson** [comment]
Is there a way to register a renderer for a custom MediaType?

I want to use something like `application/vnd.myapp.person.json;version=1.0.0` as the "preferred" json format and `application/json` as a fallback.

**Comment by Athosone** [comment]
@jarrodhroberson did you find a way to achieve mediatype versionning?

**Comment by arthurlaveau** [comment]
@Athosone about you ? Did you find a way to achieve it ?

**Comment by Athosone** [comment]
@arthurlaveau I did,

I wrote a library to solve the issue. It works with the base go net package.
It works natively with gorilla mux and go-chi.
it could work with gin gonic with a little effort. If you want to contribute feel free
Check the example: https://github.com/Athosone/golib/tree/main/examples/media-type-versioning
