### ISSUE TITLE
AbortWithStatus doesn't work

### ISSUE THREAD

**Issue by Virviil** [gin-gonic/gin#595]
Probably I don't understand, how this should work, but still.

I have error checking in Handler function. And if I make:
```go
if err != nil {
    panic("500")
}
```

Everithing works proper - 500 code response and panic trace in terminal

If I use:
```go
if err != nil {
    c.AbortWithStatus(500)
}
```
nothing happens. I get 200 response with null.

Mb, thats because at the end I use 
```go
c.JSON(http.StatusOK, u)
```
?

But still, this should not be conflicted, as I understand.

Update:
This works as needed:
```go
if err != nil {
    c.AbortWithStatus(500)
    return
}
c.JSON(http.StatusOK, u)
```

**Comment by appleboy** [comment]
Please closed this issue.
