### ISSUE TITLE
http connections stuck in close_wait state

### ISSUE THREAD

**Issue by shimron** [gin-gonic/gin#596]
I'm using gin to build a simple api server. right now, after the server started a few minutes later, all of incoming requests were stuck. After checking connections state , I got a message like below :
![image](https://cloud.githubusercontent.com/assets/5574178/14666642/632b0b2e-070d-11e6-91f7-3fabbf373f65.png)

I already have tried to set c.Request.Close=true or c.Header("Connection","close") or both of them, but it was not working. I was wondering if anyone can help me fix this issue.

**Comment by shimron** [comment]
set header connection:keep-alive, that works for me

**Comment by nep-0** [comment]
@shimron How did you solve this?
Is it convenient to you share?

**Comment by huanshengHe** [comment]
@nep-0 Did you find out how to solve this? I had the same problem

**Comment by nep-0** [comment]
@huanshengHe Sure. There was a bug in my code, a deadlock. I fixed my bug and then there was no problem.
