### ISSUE TITLE
why below code always return {}

### ISSUE THREAD

**Issue by nihao** [gin-gonic/gin#597]
`package main

import (
	//"log"
	//"encoding/json"
	"github.com/gin-gonic/gin"

)

type Job struct {
	protocol	string		`json:"protocol"`
	job_id		string		`json:"job_id"`
	targets		[]string	`json:"targets"`
}

type Jobs struct {
	error 		int		`json:"error"`
	ip			string	`json:"ip"`
	jobs		[]Job	`json:"jobs"`
}

func JobsHandler(c *gin.Context) {
	rtnBody := &Jobs{
					error: 	0,
					ip:		"10.197.1.58",
					jobs:	[]Job{
									{	
										protocol: 	"icmp",
										job_id:		"sdfsdf132434",
										targets:	[]string{
											"8.8.8.8",
											"8.8.4.4",
										},
									},
									{
										protocol:	"http",
										job_id:		"s2323143455",
										targets:	[]string{
											"www.baidu.com",
											"www.qq.com",
										},
									},
								},
							}
	
		c.JSON(200, *rtnBody)

}

func main() {
	r := gin.Default()
	r.GET("/jobs", JobsHandler)
	r.Run()
}
`

get http://127.0.0.1/jobs return {}, not the rtnBody, anyone help to check, thanks

**Comment by appleboy** [comment]
```go
package main

import (
	"github.com/gin-gonic/gin"
	// "log"
)

type Job struct {
	Protocol string   `json:"protocol"`
	JobId    string   `json:"job_id"`
	Targets  []string `json:"targets"`
}

type Jobs struct {
	Test int    `json:"test"`
	Ip   string `json:"ip"`
	Jobs []Job  `json:"jobs"`
}

func JobsHandler(c *gin.Context) {
	rtnBody := Jobs{
		Test: 0,
		Ip:   "10.197.1.58",
		Jobs: []Job{
			{

				Protocol: "icmp",
				JobId:    "sdfsdf132434",
				Targets: []string{
					"8.8.8.8",
					"8.8.4.4",
				},
			},
			{
				Protocol: "http",
				JobId:    "s2323143455",
				Targets: []string{
					"www.baidu.com",
					"www.qq.com",
				},
			},
		},
	}

	c.JSON(200, rtnBody)
}

func main() {
	r := gin.Default()
	r.GET("/jobs", JobsHandler)
	r.Run()
}
```

**Comment by nihao** [comment]
thanks @appleboy , why it must uppercase the first character ?

**Comment by appleboy** [comment]
Please see the [detail explanation](http://stackoverflow.com/questions/21825322/why-golang-cannot-generate-json-from-struct-with-front-lowercase-character)

**Comment by nihao** [comment]
tha
