### ISSUE TITLE
Document how to disable the request log

### ISSUE THREAD

**Issue by jacek99** [gin-gonic/gin#598]
Even with GIN_MODE=release, gin still prints the full request log to console, which can seriously slow down performance.

We've had to disable it temporarily during performance testing by redirecting it to /dev/null.

Please document how to properly enable/disable the request log.

Thank you

**Comment by kokaz** [comment]
Do you use `gin.Default()` ? If so you have to use `gin.New()` and add the recovery middleware (if you still want it) because `gin.Default()` add the Logger and Recovery middleware.

**Comment by jacek99** [comment]
Ah, I see. It's probably worth documenting that to be more explicit.

Thank you for the explanation.

**Comment by mishak87** [comment]
It is documented in [README](https://github.com/gin-gonic/gin#blank-gin-without-middleware-by-default).

**Comment by aequasi** [comment]
Thats not documented very well. That doesnt explain what the logger or recovery middleware are.

**Comment by appleboy** [comment]
See the PR https://github.com/gin-gonic/gin/pull/1056 improve the document.

**Comment by ldelossa** [comment]
@zirkome Even using Default() still prints out pretty verbose message when using it in  unit tests. Maybe I am doing something wrong ?

**Comment by zirkome** [comment]
@ldelossa That's the thing the `gin.Default()` function **includes** a logger by default. If you want to control the logging you should use a custom Gin router with `gin.New()` and add whatever global middleware you want/need.
