### ISSUE TITLE
Feature Request: add get response body method

### ISSUE THREAD

**Issue by lincanli** [gin-gonic/gin#603]
Hi,

Thanks you all for this amazing package.

I just wondering if it is possible to add a get response body method to context? sometime it is needed to get response body in middleware, however i don't see any public method in gin that can provide that.

Thanks!

**Comment by julio-vaz** [comment]
Any update on this? How do I get the response body?
Thank you in advance!

**Comment by javierprovecho** [comment]
the response isn't buffered, but is directly streamed to the http response writer, so it is not possible.
