### ISSUE TITLE
[questions] how to use contrib/static with HTTP auth

### ISSUE THREAD

**Issue by joyhope** [gin-gonic/gin#605]
gin-gonic/contrib/static is working, but I hope to work with HTTP auth. I did not how to use? 

authorized.Use(static.Serve(xxx , xxx)) seems not work.

**Comment by EtienneR** [comment]
Have you try this https://github.com/gin-gonic/gin#using-basicauth-middleware ?

**Comment by hotrush** [comment]
@EtienneR seems it doesn't work

```
authorized := r.Group("/", gin.BasicAuth(users))
authorized.Use(static.Serve("/", static.LocalFile("./public", false)))
```
