### ISSUE TITLE
slow json response

### ISSUE THREAD

**Issue by majimboo** [gin-gonic/gin#608]
Hello,

`c.JSON` seems to be very slow on the browser dev console network response time, why?

Why is this code faster:

```
// 17 ms (browser)
// 4ms (gin log)
out, _ := json.Marshal(versions)
c.String(http.StatusOK, string(out))
```

while this one is quite slow?

```
// 1195 ms (browser)
// 3ms (gin log)
c.JSON(http.StatusOK, versions)
```

What is the difference? (other than the headers content type)

---

**update**

So I tried this:

```
// 1125 ms (browser)
// 3.6ms (gin log)
c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
c.String(http.StatusOK, string(out))
```

So I guess the content type is making it slower? How? Why?

**Comment by akumasenpai** [comment]
What response times do you get with this? Writer.Write will determine your Content-Type using "out".
```go
out, _ := json.Marshal(versions)
c.Writer.WriteHeader(http.StatusOK)
c.Writer.Write(out)
```

**Comment by jochasinga** [comment]
Have you tried setting `Content-Length` explicitly?
```go
c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
c.Writer.Header().Set("Content-Length", str(len(out))
c.JSON(http.StatusOK, out)
```

This can [avoid chunking and sniffing in Go's HTTP server](https://groups.google.com/forum/#!topic/golang-nuts/RPpiuF_DxF0).
