### ISSUE TITLE
Best way to stop the http server within software?

### ISSUE THREAD

**Issue by lostinblue** [gin-gonic/gin#612]
The example in the documentation suggests endless but that seems to allow for graceful shutdowns if the software as a whole is closed from the outside through for example a kill command. This seems to be the same  with the other suggestion manners. 

My question is: What is the best way to stop the http server from within your software so you can have a switch to turn the http server off and on.

**Comment by lostinblue** [comment]
I found https://github.com/gin-gonic/gin/pull/81/files which provided clear instructions on how to stop the server. I will break off and clean up the code to make it a very addon library if there is interest.

**Comment by lostinblue** [comment]
The library can be found here for anyone else who runs into this issue: https://github.com/glibs/gin-webserver

**Comment by nazwa** [comment]
Nice one!

**Comment by rfyiamcool** [comment]
good.
