### ISSUE TITLE
http2 hijack interface error

### ISSUE THREAD

**Issue by rabarar** [gin-gonic/gin#613]
Looks like the http2 support has broken web socket hijacking...

If I run a server and disable http2, no panic. Otherwise, using http2 and trying to open a ws causes the following error:

```
interface conversion: *http.http2responseWriter is not http.Hijacker: missing method Hijack
github.com/gin-gonic/gin/response_writer.go:105
```

i disabled http2 by running a server with 

```
 GODEBUG=http2server=0
```

**Comment by andrewarrow** [comment]
@rabarar how do I run with http2 support? I keep getting "http2: server: error reading preface from client  timeout waiting for client preface"

**Comment by rabarar** [comment]
What version of Go? I think it's the default in 1.6

**Comment by andrewarrow** [comment]
$ go version 
go1.6 linux/amd64

**Comment by rabarar** [comment]
Hmm - what about the client? Have you tried a minimalist server to replicate the problem ?

**Comment by andrewarrow** [comment]
I guess I'm a little confused on http2. All so new to me. How do I test? With a browser plugin that only talks http2 and not http1?

**Comment by rabarar** [comment]
Check out 

https://http2.github.io

**Comment by im7mortal** [comment]
HTTP/2 does not support protocol upgrade, so you will have to disable HTTP/2 in order to use websocket  successfully on secure connections.

**Comment by rabarar** [comment]
Thanks! Disabling indeed works
