### ISSUE TITLE
run on port 443 with https?

### ISSUE THREAD

**Issue by andrewarrow** [gin-gonic/gin#614]
I can say Run(":443") but how do I give it my cert file and make https work?

**Comment by ahamilton55** [comment]
https://github.com/gin-gonic/gin/blob/develop/gin.go#L230

**Comment by andrewarrow** [comment]
thank u

**Comment by andrewarrow** [comment]
@ahamilton55 any idea about this? http://stackoverflow.com/questions/37060315/how-do-i-fix-my-pem-block-in-ssl-certificate

**Comment by j0hnwhyte** [comment]
Dead link, also there seems to be no mention in the documentation. For future readers, to run gin with TLS and a custom cert, just use the `RunTLS()` function.

**Comment by andrewarrow** [comment]
I ended up doing:

```
cert, _ := tls.X509KeyPair([]byte(Fullchain), []byte(Privkey))
  tlsConfig := tls.Config{Certificates: []tls.Certificate{cert}}
  s := &http.Server{
    Addr:      "0.0.0.0:443"
    TLSConfig: &tlsConfig,
    Handler:   ginDefault,
  }
  s.ListenAndServeTLS("", "")
```

`RunTLS` Didn’t let me set something specific I needed.
