### ISSUE TITLE
real life SSL and http2 issues with gin in production

### ISSUE THREAD

**Issue by andrewarrow** [gin-gonic/gin#615]
Some errors I keep seeing in my logs:

`http2: server: error reading preface from client 173.73.165.109:62190: timeout waiting for client preface
`
`http: TLS handshake error from 141.212.122.81:58006: tls: no cipher suite supported by both client and server`

Any ideas if these should be worried about?

**Comment by deepch** [comment]
you solved?

**Comment by andrewarrow** [comment]
I think I decided these were just normal errors that can happen and there's nothing to be done so I closed this ticket. But I'm really not 100% sure. Feel free to re-open?

**Comment by javierprovecho** [comment]
@andrewarrow does this issues happen only with gin? Those are std lib error messages (nothing to do with gin), all of them related with bad client behavior . [here](https://golang.org/pkg/net/http/#Transport) you can increment the timeouts for this kind of ops. An explanation for the different messages is available at this SOF [answer](https://stackoverflow.com/a/39548866)
