### ISSUE TITLE
Regarding gin-cors.Middleware.func1 as c.HandlerName()

### ISSUE THREAD

**Issue by oharlem** [gin-gonic/gin#618]
Hi,

Implementing request logger I've noticed that for half of all requests to Gin 
c.HandlerName() equals to "github.com/itsjamie/gin-cors.Middleware.func1"

For context:
1. I'm using "github.com/itsjamie/gin-cors"
2. Interceptor implemented as simple as:

```
r.Use(LoggerMW)
...
where
...
func LoggerMW(c *gin.Context) {
...
println(c.HandlerName())
...
}
```

My expectation was that a middleware would be "transparent" and following docs for 
func (c *Context) HandlerName() we have _"// HandlerName returns the main handler's name."_ where I read "main" as a handler behind a middleware.

Please let me know if this is something expected and I need to filter this string out then, or this is a bug or there's a some correct way to make Gin + its CORS middleware? 

Thank you!
D

**Comment by oryband** [comment]
Any input on this from the devs?

**Comment by itsjamie** [comment]
It looks like HandlerName is implemented to return the last handler that was executed, so in the case where the middleware stops the execution chain, like with a preflight request by calling `c.AbortX` it will be what is returned.

**Comment by thinkerou** [comment]
#506
