### ISSUE TITLE
[question] how should I handle https request and http one. 

### ISSUE THREAD

**Issue by hiromaily** [gin-gonic/gin#621]
I'm developing web server program that there are some pages which accept only https or http depending on page.
How should I handle it as suitable gin style.

That means, I want to handle that restriction on below code as my image.

```
//http
route.GET("/", IndexAction)

//https only
route.GET("/", someSSHAction)

```

Thanks.

**Comment by nazwa** [comment]
Create two instances of gin inside goroutines so that one handles http and the other does https. 

Or, use reverse proxy like nginx to handle all https for you sp that gin app only responds to basic http

**Comment by hiromaily** [comment]
Thanks nazwa! I understood it!
When development use, it may be better to include TLS feature in Golang web server.
However, when it is used as production use, I'd use Nginx as reverse proxy.

Thanks again!
