### ISSUE TITLE
Is it possible to stop a router from running?

### ISSUE THREAD

**Issue by RyanCopley** [gin-gonic/gin#626]
Hi! We have a weird use case where we need to stop an entire router from listening. I've looked through the source and only see code for running it. This isn't specific to go but I think this is what i'm talking about: http://www.hydrogen18.com/blog/stop-listening-http-server-go.html

**Comment by RyanCopley** [comment]
`The built-in HTTP server does not include any mechanism to shut it down.`

oy vey...

**Comment by ralph327** [comment]
What was your solution?

**Comment by Alex-Addy** [comment]
For future people that find this issue through google: go to https://github.com/gin-gonic/gin#graceful-restart-or-stop

**Comment by kazhuravlev** [comment]
upd https://github.com/gin-gonic/gin#graceful-shutdown-or-restart

**Comment by CorentinB** [comment]
Updated link : https://github.com/gin-gonic/gin/blob/master/docs/doc.md#graceful-shutdown-or-restart
