### ISSUE TITLE
gin.Error does not implement the error interface

### ISSUE THREAD

**Issue by tevjef** [gin-gonic/gin#630]
I was attempting to use the exported `gin.Error`type  in `func (c *Context) Error(err error) *Error` but it fails on compilation. 

``` go
func someFunc(c *gin.Context) {
  if u, err := SomeOp(); err != nil {
    c.Error(gin.Error{err, gin.ErrorTypePublic, c.Request.URL.String()})
  }
}
```

Here's the compilation error :
`cannot use gin.Error literal (type gin.Error) as type error in argument to c.Error:
    gin.Error does not implement error (Error method has pointer receiver)`

If seems like the inteface was improperly implemented [here](https://github.com/gin-gonic/gin/blob/develop/errors.go#L74-L77) as the reviecer type should not have be an *Error.

This should fix it.

``` go
// Implements the error interface
func (msg Error) Error() string {
    return msg.Err.Error()
}
```

**Comment by stxml** [comment]
If you really want to add an ErrorTypePublic error, you have to call 
`c.Error(&gin.Error{err, gin.ErrorTypePublic, c.Request.URL.String()})`

If you check gin.Context.Error(), it will be obvious you are putting your public gin.Error into another private gin.Error. At this point you should just call `c.Error(errors.New(c.Request.URL.String())`.

**Comment by Illirgway** [comment]
Rob Pike answered about such kind of errors
https://github.com/golang/go/issues/25346#issuecomment-388258142
