### ISSUE TITLE
Add multiple json

### ISSUE THREAD

**Issue by nhatbui102** [gin-gonic/gin#632]
I’m Nhat, I’m student from Viet Nam. I’m using Gin gonic and having a problem. Can you help me? How can I import a json like that?
[
{
"Name": "Apolo",
"Phone": "2147483643247",
"Email": "aloha1@gmail.com",
"Content": "ccvodoi"
},
{
"Name": "Apolo1",
"Phone": "214567643247",
"Email": "aloha2@gmail.com",
"Content": "ccvodoi"
},
{
"Name": "Apolo2",
"Phone": "214756743247",
"Email": "aloha3@gmail.com",
"Content": "ccvodoi"
}
]

**Comment by appleboy** [comment]
See the following example code.

https://github.com/appleboy/gorush/blob/master/gorush/notification.go#L31-L46

**Comment by tsirolnik** [comment]
What do you mean by "import"?

**Comment by nhatbui102** [comment]
Sorry. It's POST. and I have my simple code.

func importJson(c *gin.Context) {
	var listuser []User
	//var user User
	c.Bind(&listuser)
	//log.Println(listuser)
	for i:=0; i < len(listuser) ; i++ {
		//user.name := listuser[i].Name
		//user.phone := listuser[i].Phone
		//user.email := listuser[i].Email
		//user.content := listuser[i].Content
		if listuser[i].Name != "" && listuser[i].Phone != "" && vali_phone(listuser[i].Phone) != false && valid_mailform(listuser[i].Email) != false && listuser[i].Content != ""{

		if insert, _ := dbmap.Exec(`INSERT INTO user (name, phone, email, content) VALUES (?, ?, ?, ?)`, listuser[i].Name, listuser[i].Phone, listuser[i].Email, listuser[i].Content); insert != nil {
			user_id, err := insert.LastInsertId()
			if err == nil {
				content := &User{
					Id:	user_id,
					Name: listuser[i].Name,
					Phone:  listuser[i].Phone,
					Email: listuser[i].Email,
					Content: listuser[i].Content,
				}
				c.JSON(201, content)
			} else {
				checkErr(err, "Insert failed")
			}
		}

		} else {
			c.JSON(400, gin.H{"error": "Fields are empty"})
		}
	}
}

**Comment by nhatbui102** [comment]
Sorry. It's POST. I have my own simple code.

`func importJson(c *gin.Context) {
	var listuser []User
	//var user User
	c.Bind(&listuser)
	//log.Println(listuser)
	for i:=0; i < len(listuser) ; i++ {

		if listuser[i].Name != "" && listuser[i].Phone != "" && vali_phone(listuser[i].Phone) != false && valid_mailform(listuser[i].Email) != false && listuser[i].Content != ""{

		if insert, _ := dbmap.Exec(`INSERT INTO user (name, phone, email, content) VALUES (?, ?, ?, ?)`, listuser[i].Name, listuser[i].Phone, listuser[i].Email, listuser[i].Content); insert != nil {
			user_id, err := insert.LastInsertId()
			if err == nil {
				content := &User{
					Id:	user_id,
					Name: listuser[i].Name,
					Phone:  listuser[i].Phone,
					Email: listuser[i].Email,
					Content: listuser[i].Content,
				}
				c.JSON(201, content)
			} else {
				checkErr(err, "Insert failed")
			}
		}

		} else {
			c.JSON(400, gin.H{"error": "Fields are empty"})
		}
	}
}`

**Comment by nhatbui102** [comment]
Sorry. It's POST. I have my own simple code.

{ func importJson(c *gin.Context) {
	var listuser []User
	//var user User
	c.Bind(&listuser)
	//log.Println(listuser)
	for i:=0; i < len(listuser) ; i++ {
		if listuser[i].Name != "" && listuser[i].Phone != "" && vali_phone(listuser[i].Phone) != false && valid_mailform(listuser[i].Email) != false && listuser[i].Content != ""{

		if insert, _ := dbmap.Exec(`INSERT INTO user (name, phone, email, content) VALUES (?, ?, ?, ?)`, listuser[i].Name, listuser[i].Phone, listuser[i].Email, listuser[i].Content); insert != nil {
			user_id, err := insert.LastInsertId()
			if err == nil {
				content := &User{
					Id:	user_id,
					Name: listuser[i].Name,
					Phone:  listuser[i].Phone,
					Email: listuser[i].Email,
					Content: listuser[i].Content,
				}
				c.JSON(201, content)
			} else {
				checkErr(err, "Insert failed")
			}
		}

		} else {
			c.JSON(400, gin.H{"error": "Fields are empty"})
		}
	}
}
}

**Comment by nhatbui102** [comment]
Sorry. It's POST. I have my own simple code.

func importJson(c *gin.Context) {
	var listuser []User
	//var user User
	c.Bind(&listuser)
	//log.Println(listuser)
	for i:=0; i < len(listuser) ; i++ {
		/
		if listuser[i].Name != "" && listuser[i].Phone != "" && vali_phone(listuser[i].Phone) != false && valid_mailform(listuser[i].Email) != false && listuser[i].Content != ""{

		if insert, _ := dbmap.Exec(`INSERT INTO user (name, phone, email, content) VALUES (?, ?, ?, ?)`, listuser[i].Name, listuser[i].Phone, listuser[i].Email, listuser[i].Content); insert != nil {
			user_id, err := insert.LastInsertId()
			if err == nil {
				content := &User{
					Id:	user_id,
					Name: listuser[i].Name,
					Phone:  listuser[i].Phone,
					Email: listuser[i].Email,
					Content: listuser[i].Content,
				}
				c.JSON(201, content)
			} else {
				checkErr(err, "Insert failed")
			}
		}

		} else {
			c.JSON(400, gin.H{"error": "Fields are empty"})
		}
	}
}

**Comment by jochasinga** [comment]
@nhatbui102 Please format your code by using three back ticks (\`\`\`) followed by language name (in this case `go`) and close with another set of back ticks like below:

```go
// go code goes here
fmt.Println("hello")
```
