### ISSUE TITLE
Don't zero out default log package flags.

### ISSUE THREAD

**Issue by rdwilliamson** [gin-gonic/gin#634]
I imported a package (github.com/mkevac/debugcharts) that has dependencies on gin. Suddenly all my log messages were missing the time stamps and I tracked it down to the [init function in debug.go](https://github.com/gin-gonic/gin/blob/develop/debug.go#L14)

**Comment by aronatkins** [comment]
Also encountered this issue with to `gin` calling `log.SetFlags`. Working around by explicitly restoring the standard logging flags in my application main.

```go
log.SetFlags(log.LstdFlags)
```

**Comment by thinkerou** [comment]
please see #1560 and close.
