### ISSUE TITLE
Slashes in parameter

### ISSUE THREAD

**Issue by Devatoria** [gin-gonic/gin#641]
Sorry if this issue has already been reported, but I can't find an answer. I'm making some sort of proxy API in front of a Docker Registry. As some of you probably knows, Docker Registry API calls start with `/v2/<parameter>/<command>/...`.

For example, I'm trying to catch the PUT manifest call: `/v2/<repository>/manifests/<reference>`. The problem is that the `repository` parameter can contains slashes, and a route like: `/v2/:repository/manifests/:reference` can't handle this. Is there a way to do this?

Thank you!

**Comment by nazwa** [comment]
I think the only way to do this would be to parse the url manually and extract all the information you need. Unless you know the repository names upfront, in which case you could prepare routes for each repo separately.
