### ISSUE TITLE
Is it possible to have optional parameters?

### ISSUE THREAD

**Issue by jersten** [gin-gonic/gin#645]
Sample code:

```
v1 := router.Group("/v1")
	{
		v1.GET("/tableN/:number", v1GetTableN)
	}
```

Is it possible to have `:number` optional? Or, do I need to just add another route?

**Comment by javierprovecho** [comment]
Use a wildcard parameter (`"/tableN/*number"`)

Cons are:

- route must end in a slash if no parameter is specified
- parameter can have slashes

**Comment by manucorporat** [comment]
two routes sounds like a better idea anyway

**Comment by jersten** [comment]
What I did instead was use the same context. Upon using `c.Param(...)` if there is no param it's returned as empty string; if the string is empty I just set a default value.
