### ISSUE TITLE
Retrieve handler RouteInfo

### ISSUE THREAD

**Issue by itsjamie** [gin-gonic/gin#649]
When a request hits Gin, it would be great for instrumentation to have access to the original route string that was passed to register the handler that has been selected to handle the request.

**Comment by itsjamie** [comment]
https://github.com/gin-gonic/gin/issues/584 was originally opened to support this, it would be great to see the selected Route available for introspection on the Context object. Thank you :)

**Comment by clutchski** [comment]
I would like to see this as well. It's very good for instrumentation where you'd like to aggregate statistics by route (e.g. `/user/:id`) and not by path. Is this on anybody's radar?

**Comment by jonaz** [comment]
We would also need this. Id did an ugly workarround in a middleware the mean time: 

```
		routes := p.parent.Routes()
		url := ""
		for _, r := range routes {
			if r.Handler == c.HandlerName() {
				url = r.Path
				break
			}


		}
```

I guess its also affecting performance since every call is looping over all routes. But until this issue is resolved i think its the only way.
