### ISSUE TITLE
how can i use c.Query to get the array param

### ISSUE THREAD

**Issue by zhguokai** [gin-gonic/gin#653]
i use extjs to send params array like ["ac1","ac2"] with name "acMode" in Get request,
then how can i  get the params use c.Query("acMode")? now i only get the first value "ac1",
thanks every one

**Comment by appleboy** [comment]
Try this PR: https://github.com/gin-gonic/gin/pull/570

**Comment by zhguokai** [comment]
@appleboy hello,first thank you very much, the solution #570 should choose my request method to "POST",but the extjs dataGrid request must Get method, has any other solution ?

**Comment by stxml** [comment]
The PR doesn't require the POST method, but you could access the Query values directly. 
`values, ok := c.Request.URL.Query()[key]`

**Comment by zhguokai** [comment]
@stxml thank you ,i will try it later

**Comment by zhguokai** [comment]
thanks everyone

**Comment by zhguokai** [comment]
thanks every one
