### ISSUE TITLE
how can I use golang.org/x/net/context in func xxx(c *gin.Context)?

### ISSUE THREAD

**Issue by ynqa** [gin-gonic/gin#654]
As executing gin applications, I just use golang.org/x/net/context for async process, such as sending logs with fluentd, or r/w databases. So I create `ctx := context.Background()`, but I cloud not call it because `gin.GET(func)`'s func has only one arg: `*gin.Context`, cloud not include `ctx` (= context.Context).

**Comment by ramoas** [comment]
Currently, it looks like the gin.Context implements the context.Context interface in a very basic manner (no deadline, no done channel, no done error, but can get values):
https://github.com/gin-gonic/gin/blob/master/context.go#L543-L568

Thus, it seems like you can pass a gin.Context into code that expects a context.Context, but not vice versa.  You should also be able to derive a context.Context from a gin.Context.

From history, it looks like the gin experimentation with / introduction of context.Context occurred in May 2015, just before 1.0rc1.

If anyone has experience bridging / mixing gin.Context with context.Context, please share.

**Comment by ynqa** [comment]
@ramoas Thank you for your reply. I see... that we have to use them in combination.
So, I make a mixing gin.Context with context.Context middleware by the reference [econtext](https://github.com/dre1080/econtext), and here: https://gist.github.com/ynqa/78e7889a313f67d4a5d0f77e56fa506d

if you use it:
```
g := gin.Default()
ctx := context.Background()
...
g.Use(middleware.Middleware(ctx))

```

I would appreciate it very much if you could point out anything to me!!
