### ISSUE TITLE
How to download an xlsx file using gin

### ISSUE THREAD

**Issue by zhguokai** [gin-gonic/gin#658]
Could you tell me how to use Gin the Get or POST request to download a file,  i have go the file's byte[] stream,thanks every one

**Comment by zhguokai** [comment]
i have got it 
c.Status(http.StatusOK)
	header := c.Writer.Header()
	header["Content-type"] = []string{"application/octet-stream"}
	header["Content-Disposition"] = []string{"attachment; filename= demo.xlsx"}
	file.Write(c.Writer)

**Comment by nazwa** [comment]
Even easier, use `c.File()`:
```go
func (this *ViewHandler) Get(c *gin.Context) {
	c.File("myFile.xlsx")
}
```

It sets content headers for you :)
