### ISSUE TITLE
gin.Context.Param() giving wrong values

### ISSUE THREAD

**Issue by samtech09** [gin-gonic/gin#663]
Here is simple code that i am trying to run

```
package main

import (
    "log"

    "github.com/gin-gonic/gin"
)

func main() {
    server := gin.Default()

    server.GET("/countries/*code", GetCountries)
    server.Run()
}

func GetCountries(c *gin.Context) {
    ccode := c.Param("code")
    log.Printf("Code: %s", ccode)
}
```

Here is output after run

```
[GIN-debug] redirecting request 301: /countries --> /countries/
Code: /
[GIN] 2016/07/16 - 17:24:59 | 200 |      16.508��s | ::1 |   GET     /countries/
Code: /USA
[GIN] 2016/07/16 - 17:25:17 | 200 |       12.47��s | ::1 |   GET     /countries/USA
```

It is visible that if code is not passed to url still it is giving `/`.
Expected output is empty string or nil.

**Comment by stxml** [comment]
"*" is for wildcard routes. Use this:

`    server.GET("/countries/:code", GetCountries)
`

**Comment by samtech09** [comment]
Ya '*' is for wildcard.
But when there is no code set then it should return "" not "/".

is there any advantage of getting "/" in place of "" ?

**Comment by EtienneR** [comment]
Use `c.Params.ByName` instead of `c.Param`.
