### ISSUE TITLE
 Gin routing on appengine

### ISSUE THREAD

**Issue by miko-code** [gin-gonic/gin#664]
Im writing some rest API Services on the appegine in a different modules im also using Gin for routing.
This is my dispatch file

```
  - url: "*/meal"
       module: meal
```

And the gin code .

```
r.Handle("POST", "/meal", m.InsertMeal) //http 200 
    r.Handle("GET", "/meal", m.GetAllMeals)//http 200 
    r.Handle("GET", "/meal/:id", m.GetAllMealById) //http404 

    http.Handle("/meal", r)
```

What is the proper way to config my handler?

**Comment by javierprovecho** [comment]
check https://github.com/gin-gonic/gin/tree/master/examples/app-engine
