### ISSUE TITLE
Question: Status codes in error handling

### ISSUE THREAD

**Issue by samherrmann** [gin-gonic/gin#665]
@manucorporat, in your example [here](https://github.com/gin-gonic/gin/issues/274#issuecomment-104472296), what if the error is something like a "not found" error, in which case it would be more appropriate to return a status code of 404 instead of 500? What is the recommended way to handle status codes in this architecture? Should the codes be attached to the errors using the `Meta` method?

**Comment by samherrmann** [comment]
I just reread my question and realized that I wasn't very clear. What I meant is that if we have a `handleErrors` function that takes care of returning the error(s) to the client, how can it know what status code it should return that is appropriate for the error at hand? I can only imagine the originator of the error being able to make that decision no?

**Comment by nazwa** [comment]
@samherrmann In your handler function, you can use `c.AbortWithError(400, err)` function to set the actual status code and collect it inside `handleErrors` middleware. At that point your status code is set and you just log / parse / render and return the error message it in the appropriate format to the user.

This gives you the option to display a generic message for all internal (500) errors and full error for all 4** and so on.

**Comment by samherrmann** [comment]
@nazwa thanks for your suggestion! I was thinking about using `c.AbortWithError(400, err)`, but I found it a little odd that a handler function would write to the response header (status code) while the `handleErrors` would write the body (error message). To me it felt cleaner and more reliable if all handlers would attach errors (message and code) to the Gin context, and then the `handleErrors` function would be responsible for doing whatever it wants with those errors (message and code). Based on that, I created the following helper function in my code:

```
// AbortWithError attaches a Gin error to the current Gin
// context with a status code. It is the same as Gin's
// ctx.AbortWithError function, except that it attaches the
// status code to the context (accompanying the error) instead
// of writing it directly to the HTTP header. This allows a
// separate middleware to handle all the HTTP response writing,
// for the body as well as the header.
func AbortWithError(ctx *gin.Context, err error, code int) {
	ctx.Error(err).SetMeta(&ErrorMeta{Code: code})
	ctx.Abort()
}

// ErrorMeta is a matadata struct for a Gin Error
ErrorMeta struct {
	// The suggested HTTP status code to return to
	// the client for the error
	Code int
}
```
Do you agree with this approach or am I overlooking something that would make this a bad design? At this point I wonder, if what I am saying makes sense, then is there a reason why Gin's `AbortWithError` function was designed to write the status code to the header but attach the error message to the context?

**Comment by nazwa** [comment]
My _personal_ view is that it's up to the controller to set the status code and not he error handler. The error handler is really only to catch internal and form binding errors. Are you forbidden from accessing this resource? Controller will set it. Was the file you uploaded too big? Controller will set it. Did your database go down and connection failed? Let the error handler handle it - log it and return a generic message. But again, this massively depends on your application flow and is up to you to decide.

**Comment by samherrmann** [comment]
Thanks @nazwa! Based on your response, here is the general guideline for writing middleware that I've come away with:

1. Any middleware function that contains code **before** calling Gin's [Next](https://github.com/gin-gonic/gin/blob/v1.0/context.go#L93) function should handle errors by calling [AbortWithError](https://github.com/gin-gonic/gin/blob/v1.0/context.go#L125). Such middleware usually perform some sort of validation on the request and is responsible to set the error code, 4xx, should validation fail.

2. Any middleware function that contains code **after** calling Gin's `Next` function should handle errors by calling [Error](https://github.com/gin-gonic/gin/blob/v1.0/context.go#L138), NOT `AbortWithError`. First of all, `Abort` after `Next` has no effect since all middleware in the chain have already been called by that point. Second of all, code after `Next` means that the middleware is performing some sort of data processing that may originate from a database, meaning that any kind of error at this point is internal, i.e. 500.

If all middleware is written as such, the `handleErrors` middleware can be structured as follows:

```
if errors are attached to context
    if response header was already written
        log errors only, the response error code was set by the validation middleware
    else 
        log errors and write generic HTTP error response
else
    everything went well, nothing to do in here
```

Does this sound reasonable?

**Comment by javierprovecho** [comment]
LGTM.

IMO it would be great if you open a PR with a better practice guide on "how to write good middlewares in gin"

cc @tboerger @appleboy

**Comment by appleboy** [comment]
LGTM @samherrmann

**Comment by samherrmann** [comment]
Thanks for your feedback everyone!
