### ISSUE TITLE
r.Run() on TCP4 / IPV4 only

### ISSUE THREAD

**Issue by rawoke083** [gin-gonic/gin#667]
HI I've been trying to make the router/service run on TCP4 only

//none of these are working , It keeps being listed on tcp6
r.Run(":8080")
r.Run("*:8080")
r.Run("0.0.0.0:8080")

**Comment by stxml** [comment]
Let's just say, you should really just fix this at the firewall.

If you are determined, it would not be too hard, just tedious.

Now it works like this.
r.Run() -> http.ListenAndServe() -> http.Server.ListenAndServe() -> http.Server.Serve()

You would have to create the Server yourself and then call the Serve() function with a TCP4 net.Listener. It's all in http.Server.ListenAndServe() already, just change "tcp" to "tcp4".

**Comment by rawoke083** [comment]
Hi Ja, I saw plus minus that route but I'm not 100% sure how to implement it in the code.
Got any examples ?

**Comment by stxml** [comment]
server := &Server{Addr: addr, Handler: ginRouter}
ln, err := net.Listen("tcp4", addr)
if err != nil {
	return err
}
srv.Serve(tcpKeepAliveListener{ln.(*net.TCPListener)})

**Comment by rawoke083** [comment]
Awesome thank you !

**Comment by stxml** [comment]
Also C&P this from server.go, or it won't work

```
type tcpKeepAliveListener struct {
	*net.TCPListener
}

func (ln tcpKeepAliveListener) Accept() (c net.Conn, err error) {
	tc, err := ln.AcceptTCP()
	if err != nil {
		return
	}
	tc.SetKeepAlive(true)
	tc.SetKeepAlivePeriod(3 * time.Minute)
	return tc, nil
}

```
