### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by robvdl** [gin-gonic/gin#668]
It looks like version tags (semver style) were being done at some point, then stopped at v1.0rc1

Any plans to bring this back? It would help to get specific versions of Gin from a glide.yaml file when using Glide (and probably other versioning tools that support semver too).

**Comment by appleboy** [comment]
glide +1

**Comment by robvdl** [comment]
I might have got that slightly wrong though, it looks like v1.0rc1 is actually the latest version but that is a long time ago now, and since then about 270 commits have been made... maybe more frequent versioning is required.

**Comment by robvdl** [comment]
I wasn't really suggesting the project should switch to glide (although it would be nice), I was just wondering why there hasn't been a new version tag for some time.  It does appear however that the version tags are still maintained for new releases, so I might as well close this issue.
