### ISSUE TITLE
Any plan on v2?

### ISSUE THREAD

**Issue by leedstyh** [gin-gonic/gin#670]
Is there any plan on v2? Features like integrate `net/context` in `gin.Context`

**Comment by robvdl** [comment]
v1 hasn't even been released yet, latest tag is v1.0rc1

**Comment by leedstyh** [comment]
@robvdl Thinking they simply forget to tag the v1, because @javierprovecho said the project was "stuck while stable" (https://github.com/gin-gonic/gin/issues/476#issuecomment-170403216). And also @manucorporat was "in the design phase for a possible v2" (#523).

**Comment by no1youknowz** [comment]
I was going to write the same thing.

What's going to happen now that Go 1.7 has been released?

**Comment by cch123** [comment]
+1

**Comment by javierprovecho** [comment]
we have been releasing somehow quick in the last 2 months, the plan is to continue the sprint =)
some cool things at 
- [label/enhancement](https://github.com/gin-gonic/gin/labels/enhancement)
-  [label/feature](https://github.com/gin-gonic/gin/labels/feature)
