### ISSUE TITLE
Static 404

### ISSUE THREAD

**Issue by lizhong8532** [gin-gonic/gin#671]
I am using OS-X build my project, code below:
```
/usr/bin/env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v kong # kong is my project directory name 
```
Deploy to server, But all static request respond 404, Only POST request is working. My server env:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mydata/gowork"
GORACE=""
GOROOT="/mydata/go"
GOTOOLDIR="/mydata/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

If upload source to server and ' go run main.go ' so static request can be working.

How to fix the issue, Thanks everyone!

**Comment by fighterlyt** [comment]
I am not very familiar with gin,but it seems to be something wrong with your path.You didn’t put the static assets in the right path relative to the excutable . Try to move your static assets to the right place to keep the relative path

**Comment by lizhong8532** [comment]
Thanks, You are right, I has been test!
But I build project exclude static file? I need manual upload all static file to server? 
How to when building auto add all static?

**Comment by fighterlyt** [comment]
There are money tools to compile static files to Golang code,but this way has a magnificent drawback.EveryTime you modify static files, you must recompile the whole code to make it work.I strongly advise you to uploading static files.

Besides, I am also Chinese

**Comment by lizhong8532** [comment]
@fighterlyt 好吧，非常感谢，你们通常用什么工具上传静态文件到服务器呢？rsync?Git?

**Comment by fighterlyt** [comment]
其实我们用git

**Comment by lizhong8532** [comment]
@fighterlyt 然后.gitignore里加入 *.go ？因为build之后只需要把生成的执行文件和静态文件上传就好。但这个是部署版本，开发模式下如果需要版本控制的话 还是需要把所有源码都要提交啊，所以这种情况用两个remote?一个应对部署，另一个应对开发？

**Comment by fighterlyt** [comment]
严格意义上来说，不应该由某一个开发人员编译，而是创建一个和真实环境相同的测试环境，直接在测试环境编译。
go虽然标榜完全静态编译，但实际上还是会依赖底层库

把测试服务器当做一个从不提交代码的客户端，同步所有代码、资源，编译

**Comment by lizhong8532** [comment]
@fighterlyt 明白，所以针对于Web工程，我觉得还是前后端无论是开发还是部署分开比较好，前端配一个nginx转发，这样就不会每次都需要考虑有哪些静态文件了，因为前端利用Webpack就是一个很专业好的打包工具了，分开部署后期还能灵活维护，你觉得呢？

**Comment by fighterlyt** [comment]
问题不大，看项目的具体情况了，但是这些维护工作多一些
