### ISSUE TITLE
Question mark eaten from URL if no query parameters specified

### ISSUE THREAD

**Issue by fraenky8** [gin-gonic/gin#672]
If an URL/Route contains a trailing question mark, an 404-Error occures. I stumbled about this issue at https://github.com/parnurzeal/gorequest/issues/65, https://github.com/golang/go/issues/13488 and https://github.com/golang/go/issues/14573.

The golang net/http package solved this issue, see this small example (taken from here: https://golang.org/doc/articles/wiki/#tmp_3)

``` go
package main

import (
    "fmt"
    "net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hi there, I love %s!", r.URL.Path[1:])
}

func main() {

    http.HandleFunc("/", handler)
    http.HandleFunc("/q?", handler)
    http.HandleFunc("/q?foo=?", handler)

    fmt.Fprintln("Running on 127.0.0.1:8080")
    http.ListenAndServe(":8080", nil)
}
```

If i make a GET-Request to `127.0.0.1/q?` with Postman it works, and prints back "Hi there, I love q!"
The next example is written in gin-gonic:

``` go
package main

import (
    "fmt"
    "strings"

    "github.com/gin-gonic/gin"
)

func main() {
    r := gin.Default()
    r.GET("/q?", func(c *gin.Context) {
        c.String(200, "Hello there!")
    })
    r.GET("/q?foo=?", func(c *gin.Context) {
        foo, exists := c.Get("foo")
        if !exists  {
            foo = ""
        }
        c.String(200, "Hello there: %v", foo)
    })
    r.Run()
}
```

Same Get-Request with Postman. Here i get a 404-Not Found Error. Also the Server-Logs in console say 404.

**Comment by fraenky8** [comment]
My examples are faulty! m( The new parsing of URLs with trailing question marks will go live maybe go1.7. In my example i used only one handler which gets called everytime, so i couldnt distinguish between the calls, Tried it with three different handlers and there i saw my mistake. But problem still exists: instead trimming the trailing question mark and handle the route without it (and therefore i expect same behaviour like in net/http example), i still get an 404-Error.

**Comment by stxml** [comment]
Even with the changes in 1.7, the `?` won't be part of the route. The changes will preserve the question-mark when a query is empty, so that calls to url.RequestURI() will contain it.

Regarding gin, I suggest you don't put a `?` in your route. Gin stores the route with the question-mark, but net.url will not see it as part of the path and so it will never match the route.

**Comment by fraenky8** [comment]
Yeah you are right, although those routes might be valid routes according to the mentioned rfcs in the linked issues. But they make no sense to me either, therefore i won't using them at all.

**Comment by stxml** [comment]
The way I see it, a browser should distinguish between URIs like this
```
http://server.com/api/item.json
http://server.com/api/item.json?
```
Right now, you can't actually return different results on the server. With the changes to net.url you can check url.ForceQuery in your handler and respond accordingly, but it will still be the same route.
