### ISSUE TITLE
[Question] support for FastCGI protocol 

### ISSUE THREAD

**Issue by hiromaily** [gin-gonic/gin#673]
Now, I'm using Nginx as proxy.
And I want to use fast-cgi mode using fcgi package.
[fcgi](https://golang.org/pkg/net/http/fcgi/)

As far as I know, fcgi has been not supported on gin.
Is there plan to adjust it?

Thanks.

Harry.

**Comment by robvdl** [comment]
Why? it's known to be much slower to use fcgi rather than just proxy to your go app

**Comment by stxml** [comment]
I'd also suggest reverse-proxy but it should be easy to use gin with fcgi.

Sample code here:
http://www.dav-muz.net/blog/2013/09/how-to-use-go-and-fastcgi/

**Comment by hiromaily** [comment]
Thank you, I didn't know that.
Now I'm just checking how gin integrates with Nginx.
Instead of using Nginx, what is the best way to prepare reverse proxy?

**Comment by robvdl** [comment]
Plenty of info on this on Google, but something along these lines

location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:3000;
}
