### ISSUE TITLE
Regex match pattern routes

### ISSUE THREAD

**Issue by thoas** [gin-gonic/gin#680]
Hi,

I'm willing to use gin to replace mux, is there a way to do pattern route matching based on regex?

Like so:

```
router.GET("/display/{sig}/{op}/x{h:[\\d]+}/{path:[\\w\\-/.]+}", handlerFunc)
```

Thank you

**Comment by nazwa** [comment]
Unfortunately no. Routes have to be completely unambiguous with relatively simple parameters. You could then parse those and dispatch to sub handlers yourself if you need complex regex matching.

**Comment by thoas** [comment]
Ok thank you for the answer
