### ISSUE TITLE
How to set headers in middleware after HandlerFunc.

### ISSUE THREAD

**Issue by eaglewu** [gin-gonic/gin#681]
``` go
func MW1(c *gin.Context) {

     // go next middleare and run handlerFunc
     // and has already used c.JSON(200, "some data") in handlerFunc
    c.Next() 

    // Invalid!!  (Because the Header buffer already send)
    c.Header("X-Request-Id", "123")
}
```

How solve the problem that set header after handlerFunc in middleware?
:)

**Comment by EtienneR** [comment]
Why using `c.Next()` before `c.Header("X-Request-Id", "123")` and not the reverse ?

**Comment by nazwa** [comment]
You would have to create your own writer that collects the output and modifies the headers. Have a look at the cache middleware https://github.com/gin-gonic/contrib/blob/master/cache/cache.go#L111

**Comment by shivamgoel009** [comment]
You can header like this : `c.Request.Header.Add("x-request-id", requestID)`
