### ISSUE TITLE
Proxy route to another backend

### ISSUE THREAD

**Issue by kidambisrinivas** [gin-gonic/gin#686]
How to reverse proxy web requests for a few routes to another backend in Gin Gonic web golang framework

Is there a way to directly forward in the Handle function as shown below?

```
router := gin.New()
router.Handle("POST", "/api/v1/endpoint1", ForwardToAnotherBackend)
```

**Comment by stxml** [comment]
Maybe use a middleware to set up a ReverseProxy?

`router.Handle("POST", "/api/v1/endpoint1", ReverseProxy("localhost:8080/otherBackend")
`
```
func ReverseProxy(target *url.URL) gin.HandlerFunc {
	proxy := httputil.NewSingleHostReverseProxy(target)
	return func(c *gin.Context) {
		proxy.ServeHTTP(c.Writer, c.Request)
	}
}
```

**Comment by kidambisrinivas** [comment]
Thanks, this worked. But the headers are not being passed to the backend

**Comment by kidambisrinivas** [comment]
Got this sorted out with this:

```golang

router.POST("/api/v1/endpoint1", ReverseProxy()

func ReverseProxy() gin.HandlerFunc {

	// Parse fleet URL
	target := "localhost:3000"

	return func(c *gin.Context) {
		director := func(req *http.Request) {
			r := c.Request
			req = r
			req.URL.Scheme = "http"
			req.URL.Host = target
			req.Header["my-header"] = []string{r.Header.Get("my-header")}
                        // Golang camelcases headers
			delete(req.Header, "My-Header")
		}
		proxy := &httputil.ReverseProxy{Director: director}
		proxy.ServeHTTP(c.Writer, c.Request)
	}
}
```

**Comment by stxml** [comment]
Weird. I whipped up a test and I only had to add `http://` to the string to make it work. It also correctly passed on my header. Maybe your header is one of the special cases that gets filtered out.

**Comment by zwhitchcox** [comment]
Does this pass cookies?

**Comment by zwhitchcox** [comment]
Oh sorry, cookies are in the header

**Comment by zheeeng** [comment]
Can we have a chance to manipulate the response?

**Comment by sguillia** [comment]
@kidambisrinivas you should remove both lines to make it work:
```
r := c.Request
req = r
```
