### ISSUE TITLE
c.Bind not retrieving json from c.Request.Body

### ISSUE THREAD

**Issue by dvwright** [gin-gonic/gin#689]
Hi,

I seem to be having an issue with bind not getting the values I'm expecting. I have a created a gist that demonstrates the issue I am experiencing. https://gist.github.com/dvwright/4852fe63c753196fa077bb76928b4b20

When I run this I get:

go test  -run TestWhyNotBinding
[GIN-debug] POST   /api/v1/users  --> example/gin.CreateUser (5 handlers)
Raw Request Body : %s {{"email": "testEmail", "password": "testPassword"}}
Decoded Body Request Email : testEmail
Decoded Body Request Password : testPassword
Bind Email - Why not Set?
Bind Password  - Why not Set?

Thank you

**Comment by stxml** [comment]
You are reading from the Request Body twice. Why are you doing that?  Also, don't ignore the error returned from BindJSON, it could have answered your question.

**Comment by dvwright** [comment]
Bind error EOF, doh! Thanks

**Comment by dvwright** [comment]
closing, user error, end of stream....
