### ISSUE TITLE
Gin versioning needs update

### ISSUE THREAD

**Issue by nxvl** [gin-gonic/gin#695]
When using [glide](https://github.com/Masterminds/glide) as a dependency manager, the latest version detected is 0.6.0, which is an old release leading to the following errors in functions that have been added more recently:

```
c.Param undefined (type *gin.Context has no field or method Param)
c.BindJSON undefined (type *gin.Context has no field or method BindJSON)
c.Param undefined (type *gin.Context has no field or method Param)
c.DefaultQuery undefined (type *gin.Context has no field or method DefaultQuery)
c.Header undefined (type *gin.Context has no field or method Header)
c.Header undefined (type *gin.Context has no field or method Header)
c.Header undefined (type *gin.Context has no field or method Header)
c.Param undefined (type *gin.Context has no field or method Param)
```

**Comment by stxml** [comment]
I guess it's because the current tag "v1.0rc1" isn't a valid semver. Should be "1.0.0-rc.1".

**Comment by thinkerou** [comment]
- glide suggest user migrate from Glide to dep, I think maybe it is vgo.
- about Semantic Version, please see https://semver.org/
- as @stxml pointed it's a invalid semver
- now gin new tag is `v1.3.0`

so, I will close the issue, if you have any problem please reopen, welcome, thanks!
