### ISSUE TITLE
How to forward request route to another route?

### ISSUE THREAD

**Issue by netroby** [gin-gonic/gin#696]
I want to forward some to other route
Such as /login forward to /user/login

**Comment by netroby** [comment]
Not c.Redirect. I do not want redirect. I want things like nginx rewrite URL.

**Comment by Allendar** [comment]
You can write your own MiddleWare that you can feed Route>Route rules temporarily or indefinitely.

**Comment by javierprovecho** [comment]
if you don't want a redirect, maybe you want a reuse of an existing handler

you can do it as following:

```go

func main() {
  r := gin.Default()

  r.GET("/login", Login)
  r.GET("/user/login", Login)

  r.Run()
}

func Login(c *gin.Context){
  ...
}

```

**Comment by lil5** [comment]
I've created an example file, that shows how to create a middleware with url rewrite.

 https://github.com/lil5/gin-url-rewrite
