### ISSUE TITLE
middleware by Use in a group not working on basepaths

### ISSUE THREAD

**Issue by DasJott** [gin-gonic/gin#704]
I have a group "/foo".

this group uses middleware: group.Use(CertainFunc)

within this group I just have 
group.GET("/", doGet)
group.POST("/", doPost)

unfortunately the CertainFunc is never called, if I do GET on the path /foo

**Comment by stxml** [comment]
Does doGet get called?

**Comment by DasJott** [comment]
Nope.

I found out, that you have to explicitely specify the / at the end of the url in this configuration. It even makes sense, so this seems not to be a bug, but just the heat...
