### ISSUE TITLE
Program freezes on release mode

### ISSUE THREAD

**Issue by Noeru14** [gin-gonic/gin#705]
Hi, 

When I try to use gin on release mode, my program freezes right after its start. I use the following lines of code : 
gin.SetMode(gin.ReleaseMode)
router := gin.New()
router.Use(gin.Recovery())

However, when I use debug mode, the program runs normally:
gin.SetMode(gin.DebugMode)
router := gin.New()
router.Use(gin.Recovery())

OR router := gin.Default()

Am I doing something wrong ?
Also, can you explain what's the difference between these two modes ? I tried to look for this information but didn't find anything relevant.

Thanks in advance!

**Comment by stxml** [comment]
ReleaseMode only prevents logging of various info. It should have no effect on your app. Did you test with a client and actually got a connection refused?

**Comment by Noeru14** [comment]
Thanks for your reply. Your answer made me realize a mistake, problem is solved

**Comment by mamyn0va** [comment]
@Noeru14 I have the same issue, could you please provide the solution you found ?
