### ISSUE TITLE
Panic on init at gin.init() on invalid GIN_MODE 

### ISSUE THREAD

**Issue by dnp1** [gin-gonic/gin#708]
Hey guys, 

I'm using gin to create some services at my company.
We have a service  responding to a .socket , a cron scheduler or the gin's endpoint.

I wouldn't like the ideia of my service will crashing because a GIN_MODE are wrong, I want just log the problem and let my service working as usual at scheduler and socket modes.

Since panic is called on a "gin.init()" I just can't programmatically avoid that behavior.

I suggest call SetMode lazylly!

**Comment by javierprovecho** [comment]
We prefer to "hear" a failure on a wrong argument. A silent failure is worse.
