### ISSUE TITLE
router bug?

### ISSUE THREAD

**Issue by shinexiao** [gin-gonic/gin#711]
package routers

import (
	"github.com/gin-gonic/gin"
	"net/http"
	"sms/filter"
	"sms/controllers"
)

func NewRouters() *gin.Engine {

	chain := &filter.Filter{}

	router := gin.Default()
	router.Use(chain.FilterIp)

	//init controller
	smsTtemplateAtion := &controllers.SmsTemplateAction{}
	smsAppAction :=  &controllers.SmsAppAction{}

	v1 := router.Group("/v1")
	{
		//template
		v1.GET("/template/:id", smsTtemplateAtion.FindById)
		v1.GET("/findByAlias", smsTtemplateAtion.FindByAlias)
		v1.GET("/findByCompanyId", smsTtemplateAtion.FindByCompany)
		v1.GET("/template", smsTtemplateAtion.FindByPage)
		v1.POST("/template/create", smsTtemplateAtion.Create)
		v1.PUT("template/:id/update", smsTtemplateAtion.UpdateTpl)
		v1.PUT("template/:id", smsTtemplateAtion.Update)
		//app
		v1.POST("/apps/create",smsAppAction.Create)//conflicts with existing children in path '/v1/apps/:appId/recharge'
		v1.POST("/apps/:appId/recharge",smsAppAction.Recharge)
		v1.POST("/apps/:appId/setprovider",smsAppAction.SetProvider)
		v1.PUT("/apps/:appId/update",smsAppAction.Update)
		v1.GET("/apps",smsAppAction.FindByPage)
		v1.GET("/apps/:appId",smsAppAction.FindById)

	}

	router.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"message": "pong"})
	})

	return router
}

console print:

GIN-debug] GET    /v1/template/:id          --> sms/controllers.(*SmsTemplateAction).FindById-fm (4 handlers)
[GIN-debug] GET    /v1/findByAlias           --> sms/controllers.(*SmsTemplateAction).FindByAlias-fm (4 handlers)
[GIN-debug] GET    /v1/findByCompanyId       --> sms/controllers.(*SmsTemplateAction).FindByCompany-fm (4 handlers)
[GIN-debug] GET    /v1/template              --> sms/controllers.(*SmsTemplateAction).FindByPage-fm (4 handlers)
[GIN-debug] POST   /v1/template/create       --> sms/controllers.(*SmsTemplateAction).Create-fm (4 handlers)
[GIN-debug] PUT    /v1/template/:id/update   --> sms/controllers.(*SmsTemplateAction).UpdateTpl-fm (4 handlers)
[GIN-debug] PUT    /v1/template/:id          --> sms/controllers.(*SmsTemplateAction).Update-fm (4 handlers)
[GIN-debug] POST   /v1/apps/create           --> sms/controllers.(*SmsAppAction).Create-fm (4 handlers)
[GIN-debug] POST   /v1/apps/:appId/recharge  --> sms/controllers.(*SmsAppAction).Recharge-fm (4 handlers)
panic: wildcard route ':appId' conflicts with existing children in path '/v1/apps/:appId/recharge'

goroutine 1 [running]:
panic(0x4d3300, 0xc42000c7f0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/gin-gonic/gin.(*node).insertChild(0xc42030a480, 0xc420141b01, 0xc4200125a9, 0xf, 0xc4200125a0, 0x18, 0xc4200125c0, 0x4, 0x4)
	/Users/shine/Documents/dev/gosms/src/github.com/gin-gonic/gin/tree.go:275 +0xc37
github.com/gin-gonic/gin.(*node).addRoute(0xc42030a480, 0xc4200125a0, 0x18, 0xc4200125c0, 0x4, 0x4)
	/Users/shine/Documents/dev/gosms/src/github.com/gin-gonic/gin/tree.go:231 +0x22f
github.com/gin-gonic/gin.(*Engine).addRoute(0xc4203080e0, 0x57d187, 0x4, 0xc4200125a0, 0x18, 0xc4200125c0, 0x4, 0x4)
	/Users/shine/Documents/dev/gosms/src/github.com/gin-gonic/gin/gin.go:191 +0x1aa
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc420016140, 0x57d187, 0x4, 0x589fcb, 0x15, 0xc42002c090, 0x1, 0x1, 0x7c6701, 0xc42002c090)
	/Users/shine/Documents/dev/gosms/src/github.com/gin-gonic/gin/routergroup.go:73 +0xe7
github.com/gin-gonic/gin.(*RouterGroup).POST(0xc420016140, 0x589fcb, 0x15, 0xc42002c090, 0x1, 0x1, 0x7c6780, 0xc420016140)
	/Users/shine/Documents/dev/gosms/src/github.com/gin-gonic/gin/routergroup.go:96 +0x7c
sms/routers.NewRouters(0xc400000018)
	/Users/shine/Documents/dev/gosms/src/sms/routers/router.go:34 +0x7af
main.main()
	/Users/shine/Documents/dev/gosms/src/sms/main.go:22 +0x54
exit status 2

**Comment by arduanov** [comment]
same for me

**Comment by nazwa** [comment]
@shinexiao This is the "expected" behavior. Routes have to be completely unambiguous. It may feel a bit annoying at times but prefixing the url with another segment (like `/apps/manage/:appId/recharge`) is usually enough. Not very pretty but it's a small price to pay for all the other goodies.

**Comment by tboerger** [comment]
Just do it restful and post to /apps instead of /apps/create and it will work

**Comment by shinexiao** [comment]
thanks @nazwa ,  I mirgate an old java project to golang. so, some uris must using old. if it is a new project i can change the uri

**Comment by nazwa** [comment]
A not great but still valid solution would be to create a "catch all" handler at lets say `/apps/*` and manually parse the remainder of the route.
