### ISSUE TITLE
How to pass JSON to a Redirect POST

### ISSUE THREAD

**Issue by jhollar** [gin-gonic/gin#712]
I'm a newbie when it comes to Go so please excuse my ignorance, but I've setup a server that supports a POST request. I want the user to POST their request which includes a JSON payload then have that request redirected to another URL passing the original JSON payload. For example, if the user issues this CURL request: 

curl -H "Content-Type: application/json" -d '{ "name": "NewTest Network", "organizationId": 534238, "type": "wireless"}' -X POST "http://localhost:8080/network"

My Gin code does this:
r.POST("/network", func(c *gin.Context) {
       c.Redirect(http.StatusMovedPermanently, networks_url)
})

where: networks_url is another URL. I need a way to pass the original JSON payload to the redirected URL.

Any help you could provide would be greatly appreciated.

**Comment by javierprovecho** [comment]
@jhollar i think you want HTTP 307

https://tools.ietf.org/html/rfc7231#section-6.4.7

you can use `http.StatusTemporaryRedirect` as constant for 307 http code.

307 will reissue the same request and verb to a different URI specified by the location header.
