### ISSUE TITLE
Disable short 30X redirect message

### ISSUE THREAD

**Issue by jkbbwr** [gin-gonic/gin#713]
The offending code is 
```
	// RFC 2616 recommends that a short note "SHOULD" be included in the
	// response because older user agents may not understand 301/307.
	// Shouldn't send the response for POST or HEAD; that leaves GET.
	if r.Method == "GET" {
		note := "<a href=\"" + htmlEscape(urlStr) + "\">" + statusText[code] + "</a>.\n"
		fmt.Fprintln(w, note)
	}
```

This should be customisable as I want to return a JSON response to this something akin to

```
{"message": "301 Redirect " + urlStr}
```

So either allow for disabling this optional HTML response or allow overriding it.

**Comment by widnyana** [comment]
is it related to https://github.com/gin-gonic/gin/issues/712 ?

**Comment by jkbbwr** [comment]
@widnyana 301 is automatic by the framework not self initiated. Its to do with trailing slash.

**Comment by javierprovecho** [comment]
@jkbbwr then you should use this:

```go
	c.Writer.Header().Set("Location", urlStr)
	c.JSON(301, gin.H{"message": "301 Redirect " + urlStr})
```

However, repeating the message in the body seems redundant to me. If more people consider `c.Redirect("url")` should be customizable, I'll look forward converting into a variadic function for not breaking the API.

**Comment by jkbbwr** [comment]
But surely there will be invalid HTML streamed in after the JSON response? (read not checked)

**Comment by jkbbwr** [comment]
I have no control over the trailing slash because its automatic by the framework.

**Comment by javierprovecho** [comment]
@jkbbwr no, `c.Redirect...` does write HTML if request is GET, but my answer just writes location header and a JSON response. 😉 

And about the trailing slash, you have an option in the engine to control that behaviour: `	r.RedirectTrailingSlash = false`

**Comment by jkbbwr** [comment]
That's not the same thing. 

I ended up moving to Iris which seems more extendable than Gin.
