### ISSUE TITLE
How to compress the template in gin

### ISSUE THREAD

**Issue by whitezhang** [gin-gonic/gin#714]
```
router.GET("/users/index", func(c *gin.Context) {
   c.HTML(http.StatusOK, "users/index.tmpl", gin.H{
        "title": "Users",
    })
})
```

I know this code can return the html file to the browser, but this file is not compressed. How to compressed the whole template before rendering?

Is there any successful template?

**Comment by tboerger** [comment]
One option should be a middleware. You can also use a gzip middleware to compress the content

**Comment by tboerger** [comment]
You can use a lib like https://github.com/tdewolff/minify/tree/master/html to minify the html output in the custom middleware
