### ISSUE TITLE
Dumping req.Body when Binding fails

### ISSUE THREAD

**Issue by seanlindo** [gin-gonic/gin#718]
Hey guys,

Is it possible to generate a more explicit error message or just print out a string representation of `req.Body`when this happens? 

I'm getting, "cannot unmarshal number into Go value of type string", so it would be great to log what was actually sent as well. I think `req.Body` is emptied after Binding takes place. 

Edit: I meant, `json.NewDecoder` takes in a `ReadCloser` as a parameter. The subsequent calling of `Decode` drains the the ReadCloser, which is `r.Body` in this case.

**Comment by dvwright** [comment]
For what it's worth, when debugging http I use:

import "net/http/httputil" 
```
func SomeMethod(c *gin.Context) {
                dump, err := httputil.DumpRequest(c.Request, true)
                fmt.Println(err)
                fmt.Printf("%q", dump)
```

**Comment by seanlindo** [comment]
Thanks! Any idea if this closes out the body or not? That's the issue I was running into previously, it's kind of a Catch-22 :)

I could also bind the request to a `map[interface]string` intermediary object as well I think.

**Comment by dvwright** [comment]
> req.Body is emptied after Binding takes place

Correct, you can only retrieve c.Request.Body once. So if you need the data to persist you must store it to something.

For example if it's json.

```
   var postCustomHandle map[string]interface{}
   jsnErr := json.NewDecoder(c.Request.Body).Decode(&postCustomHandle)
```

**Comment by seanlindo** [comment]
This is perfect. I'm also very happy to see this error being fleshed out more in Go 1.8!
