### ISSUE TITLE
App Engine + "Parameters in Path"

### ISSUE THREAD

**Issue by benguild** [gin-gonic/gin#721]
https://github.com/gin-gonic/gin#parameters-in-path
vs.
https://github.com/gin-gonic/gin/blob/master/examples/app-engine/hello.go

... Is it possible to combine these two concepts without hand-parsing things from the path?

**Comment by tboerger** [comment]
Can you explain what you mean? I don't really understand.

**Comment by benguild** [comment]
Fixed, it was a misunderstanding due to a 404 coming from `c.File()`.
