### ISSUE TITLE
Low-priority request: Handle App Engine "RemoteAddr" address correctly in `context.ClientIP`?

### ISSUE THREAD

**Issue by benguild** [gin-gonic/gin#723]
App Engine does not attach the client's port number to "RemoteAddr". Google says they have no plans to change this behavior: https://code.google.com/p/googleappengine/issues/detail?id=11730

Running it through `SplitHostPort()` can provide inconsistent behavior with IPv6, as the colons in the IPv6 address may cause the final block of a formatted IPv6 address to be truncated with the last portion being treated as the port.

**Comment by appleboy** [comment]
@benguild Already fixed by #755.

**Comment by benguild** [comment]
Thanks! @appleboy Is this just fixed in `develop` or is it pushed to `master` already?

**Comment by javierprovecho** [comment]
@benguild develop for now, we'll wait a few days to join more pr or solve issues for v1.2

**Comment by benguild** [comment]
Great, will monitor. Thanks.

**Comment by benguild** [comment]
@appleboy @javierprovecho just wondering what the "fix" was? there's still no port number (which is fine) but it's a bit risky if code could somehow get mistakenly deployed elsewhere, etc.
