### ISSUE TITLE
What is the best practices of writing web services using gin-gonic

### ISSUE THREAD

**Issue by selvam347** [gin-gonic/gin#736]
In other frameworks like Ruby on Rails, they are having directory structure like where to keep model related code, where to keep view related code, where to keep controller related code and where to seed DB. Is there any directory organization in gin-gonic? Or Any suggestion?

**Comment by metalmatze** [comment]
You're pretty much free to do what suits you best.
I saw this video a few weeks ago and to me it was pretty neat. But it's just one way of doing things.
https://www.youtube.com/watch?v=LMSbsW1Xpwg
