### ISSUE TITLE
Confusing Cruft Surrounding Validation

### ISSUE THREAD

**Issue by jonmchan** [gin-gonic/gin#738]
Could it be made explicit in the documentation that gin is using gopkg.in/go-playground/validator.v8 as the default validation library? I spent several hours thrown off thinking gin uses https://github.com/gin-gonic/validator and implemented validation against that based off of documentation at https://gowalker.org/github.com/gin-gonic/validator. It would appear that https://github.com/gin-gonic/validator is stale and not being developed anymore? Can that repository be removed or at least a disclaimer mentioned that this library is not in use with gin at the moment?

The documentation only describes being able to add a binding:"required", but there are much more available validation options available with validator.v8. It would be beneficial if at least a link to their documentation in the[ model binding and validation](https://github.com/gin-gonic/gin#model-binding-and-validation) section is provided.

**Comment by javierprovecho** [comment]
- [x] deleted gin-gonic/validator
- [x] [PR PROPOSED(#1024)] link validator.v8 docs at https://github.com/gin-gonic/gin#model-binding-and-validation

**Comment by jonmchan** [comment]
Thanks for resolving this! 👍
