### ISSUE TITLE
How do I change and publish html to response to the browsers request? 

### ISSUE THREAD

**Issue by kekemuyu** [gin-gonic/gin#740]
router.GET("/index",func(c *gin.Context){
		c.HTML(http.StatusOK, "upload.html", gin.H{
            "title": "Main website",
        })
	} )

If the the browser types http://......../index ,how do I parse the html and change it,and last publish it to the browser.

**Comment by tsirolnik** [comment]
Can you please provide us with the current output and the output that you want? As it is hard, at least for me, to understand your question

**Comment by iamsalnikov** [comment]
@kekemuyu, as I understood, your problem connected with that you change `upload.html` file, but in fact server answer with new markup only after restart? Am I right?

**Comment by kekemuyu** [comment]
Now I know my mistake，all because I'm too native to web programming.When i learned  template pacakge,I just know how to exchange data between html and go. anyhow thank you  the answers of upper layers.
