### ISSUE TITLE
Failed install gin

### ISSUE THREAD

**Issue by RTBathula** [gin-gonic/gin#743]
I tried to install gin by go get gopkg.in/gin-gonic/gin.v1,
But getting error like
![gin failed](https://cloud.githubusercontent.com/assets/7258031/20361827/c4e9041a-ac17-11e6-8548-e5f009838ff3.png)

**Comment by javierprovecho** [comment]
Maybe it was a temporaly error from `golang.org/x/net/context` or maybe is a bug of  `go get` in windows. Can't help without more info, try `git clone ... -C $GOPATH/...` and reopen if you are still unable to get it.
