### ISSUE TITLE
Why can not use vue,js?

### ISSUE THREAD

**Issue by Toplife** [gin-gonic/gin#747]

**Comment by Toplife** [comment]
When I use vue.js and start application, show below error:

panic: template: home.html:177: function "message" not defined

I used this router.LoadHTMLGlob("app/views/**") load

**Comment by Celthi** [comment]
How did you solve this problem? I encounter this problem when I try to write a simple example use Vue and Gin.

**Comment by Toplife** [comment]
You can try add below in new Vue({}) function.
`delimiters: ['&{', '}']`

And then try use like "&{item}" get value.

And I think you can try use vue+webpack as a front-end, then use gin as back-end. It`s better.
You can find example from my repository.

**Comment by Celthi** [comment]
@Toplife 
Thank you very much. I'll study your repo to get better understanding.
