### ISSUE TITLE
Hook for Response Middleware?

### ISSUE THREAD

**Issue by dvwright** [gin-gonic/gin#750]
It seems like the middleware ability via Use is designed to operate on Requests. I think it would be useful to provide a Response level middleware feature as well. (if there is a way to do this currently please point me to it) Thanks.

**Comment by tboerger** [comment]
If you are calling next first you should be able to manipulate the response after the rest of the processing.

**Comment by dvwright** [comment]
Thank you @tboerger I will look into that.
