### ISSUE TITLE
IsTerminal not available on Google App Engine

### ISSUE THREAD

**Issue by kujenga** [gin-gonic/gin#752]
A recent commit [1] brought in the use of the `terminal.IsTerminal` function. That function is not available at compile time on Google App Engine, as can be seen in the `!appengine` build tag for the file implementing it [2].

[1] https://github.com/gin-gonic/gin/commit/32cab500ecc71d2975f5699c8a65c6debb29cfbe#diff-40646a6e1108f49d452915ba3515c206
[2] https://github.com/golang/crypto/blob/master/ssh/terminal/util.go

**Comment by appleboy** [comment]
@kujenga We reverted the old PR and bump new version. Thanks for your reminder.

**Comment by appleboy** [comment]
@kujenga I fixed this issue on #754 and also merged into develop branch.

**Comment by kujenga** [comment]
Awesome, thanks so much for the quick turnaround!
