### ISSUE TITLE
Why Govendor and not Glide

### ISSUE THREAD

**Issue by robvdl** [gin-gonic/gin#757]
I just see that gin is in the middle of switching vendor tool. That is cool, but I am just wondering why Glide wasn't chosen instead, which was "supposed to be" the preferred vendoring tool for Go (at least I read that somewhere a while back).

https://github.com/Masterminds/glide/wiki/Go-Package-Manager-Comparison

Feel free the close this issue, it's mainly just a question.

**Comment by tboerger** [comment]
There is no official preferred dependency manager. We choose govendor because it really works like expected, is quite simple and pruning the unused subpackages directly works without using just another tool as glide rejects to add that to the core.
