### ISSUE TITLE
gopkg.in context.go call github? (render & binding)

### ISSUE THREAD

**Issue by gplume** [gin-gonic/gin#763]
Hello there,
Trying a new install I found context.go calling:
```
import (
	"github.com/gin-gonic/gin/binding"
        "github.com/gin-gonic/gin/render"
)
```
So a clean install with v1 package still need github develop libraries ?
I guess it's a 'forgotten'...?

**Comment by ckeyer** [comment]
@appleboy is this solved.

**Comment by Collapsik** [comment]
We wait)

**Comment by night-codes** [comment]
A very important issue.

**Comment by appleboy** [comment]
I will fix this asap.

**Comment by appleboy** [comment]
See the status https://github.com/gin-gonic/gin/pull/781#issuecomment-271309075

**Comment by appleboy** [comment]
Comment from @javierprovecho 

>  maybe, i'm not sure. for now just to update the import statement from github.com... to gopkg.in... to really pull/use the same commit when releasing the next version (for being visible from gin.v1 or master), if not, it will pull twice both from gopkg.in and github.com.

**Comment by night-codes** [comment]
#787 Knock - knock!

**Comment by appleboy** [comment]
@gplume I recommend that pull `gin` from `github.com` path. It is stable version in master and same with `gopkg.in` in v1. We are talking about how to resolve this issue in next version.
