### ISSUE TITLE
Possible to make NewContext in helpers_test importable?

### ISSUE THREAD

**Issue by mrjrieke** [gin-gonic/gin#764]
We have some code in our codebase that is untestable because it is difficult to make a complete test Context object like the one that is in helpers_test.  
CreateTestContext

Would it be possible to expose the CreateTestContext method in a way that users of this 3rd party library could import it?

**Comment by tboerger** [comment]
It's already done within the develop branch, so it's just a matter of time that it will be available. For reference: https://github.com/gin-gonic/gin/blob/master/helpers_test.go

**Comment by tboerger** [comment]
Wrong reference, https://github.com/gin-gonic/gin/blob/develop/test_helpers.go of course.

**Comment by mrjrieke** [comment]
Just tested and this change will indeed work for me.
