### ISSUE TITLE
How to call function in templates

### ISSUE THREAD

**Issue by dimasjt** [gin-gonic/gin#765]
Hello,
I want to call function in the template, the code is like this.

```html
<img src="{{ imageURL(.Image) }}" />
```

```go
func imageURL(u string){
  return "uploads/" + u
}
```

**Comment by dimasjt** [comment]
I'm just found the solution for handle this case.


```html
<img src="uploads/{{ .Image }}" />
```

but is there a way to call function in html template?

**Comment by tboerger** [comment]
Of course there are ways for that, that is plain stdlib functionality. You need to define your template function via the func map, stdlib is explained at https://golang.org/pkg/text/template/#example_Template_func
