### ISSUE TITLE
how can I change the htmltemplate Tags

### ISSUE THREAD

**Issue by hxdhero** [gin-gonic/gin#778]
if i use html/template  Delim ,i can't use html.rander in debug mode.

this caused me to restart the server everytime when i changed the template

**Comment by EtienneR** [comment]
I do something like this

```go
// A custom function
func TemplateMe(c *gin.Context, page string, data interface{}) {
	tmpl, err := template.New("").Delims("[[", "]]").ParseFiles("views/view_layout.html", "views/"+page)

	if err != nil {
		http.Error(c.Writer, err.Error(), http.StatusInternalServerError)
	}

	tmpl.ExecuteTemplate(c.Writer, "layout", data)
}

// A handler
func indexHandler(c *gin.Context) {
	data := gin.H{"Title": "Hello World!"}
	TemplateMe(c, "view_login.html", data)
}
```

**Comment by shenshouer** [comment]
I creat a PR for solve this. The PR is https://github.com/gin-gonic/gin/pull/860

**Comment by afiune** [comment]
Should you guys close this since the PR got merged?

**Comment by appleboy** [comment]
@afiune yes, see the following document.

https://github.com/gin-gonic/gin#custom-delimiters
