### ISSUE TITLE
Streaming POST request instead of using temp file

### ISSUE THREAD

**Issue by GregorioDiStefano** [gin-gonic/gin#785]
I noticed that POSTing a multipart/form request, results in a file being created into /tmp/.
Is there anyway around this? I want to stream the content of the request without creating temp files.

Thanks

**Comment by javierprovecho** [comment]
@GregorioDiStefano please post your code (or an example) so we can reproduce. However I think it must be an accepted behaviour of `net/http` standard package.

**Comment by GregorioDiStefano** [comment]
Using the upload example in the documentation:

```
package main

import (
    "fmt"
    "log"
    "io"
    "os"
    "gopkg.in/gin-gonic/gin.v1"
)

func main() {
    router := gin.Default()

    router.POST("/upload", func(c *gin.Context) {

            file, header , err := c.Request.FormFile("upload")
            filename := header.Filename
            fmt.Println(header.Filename)
            out, err := os.Create("./tmp/"+filename+".png")
            if err != nil {
                log.Fatal(err)
            }
            defer out.Close()
            _, err = io.Copy(out, file)
            if err != nil {
                log.Fatal(err)
            }   
    })
    router.Run(":8080")
}
```

Uploading a file (easier with a large one) you'll see a temp file is created in /tmp/.

**Comment by appleboy** [comment]
@GregorioDiStefano see https://github.com/gin-gonic/gin/pull/857

**Comment by GregorioDiStefano** [comment]
Nice, can test this a bit later!

**Comment by appleboy** [comment]
@GregorioDiStefano Thank you.

**Comment by appleboy** [comment]
merged
