### ISSUE TITLE
When fatal error occur the app shutdown

### ISSUE THREAD

**Issue by thedevsaddam** [gin-gonic/gin#788]
I am using this framework and testing an application. When I send heavy traffic using apache ab tool it shows this message:

```
Error 1040: Too many connections
exit status 1
```

How can I restart the app after an error like this.

**Comment by javierprovecho** [comment]
@thedevsaddam that's an sql error, not a gin one. You must make your db logic more efficient by reusing existing conns. take a look here: https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns
