### ISSUE TITLE
gin gzip is failed. maybe should fix it

### ISSUE THREAD

**Issue by gonboy** [gin-gonic/gin#792]
please check . the same to [Issue#400](https://github.com/gin-gonic/gin/issues/400)
------------------------------------------------------------
Yes. I found gzip is invalid.
```go
package main

import (
	"fmt"
	"github.com/gin-gonic/contrib/gzip"
	"github.com/gin-gonic/gin"
)
func main() {
	r := gin.Default()
	r.Use(gzip.Gzip(gzip.BestCompression))
	r.GET("/ping", func(c *gin.Context) {
		fmt.Println("return string")
		c.String(200, "welcome to china, baby")
	})
	r.Run(":80")
}
```
**GOPATH\src\github.com\gin-gonic\contrib\gzip\gzip.go**
```go
func Gzip(level int) gin.HandlerFunc {
	return func(c *gin.Context) {

		if !shouldCompress(c.Request) {
			return
		}

		gz, err := gzip.NewWriterLevel(c.Writer, level)
		if err != nil {
			return
		}

		c.Header("Content-Encoding", "gzip")
		c.Header("Vary", "Accept-Encoding")
		c.Writer = &gzipWriter{c.Writer, gz}

		defer func() {
			c.Header("Content-Length", "0")
			gz.Close()
		}()
		c.Next()
	}
}
```

**questions:**
1. if set 
`c.Header("xxxContent-Encoding", "aaa")`
`c.Header("123Content-Encoding", "aaa")`
you can track the before Http header .
but if set
`c.Header("Content-Encodingxxxx", "aaa")`
couldn't track it
<&emsp>
2.  couldn't find any zip information . except: **`Vary: Accept-Encoding`**
```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
Date: Thu, 19 Jan 2017 07:36:37 GMT
Content-Length: 22
welcome to china, baby
```

**Comment by easonlin404** [comment]
@gonboy I've tested. It seems like no problems. 
 please reference  https://github.com/gin-contrib/gzip/issues/4#issuecomment-311290589

**Comment by thinkerou** [comment]
@gonboy please see @easonlin404 comment, if still have problem please reopen it, now closing. thanks!
