### ISSUE TITLE
Should PostForm work for a DELETE request as well?

### ISSUE THREAD

**Issue by CameronGo** [gin-gonic/gin#795]
I have a DELETE request in our RESTFUL API that requires the use of form data.  We are using the same block of code as we are for our POST request, but in the DELETE request the PostForm function doesn't seem to find the form data.

This is a code excerpt for what is called from the router.  It looks the same under our POST request and works just fine.  If this doesn't work, are there any suggestions for how I get access to form data for use in a DELETE request?

```
func deleteRequest(c *gin.Context)

	//GET form data
	pfAccountCode := c.PostForm("account_code")

	//Verify required fields
	if pfAccountCode == "" {
		err := fmt.Errorf("Error proccessing transaction. Mssing required form data: account_code)
		log.Println(err.Error())

		return err
	}

}
```

**Comment by EtienneR** [comment]
Did you try with `c.Params.ByName` instead of `c.PostForm` ?

**Comment by FrozenKP** [comment]
I have the same problem. I used almost same code in PUT and DELETE, but only PUT can get form data. 
@EtienneR  I tried ```c.Params.ByName``` but it didn't work.

**Comment by appleboy** [comment]
@CameronGo @FrozenKP 

> If a DELETE request includes an entity body, the body is ignored [...]

http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

Please change `delete` to `post` method.

**Comment by FrozenKP** [comment]
got it. Thanks a lot.

**Comment by rafaeleyng** [comment]
Hey @appleboy, any chance to get the body form a `DELETE` request? I have to implement an API that complies to a spec that specifies a `DELETE` with a body using `x-www-form-urlencoded` (https://app.swaggerhub.com/apis/tsuru/tsuru-service_api/1.0.0#/Binding/delete_resources__name__bind), so I can't just change the method.
