### ISSUE TITLE
Can't redirect when using Bind

### ISSUE THREAD

**Issue by majimboo** [gin-gonic/gin#796]
I get the error:

    [GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 301

When using something like:

    var err = c.Bind(&form)
    if err != nil {
      c.Redirect(301, "/")
    }

I saw this on BindWith

    c.AbortWithError(400, err).SetType(ErrorTypeBind)

Looks like it did already send the status code. Anyway, what is the correct approach? I'm trying to create a registration page where I want to redirect back to the registration page to display the errors.

**Comment by mbesancon** [comment]
Bind happens on a POST action, so if there is an error, just render a page with the error displayed if that's what you want to show, you don't need to redirect. 
var err = c.Bind(&form)
if err != nil {
  // log on the server side
  log.Printf("Error while binding: %v", err)
  // display error to client
  c.String(400, "Woops, something wrong with the posted form")
}

**Comment by mbesancon** [comment]
Instead of redirecting, you can call directly the handler for get /register.
In the post handler:
```
c.Set("error", err)
```
In the get handler:
```
errInterface, found := c.Get("error")
// ... convert empty interface to error, render the error
```

**Comment by bsbak** [comment]
Have the some problem! But if i need Redirect and i dont wanna call it directly? Why so unreasoned system?

**Comment by AlexeyAtIgloo** [comment]
This one also seems to be related to my issue. #840 Bind errors handling are writing header so it cant be changed later. 

Try this method for your form bind
```
func SafeFormBind(obj interface{},c *gin.Context) error {
	if err := binding.Form.Bind(c.Request, obj); err != nil {
		return err
	}
	return nil
}
```

**Comment by thinkerou** [comment]
closing, please see #840
