### ISSUE TITLE
Download and install error

### ISSUE THREAD

**Issue by wvierber** [gin-gonic/gin#804]
Trying to download gin, I end up with following error:

```
$ go get gopkg.in/gin-gonic/gin.v1
# cd .; git clone https://gopkg.in/gin-gonic/gin.v1 /Users/wvierber/work/src/gopkg.in/gin-gonic/gin.v1
Cloning into '/Users/wvierber/work/src/gopkg.in/gin-gonic/gin.v1'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/gin-gonic/gin.v1: exit status 128
```

What am I missing / is this a known issue?

Thanks for helping me out!

**Comment by zhonglushu** [comment]
I thought that only China have this problem

**Comment by wvierber** [comment]
So far I know, Belgium is not a part of China...

**Comment by appleboy** [comment]
@wvierber Can't reproduce this problem.

**Comment by wvierber** [comment]
Bummer. Installing other packages isn't a problem...

**Comment by wvierber** [comment]
Found the solution over here: https://github.com/niemeyer/gopkg/issues/50

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.
