### ISSUE TITLE
How to set cookie?

### ISSUE THREAD

**Issue by adred** [gin-gonic/gin#818]
What am I doing wrong?
```
func handler(ctx *gin.Context) {
    ctx.SetCookie(
        "token",
	"testtoken",
	3600,
	"/",
	"127.0.0.1",
	false,
	false,
    )
}
```

It does not set cookie in the response header. Tested using postman.

**Comment by adred** [comment]
I realized I need to enable interceptor in Postman to get the cookie value.

**Comment by spbligr** [comment]
use SetCookie
