### ISSUE TITLE
binding issue with multipart form

### ISSUE THREAD

**Issue by onix-sergey** [gin-gonic/gin#820]
I'm trying to send file + some other field  and read via c.Bind:
 ```
type MyForm struct {
	Field1	int		`json:"field1" form:"field1" validate:"required"`
}
params := MyForm{}
if err := c.Bind(&params); err != nil {
    return nil, err
}
```
All works fine if send request via curl, but Postman or other similar tools got error:
`invalid URL escape "%\x1f\x1a"`

here is a request body from postman:
```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cache-Control: no-cache
Postman-Token: 78ac5597-fdcc-1cb8-0e61-9b62ceb68994

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="field1"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fileupload"; filename=""
Content-Type: 


------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by thinkerou** [comment]
Hi @onix-sergey please post more details about curl command and postman command and example code, thanks!

**Comment by onix-sergey** [comment]
Hi @thinkerou ,
already soon two years will be ... I think you can close the task

**Comment by kumarravi2** [comment]
In my case, the Content-Type was sent wrong in request . 
Instead of **multipart/form-data** ,  _application/x-www-form-urlencoded_  was sent causing above error at server.
 
Http Client used  : Retrofit
