### ISSUE TITLE
Cache busting assets

### ISSUE THREAD

**Issue by lukewendling** [gin-gonic/gin#826]
Anyone know how to add a cache-busting strategy for static assets? For instance js & css asset links would render like `script src="app.1449087601.js"` when output to html, but that file would route to the static file app.js. Static file support in gin does not seem to support regex matching, as in other (lesser!) web frameworks. Thanks!

**Comment by appleboy** [comment]
You need to try https://github.com/jteeuwen/go-bindata and see the example: https://github.com/wadahiro/gin-react-boilerplate
