### ISSUE TITLE
how to set header after write to response

### ISSUE THREAD

**Issue by cssivision** [gin-gonic/gin#827]
```go
package main

import "gopkg.in/gin-gonic/gin.v1"

func main() {
    r := gin.Default()
    r.Use(func(c *gin.Context) {
        c.Next()
        c.Set("fake-header", "fake")
    })
    r.GET("/ping", func(c *gin.Context) {
        c.JSON(200, gin.H{
            "message": "pong",
        })
        c.String(200, "vdvfgbf")
    })
    r.Run() // listen and serve on 0.0.0.0:8080
}
```

I know this operation ` c.Set("fake-header", "fake")`  will fail, the `fake-header` will store in response's `trailer` if we ` c.Set("trailer", "fake-header")`. 

but now i want to set header after write to response, how can i achieve this? @appleboy

**Comment by godcong** [comment]
try to use c.Writer.Header().Set(key, value) or c.Header(key, value string)
is that ok?
