### ISSUE TITLE
latest version couldn't be built

### ISSUE THREAD

**Issue by hiromaily** [gin-gonic/gin#828]
I upgrade by `go get -u` these days.
After that build failed.

```
# gopkg.in/gin-gonic/gin.v1
../../../gopkg.in/gin-gonic/gin.v1/context.go:498: cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
	sse.Event does not implement render.Render (missing WriteContentType method)
```

How can I handle it?

Error occur here.
```
// SSEvent writes a Server-Sent Event into the body stream.
func (c *Context) SSEvent(name string, message interface{}) {
	c.Render(-1, sse.Event{
		Event: name,
		Data:  message,
	})
}
```
parameter of c.Render is `render.Render`
```
func (c *Context) Render(code int, r render.Render) {
	c.Status(code)
	if err := r.Render(c.Writer); err != nil {
		panic(err)
	}
}
```

This struct has 2 funcs
```
type Render interface {
	Render(http.ResponseWriter) error
	WriteContentType(w http.ResponseWriter)
}
```

However `sse.Event` doens't have `WriteContentType`

**Comment by hiromaily** [comment]
```
func (r Redirect) WriteContentType(http.ResponseWriter) {}
```
is not implemented to sse.Event.

**Comment by hiromaily** [comment]
```
func (r Redirect) WriteContentType(http.ResponseWriter) {}
```
is not implemented to sse.Event.

**Comment by appleboy** [comment]
@hiromaily Could you help to try to replace `gopkg.in/gin-gonic` with `github.com/gin-gonic`?

**Comment by hiromaily** [comment]
Which is recommendable usually to import?

**Comment by appleboy** [comment]
@hiromaily I recommend import `github.com/gin-gonic/gin` for now.

**Comment by godcong** [comment]
i changed  gopkg.in/gin-gonic to github.com/gin-gonic

**Comment by appleboy** [comment]
also see the comment https://github.com/gin-contrib/sessions/issues/8#issuecomment-285866714

**Comment by appleboy** [comment]
@hiromaily Please changed `gopkg.in/gin-gonic` to `github.com/gin-gonic`

**Comment by hiromaily** [comment]
@appleboy 
Thanks! I got it!

**Comment by dieselburner** [comment]
Oh. Thanks for fixing this finally.
