### ISSUE TITLE
How to read request header

### ISSUE THREAD

**Issue by ponypaver** [gin-gonic/gin#830]
Hi Guys,

May I know how to read the request header from gin context ? It seems there is only a write header function in the document.

Thanks in advance.

**Comment by lixiangzhong** [comment]
ctx.Request.Header

**Comment by appleboy** [comment]
example:

```go
	return func(c *gin.Context) {
		c.Writer.Header().Set("X-Revision", "v1.2.3")
		c.Next()
	}
```

**Comment by FrozenKP** [comment]
Excuse me,
should we have a function like 
```go
c.GetHeader( key string) string
``` 
to easily get the value of specific header with key ?

**Comment by appleboy** [comment]
@FrozenKP 

```go
	if values, _ := c.Request.Header[key]; len(values) > 0 {
		return values[0]
	}
	return ""
```

**Comment by FrozenKP** [comment]
hmmm... Can I write this as a function and pull request ?  I think it would  be useful.

**Comment by appleboy** [comment]
@ponypaver @FrozenKP I add new func `GetHeader` in develop branch. see #839

**Comment by viethocle** [comment]
c.Request.Header.Get("param")

**Comment by eloyekunle** [comment]
`c.GetHeader("param")` is much simpler

**Comment by Ruwantha-OFFICIAL** [comment]
```go

func (c *Context) GetHeader(key string) string
```

Example :-

```go

r.Get("/",func(c gin.Context){
  //clean & easy understand
  name:= c.GetHeader("name")
  return c.JSON(200,gin.H{ "You Name":name})
})
```
