### ISSUE TITLE
CreateTestContext should be exported

### ISSUE THREAD

**Issue by tmlbl** [gin-gonic/gin#842]
The function is capitalized, which suggests in idiomatic Go that it should be exported. However, the file is named `helpers_test.go` instead of `test_helpers.go`. The former name suggests that it is actually testing some helpers, and since it ends in `_test.go`, it is not exported.

Proposal: renaming the file.

**Comment by appleboy** [comment]
Has been renamed in `develop` branch

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/gin/blob/develop/test_helpers.go
