### ISSUE TITLE
url.String() missing host

### ISSUE THREAD

**Issue by kas240sx89** [gin-gonic/gin#845]
hi,
not sure if this is a isolated issue, but i am trying to use context.Request.Url.String() to build pagination links. using the golang net/url i can build the links perfectly. but when i try to grab the url from context.Request.Url.String all i get back is the path, the entire host (http://www.mysite.com) is missing, even the URL.HostName() is empty. im not sure why gin is not showing this when golang's url package returns the full url in .String().

is there another way to get the complete URL from gin or do i need to rebuild it.
Thanks for the help

**Comment by kas240sx89** [comment]
turns out this is a issue with http.Request on local testing or proxy connection

**Comment by tboerger** [comment]
Maybe the location middleware helps you: https://github.com/gin-contrib/location
