### ISSUE TITLE
Deffered header write

### ISSUE THREAD

**Issue by dfilipovic39** [gin-gonic/gin#85]
It would be very nice to have this. Lets say i want to have sessions and i need the header to be written before the response. Currently there i no way to do that.
Martni framework has it solved with Before function on custom ResponseWriter
https://github.com/go-martini/martini/blob/master/response_writer.go#L13

**Comment by dragonly** [comment]
Hi guys, after all those years, I bump into the same problem here! any cleaner solutions with middleware to write the `x-response-sent` header?

**Comment by luza** [comment]
Hey everyone. Here is how I eventually solved the problem:
https://gist.github.com/luza/dca5936637f525848d67e49e21820f93

Hope it will help.
