### ISSUE TITLE
Unescape HTML in template

### ISSUE THREAD

**Issue by flexwie** [gin-gonic/gin#858]
How can I unescape HTML when using the gin template engine?

`c.HTML(http.StatusOK, "index.tmpl", gin.H{
	"title": "<h1>Title</h1>", //Unescape this
})`

**Comment by steelbrain** [comment]
You should use typed strings to make gin not escape them. From a quick google search I found [`template.HTML`](https://golang.org/pkg/html/template/#HTML) :)

**Comment by flexwie** [comment]
Works fine, thank you!
