### ISSUE TITLE
How to call function in templates

### ISSUE THREAD

**Issue by a57571735** [gin-gonic/gin#867]
hi:
I did everything  I could to do, How to call function in templates
![image](https://cloud.githubusercontent.com/assets/20694884/24700046/93be24fe-1a28-11e7-9f9f-b3ef31263d07.png)
![image](https://cloud.githubusercontent.com/assets/20694884/24700071/a0ec8116-1a28-11e7-9940-9da466b62f99.png)
![image](https://cloud.githubusercontent.com/assets/20694884/24700088/aa5514b6-1a28-11e7-96eb-dca91a519b4f.png)
see....

![image](https://cloud.githubusercontent.com/assets/20694884/24700196/f974a520-1a28-11e7-98fa-47cfaf9bf5e9.png)
![image](https://cloud.githubusercontent.com/assets/20694884/24700223/0a948ffa-1a29-11e7-8571-58b1674e97e2.png)
![image](https://cloud.githubusercontent.com/assets/20694884/24700233/12d5acda-1a29-11e7-8dca-7336fbfb8c26.png)
see....

**Comment by a57571735** [comment]
use this https://github.com/michelloworld/ez-gin-template，in my custom version ,I supproted areas

**Comment by a57571735** [comment]
`package middleWare

import (
	"html/template"
	"log"
	"path/filepath"
	"strings"

	"github.com/gin-gonic/gin/render"
)

type Render struct {
	Templates map[string]*template.Template
	Config    []*LayoutConfig
	Debug     bool
}
type LayoutConfig struct {
	Layout      string
	Views       string
	Prefix      string
	IgnoreViews []string
	Ext         string
	FuncMap     map[string]interface{}
}

func New() Render {
	r := Render{
		Templates: map[string]*template.Template{},
		Config:    []*LayoutConfig{&LayoutConfig{}},
		Debug:     false,
	}

	return r
}

func (r Render) Init() Render {
	for _, v := range r.Config {
		layout := v.Views + v.Layout + v.Ext
		viewDirs, _ := filepath.Glob(v.Views + "**/*" + v.Ext)
	lable:
		for _, view := range viewDirs {
			if strings.Contains(strings.Replace(view, `\`, "/", -1), v.Layout) {
				continue lable
			}

			renderName := getRenderName(view, v.Prefix)
			if r.Debug {
				log.Printf("[GIN-debug] %-6s %-25s --> %s\n", "LOAD", view, renderName)
			}
			conti := false
			for _, ignore := range v.IgnoreViews {
				if strings.Contains(view, ignore+v.Ext) {
					r.AddFromFile(v, renderName, view)
					conti = true
				}
			}
			if !conti {
				r.AddFromFiles(v, renderName, layout, view)
			}
		}
	}

	return r
}

func getRenderName(tpl, prefix string) string {
	_s := strings.Replace(tpl, `\`, "/", -1)
	_c := strings.Count(_s, "/")
	return prefix + strings.Split(strings.SplitAfterN(_s, "/", _c)[_c-1], ".")[0]
}

func (r Render) Add(name string, tmpl *template.Template) {
	if tmpl == nil {
		panic("template can not be nil")
	}
	if len(name) == 0 {
		panic("template name cannot be empty")
	}
	r.Templates[name] = tmpl
}

func (r Render) AddFromFiles(v *LayoutConfig, name string, files ...string) *template.Template {
	tmpl := template.Must(template.New(filepath.Base(v.Layout + v.Ext)).Funcs(v.FuncMap).ParseFiles(files...))
	r.Add(name, tmpl)
	return tmpl
}
func (r Render) AddFromFile(v *LayoutConfig, name string, file string) *template.Template {
	tmpl := template.Must(template.New(filepath.Base(file)).Funcs(v.FuncMap).ParseFiles(file))
	r.Add(name, tmpl)
	return tmpl
}

func (r Render) Instance(name string, data interface{}) render.Render {
	return render.HTML{
		Template: r.Templates[name],
		Data:     data,
	}
}
`
to use

`	Router = gin.Default()
	render := middleWare.New()
	render.Config = []*middleWare.LayoutConfig{
		&middleWare.LayoutConfig{
			Layout: "shard/layout",
			Views:  "view/",
			Ext:    ".html",
		},
		&middleWare.LayoutConfig{
			Layout:      "shard/layout",
			Views:       "area/admin/view/",
			Ext:         ".html",
			Prefix:      "admin/",
			IgnoreViews: []string{"login"},
			FuncMap: map[string]interface{}{
				"Contains": func(s1, s2, s3 string) string { //s1是否包含s2返回s3否则返回空字符串
					if strings.Contains(s1, s2) {
						return s3
					}
					return ""
				},
				"StatusItoA": func(i int) string {
					switch i { //0:待审核 1:正常，2:已删除
					case 0:
						return "待审核"
					case 1:
						return "正常"
					case 2:
						return "已删除"
					default:
						return ""
					}
				},
				"StatusItoClass": func(i int) string {
					switch i { //0:待审核 1:正常，2:已删除
					case 0:
						return "label-info"
					case 1:
						return "label-success"
					case 2:
						return "label-danger"
					default:
						return ""
					}
				},
			},
		},
	}

	Router.Use(HTTPModule())
	Router.Use(gzipHelper.Gzip(gzipHelper.DefaultCompression))
	//Router.LoadHTMLGlob("view/**/*")
	Router.HTMLRender = render.Init()`

**Comment by thinkerou** [comment]
@a57571735 please read https://github.com/gin-gonic/gin#custom-template-funcs and closing, if still have problem please reopen and discuss, thanks!
