### ISSUE TITLE
how do we return an array of json as response

### ISSUE THREAD

**Issue by haoxian-zhao** [gin-gonic/gin#87]
from the example looks like we can only return a single json file for response? could you please advice? thanks

**Comment by thellimist** [comment]
```
type Tag struct {
	Name          string `json:"name" form:"name" binding:"required"`
	Description   string `json:"description" form:"description" binding:"required"`
	ExtraData   TagExtra `json:"extra"`
}

tags := getTags() // which return []Tag

c.JSON(200, tags)
```
results is although ExtraData exist
```
[
  {
    "name": "question",
    "description": "question is something cool",
    "ExtraData": {}
  },
  {
    "name": "intro",
    "description": "intro is something cool",
    "ExtraData": {}
  },
...
]
```
when assigning to an interface slice everything seems to work out.

```
type Tag struct {
	Name          string `json:"name" form:"name" binding:"required"`
	Description   string `json:"description" form:"description" binding:"required"`
	ExtraData   TagExtra `json:"extra"`
}

tags := getTags() // which return []Tag

var interfaceSlice []interface{} = make([]interface{}, len(tags))
for i, tag := range tags {
    interfaceSlice[i] = tag
}

c.JSON(200, interfaceSlice) 
````
```
[
  {
    "name": "question",
    "description": "question is something cool",
    "ExtraData": 
    {
       "id": 1,
       "created_at": "2015-08-25T00:35:55.408537Z"
       ...
  },
...
]
```

**Comment by TheRealKira** [comment]
Try taking your []Tag slice and converting it to a []byte slice and write
it manually like this:

byteSlice,err := json.Marshal(yourSlice)
if err != nil {
panic(err)
}
c.Writer.Header().Set("Content-Type","application/json")
c.Writer.WriteHeader(200)
c.Writer.Write(byteSlice)

Can you see ExtraData in the json output if you do it this way? Do you get
an error at all? Maybe this can give you some more insight as to how your
Struct is being misinterpreted by gins c.JSON function ;)

**Comment by thellimist** [comment]
```
byteSlice,err := json.Marshal(yourSlice)
if err != nil {
panic(err)
}
c.Writer.Header().Set("Content-Type","application/json")
c.Writer.WriteHeader(200)
c.Writer.Write(byteSlice)
```

this doesn't work. 
> You say, "nested arrays"..

I meant "nested structs"  sorry for that misunderstanding. Edited the comment

**Comment by TheRealKira** [comment]
@thellimist could you post the code for your getTags() function? I'm trying to figure out where in your Extra struct the non interface type screws with encoding/json.

When you said array I knew you meant slice, I just wanted to make sure you were storing a slice []ExtraData and not just ExtraData in your top level struct.

**Comment by thellimist** [comment]
@TheRealKira 
```
type Tag struct {
    Name          string `json:"name" form:"name" binding:"required"`
    Description   string `json:"description" form:"description" binding:"required"`
    ExtraData   TagExtra `json:"extra"`
}

type TagExtra struct {
	TypeInformation   TypeInformation `json:"type_information"`
	SenderUser        User            `json:"sender_user"`
}
```

and getTags returns `[]Tag`. The inner struct (TagExtra) screws encoding/json somehow.
```
tags := getTags() 

var interfaceSlice []interface{} = make([]interface{}, len(tags))
for i, tag := range tags {
    interfaceSlice[i] = tag
}

c.JSON(200, tags[0]) // returns TagExtra's information correctly
c.JSON(200, tags) // returns TagExtra's information empty
c.JSON(200, interfaceSlice) // returns TagExtra's information correctly
```

So expected result will be something like
```
[
  {
    "name": "question",
    "description": "question is something cool",
    "extra": 
    {
       "type_information":
       {
               ...
       },
      "sender_user":
       {
               ...
       }
   }
  },
...
]
```
but instead it returns
```
[
  {
    "name": "question",
    "description": "question is something cool",
    "extra":  {}
  },
...
]
```

I hope I was able to clarify. Thank you.

**Comment by Praying** [comment]
> @TheRealKira
> 
> ```
> byteSlice,err := json.Marshal(yourSlice)
> if err != nil {
> panic(err)
> }
> c.Writer.Header().Set("Content-Type","application/json")
> c.Writer.WriteHeader(200)
> c.Writer.Write(byteSlice)
> ```
> 
> this doesn't work.
> 
> > You say, "nested arrays"..
> 
> I meant "slice of nested structs" sorry for that misunderstanding. Edited the comment

I also want to know how to response that string as json.
