### ISSUE TITLE
upgrade protobuf version

### ISSUE THREAD

**Issue by stran12** [gin-gonic/gin#873]
Can you upgrade your version of protobuf to the newest version so that it may be compatible with google cloud datastore library at cloud.google.com/go/datastore.

Thanks!

**Comment by appleboy** [comment]
@stran12 We change the vendor tool from [godep](https://github.com/tools/godep) to [govendor](https://github.com/kardianos/govendor). Please see the protobuf version in `develop` branch.

https://github.com/gin-gonic/gin/blob/develop/vendor/vendor.json#L18-L23

**Comment by stran12** [comment]
Any particular reason? Because I switched from govendor to godep and that solved my dependency issue.

**Comment by appleboy** [comment]
@tboerger can answer your question. I don't have `godep` experience yet.

**Comment by cgarvis** [comment]
Protobuf has added `Timestamp` (https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto) which the version that gin relies on does not have.

https://github.com/gin-gonic/gin/blob/master/Godeps/Godeps.json#L1

**Comment by pbnsilva** [comment]
@stran12 I'm facing the same issue, gin's old protobuff dependencies is making me go into a rabbit hole. Any tips?

**Comment by appleboy** [comment]
@stran12 @cgarvis @pbnsilva I already updated in https://github.com/gin-gonic/gin/issues/936
