### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by jkvarela** [gin-gonic/gin#885]
I'm trying to send a message back to my server but I'm having a problem with quotes and backslash.
 I need to receive this: 

_**{  "message"  :   {  "data1"  :  "data2"  }  }**_

But I'm getting this: 

_**{  "message"  :  "{  \ "data1\ "  :  \ "data2\ "  }" }**_

(I put spaces in the example, otherwise the correct sentence does not appear)

The software is like this: 

_**message := "{\ "data1\ ":\ "data2\ "}"
c.JSON(200, gin.H{"message": message})**_

(I put spaces in the example, otherwise the correct sentence does not appear)

Can anyone help me? thank you

Juliano

**Comment by appleboy** [comment]
```go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func ginEngine() *gin.Engine {
	router := gin.Default()
	router.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"message": gin.H{"data1": "data2"}})
	})

	return router
}

func main() {
	r := ginEngine()
	r.Run(":8080")
}
```

**Comment by Ttou** [comment]
same problem

**Comment by thinkerou** [comment]
@jkvarela @Ttou As @appleboy post example it's ok.
