### ISSUE TITLE
Use gin with NewRelic

### ISSUE THREAD

**Issue by tspecht** [gin-gonic/gin#888]
Hey guys,

I'm currently struggeling to integrate NewRelic (https://github.com/newrelic/go-agent) with my gin-gonic application. Are there any examples or maybe even a ready-made plugin available I could use?

**Comment by appleboy** [comment]
See: https://github.com/newrelic/go-agent/pull/28

**Comment by tspecht** [comment]
Awesome, thanks a lot!
