### ISSUE TITLE
When will test_helper.go(CreateTestContext) be merged into master?

### ISSUE THREAD

**Issue by odg0318** [gin-gonic/gin#899]
Hello.

I am using gin with govendor and hope to test using `CreateTestContext`
I found the function in `helper_test.go`.
But when vendoring, all files whose suffix is `_test` are skipped and so I cannot vendor `helper_test.go`.
I found `test_helper.go` in `develop` branch.

Can you tell me when `helper_test.go` in `develop` branch will be merged into `master`?

Best regards

**Comment by appleboy** [comment]
See https://github.com/gin-gonic/gin/pull/871
