### ISSUE TITLE
Some times gin.Context's Writer.Size get -1 when request end

### ISSUE THREAD

**Issue by bullub** [gin-gonic/gin#907]
e.g.
```
engine.Use(Logger)  //Logger is first registed middleware for gin
func Logger(c *gin.Context) {
       
	c.Next()

	contentLength := c.Writer.Size()

	fmt.Printf("size=%d", contentLength)
       //when 404 The contentLength is -1
}
```
sorry, I only know a little English，I'am Chinese.

**Comment by ammario** [comment]
The `-1` indicates no data was written.

**Comment by bullub** [comment]
But the response header `Content-Length's` value is 18.
```
HTTP/1.1 404 Not Found
Content-Type: text/plain
Date: Tue, 09 May 2017 04:45:40 GMT
Content-Length: 18
Connection: close

404 page not found
```

**Comment by easonlin404** [comment]
@bullub c.Writer.Size() `-1` is right because haven't be written any resposne data.
gin will write default message like `404 page not found`after middlewares(handlers chain) is ended if can't match any handler, and then you got response header `Content-Length`'s value is 18.

https://github.com/gin-gonic/gin/blob/develop/gin.go#L361

```go
func serveError(c *Context, code int, defaultMessage []byte) {
	c.writermem.status = code
	c.Next() //call your middleware
	
	if !c.writermem.Written() {
		if c.writermem.Status() == code {
			c.writermem.Header()["Content-Type"] = mimePlain
			c.Writer.Write(defaultMessage) // eg: http code 404, defaultMessage == "404 page not found"
			//c.writermem.size == 18
		} else {
			c.writermem.WriteHeaderNow()
		}
	}
}
```

**Comment by thinkerou** [comment]
@bullub please see @easonlin404 comment, thanks!

**Comment by rikewang** [comment]
why the default size is -1, not zero. 0 means not write data I think is ok.
