### ISSUE TITLE
gin is vendored as two copies

### ISSUE THREAD

**Issue by go101** [gin-gonic/gin#911]
when use `glide install`, gin is vendored as two compies. The same for `go get ./...`.
one is `github.com/gin-gonic/gin`, the other is `gopkg.in/gin-gonic/gin.v1/`.

**Comment by appleboy** [comment]
Please don't use `gopkg.in/gin-gonic/gin.v1/`.

**Comment by go101** [comment]
But the the example in the project home uses it.

**Comment by appleboy** [comment]
@go101 We will update the example in next release v1.2 https://github.com/gin-gonic/gin/pull/871

**Comment by go101** [comment]
ok
