### ISSUE TITLE
Incompatibility issue with "gopkg.in/robfig/cron.v2" package

### ISSUE THREAD

**Issue by Swatiparbhakar** [gin-gonic/gin#920]
Hello,
I have created 2 functions in main function.
1) For my routing
2) For run cron
But my issue is: when cron is working then routing stop works.
If I commented the RunCron()	 function then NewRouter() function works perfectly.
If I put NewRouter() function  on top then RunCron()  stop working.
Please help me to figure what is the issue of routing with crons.
My code is below:
```
func main(){
     RunCron()	
     NewRouter()
} 
func RunCron(){
	c := cron.New()
	c.AddFunc("0 * * * * *", func() { fmt.Println("Run every minute") })
    go c.Start()
    sig := make(chan os.Signal)
    signal.Notify(sig, os.Interrupt, os.Kill)
    <-sig
}
func NewRouter(){
	router := gin.Default()
    router.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
    router.Run(":8080")
    
}
```

**Comment by easonlin404** [comment]
@Swatiparbhakar it's **NOT** incompatibility issue with "gopkg.in/robfig/cron.v2".

Because channel `sig` is waiting to receive os.Interrupt/os.Kill signal messages, it will block the calling goroutine and then `NewRouter()` function is not be called.
And `router.Run(":8080")` is a shortcut for `http.ListenAndServe(addr, router)` , it will block the calling goroutine too.

Maybe you could comment out sig snippets as follows:

``` go
func main() {
	RunCron()
	NewRouter()
}
func RunCron() {
	c := cron.New()
	c.AddFunc("0 * * * * *", func() { fmt.Println("Run every minute") })
	c.Start()
}
func NewRouter() {
	router := gin.Default()
	router.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "ping",
		})
	})

	router.Run(":8080")
}
```

**Comment by appleboy** [comment]
@Swatiparbhakar You don't need to handle go-routine for cron since `robfig/cron` already has implemtneted. See https://github.com/robfig/cron/blob/master/cron.go#L138-L145

```go
func (c *Cron) Start() {
	if c.running {
		return
	}
	c.running = true
	go c.run()
}
```

**Comment by zheeeng** [comment]
How to let `cron` be interactive to gin framework? Want to add API calling to cron tasklist.
