### ISSUE TITLE
Add an authorization middleware based on Casbin

### ISSUE THREAD

**Issue by hsluoyz** [gin-gonic/gin#922]
Hi, I'm the author of [Casbin](https://github.com/casbin/casbin). It is a Go authorization library that supports access control models like ACL, RBAC, ABAC.

Related to the most popular RBAC model, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

The model in Casbin is very flexible and can easily adapt to certain scenarios by modifying the model file. Other features about Casbin please refer to: https://github.com/casbin/casbin

I found Gin has a middleware named ``BasicAuth``, but it is mainly authentication (AuthN) instead of authorization (AuthZ). I'd like to contribute to make an authorization middleware for Gin. But I don't know the correct process to do it. Also I want to hear your opinions first, please let me know if you have any questions or suggestions. Thanks!

**Comment by hsluoyz** [comment]
Already sent a PR here: https://github.com/gin-gonic/gin/pull/925. Please advise, thanks!

**Comment by appleboy** [comment]
@hsluoyz New repo: https://github.com/gin-contrib/authz

**Comment by hsluoyz** [comment]
@appleboy  thanks for all the help:)
