### ISSUE TITLE
How to disable the "Found." link on HTTP redirect

### ISSUE THREAD

**Issue by mysticmode** [gin-gonic/gin#926]
I'm redirecting signin to home page when the user is already signed in. It shows this html element on the home page.
`<a href="/signin">Found</a> "."`

How to disable that element from the app?

This is my app code.
```
func GetSignIn(c *gin.Context) {
    // Get session from cookie. Check if email exists
    // redirect to Home page else show signin page.
    session := sessions.Default(c)
    if session.Get("email") != nil {
        fmt.Println(session.Get("email"))
        c.Redirect(302, "/")
    }
    c.HTML(200, "signin.html", "")
}
```

**Comment by nazwa** [comment]
I think it's a Go thing. Looking at implementation, nothing unusual stands out:

```go

func (r Redirect) Render(w http.ResponseWriter) error {
	if (r.Code < 300 || r.Code > 308) && r.Code != 201 {
		panic(fmt.Sprintf("Cannot redirect with status code %d", r.Code))
	}
	http.Redirect(w, r.Request, r.Location, r.Code)
	return nil
}
```
https://github.com/gin-gonic/gin/blob/master/render/redirect.go#L18

**Comment by nazwa** [comment]
Indeed.

https://github.com/golang/go/blob/master/src/net/http/server.go#L2014
```go

	// RFC 2616 recommends that a short note "SHOULD" be included in the
	// response because older user agents may not understand 301/307.
	// Shouldn't send the response for POST or HEAD; that leaves GET.
	if r.Method == "GET" {
		note := "<a href=\"" + htmlEscape(urlStr) + "\">" + statusText[code] + "</a>.\n"
		fmt.Fprintln(w, note)
	}
```

That comment makes a valid point - why are you GETting your authentication endpoint anyway? 😄

**Comment by mysticmode** [comment]
@nazwa Thank you. You still haven't answered my question. How to do the authentication endpoint? I'm new to this. You could check my code here
https://github.com/mysticmode/LibreRead/blob/master/server.go

**Comment by nazwa** [comment]
I feel like you could set the location header yourself with an empty body.
