### ISSUE TITLE
handleHTTPRequest should use EscapedPath?

### ISSUE THREAD

**Issue by chanceraine** [gin-gonic/gin#935]
On https://github.com/gin-gonic/gin/blob/master/gin.go#L272, handleHTTPRequest uses URL.Path to determine the route. 
```
func (engine *Engine) handleHTTPRequest(context *Context) {
	httpMethod := context.Request.Method
	path := context.Request.URL.Path
```
 This means that visiting `/route/encoded%2Fpath/another/route` will attempt to route with `/route/encoded/path/another/route`, which will break routing if it expected to have a route of the form `/route/:path/another/route`. I suppose it's possible that this is intended behavior, but I believe there are real use cases where passing an encoded path as a path parameter is useful. Using `URL.EscapedPath()` instead of `URL.Path` would allow encoded paths to be used as parameters.

**Comment by easonlin404** [comment]
@chanceraine this issue has already been fixed in develop branch, you can try the develop branch (the latest version) and enable ```route.UseRawPath = true``` , the url.RawPath will be used to find parameters:

https://github.com/gin-gonic/gin/blob/develop/routes_test.go#L423

```go
route := New()
route.UseRawPath = true
route.UnescapePathValues = false

route.POST("/project/:name/build/:num", func(c *Context) {
        name := c.Params.ByName("name")
	num := c.Params.ByName("num")

	assert.Equal(t, c.Param("name"), name)
	assert.Equal(t, c.Param("num"), num)

	assert.Equal(t, "Some%2FOther%2FProject", name)
	assert.Equal(t, "333", num)
})

w := performRequest(route, "POST", "/project/Some%2FOther%2FProject/build/333")
```

**Comment by appleboy** [comment]
Please reopened this issue if you face the same problem in `develop` branch

**Comment by chanceraine** [comment]
Great, thanks for letting me know! Any idea when develop will get merged to master next?

**Comment by appleboy** [comment]
https://github.com/gin-gonic/gin/pull/871 I will contact @javierprovecho
