### ISSUE TITLE
What is the best way for read the design-time URI at run-time?

### ISSUE THREAD

**Issue by FrankIT60** [gin-gonic/gin#937]
For example,
If I register a router method:

    r.GET("/users/:user_id", user_get)

at runtime I can retrieve string "/users/:user_id" ?

Thanks in advance
Franco

**Comment by easonlin404** [comment]
what is ```design-time URI``` you meant? Can you describe more specific or post your example code?

**Comment by FrankIT60** [comment]
At runtime I need to get  the `"/users/:user_id"` string.
In RequestPath I have `"/users/123"`
For me `"/users/:user_id"` is like a fingerprint, is valid for `"/users/123"` or `"/users/456"`, but I need this string at runtime.

**Comment by FrankIT60** [comment]
Sorry, I have inadvertently close the thread

**Comment by easonlin404** [comment]
You can use `c.Request.RequestURI `  to get request URI 

```go
r.GET("/users/:user_id", func(c *gin.Context) {
    // a GET request to /users/123
    requestURI := c.Request.RequestURI // requestURI == "/users/123"
})
```

**Comment by FrankIT60** [comment]
The same as `c.Request.URL.Path`
I need to write a middleware. In my example `r.GET("/users/:user_id", user_get)`, I need to intercept function `user_get` before execution.
I can obtain this with parse and manipulate string, but I think the string `"/users/:user_id"`  is recorded somewhere.
Thanks for help.

**Comment by easonlin404** [comment]
@FrankIT60 maybe you can consider to pass `relativePath` in handler just like:

```go

func main() {
	r := gin.New()

	relativePath := "/users/:user_id"
	r.GET(relativePath, user_get(relativePath))

	r.Run()
}
func user_get(path string) gin.HandlerFunc {
	return func(c *gin.Context) {
		// a GET request to /user/123
		//requestURI := c.Request.RequestURI // requestURI == "/user/123"

		fmt.Println(path) // path == "users/:user_id"
	}

}

```

**Comment by FrankIT60** [comment]
This is one solution. I already use a similar solution. But with hundreds URI (and hundreds function like  `user_get`) If I can intercept the fingerprint before entering the function, I save a lot of code.
Thanks anyway for your interest.

**Comment by SCKelemen** [comment]
@FrankIT60 Is there any reason you can't just get it from the gin context?

**Comment by FrankIT60** [comment]
The simple reason is to write less code. I need to use `"/user/:user_id" `  like a fingerprint.
In the @easonlin404 solution I know the fingerprint when I am inside the function. I need to know the fingerprint before the function execution.

**Comment by mymtwcom** [comment]
I don't know exactly, but if you still didn't get answer, it looks like `gin` not writes your url `"fingerprint"` in `*context`.
And, I even don't know such frameworks, that doing this :)
But what the problem to write middleware, and put your `"fingerprint"` into *context yourself? 
```
func PutFingerPrint(fingerPrint string) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Set("finger_print", fingerPrint)
	}
}

r.GET("/users/:user_id", PutFingerPrint("/users/:user_id"), user_get)

func user_get(c *gin.Context) {
        currentFingerPrint := c.MustGet("finger_print").(string)
        fmt.Println(currentFingerPrint)
}
```

Then you will can use the same middleware for other controllers:
```
r.GET("/users/:user_id", PutFingerPrint("/users/:user_id"), user_get)
r.GET("/admin/:admin_id", PutFingerPrint("/admin/:admin_id"), admin_get)
r.GET("/anyoneyet/:anyoneyet_id", PutFingerPrint("/anyoneyet/:anyoneyet_id"), anyoneyet_get)
```

**Comment by cch123** [comment]
@mymtwcom gives a good solution, you could combine middleware and router group to simplify your logic.

**Comment by FrankIT60** [comment]
Yes. I think this is the only solution. Inside the function `PutFingerPrint(...)` I know the "fingerprint".
The boring part is that I have to write and keep synchronized the `relativePath` and the `fingerPrint`.
Thanks.
Franco
