### ISSUE TITLE
Debug output formatted incorrectly in Windows

### ISSUE THREAD

**Issue by SCKelemen** [gin-gonic/gin#949]
When I run this service on OS X, output is as expected, but in Windows there are characters that are unable to be displayed. 

Windows 10

```
[GIN-debug] Listening and serving HTTP on 127.0.0.1:6969
[GIN] 2017/06/13 - 13:42:26 |[97;43m 404 [0m|            0s | 127.0.0.1 |[97;44m  [0m GET     /c
[GIN] 2017/06/13 - 13:42:30 |[97;43m 404 [0m|       501.3µs | 127.0.0.1 |[97;44m  [0m GET     /favicon.ico
[GIN] 2017/06/13 - 13:43:26 |[97;42m 200 [0m|            0s | 127.0.0.1 |[97;44m  [0m GET     /api/v1/c
```
![image](https://user-images.githubusercontent.com/4325375/27096287-952a6450-503e-11e7-92ba-4d1e534e4607.png)

**Comment by bbrks** [comment]
[mattn/go-colorable](https://github.com/mattn/go-colorable) seems to be a popular way of doing cross-platform color escape codes.

Might be worth refactoring the [hard-coded ANSI escape codes in logger.go](https://github.com/gin-gonic/gin/blob/e2212d40c62a98b388a5eb48ecbdcf88534688ba/logger.go#L16-L25) to use this?

**Comment by easonlin404** [comment]
@SCKelemen could you please try again as follows?

To support coloring in Windows use:
```go
import "github.com/mattn/go-colorable"
gin.DefaultWriter = colorable.NewColorableStdout()
```
https://github.com/gin-gonic/gin/blob/master/mode.go#L31

**Comment by nazwa** [comment]
How strange. Everything displays fine for me

![](https://maciej.im/u/MTkyNQ/2017-06-14-17-59-19.png)

But maybe it's because I tun everything through ConEmu and not the raw command prompt...
I remember having issues with those color tags months ago, but they suddenly disappeared one day 😄

**Comment by SCKelemen** [comment]
Under OS X, there seems to be a bug in that package where the line color is never reset:
<img width="812" alt="screen shot 2017-06-14 at 17 34 58" src="https://user-images.githubusercontent.com/4325375/27157600-02401b36-5128-11e7-9cb5-030d73c11600.png">
<img width="806" alt="screen shot 2017-06-14 at 17 34 36" src="https://user-images.githubusercontent.com/4325375/27157599-023d96e0-5128-11e7-8587-93bfe7e7bcef.png">
 This appears to be a bug though.... I was playing around with it earlier, and it seems like it's due to some unfriendly conventions. https://github.com/sckelemen/gocat

**Comment by SCKelemen** [comment]
Under Windows 10, cmd.exe, there bug persists:
![image](https://user-images.githubusercontent.com/4325375/27157728-1e347a68-5131-11e7-8030-569b26481a41.png)
You can get the test code at https://github.com/sckelemen/mstodo

**Comment by SCKelemen** [comment]
If you want me to try it with CMDR or some other shell/terminal emulator, let me know

**Comment by appleboy** [comment]
@SCKelemen Working on my MacOS

![screen shot 2017-06-16 at 10 01 25 am](https://user-images.githubusercontent.com/21979/27208844-dca00ac2-527a-11e7-8284-e6022b2e4348.png)

**Comment by appleboy** [comment]
@SCKelemen maybe you should try the following solution on Windows.

```go
import "github.com/mattn/go-colorable"

gin.DefaultWriter = colorable.NewColorableStdout()
```

**Comment by NewUserHa** [comment]
the solution works. thanks.

could you make this default in `codes of gin`, or document it in `the tutorial of Github page of gin`? that's better maybe

**Comment by NewUserHa** [comment]
I found `gin will not print color depend on detected TTY`.

but actually at first gin show square in debug log like the pic of first one comment. after using the solution `go-colorable`, it stop print square but still no color. it finally print color by using `gin.ForceConsoleColor()`.

so it detected the TTY, and not print color but do print square.
hope fix.
