### ISSUE TITLE
iota results in missing parameter

### ISSUE THREAD

**Issue by MattNewberry** [gin-gonic/gin#95]
Synopsis: 
When using `iota` to default a const group to a 0 value, and sending a 0 value via a JSON payload, the binding process fails believing the required value is missing.

Schema:

```
const (
    EventTypeEntry = iota
    EventTypeExit
)

Event struct {
        Type      int    `bson:"type" json:"type" binding:"required"`
        Timestamp string `bson:"timestamp" json:"timestamp" binding:"required"`
    }
```

JSON:

```
{
    "events": [
        {
            "timestamp": "2014-08-18T14:03:26.761-0400",
            "type": 0
        }
    ]
}
```

Response:

```
[GIN] 2014/08/18 - 14:08:03 | 400 |     78.894us | 127.0.0.1:52575 POST /v1/events
Error #01: Required Type 
     Meta: Operation aborted
```

**Comment by manucorporat** [comment]
@MattNewberry check out the new validation options: http://godoc.org/gopkg.in/bluesuncorp/validator.v5
Gin now uses that library internally, so you could use:
```go
Event struct {
        Type      int    `bson:"type" json:"type" binding:"min=0,max=2"`
        Timestamp string `bson:"timestamp" json:"timestamp" binding:"required"`
}
```

how does it sounds?

**Comment by nazwa** [comment]
Nicely done with the new form validation. I can't test it any time soon, but do you think this will have any noticeable performance impact on simple forms?

**Comment by manucorporat** [comment]
@nazwa i don't think so, we just added one more branch: `if structField.Kind() == reflect.Struct {`
anyway I just did a performance improvement: 
https://github.com/gin-gonic/gin/commit/967e62337a0c63e445c0efe4e36aa423f3983e4f
