### ISSUE TITLE
Please release the latest version

### ISSUE THREAD

**Issue by djensen47** [gin-gonic/gin#954]
I looks like there has been tons and tons of work done since the last release. Great job everybody!

Would it be possible to get a new version released? There is a lot of incompatibility with 1.14 and it would be great to not have to always use the develop branch.

Thanks!

**Comment by javierprovecho** [comment]
hi @djensen47 , v1.2 was released  few days ago

https://github.com/gin-gonic/gin/releases/tag/v1.2
