### ISSUE TITLE
Routes Hierarchy

### ISSUE THREAD

**Issue by utiq** [gin-gonic/gin#957]
I have this routes:
```go
r.GET("/drivers/price", ctrl.GetDriversPrice)
r.GET("/drivers/:id", ctrl.GetDriver)
```

So when I call http://.../drivers/price, I'm routed to ctrl.GetDriver. How can I make to get routed to ctrl.GetDriversPrice?

**Comment by easonlin404** [comment]
Gin will panic because wildcard route  conflicts with existing route, maybe your code is not like the snippet . Could you post your example code?

<img width="736" alt="2017-06-24 12 00 28" src="https://user-images.githubusercontent.com/8943871/27490276-39186b1e-5870-11e7-8f32-1fcd51538f81.png">

**Comment by utiq** [comment]
Yes, It panics. That's my question about. For example in Ruby On Rails, if those routes are defined
```
r.GET("/drivers/price", ctrl.GetDriversPrice)
r.GET("/drivers/:id", ctrl.GetDriver)
```
if you go to http://.../drivers/price the router will take it as a route and it wont take /price as a wildcard :id

**Comment by nazwa** [comment]
Gin requires routes to be unambiguous.  It's one of the ups and downs of a non regexp based routing.

**Comment by EtienneR** [comment]
Not the best solution but you can use the `strings.EqualFold` function from "strings" package with `c.Request.RequestURI` function for checking the URI.

```go
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"strings"
)

func main() {
	r := gin.Default()

	r.GET("/drivers/:id", GetDriverHandler)

	r.Run(":3000")
}

func GetDriverHandler(c *gin.Context) {
	//fmt.Println(c.Request.RequestURI)
	if strings.EqualFold(c.Request.RequestURI, "/drivers/price") {
		fmt.Fprintf(c.Writer, "GetDriversPrice")
	} else {
		id := c.Param("id")
		fmt.Fprintf(c.Writer, "GetDriversId "+id)
	}
}
````

**Comment by javierprovecho** [comment]
or something like

```go
	// main.go

	r.GET("/drivers/:id", ctrl.GetDriver)

	...

	// ctrl/handlers.go

	func GetDriver(c *gin.Context) {
		if c.Request.RequestURI == "/drivers/price" {
			GetDriversPrice(c)
			return
		}

		...

	}

	...
```

**Comment by ferluk** [comment]
how to use middleware in your solution ?

example:
```
r.GET("/drivers/price", ctrl.GetDriversPrice)
r.GET("/drivers/:id", ctrl.AuthRequired, ctrl.GetDriver)
```

**Comment by ItsLeeOwen** [comment]
@ferluk  it feels like a bummer if you're used to leveraging the order of declared paths, but with gin you can consider flipping the conflicting route.

r.GET("/price/drivers", ctrl.GetDriversPrice)
r.GET("/drivers/:id", ctrl.AuthRequired, ctrl.GetDriver)
