### ISSUE TITLE
REST: Version in Content-Type

### ISSUE THREAD

**Issue by JM2014** [gin-gonic/gin#959]
Hi, I would like to build up with gin a REST-service, where the version of the API will be included in the "Content-Type" of the requests. 
Like: 
# Request
GET http://api.example.com/users/12345
Accept: application/json; version=1
# Response
HTTP/1.1 200 OK
Content-Type: application/json; version=1
{“id”:”12345”, “name”:”Joe DiMaggio”}

What is the best (performance) way, to look for the version in the request with gin?
Is something like v1 := r.Group("/rest/v1") possible?

Thanks
Juergen

**Comment by mysticmode** [comment]
You can use` c.Request.Header["Content-Type"]` which returns `[application/json; version=1]`
