### ISSUE TITLE
how to get gin？

### ISSUE THREAD

**Issue by Rain168** [gin-gonic/gin#960]
go git go get gopkg.in/gin-gonic/gin.v1 ?

When i do like this ,one error happen , operate in china

$ go get gopkg.in/gin-gonic/gin.v1
# cd .; git clone https://go.googlesource.com/net E:\Go\src\golang.org\x\net
Cloning into 'E:\Go\src\golang.org\x\net'...
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Timed out
package golang.org/x/net/context: exit status 128

**Comment by appleboy** [comment]
```
go get github.com/gin-gonic/gin
```

Don't use `gopkg.in` anymore.

**Comment by Rain168** [comment]
ths

**Comment by Rain168** [comment]
@appleboy    go get github.com/gin-gonic/gin
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)


how shoud i do?

**Comment by appleboy** [comment]
please check your network problem.
