### ISSUE TITLE
Logo Guidelines?

### ISSUE THREAD

**Issue by spf13** [gin-gonic/gin#986]
I'd like to print up stickers of the logos of popular Go projects for GopherCon. Is it ok if I print up Gin stickers? I didn't see any guidelines or licensing for the logo. 
Thanks!

**Comment by javierprovecho** [comment]
hi @spf13 !

Thanks for asking about it. Yes, you can do that. I just created a repo for it with an open culture license, check it out here: https://github.com/gin-gonic/logo
